### ISSUE TITLE
[BUG] $resource fill params with data automatically which lead to generating wrong url

### ISSUE THREAD

**Issue by deadmann** [angular/angular.js#14383] opened 2016-04-06 13:10 UTC
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
Service ignore params, and lookup in data, it somehow find a function with same name as my parameter, and attach it to the url parameters... then generate worse url ever. :-1: 
it generate this url: http://localhost:1422/api/AcDocRows/function%20filter()%20%7B%20%5Bnative%20code%5D%20%7DGroupRows
![resourceeeeeeeeeeeeeeee](https://cloud.githubusercontent.com/assets/1919241/14317340/0c084140-fc1d-11e5-80d1-47541e24a063.jpg)
![resourceeeeeeeeeeeeeeee2](https://cloud.githubusercontent.com/assets/1919241/14317836/56fb49fc-fc1f-11e5-8945-ea0a7ffee02b.jpg)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
My Service: 
```
app.factory("AcDocRowService",
    ["$resource",
        function ($resource) {
            //noinspection JSUnusedGlobalSymbols,JSUnusedLocalSymbols
            return $resource("/api/AcDocRows/:id:filter:param1/:param2",
                {
                    id: "@id",
                    param1: "@param1",
                    param2: "@param2",
                    filter: "@filter"
                },
                {
                    "query": {
                        method: "GET",
                        isArray: true,
                    },
                    "get": {
                        method: "GET",
                        isArray: false
                    },
                    "update": {
                        method: "PUT"
                    },
                    "setBookmark":{
                        method: "PUT",
                        params: {
                            param2: "SetBookmark"
                        }
                    },
                    "groupRows":{ //--ISSUE IN HERE
                        method: "POST",
                        isArray: true,
                        params: {
                            param1: "GroupRows"
                        }
                    }
                }
            );
        }
    ]
);
```
_I do not use insert or update, it may also do same thing for them, too. once it enter the 'extractParams' function_

My tries:  -->>Selected item is list of my models.... which i then pass to the service
-AcDocRowService.groupRows({}, $scope.View.SelectedItems).$promise...
-AcDocRowService.groupRows($scope.View.SelectedItems).$promise...

**What is the expected behavior?**
To generate this url:
http://localhost:1422/api/AcDocRows/GroupRows
and send other data as json / form data

**What is the motivation / use case for changing the behavior?**
don't read data in case there is empty object for parameters, and data is set seperatly... don't dig in my data. or provide action flag, to tell service if it should use data to fill the params or not.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
angular 1.4.9 Chrom 49, FF 44 / Windows10.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by Narretz** [comment] 2016-04-06 15:53
Can you please put your code into a plnkr, so that we can run it?

**Comment by deadmann** [comment] 2016-04-07 17:10
the project is so big and require lots of data... and since i work for someone else i cant do that.
but i can say that i need to pass array of objects to my service, and since array it self has filter function, once i enter the section i took screen shot of. the function after found nothing as parameter, search the data it self, and since there is a 'filter' function inside object prototypes, it choose this as a data... i defined several thing for readability, not to fill them all, but it do this on it's own.

i think if you provide an action like: autoAssignParameters (default: true), which later i can set to false, it will solve all issue, i went to do that, but i found i have no access to actions within that method...

**Comment by Narretz** [comment] 2016-04-07 17:57
I'm not asking for the complete project. You already posted your service, and I'm just asking that you create a minimal demo that shows that the incorrect url is generated.

**Comment by Narretz** [comment] 2016-04-07 17:58
You can also open a pull request with the change to resource you would like to see and a test that shows what the change does.

**Comment by deadmann** [comment] 2016-04-07 19:05
it's my hollyday and tomorrow, so i don't have access to my source codes, saturday i try to do that

**Comment by deadmann** [comment] 2016-04-07 20:35
though i had no access, furtunately i could generate the code
![aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa](https://cloud.githubusercontent.com/assets/1919241/14365852/15ec6354-fd25-11e5-8b72-d98738f0a15a.jpg)

don't forget to open your console.

URL: https://plnkr.co/edit/fl7YsprrDcYoeCgA7Uyu?p=preview

**Comment by gkalpak** [comment] 2016-04-08 11:45
You probably didn't post the correct version of the plnkr (or forgot to save it).

Anyway, this can be seen both as a feature and a bug. The problem is that we are looking in the prototype chain as well (not just for own properties) when looking for values on the passed in object.

Since you ask resource to find a property named `filter` on your object and you pass in an Array (which has a `filter()` method on its prototype), this function is used as value for the `filter` parameter (after being stringified).

--
Unfortunately, changing this would be a breaking change. If we decide we want to "fix" it, we could consider it for `v1.6.x`.

The question is: Is this a bug or a feature ?

**Comment by deadmann** [comment] 2016-04-08 13:18
i didn't ask to find, i said i may or may not have a filter, but i didn't said if i do not define it, check the object. cause it will generate a url which won't match with my service...
this is a bug,... btw can you provide fixed version that i can use in my project...


plunker gave me save error, afrer restoring the project.
i put files in here:
app.js:
`var app = angular.module("TestServiceApp", ['ngResource']);`
controller.js
```
app.controller('TestBugsController', ['$scope', 'AcDocRowService', function($scope, AcDocRowService) {
  $scope.greeting = "Hello World";
  
  $scope.View={
    SelectedItems: []
  };
  
  //Normally i should use this instead of "AcDocRowService.groupRows({}, $scope.View.SelectedItems)" because it is a POST method, but i done both
  AcDocRowService.groupRows($scope.View.SelectedItems).$promise.then(
    function(success){
      //Since there is no server there is no data
    },
    function(failed){
      
    });
}]);
```

index.html:
```
<!DOCTYPE html>
<html ng-app="TestServiceApp" ng-controller="TestBugsController" >

  <head>
    <script data-require="jquery@1.9.1" data-semver="1.9.1" src="https://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/mootools/1.4.5/mootools-core-full-nocompat-yc.js" data-semver="1.4.5" data-require="mootools@1.4.5"></script>
    <script data-require="angular.js@1.4.8" data-semver="1.4.8" src="https://code.angularjs.org/1.4.8/angular.js"></script>
    <script data-require="angular-resource@1.4.8" data-semver="1.4.8" src="https://code.angularjs.org/1.4.8/angular-resource.js"></script>
    <link rel="stylesheet" href="style.css" />
  </head>

  <body>
    <h1>Hello Plunker!</h1>






    Test Angular Working:
                <span ng-bind="greeting"></span>
    <script src="app.js"></script>
    <script src="service.js"></script>
    <script src="controller.js"></script>
  </body>

</html>

```
service.js:
```
app.factory("AcDocRowService",
    ["$resource",
        function ($resource) {
            //noinspection JSUnusedGlobalSymbols,JSUnusedLocalSymbols
            return $resource("/api/AcDocRows/:id:filter:param1/:param2",
                {
                    id: "@id",
                    param1: "@param1",
                    param2: "@param2",
                    filter: "@filter"
                },
                {
                    "query": {
                        method: "GET",
                        isArray: true,
                    },
                    "get": {
                        method: "GET",
                        isArray: false
                    },
                    "update": {
                        method: "PUT"
                    },
                    "setBookmark":{
                        method: "PUT",
                        params: {
                            param2: "SetBookmark"
                        }
                    },
                    "groupRows":{ //--ISSUE IN HERE
                        method: "POST",
                        isArray: true,
                        params: {
                            param1: "GroupRows"
                        }
                    }
                }
            );
        }
    ]
);
```

**Comment by deadmann** [comment] 2016-04-09 05:34
**Another Bug:**

while i was tracing i saw u also check for custom url, and i said oh, let's just fix it for now using that...
```
"groupRows":{
                        /**
                         * main url will break due bug within angular-resource 1.4.8
                         * https://github.com/angular/angular.js/issues/14383
                         */
                        url: "/api/AcDocRows/:param1",
                        method: "POST",
                        isArray: true,
                        params: {
                            param1: "GroupRows"
                        }
                    }
```
but  while everythings seem to be good, in the end this url get generated...
http://localhost:1422/api/AcDocRows/GroupRows?filter=function+filter()+%7B+%5Bnative+code%5D+%7D

It attach the filter as a 'query string' parameter :| it mean the service attach unwanted parameter that get filled somehow to the url as query string (BTW, maybe it's not a bug and is a feature if it doesn't dig in object automatically)

**Comment by gkalpak** [comment] 2016-04-09 19:42
> My logic: i didn't ask to find, i said i may or may not have a filter, but i didn't said if i do not define it, check the object.

You are specifying the params as `{filter: '@filter', ...}`. This syntax means: _Look on the data I pass to you for a property named `filter` and use its value for populating the `filter` parameter of the URL.

If that is not what you want, then you need to change your definition.

--
TBH, I don't quite understand the other bug you are describing. I think it's best to provide runable demos of the problems along with a clear explanation of what is the expected behavior and what you get instead.

**Comment by deadmann** [comment] 2016-04-10 12:56
yeah that's what i did for now, i changed it to filter1, so it won't interrupt me

**Comment by gkalpak** [comment] 2016-04-11 08:17
OK, I created the plnkr. You seem to be (sort of) abusing the `parameters` feature in `$resource`. If you don't want all paremeters to be present in all actions' URLs, you shouldn't specify them in the top-level (or you need to make sure you either don't provide them or explicitly overwrite them per action).

If it's just `groupRows` that needs different parameters, you can overwrite them (null them out) there:

```
groupRows: {
  method: 'POST',
  isArray: true,
  params: {
    // id: null,
    // param2: null,
    filter: null,
    param1: 'GroupRows'
  }
}
```

[Updated plnkr][1]

--
I'm going to close this as _won't fix_/_works as expected_. This is working as intended and although the current behavior is not ideal for every usecase, I don't think a marginally better behavior justifies the breaking change.

[1]: https://plnkr.co/edit/GGvnVhgmOLx8gghPhqLm?p=preview

**Closed by gkalpak** 2016-04-11 08:17 UTC
Labels: component: ngResource, frequency: low, needs: breaking change, severity: inconvenient, type: bug

**Comment by deadmann** [comment] 2016-04-16 04:29
ok
