### ISSUE TITLE
Cache eviction of cacheDefault and cacheExpensive in $ParseProvider

### ISSUE THREAD

**Issue by jasmeetjaggi** [angular/angular.js#15925] opened 2017-04-20 02:07 UTC
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [x] other (Please do not submit support requests here (see above))

**Current behavior:**

I am trying to fix memory leaks in our application built on AngularJS.

I see references to some objects i don't expect in memory from cacheDefault.

I see in angular.js there are values added to Maps but never deleted.

In our application we have explicit use of $parse which i think also adds to this.

Interesting observation removing the line that sets values in the map, the heap size seems to be going up at a higher rate. Explanation to that would also be helpful. 

**Expected / new behavior:**

This is more for understanding the internals and the impact of what i am observing

**Minimal reproduction of the problem with instructions:**

**Angular version:** 1.5.8

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 57
**Anything else:**

**Comment by gkalpak** [comment] 2017-04-20 08:58
It is not possible to investigate any possible issues/leaks, but from what description it seems that it is `$parse`'s internal cache, which stores parsed expressions. This allows it to only parse each expressions once. It is expected that these entries remain in the cache, but after some point the size should not increase (unless you keep creating new expressions constantly).

Closing, since this is not actionable. Happy to investigate if you can provide a reproduction of some that looks like unexpected behavior.

**Closed by gkalpak** 2017-04-20 08:58 UTC

**Comment by jasmeetjaggi** [comment] 2017-04-20 17:12
@gkalpak My concern is this cache retains entries for elements that are not even in DOM anymore.
Problems with that is it can lead to unnecessary bloating.

**Comment by gkalpak** [comment] 2017-04-20 20:01
This is intentional (to some degree). For example, if you have a structural directive (`ngIf`, `ngRepeat`, `ngSwitch`), you don't want to re-parse all expressions every time the template is added to the DOM. 

And like I said before, unless you keep introducing new expressions, the size of the cache should stabilize at some point. Do you have a specific usecase where this is not the case?

**Comment by jasmeetjaggi** [comment] 2017-04-20 20:33
I am trying to get a better sense of what is the $parseProvider caching here. Is it just the expression meaning or does angular cache the values itself.
Eg: App has an object of size 100mb and an expression computes to that object. Now this will be held in the cache which is something we are observing and doesnt look like something the framework should be holding reference to. (Perhaps this is while parsing an expression function which refers to this object in closure.)
Also our app is fairly interactive where the elements are added removed from the DOM, so also trying to understand the implication on the cache.

**Comment by gkalpak** [comment] 2017-04-21 10:19
`$parse` can take an AngularJS expression and return a function that receives a `scope` and a `locals` object and evaluates the expression in the context of these objects (this is an oversimplification, but should be enough for our purpose).

So, `$parse('a + b')` will parse the expression and return a function that looks something like (again this is an oversimplification for illustration purposes):

```js
function (scope, locals) {
  var a = locals.a !== undefined ? locals.a : scope.a;
  var b = locals.b !== undefined ? locals.b : scope.b;
  return a + b;
}
```

Parsing the expression and creating the function has some cost, so `$parse` is storing the function, so that it doesn't have to parse `a + b` twice.

##
So, if you have a template like the following:

```html
<div ng-repeat="i in [1, 2, 3, 4, 5]">{{ $index + i }}</div>
```

You will end up with 5 elements which contain the expression `$index + i`, which will result in 5 calls to `$parse('$index + ')`. By caching the parsed expression, `$parse` can immediatelly return the created function after the first call, without having to re-parse the expression and create the function.

##
So, to answer your question, the cached value is a generic function and does not contain any actual data, nor does it reference it via a closure or anything.
