### ISSUE TITLE
Timeout callback can occur in the middle of a digest cycle in Firefox

### ISSUE THREAD

**Issue by pkaminski** [angular/angular.js#10083] opened 2014-11-16 22:10 UTC
It appears that, in Firefox only, certain actions cause it to process the timeout queue on top of the current call stack.  If the current call is in a digest cycle, and a `$timeout` with `invokeApply=true` gets triggered, this results in a `$apply already in progress` error.

See http://plnkr.co/edit/9V1jQSaszbjrt9F5ACjk?p=preview for a repro that uses `window.open` to trigger timeout processing.  If you click on the button you'll see the following sequence in the console:
```
"before window open" script.js:6
"timeout" script.js:5
"Error: [$rootScope:inprog] $apply already in progress
http://errors.angularjs.org/1.3.1/$rootScope/inprog?p0=%24apply
minErr/<@http://code.angularjs.org/1.3.1/angular.js:80:12
beginPhase@http://code.angularjs.org/1.3.1/angular.js:14463:1
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://code.angularjs.org/1.3.1/angular.js:14207:11
timeout/timeoutId<@http://code.angularjs.org/1.3.1/angular.js:15945:25
completeOutstandingRequest@http://code.angularjs.org/1.3.1/angular.js:4842:7
Browser/self.defer/timeoutId<@http://code.angularjs.org/1.3.1/angular.js:5215:7
$scope.click@http://run.plnkr.co/AFImpHzuwgSHuYUW/script.js:7:5
$parseFunctionCall@http://code.angularjs.org/1.3.1/angular.js:12114:15
ngEventHandler/</callback@http://code.angularjs.org/1.3.1/angular.js:22548:17
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://code.angularjs.org/1.3.1/angular.js:14110:16
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://code.angularjs.org/1.3.1/angular.js:14208:18
ngEventHandler/<@http://code.angularjs.org/1.3.1/angular.js:22553:17
createEventHandler/eventHandler@http://code.angularjs.org/1.3.1/angular.js:2979:9
" angular.js:11339

"after window open"
```

Tested on Firefox 33.1.1 in Windows 7 and OS X with Angular 1.3.1, but I've observed the same thing on older versions of both Firefox and Angular so it's not a regression.  I used `window.open` to trigger timeout processing for the repro but I have reason to believe that other operations can do it too.  I haven't seen this happen in Chrome or any other browser.

I don't know the formal spec of `setTimeout` well enough to guess whether this is a bug in Firefox or not, but in either case it seems like something that's worth guarding against in Angular.

**Comment by rwilliams-scottlogic** [comment] 2015-01-28 15:50
This is affecting our application.

We are receiving a bursty flow of messages over a web socket, and handing them to a web worker for (reasonably expensive) processing immediately. Now the general advice is to run anything that comes in to the application in a $rootScope.$apply, but we want to avoid trying to digest 50+ times a second. So when the worker postMessages back to the window with the result, we run some service code outside of $rootScope.$apply and then call a throttled version of $rootScope.$apply to limit our digest rate.

We are seeing in Firefox, that if the throttled function (underscore.js, which uses setTimeout) is scheduled to run but the main thread is busy in a digest at the time, Firefox tries to run the $rootScope.$apply on top of the current call stack - causing the error seen above.

**Comment by petebacondarwin** [comment] 2015-01-28 16:31
@rwilliams-scottlogic - I think you might benefit in your use case from using `$scope.applyAsync`. See http://blog.thoughtram.io/angularjs/2015/01/14/exploring-angular-1.3-speed-up-with-applyAsync.html

**Comment by pkaminski** [comment] 2015-01-29 01:18
@petebacondarwin It looks like `$applyAsync` still uses `setTimeout` (based on the linked article), so it would remain susceptible to this bug.  In my app, I ended up monkeypatching `$digest` and `$apply` to skip the digest if it was already in progress.  I hate messing with deep infrastructure like that but so far it seems to be holding up...

**Comment by gkalpak** [comment] 2015-01-29 07:11
How about `$evalAsync` (which is kind of a "safe $apply") ?

**Comment by lgalfaso** [comment] 2015-01-29 08:21
If multiple threads are executed on the same context, then other things on
top of digest can go wrong. Is there a bug report at Firefox?
>
>

**Comment by rwilliams-scottlogic** [comment] 2015-01-29 09:05
I found a 2006 "resolved incomplete" bug for "Functions registered with setTimeout may be executed in the same stack on MacOS X".

I've opened a new issue for what we are now seeing: https://bugzilla.mozilla.org/show_bug.cgi?id=1127236.

It also appears that "message" event handlers attached to web workers can be run on top of the current call stack, if the main thread is busy when the worker posts a message to the window.

**Comment by rwilliams-scottlogic** [comment] 2015-01-30 12:24
On further investigation, it appears that my "running on top of stack when main thread busy" only happens if the "long running script" warning is triggered. Once it appears, we're in trouble regardless of what the user chooses.

**Comment by lgalfaso** [comment] 2015-01-30 13:06
I move this out of a release until the FF team respond to the bug report

**Comment by rwilliams-scottlogic** [comment] 2015-02-05 17:41
I've updated the BugZilla issue - I don't believe that setTimeout causes an issue unless you're experimenting with breakpoints. The worker onmessage case is an issue, so I renamed that issue's title.

**Comment by ersimont** [comment] 2015-04-04 19:28
(Info from the duplicate issue I filed):

It can definitely cause issues without using breakpoints.  All you need is a $timeout to occur when an alert or confirm popup is open.  Then you get the $apply already in progress error when closing the popup.

Use this to reproduce the issue: http://plnkr.co/edit/gPe7tQyZzC9eCCpsNcqw?p=preview

**Comment by darrenmerrett** [comment] 2015-05-20 12:56
I see that the BugZilla issue hasn't made any progress, but this problem still exists.

The problem does not seem to be limited to popups and alerts. As an example, installing Avira anti virus which injects code into the dom causes this error to occur. The error is random and cannot be replicated accurately, but it is an error none the less.

**Comment by HadrienPierart** [comment] 2015-10-06 17:19
As I mentionned on the Bugzilla of Firefox :
We are running into this issue on Firefox 41 and 40, on Windows and Linux. This generates tons of errors on our production app, only in Firefox. All other browsers work nicely.
This is clearly linked only to Firefox, in which we have digest errors triggered more or less randomly in the app, but reading this topic, pretty much all of them are linked to usages of $timeout...

Is there a workaround or a monkey patch that could be used in Firefox while we wait for a bug fix ?

**Comment by pkaminski** [comment] 2015-10-06 19:07
Here's the patch I use, which makes `$digest` and `$apply` re-entrant.  I doubt the Angular folks will view it favorably but it does fix the problem in the interim.

```
.config(function($provide) {
  // Workaround for https://github.com/angular/angular.js/issues/10083
  $provide.decorator('$rootScope', ['$delegate', '$exceptionHandler',
    function($delegate, $exceptionHandler) {
      var proto = Object.getPrototypeOf($delegate);
      var originalDigest = proto.$digest, originalApply = proto.$apply;
      proto.$digest = function() {
        if ($delegate.$$phase === '$digest' || $delegate.$$phase === '$apply') return;
        originalDigest.call(this);
      };
      proto.$apply = function(fn) {
        if ($delegate.$$phase === '$digest' || $delegate.$$phase === '$apply') {
          try {
            this.$eval(fn);
          } catch(e) {
            $exceptionHandler(e);
          }
        } else {
          originalApply.call(this, fn);
        }
      };
      return $delegate;
    }
  ]);
})
```

**Comment by HadrienPierart** [comment] 2015-10-06 19:20
Ok, yes I see that you use the [safeApply](http://siongui.github.io/2013/04/04/angularjs-safe-scope-apply/) approach to mitigate the bug. I was wondering if there was any other solution. But your decorator way is pretty neat.

Wouldn't it be better to apply this monkey patch, ONLY in Firefox though ?

Thx for the code !

**Comment by pkaminski** [comment] 2015-10-06 19:26
You could certainly restrict it to just Firefox -- I decided in favor of having all my clients running as similar code as possible.

**Comment by HadrienPierart** [comment] 2015-10-06 19:29
Fair enough. For now, I'll start by trying it out only on FF to see if the mountain of related bug reports we have goes away, and then I'll see to extending it.

Thx !

**Comment by royaldark** [comment] 2016-03-08 05:54
Spent a couple hours tonight tracking down a "$apply already in progress" error tonight, and discovered I was being bit by this issue. Somewhat amazingly, I have a consistent reproduction, but unfortunately it is on a local dev build.

This is an especially hard-to-track bug because Firefox mangles the call stack, making it appear as though the error was caused by a synchronous call to the `$interval/tick()` function, when in fact `tick()` is the top of the stack. Obviously this is not Angular's problem, but that's a taste of the insanity encountered in tracking this down.

Short of using a workaround like @pkaminski provided, is there a recommended solution? It doesn't seem any progress is being made on the Bugzilla issues, but I'm at a point now where I can't even develop my Angular app in Firefox because of this issue.

**Comment by gkalpak** [comment] 2016-06-01 10:53
Unfortunately, this is still an issue in Firefox 46. Being reproducible without Angular though, this is a Firefox bug, that we can't do much about.

I'll close this since there is already a bug report for Firefox.

**Closed by gkalpak** 2016-06-01 10:53 UTC
Labels: browser: Firefox, component: misc core, frequency: low, needs: investigation, severity: broken expected use, type: bug
