### ISSUE TITLE
header changing not affect $http cache

### ISSUE THREAD

**Issue by zhangxin511** [angular/angular.js#13875] opened 2016-01-28 17:30 UTC
We have a web api call:
 return this.$http({
            method: 'GET',
            url: this.webApiEndpoints.RefTraderGetUrl,
            cache: true,
            headers: operationHeader||{}
        })

The result been cached for the first time (operationHeader is undefined at first time) it been called. However, later when operationHeader become a real header object, the http call is still using the result been cache. It should not behavior like this since the header changed, correct?

**Comment by zhangxin511** [comment] 2016-01-28 17:48
I read some articles online, "the url specified on the $http configuration object is used as the key for the cached value. ", so even if I change data the response will not respect the data change, is this true?

**Comment by gkalpak** [comment] 2016-01-28 18:06
@zhangxin511, indeed the key used to store/retrieve a response is based on the URL of the request. Note that this is not necessarily the URL passed in the `config.url`, but the result of serializing and appending `config.params` (based on the chosen `paramSerializer`) to `config.url`.
But the headers are not taken into account.

Not sure what you mean by `data`, but keep in mind that **only** `GET`/`JSONP` requests are cacheable.

**Comment by Narretz** [comment] 2016-01-28 18:16
Duplicate of https://github.com/angular/angular.js/issues/5028

**Closed by Narretz** 2016-01-28 18:16 UTC
Labels: component: $http, severity: broken expected use, type: feature
