### ISSUE TITLE
Uncaught ReferenceError: Node is not defined

### ISSUE THREAD

**Issue by minchopm** [angular/angular.js#15329] opened 2016-10-28 20:53 UTC
Hi, I all versions after 1.5.0 I am getting 
Uncaught ReferenceError: Node is not defined
because the check for Node is not correct. Please update in next version that line: 
var jqLiteContains = Node.prototype.contains || function(arg) { 
to 
var jqLiteContains = Node && Node.prototype.contains || function(arg) {

**Comment by gkalpak** [comment] 2016-10-29 08:55
This is a duplicate of #13391 and #13442 (more details can be found there).
This has been fixed in #14345 and the fix will be available in the upcoming 1.5.9 release (but you still need to ensure that `Node` will be available on `window`).

**Closed by gkalpak** 2016-10-29 08:55 UTC
