### ISSUE TITLE
Edit in Plunker link should be opened in new tab.

### ISSUE THREAD

**Issue by shyamji1983** [angular/angular.js#13819] opened 2016-01-22 09:33 UTC
Edit in Plunker link should be opened in new tab. Or user anchor, so user can be able to open links in new tab through right click / ctrl + click etc.

**Comment by Narretz** [comment] 2016-01-22 10:21
Dupe of https://github.com/angular/angular.js/issues/8328. I'm working on that. Anchor is not possible, because the plnkr url doesn't exist yet - it's created on-the-fly via the plnkr api.

**Closed by Narretz** 2016-01-22 10:21 UTC
