### ISSUE TITLE
ngModel bound to select doesn't update to second value when using keyboard

### ISSUE THREAD

**Issue by kustnodi** [angular/angular.js#12562] opened 2015-08-12 14:14 UTC
I've got a select element bound to a model in an angular view. When filling out the form with the keyboard, I noticed that if you down arrow to the second option the value, the model still represents the first value. This only happens when using the keyboard to fill out the form.

Set up is pretty simple, using angular 1.4.3 ([plunker](http://plnkr.co/edit/Hiu67NTR3Gpk9jByZtQD)):

Script:

    var app = angular.module('app', []);

    app.controller('myController', function() {
      var vm = this;

      vm.options = [{
        Id: 1,
        Value: 'A'
      }, {
        Id: 2,
        Value: 'B'
      }, {
        Id: 3,
        Value: 'C'
      }]
    });

Markup:
    <script src="https://code.angularjs.org/1.4.3/angular.js"></script>

    <body ng-app="app">
      <div ng-controller="myController as ctrl">
        <p>
          Model is not updated on second down button push. Repro:
          <ol>
            <li>Tab to select element</li>
            <li>Hit down and notice the optionId updated to 1</li>
            <li>Hit down again and notice that the displayed value changes to B, but optionId stays as 1</li>
            <li>Hit down again and notice that the displayed value changes to C, and optionId changes to 3</li>
            <li>Hit up and notice that displayed value changes to B, and optionId changes to 2</li>
          </ol>
          Why doesn't the optionId = 2 on the initial selection of B
        </p>
        <select id="mySelect" ng-options="item.Id as item.Value for item in ctrl.options" ng-model="ctrl.optionId" style="width:200px">
        </select>
        <div><strong>optionId: {{ctrl.optionId}}</strong>
        </div>
      </div>
    </body>

**Comment by Narretz** [comment] 2015-08-13 18:34
This is a dupe of https://github.com/angular/angular.js/issues/9134. Unfortunately, it's a chrome bug and we cannot really do a lot about this.

**Closed by Narretz** 2015-08-13 18:34 UTC

**Comment by kustnodi** [comment] 2015-08-13 23:40
Sorry I didn't see the other threads first.  FF doesn't update the model at all which according to the thread you posted is following the spirit of the spec.  Three browsers, three different behaviors, feels like the old days.  Thanks
