### ISSUE TITLE
ng-messages no longer interprets its attribute value properly

### ISSUE THREAD

**Issue by davidwalschots** [angular/angular.js#11616] opened 2015-04-16 12:57 UTC
In order to minimize the amount of html needed for validation, at our office, we created a directive on top of ng-messages. Sadly, moving from 1.4.0-beta.4/angular-messages.js to 1.4.0-beta.5/angular-messages.js (and later version). Our code no longer works.

The error is as follows:
```
Syntax Error: Token '{' invalid key at column 2 of the expression [{{::messages.fullFieldName}}.$error] starting at [{::messages.fullFieldName}}.$error].
```

The template for this directive is as follows:

```html
<div class="validation-message" ng-messages="{{::messages.fullFieldName}}.$error" ng-show="{{::messages.fullFieldName}}.$invalid && !{{::messages.fullFieldName}}.$pending && ({{::messages.formName}}.$submitted || {{::messages.fullFieldName}}.$touched)">
  <div ng-transclude></div>
</div>
```

The directive is defined as follows:
```javascript
function indMessages() {
    var controller = function ($element) {
      var vm = this;
      var form = $element.inheritedData('$formController');

      // Unfortunately required controllers are not injectable into our own controller, only into our link function.
      // Here's a solution, feels a bit hacky but nicer than creating a link function just for this; based on: http://stackoverflow.com/a/21252383/198797; also used in core angular code: https://github.com/angular/angular.js/blob/adcc5a00bf582d2b291c18e99093bb0854f7217c/src/ng/directive/input.js#L1614
      vm.formName = form.$name;
      vm.fullFieldName = vm.formName + '.' + vm.fieldName;
    }

    controller.$inject = ['$element'];

    return {
      restrict: 'E',
      require: '^^form',
      templateUrl: '/views/templates/ind-messages.html',
      bindToController: {
        fieldName: "@for"
      },
      controllerAs: 'messages',
      transclude: true,
      replace: true,
      scope: true,

      controller: controller
    };
  }
```

Is the above due to a programming error on our part? Or was there a change with unexpected side-effects inside the angular-messages.js code?

**Comment by Narretz** [comment] 2015-04-21 09:55
Can you please provide a runnable example inside a plnkr or jsfiddle? Thanks!

**Comment by davidwalschots** [comment] 2015-04-22 12:27
Of course! It can be found here: http://plnkr.co/edit/p1bHusDA7ZyXhuW9Ymz9

**Comment by gkalpak** [comment] 2015-04-22 13:17
You could make it work by changing `ng-messages="{{::messages.fullFieldName}}.$error"` to ng-messages="::this.$eval(messages.fullFieldName+'.$error')"` ([updated Plnkr][1]), but I am not sure this is a nice solution.

[1]: http://plnkr.co/edit/Qivd7mxkcndmml31LKSY?p=preview

**Comment by singhsays** [comment] 2015-05-20 10:30
I'm seeing this issue are well. No custom directive or anything, just plain vanilla ng-messages. It seems to me, that the ng-messages directive no longer interpolates the ng-messages and for attribute values.

Demo:
http://jsfiddle.net/singhsays/m06jeth1/ (works fine with 1.3.15, upto 1.4.0-beta.4)
http://jsfiddle.net/singhsays/oq473qyq/ (same code, stopped working at 1.4.0-beta.5)

**Comment by tkrotoff** [comment] 2015-06-01 19:33
+1, I have the same problem

**Comment by sravenhorst** [comment] 2015-06-01 21:31
This issue is basicly this:

in Angular 1.4.0.beta.4 the ngMessages/for attribute were read in the (post)link function. Here the "dynamic" value was already parsed before read in the (post)link.

In later Angular 1.4.X versions, the value in the ngMessages/for attribute is already read in the controller function, where the attribute isn't parsed yet.

@Narretz, as you set the status of this issue:
The solution would be to link the ngMessages/for attributes through bindToController so it's parsed before read.
I hope enough info is applied to pick this up.

A workaround we've introduced for now in our app, is something like you find in this fiddle: http://jsfiddle.net/m06jeth1/20/

So basicly: we added a custom directive to set the "for" attribute dynamicly. 
But as said: this is a workaround and i hope the real issue will be solved within angular-messages.js.

Groet,
Sander

**Comment by tkrotoff** [comment] 2015-06-17 23:18
@sravenhorst Your jsfiddle (http://jsfiddle.net/m06jeth1/20/) is missing something: it never displays "This is a required field"

**Comment by patrickjuchli** [comment] 2015-07-03 20:29
I have the same issue, until then:

    ng-messages="this[messages.fullFieldName].$error"

works, too.

**Comment by tkrotoff** [comment] 2015-10-07 16:45
Here another demo that shows the regression: http://plnkr.co/edit/BOYfaF?p=preview

Personally, I dynamically patch AngularJS using the `postinstall` step of Node.js:

File patches/angular-messages-#12001.diff (created with diff -u):
```Diff
--- ../node_modules/angular-messages/angular-messages.js
+++ ../node_modules/angular-messages/angular-messages.js
@@ -325,8 +325,13 @@
      var INACTIVE_CLASS = 'ng-inactive';

      return {
-       require: 'ngMessages',
        restrict: 'AE',
+       bindToController: {
+         ngMessages: '@',
+         forAttr: '@for'
+       },
+       scope: true,
+       controllerAs: 'ngMessagesController',
        controller: ['$element', '$scope', '$attrs', function($element, $scope, $attrs) {
          var ctrl = this;
          var latestKey = 0;
@@ -392,7 +397,7 @@
               : $animate.setClass($element, INACTIVE_CLASS, ACTIVE_CLASS);
          };

-         $scope.$watchCollection($attrs.ngMessages || $attrs['for'], ctrl.render);
+         $scope.$watchCollection(ctrl.ngMessages || ctrl.forAttr, ctrl.render);

          this.reRender = function() {
            if (!renderLater) {
```

File package.json:
```JSON
  "dependencies": {
    "angular": "~1.4",
    "angular-messages": "~1.4"
  },
  "scripts": {
    "patch": "for i in patches/*.diff; do patch -p1 < $i; done",
    "postinstall": "npm run patch",
  }
```

This way I can easily change my version of AngularJS and include other patches if needed instead of waiting for a new release (this regression is 6 months old...).

**Comment by Narretz** [comment] 2015-10-07 20:54
I know there's a PR open for this, which needs some improvement. Would you like to give it a shot @tkrotoff?

**Comment by tkrotoff** [comment] 2015-10-07 21:01
@Narretz I've looked at the PR but I don't have the knowledge to "fix" it

**Comment by Narretz** [comment] 2015-10-08 15:43
I had a look at this, and I'm not really sure anymore that this is (a) a regression and (b) something that really makes sense - I can definitely see the use, but the semantics are a bit more complicated.

For (a), it's not been documented that you can interpolate the ngMessages collection. And (b), interpolating inside an expression before it is evaluated is not something Angular really advocates. For example, if interpolating the expression were possible, wouldn't you expect that ngMessages picks up this change? For example, you have `ng-messages="{{collectionName}}"` and you decide later on that you want to use a different set of message keys ( for whatever reason).
In the patch, and before, this change wouldn't be picked up, because the watchCollection would settle down to watch the expression with the result of the first interpolatio.

I see that in the examples, the collection name would probably never change, but it's also questionable if we should support a case that's not really angular like, i.e. having interpolation inside another expression. I'd like to hear what others think about this. @matsko wdyt?

**Comment by Narretz** [comment] 2015-10-08 15:57
To solve this issue, I would simply move the logic of assembling the path to the collection into the directive controller: http://plnkr.co/edit/u6XUZbHr2vUcdQGfe0IM?p=preview

**Comment by JohnColvin** [comment] 2015-10-08 17:15
@Narretz thanks for example. It helped me convert a directive that had this issue. :tada:

**Comment by petebacondarwin** [comment] 2015-11-02 20:02
I agree with @Narretz here. I think that this is not something that we should support. We definitely do not encourage interpolation in attributes of directives that expect an expression.

**Comment by Narretz** [comment] 2015-11-02 20:49
Okay, I'll add a note then to the changelog & the migration docs, and close this afterwards.

**Comment by petebacondarwin** [comment] 2015-11-02 22:56
Thanks!

**Closed** 2015-11-06 16:18 UTC
Labels: branch: 1.4.x, branch: 1.5.x, component: ngMessages, severity: regression, type: bug

**Comment by brauliodiez** [comment] 2015-11-07 19:47
About both solutions proposed, I have tried adding two validations (required and minlength), and it always displays the required text message (you never get the minLength one).

```html
      <input ind-input type="text" 
      name="testField" ng-model="testField" required
      ng-minlength="10"/>
      
      <ind-messages for="testField">
        <div ng-message="minlength">min length.</div>
        <div ng-message="required">Fill in the text field.</div>
      </ind-messages>
```

Plunkr based on @Narretz proposal

http://plnkr.co/edit/iglDLJix6I0m7uxK9Bgm?p=preview

Plunkr based @gkalpak proposal

http://plnkr.co/edit/WsRl8mb3OneFQUEG5jwa?p=preview

I'm doing something wrong or missing something?

**Comment by gkalpak** [comment] 2015-11-07 20:05
In contrast to `minlength`, `ngMinlength` expects an Angular expression (not a literal value).
In order for your example to work, you should replace `ng-minlength="10"` with either:

1. `minlength="10"` ([updated plnkr][1]) or
2. `ng-minlength="'10'"` ([updated plnkr][2])

[1]: http://plnkr.co/edit/PBZzw0O1rqGQs14X4KLP?p=preview
[2]: http://plnkr.co/edit/vAVl4CDucMyldcnrBqjg?p=preview

**Comment by brauliodiez** [comment] 2015-11-07 20:19
Ouch, sorry about that.

**Comment by mohitadwani** [comment] 2015-11-17 10:06
In which version will this be released?

**Comment by petebacondarwin** [comment] 2015-11-17 10:38
@mohitadwani - will what be released?

**Comment by mohitadwani** [comment] 2015-11-17 10:47
@petebacondarwin the code resolving this issue. In which version will this be released and when ?

**Comment by petebacondarwin** [comment] 2015-11-17 11:04
There is no code resolving this issue. 
The only related commit is https://github.com/angular/angular.js/commit/aff74ec87bd31933565b76cd0ab0b988cd9bae21, which contains only documentation of the issue and why this issue will not be fixed.

**Comment by mohitadwani** [comment] 2015-11-19 04:55
@petebacondarwin Sorry, I hadn't checked it properly. Thanks

**Comment by tkrotoff** [comment] 2015-12-02 14:25
@petebacondarwin 
> this is not something that we should support

@Narretz 
>  I would simply move the logic of assembling the path to the collection into the directive controller

You are saying that ng-messages should not support things like "form{{$index}}..." anymore while ng-show (and probably other directives) does => seems unlogical to me.

Interesting part (simplified for readability) from the [plunker](http://plnkr.co/edit/BOYfaF?p=preview) given in my [comment above](https://github.com/angular/angular.js/issues/11616#issuecomment-146258675):

```HTML
<form name="form{{$index}}"
      ng-repeat="participant in Participants.list">

  <input name="name" required
         ng-model="participant.name">

  <span ng-messages="form{{$index}}.name.$error" // <= not working anymore since 1.4
        ng-show="form{{$index}}.name.$invalid">
    <span ng-message="required">Cannot be empty</span>
  </span>
</form>
```

**Comment by petebacondarwin** [comment] 2015-12-02 14:49
I don't think we should support it in `ng-show` either but it happens to work. In my view this is too many levels of indirection.

In any case you can achieve what you want, as discussed earlier in this issue with:

```html
<span
    ng-messages="this['formParticipant' + $index].name.$error"
    ng-show="this['formParticipant' + $index].name.$invalid"
    class="help-block">
```

See http://plnkr.co/edit/ba09QK?p=preview

**Comment by tkrotoff** [comment] 2015-12-02 14:53
Cool, thx. I was afraid to have to implement a new directive like given in a [comment above](https://github.com/angular/angular.js/issues/11616#issuecomment-146590968).

**Comment by rhclayto** [comment] 2016-05-21 07:09
How then do you make this work without {{}} syntax when you are dynamically generating fields & field names with ng-repeat, not when dynamically generating *form names*, as in the examples I have seen up till now?

For instance, this plunker works with a manually defined field name attribute in ng-message: http://plnkr.co/edit/Wswcbu?p=preview

However, doing something as in this plunker does not work: http://plnkr.co/edit/L3iyZE?p=preview

This would be easy with the ability to use the {{}} interpolation syntax, but without it I am unsure of how to accomplish this. All examples I have seen involve doing something like `ng-messages="this['formParticipant' + $index].name.$error"`, but don't address the case of dynamic field names.
