### ISSUE TITLE
Animations don't work when element is added with $animate.enter (vs. $element.append) in angular 1.3

### ISSUE THREAD

**Issue by connec** [angular/angular.js#10033] opened 2014-11-13 01:25 UTC
I have written a directive that `$compile`s and appends child directives to itself.

If I append the child using `$element.append` then everything works as expected.

If, however, I append the child using `$animate.enter`, then animations on elements in the child do not work at all (by which I mean `ng-hide-add`-esque classes are never added).  This issue did not occur with angular 1.2(.17).

I've tried (and failed) to make a minimal test case [here](http://jsfiddle.net/416fktbx/2/), which includes the broad functionality of the parent template (compiling a template, adding the element to itself) and the child template (showing/hiding some text when a link is clicked).  This currently works as expected, regardless of whether `$animate.enter` or `$element.append` is used.

Do you have any suggestions on where I could look for the source of the problem?

**Comment by Narretz** [comment] 2015-12-01 17:30
Closing because we never had a reproduction :(

**Closed by Narretz** 2015-12-01 17:30 UTC
Labels: component: ngAnimate, needs: investigation, severity: confusing
