### ISSUE TITLE
input[email] incorrectly claims address with IPv6 address literal is invalid

### ISSUE THREAD

**Issue by baryluk** [angular/angular.js#16599] opened 2018-06-12 23:00 UTC
FYI. I am not angular user, but I found in docs, that there is a bug.

https://docs.angularjs.org/api/ng/input/input[email]

`xyz@[IPv6:2001::1]`

should validate as correct.

Please see https://tools.ietf.org/html/rfc5321#section-4.1.3 and section 4.1.2 and 4.1.3

**Comment by baryluk** [comment] 2018-10-04 01:44
Fully agree this is not critical and lowish priority. I do use emails with IPv6 literals sometimes tho, i.e. I have a mini monitoring system that is using email to send some notifications around, as it is workable distributed queueing (pub/sub) system, that require no additional work from me, and I want monitoring to work reliably even when DNS is down, and without access to other infrastructure (or public internet).

**Comment by Niladri24dutta** [comment] 2018-10-09 21:04
@gkalpak CAn I submit a PR for this with the updated documentation? I think only the format needs to be updated for this.

**Comment by petebacondarwin** [comment] 2018-10-10 13:46
A docs pull request would be accepted.

**Comment by mgol** [comment] 2018-10-11 14:59
Note that even the native `<input type="email">` in Chrome doesn't recognize the provided address as valid: https://jsfiddle.net/Lnm3kj64/

**Comment by Niladri24dutta** [comment] 2018-10-11 16:09
@mgol yes I noticed that too, so before creating the PR for this I wanted to be sure is this behavior by design for HTML5 and angular

**Comment by mgol** [comment] 2018-10-11 21:08
I looked at the HTML spec and at the [`input[type="email"]` section](https://html.spec.whatwg.org/#e-mail-state-(type=email)) it says:
> The value attribute, if specified and not empty, must have a value that is a single valid e-mail address.

The "valid e-mail address" text links to [the definition of a valid e-mail address](https://html.spec.whatwg.org/#valid-e-mail-address) where it even (in a non-normative part) defines a JS-compatible regex for checking the value. This regex rejects IPv6 emails like the one in the original post here.

Taking that into account as well as our imminent feature freeze I think we shouldn't diverge from the standard here and just document the limitation, mentioning that native inputs behave in the same way.

As we're not going to actually fix this issue, I'm moving it to the "Won't fix" milestone. We would still accept a docs contributions explaining the situation.

**Comment by mgol** [comment] 2018-10-11 21:16
I reported an issue to the HTML standard repo: https://github.com/w3c/html/issues/1638

**Comment by Niladri24dutta** [comment] 2018-10-12 08:01
@mgol Is it fine if I add the limitation regarding this in the documentation as a PR(the default HTML5 behavior )

**Comment by mgol** [comment] 2018-10-12 08:08
Yes, definitely!

**Comment by mgol** [comment] 2018-10-12 08:10
I re-submitted the issue to WHATWG, I erroneously submitted it to the W3C HTML standard first. Here it is: https://github.com/whatwg/html/issues/4089

**Comment by Niladri24dutta** [comment] 2018-10-12 17:42
@mgol I am adding it under the `note` of the "Overview" section in this page https://docs.angularjs.org/api/ng/input/input%5Bemail%5D. Let me know if it's fine.

**Comment by mgol** [comment] 2018-10-15 08:52
@Niladri24dutta Yes, I think an additional `Note` section there would be fine.

**Closed** 2019-01-21 14:41 UTC
Labels: PRs plz!, component: forms, type: feature
