### ISSUE TITLE
Expose `require`d controllers to a directive's controller

### ISSUE THREAD

**Issue by abyx** [angular/angular.js#13041] opened 2015-10-07 19:58 UTC
Currently you use controllers on directives to expose functionality. Then other directives use those controllers by supplying `require` and getting the controllers in the `link` function.

This feels asymmetric and a more natural way would be to allow the injection of required controllers to the directive's controller as well. That would mean that for a lot of use cases would could simply write directives with just the `controller` function and no need to pass it awkwardly from `link` to `controller`.

I was thinking about something like providing a `$requires` injectable for directive controllers that is basically an object, like `$routeParams`, from controller name to controller object.

If that sounds reasonable I'll work on a pull request.

**Comment by gkalpak** [comment] 2015-10-07 20:49
Duplicate of #5893 and #12989.
Closing, since #5893 has more context/discussion.

<sub>(There is also PR #6040 addressing this, but it's too old now.)</sub>

**Closed by gkalpak** 2015-10-07 20:49 UTC
