### ISSUE TITLE
Bug on $httpBackend mock with promise chain

### ISSUE THREAD

**Issue by fantarama** [angular/angular.js#15850] opened 2017-03-22 14:30 UTC
Code to reproduce the issue:

Controller:
```javascript
function MyController() {
    var vm = this;
    function fetch() {
        return $http.get("mytestservice").then(function(response) {
            //do something            
            return response;
        });
    }

    vm.publicFetch() {
        fetch().then(function() {
            vm.mode= 'fetch';
        }
    }
}
```
Test:
```javascript
describe("MyController", function () {
    it("should fetch data", inject(function ($controller, $httpBackend) {
        var ctrl = $controller("MyController");
        $httpBackend.expectGET("mytestservice").respond(200);
        ctrl.publicFetch();
        $httpBackend.flush();
        expect(ctrl.mode).toBe("fetch");
    }
}
```
On Angular 1.6.3 the **test fail** because the chained promise on `publicFetch `function is rejected, and ctrl.mode is undefined but the $http promise is resolved.

If I remove the chained promise (the then callback on $http.get) the test work.

**Comment by frederikprijck** [comment] 2017-03-22 14:42
This seems to work for me: https://plnkr.co/edit/zJaMjrL6Eg0u6Mkp31Al?p=preview

Note: Your code has a lot of typo's, I needed to do quite some work to get it running. If you still think there's a bug, please update the plunkr to reproduce your issue.

**Comment by fantarama** [comment] 2017-03-22 15:03
Code updated https://plnkr.co/edit/CZwgZwygxQdADil4YKLN?p=preview

The only part missing was the $onInit that call the private fetch. On plunkr jasmine fail with "unexpected GET error" but in my karma run the same code fail with error mentioned above, the $http promise is rejected. Removing the $onInit call it work.

**Comment by frederikprijck** [comment] 2017-03-22 15:07
You're executing the Http request multiple times. Why are you adding `$onInit` to a controller which does not belong to a `component` ?

And why are you trying to call `$http.get` with the same params twice ?

The error I'm seeing is:

> Error: Unexpected request: GET mytestservice
No more request expected

Which is normal and easy to fix by declaring a second `expectGet` like so: https://plnkr.co/edit/qr157z6x7miNJbTk7s4u?p=preview

**Comment by fantarama** [comment] 2017-03-22 15:13
The code is extracted from the more complex component controller. the public fetch function is called after a user interaction that need data update.

The jasmine error on plunkr is clear and simple to resolve, but same test with karma do not throw the GET expection but resolve the second call with `Error {}`.

Is there some test behavior that produce the issue?

**Comment by frederikprijck** [comment] 2017-03-22 15:15
It's extremely difficult for us to help you without a reproduction sample. It might be a better idea to move this discussion to any of the channels mentions [here](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question), as github issues are reserved for bug reports and feature requests..

**Comment by fantarama** [comment] 2017-03-22 15:43
If can help Karma version is 0.13.22 with Jasmine 2.4.1.

**Comment by Narretz** [comment] 2017-03-23 07:09
I agree with @frederikprijck that the current example code is insufficient. When the problem happens with a component, you should use a component and not a regular controller.

**Comment by Narretz** [comment] 2017-03-29 13:07
I'm going to close this issue because we have no reproduction of the issue. Feel free to reopen this issue if you can provide a reproduction (ideally a runnable demo in a [Plunker](https://plnkr.co) or similar. You can use this [Plunker Template](http://plnkr.co/edit/tpl:yBpEi4)).

**Closed by Narretz** 2017-03-29 13:07 UTC
Labels: component: ngMock, needs: more info

**Comment by paveleremin** [comment] 2018-01-18 15:04
@frederikprijck did you find a solution?

**Comment by frederikprijck** [comment] 2018-01-18 15:08
@paveleremin A solution for what ?

**Comment by paveleremin** [comment] 2018-01-18 15:11
@frederikprijck for current issue

**Comment by paveleremin** [comment] 2018-01-18 15:24
I get 2 errors
```
ERROR: Error{}
ERROR: 'Unhandled promise rejection', Error{line: 142, sourceURL: 'http://localhost:9876/base/karma.entry.js?0971cc365afeb23d6e3577f2b33fc452ffd65079', stack: 'oe@http://localhost:9876/base/karma.entry.js?0971cc365afeb23d6e3577f2b33fc452ffd65079:142:81
run@http://localhost:9876/base/karma.entry.js?0971cc365afeb23d6e3577f2b33fc452ffd65079:18029:29
http://localhost:9876/base/karma.entry.js?0971cc365afeb23d6e3577f2b33fc452ffd65079:18042:33
flush@http://localhost:9876/base/karma.entry.js?0971cc365afeb23d6e3577f2b33fc452ffd65079:18260:11'}
```
```
FAILED TESTS:
    × load items
      PhantomJS 2.1.1 (Windows 8 0.0.0)
    Error: No pending request to flush ! in karma.entry.js (line 122337)
    flush@karma.entry.js:122337:76
    karma.entry.js:123353:27
    loaded@http://localhost:9876/context.js:1891:17
```
for this simple code:
```
it('load items', () => {
    $httpBackend.flush();
});
```

I'm OK with 2nd and what about 1st?
```
$qProvider.errorOnUnhandledRejections(false);
```
didn't helped for me

**Comment by frederikprijck** [comment] 2018-01-18 15:25
I think you confused me with the OP, I didn't have any issue.

Also, please read: https://github.com/angular/angular.js/issues/15850#issuecomment-288420345
