### ISSUE TITLE
ngModel getterSetter is called before validity has been checked when allowInvalid is true

### ISSUE THREAD

**Issue by s100** [angular/angular.js#15930] opened 2017-04-21 10:54 UTC
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

I have a [custom `ng-model` input](https://plnkr.co/edit/7vlNRDgF7q647O0sO0Xf?p=preview) which uses a getter-setter and allows invalid values:

```html
<custom-input ng-model="value" ng-model-options="{
  allowInvalid: true,
  getterSetter: true
}"></custom-input>
```

When the value of the model is changed using `$setViewValue()`, the getter-setter is called. Inside the getter-setter, I inspect the `ng-model` to see which errors, if any, are present. However, it seems that the validators are not called until *after* this, so I see a stale result. E.g. if the value has just been changed to something which should be invalid, no errors can be found until e.g. the next digest cycle.

[Documentation for `$setViewValue()`](https://docs.angularjs.org/api/ng/type/ngModel.NgModelController) states "If there are no special `ngModelOptions` specified then the staged value is sent directly for processing through the `$parsers` pipeline. After this, the `$validators` and `$asyncValidators` are called and the value is applied to `$modelValue`. Finally, the value is set to the **expression** specified in the ng-model attribute and all the registered change listeners, in the `$viewChangeListeners` list are called." In other words, validation should be performed *before* the getter-setter is called.

I admit that `allowInvalid` may constitute a "special `ngModelOption`", but it is not called out in later paragraphs, whereas `updateOn` and `default` are, so I would expect the regular behaviour.

**Expected / new behavior:**

For my use case I would prefer it if validation is always performed before the getter-setter is called, even if `allowInvalid` is `true`.

Alternatively (this is not my preferred solution) it would at least be nice to call out this special behaviour in the documentation.

**Minimal reproduction of the problem with instructions:**

[Here](https://plnkr.co/edit/7vlNRDgF7q647O0sO0Xf?p=preview). Click the button to see the behaviour. I think the two Booleans should be identical.

**Angular version:** seen in 1.5.11 but the code in question is still there in 1.6.x

**Browser:**  Chrome 57 on Windows 7 but likely not platform-related

**Anything else:**

I think the code to be changed is [here](https://github.com/angular/angular.js/blob/2931a6df034ad0b93b24718e86814e4592ade43e/src/ng/directive/ngModel.js#L741-L757).

**Comment by Narretz** [comment] 2017-04-21 11:20
Hi, thanks for the report. I think this is essentially a duplicate of https://github.com/angular/angular.js/issues/14043 - ngChange / ngModel setter are called at the same time. Changing this now could be a pretty big breaking change, as we would delay the model update for async validators. A new API probably needs to be introduced.

**Closed by Narretz** 2017-04-21 11:20 UTC

**Comment by s100** [comment] 2017-04-21 12:41
Any plans to at least update the documentation to indicate this special case? It really caught us out.

**Comment by Narretz** [comment] 2017-04-21 13:45
@s100 not at the moment - do you want to send a PR?
