### ISSUE TITLE
Bug using ngForm and ngRepeat on the same node

### ISSUE THREAD

**Issue by kwypchlo** [angular/angular.js#12561] opened 2015-08-12 13:11 UTC
consider this example:

```
<table ng-controller="TestController as ctrl">
    <tbody>
        <tr ng-repeat="person in ctrl.people" ng-form="testForm">
            <td>{{ person.name }}</td>
            <td><button type="button" ng-click="ctrl.remove($index)"></button></td>
        </tr> 
    </tbody>
</table>
```

```
function TestController() {
    this.people = [
        {name: 'John'},
        {name: 'Dorothy'},
        {name: 'Charles'}
    ];

    this.remove = function(index) {
        this.people.splice(index, 1);
    }
}
```

Using remove button fires up the remove function from the controller, removes one person from the `people` collection but the row remains displayed, yet without any data. Removing `ngForm` directive from the `<tr>` that has `ngRepeat` resolves the issue, however I need that `ngForm` there in my case :)

I couldn't get a fiddle or codepen working, dunno why but the example should be simple enough. Tested on 1.4.1 but haven't seen any changes since then in changelog that could suggest it was fixed anyhow.

**Comment by Narretz** [comment] 2015-08-12 13:48
This is a dupe of #12161. I hope we can a fix (see #12271) into 1.4.4 or 1.4.5

**Closed by Narretz** 2015-08-12 13:48 UTC
