### ISSUE TITLE
un provided 'require' don't throw an error on test

### ISSUE THREAD

**Issue by IdoMor** [angular/angular.js#15651] opened 2017-01-30 07:28 UTC
I had upgraded my application from angular 1.48 into angular 1.6.1

We had implemented a test which verifies that our custom directive cannot be initiated without been supplied with a ng-model attribute.

The test is expecting an exception to be thrown.

prior to the upgrade, the test had passed, but not it fails.

The expected behavior would be that an attempt to create an instance of the directive without providing a ng-model would throw an error. As it was in angular 1.4.8

The directive definition:
`angular.module('ourApp')
    .directive('ourdirective', ['$timeout', function($timeout) {
    return {
      restrict: 'AE',
       require: 'ngModel',
       scope: {
         options:'=?',
         max:'=',
         ngModel : "="
    },
    templateUrl: 'ourhtmltemplate.html'
    link: function(scope, elt, attrs, ctrl) { // some code here }`

And here is the test implementation: 

`it('should throw if no ng model present', function() {
  expect(function() {
    buildElement("<ourdirective ></ourdirective>");
  }).toThrowError();
};

function buildElement(html) {
  element = angular.element(html);
  $compile(element)($rootScope);
  $rootScope.$digest();
  $rootScope.select = {}
  isolatedScope = element.isolateScope();
  $rootScope.$apply(function() {});
}`

We are using the following packages : 

`"angular": "1.6.1", 
"angular-mocks": "1.6.1",
 "jasmine-expect": "1.22",
 "karma": "^0.12.31",
 "karma-jasmine": "^0.3.5",
 "karma-jasmine-matchers": "^0.1.3",
 "karma-phantomjs-launcher": "^0.1.4"`

Thanks

**Comment by Narretz** [comment] 2017-01-30 10:32
Looks like a duplicate of https://github.com/angular/angular.js/issues/15629

We'll try to get the fix into 1.6.2

**Closed by Narretz** 2017-01-30 10:32 UTC
