### ISSUE TITLE
Select directive: the last option won't show somehow

### ISSUE THREAD

**Issue by gfaceless** [angular/angular.js#10627] opened 2015-01-03 07:38 UTC
hi,
this seems to be a bug for select directive

plunker demo:
[1.2.6+ (bug)](http://plnkr.co/edit/LAWqby?p=preview)
[1.2.5 works fine](http://plnkr.co/edit/6B84dv?p=preview)

it has something to do with select directive's update of 1.2.6

    selectCtrl.addOption(option.label, element);
the bug disappears if I remove this change.
the above line is [here](https://github.com/angular/angular.js/blob/v1.2.x/src/ng/directive/select.js#L594)

**Comment by lgalfaso** [comment] 2015-01-03 13:56
looks like a duplicate of #10161

**Closed by lgalfaso** 2015-01-03 13:56 UTC
