### ISSUE TITLE
$anchorScroll does not work with ng-view and pushState

### ISSUE THREAD

**Issue by shuhaowu** [angular/angular.js#2936] opened 2013-06-12 00:20 UTC
If you enable pushState and use $routeProvider for different urls, clicking on any links that only has the hashed part will cause the route to "change" (even if it is with in the same page).

I'll list a couple scenarios that I found. All of these requires pushState and the use of ng-view with templateUrl

**Scenario 1**

If there is already a hash on the URL when the user lands on the page. Angular has yet to render the page so obviously no hash scroll could happen as there is still nothing on the page. However, the automatic $anchorScroll is called before the rendering and therefore the page does not scroll to the correct location.

**Scenario 2**

If there is a hashed link (`<a href="#foo">foo</a>`) inside the ng-view: clicking on it will cause the route to change and rerender the page as oppose to just scrolling.

**Comment by anurag-itsolvs** [comment] 2015-02-21 08:09
Anyone found solution for this????

**Comment by Narretz** [comment] 2016-11-03 15:26
I'm going to close this issue because we have no reproduction of the issue. Feel free to reopen this issue if you can provide a reproduction (ideally a runnable demo in a https://plnkr.co or similar. You can use this [Plunker Template](http://plnkr.co/edit/tpl:yBpEi4)).

**Closed by Narretz** 2016-11-03 15:26 UTC
Labels: component: $location, component: ngRoute, frequency: low, severity: broken expected use, type: bug
