### ISSUE TITLE
Proposal extend existing DI framework to allow more than strings for keys

### ISSUE THREAD

**Issue by mikehaas763** [angular/angular.js#13094] opened 2015-10-14 20:08 UTC
I think it would be useful *today* to be able to use more than just strings as keys in Angular.js's injector. I'm already aware that the DI framework written for Angular 2 has this capability.

Now that I've been writing all my app code in ES6 and TS I find myself wanting to use a reference to classes/functions like below.

```javascript
// Module.js
import EmailDao from './EmailDao.js';
export default angular.module('org.name', [])
    .service(EmailDao, EmailDao); // Using a reference token here

// EmailList.js
import EmailDao from './EmailDao.js';

export default class EmailList {
    static get $inject() {
        return [EmailDao]; // Using a reference token here
    }

    constructor(emailDao) {
        this.emails = [];
        emailDao.getForPerson(123)
            .then(emails => this.emails = emails);
    }
}
```

In very large apps and very large organizations with a lot of shared modules you will often see hacking in a namespace in the string as a result of the key needing to be a string + there is essentially just one injector per ng1 app. For example `.service('org.name.namespace.a', EmailDao)`. By extending the ng1 DI system to be keys by other tokens, we lose the need to use a string for an injector key and being that it's a reference to specific class/function it's guaranteed to be unique.

Thoughts?

**Comment by Narretz** [comment] 2015-10-15 11:38
I think this is a duplicate of https://github.com/angular/angular.js/issues/10347

My guess is that it's quite complex to support this in 1.x. But if someone has a PR, we can definitely consider it.

**Closed by Narretz** 2015-10-15 11:38 UTC
