### ISSUE TITLE
ngRepeat has weird behaviour when DOM nodes has transition CSS property set

### ISSUE THREAD

**Issue by krassx** [angular/angular.js#11817] opened 2015-05-06 09:42 UTC
Consider the following HTML tempalte:

```
<div class="container">
  <div class="item" ng-repeat="item in items" ng-class="{'item-active':activeItem == item}" ng-click="itemClick(item)">
    <span>{{item.title}}</span>
    <div> {complex_markup_goes_here} </div>
  </div>
</div>
```

Assume we have set some transition proeprty to '.item' (like, `transition: background 0.2s linear`). Now, when we will try to replace items in controller we will see that new items are added and old ones are deleted only after some time (thus we are having duplicating double sized list). Removing transition property makes everytging work like a charm.

Does it a known limitation? Or it's a bug that can be fixed?

Thanks in advance.

**Comment by gkalpak** [comment] 2015-05-06 11:01
There is some context missing here (e.g. what version of Angular are you using, are you using `ngAnimate` or not, what other CSS styles are defined etc).
It would be best, if you could provide a live reproduction of the issue, e.g. using CodePen, Plnkr, JSFiddle.

**Comment by krassx** [comment] 2015-05-06 11:57
Sorry, for such simple explanation. Will create plunker for it. But for now here is what I am using:
- AngularJS 1.3.15
- Modules( ngAnimate, ngAria, ngResource, ngMaterial, ui.router, cfp.hotkeys )

**Comment by Narretz** [comment] 2015-05-13 08:58
If you are creating an example, try to reproduce the error only with core angular modules (ng, ngAnimate)

**Comment by Narretz** [comment] 2015-06-16 22:07
I'm closing this because we don't have enough info to pursue the issue. Feel free to reopen if you can provide more info.

**Closed by Narretz** 2015-06-16 22:07 UTC
Labels: component: ngRepeat
