### ISSUE TITLE
How to use ngResource with JSend-compliant responses?

### ISSUE THREAD

**Issue by iyel** [angular/angular.js#9855] opened 2014-10-31 09:27 UTC
I have to work with JSend-compliant response, like this

```
{
      "status": "success",
      "data": {
          "folders": {
              "list": [
                  {"id": 7, "name": "vavava"},
                  {"id": 8, "name": "123123a"},
                  {"id": 9, "name": "caca12341"},
                  {"id": 11, "name": "jkjkjk"}
              ], "total": 4
          }
      }
  }
```

but ngResource's query() expects an array of objects, this is why objects in `list` don't have `$delete, $remove, $update, etc.` actions

**Comment by Narretz** [comment] 2017-02-13 16:03
Dupe of https://github.com/angular/angular.js/issues/6138

**Closed by Narretz** 2017-02-13 16:03 UTC
Labels: component: ngResource, frequency: moderate, needs: public api, type: feature
