### ISSUE TITLE
On Interpolating start and end symbol to '[[ - ]]' arrayVal[index] fails

### ISSUE THREAD

**Issue by rijosimon** [angular/angular.js#14399] opened 2016-04-08 23:23 UTC
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

No

**What is the current behavior?**

On setting '[[' and ']]' as the start and end symbol. Then this produces an error: [[arrayVal[index]]]

The error produced is: https://docs.angularjs.org/error/$parse/ueoe?p0=arrayVal%5B0

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

Codepen reproduction of the bug: http://codepen.io/rijosimon/pen/oxpmJO

There is a workaround, putting space between the expression and the start and end symbols: http://codepen.io/rijosimon/pen/VaygqJ

**What is the expected behavior?**

[[arrayVal[0]]] should not be different from {{arrayVal[0]}} when you do interpolation.

**What is the motivation / use case for changing the behavior?**

It should be the expected behavior.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

AJs: 1.4, Browser: Chrome

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by lgalfaso** [comment] 2016-04-09 07:01
This is a duplicate of #8642

**Closed by lgalfaso** 2016-04-09 07:01 UTC
