### ISSUE TITLE
Another ng-animate issue

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [angular/angular.js#11692] opened 2015-04-23 13:13 UTC
I am using angular-strap typeahead control from http://mgcrea.github.io/angular-strap/#/typeaheads

with ngAnimate library included after some clicking on it i get error:

```
TypeError: options.domOperation is not a function
    at close (angular-animate.js:2747)
    at angular-animate.js:2566
    at forEach (angular.js:332)
    at angular-animate.js:2560
    at Scope.$get.Scope.$digest (angular.js:15352)
    at safeDigest (angular-strap.js:5211)
    at angular.module.provider.$get.$tooltip.show (angular-strap.js:4742)
    at Object.angular.module.provider.$get.$typeahead.show (angular-strap.js:4380)
    at HTMLInputElement.angular.module.provider.$get.$tooltip.enter (angular-strap.js:4682)
    at HTMLInputElement.n.event.dispatch (jquery-2.1.1.min.js:3)
```

when comment out ngAnimate everything works perectly.
This was not issue with 1.3.0 version

**Comment by Mechzeit** [comment] 2015-04-24 04:41
+1, getting the same issue with the same stack trace.

**Comment by RavisMsk** [comment] 2015-04-24 13:18
+1

**Comment by Narretz** [comment] 2015-04-27 08:16
Duplicate of https://github.com/angular/angular.js/issues/11713

**Closed by Narretz** 2015-04-27 08:16 UTC

**Comment by vytautas-pranskunas-** [comment] 2015-04-27 08:30
Is it resolved? If yes - when it will be available?

**Comment by Narretz** [comment] 2015-04-27 12:40
No, it is not fixed to my knowledge. I closed the issue because there's another open issue about the same problem.
