### ISSUE TITLE
ngForm gets removed when used on ngSwitchDefault

### ISSUE THREAD

**Issue by dietergeerts** [angular/angular.js#16374] opened 2017-12-14 10:13 UTC
**I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] other

**Current behavior:**
When using 
```
<div ng-switch-default ng-form="$ctrl.form">
```
or 
```
<div ng-switch-default><div ng-form="$ctrl.form">
```
the form is populated and then removed again. If you interpolate it using `{{$ctrl.form}}`, you see a flash of the form content.

**Expected / new behavior:**
This situation should not empty the form.

**AngularJS version:** 1.5.11

**Anything else:**
A current workaround is to use the following instead:
```
<div ng-form="$ctrl.form">
    <div ng-switch-default>
```

**Comment by gkalpak** [comment] 2017-12-14 10:29
I am not sure what you mean. Can you create a minimal live reproduction (e.g. using plnkr, CodePen, etc) and describe what you expect to see vs what you actually see?

**Comment by dietergeerts** [comment] 2017-12-17 16:08
Hmmm, recreating an example at home and I see that it works as expected, though in the code at work it didn't. I'll try to investigate further and recreate the exact situation at work.

**Comment by Narretz** [comment] 2017-12-29 12:05
I'm going to close this issue because we have no reproduction of the issue. Feel free to comment in this issue if you can provide a reproduction, and we will re-open it.

**Closed by Narretz** 2017-12-29 12:05 UTC
Labels: needs: more info
