### ISSUE TITLE
ngAnimate messing with validation classes

### ISSUE THREAD

**Issue by crisbeto** [angular/angular.js#12266] opened 2015-07-03 12:22 UTC
Since 1.4.0, ngAnimate has been messing with the way ng-valid/ng-invalid classes are being applied. Here's a plunker with an example (forked from the official email example): http://plnkr.co/edit/THMRi4lrFoVUMOFsmeli?p=preview

To reproduce, try entering any random value whose length is divisble by 3 (e.g. "123"). Note that the input and the form have the `ng-valid` class, in addition to `ng-invalid-email`, even though the value isn't a valid email. The correct behavior is for them to both be `ng-invalid`.

The problem gets solved if `ngAnimate` gets commented out from the dependencies.

**Comment by gkalpak** [comment] 2015-07-03 22:46
I am pretty sure there is a duplicate issue, but I can't find it :disappointed:

**Comment by Narretz** [comment] 2015-07-10 18:01
Looks like a dupe of #12007

**Closed by Narretz** 2015-07-10 18:01 UTC

**Comment by gkalpak** [comment] 2015-07-10 21:47
Yup, that's the one !
:+1: @Narretz :smiley:

**Comment by crisbeto** [comment] 2015-07-17 19:00
Can confirm that it works fine with a snapshot of 1.4.4. Thank you!
Here's a forked plunk: http://plnkr.co/edit/5xECEaHLGizWsJ82WUTj?p=preview
