### ISSUE TITLE
Empty option in select shows at last position when using ng-options and ng-if on the empty option

### ISSUE THREAD

**Issue by latata** [angular/angular.js#11061] opened 2015-02-14 20:58 UTC
Check this: http://plnkr.co/edit/OtwP7LK34MuOeXDxiM3x?p=preview
When options are loaded from http request (in plunkr I use $timeout) the empty option apears at the last position when using ng-if on it. When I use ng-show everything works well.

This is on Angular 1.3
I'm also curious why it (the ng-if version) doesn't work on Angular 1.4 (I get `TypeError: undefined is not a function` on console - http://plnkr.co/edit/RpGCd4UpOVoi2VBfbWZb?p=preview)

**Comment by Narretz** [comment] 2015-02-16 16:20
I assume that's because `ngIf`'s link fn is executed after ngOptions runs, so the options are already inserted.
I wonder what your use case for that is? Why do you need conditional empty options with ngIf?

**Comment by Narretz** [comment] 2015-09-26 14:37
Duplicate of #12190

**Closed by Narretz** 2015-09-26 14:37 UTC
Labels: component: forms
