### ISSUE TITLE
Open AngularJs 1.2.18 Doc in IE9 Error

### ISSUE THREAD

**Issue by itsverygood** [angular/angular.js#7876] opened 2014-06-17 15:18 UTC
I was trying to open https://code.angularjs.org/1.2.18/docs/#!/api/api/ng/directive/select in IE9. I got a blank page (Angular no response) for long time. Then I closed IE and open it again (from reopen session). I got the same blank page with no response. I closed it and opened it again. I got the page as in this screenshot.
![angularerrorpage](https://cloud.githubusercontent.com/assets/7784696/3302210/8b519d86-f632-11e3-9d23-469bd9c18da5.png)

**Comment by DOrlov77** [comment] 2015-04-08 14:13
The [docs page](https://docs.angularjs.org/api/) doesn't work too in IE9:

![image](https://cloud.githubusercontent.com/assets/7703176/7046914/af3b23da-de11-11e4-879f-8e59446c708e.png)

**Comment by Narretz** [comment] 2017-02-14 16:30
Dupe of https://github.com/angular/angular.js/issues/10317

**Closed by Narretz** 2017-02-14 16:30 UTC
Labels: browser: IE9, frequency: low, needs: investigation, severity: confusing, type: bug, type: docs
