### ISSUE TITLE
Support for CommonJS/AMD/UMD

### ISSUE THREAD

**Issue by pluma** [angular/angular.js#4919] opened 2013-11-12 15:54 UTC
This is not another "Angular modules should be real modules" ticket.

Currently AngularJS directly pollutes the global namespace. This means using angularjs in an environment that uses a module loader (e.g. require.js or browserify) requires developers to use shims or just give up and use AngularJS from the window object directly.

Instead, AngularJS should only attach itself to the window object if AMD is not present and there is no CommonJS/node-style `module`/`exports` object available. The [UMD](https://github.com/umdjs/umd) repository has plenty of examples for this.

The only implementation issue I can see is that AngularJS is becoming more modularized with "plugins" like the ngRoute module, which depend on AngularJS and potentially modify the `angular` object directly.

Ideally AngularJS should also provide an npm package (for browserify primarily, but with some modifications it could also work with server-side implementations of the browser DOM).

I realize the whole "modularity" concept is a problem with the different interpretations of how modules ought to work between AngularJS on the one side and AMD/CommonJS on the other, but I think it would be beneficial to the community if it were possible to load the files that are currently intended to be loaded via script tags with a real module loader like require.js/curl.js or browserify instead.

EDIT: Another problem I could imagine would be the optional dependency on jQuery (and potentially Q) as neither AMD nor CommonJS currently provide a mechanism for optional dependencies. If that's the only thing keeping AngularJS back, I would recommend creating a mechanism to configure AngularJS after it has been loaded (though before it has been applied to the document).

**Comment by itkach** [comment] 2015-01-09 18:00
I've been wondering for some time now - what exactly is the point of publishing Angular to npm if it's not a proper CommonJS module? I had trouble getting it to work in browserify, and finally managed with browserify-shim, but I can't find black magic vudu incantation to make it work with webpack. Just because you guys for some unfathomable reason decided to publish broken package. Am I missing something?

**Comment by mzgol** [comment] 2015-01-09 18:23
> Am I missing something?

Not all packages are CommonJS modules. This is also official npm, Inc. stance so if you expect every module to be requireable, that's just an incorrect assumption.

**Comment by itkach** [comment] 2015-01-09 18:42
@mzgol This doesn't really answer my question: what is angular package in npm good for? It doesn't work with any bundlers without shimming as far as I can tell, just <script> tags, and it doesn't have any dependencies, so what is the value in publishing it to npm? What is the value in having it not requireable? Forgive me if I'm asking something blatantly obvious to everyone, but I just can't make sense of it.

**Comment by pluma** [comment] 2015-01-09 18:44
@itkach There's nothing wrong with publishing other things than CommonJS modules on NPM. It's just a lot nicer to have JS packages on NPM be good CommonJS citizens.

The angular package on NPM works just fine, as long as you don't expect it to be a CommonJS module: it modifies the global object, so that's how you need to access Angular.

**Comment by pkozlowski-opensource** [comment] 2015-01-09 18:46
@itkach here we are are using npm as a package manager here - a place to store arbitrary files as some people prefer npm over, say, bower, for client-side dependencies.

Let's not mix-up 2 things (package manager and module format here), those are 2 completely separate problems (that I guess will be even more evident with the raising popularity of ES6 modules).

**Comment by itkach** [comment] 2015-01-09 18:48
> package manager here - a place to store arbitrary files

That's a very strange idea of what package manager is.

**Comment by pkozlowski-opensource** [comment] 2015-01-09 18:53
@itkach could you elaborate? I've got an impression that you are expecting all the packages deployed to npm to be modules written using CommonJS. This is not at all what npm is encouraging - a package is nothing more that a set of arbitrary files + metadata (name, version etc. - all the stuff in package.json). 

It would be totally valid to deploy a package containing, say, images only.

**Comment by itkach** [comment] 2015-01-09 19:00
> The angular package on NPM works just fine, as long as you don't expect it to be a CommonJS module: it modifies the global object, so that's how you need to access Angular.

If you put it in `script` that is? That's hardly a definition of "works" just fine. I don't need NPM for this kind of "fine". I'm trying to set up a large-ish project and put together a number of components in a sane way - using a module system for a browser application. Tools such as webpack are not even very picky as to module format - pretty much anything goes. Angular actively resists by providing NPM package that is unusable out of the box with any bundler. I am asking why is it so and you don't have any answer for me except "we can put anything we want into NPM". That is just not useful.

**Comment by btford** [comment] 2015-01-09 19:09
@itkach – I'm not sure what you're trying to accomplish by being overly argumentative. Browserify has a shim transform that makes working with Angular easy. I'm sure there's similar tooling for webpack. And I'm already looking into adding support for CJS/AMD.

Angular 1 was written in a time when neither of AMD or CJS was very prominent. It doesn't make sense to say that it "resists" tools that it predates.

**Comment by pkozlowski-opensource** [comment] 2015-01-09 19:11
@itkach the reasons are simple:
* there are many module formats in JS (AMD, CommonJS, ES6 modules)
* Not everyone is using CommonJS and even less so in a browser (but it is indeed getting a lot of traction recently thnx to Browserify)
* Historically AngularJS wasn't packaged using any of those package formats

So to move forward on this one we would need to either choose a one of the package formats (and make rest of the world unhappy) or support all of them (which is additional work, but initial + maintenance).

So, there is a work to be done here and this work needs to be prioritised vs. other items. If you are in the immediate need of some form of CommonJS support you could liaise with @btford and offer help as he is about to work on this topic.

**Comment by pkozlowski-opensource** [comment] 2015-01-09 19:11
Oh, @btford is here already :-)

**Comment by pluma** [comment] 2015-01-09 20:41
@itkach read this: http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging (especially point 1).

Yes, using AngularJS with CommonJS is pretty meh. That is why this issue exists and why it is still open. But it is usable. Much like jQuery plugins, Angular's module system pre-dates wide-spread use of module systems in front-end code. Think of the angular module on npm as a shim, or a polyfill. It monkeypatches itself into existence. If WebPack wants to be an alternative to browserify, it needs to support this kind of dependency as well. If it doesn't do that, you should file an issue with WebPack, too.

**Comment by alejonext** [comment] 2015-01-11 17:01
The problem is that if you opt for one method or the other, is reaping the possibility of using other methods. What you can do is you can use any method of construction of Javascripts files. As it can be used as browserify, bower, NPM, CommonJS or RequireJS. Without incompatibilities.

> Browserify seems to me, is the best solution.

**Comment by spacepluk** [comment] 2015-01-11 17:10
I appreciate that angular is not pushing some arbitrary package format on me, but I think it's reasonable for the npm build to use commonjs.  I might be wrong but I don't think there's a lot of people using angular from npm with a different package manager.

**Comment by mzgol** [comment] 2015-01-11 20:59
> I might be wrong but I don't think there's a lot of people using angular from npm with a different package format.

I use Angular from npm together with https://www.npmjs.com/package/grunt-npmcopy. In this way I don't need to manually copy newer Angular versions when updating; I just change the version in package.json and that's it.

jQuery uses the same system for their dependencies (for Sizzle & RequireJS). This is a valid use case.

Also, when ES6 modules are stabilized & appear in the browser, it will become more common to just use them as Angular 2 intends to do. `require` is not required to publish on npm.

**Comment by spacepluk** [comment] 2015-01-12 08:27
I still believe the other use case is more common but I don't have any data to back it up.

**Comment by pluma** [comment] 2015-01-12 10:49
FWIW, "we don't want to bless one arbitrary module format" is a solved problem thanks to [UMD](https://github.com/umdjs/umd).

**Comment by spacepluk** [comment] 2015-01-12 13:37
@pluma: I completely agree, but I think that should apply to the plain javascript distribution.  For the npm package I'm not so sure that's all I'm saying.

@bclinkinbeard's package was CommonJS before the angular team took over, so it feels a bit weird to upgrade an official release and suddenly needing browserify-shim or other tricks to make it work.  Of course, if most people are using npm + other module formats it makes sense to leave it as it is now.  But I wonder if that's really the case.

Also, "AngularJS with CommonJS is pretty meh" is a weak argument in my opinion.

**Comment by spacepluk** [comment] 2015-01-12 14:01
BTW, does having a CommonJS wrapper in the npm package break the other use cases in any way?

**Comment by bclinkinbeard** [comment] 2015-01-12 14:12
No, `package.json` just needs to have a browser field added (`"browser": "index-browserify.js"`) and then `index-browserify.js` can look something like this.

```js
require('./lib/angular.min.js');

module.exports = angular;
```

It will then "just work" for Browserify users, and nobody else will be affected at all.

**Comment by bclinkinbeard** [comment] 2015-01-12 18:39
I just submitted a PR that makes `require('angular')` work for Browserify (and webpack) users, without affecting anyone else. If it gets merged, we should be good to go starting with the next release/publish.

https://github.com/angular/bower-angular/pull/38

**Comment by caitp** [comment] 2015-01-12 18:46
@bclinkinbeard the bower-angular repository is generated automatically (see https://github.com/angular/angular.js/blob/master/scripts/bower/publish.sh --- for whatever reason we publish the npm releases from here too). So any changes you made would need to be achieved through this process.

It's a complicated mess, but I think it can be done. That said, I think we'd want to discuss the approach we want to take in detail, so maybe I can bring it up during the meeting today

**Comment by bclinkinbeard** [comment] 2015-01-12 18:51
Right, but the first step of that publish script is to clone the bower- repos. The files are then updated and published.

Unless I am missing something major, like where the contents of that package.json file come from. I went back through the history there and found that @btford manually added it, so I think the change is correct.

**Comment by caitp** [comment] 2015-01-12 18:54
no, I don't believe so. CJS support makes sense for npm, but it does not make sense for bower. So the publish scripts need a fixup to do that right

**Comment by bclinkinbeard** [comment] 2015-01-12 18:57
The PR only changes package.json, so it doesn't affect Bower.

**Comment by caitp** [comment] 2015-01-12 18:58
hmm, yes I see. Still not keen on it =)

**Comment by bclinkinbeard** [comment] 2015-01-12 19:01
How would you do it then? The package.json file I edited is the one published to npm, what would a better way be?

**Comment by caitp** [comment] 2015-01-12 19:03
a better way would not require a change for each module, and an extra change each time a new module is added.

**Comment by caitp** [comment] 2015-01-12 19:05
it's simpler to just name the file `index.js` and not have a `main` in package.json, then no changes to package.json are needed ever, and all you need to do is ensure that `index.js` has the correct contents, which can be easily automated

**Comment by bclinkinbeard** [comment] 2015-01-12 19:08
OK, so if I update the publish file to delete the main field and dynamically generate an index.js, you'd be amendable to that?

**Comment by btford** [comment] 2015-01-12 19:09
I agree with @caitp.

**Comment by caitp** [comment] 2015-01-12 19:09
yes

**Comment by bclinkinbeard** [comment] 2015-01-12 19:10
OK, hold please. :)

**Comment by bclinkinbeard** [comment] 2015-01-12 19:12
Oh, the publish script references a top level `build` directory that does not appear to be in the repo. What's up with that?

**Comment by caitp** [comment] 2015-01-12 19:14
the build directory is there when angular is built, which is part of ci builds and release

**Comment by bclinkinbeard** [comment] 2015-01-12 19:24
Is there a way for me to get a copy of it? Not sure how to test this process without it.

**Comment by caitp** [comment] 2015-01-12 19:25
you can build manually with `grunt build` or `grunt package`

**Comment by caitp** [comment] 2015-01-12 20:45
@bclinkinbeard please ping me on the PR once you've opened it

**Comment by bclinkinbeard** [comment] 2015-01-12 21:02
Here it is. https://github.com/angular/angular.js/pull/10731

**Comment by caitp** [comment] 2015-01-13 00:11
So, one (or more) of you should test the fixes with browserify ASAP and file a bug if there are any issues.

It __looks__ like it should be okay though

**Comment by caitp** [comment] 2015-01-13 00:11
Closed by c5686c5, babc20b

**Closed by caitp** 2015-01-13 00:11 UTC
Labels: 1.5-candidate

**Comment by bclinkinbeard** [comment] 2015-01-13 00:39
If you can point me to a build I can test it right now.

**Comment by btesser** [comment] 2015-02-09 06:18
I'm not sure to what extent this applies... but it may apply somewhat 
https://github.com/btesser/angular-global-injector
