### ISSUE TITLE
Add ng-on-* for listening to arbitrary events

### ISSUE THREAD

**Issue by ewinslow** [angular/angular.js#10073] opened 2014-11-15 22:23 UTC
ng-on-* could bind an expression to arbitrary events:

```
ng-on-click="doSomething()"
```

This would be a 1-for-1 replacement for the current ng-* event handlers:
```
ng-click="doSomething()"
```

Reasoning:
 1. Angular 2.0 is going this sort of direction. So this will help ease migration. Migration pain is one of the main complaints right now for 2.0, it seems to me.
 2. Get the benefits of the Angular 2.0 approach today.
   * ng-on-* prefix makes it clear that this is an event listener, regardless what event is being listened to.
   * ng-on-* would work on arbitrary events (like ng-attr-* works for arbitrary attributes), even custom events from web components
 3. (Minor) Provides nice symmetry from jQuery API to Angular API: `ng-on-*` => `$.fn.on('*', ...)`
 4. Binding to arbitrary events requires custom compiler support to recognize all ng-on-* attributes without explicitly adding them as separate directives, which is why I think it belongs in core.

**Comment by ewinslow** [comment] 2015-01-03 00:22
@caitp I did some research and it looks like certain events (e.g. blur) are special-cased to be always async so that events triggered during dom removal don't cause problems with inconsistent state.

**Comment by caitp** [comment] 2015-01-03 00:31
That's not actually the reason why it runs asynchronously, but yes. So there are a few combinations of behaviors that you may or may not want: digest or not, sync or not. No one answer applies to all cases for all users.

**Comment by ewinslow** [comment] 2015-01-03 00:45
For reference, I was looking at the comment here: https://github.com/angular/angular.js/blob/master/src/ng/directive/ngEventDirs.js#L44

**Comment by ewinslow** [comment] 2015-03-18 18:50
Lots of new announcements surrounding around 2.0 recently. Any new thoughts here?

**Comment by pkozlowski-opensource** [comment] 2015-03-22 13:35
@ewinslow I think that it would be a good candidate to explore / implement in 1.5 time-frame. Scheduling as such.

**Comment by ewinslow** [comment] 2015-03-22 21:39
Great, thanks!

**Comment by pkozlowski-opensource** [comment] 2015-06-28 14:47
Closing as duplicate of https://github.com/angular/angular.js/issues/12197

**Closed by pkozlowski-opensource** 2015-06-28 14:47 UTC
Labels: 1.5-candidate, component: $compile, needs: feedback, type: feature
