### ISSUE TITLE
$resource does not abort the requests through the promise

### ISSUE THREAD

**Issue by FireVolkhov** [angular/angular.js#10890] opened 2015-01-28 07:51 UTC
https://github.com/angular/angular.js/blob/master/src/ngResource/resource.js#L564

**Comment by Narretz** [comment] 2015-01-28 18:46
I assume this is a duplicate of https://github.com/angular/angular.js/issues/9332? Without a clear description, this issue is not really actionable. Please reopen if you don't think this is the same issue.

**Closed by Narretz** 2015-01-28 18:46 UTC
