### ISSUE TITLE
App in iframe throws exception when $location tries to manipulate window.history (Firefox 30.0) (Angular 1.2.20)

### ISSUE THREAD

**Issue by JohnAtWork** [angular/angular.js#8263] opened 2014-07-18 19:01 UTC
# Plunkr

http://plnkr.co/edit/7eQ4bBYc3R6UVnvPDiii

# Environment / Pre-conditions
Firefox 30.0
AngularJS 1.2.20
AngularJS app must be loaded in an iframe.  *Iframe domain must be different than main window domain.*

# Explanation

Calls like $location.path() manipulate the browser history using the window.history object.  In Firefox 30.0, if angular is loaded within an iframe, window.history appears to refer to main window history object, not an iframe-specific instance.  If iframe is hosted on a different domain from the main window, calls to history.replaceState() and other similar methods violate Same Origin Policy and cause exceptions and (ultimately) odd/undefined behavior.

In many cases the cause of the exception is Browser::url().

**Comment by gkalpak** [comment] 2016-06-01 12:37
I can't reproduce this on Firefox 46. Assuming this has been fixed.
Closing (feel free to re-open if you still see the error)...

**Closed by gkalpak** 2016-06-01 12:37 UTC
Labels: component: $location, type: bug
