### ISSUE TITLE
$rootScope:infdig Scope values aren't updating across digests

### ISSUE THREAD

**Issue by seaside98** [angular/angular.js#13665] opened 2016-01-03 17:05 UTC
Sometimes, my complex app will get into a loop where every single digest throws a $rootScope:infdig. The problem comes from the fact that the watched values are not being updated for the next digest.  The full ```watchLog``` array can be [viewed here](http://www.jsoneditoronline.org/?id=3b60b114e1dbe2d554bbb5d6be188557). Basically, in each digest the ```newValue``` and ```oldValue``` remain unchanged, instead of updating themselves like they should. For example, the last three digest loops look like this:
```json
[
  ...
  [
    {
        "msg": "fn: regularInterceptedExpression",
        "newVal": null,
        "oldVal": {
            "name": "AllasoPhotosTest",
            "isDirectory": 1,
            "size": 4930802,
            "fullPath": "/shared-files/AllasoPhotosTest",
            "$index": 1
        }
    },
    ...
  ],
  [
    {
        "msg": "fn: regularInterceptedExpression",
        "newVal": null,
        "oldVal": {
            "name": "AllasoPhotosTest",
            "isDirectory": 1,
            "size": 4930802,
            "fullPath": "/shared-files/AllasoPhotosTest",
            "$index": 1
        }
    },
    ...
  ],
  [
    {
        "msg": "fn: regularInterceptedExpression",
        "newVal": null,
        "oldVal": {
            "name": "AllasoPhotosTest",
            "isDirectory": 1,
            "size": 4930802,
            "fullPath": "/shared-files/AllasoPhotosTest",
            "$index": 1
        }
    },
    ...
  ]
]
```
Does anyone have any idea why the values are not updating? None of my watches are editing the watched value. Is there any chance that this is a problem with $rootScope.$digest?

**Comment by Narretz** [comment] 2016-01-04 15:04
Impossible to say (for me) what's happening. Maybe some other watch causes the infdig digest, and that's why you are getting the same output for this specific object?

**Comment by petebacondarwin** [comment] 2016-01-10 17:37
@seaside98 please provide a running reproduction or at least some example code so that we can debug this. Closing as not-actionable at this stage.

**Closed by petebacondarwin** 2016-01-10 17:37 UTC
Labels: component: scopes, needs: more info

**Comment by seaside98** [comment] 2016-01-10 22:40
I was using some code from [angular-viewport-watch](https://github.com/shahata/angular-viewport-watch/blob/master/dist/scripts/angular-viewport-watch.js) to disable watchers on hidden sections of my app. After removing it, I stopped having problems.

**Comment by petebacondarwin** [comment] 2016-01-11 09:10
Glad to hear that you got to the root cause of the problem.
