### ISSUE TITLE
$compile inside link function in angularjs directive not work as expected

### ISSUE THREAD

**Issue by szaccaria** [angular/angular.js#11887] opened 2015-05-16 15:28 UTC
I try do something with directive in angular, but I've some problem with $compile function in programmatically html element, call here "phe".

    var phe = angular.element('<div style="background-color:orange">{{value}}</div>');
When I append "phe" after or before the directive's element, it work like a charm...

    var $phe = $compile(phe)(scope);    
    element.after($phe);
but if I wrapped the directive element with this "phe" the $compile not work.

    element.wrap($phe);
Somebody have some idea?

I have made a plunker http://plnkr.co/edit/0x2MmQ7WYmiNog0IEzTj?p=preview

**Comment by petebacondarwin** [comment] 2015-05-16 20:10
The problem is that `wrap()` actually makes some kind of copy of the element that is going to wrap the directive element and so you lose the compiled node.
See http://plnkr.co/edit/64C0FZ7iXwysI2XPzn8S?p=preview

**Comment by szaccaria** [comment] 2015-05-17 06:58
So I think this is a issue on compile procedure in directive process?

**Comment by petebacondarwin** [comment] 2015-05-17 07:49
No, I don't think so. The problem is that you are cloning the compiled node outside of Angular and so it no longer has a connection to the scope.

**Comment by petebacondarwin** [comment] 2015-05-17 07:52
I think there must be a more angular way of achieving what you want. Can you give more indication of the use case?

**Comment by szaccaria** [comment] 2015-05-17 08:04
Thanks Pete for this attention. I made this test for learn better how angular work with compile e scope inside a link function. I found strange that the "before" and "after" work as i expect but wrap nope. If you see the "wrapper" element, after create and compile, have the "ng-binding and ng-scope" as other two. And if you see "before" element is out side the directive element (as after element) but work. Can you explain how it work?

    <div class="row">  
  			<input class="form-control ng-pristine ng-untouched ng-valid" ng-model="vm.value">  
  			<div style="background-color:orange" class="ng-binding ng-scope">Before Stefano</div>
			<div class="xx ng-binding ng-scope" style="background-color:orange">
			    Wrap {{value}}
				<h1 my-directive="vm.value" class="ng-binding ng-isolate-scope">Hello Stefano</h1>
				<div style="background-color:orange" class="ng-binding ng-scope">After Stefano</div>
		    </div>  
    </div>

**Comment by petebacondarwin** [comment] 2015-05-18 07:38
@szaccaria I will take a quick look but be aware that the angular compiler does not officially support changing the DOM elements outside the directive that is being compiled, which is what you are doing using the `wrap()` function.

**Comment by szaccaria** [comment] 2015-05-18 09:15
Thanks Pete, I understood.

**Comment by petebacondarwin** [comment] 2015-05-18 09:20
Here is one possible more "angular" way to achieve this: http://plnkr.co/edit/rtgqoYk3Qda7At3Q6doG?p=preview

**Comment by szaccaria** [comment] 2015-05-18 12:09
:+1:  thumbs up for you! thanks again!

**Comment by petebacondarwin** [comment] 2015-05-18 12:48
Closing this as I think we have concluded that this is not an issue with Angular.

**Closed by petebacondarwin** 2015-05-18 12:48 UTC
Labels: component: $compile, resolution: works as expected
