### ISSUE TITLE
angular module

### ISSUE THREAD

**Issue by alfu32** [angular/angular.js#15355] opened 2016-11-03 10:47 UTC
buggy semantics / feature request

**What is the motivation / use case for changing the behavior?**

*(+) angular module is a singleton, it's constructor should behave as such;*
(+) code clarity;
(-) the current implementation provides no benefit compared to the proposed one (on the contrary);

**tested with angular 1(.5.8) **

**current behavior?**
angular.module
the redeclaration of an angular.module is allowed, which goes against the fact that a module should be a singleton

```javascript
var A=angular.module('moduleX',[]);
var B=angular.module('moduleX',[]);
console.log(A===B) //will print false
```
even worse -  redeclaring the module will render all the previous entities declared in this module inaccesible;

```javascript
(function(){

	// factory moduleX.serviceA

	angular
	    .module('moduleX',[])
	    .factory('serviceA', serviceAInstanceGetter);

	function serviceAInstanceGetter() {
		return {
			func: func
		};

		function func() {
			return "serviceA.func"
		}
	}

})();

(function(){

	// factory moduleX.serviceB

	angular
	    .module('moduleX',[])
	    .factory('serviceB', serviceBInstanceGetter);

	function serviceBInstanceGetter() {
		return {
			func: func
		};

		function func() {
			return "serviceB.func"
		}
	}

})();
using moduleX as dependency in another module will return only what is contained in its latter declaration

/** test 1 **/
angular.module('test',['moduleX'])
.factory('testModuleX',["serviceA",function(serviceA){
return {test:function(){console.log(serviceA.func()) }}
}])
var moduleTest=angular.injector(['test']);
var test=moduleTest.get('testModuleX')
//will throw an error
// angular.js:4669 Uncaught Error: [$injector:unpr] http://errors.angularjs.org/1.5.8/$injector/unpr?p0=serviceAProvider%20%3C-%20serviceA%20%3C-%20testModuleX(…)

/** test 2 **/
angular.module('test2',['moduleX'])
.service('testModuleX',["serviceB",function(serviceB){
return {test:function(){console.log(serviceB.func()) }}
}])
var moduleTest=angular.injector(['test2']);
var test=moduleTest.get('testModuleX')

//this will print "serviceB.func" to the console
testB();

function testB(){
	var moduleX=angular.injector(['moduleX']);
	var serviceB=moduleX.get('serviceB');
	console.log(serviceB.func());
}

//this will throw an error upon retrieval of 'serviceA'
testA();

function testA(){
	var moduleX=angular.injector(['moduleX']);
	var serviceA=moduleX.get('serviceA')
	console.log(serviceA.func());
}
```
it is reasonable to expect that redeclaration of modules shouldn't work, *they are sigletons ... aren't they ?*
especially when one would divide entities for the same module across several files.

the (one) solution i'm currently using is

```javascript
(function(){

/*to prevent redeclaration one has to use a construct like this one*/

	var module;
	try{
		module=angular.module('some.module');
	}catch(error){
		module=angular.module('some.module',['dependency1',,,'dependencyN']);
	}

/*and only here what is non trivial about this module*/

/*implementation*/
	module
		.directive('someDirective',someDirectiveConstructor)
		.directive('someOtherDirective',someOtherDirectiveConstructor);

	someDirectiveConstructor.$inject=["$http","$timeout"];
	someOtherDirectiveConstructor.$inject=["$interval","$window"];

/*implementation details*/
	/*@ngInject*/
	function someDirectiveConstructor($http,$timeout){
		//// ...... 
	}

	/*@ngInject*/
	function someOtherDirectiveConstructor($interval,$window){
		//// ...... 
	}
})()
```
however it will render the code less readable, one is forced to put implementation details in front. which would go (and for good reason i believe) against clean code principles ( _see [ john papa's angular style guide - section y023 ](https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#style-y023)_ )

take any angular directive that is published here (on github) and you would see how the non trivial meaning of a module is obscured by all the logic needed to get a hold of the target environment and eventualy the right module reference 

**proposed solution**

prevent the redeclaration of the module

```javascript
(function(){
	var _angularModule=angular.module;
	angular.module=createModuleIfNotExists;

	function createModuleIfNotExists(name,dependencies){
		var module;
		try{
			module=_angularModule('some.module');
		}catch(error){
			module=_angularModule('some.module',['dependency1',,,'dependencyN']);
		}
		return module;
	}
});
```

**Comment by petebacondarwin** [comment] 2016-11-03 11:50
Thanks for this detailed issue @alfu32 

We have talked before about the difficulties of the `angular.module()` method. In particular the danger of accidentally re-declaring the module (i.e. by including the dependency list), which as you point out deletes the previous module declaration completely.

Just to be clear - Angular 1 modules are not singletons. They are named containers of service, filters and directives, that are used to populate the injector. In this sense it is perfectly reasonable to create a new module with a given name, which would override any previous module. In this way they are more like ES6 modules than singletons. You would not expect to be able to import an ES6 module into your file and then be able to add more exports to that module, right?

I guess from reading your issue, that you like to write to your application code so that you just request the module that you care about and then add more stuff to it.  Personally I feel that this is an anti-pattern and I prefer to go the other way and make a rule that one should never "re-open" a module by calling `angular.module()` without the dependency list. Which I accept goes against the John Papa style guide. 

This means that a module should only be accessed in one place in your application. The dependency mechanism helps a lot here as it means that you can always include a dependency upon another module rather than reopening it. I go further and ensure that I have a one-module to one-file bijection. Each module is wholly contained in exactly one file. If I find the file getting larger, I split the file, and so the module, into sub-files (and associated modules); then bring in those sub-modules via dependency.

This is what we did in https://github.com/angular-app/angular-app/tree/master/client/src and we found it worked well:
* it reduces the effort to think about where things have to go
* it makes it easier to move items around the project - or between projects - as everything is located in one place.
* it makes it easier to see the dependencies between the different parts of the code base.
* it also simplifies any build process you have as it doesn't require the files to be loaded into the browser in any particular order.

Regarding the suggested change to the current public API. This behaviour is how Angular 1 has worked for many years and it is well understood among most Angular 1 developers. I am afraid that changing this behaviour would be too much of a breaking change for Angular 1.

**Comment by alfu32** [comment] 2016-11-08 10:18
Thank you for being so kind to take the time to explain,

If I understood correctly  : 
_one should not declare a module that spans across several files_ ;

**one module - one file**.

example : 
let's say i have a module `'tasklist'`, in a single file that had grown over an acceptable limit and accumulated to much responsibilities.

initial `tasklist.js`
```javascript
(function(){
	angular
	.module('tasklist',[])
	.service('mailCnx',MailCnx)
	.directive('mailOnChange',MailOnChange)
	.service('dataStore',DataStore)
	.directive('storeOnChange',StoreOnChange)
	.provider('aceProvider',AceProvider)
	.directive('aceEditor',AceEditor)
		... injection and implementation details
})();

```
We decide to "split" it across several files : 
```
-tasklist.js 				/*the initial module	*/
---tasklist.mail.js			/* 						*/
---tasklist.datastore.js	/* 	new modules			*/
---angular.ace.js			/* 						*/

```
keeping the original module in `tasklist.js`

(one solution) leave in the original file only the module declaration referencing the newly created  dependencies :

modified `tasklist.js`
```javascript
	angular.module('tasklist',['tasklist.mail','tasklist.datastore','aceAngular']);
```

the other files 

`tasklist.mail.js`
```javascript
(function(){ 
	angular.module('tasklist.mail',[])
	.service('mailCnx',MailCnx).directive('mailOnChange',MailOnChange)
		... injection and implementation details
})();

```

`tasklist.datastore.js`
```javascript
(function(){
	angular.module('tasklist.datastore',[])
	.service('dataStore',DataStore).directive('storeOnChange',StoreOnChange)
		... injection and implementation details
})();
```

`angular.ace.js`
```javascript
(function(){
	angular.module('angular.ace',[])
	.provider('aceProvider',AceProvider).directive('aceEditor',AceEditor)
		... injection and implementation details
})();
```

**Comment by petebacondarwin** [comment] 2016-11-08 17:09
That is right. By the way, you do not need the IIFE since you have no variables

**Comment by gkalpak** [comment] 2016-11-08 20:39
> one should not declare a module that spans across several files

<sub>"should" is probably a strong word here...just saying 😛</sub>

**Comment by Narretz** [comment] 2017-04-27 10:33
This is essentially a duplicate of https://github.com/angular/angular.js/issues/1779

**Closed by Narretz** 2017-04-27 10:33 UTC
Labels: frequency: low, resolution: won't fix, severity: confusing, type: feature
