### ISSUE TITLE
bug(ngMock): errors thrown to reject promises are not caught

### ISSUE THREAD

**Issue by bclinkinbeard** [angular/angular.js#7187] opened 2014-04-22 03:05 UTC
Request Type: bug

How to reproduce: Include angular and angular-mocks on a page and run this code. Error is printed to the console even though the promise chain is configured to recover from the error.

```js
var inject = angular.injector(['ng', 'ngMock']).invoke

inject(function ($http, $httpBackend) {

  $httpBackend.expectGET('http://example.com').respond('foo')

  $http.get('http://example.com')
    .then(function (result) {
      throw new Error('Intentional rejection')
    })
    .then(null, function (err) {
      console.log(err);
    })

  $httpBackend.flush()
})
```

Component(s): ngMock

Impact: small

Complexity: medium

This issue is related to: 

**Detailed Description:**

This behavior can be corrected by wrapping a try...catch around the call to callback around line 1124 of angular-mocks, but that breaks 3 $compile tests and I'm not sure what to do with the caught error.

In its current state, unit testing promise chains must be done with ngMockE2E.

**Other Comments:**

**Comment by jnizet** [comment] 2015-05-28 16:27
+1.

This is caused by the code in `processQueue()`which does the following:

      try {
        if (isFunction(fn)) {
          promise.resolve(fn(state.value));
        } else if (state.status === 1) {
          promise.resolve(state.value);
        } else {
          promise.reject(state.value);
        }
      } catch (e) {
        promise.reject(e);
        exceptionHandler(e);
      }

So, every time a promise is rejected by throwing, the $exceptionHandler service is invoked. Removing this call would (as far as my tests show) make the behavior similar to a promise rejection that would return $q.reject() to reject the promise.

The $exceptionHandler service is documented as

> Any uncaught exception **in angular expressions** is delegated to this service.

(emphasis mine).

So, I don't understand why the $exceptionHandler is called when rejecting a promise, since that is not an "uncaught exception in angular expressions":
- the exception is caught
- it's not thrown by an angular expression

Can't we just remove that call to exceptionHandler?

**Comment by petebacondarwin** [comment] 2015-09-09 17:21
Closing as a duplicate of #7992 where there is significant discussion.

**Closed by petebacondarwin** 2015-09-09 17:21 UTC
Labels: component: $http, component: ngMock, frequency: low, severity: confusing, type: bug
