### ISSUE TITLE
Rendering Issues in Chrome and IE browsers for Angular table HTML

### ISSUE THREAD

**Issue by meetDinesh** [angular/angular.js#15481] opened 2016-12-09 10:38 UTC
Hello All, 

Have a good day!

We are using tables in angular and the data is shown there in around 8 columns and around 100 rows.
The HTML looks like following:

![html](https://cloud.githubusercontent.com/assets/24474001/21046106/04fd658c-be29-11e6-8380-4ab8bde2a2b8.PNG)

so now before rendering the complete table there is fraction of second the table looks like following:
![inbetweenissue](https://cloud.githubusercontent.com/assets/24474001/21046153/402f09e4-be29-11e6-8cc9-fc8f80e93636.PNG)

Please note table renders properly at the end but before it, it gives a problem like table wants itself to fit on the left as shown in above image.

Not sure what can be the reason behind it, is anyone have idea for it.

**Comment by gkalpak** [comment] 2016-12-09 10:52
It sounds more like an `ngGrid` issue, than Angular core. I would try reporting it to their repo.
In any case, it is impossible to investigate this without a reproduction.

Closing since this is not actionable atm. (Happy to reopen if there is more info indicating it is indeed an Angular core issue and/or a reporduction.)

**Closed by gkalpak** 2016-12-09 10:52 UTC

**Comment by meetDinesh** [comment] 2016-12-09 11:07
can you please share information when you finish reporting it to their repo (nggrid) so that I can get better understanding of it.

**Comment by gkalpak** [comment] 2016-12-09 11:16
@meetDinesh, I meant _you_ should try reporting it to them (at least that is what I would do if I were you). I lack the context (and a minimal reproduction), so I can't report it in a useful way.

**Comment by meetDinesh** [comment] 2016-12-09 11:27
how can I do it.. can you please guide me.

**Comment by gkalpak** [comment] 2016-12-09 11:38
Pretty much the same you did here:

- Go to their repo: https://github.com/angular-ui/ui-grid.
- Search through the open issues to see if it has already been reported: https://github.com/angular-ui/ui-grid/issues
- If not, open a new issue: https://github.com/angular-ui/ui-grid/issues/new

Ideally, you should provide a minimal reproduction of the problem (e.g. using CodePen, Plnkr etc), so people can immediately see the problema and investigate it.
