### ISSUE TITLE
mouseleave not caught in certain situations

### ISSUE THREAD

**Issue by wesleycho** [angular/angular.js#12703] opened 2015-08-30 06:23 UTC
There are certain situations where jqLite does not appropriately fire the mouseleave event when the element has a disabled child element - [here](http://plnkr.co/edit/P65m0unXt3SX1C8BSfod?p=preview) is a demonstration of the difference between listening on the DOM event and the jqLite event.

It should be noted that this is how jQuery handles it, but this is probably an incorrect implementation in jQuery IMO - jQuery should not swallow the event and prevent it from being propagated.

**Comment by PerfectPixel** [comment] 2015-10-28 23:46
This affects mouseenter as well: http://plnkr.co/edit/gcH7D94xe0KjyTH8usF2?p=preview

jqLite and jQuery substitute mouseenter with mouseover and mouseleave with mouseout. Most browsers do not support mouse events on disabled form elements, Mozilla fixed that bug a few days ago in the upcoming Firefox Version 44.

**Comment by petebacondarwin** [comment] 2015-12-07 18:07
@gkalpak - didn't you and I spend some time on mouseenter, mouseleave events recently? Fancy investigating this one?

**Comment by gkalpak** [comment] 2015-12-07 18:12
Yes and yes :)

**Comment by gkalpak** [comment] 2015-12-08 10:41
@wesleycho, @PerfectPixel, I can't reproduce the issue using your demos (tried on Chrome 47 and Firefox 42 on Windows). What OS/browser/versions are you seeing this ?

**Comment by PerfectPixel** [comment] 2015-12-08 11:13
@gkalpak OS X 10.11.1 with Chrome 47 / Firefox 42

In order to reproduce the issue, enter/leave the red boxed with your mouse by moving over the disabled checkbox.

**Comment by gkalpak** [comment] 2015-12-08 12:29
I see he issue now :) Thx !

It seems to be (related to) a browser issue indeed. (Here is the [bug-report for Chromium][1], btw.)
It's been fixed on Firefox 44, IE11 seems to work correctly, but it's not fixed in Chrome and although people have reported it working correctly on Edge, it didn't work for me. I don't know about Safari.

So, I am not sure how quickly the underlying browser bugs will be addressed on all supporting browsers and having a work-around (if possible) until then would be nice. On the other hand, jQuery has the same behaviour and (based on the discussion on [this issue][2]), there doesn't seem to be an easy and safe way out.

[1]: https://code.google.com/p/chromium/issues/detail?id=120132
[2]: https://github.com/jquery/jquery/issues/2558

**Comment by PerfectPixel** [comment] 2015-12-08 15:03
Safari has the same issue.

I agree that there is no easy fix. And I guess there won't be quick fixes on the browser side, the firefox bug received its fix after 12 years... :-(

**Comment by mgol** [comment] 2018-03-28 20:18
I think it's a can't fix from our side, especially that jQuery has worked that way for ages as well. Closing.

**Closed by mgol** 2018-03-28 20:18 UTC
Labels: component: jqLite, frequency: low, needs: browser fix, type: bug
