### ISSUE TITLE
Changing $window.location through script reloads page in Chrome but not in Firefox

### ISSUE THREAD

**Issue by vineelal** [angular/angular.js#14374] opened 2016-04-05 09:57 UTC

**Comment by Narretz** [comment] 2016-04-05 13:48
Can you please provide a demo of this problem?

**Comment by Narretz** [comment] 2016-04-12 11:14
I'm going to close this issue because we have no reproduction of the issue. Feel free to reopen this issue if you can provide a reproduction (ideally a runnable demo in a https://plnkr.co or similar).

**Closed by Narretz** 2016-04-12 11:14 UTC
Labels: component: $location, needs: more info
