### ISSUE TITLE
Cannot read property 'childNodes' of undefined

### ISSUE THREAD

**Issue by adamreisnz** [angular/angular.js#15332] opened 2016-10-29 01:14 UTC
This error has popped up in Sentry, originating from Angular source code:

![image](https://cloud.githubusercontent.com/assets/490562/19826208/8456511c-9de1-11e6-8605-64801716f988.png)

The offending line is: https://github.com/angular/angular.js/blob/master/src/ng/compile.js#L2043

It seems under some circumstances `node` may be undefined, after which this error is triggered when attempting to access `node.childNodes`. A guard should probably be put in place to ensure `node` is not undefined, and if it's a use case error, a more meaningful error should probably be triggered by Angular itself.

This issue has been seen on Angular 1.5.8 with Chrome mobile v44.0.2403, on Android 6.0.1.

**Comment by gkalpak** [comment] 2016-10-29 09:33
This sounds very similar to #13960. It could be due to the same underlying issue: An out-of-sync `nodeList.length` (i.e. a situation where `nodeList[nodeList.length - 1] === undefined`, which should be impossible).

Unfortunately, we can't start putting guards all over the place in order to work around possible browser bugs. Do you have a way to reliably-ish reproduce this (I assume not 😞)? 

It would be interesting to know what `nodeList` and `stableNodeList` look like and how the latter is populated [here](https://github.com/angular/angular.js/blob/1cf01d6fa7fcfb45bef46e4a800845ae8ab90b06/src/ng/compile.js#L1998-L2011) - but maybe that's too much to ask :smiley:

**Comment by adambuczynski** [comment] 2016-10-29 19:02
Yeah, I was afraid it might just be a fluke or browser specific issue. No reliable way to reproduce I'm afraid :) I was going to ignore the error, but figured I'd report it to see if it's something that Angular could do something about it or not.

Sounds similar to the issue you referred to, which also has been captured by Sentry. I guess capturing every single error from a large variety of browsers will inherently trigger some fluke situations/errors that we can't really do anything about.

**Comment by dtruel** [comment] 2017-01-03 15:22
I had this issue when using `$compile` on html that contained a directive that used `$templateCache`.  I got rid of the `$templateCache` and `templateUrl` and just replaced it with plain old `template:'<div>...'`, and the error went away.

**Comment by Narretz** [comment] 2017-02-22 19:51
Closing due to lack of reproduction.

**Closed by Narretz** 2017-02-22 19:51 UTC
Labels: browser: chrome, component: $compile, frequency: low, needs: investigation, severity: broken expected use
