### ISSUE TITLE
Observed `TypeError - Illegal invocation` exception when deep watching an object containing FileList object.

### ISSUE THREAD

**Issue by vinayk406** [angular/angular.js#13924] opened 2016-02-02 05:23 UTC
Browser : chrome 
Angular Version : 1.4.8

Plnkr: https://plnkr.co/edit/EjTuiuG9LXaEm2KUnThn?p=preview

Exception in firefox: 'name' getter called on an object that does not implement interface File.

**Comment by gkalpak** [comment] 2016-02-02 13:08
This happens because you are using deep equality. As mentioned [in the docs][1], using `objectEquality: true` will copy the object (so it can compare it with subsequent values and detect changes) using `angular.copy()` (and watching complex objects can have adverse implications).

`File` objects can't be properly copied, thus the error. You could use "normal" (non-deep) watch on the file-list itself or shallow watch `details` using `$watchCollection()`: [Updated plnkr][2] 

[1]: https://docs.angularjs.org/api/ng/type/$rootScope.Scope#$watch
[2]: https://plnkr.co/edit/etgcN3BphtvVPssSnhdA?p=preview

**Comment by vinayk406** [comment] 2016-02-02 13:20
As the watch expression in my case is dynamic, neither can use $watchCollection nor normal watch. 
Why can't the framework ignore the copying of Special Objects(FileList in this case) in the deep watch scenario and compare only on the references?

**Comment by gkalpak** [comment] 2016-04-07 19:32
Closing as duplicate of #14352 (well, it's the other way around, but #14352 has more participants :smiley:)
Let's track the issue there.

**Closed by gkalpak** 2016-04-07 19:32 UTC
Labels: component: misc core, component: scopes, frequency: low, severity: broken expected use
