### ISSUE TITLE
getService broken in IE11

### ISSUE THREAD

**Issue by steveblue** [angular/angular.js#12466] opened 2015-07-30 00:04 UTC
IE11 will throw an error during bootstrap of Angular 1.4.2 on the getService function. Removing the throw bootstraps our app, but none of the Services are injected then, end up 'undefined'.

```   
function getService(serviceName, caller) {
      if (cache.hasOwnProperty(serviceName)) {
        if (cache[serviceName] === INSTANTIATING) {
          throw $injectorMinErr('cdep', 'Circular dependency found: {0}',
                    serviceName + ' <- ' + path.join(' <- '));
        }
        return cache[serviceName];
      } else {
        try {

          path.unshift(serviceName);
          cache[serviceName] = INSTANTIATING;
          return cache[serviceName] = factory(serviceName, caller);

        } catch (err) {

          if (cache[serviceName] === INSTANTIATING) {
            delete cache[serviceName];
          }
         // throw err; 
        } finally {
          path.shift();
        }
      }
    }
```

**Comment by wesleycho** [comment] 2015-07-30 02:18
I am not able to reproduce this on a clean Plunker on IE11 - this likely needs a reproduction.

**Comment by caitp** [comment] 2015-07-30 16:19
yes, please provide a demonstration of this failure, thanks

**Comment by Narretz** [comment] 2015-08-21 09:45
Closing because we don't have a reproduce scenario.

**Closed by Narretz** 2015-08-21 09:45 UTC
Labels: branch: 1.4.x, browser: IE11, component: di
