### ISSUE TITLE
Cannot mock $injector

### ISSUE THREAD

**Issue by mmiszy** [angular/angular.js#14049] opened 2016-02-15 19:34 UTC
The code below works in Angular 1.4.9 but fails in 1.5.0 with the following error:

```
PhantomJS 2.1.1 (Mac OS X 0.0.0) Mock Injector should FAILED
    undefined
    workFn@/Users/dev/projects/app/bower_components/angular-mocks/angular-mocks.js:2810:26
    TypeError: undefined is not an object (evaluating 'injector.get('$rootElement').off') in /Users/dev/projects/app/bower_components/angular-mocks/angular-mocks.js (line 2611)
    /Users/dev/projects/app/bower_components/angular-mocks/angular-mocks.js:2611:35
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 1 of 1 (1 FAILED) ERROR (0.03 secs / 0.013 secs)
Warning: Task "karma:unit" failed. Use --force to continue.

Aborted due to warnings.
```

The test simply tries to mock `$injector` before it's injected into the service:

```javascript
'use strict';

// service.js
angular
    .module('testModule', [])
    .factory('Test', function Test($injector) {});

// service.spec.js
describe('Mock Injector', function() {
    beforeEach(module('testModule'));

    var $injectorMock;

    beforeEach(function() {
        $injectorMock = jasmine.createSpyObj('$injector', ['get']);

        module(function ($provide) {
            $provide.value('$injector', $injectorMock);
        });
    });

    beforeEach(inject(function(_Test_) {
    }));

    it('should', function () {
        expect(true);
    });
});
```

**Comment by Narretz** [comment] 2016-02-15 20:24
This happens since 1.5.0-beta.2. It's either caused by https://github.com/angular/angular.js/commit/fd83d3724ad30a93254f08cb82f981eaddb5dbff or https://github.com/angular/angular.js/commit/29a05984fe46c2c18ca51404f07c866dd92d1eec. Prob the latter, because the fix should have landed in 1.4.x too.

**Comment by petebacondarwin** [comment] 2016-02-15 21:14
@mmiszy can you try adding `invoke` as an additional property of your spy object?
E.g.

```js
$injectorMock = jasmine.createSpyObj('$injector', ['get', 'invoke']);
```

**Comment by lgalfaso** [comment] 2016-02-16 09:36
When running the test in 1.4.9, I get the expected below error, as the spy is not returning anything for `Test`.

```
Chrome 46.0.2490 (Mac OS X 10.11.1) test Mock Injector should FAILED
	Error: [$injector:undef] Provider 'Test' must return a value from $get factory method.
	http://errors.angularjs.org/"NG_VERSION_FULL"/$injector/undef?p0=Test
	    at /Users/lmirelmann/Documents/github/angular.js/src/minErr.js:63:12
	    at Object.enforcedReturnValue [as $get] (/Users/lmirelmann/Documents/github/angular.js/src/auto/injector.js:681:15)
	    at Object.invoke (/Users/lmirelmann/Documents/github/angular.js/src/auto/injector.js:827:17)
	    at /Users/lmirelmann/Documents/github/angular.js/src/auto/injector.js:644:37
	    at getService (/Users/lmirelmann/Documents/github/angular.js/src/auto/injector.js:786:39)
	    at Object.invoke (/Users/lmirelmann/Documents/github/angular.js/src/auto/injector.js:818:13)
	    at workFn (/Users/lmirelmann/Documents/github/angular.js/src/ngMock/angular-mocks.js:2510:20)
```

**Comment by lgalfaso** [comment] 2016-02-16 09:36
I would need a little more information before thinking that this is a regression

**Comment by lgalfaso** [comment] 2016-02-16 09:40
BTW, now there is a standard way to mock/decorate `$injector` by doing

```js
$provide.decorator('$injector', function($delegate) {
  // Return a new $injector here. Use $delegate if needed.
});
```

**Comment by Narretz** [comment] 2016-02-16 10:20
@lgalfaso Here's a reproduction: http://plnkr.co/edit/t9uGO5SJ08m7eQDQ4rlL?p=preview The service was simply missing a return value.
I think it's actually caused by the ability to decorate an injector.

**Comment by lgalfaso** [comment] 2016-02-16 10:42
@Narretz I am still trying to understand the issue. In 1.4.9 the line
```js
module(function ($provide) {
  $provide.value('$injector', $injectorMock);
});
```

does nothing, and `$injector` would not be mocked
http://plnkr.co/edit/tBNdLhWX6OwCicSdSV0b?p=preview

and with 1.5.x, this is now possible and the way to do so is http://plnkr.co/edit/kgzdOhosI1hAOMTJtCbx?p=preview

**Comment by Narretz** [comment] 2016-02-16 10:51
Oh, I see. So the original test was based essentially non-working.
I've also wondered why @mmiszy is mocking the injector, maybe there's a usecase, but if you just want to make sure the dependency is resolved, there's not need to mock it.

**Comment by mmiszy** [comment] 2016-02-16 11:49
>  and $injector would not be mocked

wow. How stupid of me :) This issue can be closed now, thank you for your help.

**Closed** 2016-02-16 12:35 UTC
Labels: branch: 1.5.x, branch: 1.6.x, severity: broken expected use, severity: regression, type: bug
