### ISSUE TITLE
Too Much Recursion on firefox

### ISSUE THREAD

**Issue by senateurritchie** [angular/angular.js#12579] opened 2015-08-13 11:32 UTC
Hi i build a big project with angularjs 1.2.28 
every thing i perfect on chrome and opera broswer but crash on firefox

```
"Error: too much recursion
s</ga.compile@http://yoobit.dev/src.php/v1-L6/jquery-1.11.3.min.js:2:21238
s</ga.select@http://yoobit.dev/src.php/v1-L6/jquery-1.11.3.min.js:2:21918
ga@http://yoobit.dev/src.php/v1-L6/jquery-1.11.3.min.js:2:7364
a.find@http://yoobit.dev/src.php/v1-L6.4/jquery.mobile-1.4.0.min.js:2:1957
.find@http://yoobit.dev/src.php/v1-L6/jquery-1.11.3.min.js:2:23658
t@http://yoobit.dev/src.php/v1-L5/jquery.tinymce.min.js:1:106
t/</e.fn[i]@http://yoobit.dev/src.php/v1-L5/jquery.tinymce.min.js:1:1393
t/</e.fn[i]@http://yoobit.dev/src.php/v1-L5/jquery.tinymce.min.js:1:1408
t/</e.fn[i]@http://yoobit.dev/src.php/v1-L5/jquery.tinymce.min.js:1:1408
```

what is the problem please.

**Comment by pkozlowski-opensource** [comment] 2015-08-13 11:37
@senateurritchie please don't cross-post (https://github.com/angular/angularjs.org/issues/175) and use an appropriate support forum to ask support questions (see: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question).

We want to keep GitHub issues for feature requests and bug reports. If you believe that root cause of your issue is a bug in AngularJS, please open an issue following bug reporting guidelines outlined here: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#submit

Closing this one as it looks like a support request that is not actionable in the current form.

**Comment by caitp** [comment] 2015-08-13 11:37
this doesn't really look angular related, but it does look like you are manually (or components you're using are doing it) doing a lot of recursive component building. somewhere along the way, probably encountering an endless loop.

but this is more of a support question, so why not take this to http://webchat.freenode.net/?channels=angularjs or https://gitter.im/angular/angular.js# ?

**Closed** 2015-08-13 11:37 UTC

**Comment by senateurritchie** [comment] 2015-08-13 12:32
thank u
