### ISSUE TITLE
1.7.1 $controller removes private 'later' api that is used by ui-bootstrap

### ISSUE THREAD

**Issue by jelmerjellema** [angular/angular.js#16598] opened 2018-06-12 11:47 UTC
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [x] other 

**Current behavior:**
Updating to 1.7.1 breaks operation of ui-bootstrap uibModal calls, because it depends on the `later` argument that has disappeared.

**Expected / new behavior:**
Well, expected  behaviour would be that code using uibModal would keep working. Of course, the expected fix would be in ui-bootstrap, which used the explicitly private flag. Problem is, that that library is now unsupported.
I see  that the master-snapshot code does have the later flag (*https://github.com/angular/angular.js/blob/master/src/ng/controller.js#L84). I am not sure if that means it wil return to the next version.

**Minimal reproduction of the problem with instructions:**
```
angular.module('example',['ui.bootstrap'])
 .factory('myservice',['$uibModal', function($uibModal) {
   return function() {
     $uibModal.open({
         template: '<div class="modal-body"><button ng-click="$dismiss()">Dismiss</button></div>",
         controller: ['$scope','$uibModalInstance', function($scope, $uibModalInstance) {}]
   });
  });
```
**AngularJS version:** 1.7.1
Only an issue in 1.7.1. When I look at the master branche, the `later` flag is there, but this is old code.

**Browser:**  all

**Anything else:**
I think reverting to the 1.7.0 version of the $controller function would be best, considering the end of live announcement and all. I would not know if the 'later' parameter was removed for some important issue. For now, I'll just stick to 1.7.0.

**Comment by gkalpak** [comment] 2018-06-12 12:51
Duplicate of #16594.

**Closed by gkalpak** 2018-06-12 12:51 UTC
