### ISSUE TITLE
css styles loading via component

### ISSUE THREAD

**Issue by MeirAmar** [angular/angular.js#15805] opened 2017-03-13 09:01 UTC
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

angularjs does not include css styles loader like the html template loader as part of the components definitions.

lets say we have a component:
```
module.component('myComponent', {
    template: '<some-html></some-html>'    // or we can use templateUrl: 'path/to/template.html'
}
```

**What is the expected behavior?**

I would love to add something like: 
```
module.component('myComponent', {
    template: '<some-html></some-html>' ,   // or we can use templateUrl: 'path/to/template.html'
   // the addion
    styles: '.some-css { color: green;}' // or styleUrls: ['path/to/file.css', 'another/path/to/file.css']
}
```

**What is the motivation / use case for changing the behavior?**

1. help developers or designers using the platform to use a structural styles.
2. the final destination is to encapsulate the styles within a component.
3. bigger apps often using one or few huge css files, the dynamic css style will help in performance since the majority of rules will not load at all only the relevant rules. 
4. get closer to the angular 2.x syntax - which will make the transition from angularjs to angular more natural.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

https://github.com/angular/angular.js/pull/15799

**Comment by Narretz** [comment] 2017-04-28 16:03
duplicate of https://github.com/angular/angular.js/issues/15014

**Closed by Narretz** 2017-04-28 16:03 UTC
Labels: component: $compile, type: feature
