### ISSUE TITLE
ng-animate on ng-view doesn't remove previous page content with firefox

### ISSUE THREAD

**Issue by jmeiss** [angular/angular.js#2514] opened 2013-04-26 11:07 UTC
Here is a fiddle to see the bug in action: http://jsfiddle.net/qSBHE/10/

When you navigate between pages with chrome and had a look at the source page, you will only see the destination page content.
Ex: 
```javascript
<div ng-view="" ng-animate="'flip'">
  <a href="#/page2" class="ng-scope">page 2</a>
</div>
```

but when you do the same thing with firefox, all pages are append.
Ex:
```javascript
<div ng-animate="'flip'" ng-view="">
  <a href="#/page1" class="flip-enter-setup ng-scope flip-enter-start flip-leave-setup flip-leave-start">page 1</a>
  <a href="#/page2" class="flip-enter-setup ng-scope flip-enter-start flip-leave-setup flip-leave-start">page 2</a>
  <a href="#/page3" class="flip-enter-setup ng-scope flip-enter-start flip-leave-setup flip-leave-start">page 3</a>
  <a href="#/page2" class="flip-enter-setup ng-scope flip-enter-start flip-leave-setup flip-leave-start">page 2</a>
  <a href="#/page3" class="flip-enter-setup ng-scope flip-enter-start flip-leave-setup flip-leave-start">page 3</a>
  <a href="#/page1" class="flip-enter-setup ng-scope flip-enter-start">page 1</a>
</div>
```

**Comment by infoTrainingym** [comment] 2015-01-29 13:57
I have this problem. Everything works perfectly in chrome, however in firefox ng-views are appended one after the other.

Any fix?

**Comment by matsko** [comment] 2015-01-29 14:00
Right now ngAnimate has a big refactoring going on. I'm happy to deal with this directly during that refactor. Seeing as it is still an issue, I'm going to reopen this.

**Comment by infoTrainingym** [comment] 2015-01-29 16:07
I just found out that the problem was a failure within a directive. I have
         element.on ('$ destroy', function () {
           document.removeEventListener (visibilityChange);
         });

In firefox, two arguments is necessary in removeEventListener and the transition stopped.

Thanks and sorry.

**Comment by matsko** [comment] 2015-01-29 16:09
OK. Thanks for the info. Why did you not use `$(document).off(...)` instead?

**Comment by infoTrainingym** [comment] 2015-01-29 16:30
Yes, i should use that. 

Thanks.

**Comment by petebacondarwin** [comment] 2015-01-29 21:56
@matsko - can we put this in a milestone? If you are actively working on it then I would think [1.4.x](https://github.com/angular/angular.js/milestones/1.4.x) or even [1.4.0-beta.3 / 1.3.12](https://github.com/angular/angular.js/milestones/1.4.0-beta.3%20/%201.3.12)

**Comment by aaani** [comment] 2015-02-19 02:35
I am experiencing the same issue in both chrome and firefox. I am using version 1.2.19.

**Comment by melino** [comment] 2015-03-03 23:15
Same here, even with latest v1.4.0-beta.5

**Comment by petebacondarwin** [comment] 2015-04-27 13:22
@matsko - is this fixed with the new animation engine?

**Comment by matsko** [comment] 2015-05-06 17:02
By the looks of it, things are working as expected with 1.4:

http://plnkr.co/edit/38upnPJqcLdMGUkoveZn?p=preview

And with 1.3:

http://plnkr.co/edit/5sjlneFawUPU52CURl3V?p=preview

Am I missing something here? It looks like the views are being removed correctly in both versions on Chrome and Firefox.

**Comment by matsko** [comment] 2015-05-11 19:12
I'm closing this issue for now since I can't get a reproduction to work. Please reopen if it's still an issue.

**Closed by matsko** 2015-05-11 19:12 UTC
Labels: component: ngAnimate, needs: investigation, type: bug
