### ISSUE TITLE
IE11: form.control.$dirty attribute always true if placeholder has non-ascii chars and required attribute

### ISSUE THREAD

**Issue by heinij** [angular/angular.js#7726] opened 2014-06-06 12:54 UTC
Angular 1.3.0-beta.10
IE 11.0.9600.17107 + Windows 7 ultimate 64-bit
Chrome+Firefox are ok

If a control has the required attribute and a placeholder attribute that contains a non-ascii character the form.control.$dirty attribute is always true.

```
<!DOCTYPE html>
<head>
<meta charset="utf-8" />
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-beta.10/angular.js"></script>
</head>
<body>
<div ng-app="testApp">
    <div ng-controller="testController">
    <form name="form" novalidate>
                //placeholder with non-ascii char
        <input type="text" name="fld1" ng-model="field1" placeholder="a&aacute;bcd" required>
        <p>form.fld1.$dirty: {{form.fld1.$dirty}}</p>

        <input type="text" name="fld2" ng-model="field2" placeholder="abcd" required>
        <p>form.fld2.$dirty: {{form.fld2.$dirty}}</p>
    </form>
    </div>
</div>

<script>
var app=angular.module("testApp",[]);
var controller=app.controller("testController", function($scope) {
    $scope.field1="";
    $scope.field2="";
});
</script>
</body>
</html>
```

**Comment by Narretz** [comment] 2018-01-11 14:35
This is caused by the infamous "IE fires input when the placeholder changes" bug, which Microsoft will never fix: https://connect.microsoft.com/IE/feedback/details/881670/ie11-esc-key-changes-value-of-input-type-text-but-does-not-fire-input-event (but at least it's fixed in Edge)
We actually fixed this in Angular back in 1.3.0, I think.

**Closed by Narretz** 2018-01-11 14:35 UTC
Labels: browser: IE11, component: forms, type: bug
