### ISSUE TITLE
ngOptions select as selects first option (due to reuse?)

### ISSUE THREAD

**Issue by asharpe** [angular/angular.js#12283] opened 2015-07-07 08:40 UTC
See http://plnkr.co/edit/uQL4B6C32f65Cm4lnFNH?p=preview

Inspecting the options in the select shows that both options have been selected.

**Comment by asharpe** [comment] 2015-07-07 08:42
Here's another plunk that indicates it's the reuse of the first option (with selected="selected") that's causing the option to remain selected - http://plnkr.co/edit/hmsvIu5OV8o2lCu1Ass1?p=preview

**Comment by asharpe** [comment] 2015-07-07 08:55
Possibly a dupe of #11727

**Comment by Narretz** [comment] 2015-07-10 17:56
Yes that's a dupe of #11727

**Closed by Narretz** 2015-07-10 17:56 UTC
