### ISSUE TITLE
a strange scope behaviour for an inner directive content 

### ISSUE THREAD

**Issue by stevermeister** [angular/angular.js#13845] opened 2016-01-26 09:38 UTC
Let's have a look at mydir:
template:
```
   <body ng-init="x=10">
       <mydir>
          {{x}}
       </mydir> 
   </body>
```
and the definition:
```
    .directive('mydir', function() {
       return {
           scope: {},
           link: function(scope){
               scope.x = 5;
           }
       };
    });
```

It shows 5 when scope is isolated (scope: {}) that is pretty expected behaviour. But when I create non-isolated one(scope: true). It shows 10! 

Already asked on stackoverflow - http://stackoverflow.com/q/34917448/274500, but did not get exact answer.

Is it a feature or some kind of side-effect?

**Comment by EdwardDiehl** [comment] 2016-01-26 10:28
:+1:

**Comment by besuhoff** [comment] 2016-01-26 10:28
:+1:

**Comment by besuhoff** [comment] 2016-01-26 10:28
:+1:

**Comment by gkalpak** [comment] 2016-01-26 10:47
First of all, I think the reverse of what you describe happens. When using `scope: {}`, you get `10`, whereas, when you use `scope: true`, you get `5`.

This is expected behavior. The interpolated `{{ x }}` value looks up the DOM hierarchy looking for the closest scope to get evaluated against.
In case of `scope: true`, it gets evaluated against that (normal) new scope which is created on its parent and is evaluated to `5`.
In case of `scope: {}`, the isolate scope is only visible in the directive's template, but your `{{ x }}` binding is not in it's template, so it's looking for "normal" scopes. And the closest normal scope in the hierarchy is the parent scope (where `ngInit` has set `x = 10` on). Thus you get a `10`.

This is intended, since the purpose of an isolate scope is to isolate what's happening inside, with what's going on outside of the directive (either up the DOM hierarchy or down). Only the template of the directive should be able to "see" the isolate scope.
Non-isolate scopes, on the other hand, behave like every other part of the scope hierarchy and are visible by other elements.

Closing as it works as expected.

**Closed by gkalpak** 2016-01-26 10:47 UTC

**Comment by stevermeister** [comment] 2016-01-26 11:09
@gkalpak 
could I ask you to provide a link to source code for this scope condition for directive inner content?

**Comment by gkalpak** [comment] 2016-01-26 12:37
@stevermeister, you could, but do you want to ? :stuck_out_tongue:
The `$compiler` is quite compicated, so it's really the combined result of several places. But one could say that the decision is made [here][1].

[1]: https://github.com/angular/angular.js/blob/eae0a1121ffcc636d760463105dcdc548ea47390/src/ng/compile.js#L2538-L2545

**Comment by stevermeister** [comment] 2016-01-26 13:46
@gkalpak 
great! thank you very much! 
it's exactly what I was looking for!
