### ISSUE TITLE
ngMessages memory leak with  unmatchedMessages.push(messageCtrl);

### ISSUE THREAD

**Issue by marcdexet** [angular/angular.js#14067] opened 2016-02-17 11:54 UTC
Hi 

## Description
We migrated from ngMessages 1.3 to 1.4 and we have a memory leak we do not understand, in the *render* function, there's an infinite loop that pushes more than 100000 element in  unmatchedMessages via

     unmatchedMessages.push(messageCtrl);

We don't understand why this loop nerver end

**EDIT**
It should be a problem in messageItem construction becauseof we have this test ever true:

      messageItem === messageItem.next;

How could this be possible ?

To my humble opinion this no a normal behavior, even if we miss something

## Context
Overview of the Issue - No stack
Motivation for or Use Case - silent memory leak
Angular Version(s): 1.4.8
Browsers and Operating System - Chrome Version 46.0.2490.71 m (64-bit) / Firefox 43.0.4 / Windows 7

### Involved piece of code
```(javascript)
return {
       require: 'ngMessages',
       restrict: 'AE',
       controller: ['$element', '$scope', '$attrs', function($element, $scope, $attrs) {
 ...

         this.render = function(collection) {
           collection = collection || {};
           while (messageItem != null) {
             totalMessages++;
             var messageCtrl = messageItem.message;

             var messageUsed = false;
             if (!messageFound) {
               forEach(collection, function(value, key) {
                 if (!messageUsed && truthy(value) && messageCtrl.test(key)) {
                   // this is to prevent the same error name from showing up twice
                   if (matchedKeys[key]) return;
                   matchedKeys[key] = true;

                   messageUsed = true;
                   messageCtrl.attach();
                 }
               });
             }

             if (messageUsed) {
               // unless we want to display multiple messages then we should
               // set a flag here to avoid displaying the next message in the list
               messageFound = !multiple;
             } else {
/*>>>>>>>>>>>>>>>>>> HERE <<<<<<<<<<<<<<<<<<<<<<<*/
               unmatchedMessages.push(messageCtrl);
/*>>>>>>>>>>>>>>>>>> HERE <<<<<<<<<<<<<<<<<<<<<<<*/
             }

/*>>>> ( messageItem === messageItem.next) is ever true<<<<<<<<*/
             messageItem = messageItem.next;
/*>>>>>>>>>>>>>>>>>> HERE <<<<<<<<<<<<<<<<<<<<<<<*/
           }
```

**Comment by Narretz** [comment] 2016-02-17 12:30
There must be something else going on that is not part of ngMessages, otherwise the leak would have been reported before. There are some changes to ngMessages in 1.4. Have you made sure to migrate your templates: https://code.angularjs.org/snapshot/docs/guide/migration

**Comment by marcdexet** [comment] 2016-02-17 12:53
My workmate has followed this guide, maybe he missed a point.

To my humble opinion, a exception when 

      messageItem === messageItem.next;

would be a very usefull feature

**Comment by marcdexet** [comment] 2016-02-17 14:22
I have this kind of message, with an intermediate UL list, could the *findPreviousMessage* function be fooled ?
```
<div bt-class="errors" ng-messages="fhs.getErrorFromField(cardForm.number)" ng-show="fhs.hasError(cardForm.number,'maxlength')">
          <ul>
            <li ng-message="required" class="has-error">some message</li>
            <li ng-message="maxlength" class="has-error">some another message</li>
          </ul>
        </div>
```

**Comment by Narretz** [comment] 2016-02-17 15:34
That's possible. I'm not sure if it's allowed to have an intermediate element. It probably was in 1.3 though, if the same structure works.

**Comment by Narretz** [comment] 2016-02-17 15:37
It would help if you could post an example on plnkr.co or similar.

**Comment by marcdexet** [comment] 2016-02-17 16:19
I working on it :)
It works in 1.3 very well (and it's in production yet)
But I'm near the problem

It's linked to the *$destroy* callback in *attach* function

* when parent is destroyed, the *$detroy* callback is called to deregister the commentNode.
* in the `removeMessageNode` , the `findPreviousMessage` return a `match` such as 
** `match === messageNode.next`

**Comment by marcdexet** [comment] 2016-02-17 16:21
It's not a very simple to create a stable plunker that creates a memory leak :/

**Comment by marcdexet** [comment] 2016-02-17 16:38
It's the nested UL, it worked in 1.3, but it doesn't work with the version 1.4.8

I have tested a form field with nested Ul and another without 

## Failed
```
<div bt-class="errors" ng-messages="fhs.getErrorFromField(cardForm.number)" ng-show="fhs.hasError(cardForm.number,'maxlength')">
          <ul>
            <li ng-message="required" class="has-error">some message</li>
            <li ng-message="maxlength" class="has-error">some another message</li>
          </ul>
</div>
```

## Working
```
<div bt-class="errors" ng-messages="fhs.getErrorFromField(cardForm.number)" ng-show="fhs.hasError(cardForm.number,'maxlength')">
            <div ng-message="required" class="has-error">some message</div>
            <div ng-message="maxlength" class="has-error">some another message</div>
        </div>
```

**Comment by Narretz** [comment] 2016-02-17 17:16
Ok, good to know the cause. However, I can't seem to reproduce it: http://plnkr.co/edit/9yXNg1uzwB94hcTtWpan?p=preview

Regarding a solution, I don't think we will support this. It was never supported explicitly, it just worked by chance. It's also quite easy to just put the ngMessages attribute on the ul, no?

**Comment by marcdexet** [comment] 2016-02-17 17:28
@Narretz  that's what I have done to all my messages, and it works better.

I would appreciate a test on bad chaining as

```(javascript)
return {
       require: 'ngMessages',
       restrict: 'AE',
       controller: ['$element', '$scope', '$attrs', function($element, $scope, $attrs) {
 ...

         this.render = function(collection) {
           collection = collection || {};
           while (messageItem != null) {
             totalMessages++;
             var messageCtrl = messageItem.message;

             var messageUsed = false;
             if (!messageFound) {
               forEach(collection, function(value, key) {
                 if (!messageUsed && truthy(value) && messageCtrl.test(key)) {
                   // this is to prevent the same error name from showing up twice
                   if (matchedKeys[key]) return;
                   matchedKeys[key] = true;

                   messageUsed = true;
                   messageCtrl.attach();
                 }
               });
             }

             if (messageUsed) {
               // unless we want to display multiple messages then we should
               // set a flag here to avoid displaying the next message in the list
               messageFound = !multiple;
             } else {
               unmatchedMessages.push(messageCtrl);
             }

/******************************** HERE ***************************************************************/
            if( messageItem === messageItem.next) {
                 throw new Error('Misconfiguration blabla, maybe have you nested your messages: please see the FAQ http://therightfaqurl')
            }
/******************************** HERE ***************************************************************/
             messageItem = messageItem.next;
           }
```

**Comment by Narretz** [comment] 2016-02-19 12:05
I would like to add an error for this, but I still can't reproduce the leak. If I understand correctly, then this block `unmatchedMessages.push(messageCtrl);` should be called infinitely often if you have an additonal wrapping element around your ng-message elements?

**Comment by Narretz** [comment] 2016-03-23 23:21
I think this is fixed by https://github.com/angular/angular.js/pull/14242
It'll take while to hit 1.4, though

**Closed by Narretz** 2016-03-23 23:21 UTC
Labels: branch: 1.4.x, component: ngMessages
