### ISSUE TITLE
"Cannot read property 'childNodes' of undefined" error when using Google analytics opt out chrome plugin

### ISSUE THREAD

**Issue by stalluri** [angular/angular.js#13883] opened 2016-01-29 06:02 UTC
In chrome browser, with angularjs 1.4.8, when I use Google analytics opt out plugin, I'm getting this error and my entire angular app doesnt work; 

TypeError: Cannot read property 'childNodes' of undefined
    at g (angular.js:7734)
    at g (angular.js:7734)
    at D (angular.js:8330)
    at g (angular.js:7731)
    at angular.js:7611
    at angular.js:1681
    at r.$eval (angular.js:16052)
    at r.$apply (angular.js:16152)
    at angular.js:1679
    at Object.e [as invoke] (angular.js:4523)

**Comment by Narretz** [comment] 2016-01-29 10:51
Sounds like the plugin is removing some DOM node or something. Does only you angular app not work? Or all angular apps? And what's the exact name of the plugin?

**Comment by stalluri** [comment] 2016-01-29 14:51
1) Plugin name : Google analytics opt out 
2) All angular apps are not working.

**Comment by Narretz** [comment] 2016-01-29 15:22
Hm, all apps would be bad, and I don't think this is true.
Here's plnkr.co Plnkr itself uses angular, and the test uses angular, too. Both work:
http://embed.plnkr.co/QKlsLNyr0RrECqeSDDRc/

Does the page need Google analytics for this?

**Comment by stalluri** [comment] 2016-01-29 15:41
Firstly, thanks @Narretz for the quick turnaround trying to replicate the issue and help me out. Much appreciated.

I don't know whey the plnkr is not failing , but here is our sample page, that is failing because of Google analytics opt out plugin.

https://www.neptune.io/useCases.html

By all apps, I meant, we have 2-3 angular apps several different pages, and all of them are failing with this plugin. We need Google analytics to track specific use-cases that users are most interested in on this use-cases page.

**Comment by stalluri** [comment] 2016-01-29 15:43
GA opt plugin is inserting script tags before head tag, and it might be causing trouble with angular's core compile or linking cycles. How do I handle such a scenario ?

![image](https://cloud.githubusercontent.com/assets/3118012/12679934/e4218124-c65b-11e5-8029-91a8bde27e4e.png)

**Comment by Narretz** [comment] 2016-01-29 15:51
Thanks for the page where it breaks. However, the page seems to have issues even without the opt out plugin ($sce is not defined)

Can you maybe load the unminified angular.js version for this site and then post the stack trace again?

**Comment by stalluri** [comment] 2016-01-29 16:21
Sorry for that. Here are the stack traces as you requested, with non-minified angularjs, and the $sce issue rectified. Please use the staging link below with Google analytics opt out plugin enabled.

https://staging.neptune.io/useCases.html

![image](https://cloud.githubusercontent.com/assets/3118012/12680957/304a93ec-c661-11e5-951b-d83442686cbc.png)

![image](https://cloud.githubusercontent.com/assets/3118012/12680967/37900da8-c661-11e5-976f-29281bb94c08.png)

![image](https://cloud.githubusercontent.com/assets/3118012/12680981/44c164fe-c661-11e5-9028-f254a238e1a7.png)

**Comment by Narretz** [comment] 2016-01-29 17:15
Thanks. Yes, it looks like the adding of the script node breaks the compiler. However, it must be something specific to your app. Check out https://www.madewithangular.com/#/, I've tested a few sites and none show the problem.

Something strange in your app is that the ng-controller is on the html tag. This is weird, because I expect that in the body only. Try placing it on the body. Also weird, your scripts are not in the head tag, but outside it, inside html. Try placing them inside the head and see what happens.

**Comment by Narretz** [comment] 2016-02-05 15:15
@stalluri I'm going to close this issue since you haven't provided further feedback. I assume the problem is that the plugin adds a script tag during the angular compile phase. And I think that this happens because you have either the controller on the html or the script tags outside of the head, both of which is a bad practice.

**Closed by Narretz** 2016-02-05 15:15 UTC
Labels: branch: 1.4.x, needs: more info

**Comment by stalluri** [comment] 2016-02-11 20:19
@Narretz , Sorry for the tardiness. 

Just so that someone else in future will benefit from what worked for me : 

As @Narretz  suggested, once I moved the data-ng-controller from html to body the errors went away. However I still load my scripts at the end before </body> , just to ensure script loading times don't block rest of html page.
