### ISSUE TITLE
$location.url partially decodes url encoded string

### ISSUE THREAD

**Issue by yasar11732** [angular/angular.js#15596] opened 2017-01-11 13:59 UTC
Here is simple example to demonstrate the problem;

```
<html>
  <head>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js"></script>
  </head>
  
  <body ng-app="testapp" ng-controller="topcontroller">
      <script>
   (function(){
      'use strict'
      
      angular.module('testapp',[])
      .controller("topcontroller", function($location){
        var test_data = {"a":"123/65"};
        
        var routeparam = window.encodeURIComponent(JSON.stringify(test_data));
        console.log(routeparam);
        
        $location.url("/test/" + routeparam);
      })
      
    })();
   </script>
  </body>

</html>
```

while `console.log(routeparam)` outputs `%7B%22a%22%3A%22123%2F65%22%7D` I am being redirected to `#/test/%7B%22a%22:%22123/65%22%7D`. Notice the `/` character in redirected url. This behaviour affects how angular-route behaves because `%7B%22a%22:%22123` and `65%22%7D` parts are considered as path components.

**Comment by gkalpak** [comment] 2017-01-11 14:42
Isn't this a duplicate of #13245 and/or #13815?

**Comment by yasar11732** [comment] 2017-01-13 06:23
As I workaround, I have decided to base64 encode my date instead of url encoding.

**Comment by gkalpak** [comment] 2017-01-13 08:50
👍 Closing as duplicate.

**Closed by gkalpak** 2017-01-13 08:50 UTC
Labels: resolution: duplicate
