### ISSUE TITLE
location.hash = "myhash" coming as #/myhash in url

### ISSUE THREAD

**Issue by softreigns** [angular/angular.js#11125] opened 2015-02-21 20:46 UTC
I am having a html page with a angular with angular controller in seperate file. I am bootstrapping in this html page and i have other plain javascript also where I am trying to set the location.hash with a button click. For me hash value in the page url is coming as #/myhash. If i remove angular bootstraping it come correct as #myash. Is there any way to prevent it ? Am I missing something ? Why is bootstrapping making it wrong ?

Thanks for the help

**Comment by pkozlowski-opensource** [comment] 2015-02-21 20:57
This is duplicate of https://github.com/angular/angular.js/issues/4608

What is going on here is that the built-in `$location` service observes URLs and tries to use them for routing. This is exactly what we want in SPAs but usually not what we want in an application which already manages URLs and want to use AngularJS only for a small portion of the page.

There are some work-arounds in #4608 but no "best & official" solution. I hope to look into it in the 1.5 timeframe.

Closing as a duplicate.

**Closed by pkozlowski-opensource** 2015-02-21 20:57 UTC

**Comment by softreigns** [comment] 2015-02-26 17:40
Thanks for your reply.
