### ISSUE TITLE
jqlite.after failing when having text nodes in browser (IE11)

### ISSUE THREAD

**Issue by jbaan** [angular/angular.js#16375] opened 2017-12-15 15:11 UTC
**I'm submitting a ...**

- [ x] bug report
-

**Current behavior:**

In IE11 comments nodes exists, so in case a jqlite.after is done, the nextSibling used as reference node for insertBefore could be a text node. In case of IE11 this is failing. So better is to use there index.nextElementSibling

**Expected / new behavior:**

```diff
 after: function(element, newElement) {
   var index = element, parent = element.parentNode;
   
   if (parent) {
     newElement = new JQLite(newElement);
   
     for (var i = 0, ii = newElement.length; i < ii; i++) {
       var node = newElement[i];
-      parent.insertBefore(node, index.nextSibling);
+      parent.insertBefore(node, index.nextElementSibling);
       index = node;
     }
   }
 },
```

**Minimal reproduction of the problem with instructions:**

**AngularJS version:** 1.6.6

**Browser:**  IE 11| 

**Anything else:**

**Comment by gkalpak** [comment] 2017-12-15 16:19
Can you post a demo of the issue (e.g. using CopePen, plnkr, etc)? It not clear to me what the problem is.
In any case, we can't use `nextElementSibling`, as this changes the behavior completely. (I wonder if jQuery does something special for IE.)

**Comment by Narretz** [comment] 2017-12-19 10:44
I'm going to close this issue because we haven't got any feedback. Leave a comment if you can provide new feedback.

**Closed by Narretz** 2017-12-19 10:44 UTC
Labels: component: jqLite, needs: more info
