### ISSUE TITLE
HTML comments are interpreted as an element in directives.

### ISSUE THREAD

**Issue by AlexGustafsson** [angular/angular.js#13118] opened 2015-10-18 14:02 UTC
When using templates for directives only one root element is allowed. This makes perfect sense, however, using HTML comments to describe the root element does not work since the comment is thought to be an element.

Comments should not break directive templates now, should they? If there's an underlaying reason for this behaviour, please enlighten me.

Valid template:
```HTML
<p>This works well!</p>
```

Invalid template:
```HTML
<!--This comment will stop it from working-->
<p>This doesn't work</p>
```

Error: [$compile:tplrt] Template for directive '[name]' must have exactly one root element. [URL]

The error occurs in 1.4.7 (dark-luminescence)

**Comment by frfancha** [comment] 2015-10-18 18:16
A comment is potentially a directive "call" itself in angular, so it is normal that it is seen as element.
Therefore that makes really 2 elements

**Comment by gkalpak** [comment] 2015-10-18 19:15
Duplicate of #12880.

**Comment by Narretz** [comment] 2015-10-27 17:04
To add to this: comments in the DOM are actual elements.

**Closed by Narretz** 2015-10-27 17:04 UTC
Labels: resolution: duplicate
