### ISSUE TITLE
httpParamSerializer and ";" symbol

### ISSUE THREAD

**Issue by materkov** [angular/angular.js#12623] opened 2015-08-19 11:45 UTC
With new AngularJS 1.4 I can use httpParamSerializer and httpParamSerializerJQLike:
```
http({
        method: 'POST',
        url: '...',
        data: $httpParamSerializer({body: ';'}),
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded' // Note the appropriate header
        }
})
```
Result:
```
body=;
```
Which is incorrect. Correct string should be (result 2):
```
body=%3B
```
Django backend can't parse first result correctly. With AngularJS 1.3 I use this this technique: http://www.bennadel.com/blog/2615-posting-form-data-with-http-in-angularjs.htm that produces correct result (result 2)

**Comment by pkozlowski-opensource** [comment] 2015-08-19 15:12
@materkov I think that you are trying to use this class for incorrect purpose. It was designed to prepare URL parameters, not request bodies. For URLs you don't have to encode `;` - or at least this is what we assume [here](https://github.com/angular/angular.js/blob/d0e50fdcd09b1d99da1ced45ee2fa9da07ce131e/src/Angular.js#L1326)

I would suggest writing a custom data transformer till we get to solving this properly in https://github.com/angular/angular.js/issues/6039

Closing as duplicate of https://github.com/angular/angular.js/issues/6039

**Closed by pkozlowski-opensource** 2015-08-19 15:12 UTC

**Comment by saumyaj92** [comment] 2016-03-18 19:43
I am facing the same problem. Did you find a solution? @materkov
