### ISSUE TITLE
Using ngRoute with html5Mode and HTTP basic authentication

### ISSUE THREAD

**Issue by tjespe** [angular/angular.js#15519] opened 2016-12-18 18:28 UTC
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
ngRoute does not work if it is used with html5Mode and HTTP basic authentication credentials are provided in the url like `http://user:password@domain.com`. The location doesn't get changed an the console is filled with several errors, including this one:
`Error: Failed to execute 'pushState' on 'History': A history state object with URL 'http://example.com/test' cannot be created in a document with origin 'http://example.com' and URL 'http://user:password@example.com'.`

**Steps to reproduce**
Kind of hard to show this problem in a plunker, but to reproduce you could copy code from [here](http://plnkr.co/edit/2yZyfZnkWYmgQtySCJKm) and put it on a test server with HTTP basic authentication.

**What is the expected behavior?**
The expected behavior would be that ngRoute works regardless of how the credentials are provided.

**What is the motivation for changing the behavior?**
I think providing credentials in the url shouldn't stop the whole page from working.

**Which versions of Angular, and which browser / OS are affected by this issue?**
This issue at least exist in Chrome with angular and angular-route version 1.5.6.
The issue does not seem to affect iOS safari.

**Comment by gkalpak** [comment] 2016-12-19 22:16
From a quick search, this seems to be a Chrome issue (introduced in Chrome 49): [discussion][1]
If that is indeed the case, it seems that we can't do much.

<sub>(Needs further investigation though.)</sub>

[1]: https://productforums.google.com/forum/#!topic/chrome/Rap85JfWrQg;context-place=forum/chrome

**Comment by gkalpak** [comment] 2016-12-20 08:25
After further investigation, it is indeed a Chrome issue. I have reported the issue [here][1].
I am going to close this issue, since:

1. It is basically caused by a browser bug.
2. Embedding credentials in the URL is neither common nor a good idea for production deployments anyway (so I assume it is only used as a convenience - probably during development).
3. There are ways to work around it (e.g. use hashbang mode, do not embed the credentials into the URL etc).

[1]: https://bugs.chromium.org/p/chromium/issues/detail?id=675884

**Closed by gkalpak** 2016-12-20 08:25 UTC
