### ISSUE TITLE
Cookie value doesn't get set if domain is given (v1.4.beta6)

### ISSUE THREAD

**Issue by demisx** [angular/angular.js#11420] opened 2015-03-24 22:02 UTC
I am using v1.4.beta6 and currently, if I try to write a cookie with specified domain, it fails: 

```js
 $cookies.put('fakeAuthToken', 'some.fake.token.value', { domain: '.exmaple.org' });
 expect($cookies.get('fakeAuthToken')).to.eql('some.fake.token.value'); // fails since $cookies.get returns undefined
```

In the meantime, this passes without domain value:

```js
 $cookies.put('fakeAuthToken', 'some.fake.token.value');
 expect($cookies.get('fakeAuthToken')).to.eql('some.fake.token.value'); // passes
```

The issue is here: https://github.com/angular/angular.js/blob/9b35dfb658411ff12ded73be44e52072e43e0c1c/src/ngCookies/cookieWriter.js#L52

The `rawDocument.cookie` property doesn't get updated when the built cookie string contains a domain path in it.

**Comment by lgalfaso** [comment] 2015-03-24 22:56
Hi, thanks for reporting this. Is everything within one domain (and is this
the same domain that you are trying to set?)
Would it be possible for you to create a plunker with the error?
>
>

**Comment by Narretz** [comment] 2015-05-06 13:11
Closing due to lack of response. Feel free to reopen with more information.

**Comment by demisx** [comment] 2015-05-06 19:59
Sorry, been swamped at work. Yes, the domain is the same in all cases.

**Comment by shahata** [comment] 2015-05-13 17:02
@demisx this seems to work just fine to me: http://plnkr.co/edit/4g1CP27NhVQKWCzFiPTM?p=preview
can you try and edit this plnkr in order to reproduce your use case?

**Comment by Narretz** [comment] 2015-06-16 19:58
Closing due to lack of info.

**Closed by Narretz** 2015-06-16 19:58 UTC
Labels: component: ngCookies, needs: more info
