### ISSUE TITLE
IE invalid argument error

### ISSUE THREAD

**Issue by Alexggp** [angular/angular.js#12058] opened 2015-06-09 10:54 UTC
I get this error only in IE11. In chrome and firefox it works fine. I've read this is produced because of placeholders, I've tried "ng-attr-placeholder", but it doesn't seem to work, so I tried deleting all the placeholders even deleting the content of the view and it still happens. 

Error: Invalid argument.
   at interpolateFnWatchAction (http://localhost:4000/companies/bower_components/angular/angular.js:6976:19)
   at Scope.prototype.$digest (http://localhost:4000/companies/bower_components/angular/angular.js:12541:23)
   at Scope.prototype.$apply (http://localhost:4000/companies/bower_components/angular/angular.js:12806:13)
   at done (http://localhost:4000/companies/bower_components/angular/angular.js:8379:34)
   at completeRequest (http://localhost:4000/companies/bower_components/angular/angular.js:8593:7)
   at xhr.onreadystatechange (http://localhost:4000/companies/bower_components/angular/angular.js:8532:11)

what could it be?
thank you.

**Comment by gkalpak** [comment] 2015-06-09 11:28
At the very least you should provide a runnable demo that reproduces the problem (e.g. using CodePen, Plnkr, JSFiddle etc).

**Comment by Alexggp** [comment] 2015-06-09 13:04
I can't show you a demo because it's a very big proyect, this is part of the configuration, any help?

    .state('promoEdit', {
        url: '/promos/promo/edit/:id',
        resolve: {
          promoResolve: promoResolve,
          storesResolve: storesResolve,
          regionsResolve: regionsResolve,
          editResolve: function() {
            return true;
          }
        },
        views: {
          'header': {templateUrl: 'views/header.html'},
          'headerButtons@promoEdit': {
            template: '<li ng-show="isEdit"><button type="button" ng-click="sendPromo()" class="btn btn-success btn-menu"><span translate>ctr_guardarBtn</span></button></li>'
          },
          'content': {
            templateUrl: 'views/promos/promosAdd.html',
            controller: 'PromoController'
          }
        }
      })

**Comment by pkozlowski-opensource** [comment] 2015-06-09 13:10
> I can't show you a demo because it's a very big proyect

@Alexggp we are not asking for the entire project, just a minimal reproduce scenario. You basically need to narrow down the problem and send a plunker demonstrating the issue. Without this the chances of understanding (and eventually fixing) the issue are very slim.

You are in the best position to provide the reduced reproduce scenario as you are in charge of the app.

**Comment by Narretz** [comment] 2015-06-16 10:10
Closing  since there is not enough information

**Closed by Narretz** 2015-06-16 10:10 UTC
Labels: needs: more info
