### ISSUE TITLE
Uncaught Error: [$injector:modulerr] Failed to instantiate module ng due to: TypeError: Cannot set property 'aHrefSanitizationWhitelist' of null when code migrating from 1.4.8 to 1.7.8

### ISSUE THREAD

**Issue by sivasatyababu** [angular/angular.js#16883] opened 2019-07-11 09:13 UTC
# AngularJS is in LTS mode
Uncaught Error: [$injector:modulerr] Failed to instantiate module ng due to: TypeError: Cannot set property 'aHrefSanitizationWhitelist' of null when code migration from 1.4.8 to 1.7.8

**Comment by gkalpak** [comment] 2019-07-11 09:45
Closing since there is not enough info for us to understand and investigate the problem (e.g. missing a minimal reproduction). Make sure you check out the [Migration Guide][1] for something that may be affecting the way you are using `aHrefSanitizationWhitelist` (e.g. the relative order of providers and config blocks, etc.). 

[1]: https://docs.angularjs.org/guide/migration

**Closed by gkalpak** 2019-07-11 09:45 UTC

**Comment by hedaprateek** [comment] 2021-07-12 10:55
I am facing the exact same issue when migrating from 1.2.32 to 1.8.2.
