### ISSUE TITLE
Context hierachy is not destroyed within a destroyed context, making memory leaks worse

### ISSUE THREAD

**Issue by yoann-antoviaque** [angular/angular.js#12699] opened 2015-08-28 12:44 UTC
While looking for memory leaks in our application (using angular 1.3.18) I found references to destroyed contexts, preventing them from being garbage collected.
Those destroyed contexts still have siblings, children and parents, all of them destroyed. The whole hierarchy should no longer be referenced and therefore garbage collected but as there are some rerefences left (root cause for memory leak), none of them could be collected.

This is due to the fact that only the $destroy() method is only invoked for the top context is invoked, broadcasting "$destroy" event to children making them all destroyed while only cleaning top context's $parent $$nextSibling $$prevSibling $$childHead $$childTail $root $$watchers.

Calling $destroy on children before boradcasting "$destroy" would help garbage collecting:

        $destroy: function() {
                // we can't destroy the root scope or a scope that has been already destroyed
                if (this.$$destroyed) return;
                var parent = this.$parent;
        
                // let's help garbage collecting
                while (this.$$childHead) {
                	this.$$childHead.$destroy();
                }

               	this.$broadcast('$destroy');

**Comment by yoann-antoviaque** [comment] 2015-08-28 13:51
pull request https://github.com/angular/angular.js/pull/12701

**Comment by frfancha** [comment] 2015-09-25 08:01
@yoann-antoviaque 
Seems perhaps a good idea to me.
In our general application we can see the memory usage increasing during the day (the application is used from morning to evening).
We can "reproduce" the problem by running a selenium test going from one screen to another one and vice versa 200 times.
Previously we didn't use reloadOnSearch: false in our routes, but we have rewritten our strategy to be able to support that.
Before the change, in our 200 switch selenium test, firefox 38 ESR memory was going from 300 MB to 4GB and crashed, after the change if goes from 300MB to about 1GB and "survives".
This was enough to let users work a full day (previously they had to restart the browser once a day), but we will take the code you propose in our angular.js and run the test and let you know the impact.
(When we have time I don't promise a quick try)
Fred
P.S. Currently we use 1.4.3

**Comment by frfancha** [comment] 2015-10-02 14:01
@yoann-antoviaque 
We have tested it now, without the proposed change the test makes firefox going from 300MB to 600MB, and with the change from 300MB to 1GB ...
So we will keep the standard version of angular here.
What we have observed is that without the change the memory usage goes up and down by big chunk (50 up 100MB sometimes), and with the change the memory increases much more regularly, which can be logical as your change is supposed to give much smaller pieces to eat at the garbage collector.

**Comment by dcherman** [comment] 2015-10-06 20:23
There should be no logical changes here.  In both cases, you're severing the path to the GC roots, so the scope and all descendants should immediately become eligible for GC ( assuming nothing leaked in descendant scopes ).

IMO, it seems like the solution here is to not have memory leaks in your code, or fix them if they're present.

**Comment by gkalpak** [comment] 2016-06-01 18:07
Since there is some scepticism around this change and we don't have a clear proof that it improves the situation, I'm going to close this. Please open a new issue if you can provide more info.

**Closed by gkalpak** 2016-06-01 18:07 UTC
Labels: component: scopes, severity: memory leak
