### ISSUE TITLE
ng-pattern - Particular valid regex pattern throws error

### ISSUE THREAD

**Issue by darrenshrwd** [angular/angular.js#11535] opened 2015-04-09 05:54 UTC
I am trying to use the following regex (angular 1.3.6):

ng-pattern="^0[0-9]{7,10}$"

It throws error: https://docs.angularjs.org/error/$parse/lexerr?p0=Unexpected

**Comment by pkozlowski-opensource** [comment] 2015-04-09 17:50
Can't reproduce with the latest 1.3.16 release: http://plnkr.co/edit/djlaGq9hDDMqZuRPJeO3?p=preview

Closing as "can't reproduce", please feel free to re-open when you've got reproduction scenario.

**Closed by pkozlowski-opensource** 2015-04-09 17:50 UTC
