### ISSUE TITLE
Proposal for spread in promises

### ISSUE THREAD

**Issue by fernandomoraes** [angular/angular.js#13076] opened 2015-10-12 21:25 UTC
Hello , someone else misses the spread functionality , that the Q have? I think it's much more intuitive than just retrieve the values ​​of an array. Something more like this:

```js
$q.all([promise1, promise2]).spread(function (value1, value2) {
  console.log(value1);
  console.log(value1);
});
```

over this:

```js
$q.all([promise1, promise2]).then(function (arr) {
  console.log(arr[0]);
  console.log(arr[1]);
});
```

For me, it gets a little more confusing when the return value is also an array:

```js
$q.all([promise1, promise2]).then(function (arr) {
  console.log(arr[0][1]);
});
```
I made a <a href="https://github.com/angular/angular.js/pull/13077">pull request</a> for this, and the increase of final file of angularjs is much low

**Comment by mchlbrnd** [comment] 2015-10-13 07:44
I like your approach, but I think would stick with an array or object. Where I would use an array if the number of promises is unknown beforehand. Otherwise I would use an object;

```javascript
$q.all({
    one: promise1, 
    two: promise2
})
.then(function (result) {
   // start using result.one and result.two
});
```
For you example to work, $q.all (with arbitrary arguments) also needs a change.

**Comment by fernandomoraes** [comment] 2015-10-13 11:38
Hello @mchlbrnd, I wrote the $q.all in wrong way, sorry for this, now is correct. Like you can see now, there is no changes to do with $q.all ...

**Comment by fernandomoraes** [comment] 2015-10-13 11:58
In my pull request code, is secure for who receive a promise as argument, because always can call spread. This work like a uniforme interface ...

```js
function foo (promise) {
    promise.spread(function (a) {
        console.log(a);
    });
}

foo($q.all([promise1]));
foo(promise1);
```

**Comment by mchlbrnd** [comment] 2015-10-13 12:11
Hi @fernandomoraes,

What I liked was:
```javascript
$q.all(x, y, z).spread(function (x, y, z) {})
```
Then $q.all needs to transform arguments before doing its magic. I think all and spread need to work similarly in order to improve readability and consistency (removing square brackets).

Additionally, for an object, your PR produces a second argument of undefined in spread's callback (see below). Another problem might be preserving order of object properties. I think this PR will lead to unexpected behaviour with the current implementation of $q.all.

```javascript
$q.all({
  one: promise1,
  two: promise2
})
.spread(function (one, two) {
  // two will be undefined
});
```

**Comment by Narretz** [comment] 2015-10-13 13:53
I think we usually don't want to integrate too many of these "specialised" promise functions. It might be a good candidate for this library, though: https://github.com/ohjames/angular-promise-extras

**Comment by dcherman** [comment] 2015-10-13 16:52
FWIW Since it's an extremely common helper lib, Lodash also has functions to assist with this

https://lodash.com/docs#spread

**Comment by fernandomoraes** [comment] 2015-10-13 19:39
@dcherman thanks.

**Comment by wesleycho** [comment] 2016-06-13 23:33
Sounds like this issue can safely be closed as won't implement - $q has been kept pretty thin in core, and is likely to stay that way as far as I can tell given prior feature rejections for $q.

**Comment by gkalpak** [comment] 2016-06-14 20:49
I agree that this is too much syntactic sugar for `$q`. Especially with ES2015's destructuring, this should be a non-issue :smiley:

Besides, we shouldn't add non-standard features to `$q` just for convenience, since it will make switching to/from other implementations harder.

**Closed by gkalpak** 2016-06-14 20:49 UTC
Labels: component: $q, frequency: moderate, resolution: won't fix, severity: inconvenient, type: feature
