### ISSUE TITLE
ng-href with empty value, cause lag

### ISSUE THREAD

**Issue by Khwesten** [angular/angular.js#14826] opened 2016-06-26 04:18 UTC
When i click some times on the link with an empty value in ng-href, my application stay with lag, until process the clicks.

**Comment by gkalpak** [comment] 2016-06-26 07:33
@Khwesten , it is not possible to diagnose the problem without more info. Could you post a live reproduction (e.g. using CodePen, Plnkr etc)?

**Comment by Khwesten** [comment] 2016-06-27 23:58
I create my CV online with github: https://khwesten.github.io/ and in name of freelances(in blue), i use ng-href, i have a mouse with fire-click(2 click on this button)... If i press very times, and try change de language on the flags in top page, have a delay.

**Comment by gkalpak** [comment] 2016-06-28 16:23
@Khwesten , it can be anything. With so many (unrelated) moving parts (3rd party libs, elements) and without being able to modify the app, it is very difficult to investigate. Please, try to narrow it down an create a minimal live demo.

**Comment by Khwesten** [comment] 2016-06-30 03:31
@gkalpak , i tried reproduce this error with litlle content, but... without success. I think that the way used by me: ng-href + radio input be wrong. I see this error, only with much content as in my cv. Thanks for attention and sorry me for anything.

**Comment by gkalpak** [comment] 2016-06-30 07:04
OK,thx for getting back. I will go ahead and close this, since we can't investigate further (and there is no indication that this is Angular-specific), nut feel free to reopen if/when you come up with a minimal reproduction.

**Closed by gkalpak** 2016-06-30 07:04 UTC
Labels: needs: more info, type: perf
