### ISSUE TITLE
email input - does not require tld to validate email

### ISSUE THREAD

**Issue by tsaltd** [angular/angular.js#14612] opened 2016-05-14 15:04 UTC
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

me@this does not raise error for email validation

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

simply enter an email address that is valid up to the characters after the @ 

me@domain is valid
me@domain. is invalid

**What is the expected behavior?**

me@domain should not be valid

**What is the motivation / use case for changing the behavior?**

insure valid email address

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by PascalPrecht** [comment] 2016-05-15 15:24
me@domain is a valid email address. You could also have foo@localhost.

This is intended behaviour.

**Comment by Narretz** [comment] 2016-05-15 18:10
@PascalPrecht is right, closing.

**Closed by Narretz** 2016-05-15 18:10 UTC
