### ISSUE TITLE
NPM Package /// "require" results with "ReferenceError: window is not defined"

### ISSUE THREAD

**Issue by slurmulon** [angular/angular.js#14442] opened 2016-04-15 01:39 UTC
If you install the latest 1.X Angular via NPM:

`npm install angular`

and then try to use it:

```
> $ node
> require('angular')
```

you immediately receive:

```
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/adminaccount/Code/clint/ui/node_modules/angular/angular.js:30712:4)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/adminaccount/Code/clint/ui/node_modules/angular/index.js:1:63)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
```

I'm not sure if this is expected, but it seems counter-intuitive.  Some people suggest "just not using NPM", but that doesn't quite cut it for people with `webpack` and `browserify` needs.

**Comment by Narretz** [comment] 2016-04-15 08:01
Since angular is designed for a browser environment,  yoi must somehow provide angular with a window object. I think most people use jsdom for that purpose.

**Comment by slurmulon** [comment] 2016-04-15 16:30
Would you not expect `require('angular')` to just work without any implicit external dependencies? Thanks for the tip though, will try integrating it. I figured if anything `browserify` and `webpack` would make such a common variable accessible.

**Comment by gkalpak** [comment] 2016-04-18 19:22
@slurmulon, `require('angular')` is not the problem per se. The problem is the environment where this is executed in (assuming that `require()` is defined in context).

Node obviously defines `require()` and makes it available in the context of an file/module. Browsers don't provide a `require()`. Browserify can be used to convert code written in "Node style" in a format that is suitable for running in the browser (e.g. providing `require()` and transforing the code using APIs available in a browser environment, while preserving the semantics).

--
Yet, AngularJS is not designed to be run in environments other than the browser. If you try to run Angular on the server-side (using Node), without somehow providing a browser-like environment (e.g. using jsdom or something similar), you will get an error.

What browserify (+webpack) can do, is allow you to write your code in "Node style" (e.g.  using `require('angular')`) and still make it work in the browser. But you still have to run it in a browser environment (or somehow emulate it on the server-side).

--
In case it isn't clear by now, `require('angular')` will load the angular.js script, which in turn will try to perform some initialization tasks (e.g. set up listeners for DOM events), which assume a browser environment.

Closing, since it works as expected.

**Closed by gkalpak** 2016-04-18 19:22 UTC

**Comment by slurmulon** [comment] 2016-04-19 18:02
@gkalpak Thank you for your thorough feedback. I understand the point of tools such as `browserify` and `webpack`, I have used them quite a bit in my time. I'm more poking at an intentional design decision by the Angular team and tools like it designed "exclusively" for the browser, which was to sacrifice zero-configuration installation for one that implicitly requires third party tools in order to function.  I understand the benefits of this, as it implies less for the user and allows them to choose the tools that are right for them - but let's face it, this scenario is extremely common, and needing to rely on (yet another) tool such as `jsdom` or `CommonJS` shims in order to jankily function just feels silly at this point.

The large part of the JS community is favoring exclusive use of `npm` over `bower` because obviously you can explicitly `require` resources and not depend on `global` variables being defined and available. Another complication is properly supporting transparent builds for both `npm` and `bower`, while also loading efficiently in projects that inherit your Angular modules. For instance:

`var angular = requie('angular')`

When I also have this in my `webpack` application, which I certainly will, then I receive an error message specifying that `angular tried to load twice`. As I see it, this leaves the engineer in a bit of a catch 22. The alternative is to write your external library/module such that it implicitly requires angular, either provided to an IIFE or assumed to exist on `global`. In my eyes, disregarding complications like this and giving the developer "more flexibility and freedom" is becoming more of a headache than a benefit.

I have analyzed countless repositories of Angular modules using hybrid `bower` and `npm` packaging techniques, but none of them have been able to elegantly address the problem. If you have some preferred resources on the topic, it would be much appreciated if you sent them my way!  Thanks again.

**Comment by gkalpak** [comment] 2016-04-20 14:52
@slurmulon, maybe I did not understand your usecase correctly. Could you provide a simple POC that reproduces the error.

Note that also it is a common requirement now to run something on the server, it really wasn't when Angular first came to be and retro-fitting support for browser-less environments is an enormous undertaking. (Angular 2 will support that out of the box.)

**Comment by slurmulon** [comment] 2016-04-20 15:58
@gkalpak Sorry yeah, I believe the issue is generally one of inconsistency - I've been waiting for things like CommonJS to be thoroughly adopted forever now (I know, fighting the tide of various standards in various environments is incredibly difficult). I will try to put together an example that shows this, or push up a branch to my angular module repo that outlines the problem, but I'm trying to get a release out this week so it might be in a few days.

This web requirement is admittedly recent but it's becoming a dominating force so quickly that I believe more idiomatic solutions should be strove for. Also aware that this would require a massive amount of work in order to achieve, but the aggregated amount of work (research, debugging, build crap, etc.) that each engineer must perform outside of the Angular team is arguably more significant.

Very excited to hear that this will be a part of Angular 2. I haven't had the luxury to port over any of my professional projects to this yet, but certainly looking forward! Is there anything so different about the Angular 2 packaging / run-time regarding specific browser-environment variables like `window` and `document`? Curious if anything could be partially adopted in Angular 1.x code, but if not I'll just have to stay patient for now and live with a little inconsistency. Thanks again!

**Comment by gkalpak** [comment] 2016-04-20 20:53
@slurmulon, the difference with ng2 is that is was designed from the beginning with the ability to run on different environments in mind (not just the server, but also on mobile devices, service workers, etc).

So, (among other things) all DOM access and manipulation is abstracted away and the things that need direct access to a UI are clearly isolated from other parts that can run without one. 
Thus, it is very easy to swap the underlying implementations per environment or bootstrap the framework without the parts that you are not interested in (e.g. the things that need access to a "view").

--
Anyway, feel free to ping me when/if you have set something up and I'll look into it.
If there are way that we can better support common usecases (with a reasonable amount of work), we would sure be interested :wink:
