### ISSUE TITLE
ng-messages eats all memory and crashes after removeMessageNode call

### ISSUE THREAD

**Issue by olegccc** [angular/angular.js#13627] opened 2015-12-24 20:22 UTC
Hi,

Please see the attached picture. Immediately after current line is invoked two elements in the message list start to link to each other which results in that the page eats all available memory and crashes in 5 seconds.

Probably the reason is that the node tree is as is:
```
<ng-messages><ng-transclude><ng-message/><ng-message/></ng-transclude></ng-messages>
```

Version: 1.4.8

![ngmessages-error](https://cloud.githubusercontent.com/assets/7957115/11997710/a028c748-aa8b-11e5-9404-cab9e8422b60.png)

**Comment by olegccc** [comment] 2015-12-24 20:35
UPD: not 'propably', 'definitely'. After removing <ng-transclude> sublevel, the error is gone. Anyway it is something which should never happen.

**Comment by Narretz** [comment] 2015-12-31 15:01
Can you please create a minimal demo that reproduces the problem?

**Comment by Narretz** [comment] 2016-01-11 11:21
Closing due to lack of feedback and minimal demo.

**Comment by silver2k** [comment] 2016-04-13 09:33
I can confirm I'm also seeing something very similar - but I can't pin down why it's happening. I've attempted a minimal demo, but without knowing the specific combination of factors, it's like looking for a needle in a haystack. I do however have a production website exhibiting this behaviour I can point a someone to for easy replication!

**Comment by gkalpak** [comment] 2016-04-13 10:51
This sounds pretty much like the bug that was fixed in #14242.
@silver2k or @olegccc, could you confirm that the problem is gone using the latest code from master (e.g. from https://code.angularjs.org/snapshot/angular-messages.js) ?

**Comment by Narretz** [comment] 2016-04-13 11:50
The fix is not yet in a 1.4 release, though.

**Comment by silver2k** [comment] 2016-04-14 02:55
Exactly - upgrading to 1.5 and confirming the bug is gone probably isn't a great test. Is the a chance of backporting the fix to 1.4? Crashing the browser seems pretty significant.

**Comment by gkalpak** [comment] 2016-04-14 19:34
@silver2k, it _has_ been backported to the `v1.4.x` branch, so it will be included in the upcoming 1.4.11 release. Stay tuned :smiley:

**Comment by Narretz** [comment] 2016-06-02 12:16
1.4.11 is available!

**Closed by Narretz** 2016-06-02 12:16 UTC
Labels: component: ngMessages, needs: more info, type: bug

**Comment by gkalpak** [comment] 2016-06-03 20:20
`v1.4.11` is out :smiley:

**Comment by sswayney** [comment] 2017-05-10 22:37
Just in case it helps anyone else. I had some sort of issue with ng-messages and out of memory errors in firefox and chrome. I watched using the firefox profiler and came to the realization it had something to do with ng-messages. I was using angular and angular-messages 1.4.9 and moved to 1.9.11 and the issue was gone.

**Comment by gkalpak** [comment] 2017-05-11 06:17
Thx for confirming, @sswayney.
