### ISSUE TITLE
$location.absUrl() returns extra / character after # in the url

### ISSUE THREAD

**Issue by rockneverdies55** [angular/angular.js#14375] opened 2016-04-05 14:37 UTC
Interestingly `location.absUrl()` function call returns an extra leading slash `/` charater in the fragment part of url.

I can confirm in address bar and `location.href` (or angular's `$browser.url()`) that the actual url doesn't contain that character.

My url looks like the following: https://example.com:8042/over/there?name=ferret#nose1/nose2/nose3 . Though `location.absUrl()` returns https://example.com:8042/over/there?name=ferret#/nose1/nose2/nose3

In the docs it's said that `absUrl` parses based on http://www.ietf.org/rfc/rfc3986.txt specification, however I haven't seen anything about the extra slash character I'm getting back in the spec. Maybe it's a result of other slash characters within the fragment section of the url?

**Comment by Narretz** [comment] 2016-04-06 15:38
Could you please create a runnable demo of this problem?

**Comment by gkalpak** [comment] 2016-04-08 09:24
This happens because in the default Hashbang mode, the part after the first `#` (and before the first `?` after that) is interpreted as the `path` (as far as Angular's `$location` in concerned).
So, `$location` will normalize that, by prepending it with a `/` if it doesn't have one already.

With `v1.5.3` that I tried, the URL in the address bar seems to be updated as well to include the leading `/`.

--

If you don't `$location` to mess with your URL (and are not using client-side routing), you can configure the `$locationProvider` like this:

```js
$locationProvider.html5Mode({
  enabled: true,
  requireBase: false,
  rewriteLinks: false
});
```

**Comment by gkalpak** [comment] 2016-06-07 07:02
Closing as we don't have a demo and it seems to be expected behavior anyway.

**Closed by gkalpak** 2016-06-07 07:02 UTC
Labels: component: $location, needs: more info, type: bug
