### ISSUE TITLE
Directive is added twice to angular cache

### ISSUE THREAD

**Issue by douglascvas** [angular/angular.js#13389] opened 2015-11-26 16:15 UTC
Consider the following situation:

Directive A has an isolated scope.
Page A loads, registers directive D but does not use it in the DOM.
- Directive D is registered
- Angular adds this to an array in the internal object 'hasDirectives', but does not add to the 'instanceCache' since the directive factory for D was not yet used

Now I navigate to another page, that also registers the same directive, but this time uses it in the DOM.
- Directive D is registered again
- Angular adds it again to the array in 'hasDirectives'
- Angular compiler finds the DOM element and calls the directive factory
- The directive factory adds the TWO directive instances to the private factory array 'directives' and return it to be stored in the 'instanceCache'
- Angular tries to get the directive using the $injector.get, which one gets it from the cache.

Result: it throws an error of multiple directives requiring isolated scope.

Why not initiating the angular cache with the directive whenever it is registered?

**Comment by Narretz** [comment] 2015-12-01 10:30
Can you show an example where this happens? I'm not sure how you could add directives at runtime.

**Comment by douglascvas** [comment] 2015-12-04 14:11
Calling $compileProvider.directive
I do this in order to register lazily the components.

```
app.config(['$compileProvider', function ($compileProvider) {
   app.lazyDirective = $compileProvider.directive;
});

....
// somewhere in time:
app.lazyDirective('myDirective', function(){ ... });

**Comment by Narretz** [comment] 2015-12-04 14:19
Ok. But config is run once on app start, how do you register the same directive twice? Do you have multiple apps on the page?

**Comment by douglascvas** [comment] 2015-12-04 14:47
I use ui-router as routing framework and requirejs to fetch the javscript files.

```Javascript
function resolve(dependencies) {
      var self = this;
      if (!(dependencies instanceof Array)) {
        dependencies = [dependencies];
      }
      return ['$q', '$rootScope', '$injector', function ($q, $rootScope, $injector) {
        var deferred = $q.defer();
        require(dependencies, function () {
          var modules = Array.prototype.slice.call(arguments),
            buildResult = modules.map(function (buildModule) {
              if (typeof buildModule === 'function') {
                return $q.when(buildModule(app, $injector));
              }
            }).filter(function (value) {
              return !!value;
            });
          return $q.all(buildResult).then(function () {
            deferred.resolve(modules);
          });
        });
        return deferred.promise;
      }];
    };

// In ui-router routes configuration:
myPage: {
  resolve: {
    page1Dependency: resolve('myDirectiveJS');
  }
}
```

This way, as soon as I navigate, I fetch the javascripts for the new page using requirejs. RequireJS fetches the javascript (which one exports a build function that accepts as parameter my app) and call its build function passing the app as parameter.

```Javascript
// myDirectiveJS.js
define(function (require) {
  function myDirective() {
    return {
      require: [],
      controller: function () {
      },
      link: function (scope, element, attributes) {
         ...
      }
    };
  }

  function build(app) {
    app.lazyDirective('myDirective', [myDirective]);
  }
  return build;
});

```

This way I am able to load a smaller JS in the application startup, and load the others on demand, as soon as the user navigates in the website.

**Comment by Narretz** [comment] 2015-12-14 14:48
I'd like to see this setup in a minimal demo. Can you put it on a plnkr.co or similar?

**Comment by gkalpak** [comment] 2016-06-03 19:43
Closing due to lack of reproduction. Feel free to re-open if you can provide one.

**Closed by gkalpak** 2016-06-03 19:43 UTC
Labels: component: $compile, needs: more info
