### ISSUE TITLE
Update repo README and angularjs.org landing page with 1.7/LTS information

### ISSUE THREAD

**Issue by peterblazejewicz** [angular/angular.js#16458] opened 2018-02-18 10:56 UTC
**I'm submitting a ...**
- [x] other

Hi team,
Can you consider adding a paragraph like this below one, taken from [Medium blog post](https://blog.angular.io/stable-angularjs-and-long-term-support-7e077635ee9c):

> AngularJS is planning one more significant release, version 1.7, and on July 1, 2018 it will enter a 3 year Long Term Support period.

The information in this blog post has some significant value and repercussion and I think it should be somehow more prominent, better visible, allowing all interested parties to make better decision in future.

Thanks!

**Comment by Narretz** [comment] 2018-02-19 09:51
closing as dupe of https://github.com/angular/angular.js/issues/16058

**Closed by Narretz** 2018-02-19 09:51 UTC

**Comment by peterblazejewicz** [comment] 2018-02-19 10:29
Hi
IMO that's not the same and this is not a dup. I don't want to have a list of EOL/LTS/etc per release (be pragmatic, this is Angular 1.*). What I ask is to have a word from dev/maintaince team that 1.7 version is the last one and it will have an LTS status for 3 years, exactly as worded in linked blog post. 
Thanks!

**Comment by Narretz** [comment] 2018-02-19 10:47
Well that's just a subset of a version support list. Anyway @petebacondarwin wrote the blogpost and is assigned to the version support changes so I expect the content of the blog post to be included

**Comment by peterblazejewicz** [comment] 2018-02-19 17:21
thx for update!
