### ISSUE TITLE
Model value not properly updating on select list with ngModel and blank default option

### ISSUE THREAD

**Issue by chalisegrogan** [angular/angular.js#4316] opened 2013-10-07 18:41 UTC
When tabbing into a select list with ng-model directive and a blank default option, the model value does not get properly updated when using arrow key to select the second option in the list. This only seems to happen on the second arrow key press after tabbing into the select list. The model is first updated on the initial selection but not on the second.

A Plunker with the repro steps and showing the issue in action is here: http://plnkr.co/edit/8bIbeUmdZfJ95lA5ssbE?p=preview

**Comment by Narretz** [comment] 2015-09-22 11:51
Duplicate of https://github.com/angular/angular.js/issues/9134

**Closed by Narretz** 2015-09-22 11:51 UTC
Labels: browser: chrome, component: forms, frequency: low, needs: investigation, type: bug
