### ISSUE TITLE
Hashbang browser reload issue

### ISSUE THREAD

**Issue by ahmednuaman** [angular/angular.js#5963] opened 2014-01-23 21:30 UTC
Here's the scenario: 
1. Create an app that uses `ngRoute`
2. Load the app in a non history API browser, like IE8 or IE9
3. Notice how the app is loaded twice:

![non-history-api](https://f.cloud.github.com/assets/99223/1989313/31820b3a-8475-11e3-8c29-10098a25701c.gif)

Compare this to, say, Chrome:

![history-api](https://f.cloud.github.com/assets/99223/1989314/3af488fa-8475-11e3-9cba-ebf5eec5d5f4.gif)

My app is loading `AppController` that runs `aService` and this makes a call to `/data.json`. Notice how the hashbang browser makes the request twice, this is because the app is loading twice.

Here's the source code of the example: https://github.com/ahmednuaman/angular-hashbang-reload

I'm going to have a trawl through the source code and work out a way of delaying the app loading until `ngRoute` has resolved, rather than cancelling it half way and hoping for the best.

**Comment by Icestorm0141** [comment] 2016-06-27 19:15
@ahmednuaman I know this is a pretty old thread but where did you put that hack? I'm not seeing it in your git repo code and the referenced [fix above](https://github.com/angular/angular.js/pull/5972) doesnt really do anything. If the code reads:
```
if (!$sniffer.history) {
       return $location;
}
$browser.url($location.absUrl(), true);
```
my app still loads twice. But you mentioned a different fix //yolo IE....where did you end up putting that in the code?

**Comment by gkalpak** [comment] 2017-01-03 21:14
I [can't reproduce it][1] since on v1.5.10/v1.6.1. It seems to have been fixed at some point. Closing...

[1]: https://codepen.io/ExpertSystem/pen/xgxYwM?editors=1011

**Closed by gkalpak** 2017-01-03 21:14 UTC
Labels: browser: IE8, browser: IE9, component: ngRoute, frequency: moderate, needs: investigation, severity: broken expected use
