### ISSUE TITLE
Empty message exception on Firefox before a json call

### ISSUE THREAD

**Issue by kgeoir** [angular/angular.js#14736] opened 2016-06-08 10:09 UTC
I have a bug difficult to reproduced only on firefox (46.0.1). I created a service like this:

```
angular.module('MyApp').factory('MyService', function($resource) {
  return $resource('pro/api/affiliation', {},
    {
      create: {method:'POST', url: '/api/MyService/'},
      destroy: {method:'DELETE', url: '/api/MyService/:id', params: {id: '@id'}}
    }
  );
});
```
The call is not even triggered because the exception happens before

`Exception { message: "", result: 2153644038, name: "", filename: "http://localhost:3000/assets/angula…", lineNumber: 11822, columnNumber: 0, data: null, stack: "createHttpBackend/<@http://localhos…" }
`
Stack:
```
consoleLog/<() angular.self-a3680fff57179d0080f9d5748ca2a23e287fbbf4425e8199ec882f4c37ff01f7.js:13643
$ExceptionHandlerProvider/this.$get</<() angular.self-a3680fff57179d0080f9d5748ca2a23e287fbbf4425e8199ec882f4c37ff01f7.js:10288
processQueue() angular.self-a3680fff57179d0080f9d5748ca2a23e287fbbf4425e8199ec882f4c37ff01f7.js:16113
scheduleProcessQueue/<() angular.self-a3680fff57179d0080f9d5748ca2a23e287fbbf4425e8199ec882f4c37ff01f7.js:16121
$RootScopeProvider/this.$get</Scope.prototype.$eval() angular.self-a3680fff57179d0080f9d5748ca2a23e287fbbf4425e8199ec882f4c37ff01f7.js:17379
$RootScopeProvider/this.$get</Scope.prototype.$digest() angular.self-a3680fff57179d0080f9d5748ca2a23e287fbbf4425e8199ec882f4c37ff01f7.js:17192
$RootScopeProvider/this.$get</Scope.prototype.$apply() angular.self-a3680fff57179d0080f9d5748ca2a23e287fbbf4425e8199ec882f4c37ff01f7.js:17487
ngEventHandler/<() angular.self-a3680fff57179d0080f9d5748ca2a23e287fbbf4425e8199ec882f4c37ff01f7.js:25178
jQuery.event.dispatch() jquery.self-25ca496239ae8641a09627c8aace5863e7676e465fbb4ce81bc7eb78c4d15627.js:4737
jQuery.event.add/elemData.handle() jquery.self-25ca496239ae8641a09627c8aace5863e7676e465fbb4ce81bc7eb78c4d15627.js

```

**Comment by gkalpak** [comment] 2016-06-08 11:29
It is next to impossible to investigate based on the provided info. Could you create a reproduction (e.g. using CodePen, Plnkr etc) ?

**Comment by Narretz** [comment] 2016-06-13 09:40
I'm going to close this issue because we have no reproduction of the issue. Feel free to reopen this issue if you can provide a reproduction (ideally a runnable demo in a https://plnkr.co or similar).

**Closed by Narretz** 2016-06-13 09:40 UTC
Labels: browser: Firefox, needs: more info
