### ISSUE TITLE
$location + html5 mode + legacy browser + #url('/newUrl') => full page reload

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular.js#1102] opened 2012-06-29 19:11 UTC
it seems that we do something wrong when $location is in html5 mode and we run in a browser that doesn't support history.pushState and we change url with $location#url() method.

```
angular.module('myApp', [])
    .config(function($locationProvider){
        $locationProvider.html5Mode(true).hashPrefix('!');
    }
);

function MyCtrl($scope, $location) {
   $scope.changeURL = function() {
        $location.path('/myPath');
  }
}
```

```
<a href ng-click="changeURL()">click here to see full page reload</a>
```

originally reported at: https://groups.google.com/forum/?fromgroups#!topic/angular/k-i6UYa7KpQ

**Comment by mblasi** [comment] 2015-01-09 16:18
Hi, I have same issue using chrome.
html5mode is set as true, and $location.path('/any/path') is causing full reload.
I'm using angular-1.3.0-beta.17 
Any suggestion or workaround?

**Comment by pkozlowski-opensource** [comment] 2015-01-09 16:21
@mblasi 1.3.0-beta.17 is several months old - please try the latest 1.3.x version and open a separate issue with a clear reproduce scenario if you are still bumping into problems.

**Comment by Narretz** [comment] 2016-06-03 19:26
Due to the vast number of reports here without a clear reproduction, I'm gonna close this issue. I assume the problem has been fixed in one of the later releases.

**Closed by Narretz** 2016-06-03 19:26 UTC
Labels: component: $location, component: ngRoute, frequency: moderate, Lots of comments, type: bug
