### ISSUE TITLE
docs page is not loading properly.

### ISSUE THREAD

**Issue by nikhilvm1993** [angular/angular.js#15568] opened 2017-01-03 09:38 UTC
**Do you want to request a feature or report a bug?**

Bug

**What is the current behavior?**

In chrome the selected page is not loading properly .please see the below image.
![capture](https://cloud.githubusercontent.com/assets/12045611/21604116/61f2cd84-d1c7-11e6-9430-7e8d425683ee.PNG)

**Comment by gkalpak** [comment] 2017-01-03 10:47
This is due to Chrome blocking some features (i.e. `document.write`) on slow networks. It is in our plans to fix this. (Sorry, for the inconvenience in the meantime 😞)

Closing, since the issue is being tracked in #15396.

**Closed by gkalpak** 2017-01-03 10:47 UTC
