### ISSUE TITLE
Controllers on directives should be able inject in parent directives

### ISSUE THREAD

**Issue by heneryville** [angular/angular.js#11267] opened 2015-03-06 17:06 UTC
Directives that require a parent controller should be able to inject those parents into their own controller.

Currently it is possible to get controllers on parent elements in the link function. It would be nice if $compile made these parent controllers injectable into that directives controller.  The current workaround would be to add the controller to the scope in the link function, which the controller can also access.

Expected functionality is in this plunker. Expected behavior is that there is no error and blah is injected into blah2. Actual functionality an error occurs saying blahProvider cannot be found.

http://plnkr.co/edit/QXnplKN0asljpKif1qzm?p=preview

**Comment by Narretz** [comment] 2015-03-08 13:04
Hi, this is a dupe of https://github.com/angular/angular.js/issues/5893

**Closed by Narretz** 2015-03-08 13:04 UTC
