### ISSUE TITLE
IE 11 animates ng-class related transition on refresh

### ISSUE THREAD

**Issue by maripuhakka** [angular/angular.js#10959] opened 2015-02-04 07:48 UTC
I am using css transition to animate an element margin depending on applied class. This class is controlled by AngularJS 1.3.11 ng-class directive. Chrome and Firefox don't show the animation on page load and refresh, which is desirable. IE 11 on the other hand shows the animation if there is evaluated content within the animated element.

Compare <a href="http://plnkr.co/edit/qz2hG5JAxSgsFVKWu1FW?p=preview">the plunker</a> with IE and Chrome and click refresh button on preview window to see how IE animates on page load.

Is this a bug? AngularJS documentation says "Are animations run when the application starts? No they are not. ..."

**Comment by bruunofco** [comment] 2015-02-04 13:41
Hello friend,

I believe it is not a bug angularjs, I believe the problem is occurring because it is being rendered in index.html which is the first file to be loaded, I believe that if carrengando the template for include or route would not have this problem.
A not very correct solution would be to apply:

var app = angular.module('plunker', []);

app.controller('MainCtrl', function($scope, $timeout) {
  
  $scope.indent = false;
  $scope.message = 'Hello World';
  
  $timeout (function () {
    $scope.indent = true;
  }, 10);
  
  $scope.isIndent = function() {
    return $scope.indent;
  }
  
  $scope.toggle = function() {
    $scope.indent = !$scope.indent;
  }
});

Hope this helps.

**Comment by maripuhakka** [comment] 2015-02-05 10:18
Initially the problem occurs not in index.html but in a template in route. The plunker is an example to focus on the problem.

Adding timeout causes the animation appear on page load also in other browsers, which is not what I want. It is expected as class is set outside the context of page load.

**Comment by bruunofco** [comment] 2015-02-05 17:20
Can I See,

What do I want to show is that the angle is doing its job, the problem is that it is performing the task of adding the class before the browser to render the screen, that is why you can not see the effect

**Comment by matsko** [comment] 2015-04-10 17:18
@maripuhakka this actually has nothing to do with ngAnimate and Angular. Firstly because ngAnimate isn't loaded, second because transitions (without ngAnimate) are handled at the mercy of the browser.

So when the class is added (in this case `.group-indent`) then the transition will fire (which is on the existing class on the element). By default, any CSS classes added and removed on an element are picked up as transitions in this case. When the page loads, everything happens in the same synchronous flow (one operation after the other) without any pause. If there is a pause and then the class is added then the browser is able to do an animation. In this case there is no pause in execution, but IE doesn't care and just animates anyway.

Unfortunately the solution is to use a timeout, or you can do the following:

1) Add ngAnimate into your application.
2) Then set your transition code as follows:

```css
.group-indent-animate.ng-animate {
  transition: 1s linear all;
}
```

Unfortunately there's nothing we can do on the Angular side to prevent this happening. Closing this issue for now.

**Closed by matsko** 2015-04-10 17:18 UTC
