### ISSUE TITLE
AngularJS infinite digest messages too long

### ISSUE THREAD

**Issue by ilanbiala** [angular/angular.js#10629] opened 2015-01-03 19:56 UTC
Sometimes I get a message that's crazy long (8000 characters somehow)...it would be nice if the links were actually loadable in the browser (because mine isn't) and didn't go to an errors.angularjs.org page because then I have to be online to view the error...

**Comment by caitp** [comment] 2015-01-03 20:00
You can host these error pages yourself, they're on the angular repository under docs/content/errors

**Comment by pkozlowski-opensource** [comment] 2015-01-03 20:05
Another alternative is not to use minified version for development if you are not online....

**Comment by Narretz** [comment] 2017-02-16 14:53
Dupe of #15043

**Closed by Narretz** 2017-02-16 14:53 UTC
Labels: component: misc core
