### ISSUE TITLE
ngAria disables spacebar for contenteditable divs

### ISSUE THREAD

**Issue by Eblax** [angular/angular.js#16761] opened 2018-11-16 12:49 UTC
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**

If you have a div with contenteditable="true" and this div has an ancestor with an ng-click directive, and ngAria is being used, pressing spacebar does nothing when editing inside the contenteditable div.

**Expected / new behavior:**

Pressing the spacebar should result in a space being entered in the text.

**Minimal reproduction of the problem with instructions:**

- Include ngAria
- Put ng-click on a div
- Put contenteditable="true" on a div inside this div
- See that pressing the spacebar when editing text in this div does nothing
http://plnkr.co/edit/CqMNGYzinoYy8o3HawPw

**AngularJS version:** 1.7.5

**Browser:** [Chrome 71 | Firefox 63]

**Anything else:**

I fixed this by adding a check if element has "isContentEditable" property before blocking spacebar.

**Comment by petebacondarwin** [comment] 2018-11-16 14:01
Is this a result of fixing https://github.com/angular/angular.js/issues/16664?  by https://github.com/angular/angular.js/pull/16680?

**Comment by gkalpak** [comment] 2018-11-16 16:42
It is more like #16680 didn't entirely fix the issue caused by 6c224a2a6. So, if you have an `ngClick` handler on a contenteditable element (that is not an input/select/textarea/button), then spacebar will not work correctly.

Work-arounds:
- Use `ngKeydown`/`ngKeypress`/`ngKeyup` on the same element (and set it to an non-empty value).
- Use `ng-on-click` instead of `ng-click` (if you are are on latest 1.7.x).

If we wanted to fix it, it probably makes sense to also exclude `[contenteditable]` elements from this behavior of preventing spacebar.

**Comment by Narretz** [comment] 2018-12-05 07:36
Fixed by https://github.com/angular/angular.js/pull/16762

**Closed by Narretz** 2018-12-05 07:36 UTC
Labels: component: ngAria, type: bug
