### ISSUE TITLE
ng-repeat won't work if my object keys starting with "$" and there is no error messages

### ISSUE THREAD

**Issue by puncha** [angular/angular.js#11379] opened 2015-03-20 01:54 UTC
<div ng-app='app'>
      <h1 ng-repeat='(key,val) in {"SimpleKey":"This works fine"}'>{{key}}:{{val}}</h1>
      <h1 ng-repeat='(key,val) in {"Key/$/FOO":"This works fine"}'>{{key}}:{{val}}</h1>
      <h1 ng-repeat='(key,val) in {"$/FOO":"This does NOT work fine!"}'>{{key}}:{{val}}</h1>
    </div>

The related codes in angularjs:

    if (collection.hasOwnProperty(key) && key.charAt(0) != '$') {
        collectionKeys.push(key); 
    }

IMO, this is a limitation or a bug in AngularJs side. It is very inconvenient because each time to use ng-repeat to iterate over object keys, we need to ensure each key not start with $, or it won't work and there is no error messages.

Also there is a post on stackoverflow:
http://stackoverflow.com/questions/29141277/angularjs-ng-repeat-doesnt-work-if-the-key-starts-with

**Comment by wesleycho** [comment] 2015-03-20 04:15
$ is considered a private key to Angular (generally signifying API) - this is pretty well known, and I do not believe this should be modified in Angular.

**Comment by steida** [comment] 2015-03-20 04:37
Yet another HTML parser magic. Give up and use JavaScript for codding view.

**Comment by miraage** [comment] 2015-03-20 07:24
`$` and `$$` are reserved AngularJS internal prefixes. You should not use them.

**Comment by Narretz** [comment] 2016-02-08 22:59
Dupe of #6266

**Closed by Narretz** 2016-02-08 22:59 UTC
Labels: component: ngRepeat, type: docs
