### ISSUE TITLE
Making `angular.mock.inject` return stuff

### ISSUE THREAD

**Issue by qlonik** [angular/angular.js#15053] opened 2016-08-24 03:35 UTC
**Do you want to request a *feature* or report a *bug*?**
I would like to request the feature in the angular-mocks module, `angular.mock.inject` function.

**What is the current behavior?**
Right now test case functions that are passed into `it()` could also be wrapped using `angular.mock.inject` function. Some of those test case functions could return something when they finish execution. The `angular.mock.inject` function does not do anything with those values returned from test functions.

**What is the expected behavior?**
Is it possible to pass returned values to the "outside" from `angular.mock.inject` function? Usually there is only one function that is passed into `it`. So is it possible to return that value from the `inject` function? I see that `inject` function also supports multiple test functions, so in that case maybe array of results could be returned?

**What is the motivation / use case for changing the behavior?**
This feature would allow for integration with [jasmine-promises](https://www.npmjs.com/package/jasmine-promises) module. The module expect that the test case function will return the promise, so that it can seamlessly attach `.then(done).catch(done.fail)` on the promise, so the test case can finish or fail successfully.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
Suggestions how to implement fix are provided in the expected behavior section. Also note that jasmine-promises module does not support the case where the test function returns an array. In this scenario, jasmine-promises will have to be extended to support arrays.

**Comment by Narretz** [comment] 2016-08-24 15:35
Looks like a dupe of https://github.com/angular/angular.js/issues/13584

I think this should be easy to support, barring any issues that I cannot foresee.

**Closed by Narretz** 2016-08-24 15:35 UTC
