### ISSUE TITLE
angular-bootstrap's $uibModal

### ISSUE THREAD

**Issue by rtbm** [angular/angular.js#16596] opened 2018-06-11 14:50 UTC
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other 

**Current behavior:**

Angular's 1.7.1 update causes angular-bootstrap's 2.5.6 $uibModal.open throws an error `TypeError: ctrlInstantiate is not a function`.

**Expected / new behavior:**

Provide compatibility with significant, discontinued, commonly used library or examine workaround.

**Minimal reproduction of the problem with instructions:**

http://plnkr.co/edit/KTlq6CFUQbL03PK1XU7E?p=preview

**AngularJS version:** 1.7.1

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

**Anything else:**

https://github.com/angular-ui/bootstrap/search?q=ctrlInstantiate&unscoped_q=ctrlInstantiate - lib's $controller usage

**Comment by gkalpak** [comment] 2018-06-11 15:05
Duplicate of #16594.

**Closed by gkalpak** 2018-06-11 15:05 UTC
