### ISSUE TITLE
ngOptions problems with updating object properties in options array

### ISSUE THREAD

**Issue by tiaanwessels** [angular/angular.js#13435] opened 2015-12-03 09:10 UTC
The foillowing HTML

```
<!DOCTYPE html>                                                                 
<html>                                                                          
<script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.2.1/angular.min.js">  </script>                                                                     
<script src="test.js"></script>                                                 
<body>
<div class="ng-scope" ng-app="tstApp" ng-controller="tstCtrl">
<div>
        <select size="2" style="width: 100px"
                ng-model="selected"
                ng-options="i as i.name for i in items track by i.name"
        />
</div>
<hr/>
<div>
        <br/>Description: <input type="text" name="descr" ng-model="selected.descr"/><br/>
        <br/>Reference: <input type="text" name="ref" ng-model="selected.ref"/><br/>
</div>
</div>
</body>
</html>
```

and JS

```
var tstapp = angular.module('tstApp', [])
tstapp.controller('tstCtrl', function($scope) {
    $scope.items = [
                {
                        "name" : "ITEM1",
                        "descr" : "This is item1",
                        "ref" : "Reference1"
                },
                {
                        "name" : "ITEM2",
                        "descr" : "This is item2",
                        "ref" : "Reference2"
                }
    ];
        $scope.selected = $scope.items[0];
});
```

works when using 1.2.1 but change to 1.4.8 and changes to Description or Reference are not remembered

**Comment by lgalfaso** [comment] 2015-12-03 10:10
Can you please create a plunker with the example above?

**Comment by tiaanwessels** [comment] 2015-12-03 10:23
http://plnkr.co/edit/G7DNLp6eHz9BGqPZceRv

**Comment by tiaanwessels** [comment] 2015-12-03 10:26
I verified with 38.1.1 on Linux and latest Chrome on Windows.

**Comment by Narretz** [comment] 2015-12-03 13:18
Yes, there is definitely something odd going on. It seems like when using track by, the selected model is not a always a reference to the object in the options array. But the behavior is a bit erratic and definitely needs some investigating,

**Comment by tiaanwessels** [comment] 2015-12-03 13:22
Sorry, it is my first day with AngularJS so I will only be a spectator and leave it to the pros.

**Comment by MYSHLIFE** [comment] 2015-12-03 16:58
I meet this issue same as you, and i use ng-repeat in options to replace use ng-options in select tag.

**Comment by Narretz** [comment] 2018-03-20 13:10
Duplicate of https://github.com/angular/angular.js/issues/15980

**Closed by Narretz** 2018-03-20 13:10 UTC
Labels: component: forms, frequency: low, needs: investigation, severity: broken expected use, type: bug
