### ISSUE TITLE
'select' / 'ng-model' / 'ng-options' behaviour changed in 1.4.9

### ISSUE THREAD

**Issue by almilo** [angular/angular.js#14115] opened 2016-02-23 14:09 UTC
Dear angular guys,

after upgrading AngularJS from version 1.4.8 to 1.4.9 some unit tests in our project related with basic functionality of the 'select' / 'ng-options' / 'ng-model' directives are broken. When using 1.4.9 with a 'select' tag with 'ng-options' and 'ng-model', the corresponding option does not seem to be selected in the unit test.

**Reproducible:** always
**Browsers:** Chrome 45, Firefox 43
**Operating system:** Mac OS X Yosemite (10.10.3)

**Steps to reproduce:**
see plunker http://plnkr.co/edit/wlgE9zrTduqhlG0i8oGT?p=preview (first plunker version - angularjs 1.4.8 OK, last plunker version angularjs 1.4.9 NOK)

**Comment by Narretz** [comment] 2016-02-23 18:00
Do I understand correctly that only the test fails, but the select behaves correctly inside the app?

**Comment by Narretz** [comment] 2016-02-23 18:19
Ok, so for some reason if the first option is selected, the selected attribute is not set on it. But apart from that, everything seems to work correctly.

**Comment by gkalpak** [comment] 2016-02-23 22:27
This happens because (as an optimization) we check if `select.value === option.selectValue` ([here][1]), before doing "stuff" including setting the selected attribute. Apparently, the 1st option of a `<select>` gets automatically selected, so `select.value` will equal 1st option's `value` the first time this branch is reached. If the selected option that was determined by the `ngModel` value happens to correspond to the 1st `<option>` element, we skip the whole `if-block` (including setting the `selected` attribute).

[1]: https://github.com/angular/angular.js/blob/76f47d5632526f6d4d0c2f3f621956d86b3ab98e/src/ng/directive/ngOptions.js#L471

**Comment by almilo** [comment] 2016-02-24 08:57
@Narretz Yes, it is seems to be only observable through a test which checks the DOM but this can well be because of the explanation from @gkalpak here "the 1st option of a <select> gets automatically selected".
In my Plunker I am using JQuery instead of jqLite (to use attribute based support)

**Comment by almilo** [comment] 2016-02-24 09:00
@gkalpak any suggestion on how to rewrite such a test to know which option is selected without relying on the 'selected' attribute?

**Comment by gkalpak** [comment] 2016-02-24 09:23
@almilo, I rather think we should fix this in Angular. It's a bug imo.
If you want a temporary work-around for the test, you could do something like this:

```js
  var opt = $('[value="' + selectElement.val() + '"]');
  expect(opt.prop('selected')).toBe(true);
  expect(opt.text()).toBe(...);
```

**Comment by Narretz** [comment] 2016-02-24 09:32
You can also get the option that should be selected by index:
`selectElement.find('option').eq(2)` and the check the selected *prop*, not the attribute. Another possibility should be to access the selectElements `selectedIndex` property, which is afaik the canocal way of getting the selected option.

**Comment by Narretz** [comment] 2016-02-24 09:33
@gkalpak I'm not sure why it breaks with 1.4.9, because the line you've linked has been in the code for a year.

**Comment by almilo** [comment] 2016-02-24 12:07
@gkalpak if my opinion counts, it is a change in an expected behaviour, so yes it is a regression bug.
I switched anyway to use `select.selectedIndex` and `select.value` which is IMO a better approach than relying on DOM selectors.

Many thanks guys!!

**Comment by Narretz** [comment] 2016-02-24 15:11
So there's two things going on:
1.The line  @gkalpak mentioned is reponsible for the attribute not being set, because the browser has already selected the first option automatically, but it doesn't set the attribute in this case, only the property. Before https://github.com/angular/angular.js/commit/f7eab8d8fe8cadecaee425f0db0c74e48619310c, the order of fn calls was different, so this is why it worked. The easy fix for this is to always set the selected attribute even if the option is already selected.

2. jqlite and jquery differ with regard to what they return from .attr('selected'). jquery returns the actual attribute value, but jqlite returns 'selected' if the selected property is defined on the element (it does that for all boolean attributes). So `expect(options.eq(0).attr('selected')).toBe('selected');` currently works with jqlite but it doesn't with jquery. I'll have a look how query handles this.

**Comment by gkalpak** [comment] 2016-02-24 15:32
Wow, that's pretty unexpected behavior ftom jqLite :confused:

**Comment by Narretz** [comment] 2016-02-24 15:41
The code for that is very old - I suppose (hope) it's an workaround for IE <= 8

**Comment by Narretz** [comment] 2016-02-24 15:56
@mgol @jbedard Do you know how jquery handles `attr` for boolean attributes? I think it must be simpler than the code we use: https://github.com/angular/angular.js/blob/master/src/jqLite.js#L661-L664

**Comment by mgol** [comment] 2016-02-24 16:26
jQuery has a [boolHook](https://github.com/jquery/jquery/blob/8a91f8442f4d31bdd4b43035ee88d40fbb116f64/src/attributes/attr.js#L100-L112) that changes `.attr('aBoolAttr', anything) into `.attr('aBoolAttr', 'aBoolAttr')` (TBH I'm not sure if we still need that one... filed https://github.com/jquery/jquery/issues/2946 for that) and `.attr('aBoolAttr', false) into `.removeAttr('aBoolAttr')`. We have [a hook for buggy behavior of the `type` attribute in IE<11](https://github.com/jquery/jquery/blob/8a91f8442f4d31bdd4b43035ee88d40fbb116f64/src/attributes/attr.js#L72-L84) but that's about it. Otherwise we don't always reflect the attribute into the property, there's `.prop()` for that; and we certainly don't return a property state on the `.attr('aBoolAttr')` getter. It does seem this code should be reduced.

P.S. Please press `y` on the keyboard before copying a link to concrete lines in the code to make it point to a specific commit; otherwise the link will become useless once something changes on `master` in the file and it'd be good to keep it relevant.

**Comment by Narretz** [comment] 2016-02-24 16:35
Nice trick with the `y`.
In jqLite, only the read part of attr has the bug, write seems to be okay. It's not a big deal atm, but it would be nice to have it fixed. I think I'll open an issue about it. Can I assign you @mgol? Like I said, it's not pressing.

**Comment by mgol** [comment] 2016-02-24 16:48
@Narretz Sure, assign it to me, I'll have a look.

**Comment by mgol** [comment] 2016-02-24 16:56
Checking for the `specified` property is definitely a relic of IE<9 support, in modern browsers this property is obsolete and always returns true.

**Closed** 2016-02-28 15:16 UTC
Labels: component: forms, frequency: low, severity: confusing, severity: regression, type: bug
