### ISSUE TITLE
href is not generated when ui-sref is used after migration form AngularJS from 1.6 to 1.7

### ISSUE THREAD

**Issue by Zadvornyi** [angular/angular.js#16809] opened 2019-01-09 10:12 UTC
I have migrated for AngularJS 1.6.10 to 1.7.5. After migration almost, all links are broken. A href is not generated.

    <a href="" ui-sref="app.state1.substate">Link</a>

Expected Result:

    <a href="/app/state1/substate/" ui-sref="app.state1.substate">Link</a>

But after migration:

    <a href ui-sref="app.state1.substate">Link</a>

**Comment by petebacondarwin** [comment] 2019-01-09 10:23
This is a duplicate of https://github.com/angular/angular.js/issues/16734.  It will be included in the next release.

**Closed** 2019-01-09 10:23 UTC
