### ISSUE TITLE
ngDisabled reference highlights incorrect usage

### ISSUE THREAD

**Issue by LegalizeAdulthood** [angular/angular.js#10100] opened 2014-11-17 18:00 UTC
[ngDisabled](https://docs.angularjs.org/api/ng/directive/ngDisabled) starts out by showing a big code block of what **not** to do.  IMO, this is bad form, as folks tend to copy/paste the first thing that they see and the code block has no comments indicating that this is poor form.

I suggest the page be reworked to more closely resemble the documentation for [ngChecked](https://docs.angularjs.org/api/ng/directive/ngChecked), which handles the same problem but for the `checked` attribute instead of the `disabled` attribute.

**Comment by pkozlowski-opensource** [comment] 2015-02-22 15:52
This is duplicate of #11032 for which I've just sent a PR.

**Closed by pkozlowski-opensource** 2015-02-22 15:52 UTC
Labels: component: misc core, severity: confusing, type: docs
