### ISSUE TITLE
$resource: allow body in HTTP delete.

### ISSUE THREAD

**Issue by jpprins1** [angular/angular.js#12747] opened 2015-09-03 10:01 UTC
In resource.js:
520:   var hasBody = /^(POST|PUT|PATCH)$/i.test(action.method);

Maybe also add DELETE?  
($http supports delete with body)

Note: As far as I could find it looks like it's unclear (RFC) if body should be accepted for delete, but I needed this for an external API.

**Comment by pkozlowski-opensource** [comment] 2015-09-03 10:06
Duplicate of https://github.com/angular/angular.js/issues/8567 - currently `$http` does _not_ allow DELETE requests with body (see https://github.com/angular/angular.js/blob/c3a654b7c8e585b8fb9f90ece10ef54d19fd74c8/src/ng/http.js#L1113) so eventually changing this would be a prerequisite.

**Closed by pkozlowski-opensource** 2015-09-03 10:06 UTC
