### ISSUE TITLE
Possibly unhandled rejection: {}

### ISSUE THREAD

**Issue by EricBourland** [angular/angular.js#15516] opened 2016-12-18 07:43 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If a promise throws an exception, a useless error is now printed to the console instead of what went wrong: Possibly unhandled rejection: {}

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
http://plnkr.co/edit/PE1GPJSDUxRGiabjACCn

**What is the expected behavior?**
It should print the exception that was thrown and the stack trace

**What is the motivation / use case for changing the behavior?**
To help track down where/why the exception was thrown

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
It worked before, now in 1.6.0 it gives this new error message that swallows the exception

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
It happens because ToDebugString calls JSON.Stringify on the exception, which returns {}. it needs to handle error objects differently.

**Comment by junqdu** [comment] 2016-12-18 15:10
https://docs.angularjs.org/guide/migration#migrate1.5to1.6-ng-services-$http

**Comment by thany** [comment] 2016-12-19 15:14
Yes, this desperately needs fixing. This error is utterly useless.

Every time I see this one, I have to step into the `processChecks()` function using the debugger, and checking the `toCheck` variable to see what actual error is in there. Couldn't be more irritating when I'm trying to get something done.

**Comment by gkalpak** [comment] 2016-12-19 22:04
Closing as duplicate of #14631.

**Closed** 2016-12-19 22:06 UTC
Labels: branch: 1.6.x, component: $q, frequency: high, needs: investigation, severity: inconvenient, type: bug
