### ISSUE TITLE
TypeError: Unable to get property 'open' of undefined or null reference

### ISSUE THREAD

**Issue by dhiman252** [angular/angular.js#12609] opened 2015-08-18 05:58 UTC
I am using the angular js version 1.3.11 and facing this problem.

TypeError: Unable to get property 'open' of undefined or null reference
-at openSignIn (http://elocations.me/assets/js/custom.js:445:9)
-at Anonymous function (http://elocations.me/assets/js/app.js:253:18)
-at Anonymous function (http://elocations.me/assets/js/angular-1.3.11/angular.min.js:81:199)
-at Anonymous function (http://elocations.me/assets/js/angular-1.3.11/angular.min.js:112:333)
-at $eval (http://elocations.me/assets/js/angular-1.3.11/angular.min.js:126:182)
-at $digest (http://elocations.me/assets/js/angular-1.3.11/angular.min.js:123:278)
-at $apply (http://elocations.me/assets/js/angular-1.3.11/angular.min.js:126:469)
-at l (http://elocations.me/assets/js/angular-1.3.11/angular.min.js:81:487)
-at O (http://elocations.me/assets/js/angular-1.3.11/angular.min.js:86:99)
-at onload (http://elocations.me/assets/js/angular-1.3.11/angular.min.js:87:124)

The above working fine in FF and Chrome.

**Comment by pkozlowski-opensource** [comment] 2015-08-18 08:51
Looking at the stack trace the error is thrown from the application code, so not sure how we could help here, especially that the crucial code part wasn't shared. For now this sounds like a support question that should be asked using a dedicated channel: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

If you believe that the error is caused by a bug in AngularJS itself, please provide enough context / reproduce scenario as requested here: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#submit

Closing as not actionable in the current form.

**Closed by pkozlowski-opensource** 2015-08-18 08:51 UTC
