### ISSUE TITLE
$anchorScroll on root page

### ISSUE THREAD

**Issue by Grandiz** [angular/angular.js#12051] opened 2015-06-08 08:25 UTC
Hi. I have some issue this anchors and html5mode. If i go for example to domain/foo#bar, this work properly, but if i want go to domain/#bar i get redirection to domain/bar

**Comment by gkalpak** [comment] 2015-06-08 10:24
@Grandiz, does `domain#bar` work as expected ?
(This sounds more like a `$location` issue, rather than `$anchorScroll` (but I'm not sure yet).)

**Comment by petebacondarwin** [comment] 2015-06-16 11:31
@Grandiz - please provide a running example of this problem. It is very hard to help you otherwise.

**Comment by divmgl** [comment] 2015-07-15 04:51
This happens to me as well. If I route a URL which is formatted as "localhost:1337/applications/foo#bar" then my anchor will work as intended. However, "localhost:1337/applications/#bar" will scroll to my anchor and then immediately scroll all the way up. This is an extremely annoying issue that I hope I will be able to solve.

**Comment by petebacondarwin** [comment] 2015-07-15 11:45
Please can you provide a running example?

**Comment by Narretz** [comment] 2015-11-06 21:59
Closing because we don't have a reproduce scenario.

**Closed by Narretz** 2015-11-06 21:59 UTC
Labels: component: misc core, needs: more info
