### ISSUE TITLE
ngModelWatch breaks if $modelValue is object

### ISSUE THREAD

**Issue by serzh** [angular/angular.js#6648] opened 2014-03-11 17:53 UTC
When using ngModel inside custom directive there is a chance to break `ngModelWatch` fn. On the first run `ngModelWatch` will set `$modelValue` to `ngModelGet($scope)`. Then, if you change property of that scope var (ngModelGet($scope)) it will change the properties on the $modelValue, because it is the same object! So if you have some $formatters they won't be called at all.

Here is [plnkr](http://plnkr.co/edit/r3NEljUTUMsqqUJHoicr?p=preview) for demonstration.

**Comment by Narretz** [comment] 2015-09-11 09:47
Duplicate of https://github.com/angular/angular.js/issues/5449

**Closed by Narretz** 2015-09-11 09:47 UTC
Labels: component: misc core, frequency: moderate, severity: confusing, type: bug
