### ISSUE TITLE
angular.mock.inject.strictDi(value:boolean) is undocumented

### ISSUE THREAD

**Issue by rcollette** [angular/angular.js#15544] opened 2016-12-23 15:04 UTC
The function angular.mock.inject.strictDi(value) appears to be documented.  I would attempt perhaps to provide documentation but I am not even sure if this function is intended for use.

I tried

```js
beforeEach(()=> angular.mock.inject.strictDi(true));
beforeEach(angular.mock.inject(...));
```
And I wound up getting some errors about $delegate not being annotated in ui-router on a line where it is calling `injector.get`.  I'm not sure at this point if it's my own code (a state definition perhaps) or library code.

**Comment by gkalpak** [comment] 2016-12-29 13:09
It is intentionally undocumented, as it is not intended for "public" use. That said, it sounds useful for libraries to verify that they are `strictDi`-compatible.

I can't speak about the failures you are seeing without an actual reproduction (could be a library issue or a usage issue).

I am going to close this, since this is not actionable, but if you feel like it, you can open a PR for documenting `inject.strictDi()` and we can have further discussion there.

**Closed by gkalpak** 2016-12-29 13:09 UTC

**Comment by rcollette** [comment] 2016-12-29 15:32
Are internal methods supposed to be prefixed in some way like with $$?

**Comment by gkalpak** [comment] 2016-12-29 17:35
Internal/private methods on public objects should indeed be prefixed with `$$`. I assume `inject.strictDi` was not, because people were not supposed to access properties on `inject` anyway.
