### ISSUE TITLE
ngResource: non-array instance custom action that isArray tries to append results to non-array instance and fails.

### ISSUE THREAD

**Issue by janvogt** [angular/angular.js#10258] opened 2014-11-28 11:22 UTC
Calling an array returning request on an non-array object, like so
```js
ContainerObj = $resource('url.to/container/:id', {id: '@containerId'}, {
 getChildren: {
  method: 'GET',
  url: 'url.to/container/:id/children',
  isArray: true
 }
container = ContainerObj({id: 1})
children = container.$getChildren()
```
fails with
```
TypeError: undefined is not a function
    at [...]angular-resource.js:551:27
    at forEach ([...]angular.js:325:18)
    at $http.then.value.$resolved ([...]angular-resource.js:549:17)
    at deferred.promise.then.wrappedCallback ([...]angular.js:11561:81)
    at deferred.promise.then.wrappedCallback ([...]angular.js:11561:81)
    at[...]angular.js:11647:26
    at Scope.$eval ([...]angular.js:12673:28)
    at Scope.$digest ([...]angular.js:12485:31)
    at Scope.$apply ([...]angular.js:12777:24)
    at done ([...]angular.js:8371:45) 
angular.js:10061
```

I know, that instance methods are only documented for non-GET requests and those imply often returning the object itself (making the automatic assignment reasonable). But this is only implicit and it took me some time to figure out since AFAIK it is nowhere documented. So, this issue might just be a lack of documentation and/or a meaningful error-message.
On the other hand it would be a nice feature to have for use cases as the example above (hierarchical structured resources), so it could be seen as a feature request as well.
For the time being the workaround is obvious, when the reason is found:
```js
ContainerObj = $resource('url.to/container/:id', {id: '@containerId'}, {
 getChildren: {
  method: 'GET',
  url: 'url.to/container/:id/children',
  isArray: true
 }
container = ContainerObj({id: 1})
children = ContainerObj.getChildren({id: container.id})
```

**Comment by pkozlowski-opensource** [comment] 2015-01-20 15:32
Closing due to the lack of the reproduce scenario. Happy to re-open when we've got one.

**Closed by pkozlowski-opensource** 2015-01-20 15:32 UTC
Labels: component: ngResource, needs: more info, severity: confusing, type: bug
