### ISSUE TITLE
Angular-mock.js 1.5 is triggering scope.$destroy

### ISSUE THREAD

**Issue by aarongan** [angular/angular.js#14158] opened 2016-03-01 19:55 UTC
hi Angular Team, 

I have a problem when migrating from Angular 1.4.3 to 1.5. We are facing angular-mock issue which is triggering scope.$destroy when compile a template and digest/apply. So basically i have callback function in scope.$destroy and it get removed before my unit test.

And if i use Angular-mock.js from 1.4.3 it works fine. Please advise. 
Below are code that trigger the $destroy, which both 1.4.3 and 1.5 has same code but 1.4.3 doesn't trigger scope.$destroy. 

Thank you 

```js
if (injector) {
  injector.get('$rootElement').off();
  injector.get('$rootScope').$destroy();   --> this is triggering my directive scope.$destroy
}
```

**Comment by gkalpak** [comment] 2016-03-01 20:25
@aarongan, this should be happening **after** each test. It is difficult to know how this affects your test.
Could you post the relevant code (preferrably a live demo using CodePen, Plnkr etc) ?

**Comment by raftheunis87** [comment] 2016-03-08 07:29
@gkalpak 

In Angular 1.4.7, we had a test where we had the following afterEarch block (coffeescript):

`afterEach ->
  $scope.$destroy()
  $element.remove()
`

In 1.4.7 this was working, but on 1.5.0 it's not. I get the following error:

`TypeError: 'undefined' is not an object (evaluating '$scope.$destroy')`

if I remove the afterEach block, the test runs without errors. Is this something that is handled automatically by the new ngMocks?

**Comment by raftheunis87** [comment] 2016-03-08 09:54
@aarongan @gkalpak I have the same issue when upgrading from angular 1.4.7 to 1.5.0.

I'll see if I can write a codepen to duplicate the issue...

**Comment by aciccarello** [comment] 2016-03-08 21:00
@aarongan Possibly related #13985 discusses changes made in b75c0d8 which I think is causing your issue.

**Comment by raftheunis87** [comment] 2016-03-10 14:48
Hmm it's very hard to reproduce the issue with a codepen/plnkr. When I downgrade to angular-mocks 1.4.9 in combination with angular 1.5.0 I don't have any issues with my unit tests. In the controller that I'm testing I have the following code:

`$scope.$on '$destroy', ->
        myService.doSomething()`

That service is still available at the moment of testing. But in this service, I have some backend data that I want to do something with. Problem is that it is not available anymore on that time. I guess that angular-mocks is cleaning up the $rootScope and that gets me into trouble...

**Comment by raftheunis87** [comment] 2016-03-10 15:00
I've just rerun my unit tests and just removed the following line from angular-mocks:

`injector.get('$rootScope').$destroy()`

then all of my unit tests work flawlessly on angular-mocks 1.5.0.

**Comment by gkalpak** [comment] 2016-03-10 15:31
This is an indeication that your tests somehow rely on the scope not being destroyed after the test.
Are you using a scope from a previous testcase ?

Can you post the tests that cause this error ? Can you isolate them ?

**Comment by Narretz** [comment] 2016-04-06 15:43
I'm going to close this issue because we have no reproduction of the issue. Feel free to reopen this issue if you can provide a reproduction (ideally a runnable demo in a https://plnkr.co or similar).

It does sound like your tests might depend on state that is set up in a previous test, which is never a good idea.

**Closed by Narretz** 2016-04-06 15:43 UTC
Labels: component: ngMock, needs: more info, severity: regression
