### ISSUE TITLE
$location in hashbang mode stripping "windows drive name"-like prefixes even when encoded

### ISSUE THREAD

**Issue by jr314159** [angular/angular.js#5958] opened 2014-01-23 16:38 UTC
$location seems to be a little greedy in the way it is running ```decodeURIComponent``` on my links in ```parseAppUrl```.  This causes problems because it then runs ```removeWindowsDriveName``` on the parsed path and ends up dropping fragments from my links that should have been safe since they were encoded to begin with.  Here's my setup (using hashbang mode):

$routeProvider setup:
```coffee
  $routeProvider
    .when '/',
      controller: 'AllEventsCtrl'
      templateUrl: 'all.html'
      reloadOnSearch: false
    .when '/event/:event*',
      controller: 'EventDetailCtrl'
      templateUrl: 'detail.html'
      reloadOnSearch: false
```

Markup generating links (where encodeURIComponent is a filter that runs the function of that same name):
```html
<a ng-href="{{ '#/event/' + event.name | encodeURIComponent }}" title="{{event.name}}">{{ event.name }}</a>
````

When ```event.name``` has some nasty characters in it, like ```pv:/item/popup/```, the safely encoded output of this ng-href is ```http://localhost:3000/analyze/events/?org_id=2404#/event/pv%3A%2Fitem%2Fpopup%2F```.  Should be safe.

What happens is that when I navigate to this link, ```LocationHashbangUrl``` calls ```parseAppUrl```, setting ```this.$$path``` to "/event/pv:/item/popup/".  Then ```removeWindowsDriveName``` recognizes this as a windows drive name and strips it down to "/item/popup/".

My immediate fix would be to double-encode these strings in the links, and then when I need to reference ```$routeParams.event``` in my controllers, I'd need to decode it once.  This is a little ugly though so I'm wondering if the solution is to move the call to ```removeWindowsDriveName``` inside ```parseAppUrl``` before the path is decoded?  I'm not too clear on the purpose of ```removeWindowsDriveName``` so I'm not sure what's the best solution.  Thanks!

Using Angular 1.2.9.

**Comment by Narretz** [comment] 2016-10-18 12:55
I'm going to close this issue because we have no reproduction of the issue. Feel free to reopen this issue if you can provide a reproduction (ideally a runnable demo in a https://plnkr.co or similar. You can use this [Plunker Template](http://plnkr.co/edit/tpl:yBpEi4)).

**Closed by Narretz** 2016-10-18 12:55 UTC
Labels: component: $location, frequency: low, severity: broken expected use, type: bug
