### ISSUE TITLE
Animate crash: Cannot read property 'runner' of undefined in 1.4.0

### ISSUE THREAD

**Issue by robertftw** [angular/angular.js#11992] opened 2015-06-01 09:57 UTC
```
TypeError: Cannot read property 'runner' of undefined
    at angular-animate.js:2330
    at forEach (angular.js:336)
    at closeChildAnimations (angular-animate.js:2325)
    at queueAnimation (angular-animate.js:2148)
    at Object.$$AnimateQueueProvider.$get.push (angular-animate.js:2040)
    at Object.$AnimateProvider.$get.leave (angular.js:5200)
    at cleanupLastView (angular-route.js:913)
    at angular-route.js:942
    at publicLinkFn (angular.js:7387)
    at $get.boundTranscludeFn (angular.js:7533)`
```

I get it when using it with the following CSS:
```
.hide-fade.ng-hide-add, .hide-fade.ng-hide-remove {
  -webkit-transition:all linear 0.3s;
  -moz-transition:all linear 0.3s;
  -o-transition:all linear 0.3s;
  transition:all linear 0.3s;
  display:block!important;
}
.hide-fade.ng-hide-add.ng-hide-add-active,
.hide-fade.ng-hide-remove {
  opacity:0;
}
.hide-fade.ng-hide-add,
.hide-fade.ng-hide-remove.ng-hide-remove-active {
  opacity:1;
}
```

Does not happen while using 1.3.15

**Comment by Narretz** [comment] 2015-06-01 10:43
Can you please provide a reproduction in a plunker or similar?

**Comment by robertftw** [comment] 2015-06-01 13:35
I'll try, but might be difficult due to I found it in a large enterprise app when I updated to 1.4.0 so I had to revert back to 1.3.15 again.

**Comment by mafrost** [comment] 2015-06-04 09:18
I have the same issue in my large app when upgrading to 1.4.0, using ui-router if that could matter.

**Comment by parliament718** [comment] 2015-06-13 03:37
Yup I get the same issue. Just upgraded to 1.4 recently.

**Comment by Kerumen** [comment] 2015-07-14 09:54
I'm experiencing the same issue with UI-Router, Angular Material and Flexslider included in my app.
It's only appearing when Flexslider is loaded on a page so it could be related to Flexslider. Do you guys have Flexslider in your app?

**Comment by Narretz** [comment] 2015-09-19 10:54
Is this still an issue with the latest 1.4.6?

**Comment by robertftw** [comment] 2015-09-22 09:26
@Narretz Seems to be fixed now!

**Comment by Narretz** [comment] 2015-09-22 11:28
@robertftw Great, I'll close this then!

**Comment by Emnalyeriar** [comment] 2015-09-28 11:14
Sorry but this doesn't seem to be fixed. It just occured in my project.
Tried different angular and angular animate versions but the bug occurs in all versions combinations I tested.
The problem is I have a translate animation on ui-view just like [here](https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-animate-ui-view-with-ng-animate) and inside ui-view I have html section elements that have their own translate and transition css rules. When I turn off one or another it works fine but when both css animations are declared I get this error:

TypeError: Cannot read property 'runner' of undefined
    at angular-animate.js:2330
    at forEach (angular.js:336)
    at closeChildAnimations (angular-animate.js:2325)
    at queueAnimation (angular-animate.js:2148)
    at Object.and.$get.data.push (angular-animate.js:2040)
    at Object.$provide.$get.afterElement.leave (angular.js:5200)
    at Object.scope.leave (angular-ui-router.js:3890)
    at cleanupLastView (angular-ui-router.js:3941)
    at angular-ui-router.js:3969
    at publicLinkFn (angular.js:7387)

Tested on 1.4 and 1.4.6, ui router 0.2.15.

**Comment by Emnalyeriar** [comment] 2015-09-28 11:50
Found out that it works fine with this version combination: angular@1.3.15, angular-animate@1.3.15 and ui-router@0.2.13 - tbh no idea why.

**Comment by robertftw** [comment] 2015-09-29 07:24
@Narretz Sorry it's still there but happens more rarely now in 1.4.6.

**Comment by Narretz** [comment] 2015-09-29 08:51
That's bad. But we still need a demo, otherwise it's impossible to fix. Maybe another module (slider) uses $animate in a bad way?

**Comment by Emnalyeriar** [comment] 2015-09-29 09:57
I'll try to recreate this bug later and post it on jsbin or something.

**Comment by iskuhar** [comment] 2015-10-19 09:47
+1 Happens to me as well (1.4.5)

**Comment by roosnic1** [comment] 2015-10-29 13:40
I have this error in angularjs 1.4.7 with angular-animate 1.4.7 and can reproduce it. I also use the angular-ui-router 0.2.14 in my web app.

I have a ul list with the following a tag:
```html
<a ng-click="changeTabById(tab.id, tab.title)" >{{ tab.title }}</a>
```

and further down in the same html file the following tag which gets the content from the sub routes from the $stateProvider.

```html
<section ui-view></section>
```

The function ```changeTabById(id)``` executes a ```$state.go(...)```
```javascript
function changeTabById(id) {
    $scope.currentTabId = id;
    var cs = appCampaignService.getCampaignSettings();
    $state.go(id, {
        campaign_id: $scope.campaignInfo.id,
        date_from: (cs.startDate) ? cs.startDate.format('YYYY-MM-DD') : moment($scope.campaignInfo.start_date).format('YYYY-MM-DD'),
        date_to: (cs.endDate) ? cs.endDate.format('YYYY-MM-DD') : moment().subtract(1, 'days').format('YYYY-MM-DD'),
        campaign_ids: cs.relatedCampaigns.join(',')
    });
}
```

Now comes the interesting part. The error only occurs if ```$state.go(id,...)``` get's called twice with the same id. But once the error got thrown it get's thrown for every other ```$state``` change.

@Narretz Could you reopen this issue?

**Comment by Narretz** [comment] 2015-10-29 16:53
Hi @roosnic1 yes I will reopen the issue. Can you do two things for me:

1. Open an issue about this in the ui-router repo. It's possible that they need to adjust their code for 1.4.x
2. Put a demo of the problem occuring inside a plnkr.com or similar. This is important! If we don't have a reproduction, it's very difficult to fix a bug.

**Comment by chino23** [comment] 2015-11-06 08:50
I have the same issue.

The fix from @iskuhar works for me.

it seems when switching views (but to the same view with ui-router, just different stateParams) it tries to kill the animations that are not there anymore. That happens when I try to load another view before it has fully loaded if it's big html inside.

**Comment by weisk** [comment] 2015-11-09 20:26
+1

**Comment by jcicero518** [comment] 2015-11-14 06:06
The same issue happens for me when switching between tabbed ui-views. It only happens when switching from a view that has a select element with ng-repeated options. I'm guessing the additional scopes created by ng-repeat may be part of it, but not sure yet.

This quick hack works (for me anyways) if you don't have a lot of time (v 1.4.7):

switch (state) {
     case RUNNING_STATE:
         if (typeof animationDetails !== undefined) {
            animationDetails.runner.end();
            /* falls through */
         }
 .......

Sorry about the formatting issues, some of the MarkDown syntax escapes me at the moment. Basically it picks up on an animation in the RUNNING_STATE and ends it with animationDetails.runner.end();

But it tries to run through it a second time and by then animationDetails is no longer defined, hence the conditional check.

This is for angular-animate.js v.1.4.7. 

If people are still experiencing this I can add a plunk.

**Comment by mydnic** [comment] 2015-11-25 10:45
@jcicero518 How exactly do you implement your code snippet ? I encounter the same error in my application (v1.4.8).

**Comment by chino23** [comment] 2015-11-25 11:10
@mydnic use angular-animate.js instead of the minified version and search for the line
````
case RUNNING_STATE:
````
then add the if clause

**Comment by Narretz** [comment] 2015-11-25 11:53
Can somebody create a plnkr with a demo? It should be simple, but if it needs ui-view, then so be it.

**Comment by mydnic** [comment] 2015-11-25 13:39
Weird... your solution didn't work for me.
But if I use

```javascript
if (animationDetails !== undefined) {
  //
}
```
Instead of
```javascript

if (typeof animationDetails !== undefined) {
```

Then, it solves the problem :/

Also, I tried to build a plnkr but I didn't manage to reproduce the problem :(
On my side, the problem occur in a quite large application that uses also jQuery, jquery sliders, so it might be linked ?

**Comment by jcicero518** [comment] 2015-11-25 21:57
Yeah you need to use the un-minified version of angular animate, I forgot to mention that. Not good practice for production obviously but I always use it for development.

@mydnic : I have trouble reproducing it in a plnkr too. It seems to depend on what your CSS looks like as well.

Your fix makes sense, as typeof is returning the type of the object as a string. Something else that got lost in translation, it should be like this:

if ( typeof animationDetails !== 'undefined' ) { ... }   // notice the quotes

You can mess with the DOM in the link function - to a point at least. It's the controller you want to avoid DOM changes with. Either way, unless you let Angular know about the DOM changes with scope.$apply() it's watchers won't be synced correctly. Some jQuery that fires off events or changes the DOM could definitely cause a conflict.

I'll look into creating a plnkr again since more people are running into this issue.

**Comment by seza443** [comment] 2015-11-26 21:29
I had the same issue when running [Slick](https://github.com/vasyabigi/angular-slick)
My code to load Slick was simply
```
<slick class="slides" arrows="false" lazy-load="ondemand" auto-play-speed="6000" autoplay="true" slides-to-show="4" slides-to-scroll="1">
       <div ng-repeat="sponsor in sponsors">
                <a href="{{sponsor.urlWeb}}" target="_blank"><img data-lazy="{{sponsor.urlLogo}}"></a>
       </div>
</slick>
```
It loads images in a lazy way after the ```sponsors``` array is populated.
Simply adding a ```ng-if="sponsors" ``` condition to the Slick div solved the problem.

Final code
```
<slick class="slides" arrows="false" lazy-load="ondemand" auto-play-speed="6000" autoplay="true" slides-to-show="4" slides-to-scroll="1" ng-if="sponsors">
       <div ng-repeat="sponsor in sponsors">
                <a href="{{sponsor.urlWeb}}" target="_blank"><img data-lazy="{{sponsor.urlLogo}}"></a>
       </div>
</slick>
```

Don't know if it can be helpful to anybody

**Comment by pptp** [comment] 2015-11-27 09:57
@seza443, thank you! It helps me

**Comment by Narretz** [comment] 2015-11-27 10:21
@seza can you create a demo on plnkr.co etc. that shows the problem?

**Comment by Narretz** [comment] 2015-11-27 10:22
@seza443 can you create a demo on plnkr.co etc. that shows the problem?

**Comment by seza443** [comment] 2015-11-27 11:56
@Narretz Here you are : http://plnkr.co/edit/ZwzPuxw0Ymvke2coBNwi?p=preview

**Comment by Narretz** [comment] 2015-11-30 16:15
@seza443 Thanks! However, I can't see / force the error in the plnkr. What do I have to do to make the error appear?

**Comment by seza443** [comment] 2015-11-30 16:19
@Narretz 
1. We start at the /page1 page
2. Going to the /home page works fine and the carousel appears
3. Navigating to any page cause the 'runner' error (in the console log of the browser)

**Comment by Narretz** [comment] 2015-11-30 17:02
Ok, now I see it.

**Comment by weisk** [comment] 2015-12-01 02:49
Thanks @seza443 , that was exactly my problem too, using Slick.js

**Comment by jcicero518** [comment] 2015-12-01 21:37
@seza443 - Nice job. I think your fix nails it. That's something else that our apps have in common - they use Slick Slider.

**Comment by Narretz** [comment] 2015-12-01 21:46
Yes, thanks to @seza443 , especially for the demo and @iskuhar who was the first to find the fix. The fix will hopefully make it into the next releases (1.4.8 / 1.5.0-rc.1).
This seems to happen very often with sliders, there are at least 3 mentioned in this thread. In the case of slick it happens because the repeat elements are cloned, and the clones still have animation indicators on them, which confuses ngAnimate.

**Comment by jcicero518** [comment] 2015-12-01 22:14
@Narretz - When you say the clones still have animation indicators, are you talking about the "data-ng-animate" attributes they are given? I haven't done all that much with ng-animate yet so much of its internals are still a bit of a mystery.

**Closed** 2015-12-02 20:02 UTC
Labels: component: ngAnimate, needs: more info, severity: regression, type: bug

**Comment by Narretz** [comment] 2015-12-02 20:04
@jcicero518 Yes, that is exactly the problem.

**Comment by chino23** [comment] 2015-12-03 05:43
Thanks a lot @Narretz ! glad to see this fixed.

**Comment by jeffhuys** [comment] 2015-12-15 16:05
@seza443 Thank you so much. This helped me a lot. How did you debug this?

**Comment by RazzyJohnson** [comment] 2015-12-15 16:05
Thank you @seza443 this fixed our webapp! Much thanks!

**Comment by seza443** [comment] 2015-12-16 17:20
You welcome :)
@jeffhuys desesperate attempt...

**Comment by chino23** [comment] 2015-12-17 03:20
the fix made it to 1.5 rc0 already.

hope they'll push out 1.4.9 soon

**Comment by PLPeeters** [comment] 2016-01-12 09:47
Are there any plans to push this to 1.4.9 anytime soon? This is breaking our application and we'd prefer to avoid having to manually apply the fix.

**Comment by Narretz** [comment] 2016-01-12 10:56
There was an issue with the release process which delayed 1.4.9. We plan to release it this week.

**Comment by mcpDESIGNS** [comment] 2016-01-22 18:11
Also happening on 1.4.9 with bootstrap UI (latest version)
This will get patched in a minor bug fix release in 1.4.9 I'm guessing? @Narretz 
Appreciate it! (using the patch above for now)

**Comment by Narretz** [comment] 2016-01-22 19:09
@mcpDESIGNS This is fixed in 1.4.9, I just checked.

**Comment by mcpDESIGNS** [comment] 2016-01-22 22:13
Very strange! Okay thank you Narretz. It seemed to go away when I went down to 1.4.6, and happened when I upgraded. Must be some strange cache issue on my end. Thanks again! My mistake.

**Comment by mydnic** [comment] 2016-01-25 09:32
:+1: 1.4.9 works fine ! Thanks guys

**Comment by samy100** [comment] 2016-03-19 04:51
I'm experiencing a very similar issue. See angular/angular.js#13215
