### ISSUE TITLE
NgModelController: getter function gets assigned to $viewValue

### ISSUE THREAD

**Issue by denim2x** [angular/angular.js#14926] opened 2016-07-16 17:57 UTC
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When `$options.getterSetter` is `true` the getter function gets assigned to the `$viewValue` which causes the validators to be called prematurely.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
Have a directive on an `input` element which requires `ngModel` with a `preLink` function like this:
```js
function link (scope, element, attrs, model) {
  model.$options = { getterSetter: true };
  scope.test = function () { return 'foo' };
  model.$validators.test = function () {
    console.error('FAIL: validator called prematurely');
  };
}
```
The error message will be immediately printed to the console.

**What is the expected behavior?**
The getter function should never be assigned to the `$viewValue`.

**What is the motivation / use case for changing the behavior?**
The validators get called prematurely.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
I've checked this with Angular v1.5.7 and v.1.5.8 in Chrome 51 x64 on Windows 7 x64.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
This stacktrace is from Angular v1.5.7 (development version):
![image](https://cloud.githubusercontent.com/assets/8561801/16896264/212ad686-4b97-11e6-8216-c581b96e8c3a.png)

**Comment by gkalpak** [comment] 2016-07-16 19:48
You should probably not overwrite `$options` in such a way (but I am not sure if that is the problem here).
In fact, `$options` is private at the moment, so you shouldn't probably touch it anyway (let alone overwrite it entirely).

In any case, could you provide a runnable demo (e.g. using CodePen, Plnkr etc) or a complete code example with instructions on how to reproduce the issue? That would help investigate.

**Comment by denim2x** [comment] 2016-07-17 11:42
The best workaround is to replace [this formatter](https://github.com/angular/angular.js/blob/v1.5.7/src/ng/directive/input.js#L1100) with one that also accounts for when the controller has `$options.getterSetter` - here goes:
```js
function prelink (scope, element, attrs, ctrl) {
  // ...
  var list = ctrl.$formatters, safety = true;
  list[list.length-1] = function (value) {
    if (ctrl.$isEmpty(value))
      return value;

    const options = ctrl.$options;
    if (options && options.getterSetter && safety)
      return void(safety = false);

    return value.toString();
  };
  // ...
}
```

**Comment by gkalpak** [comment] 2016-07-27 08:37
Closing since we don't have a reproduction of the problem and it is most probably not a supported usecase.
<sub>Happy to reopen when/if we have the necessary info for further investigation.</sub>

**Closed by gkalpak** 2016-07-27 08:37 UTC
Labels: component: forms, frequency: low, needs: more info, severity: broken expected use, type: bug

**Comment by denim2x** [comment] 2016-07-31 17:08
To be honest, the best way is to simply ditch [`ngModelWatch`](https://github.com/angular/angular.js/blob/v1.5.8/src/ng/directive/ngModel.js#L860) as it's practically useless - I'd never really want to change the model value directly, I want the user to supply the value.
```js
function prelink (scope, element, attrs, ctrl) {
  // shameless elimination of the model watcher ;))
  scope.$$watchers.pop();
  scope.$$watchersCount--;
  // ...
}
```

 I'm sure there's a better way to accomplish this, but I'd stick to the *one-way* paradigm for now.
