### ISSUE TITLE
"Maximum call stack size" issue with Chrome 64 bit

### ISSUE THREAD

**Issue by krishm27** [angular/angular.js#15848] opened 2017-03-22 13:50 UTC
Hi,

I have Chrome (57.0.2987.110) 64-bit and angularjs version 1.6.3. When I try to open my application, I am getting the following error and the site does not load:

Uncaught RangeError: Maximum call stack size exceeded
    at Object.invoke (angular.js:5003)
    at angular.js:4805
    at forEach (angular.js:402)
    at createInjector (angular.js:4805)
    at doBootstrap (angular.js:1909)
    at bootstrap (angular.js:1930)
    at angularInit (angular.js:1815)
    at angular.js:33340
    at HTMLDocument.trigger (angular.js:3435)

I have tried grunting the angularjs file and also by using it separately. I have used older versions of angularjs as well but no matter what, I am getting the same issue. With 32 bit chrome, everything works fine. The site also works fine in IE-11.

Please look into this issue on priority as we have a deliverable planned soon.

Thanks
Krishnendu

**Comment by frederikprijck** [comment] 2017-03-22 13:55
Github issues are reserved for bugs and feature requests.

For general support questions, feel free to ask for help in any of the channels mentioned [here](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question).

**Comment by Narretz** [comment] 2017-03-27 07:15
I'm going to close this issue because we have no reproduction of the issue. Feel free to reopen this issue if you can provide a reproduction (ideally a runnable demo in a [Plunker](https://plnkr.co) or similar. You can use this [Plunker Template](http://plnkr.co/edit/tpl:yBpEi4)).

**Closed by Narretz** 2017-03-27 07:15 UTC
Labels: browser: chrome, needs: more info
