### ISSUE TITLE
Date filter timezone with day light saving time

### ISSUE THREAD

**Issue by craigfoden** [angular/angular.js#15837] opened 2017-03-21 10:49 UTC
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The date filter is ignoring the timezone when in a day light saving time switch over hour. As can be seen in the plnker all the dates are appearing as '02:17' even though the actual date time is set to '2017-03-26T01:17:00.000Z'. I'm currently not sure if this only applies to people within the same day light saving time switch over.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

https://plnkr.co/edit/ZnA9CyObpokL0qbcVQC5?p=preview
Screenshot added to show my output
![screen shot 2017-03-21 at 10 52 10](https://cloud.githubusercontent.com/assets/5611549/24144299/9714d90a-0e24-11e7-889b-192f1e425fa3.png)

**What is the expected behavior?**
When applying the timezone filter 'UTC', 'GMT', or '+0000' the daylight saving time should not be taken into consideration.

**Which versions of AngularJS, and which browser / OS are affected by this issue? Did this work in previous versions of AngularJS? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
Tried this in most popular browsers on windows and mac.

**Comment by gkalpak** [comment] 2017-03-21 13:03
What is your timezone? This seems like a duplicate of #14418.

**Comment by craigfoden** [comment] 2017-03-21 13:10
My timezone is GMT/BST but seems like the same bug. Apologies I didn't see the other thread.

**Comment by frederikprijck** [comment] 2017-03-22 14:14
If the issue occurs in Angular as well, I'd create an issue over there and reference #14418 if it's related.

**Comment by Narretz** [comment] 2017-03-29 13:06
Clsoing as dupe of https://github.com/angular/angular.js/issues/14418

**Closed by Narretz** 2017-03-29 13:06 UTC
Labels: component: filters, frequency: low, needs: investigation, resolution: duplicate, severity: broken expected use, type: bug
