### ISSUE TITLE
Adding support for memoize expression result on a single $digest loop

### ISSUE THREAD

**Issue by oriSomething** [angular/angular.js#14585] opened 2016-05-11 08:32 UTC
**Do you want to request a *feature* or report a ~~*bug*~~?**
Currently there is no cache for the same expression evaluation on the same scope on the same digest loop.
so it means if there is an expression that called with a specific function with the same params, it might not get the same result on a digest cycle.
i made a [demo](http://codepen.io/oriSomething/pen/EKebyy) and of course it's a bad example because it something you shouldn't do. but in this example if the function would use `Date.now()` there is no guaranty it would result the same in all expressions.
i know the problem with this feature that if won't done carefully it can lead to many breaking changes

**What is the current behavior?**
The same expression will evaluate number of times
http://codepen.io/oriSomething/pen/EKebyy

**What is the expected behavior?**
having a cache for expression result on a single `$digest` cycle which lead to more predicted results

**What is the motivation / use case for changing the behavior?**
- more predicated results
- not sure how much better pref it can make if any on the average use case

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
Tested agains 1.5.2 but i guess it's related to all versions

**Comment by frfancha** [comment] 2016-05-11 13:40
Functions in watchers are guaranteed to be called at least once in digest cycle.
So caching the result is absolutely out of the question.

**Comment by Narretz** [comment] 2016-05-12 12:05
I agree with @frfancha. 
In every digest, the result of an expression is checked at least twice (and a maximum of 10 times) to see if it is stable. If we do caching here, this would contradict the whole idea of a digest cycle.

**Comment by petebacondarwin** [comment] 2016-05-12 13:08
In your example you have a non-stable impure function that you are binding against. The way that Angular works is that if the value of an expression changes then it updates the UI. Of course since your function always changes then Angular can never stop updating the UI. This is caught, as @Narretz explains, by our digest mechanism and bails out after 10 iterations to prevent the browser locking and becoming unresponsive.

It is your responsibility as an app developer not to bind to (or watch) expressions that do not stabilize.

Interesting, though, the `$parse` service, which actually parses and evaluates Angular expressions does have some caching built in.  Consider the following interpolation: `{{a + b}}`. The $parse service is able to tell that the value of this expression will only change if either `a` or `b` have changed. If neither of those have changed then it doesn't bother to re-evaluate `a + b`.

This does indeed lead to performance gains but has no impact on the expected behaviour of the application.

Closing as this is not a valid behaviour for Angular to adopt.

**Closed by petebacondarwin** 2016-05-12 13:08 UTC
Labels: component: scopes

**Comment by petebacondarwin** [comment] 2016-05-12 13:11
Of course you can always "implement" this in your own application as follows: http://codepen.io/petebacondarwin/pen/wGObeZ
