### ISSUE TITLE
Unable to focus inputs inside modals with touch event on mobile devices

### ISSUE THREAD

**Issue by eng-almeida** [angular/angular.js#13786] opened 2016-01-17 20:38 UTC
I'm using $modal service from here: https://pineconellc.github.io/angular-foundation/ and I'm not able to focus an input inside this modal on a touch event using angular touch 1.4.3. Any suggestion?

**Comment by gkalpak** [comment] 2016-01-18 11:56
If it's only specific to when using the `$modal` service, then it sounds more like an issue for https://pineconellc.github.io/angular-foundation.

In any case, a live reproduction (e.g. using CodePen, Plnkr etc) would help investigate the problem.

**Comment by Narretz** [comment] 2016-01-18 12:05
It does sound similar to this issue, which plagues ngTouch for quite some time.
https://github.com/angular/angular.js/issues/12153

**Comment by Narretz** [comment] 2016-01-26 15:26
I do think it's the issue where the clickbusting fails when there's a parent elemetn with a click on it. I can't say for sure, but since there's no repro, I'm closing this issue.

**Closed by Narretz** 2016-01-26 15:26 UTC
Labels: component: ngTouch, frequency: low, severity: broken expected use, type: bug
