### ISSUE TITLE
Android Predictive Text and Submit

### ISSUE THREAD

**Issue by bradleymf** [angular/angular.js#14397] opened 2016-04-08 17:38 UTC
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

Bug with Android devices and Predictive Text

**What is the current behavior?**

1)	Type in text into an input/text area and leave it underlined (meaning the keyboard is still up and do not tap anywhere to take the focus off the input/text area), tap Submit/Save button and it doesn’t completely work
2)	Type in text into an input/text area and select the word from the Predictive Text Menu or tap the space bar and leave the word underlines (meaning the keyboard is still up and do not tap anywhere to take the focus off the input/text area), tap Submit/Save and it works
3)	Delete text from an input/text area and that focus in the input/text area (meaning the keyboard is still up and do not tap anywhere to take the focus off the input/text area), tap Submit/Save and it works

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

**What is the expected behavior?**
Pick up that text that is underlined from Predictive Text. It looks like it is binding with ng-model but when you hit the submit/save button it doesn't think it is there anymore...

**What is the motivation / use case for changing the behavior?**

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

We're using Angular 1.5.1. I don't know if this is a known issue or not. Works fine for iOS.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by gkalpak** [comment] 2016-04-09 16:17
It's not clear if this is an issue with Angular or Android/Browser (sounds more like the latter).
In  order to investigate this further, could you please provide the following:

* What is the latest Android version that this is known to affect.
* Which browsers is this known to affect ?
* Create a minimal live demo that shows the problem (e.g. using Plnkr, CodePen etc).

**Comment by bradleymf** [comment] 2016-04-13 16:35
Found this to be an issue with scrolling on an Android. So I implemented a scroll watch and if the user was scrolling and blurred the current focus.

If I entered text into a field and left it underlined with predictive text from Android, scrolled down to the button, and hit the button it would not work. But once I implemented the scroll watch, it worked without having to click the button twice.

**Comment by gkalpak** [comment] 2016-04-14 19:14
It seems like you got it working on your end.
I will close this, since it is not clear what the issue is (or if it's related to Angular).

Feel free to re-open or submit a new issue, if you can provide more details or a runnable demo.

**Closed by gkalpak** 2016-04-14 19:14 UTC
Labels: component: forms, frequency: low, needs: more info, severity: broken expected use, type: bug
