### ISSUE TITLE
In IE9, IE10, IE11 browsers, jqLite method after() causes exception when "parent" is null

### ISSUE THREAD

**Issue by SmilingJoe** [angular/angular.js#14552] opened 2016-05-02 20:43 UTC
This is a bug report for Angular 1.4.x/1.5.x on Internet Explorer 9+ browsers.

Under certain circumstances, the "after" method will be called where the first argument ("element") will have a "null" parentNode value in IE9+ browsers.

When this happens, the following call will cause an exception as "parent" is a null value:
`parent.insertBefore(node, index.nextSibling);`

I will be putting together a sample on jsfiddle tomorrow which should reproduce this behavior.

The expected behavior is for this method to check that "parent" is not null prior to executing the "insertBefore" function.

When this exception occurs, the JavaScript engine is broken so no further code will execute until the browser is refreshed.

This behavior does not manifest in Google Chrome or Mozilla Firefox.

Simply determining if "parent" is not null before proceeding with the rest of the function would resolve this issue.

    after: function(element, newElement) {    
        var index = element, parent = element.parentNode;
        if (parent != null){
            newElement = new JQLite(newElement);
            ...
        }
    },

Again, I will be posting a link to a jsfiddle tomorrow which should display the error.

**Comment by jdforsythe** [comment] 2016-05-03 20:34
This seems to be the same error as https://github.com/chinmaymk/angular-charts/issues/210

**Comment by Narretz** [comment] 2016-05-12 12:45
Still waiting for dat jsfiddle :)

**Comment by Narretz** [comment] 2016-06-02 13:08
I'm going to close this issue because we have no reproduction of the issue. Feel free to reopen this issue if you can provide a reproduction (ideally a runnable demo in a https://plnkr.co or similar).

**Closed by Narretz** 2016-06-02 13:08 UTC
Labels: browser: IE10, browser: IE11, browser: IE9, component: jqLite, needs: investigation, severity: inconvenient, type: bug

**Comment by Vadorequest** [comment] 2016-09-07 11:49
IMO, the proposed solution should be implemented (checking whether `parent` is defined or not to avoid uncatched exception). It shouldn't cause harm to check if the parent is defined or not before processing.

We are encountering the same issue on our side, in IE11.

**Comment by gkalpak** [comment] 2016-09-07 19:00
@Vadorequest, adding potentially unnecessary code in order to fix ghost bugs that we can't reproduce does harm. It increases the code size and especially hurt maintenability, which is a big deal for projects of this size.

Since you ran into this yourself, maybe you could provide a reproduction, so we have something tangible to work on.
