### ISSUE TITLE
chrome developer tool angularjs error url is not clickable

### ISSUE THREAD

**Issue by zeel** [angular/angular.js#12526] opened 2015-08-08 14:09 UTC
When error occurs in angularjs app, message in chrome developer tool have large url which when clicked opens only https://docs.angularjs.org/error/$injector/modulerr?p0=  truncating remaining parameters/values from url.

Thus it's some time difficult to understand the error message in chrome dev tool as it's also html encoded.

**Comment by pkozlowski-opensource** [comment] 2015-08-28 16:53
Duplicate of https://github.com/angular/angular.js/issues/10629

**Closed by pkozlowski-opensource** 2015-08-28 16:53 UTC
