### ISSUE TITLE
ngLocale error in publishExternalAPI

### ISSUE THREAD

**Issue by frodegil** [angular/angular.js#11836] opened 2015-05-08 08:03 UTC
I'm using version 1.3.15.
`publishExternalAPI(angular)` is called before I declare any new modules (and dependencies). And it seems to use `try...catch` as flow-control when adding the ngLocal module.
This is a problem because I want Visual Studio to break on javascript exceptions thrown in code.
Therefore I always get the ngLocal error when I refresh my SPA index.html.
The problem is:
```javascript
  angularModule = setupModuleLoader(window);
  try {
    angularModule('ngLocale');
  } catch (e) {
    angularModule('ngLocale', []).provider('$locale', $LocaleProvider);
  }
```
There might be a reason for the angularjs team to do this that I don't see.
During development I've temporarily changed it to:
```javascript
  angularModule = setupModuleLoader(window);
  angularModule('ngLocale', []).provider('$locale', $LocaleProvider);
```
Can it be fixed/re-written more permanently without `try..catch` flow-control?

Thanks

**Comment by lili21** [comment] 2015-05-15 09:19
What If I already have the ngLocale module ?

**Comment by frodegil** [comment] 2015-05-15 13:39
The framework should check with if statement or similar instead of relying on try..catch program flow.
```javascript
if(angularModuel.exists('ngLocale') === false) 
   angularModule('ngLocale', []).provider('$locale', $LocaleProvider);
```
The try...catch way its implemented right now makes Visual Studio debugger stop execution (every time I refresh the page).

**Comment by Narretz** [comment] 2015-05-18 16:27
This is a duplicate of https://github.com/angular/angular.js/issues/1248 I'll mark this one as 1.5 candidate, so it'll get on the agenda again.

**Closed by Narretz** 2015-05-18 16:27 UTC
