### ISSUE TITLE
Adding a HTTP interceptor causes a memory leak in phantomjs in Karma

### ISSUE THREAD

**Issue by KamBha** [angular/angular.js#15655] opened 2017-01-31 00:18 UTC
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**What is the current behavior?**
I have setup an http interceptor like this:-
```
(function() {
    'use strict';

    angular
        .module('agora')
        .factory('httpInterceptorService', httpInterceptorService);

    function httpInterceptorService(applicationDetailsService, loginDetailsService, $location) {
        return {
            request : handleRequest
        };

        function handleRequest(config) {

            if (!config.headers['X-Browser-Location'])
                config.headers['X-Browser-Location'] = $location.absUrl();

            return config;
        }
    }

})();
```

However, the fact we are adding a config.header seems to cause a memory leak in PhantomJS (and only PhantomJS)

I have setup a Karma project like this:-
```

'use strict';

module.exports = function(config) {

    config.set({
        autoWatch : false,

        ngHtml2JsPreprocessor: {
            stripPrefix: 'src/',
            moduleName: 'agora'
        },

        logLevel: 'WARN',

        frameworks: ['jasmine', 'bdd-using'],

        browsers : ['PhantomJS'/*, 'Firefox'*/],

        plugins : [
            'karma-phantomjs-launcher',
            'karma-firefox-launcher',
            'karma-ng-html2js-preprocessor',
            'karma-bdd-using',
            'karma-jasmine'
        ],

        preprocessors: {
            'src/**/*.html': ['ng-html2js']
        },

        exclude: [
            'src/assets/asynchScripts/infobox.js'
        ]
    });
};

```
I am using Angular 1.5.4 and running on Windows 7.

I appreciate that this may not be a problem with Angular, but thought I would start here in case this is an indication of a deeper problem with http interceptors.

Thanks.

**Comment by gkalpak** [comment] 2017-01-31 10:16
There is doesn't seem to be anything wrong with how `$http` interceptors are handled (and the fact that the issue only appears on PhantomJS seems to confirm that). In any case, more info is needed in order to investigate this further (e.g. a reproduction, how do you identify the memory leak, is the leak affected by the header name or value etc).

**Comment by Narretz** [comment] 2017-02-16 15:49
I'm going to close this issue because we have no reproduction of the issue. Feel free to reopen this issue if you can provide a reproduction (ideally a runnable demo in a [Plunker](https://plnkr.co) or similar. You can use this [Plunker Template](http://plnkr.co/edit/tpl:yBpEi4)).

**Closed by Narretz** 2017-02-16 15:49 UTC
Labels: component: ngMock, frequency: low, needs: more info, severity: memory leak, type: bug
