### ISSUE TITLE
bug with directive "replace" property

### ISSUE THREAD

**Issue by TekVanDo** [angular/angular.js#11977] opened 2015-05-29 13:34 UTC
When i insert the value of attribute with same name as one of the isolate scope property into directive template. Space symbol is appended to scope property.
http://jsbin.com/bohicegaka/3/edit?js,console,output

**Comment by ryanhart2** [comment] 2015-06-01 13:21
Is this a duplicate of https://github.com/angular/angular.js/issues/8132?

**Comment by TekVanDo** [comment] 2015-06-02 10:15
yas it's duplicate.

**Comment by Narretz** [comment] 2015-06-03 13:16
`replace: true` is deprecated. As noted in the linked issue, this bug will not be fixed.

**Closed by Narretz** 2015-06-03 13:16 UTC
