### ISSUE TITLE
ES6 code in new Angular 1.5 Component Router

### ISSUE THREAD

**Issue by glounder** [angular/angular.js#14382] opened 2016-04-06 12:21 UTC
While implementing the new Angular 1.5 Component Router in our app, I noticed a couple ES6 features in the library. 

- While running tests in PhantomJS, it failed on my menu tests because of references to 'Map'.
- Running the Angular Component Router fails in IE because of references to 'startsWith'.

I got around the problem by including babel-polyfill in our app.

**Comment by Narretz** [comment] 2016-04-06 15:39
Dupe of https://github.com/angular/angular.js/issues/14172

Yeah, we have to document this at least

**Closed by Narretz** 2016-04-06 15:39 UTC
