### ISSUE TITLE
ngModel looses dynamic binding for numbers when input is cleared

### ISSUE THREAD

**Issue by kimgraf** [angular/angular.js#11721] opened 2015-04-24 23:50 UTC
I'm adding inputs in several nested ng-repeat loops using a dynamic binding i.e. 
<input msli-is-string="v" class="inputleftalign" type="number" name="{{k}}" id="{{k}}" placeholder=""
                                   ng-model="refnode[controlkey][key][k]" >

The binding works fine as long as I don't completely clear the input value.  If I highlight the number in the input and replace it everything works fine but if I backspace out and clear the field the binding is lost.

**Comment by gkalpak** [comment] 2015-04-25 04:42
Could you provide a minima, live reproduction (e.g. using CodePen, Plnkr, JSFiddle etc) ?
The description is a little too vague.

**Comment by kentcdodds** [comment] 2015-04-25 12:48
[Here's an example](http://jsbin.com/lerope/edit) of what I think @kimgraf is talking about. I am unable to reproduce the issue however. Feel free to clone the example and demonstrate your issue.

**Comment by kimgraf** [comment] 2015-04-27 18:23
Thank you for your quick response and I've created a plunkr example with the issue it's a bit more complex than the one  Kent C. Dodds provided.  
http://plnkr.co/edit/j2vhfCuBZlzAwnD5Zg3X?p=preview  
Creating the plunker I've found the issue is with my is-number directive. 
 It appears for text the empty input is a 0 length string and for a number it's null which causes the loss of the reference.  
I don't know if you still consider this an issue but I don't know how fix it.
 
I'm also emailing Kent my findings
 
Thanks


 
Kim Graf
Tel: (250) 309-5472
 
 
--------- Original Message --------- Subject: Re: [angular.js] ngModel looses dynamic binding for numbers when input is cleared (#11721)

**Comment by kimgraf** [comment] 2015-04-27 18:24
http://plnkr.co/edit/j2vhfCuBZlzAwnD5Zg3X?p=preview  
Creating the plunker I've found the issue is with my is-number directive.
 It appears for text the empty input is a 0 length string and for a number it's null which causes the loss of the reference.  
I don't know if you still consider this an issue but I don't know how fix it.
 
It's worth noting this doesn't happen with the string.
 
Thanks for your quick response and help
 

 
Kim Graf
Tel: (250) 309-5472
 
 
--------- Original Message --------- Subject: Re: [angular.js] ngModel looses dynamic binding for numbers when input is cleared (#11721)

**Comment by kimgraf** [comment] 2015-04-27 19:10
So last update on this I've found if I remove the else in the is-number I get the behavior I need.  Sorry to have bothered you and thanks again for your help.
 
Kim Graf
Tel: (250) 309-5472
 
 
--------- Original Message --------- Subject: Re: [angular.js] ngModel looses dynamic binding for numbers when input is cleared (#11721)

**Comment by kentcdodds** [comment] 2015-04-27 19:13
You're welcome! Feel free to close this issue so the angular team knows they don't need to worry about it. Good luck!

**Comment by kimgraf** [comment] 2015-04-27 19:20
Closed all is good

**Closed** 2015-04-27 19:19 UTC
Labels: component: forms, component: ngRepeat, needs: more info
