### ISSUE TITLE
Strange behavior $scope.$watchCollection with the cloned objects (by angular.copy)

### ISSUE THREAD

**Issue by AbstractVisions** [angular/angular.js#13799] opened 2016-01-19 14:50 UTC
If collection Object is changed with use:
1. change not object property and then use `obj = angular.copy(obj)` - its work ok, 
but if it's changed with:
2. change element of object property of collection Оbject,  with type (element of Array, for example) and then use `obj = angular.copy(obj)` - follow that oldVal, and newVal - is equal in watcherFn !!!

For example:
http://plnkr.co/edit/dMZih1fChn6GE3zXEG38?p=preview
if change `obj.username` then ok, but if change`obj.aaa[0]`, then old and new val are equal in watcher function

**Comment by Narretz** [comment] 2016-01-19 16:08
Strange indeed. I suspect it has something to do with watchCollection only watching one level deep. You can work around this quite easily by using $watch('obj', actionFn, true) instead. watchCollection should be used when you have an array of values and you are removing / adding whole objects. watch with third argument is true compares the whole object, which looks like what you want to do.
Also, why are you copying $scope.obj on ng-change?

**Comment by frfancha** [comment] 2016-01-19 18:08
angular.copy is a deep copy, but watchCollection without deep watch maintains only a shallow copy (for performance reason) and therefore sends you as old object items containing the new values.
It is normal behavior, when you don't deep watch, you must not rely on "pointers" in old value but only on first level property. The same is true for normal $watch.

**Comment by petebacondarwin** [comment] 2016-01-19 18:31
Closing as this is the expected behaviour of `$watchCollection`.

**Closed by petebacondarwin** 2016-01-19 18:31 UTC
Labels: component: scopes, needs: investigation, severity: confusing

**Comment by AbstractVisions** [comment] 2016-01-19 20:20
Thanks for an explanation!

But ... if it's created a deep copy of "obj" then "obj"'s property "aaa" shall change and refer to other Array object and run watchFn. 
obj.aaa 'before' != obj.aaa 'after' angular.copy 
Why old value of obj.aaa doesn't refer to oldVal in watchFn?
__to frfancha:__ following your explanation shall be:
First $digest watchFn -  oldVal_1 shallow equivalent newVal_1, and not trigger whatchFn 
Second $digest watchFn (after deep copy) - newVal_2 != oldVal_1 and newVal_2.aaa != oldVal_1.aaa
and trigger watchFn with (newVal_2, oldVal_1), 
but  instead occurs Second watchFn trigger with (newVal_2, newVal_1).

Or in each cycle watcher's Value redefined by newVal even if newVal shallow-eq oldVal?
if it so, whether that it was better to exclude redefined Value in that case?
It would allow to trace more precisely changes and to trigger watchFn correctly if object-like property of Collection changes in functions runs inside $timeout
  
__to Narretz:__ i use angular.copy in ng-change for demo-example. 
If i use `$scope.obj.aaa = [$scope.obj.aaa[0], $scope.obj.aaa[1]]`  (create a new value of "obj.aaa" then folow the same strange behavior

A lot of thanks for consideration and further explanations!

**Comment by petebacondarwin** [comment] 2016-01-19 20:58
Here is a more comprehensive Plunker for you to play with: http://plnkr.co/edit/rc4s6le7ef3H85MjjHTp?p=preview

**Comment by AbstractVisions** [comment] 2016-01-19 22:29
It's Very visually, thanks a Lot !

Whether correctly I understand that in case of the current implementation of $watchCollection, if only updating of properties of nested object (for example obj.aaa[0]) and its cloning happens in the different $digest-cycle (for example, by using $timeout), then  $watchCollection launches watchFn once (of two or more $digest-cycle) with (oldVal, newVal), that which satisfy to the following:
 `newVal !== oldVal`  but `newVal` deep equivalent of `oldVal` ?

**Comment by petebacondarwin** [comment] 2016-01-20 07:49
`$watchCollection` and `$watch` (shallow) will both be triggered if the main object being watched is replaced with something new
`$watchCollection` will be triggered if any of its top level properties changes
`$watch` (deep) will only be triggered if a deep comparison of the nested objects is different, whether or not the actual object itself changes.

**Comment by frfancha** [comment] 2016-01-20 09:48
@AbstractVisions You should read chapter one of the book "Build your own angularjs" (from Tero Parviainen).
It explains extremely clearly what is the scope, the digest cycle, watchers, ... after that everything is clear and all behaviors that could seem strange with only superficial knowledge become perfectly logical and predictable.
My life with angularjs has changed after reading this book, thanks to Tero!
