### ISSUE TITLE
Error: Requested keys of a value that is not an object.

### ISSUE THREAD

**Issue by brunomacf** [angular/angular.js#10949] opened 2015-02-03 18:20 UTC
Everything working great with Chrome 40.0.2214.94 and Firefox 35.0.1, but when comes to test in Safari 8.0.2 i get the following error (i think the error is in $http module as you can see in call stack).

```
[Error] Error: Requested keys of a value that is not an object.
keys@[native code]
sortedKeys@http://localhost:10006/vendor/angular/angular.js:340:21
forEachSorted@http://localhost:10006/vendor/angular/angular.js:344:24
buildUrl@http://localhost:10006/vendor/angular/angular.js:9685:20
sendReq@http://localhost:10006/vendor/angular/angular.js:9575:25
serverRequest@http://localhost:10006/vendor/angular/angular.js:9335:23
processQueue@http://localhost:10006/vendor/angular/angular.js:13175:29
http://localhost:10006/vendor/angular/angular.js:13191:39
$eval@http://localhost:10006/vendor/angular/angular.js:14388:28
$digest@http://localhost:10006/vendor/angular/angular.js:14204:36
$apply@http://localhost:10006/vendor/angular/angular.js:14493:31
done@http://localhost:10006/vendor/angular/angular.js:9650:53
completeRequest@http://localhost:10006/vendor/angular/angular.js:9840:15
requestLoaded@http://localhost:10006/vendor/angular/angular.js:9781:24
	(função anônima) (angular.js, line 11598)
	(função anônima) (angular.js, line 8548)
	processQueue (angular.js, line 13183)
	(função anônima) (angular.js, line 13191)
	$eval (angular.js, line 14388)
	$digest (angular.js, line 14204)
	$apply (angular.js, line 14493)
	done (angular.js, line 9650)
	completeRequest (angular.js, line 9840)
	requestLoaded (angular.js, line 9781)
```

I'm using the latest version of angular (1.3.11).

**Comment by pkozlowski-opensource** [comment] 2015-02-04 05:02
@brunomacf could you please try to narrow it down a bit, ideally including a live reproduce scenario in plunker or similar? This would speed up things considerably. Thnx!

**Comment by lgalfaso** [comment] 2015-02-04 09:48
any chance that you are trying to make a call and the value of `params` is not an object?

**Comment by Morgul** [comment] 2015-02-04 16:32
I'm also running into this error. Interestingly, it appears to be related to $cacheFactory. I will attempt to build a reproducible plunkr.

**Comment by Morgul** [comment] 2015-02-04 16:43
@pkozlowski-opensource Yup, I get the error simply by creating an instance using $cacheFactory. See this plunkr:

http://plnkr.co/edit/N7PGzdR0r9wX71PbMo5z

You can comment everything out except line 4 in script.js and still get the error.

**Comment by Burstaholic** [comment] 2015-02-04 16:51
The same error occurs in Internet Explorer 11.

**Comment by pkozlowski-opensource** [comment] 2015-02-04 17:02
@Morgul it looks like the call to the $cacheFactory you are having is wrong - options should be an object and not a number: http://plnkr.co/edit/40gIlTjHCInzk61bk95Q?p=preview

@brunomacf @Burstaholic we _really_ need a reproduce scenario to nail this one...

**Comment by Morgul** [comment] 2015-02-04 17:09
@pkozlowski-opensource: Interesting, did that change in the 1.3 release? Because, the plunkr I posted exhibited exactly the same behavior described; in Chrome 40 it works, but on Safari it doesn't.

That code is a heavily simplified version of code from an angular 1.2 site I'd written that since upgrading to 1.3 was exhibiting this behavior (being broken on some but not all browsers). Simply changing to `{ capacity: 10 }` fixes the original on all browsers.

**Comment by pkozlowski-opensource** [comment] 2015-02-06 03:50
@Morgul there were several changes in 1.3.x but none to the cache / cache factory. This is why it is important to narrow down the problem. Does anyone has a valid reproduction scenario?

**Comment by jgatjens** [comment] 2015-02-13 16:21
I had the same error with this code above.      

      var sectionUrl = HOST + API_END_POINT + sectionName + '/';

      var Resource = function (data) {
        angular.extend(this, data);
      };

      Resource.query = function (params) {

        return $http.get(sectionUrl, { cache: APP_CACHE })
                  .then(function (response) {
                    var result = [];

                    angular.forEach(response.data, function (value, key) {
                      result[key] = new Resource(value);
                    });

                    return result;
                  });
      };


To fixed I changed to only return:

       return response.data;

**Comment by pkozlowski-opensource** [comment] 2015-02-28 13:31
Closing as we still don't have any live, reliable reproduce scenario... I would really love to fix this one but we can't do much for bugs that we can't see reproduced.... Re-opening as soon as anyone can share a plunker with reproduce!

**Closed by pkozlowski-opensource** 2015-02-28 13:31 UTC
Labels: component: $http, frequency: low, needs: more info

**Comment by HenriqueLimas** [comment] 2015-03-05 12:15
This problems it seems is related to the native Object.keys method when a non-object parameter is passed. On Chrome version 40 or superior, return an empty Array but in others Browsers like Firefox or Chrome 39 it throw an error.
The "angular.extend" method  uses the "Object.keys" and maybe it is better add a validation where the "Object.keys" method is used.

**Comment by sadu** [comment] 2015-03-19 10:36
I'm getting the same error on angular material (1.13), however the context is different. Mine comes up when using angular-material, the views render and works on Chrome 40+ and FF 36+ but it fails with console error:

on Safari 5.1
```
Error: [$injector:modulerr] Failed to instantiate module MYAPP due to:         angular.js:4121
[$injector:modulerr] Failed to instantiate module MYAPP.roles due to:
Requested keys of a value that is not an object.
```
on Chrome 37
```
Uncaught Error: [$injector:modulerr] Failed to instantiate module MYAPP due to:
Error: [$injector:modulerr] Failed to instantiate module MYAPP.roles due to:
TypeError: Object.keys called on non-object
   at Function.keys (native)
   at Object.extend (http://localhost/bower_components/angular/angular.js:411:25)
   at $RouteProvider
...
```
screenshots from browserstack confirms it is working only on Chrome 40+ and FF 36+. There is no coding errors inside the module as it works perfectly fine on the latest Chrome. I'd have provided a plunker link but my code is an internal project and under NDA. This however should reproduce easily with angular-material(on top of the angular seed).

Note: I am not aware of any compatibility restrictions angular material has, but it shouldn't matter in this case?

**Comment by mshaaban0** [comment] 2015-03-25 16:31
Check your http requests , you might passing keys that is not an object

**Comment by jcroughton** [comment] 2015-07-06 00:02
I recently had this issue though my circumstances / knowledge (lack of) may have contributed to it. Note, I am using ui-router and it's state management for routing.

In the site I was building I was doing a bit of 'funky' state param manipulation, programmatically building params on a certain state. I only had the Id's for the categories and I want to send the category name (pretty URL), so I use the Id's to retrieve the category names and manually build the state params. I squash the params not provided and replace with '~' in the URL (so additional further sub states still works ok).

I eventually tracked the issue to a $state.transitionTo call. Initially removing the ui-router options param of true (update the url in the location bar) helped. But further testing still resulted in occasional errors. Ultimately I tracked the error to the following location in angular.js (See Fix code block), explanation above code block.

Again, my use of programmatic state params / lack of knowledge may well have contributed to this and I may have only implemented a workaround for a problem I ultimately caused. Just wanted to forward my findings.

Thanks

************************************

Programmatic build of state params, transitionTo won't work if options true (update URL)
<pre>
var eventCategoriesToPass = {};

for (var i = 0; i < selectedEventCategories.length; i++) {
    var propertyName = 'eventCategory'+[i];
    eventCategoriesToPass[propertyName] = selectedEventCategories[i];
}

// Doesn't work
// $state.transitionTo('day-planner.event-categories.events', eventCategoriesToPass, true);
$state.transitionTo('day-planner.event-categories.events', eventCategoriesToPass);
</pre>
************************************

Fix

angular.js
line 411
<pre>
function extend(dst) {
  var h = dst.$$hashKey;

  for (var i = 1, ii = arguments.length; i < ii; i++) {
    var obj = arguments[i];

    // JC Update.
    // 19.09.2015
    // When using programmatic params (day-planner.module.js - state = day-planner.event-categories.events)
    // It seems this may receive a Boolean true.
    // This causes the original check to pass, but then Object.keys fails of course.
    // Amend to check for not boolean.
    // if (obj) {
    if (obj && typeof obj !== 'boolean') {
      var keys = Object.keys(obj);
      for (var j = 0, jj = keys.length; j < jj; j++) {
        var key = keys[j];
        dst[key] = obj[key];
      }
    }
  }
</pre>

**Comment by azatoth** [comment] 2015-09-23 09:03
I myself caught this issue having following "html":

```
<a ng-if="eq(company.state, 'active')" ng-show="isAdmin()" id="create-transaction-link" ng-click="$storage.$reset()" ui-sref=".create(company._id)" class="btn btn-primary">Create new transaction</a>
```

Fixed it by changing the ui-sref to:

```
ui-sref=".create({companyId:company._id})" 
```

i.e. spell out the object fully.

**Comment by ZaidAhmad2468** [comment] 2018-11-16 19:15
![untitled](https://user-images.githubusercontent.com/45063881/48642077-a17b2500-e9fd-11e8-8ca3-2b178d36238f.png)
Build successful but it not print anything on emulater.
I,m following this 

> link

 https://medium.com/react-native-training/react-native-navigation-v2-by-wix-getting-started-7d647e944132

**Comment by Morgul** [comment] 2018-11-16 20:03
@ZaidAhmad2468 I don't think you meant to post that to this item. Not only is this a very old, resolved issue, but it's for angular, not React/ReactNative.
