### ISSUE TITLE
Weird Interaction with $location.hash() and Chrome/Firefox

### ISSUE THREAD

**Issue by bobber205** [angular/angular.js#10659] opened 2015-01-07 00:28 UTC
When I enter the following into Chrome
```
http://www.example.com/enter/contest#top
```
it turns into

```
http://www.example.com/enter/contest/#top
```

This also happens when just running ```$location.hash("top")``` without any hashes in the URL.

This causes ```$location.hash()``` to be ```""```. I need this check because if I do ```$location.hash("top")``` in any repeated function I get ```#top#top```. I have a simple "is it already ```'top'``` if check but since chrome messes with the url, it's always blank.

```
$location.hash("top");
$anchorScroll();
```
makes the url fwiw

```
http://www.example.com/enter/contest/#top#top
```

Any ideas of a work around?

**Comment by Narretz** [comment] 2015-01-07 09:13
Hi, 
what version of angular are you using? And are you using html5Mode?

**Comment by bobber205** [comment] 2015-01-07 17:24
I'm using 1.3.6
Not using html5 mode.

**Comment by arpit2438735** [comment] 2015-01-08 11:32
`html5Mode` is feature given by Angularjs.Have a look to [HTML5Mode](https://docs.angularjs.org/guide/$location) link

**Comment by bobber205** [comment] 2015-01-08 18:26
Do I need to use html5mode() to use anchors?

**Comment by arpit2438735** [comment] 2015-01-09 10:27
No, it is disable by default angular append `/#/` after domain url

**Comment by martea** [comment] 2015-01-09 13:54
We've also encounterd this issue, with the latest 1.3.6
before when the hash was working was 1.3.4

have you changed the default from "##" to "#/" ?

anyhow the latest update as a small revision update, did something major.

**Comment by Narretz** [comment] 2015-01-14 20:41
@petebacondarwin this sounds like it is related to the changes we made for the hash-handling,

@bobber205 are you using any kind of routing at all, or are you using the hash simply for scrolling? Also, could you post a reproduction?

**Comment by bobber205** [comment] 2015-01-14 20:58
Simply for scrolling. We're using anchorScroll() afterwards (made sure that
wasn't the cause and it isn't)

Will post repo in a bit


On Wed, Jan 14, 2015 at 12:43 PM, Narretz <notifications@github.com> wrote:

> @petebacondarwin <https://github.com/petebacondarwin> this sounds like it
> is related to the changes we made for the hash-handling,
>
> @bobber205 <https://github.com/bobber205> are you using any kind of
> routing at all, or are you using the hash simply for scrolling? Also, could
> you post a reproduction?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/angular.js/issues/10659#issuecomment-69987543>
> .
>



-- 
Buoyancy and displacement float my boat.

**Comment by bobber205** [comment] 2015-01-14 21:09
Not able to produce a example on plunker because it keeps messing with the url/url is not handled in standard way. Without setting up my own hosting, do you guys know of another place I could demo this?

**Comment by bobber205** [comment] 2015-01-14 21:10
Code so far:
```html
<body ng-controller="MainCtrl">
    <a id="top">THIS IS THE TOP</a>
    
    <br/>
    <br/>
    <br/>
    <br/>
    <a id="bottom"></a>
    BOTTOM
  </body>
```

```javascript
app.controller('MainCtrl', function($scope, $location, $anchorScroll, $timeout) {

  $timeout(function () {
    console.log("scrolling!");
      $location.hash("bottom");
      debugger;
     $anchorScroll();
  },1000);
});
```

**Comment by petebacondarwin** [comment] 2015-01-15 12:07
So the simple workaround for this is to actually provide a `hashPrefix`. For some reason at the moment if you don't provide a hashPrefix then it doesn't ignore the functionality - instead it assumes that everything after a hash is a "path" rather than a real hash.

See this example:

```html
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body ng-app="app" ng-controller="MainCtrl">
    <a id="top">THIS IS THE TOP</a>

    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <a id="bottom"></a>
    BOTTOM
  </body>
  <script src="angular.js"></script>
  <script type="text/javascript">
    angular.module('app', [])

    .config(function($locationProvider) {
      $locationProvider.hashPrefix('!');
    })

    .controller('MainCtrl', function($scope, $location, $anchorScroll, $timeout) {

      $timeout(function () {
        console.log("scrolling!");
          $location.hash("bottom");
          debugger;
         $anchorScroll();
      },1000);
    });
  </script>
</body>
</html>
```

**Comment by petebacondarwin** [comment] 2015-01-15 12:11
We ought not to have to do this and it appears that we didn't previously. So this is a regression that needs fixing. @Narretz do you have any cycles to take a look?

**Comment by bobber205** [comment] 2015-01-15 18:15
The above workaround does work, just confirmed locally in Chrome latest stable.

However, if I put do ```hashPrefix("#")``` and then use ```.hash("#")``` the app basically implodes.

I also just noticed that without any use of ```hasPrefix``` (basically my current code base with no changes) I'm getting an infinite digest error OCCASIONALLY.

```
 Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
http://errors.angularjs.org/1.3.6/$rootScope/infdig?p0=10&p1=%5B%5D
    at http://mywebsite/app/assets/js/vendor/angularjs/angular.js:63:12
    at Scope.$digest (http://mywebsite/app/assets/js/vendor/angularjs/angular.js:14232:19)
    at Scope.$apply (http://mywebsite/app/assets/js/vendor/angularjs/angular.js:14456:24)
    at done (http://mywebsite/app/assets/js/vendor/angularjs/angular.js:9614:47)
    at completeRequest (http://mywebsite/app/assets/js/vendor/angularjs/angular.js:9804:7)
    at XMLHttpRequest.requestLoaded (http://mywebsite/app/assets/js/vendor/angularjs/angular.js:9745:9)
angular.js:63 Uncaught Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
```

Seems related as when I put in ```hashPrefix("#")``` I got this error and many others, like

```
Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [[{"msg":"fn: autoScrollWatch","newVal":"/top","oldVal":""}],[{"msg":"fn: autoScrollWatch","newVal":"","oldVal":"/top"}],[{"msg":"fn: autoScrollWatch","newVal":"/top","oldVal":""}],[{"msg":"fn: autoScrollWatch","newVal":"","oldVal":"/top"}],[{"msg":"fn: autoScrollWatch","newVal":"/top","oldVal":""}]]
```

![screen recording](https://cloud.githubusercontent.com/assets/5841107/5763470/6e01cd3c-9c9f-11e4-8638-9a1dab673511.gif)

**Comment by Narretz** [comment] 2015-01-15 18:36
It's not recommended to use `#` as the hashPrefix. It's usually something like `!`.

@petebacondarwin I can take a look next week

**Comment by bobber205** [comment] 2015-01-15 18:39
@Narretz good to know, thanks! :dancer: sticking with ! for now.

Is ```/register#!#top``` what I can expect even under ideal conditions?

**Comment by petebacondarwin** [comment] 2015-01-25 02:45
I think this is actually a duplicate of #8675

**Closed by petebacondarwin** 2015-01-25 02:45 UTC
Labels: branch: 1.3.x, component: $location, severity: regression
