### ISSUE TITLE
minErr: Make optional link on errors.angularjs.org

### ISSUE THREAD

**Issue by maksimr** [angular/angular.js#10590] opened 2014-12-28 18:25 UTC
It's useful when you write tests and output tests' result to terminal.
On small displays query parameters for errors.angularjs.org occupy a large part of display and you have to switch to screen where run tests and scroll to the beginning of the error message.

**Comment by Narretz** [comment] 2015-01-20 12:28
That doesn't seem unreasonable, although I am not sure how you would tell minErr to not append the whole stack.

**Comment by phdesign** [comment] 2015-10-05 00:06
Running into this problem myself. As a workaround I'm piping test output through grep
```
grunt test | grep -v http://errors.angularjs.org
```

**Comment by jakub-g** [comment] 2015-11-23 17:23
@phdesign I followed your advice, but just realized this is not a very good solution for most usages.

I put this into my `package.json` to have `npm test`:

  "scripts": {
    "test": "karma start --single-run | grep -v errors.angularjs.org",
  }

Normally, when you run the test (`karma start --single-run`) and it fails, karma exits with non-zero exit code.

However when you pipe to grep, the exit code will be `0` even it failed! So suddenly all the tools, like build hooks that relied on `npm test` to return zero only for good tests (and non zero when there are issues, to immediately stop the build) are broken

**Comment by Narretz** [comment] 2017-02-16 11:27
Duplicate of #14744 and the the url length will be configurable in the future: https://github.com/angular/angular.js/pull/15707

**Closed by Narretz** 2017-02-16 11:27 UTC
Labels: component: misc core, frequency: moderate, severity: inconvenient, type: feature
