### ISSUE TITLE
input file not working with ngTouch module

### ISSUE THREAD

**Issue by manikmi** [angular/angular.js#12732] opened 2015-09-02 12:38 UTC
Hi,

I am using an angular bootstrap modal window in angular application. Inside which I have used multiple controls like buttons, input type="file".

I was facing an issue with browsers on mobile and chrome mobile simulators, that if i open the bootstrap modal window, all the buttons inside the bootstrap modal window require clicking twice to work.

I saw the latest module https://docs.angularjs.org/api/ngTouch and enabled it in my project. All the buttons started working FINE with the single click, except for the input type="file", which even on multiple clicks too is not working in mobile simulator and mobile phones. For the desktop browser version, it is still working fine.

Can some body help me out?

Regards,
Manik Mittal

**Comment by wesleycho** [comment] 2015-12-27 14:22
This might be a UI Bootstrap issue, and not an angular one - can you repost the issue in https://github.com/angular-ui/bootstrap/issues with a reproduction?

**Comment by Narretz** [comment] 2016-04-10 14:53
I'm going to close this issue because we have no reproduction of the issue. Feel free to reopen this issue if you can provide a reproduction (ideally a runnable demo in a https://plnkr.co or similar).

**Closed by Narretz** 2016-04-10 14:53 UTC
Labels: component: ngTouch, type: bug
