### ISSUE TITLE
Form Password field is set as invalid field with browser's saved password option

### ISSUE THREAD

**Issue by Sibiraj-S** [angular/angular.js#15985] opened 2017-05-14 14:03 UTC
- [X] bug report

**Current behaviour:**
Now every browser comes with save password option.

If the password is saved by a browser when we reload a page that contains form password field. By default, it is set to invalid even though the browser fills password field. On clicking anywhere on the page it is set to valid.

#### Current behaviour

Here is the [plunker demo](https://plnkr.co/edit/jWpHLhrLjWSRIYoYnLnM?p=preview). 

This is a plunker. I forked from the internet for the demo. 

**How to recreate the issue**
1. Go to external run plunk
2. Enter the username and password 
3. click login
4. save username and password. which Chrome will ask
5. navigate back to login
6. reload the page
7. **Here** the password field will be invalid. on clicking anywhere on the page. the password field will become valid

![bug](https://user-images.githubusercontent.com/20282546/27425079-da69522a-5754-11e7-97b8-a702a06b504c.gif)

here after reload, the password field changed to true **after the click**.

This behaviour is only with input type="password".

**Expected / new behaviour:**
If a valid password is auto-filled by browser then it should be made valid

**Comment by Narretz** [comment] 2017-05-18 09:23
Can you please post a reproduction? It sounds very similar to https://github.com/angular/angular.js/issues/1460 which should have been fixed by all major browsers.

**Comment by Sibiraj-Codes** [comment] 2017-05-18 18:38
I tried reproducing that in plunker. but chrome doesn't autofill username or password field in plunker while page load. I am not sure why that happens. I will reproduce in some other ways

**Comment by Narretz** [comment] 2017-05-18 18:53
I think that's because plnkr is run in an iframe. There's a "external run"
option with which it should work

Am 18.05.2017 20:40 schrieb "Sibiraj" <notifications@github.com>:

**Comment by Sibiraj-Codes** [comment] 2017-05-25 05:13
@Narretz. I am unable to reproduce the issue. because chrome password does not auto-fill at places. This is the code I have tried with [angularjs-seed](https://github.com/Sibiraj-Codes/angularjs-seed). It is possible to run locally with the gulp. will this help?

**Comment by Sibiraj-Codes** [comment] 2017-05-25 05:52
this behaviour, I see in Angular4 too.

**Comment by Sibiraj-S** [comment] 2017-06-22 08:37
@Narretz . Here is the [plunker demo](https://plnkr.co/edit/IPAr7mtg21SWLoRh9WLw?p=preview). 

This is a plunker. I forked from the internet for demo. 

**How to recreate the issue**
1. Go to external run plunk
2. Enter the username and password 
3. click login
4. save username and password. which chrome will ask
5. navigate back to login
6. reload the page
7. **Here** the password field will be invalid. on clicking anywhere on the page. the password field will become vaild


Sorry for the delay.

**Comment by Sibiraj-S** [comment] 2017-06-22 08:44
@Narretz . also I updated my question too.

**Comment by frederikprijck** [comment] 2017-06-22 12:26
@Sibiraj-S Do note that the plunkr you've linked is using AngularJS 1.2.x, which is a very old version of AngularJS.

Could you check if the issue persists with the latest version of AngularJS 1.6.4 ?

Also note that you have to use the same version for all angularjs modules...

```
    <script src="//code.angularjs.org/1.2.20/angular.js"></script>
    <script src="//code.angularjs.org/1.2.20/angular-route.js"></script>
    <script src="//code.angularjs.org/1.2.13/angular-cookies.js"></script>
```

The above versions are not supported to work together.

**Comment by Sibiraj-S** [comment] 2017-06-22 12:30
My bad @frederikprijck . check this one https://plnkr.co/edit/jWpHLhrLjWSRIYoYnLnM?p=preview

**Comment by Sibiraj-S** [comment] 2017-06-22 12:35
I double checked with the latest version 1.6.4 too.

**Comment by Sibiraj-S** [comment] 2017-06-24 20:18
@frederikprijck . is this issue has enough info now?

**Comment by frederikprijck** [comment] 2017-06-25 14:53
@Sibiraj-S Alright, for me it doesn't work with AngularJS 1.6.4 either.

@Narretz It looks like I'm also having the exact same behavior when running the above plunkr. It works fine for the input text, but not for the password.

**Comment by Narretz** [comment] 2017-06-25 16:00
I cannot reproduce this in Version 59.0.3071.109 (64-Bit)

After I've been logged out, Chrome correctly fills user and password field, and I can simply click on login and it works.

**Comment by Sibiraj-S** [comment] 2017-06-25 16:04
everything happens fine. The chrome fills passwords correctly.
but,
Check the plunker.
Reload the page after logout. the password field is set to invalid until any click happens

**Comment by Narretz** [comment] 2017-06-25 16:07
Oh, I see it now. This looks like a Chrome bug / wuirk, but we should investigate why it only doesn't work with password fields.

**Comment by gkalpak** [comment] 2017-06-29 13:10
This happens because autofilling the password field does not emit an `input` event (which would hint AngularJS that the field's value may have changed). This does indeed sound like a browser bug (but could be intended behavior - I can't be 100% sure).

In any case, I am going to close this, because there is nothing we can do for this on the AngularJS side. (If anyone has ideas, I would be happy to discuss.)

**Closed by gkalpak** 2017-06-29 13:10 UTC
Labels: component: forms, needs: more info
