### ISSUE TITLE
Date filter incorrectly sets the year as 1 when year is 0 and fullDate format is used

### ISSUE THREAD

**Issue by wesleycho** [angular/angular.js#15548] opened 2016-12-27 10:22 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

It sets the year as 1 when `fullDate` is used with the date filter and the year is 0.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

http://plnkr.co/edit/kXo5BOzNc5SpCYRvrb9s?p=preview

**What is the expected behavior?**

It should format the year properly

**What is the motivation / use case for changing the behavior?**

This was reported as a bug against UI Bootstrap, but I have determined that it is an Angular bug, as seen in the Plunker.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

All versions

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

This is likely bad behavior in the date filter itself - I haven't dug into it yet, but I could potentially investigate and craft a fix sometime this week.

**Comment by gkalpak** [comment] 2016-12-29 11:17
Actually, it is intended behavior (changed in 9421674). The year `0000` is interpreted as `0001 BC`, but this is not visible in the original plnkr, because the `fullDate` format does not contain the era ([updated plnkr][1]).

While accurate, I admit this can be a little confusing. There is also some more context [here][2]. Maybe we should add support for [the `u` pattern][3] (as suggested [here][4]).

For reference/comparison, this works the same with Java's [`DateTimeFormatter`][5]: [demo][6]

##
I am going to close this, since it currently works as expected. Please open a new request if you think it worth adding/changing something.

<sub>(E.g. implementing the `u` pattern and switching predefined formats to that sounds reasonable.)</sub>

[1]: http://plnkr.co/edit/PLkCiiWOulzqQXsJZ7Xp?p=preview
[2]: https://github.com/angular/angular.js/pull/14026#r52828854
[3]: https://github.com/google/closure-library/blob/3589a5c7d0236c84d6f2c5d01b036e782af41acd/closure/goog/i18n/datetimeformat.js#L44
[4]: https://github.com/angular/angular.js/pull/14026#r52841882
[5]: https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html
[6]: http://ideone.com/EG1E6v

**Closed by gkalpak** 2016-12-29 11:17 UTC
Labels: component: filters, frequency: low, severity: broken expected use, type: bug
