### ISSUE TITLE
It's error, only Chrome(60.0.3112.101), it's fine on firefox or edge. it's sudden.

### ISSUE THREAD

**Issue by shenjielx** [angular/angular.js#16176] opened 2017-08-16 06:29 UTC
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

**Expected / new behavior:**

**Minimal reproduction of the problem with instructions:**

**AngularJS version:** 1.x.y

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

```
angular.js:13920 Error: [$compile:tpload] Failed to load template: home/dashboard (HTTP status: -1 )
http://errors.angularjs.org/1.5.8/$compile/tpload?p0=home%2Fdashboard&p1=-1&p2=
    at angular.js:68
    at handleError (angular.js:19433)
    at processQueue (angular.js:16383)
    at angular.js:16399
    at Scope.$eval (angular.js:17682)
    at Scope.$digest (angular.js:17495)
    at Scope.$apply (angular.js:17790)
    at done (angular.js:11831)
    at completeRequest (angular.js:12033)
    at XMLHttpRequest.requestError (angular.js:11976)

angular?v=SoymK9Y9ucGPQikPKd-Bve0nwIqic7YUxFep-8U94IA1:121 Error: [$compile:tpload] http://errors.angularjs.org/1.5.8/$compile/tpload?p0=%2FHome%2FDashboard&p1=-1&p2=
    at angular?v=SoymK9Y9ucGPQikPKd-Bve0nwIqic7YUxFep-8U94IA1:9
    at angular?v=SoymK9Y9ucGPQikPKd-Bve0nwIqic7YUxFep-8U94IA1:159
    at angular?v=SoymK9Y9ucGPQikPKd-Bve0nwIqic7YUxFep-8U94IA1:134
    at m.$eval (angular?v=SoymK9Y9ucGPQikPKd-Bve0nwIqic7YUxFep-8U94IA1:148)
    at m.$digest (angular?v=SoymK9Y9ucGPQikPKd-Bve0nwIqic7YUxFep-8U94IA1:145)
    at m.$apply (angular?v=SoymK9Y9ucGPQikPKd-Bve0nwIqic7YUxFep-8U94IA1:149)
    at l (angular?v=SoymK9Y9ucGPQikPKd-Bve0nwIqic7YUxFep-8U94IA1:100)
    at J (angular?v=SoymK9Y9ucGPQikPKd-Bve0nwIqic7YUxFep-8U94IA1:105)
    at XMLHttpRequest.e (angular?v=SoymK9Y9ucGPQikPKd-Bve0nwIqic7YUxFep-8U94IA1:106)
```

only Chrome(60.0.3112.101),

**Comment by frederikprijck** [comment] 2017-08-16 06:29
@shenjielx As mentioned on gitter, it's going to be easier to help you if you can reproduce it.

Also be sure to check:

> The [Chrome Developer Tools](https://developers.google.com/chrome-developer-tools/docs/network#network_panel_overview) might also be helpful in determining why the request failed.

**Comment by Narretz** [comment] 2017-08-29 11:04
I'm going to close this issue because we haven't got any feedback. Feel free to reopen this issue if you can provide new feedback.

**Closed by Narretz** 2017-08-29 11:04 UTC
Labels: component: misc core, needs: more info
