### ISSUE TITLE
history issue when routing to root directory

### ISSUE THREAD

**Issue by dmaison** [angular/angular.js#13538] opened 2015-12-14 17:30 UTC
**Versions**
AngularJS: 1.4.1
Angular-Route: 1.4.1

**Description**
Despite the route being defined, when clicking an anchor whose href attribute points to the root directory ( i.e. href="/" ) instead of navigating to the defined route, it appears to navigate to one page prior in the history. 

**Example**
1. navigate to "/page1" w/ anchor element
2. navigate to "/page2" w/ anchor element
3. navigate to "/" w/ anchor element
Instead of being routed to "/", you are routed to "/page1" 
Should be noted that after being routed erroneously to "/page1" attempts to navigate to "/" are routed correctly

apologies for no JSfiddle, at work so not a lot of time

**Comment by gkalpak** [comment] 2015-12-15 12:14
@dmaison, it is not possible to fix the issue without a way to reproduce it (or more info). I tried to reproduce it [here][1], but I wasn't able to.

Some additional info that would help:
Are you using HTML5 mode ?
Are you using `ngRoute` or `uiRouter` ?
What does your route configuration look like ?
(Of course, a live reproduction works wonders :smiley:)

Also, you should try the latest version for the branch that you are using (i.e. `v1.4.8` atm) and see if it's already fixed.

[1]: https://codepen.io/ExpertSystem/pen/XXXjJJ?editors=100

**Comment by dmaison** [comment] 2015-12-16 20:49
I will make/try to make a test case asap 

Answers to questions:
html5 is true
ngRoute 

route config:
	.config( [ '$routeProvider', '$locationProvider', function( $routeProvider, $locationProvider ){

		$routeProvider
			.when('/', {
				templateUrl: 'views/login/home.html',
				controller: 'authController'
			})
			.when('/registration', {
				templateUrl: 'views/login/register.html',
				controller: 'registerController'
			})
			.otherwise({
				templateUrl: 'views/404.html'
			});

		$locationProvider.html5Mode( true );

	}]);

**Comment by dmaison** [comment] 2015-12-16 20:54
it does look like you're handling anchors in your example a little differently though:
Yours:`<a href="#/">Home</a>`
Ours: `<a href="/"><i class="sign in icon"></i> Login</a>`



though i'm fairly certain that probably has nothing to do with it.

**Comment by gkalpak** [comment] 2016-06-03 20:13
Closing since we don't have a reproduction.
<sub>
Feel free to re-open if you are still facing issues and are able to provide a way for us to reproduce the issue.
</sub>

**Closed by gkalpak** 2016-06-03 20:13 UTC
Labels: branch: 1.4.x
