### ISSUE TITLE
$timeout / $browser.defer broken on iOS 9 Cordova UIWebView

### ISSUE THREAD

**Issue by jd-carroll** [angular/angular.js#12635] opened 2015-08-20 13:46 UTC
On iOS 9 runing Cordova with UIWebView, $timeout will invoke multiple times for a single request.

Here's a simple example:

```
<!DOCTYPE html>
<html>
    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.16/angular.js"></script>
        <script>
            angular.module('timeout', [])
            .config(function($timeout) {
              var i = 0;
              $timeout(function() {
                i++;
                console.log('$timeout invoked ' + i + ' times');
              }, 0);
        </script>
    </head>
    <body ng-app="timeout">
        <div ng-view></div>
    </body>
</html>
```

It does not matter how long the delay is.

**Comment by jd-carroll** [comment] 2015-08-20 13:48
I should note that the issue is with the `window.setTimeout` which will affect everything that uses it

**Comment by Narretz** [comment] 2015-08-20 13:52
If the problem is with setTimeout then Apple needs to fix it. no? Have you reported this to Apple?

**Comment by jd-carroll** [comment] 2015-08-20 14:20
Open Radar: https://openradar.appspot.com/22360634

**Comment by Narretz** [comment] 2015-08-20 14:29
Thanks. Let's hope Apple fixes this before the release, it's a pretty big bug. If you see that it is resolved, can you close this issue?

**Comment by jd-carroll** [comment] 2015-08-20 15:05
Absolutely, I'll keep the rdar updated as best as possible with any updates from apple (if it doesn't happen automatically)

**Comment by realityfilter** [comment] 2015-08-20 16:39
I tried the code snippet from the apple bug report and got only one debug line. Is used an iPhone 5 with iOS 9 beta5 and the simulator for an iPad Air. 

I also decorated $browser.defer the following way:

```javascript
    app.config(['$provide', ($provide) => {
        $provide.decorator('$browser', ['$delegate', ($delegate) => {
            var origDefer = $delegate.defer;

            var saveInvoke = function(fn) {
                var invoked = 0;
                return function () {
                    if (invoked > 0) return console.log("Called multiple times: " + invoked);

                    try {
                        fn.apply(this, arguments);
                    } finally {
                        ++invoked;
                        fn = angular.noop;
                    }
                }
            };

            function newDefer(fn, timeout) {
                return origDefer(saveInvoke(fn), timeout);
            }

            $delegate.defer = newDefer;
            $delegate.defer.cancel = origDefer.cancel;

            return $delegate;
        }]);
    }]);
```

And received no multiple invocations. I tested this on an iPad Air, too.

Bottom line: gladly I can not reproduce this.

**Comment by jd-carroll** [comment] 2015-08-26 00:22
@realityfilter That's interesting you cannot reproduce... Very clearly for me I can open the test page from our app and it will break on iOS 9 in Cordova but loading the same exact app from Safari web browser I do not have an issue.  (this is an enterprise app which is loaded from a web server and not actually stored in the Cordova app, so it is trivial to load from Safari vs Cordova)

I'll try to spend some time with this to see if there is something unique we are doing in our app that could be causing this, but have no expectation of finding anything.

I was not familiar with the `decorator` api and thank you for sharing that.  Until I can find an exact cause, I will be using the strategy you outlined above both for this issue and the original infinite digest issue.

**Comment by realityfilter** [comment] 2015-08-26 13:27
@jd-carroll 
The given example in the bug report does not run. Missing parentheses and $timeout service is not injectable during config.

I had to change this to:

```javascript
<!DOCTYPE html>
<html>
    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.16/angular.js"></script>
        <script>
            angular.module('timeout', [])
            .run(function($timeout) {
              var i = 0;
              $timeout(function() {
                i++;
                console.log('$timeout invoked ' + i + ' times');
              }, 0);
		  });
        </script>
    </head>
    <body ng-app="timeout">
        <div ng-view</div>
    </body>
</html>
```

This time I was loaded from the server inside cordova. Still not reproducible.

**Comment by aderowbotham** [comment] 2015-08-31 20:52
@realityfilter I too am **not** seeing the timeout invoked more than once (using your corrected syntax), with Angular 1.4.0 running in a Cordova (cordova-ios 3.9.1) app on iOS 9 beta 5 13A4325c

**Comment by wesleycho** [comment] 2016-06-15 00:16
Sounds like this is potentially fixed - is there any update?

**Comment by Narretz** [comment] 2016-06-15 09:16
I think we can close it, as there hasn't been activity in almost a year.

**Closed by Narretz** 2016-06-15 09:16 UTC
Labels: browser: iOS, type: bug
