### ISSUE TITLE
replace history when $locationChangeStart is prevented

### ISSUE THREAD

**Issue by hesamwls** [angular/angular.js#11643] opened 2015-04-18 11:46 UTC
I'm trying to cancel out all effects of unsuccessfull route in terms of Browser History.
when I call event.preventDefault() in $locationChangeStart listener, I expect the new History token replace the last one.
I mean right now for this :
    Route A--->Route B(prevented)--->route C($location.replace called) 
I get:
    Route A->Route A
in my browser history.
but if history get replaced when I prevent locationChangeStart, I'll get:
    Route A
that seems logical.
Any thoughts?

**Comment by pkozlowski-opensource** [comment] 2015-04-21 08:55
This is duplicate of https://github.com/angular/angular.js/issues/2100 - let's move the discussion in there.

**Closed by pkozlowski-opensource** 2015-04-21 08:55 UTC
