### ISSUE TITLE
feature request -- if config or provider returns promise, defer bootstrap of that module

### ISSUE THREAD

**Issue by ilovett** [angular/angular.js#12316] opened 2015-07-09 20:24 UTC
This would be useful for 3rd party modules that may require fetching some data or anything async, that might need to be available as a constant in that module.

Currently, we can defer the app bootstrap itself, but the app has a module dependency, there's no way (I know of) to defer that module from bootstrap synchronously.

In my use case, I want to dynamically set up navigation states, so this needs to be available at `.config` and `.provider` run time so I can define routes.

**Comment by petebacondarwin** [comment] 2015-07-11 20:07
This is kind of a duplicate of https://github.com/angular/angular.js/issues/4003.

How would you propose fetching this data inside the provider? If the injector has not been created, which is true inside providers, then there would be no access to `$http` or `$q` to return a promise.

**Comment by OpenSiteMobile** [comment] 2015-07-14 00:40
Hi ilovett, I do exactly what you are looking for, but I use my own overall module controlling script, and bootstrap manually AngularJS when my script is finished loading modules. I also can load new Angular modules, as well as my own or other third party at any time later in the page display (ie: view new content or add functionality: angularjs or plain javascript). I had at first just made a simple change to AngularJS to accommodate my AngularJS-Post Loading script, but now use my own version.

Long story short, it can be done but isn't dead easy to do. Can probably be done with RequireJS and similar techniques to what I do, but still might require a "special" version of AngularJS. And as you can see, they aren't interested in "new features" much, so you have to decide how bad you want it. If interested, have a look at http://opensitemobile.com/angularjs/ for the demo and https://github.com/OpenSiteMobile/angularjs for the content pages, etc. My base scripts reside at https://github.com/OpenSiteMobile/mobilesiteos.

**Comment by petebacondarwin** [comment] 2015-07-14 13:39
I think that if you want to do this kind of thing then what @OpenSiteMobile is offering is the right way forward. It is not something we are going to include in Angular 1 in the foreseeable future. Angular 2 is much more configurable in this regard.

**Closed by petebacondarwin** 2015-07-14 13:39 UTC
Labels: frequency: low, resolution: invalid, severity: inconvenient, type: feature
