### ISSUE TITLE
$http Cache for POST Method. Possible extend for native Cache ? 

### ISSUE THREAD

**Issue by cullsin** [angular/angular.js#15321] opened 2016-10-27 19:45 UTC
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

feature / bug

**What is the current behavior?**

$http cache only caches GET response. How do I extend the cache module alone to implement cache techniques for 'POST'  

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

Set the config : cacheObject in the $http get method, angular by default operates the cache. whereas it disabled the cache method for "POST". 

**What is the expected behavior?**

I expect that there should be a way to extend angularjs cache module. I can write a common cache mechanism outside of $http calls, but I wanted to know I can do it by native.

**What is the motivation / use case for changing the behavior?**

POST method can also be used for fetching data if the request has unlimited data input.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

Angular 1.5.x

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

I would like to know If I can write a module that extend AngularJs Cache Implementation. If so, please suggest me on the same.

**Comment by Narretz** [comment] 2016-10-28 10:14
Duplicate of https://github.com/angular/angular.js/issues/3031
There are currently no plans to implement this. If someone wants to submit a PR that makes this configurable, e.g. by creating a $httpCacheService that can be overwritten in userland and which will decide what requests are cached

**Closed by Narretz** 2016-10-28 10:14 UTC

**Comment by cullsin** [comment] 2016-10-31 17:59
Hi, 

Thanks. Shall I do the Implementation. Can you suggest me the procedure so that I can contribute.

Raja K
