### ISSUE TITLE
Transclude slot doesn't work as expected when outlet is in a <table>

### ISSUE THREAD

**Issue by cheapsteak** [angular/angular.js#15598] opened 2017-01-11 15:10 UTC
Want to create a table component but still allow users to customize the rendering of each row

This does not seem to work

```js
component('myTable', {
    transclude: {
      row: 'row',
    },
    replace: true,
    template: `
      <table>
        <tr ng-repeat="row in vm.rows" ng-transclude="row">
        </tr>
      </table>
    `,
  })
```

```html
<my-table>
    <row>
        <td>this doesn't show up</td>
    </row>
</my-table>
```

The `<row>` tag ends up being rendered inside the `<tr>`, and `<td>`s are lost

![image](https://cloud.githubusercontent.com/assets/743976/21821078/2882d76e-d740-11e6-82ab-e794d7a41cd6.png)

The browser takes liberties with `<tr>` and `<td>` tags (seems to strip them out if they're not in the right place)

One way to solve would be if we could transclude `<tr attribute-selector>` and `transclude: { row: '[attribute-selector]'}`

**Comment by Narretz** [comment] 2017-01-11 15:19
Looks like this is a follow-up to https://github.com/angular/angular.js/issues/14169

Yes, browsers discard td and tr elements if they are not inside a table element. This is standard behavior and cannot be changed, because the browser parses the HTML before Angular mutates the DOM. Looks like a valid use case attribute selectors in multi transclusion.

**Comment by gkalpak** [comment] 2017-01-11 19:50
I am not sure how attribute selectors would help here. The problem is that yu can't have `<td>` elements inside non-`<tr>` elements. How you select them is not the issue.

**Comment by cheapsteak** [comment] 2017-01-11 20:08
I think attribute selectors would allow 

```js
component('myTable', {
    transclude: {
      row: '[row]',
    },
});
```

```html
<my-table>
    <tr row>
        <td>this doesn't show up</td>
    </tr>
</my-table>
```

**Comment by gkalpak** [comment] 2017-01-11 20:29
It wouldn't, because `<tr>` elements are not allowed inside `<my-table>`.

**Comment by Narretz** [comment] 2017-01-18 13:55
@gkalpak is correct, I think we can close this. Angular 1 is not built to work around these browser limitations.

**Closed by Narretz** 2017-01-18 13:55 UTC
Labels: component: $compile, frequency: low, severity: broken expected use
