### ISSUE TITLE
Object doesn't support property or method 'call'

### ISSUE THREAD

**Issue by RoelofDelft** [angular/angular.js#12595] opened 2015-08-17 07:57 UTC
Since angular 1.4.3 the "Object doesn't support property or method 'call' " occurred in angular.js

Concerning code in minified version is:

for(var l=0;l<g;l++)c.isImmediatePropagationStopped()||f[l].call(b,c)

Problems occur when not only svc.interrupt are there, such as:

c.isImmediatePropagationStopped=false ==> f = [function () {
                    svc.interrupt();
                }]
c.isImmediatePropagationStopped=false ==> f = [function () {
                    svc.interrupt();
                }]
c.isImmediatePropagationStopped=false ==> f = [function(d){var f=function(){h(c,{$event:d})};wg[a]&&e.$$phase?c.$evalAsync(f):c.$apply(f)}]
c.isImmediatePropagationStopped=false ==> f = [[[object HTMLInputElement]]]
c.isImmediatePropagationStopped=false ==> f = [function(d){var f=function(){h(c,{$event:d})};wg[a]&&e.$$phase?c.$evalAsync(f):c.$apply(f)}]
c.isImmediatePropagationStopped=false ==> f = [function(b){if(a.rewriteLinks&&!b.ctrlKey&&!b.metaKey&&!b.shiftKey&&2!=b.which&&2!=b.button){for(var e=
z(b.target);"a"!==ta(e[0]);)if(e[0]===f[0]||!(e=e.parent())[0])return;var h=e.prop("href"),l=e.attr("href")||e.attr("xlink:href");D(h)&&"[object SVGAnimatedString]"===h.toString()&&(h=Aa(h.animVal).href);B.test(h)||!h||e.attr("target")||b.isDefaultPrevented()||!k.$$parseLinkUrl(h,l)||(b.preventDefault(),k.absUrl()!=d.url()&&(c.$apply(),g.angular["ff-684208-preventDefault"]=!0))}}]
c.isImmediatePropagationStopped=false ==> f = [function () {
                    svc.interrupt();
                }]
c.isImmediatePropagationStopped=false ==> f = [function () {
                    svc.interrupt();
                }]
c.isImmediatePropagationStopped=false ==> f = [function () {
                    svc.interrupt();
                }]

**Comment by RoelofDelft** [comment] 2015-08-18 09:03
A dirty hack to solve the problem, can be the following:

for(var l=0;l<g;l++)c.isImmediatePropagationStopped()||f[l].toString().match('svc')||f[l].call(b,c)

**Comment by RoelofDelft** [comment] 2015-08-18 09:05
To whom it may concern:

In the unminified version it is part of function "createEventHandler(element, events)" with the problem code:
    for (var i = 0; i < eventFnsLength; i++) {
      if (!event.isImmediatePropagationStopped()) {
        eventFns[i].call(element, event);
      }
    }

**Comment by RoelofDelft** [comment] 2015-08-18 11:34
btw, in certain cases it is not even a function, but for example:
"[[object HTMLInputElement]]"

**Comment by lgalfaso** [comment] 2015-08-18 17:02
would it be possible for you to create a minimal plunker that shows the error?

**Comment by RoelofDelft** [comment] 2015-08-19 07:45
Webbrowser in this case is IE 11, which fails to write a plunker. Tried in speed to build a  minimal plunker at: http://plnkr.co/edit/n3wM3Y2xRc0MbfELPCQp?p=preview

However, the modal does not popup went it should popup, but I think I overlooked something.

Maybe you can test it off line at your place?

It occurred in my software at multiple locations, sometimes on the datepicker (at reload through a reset button of the repeat loop, the datepicker line dissapears always with this error) sometimes on the cancel action sometimes elsewhere.

**Comment by RoelofDelft** [comment] 2015-08-19 10:18
NgIdle:  v1.1.0
Link https://github.com/HackedByChinese/ng-idle.git

**Comment by RoelofDelft** [comment] 2015-08-19 12:28
Best to use "||!f[l].toString().match('function')" instead of my previous solution

**Comment by RoelofDelft** [comment] 2015-08-19 12:31
if error occur on cancel of modal, then modal dissapears as expected but background is still freezed.

**Comment by pkozlowski-opensource** [comment] 2015-08-19 12:44
@RoelofDelft I'm afraid that we don't have free cycles to debug your whole application. Please reduce the problem to the absolute minimum and share a plunk that illustrates a bug in AngularJS. Please check the bug submission guidelines here:  https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#submitting-an-issue

If you are not sure that you are hitting a bug in AngularJS, please ask support questions using a dedicated support channel: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem

**Comment by RoelofDelft** [comment] 2015-08-19 14:56
Yes, I do understand.

But making a minimal plunker is not possible to show this behavior.

Just adding an additional check to make sure that the object is indeed a callable function should be enough.

**Comment by pkozlowski-opensource** [comment] 2015-08-19 14:59
> But making a minimal plunker is not possible to show this behavior

Why it is so? If we can't reproduce we can't confirm that this is a bug. And we can't write a test for it...
The first step is to understand what is going on and if we really talking about about a bug in the framework or just a pb with usage / 3rd party code. Without minimal reproduce we don't know so we can't act.

**Comment by Narretz** [comment] 2015-09-01 11:46
Closing because we can't confirm the bug without a reproduce scenario

**Closed by Narretz** 2015-09-01 11:46 UTC
Labels: needs: more info
