### ISSUE TITLE
ngAnimate - strange behavior when using external templates

### ISSUE THREAD

**Issue by alexus85** [angular/angular.js#16128] opened 2017-07-25 09:34 UTC
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**
The animation does not start properly when using external template for my `list-entry` component. It only works while the template is defined as a string. 

**Expected / new behavior:**
The animation should start whether the template is defined as string or it's an external file. 

**Minimal reproduction of the problem with instructions:**
(using external template) -> http://plnkr.co/edit/wyulABVJp6m8OWrbMIi3
(template defined as string) -> http://plnkr.co/edit/BP6OsgYA6SkVduoTBERk?p=preview

**Angular version:** 
both angularjs and  angular-animate are 1.6.2

**Browser:** 
It's happening in all browsers.

**Comment by frederikprijck** [comment] 2017-07-25 09:52
Possibly related https://github.com/angular/angular.js/issues/14074 ?

**Comment by alandrieu-gimel** [comment] 2017-07-25 09:55
Change your ng-repeat div location.

```html
List of items:
<div ng-repeat="item in $ctrl.games">
  <list-entry  game="{{item}}" class="repeat-animation">
  </list-entry>
</div>
```

**Comment by alexus85** [comment] 2017-07-25 10:10
@alandrieu-gimel , this seems to be working , also had to apply the 'repeat-animation' class for that div in order to get the animation working as well. 

```
List of items:
<div ng-repeat="item in $ctrl.games" class="repeat-animation">
	<list-entry  game="{{item}}">
	</list-entry>
</div>
```
Even though it seems to be working with this workaround, I still wonder as why it doesn't work in my example above.

**Comment by alandrieu-gimel** [comment] 2017-07-25 10:31
It doesn't work because your ng-repeat is not at the right place. You must repeat entry element like this :

```
loop (list-entry){
  entry
}
```
```html
<!-- My list-entry-component -->
<div ng-repeat="entry in list-entry">
        <!-- My entry-component -->
	<entry/>
</div>
```

**Comment by frederikprijck** [comment] 2017-07-25 11:16
@alandrieu-gimel 
> It doesn't work because your ng-repeat is not at the right place.

Despite the fact that it's not working with the animation in the plunkr, It actually is okay to use `<entry ng-repeat="...">`, I'm not sure what you mean with `because your ng-repeat is not at the right place`.

**Comment by alexus85** [comment] 2017-07-25 11:33
@frederikprijck 
that's what I thought,. I've been using this technique `<entry ng-repeat="...">` without any issues up until I started playing around with the `ngAnimate`.

**Comment by alandrieu-gimel** [comment] 2017-07-25 12:04
...in your plunkr replace _repeat-animation_ by _animate-repeat_ .

**Comment by gkalpak** [comment] 2017-07-25 12:57
@frederikprijck, is right. This is a duplicate of #14074. See https://github.com/angular/angular.js/issues/14074#issuecomment-269863352 for some details/workaround.

Closing this, since the other issue hasmore context/discussion.

**Closed by gkalpak** 2017-07-25 12:57 UTC
