### ISSUE TITLE
Angular js Error: The operation is insecure

### ISSUE THREAD

**Issue by rajcybage** [angular/angular.js#12205] opened 2015-06-24 13:33 UTC
I have script.js which has following code

```javascript
(function(angular) {
  'use strict';
angular.module('ngViewExample', ['ngRoute', 'ngAnimate'])
  .config(['$routeProvider', '$locationProvider',
    function($routeProvider, $locationProvider) {
      $routeProvider
        .when('/Book/:bookId', {
          templateUrl: 'book.html',
          controller: 'BookCtrl',
          controllerAs: 'book'
        })
        .when('/Book/:bookId/ch/:chapterId', {
          templateUrl: 'chapter.html',
          controller: 'ChapterCtrl',
          controllerAs: 'chapter'
        });

      $locationProvider.html5Mode(true);
  }])
  .controller('MainCtrl', ['$route', '$routeParams', '$location',
    function($route, $routeParams, $location) {
      this.$route = $route;
      this.$location = $location;
      this.$routeParams = $routeParams;
  }])
  .controller('BookCtrl', ['$routeParams', function($routeParams) {
    this.name = "BookCtrl";
    this.params = $routeParams;
  }])
  .controller('ChapterCtrl', ['$routeParams', function($routeParams) {
    this.name = "ChapterCtrl";
    this.params = $routeParams;
  }]);
})(window.angular);
```

and in html view I have

````
<div ng-controller="MainCtrl as main">
  Choose:
  <a href="Book/Moby">Moby</a> |
  <a href="Book/Moby/ch/1">Moby: Ch1</a> |
  <a href="Book/Gatsby">Gatsby</a> |
  <a href="Book/Gatsby/ch/4?key=value">Gatsby: Ch4</a> |
  <a href="Book/Scarlet">Scarlet Letter</a><br/>

  <div class="view-animate-container">
    <div ng-view class="view-animate"></div>
  </div>
  <hr />

  <pre>$location.path() = {{main.$location.path()}}</pre>
  <pre>$route.current.templateUrl = {{main.$route.current.templateUrl}}</pre>
  <pre>$route.current.params = {{main.$route.current.params}}</pre>
  <pre>$routeParams = {{main.$routeParams}}</pre>
````

also I have book.html and chapter.html.

But it is throwing error while I click any links of it.

The error stack

````
Error: The operation is insecure.
Jf/l.url@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular.min.js:44:436
h@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular.min.js:104:180
ef/this.$get</</<@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular.min.js:107:221
hf/this.$get</m.prototype.$eval@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular.min.js:134:393
hf/this.$get</m.prototype.$digest@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular.min.js:131:418
hf/this.$get</m.prototype.$apply@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular.min.js:135:158
ef/this.$get</<@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular.min.js:106:46
Gf/c@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular.min.js:35:70
e/<()angular.min.js (line 108)
Ye/this.$get</<()angular.min.js (line 80)
hf/this.$get</m.prototype.$digest()angular.min.js (line 131)
hf/this.$get</m.prototype.$apply()angular.min.js (line 135)
ef/this.$get</<()angular.min.js (line 106)
Gf/c()angular.min.js (line 35)
````

**Comment by Narretz** [comment] 2015-06-24 17:38
Can you please try to reproduce the problem on a plnkr.co or similar? There's not really enough info to assess the problem. The code is taken from the angular docs, right?

**Comment by rajcybage** [comment] 2015-06-25 03:52
Yes the code is taken from docs but it is not working I will send you plunkr link

**Comment by havenchyk** [comment] 2015-06-26 12:45
@rajcybage it looks like you're trying to run this code on the static html page, is it right? Do you use any kind of server with this example?

**Comment by rajcybage** [comment] 2015-06-26 14:18
Yes it is working on  plunckr but not working on static html why it is happening but I include all dependencies

**Comment by havenchyk** [comment] 2015-06-26 17:22
@rajcybage angular uses ajax requests to load your template html files, so request cannot be resolved without the server, please, look at http://stackoverflow.com/a/16251614/1815058 for details.

**Comment by pkozlowski-opensource** [comment] 2015-06-28 18:03
Closing as we've got no reproduce scenario and the explanation given by @havenchyk (thnx, BTW!) sounds plausible.

**Closed by pkozlowski-opensource** 2015-06-28 18:03 UTC
Labels: needs: more info
