### ISSUE TITLE
Touch and Hold on the link cannot bring up context menu

### ISSUE THREAD

**Issue by Dunsin-cyber** [angular/angular.js#17158] opened 2021-09-04 06:32 UTC
I'm submitting an issue caused by a new browser version

**Current behavior:**
In iOS 13 above, to touch and hold a link cannot bring up a context menu, suppose it will bring up below the context menu.

**Expected / new behavior:**
Bring up a context menu when holding on the link(which is HTML a tab)

**Minimal reproduction of the problem with instructions:**
Touch and Hold on the link cannot bring up the context menu

**AngularJS version:** 
AngularJS Version: v1.5.8

Browser Type: * Mobile Safari & Mobile Chrome
OS: * iOS 10.3.1 and above

**Comment by gkalpak** [comment] 2021-09-04 11:31
Thx for reporting this, @Dunsin-cyber :+1:
Can you please share more specific details on how to reproduce (for example, what modules are included, how they are configured, what does the template look like, etc.). The easiest way would be to share a minimal reproduction using [StackBlitz][1] (or a similar service).

[1]: https://stackblitz.com/fork/angularjs

**Comment by Dunsin-cyber** [comment] 2021-09-05 12:03
CodePen Demo which shows your issue
: https://codepen.io/marvincd/pen/dyRpdNm

**Comment by gkalpak** [comment] 2021-09-06 17:58
The CodePen doesn't seem to be runnable (it just includes some code snippets). Also, is seems to be using 3rd-party modules (and it is not clear whether the problem is related to one of the core AngularJS packages or a 3rd-party).

I am going to close this issue, since there is not clear reproduction or indication that this is causes by a core AngularJS package. If the issue is caused by a 3rd-party package (i.e. one not maintained by the AngularJS team), please report an issue to that project's issue tracker. If this is an issue with a core AngularJS package, please open a new issue providing a complete but minimal reproduction (i.e. one that is runnable and does not include any 3rd-party packages).

**Closed by gkalpak** 2021-09-06 17:58 UTC
