### ISSUE TITLE
Issue with ng-repeat 5000 records ~750KB size + IE11

### ISSUE THREAD

**Issue by haribalaji79** [angular/angular.js#16320] opened 2017-11-07 14:59 UTC
Hi,
We are trying to create a custom dropdown menu using bootstrap3 + HTML5 (UL / LI) elements.  The  <li> element listed below repeats 5000 times which is done using ng-repeat.
But angular1.6.3 is taking close to 4 minutes to render the HTML. I have attached the output of the profiler in IE11 which clearly indicates the issue. Is there any way we can improve the performance here.
Any suggestion / pointers are highly appreciated. We are using {{}} inside <li> tags. For e.g.
```html
<li ng-repeat="load in loadAndAxleDetailsFormData.loadList" ng-click="editableDropdownSelected(load,'load', false)" class="ng-binding ng-scope" style="">{{load}}</li>
```
```html
<div  class="editableDropdown input-group">
	<input type="text" class="col-md-3 ng-pristine ng-untouched ng-invalid ng-invalid-required gui-input ng-not-empty" name="load" id="load" custom-required="true" ng-model="loadAndAxleDetailsFormData.load" ng-show="loadAndAxleDetailsFormNgShow.load == 'true'" ng-disabled="loadAndAxleDetailsFormNgReadOnly.load == 'true'" ng-class="(requiredFieldsMap.load == 'true') ? 'gui-input' : 'gui-input ml10'" style="">
	<div class="col-md-3 pn" ng-show="loadAndAxleDetailsFormNgShow.load == 'true'" style="">
		<button type="button" class="col-md-4 btn btn-default dropdown-toggle" data-toggle="dropdown" ng-disabled="loadAndAxleDetailsFormNgReadOnly.load == 'true'"><span class="col-md-1  glyphicon glyphicon-menu-up"></span><span class="col-md-1 glyphicon glyphicon-menu-down"></span></button>
		<ul id="color-dropdown-menu" class="dropdown-menu dropdown-menu-right scrollable-menu" role="menu"><!-- ngRepeat: load in loadAndAxleDetailsFormData.loadList -->
			<li ng-repeat="load in loadAndAxleDetailsFormData.loadList" ng-click="editableDropdownSelected(load,'load', false)" class="ng-binding ng-scope" style="">Select / Enter Load</li>
			<!-- end ngRepeat: load in loadAndAxleDetailsFormData.loadList -->
			<li ng-repeat="load in loadAndAxleDetailsFormData.loadList" ng-click="editableDropdownSelected(load,'load', false)" class="ng-binding ng-scope">ALUMINUM BOAT</li>
			<!-- end ngRepeat: load in loadAndAxleDetailsFormData.loadList -->
			<li ng-repeat="load in loadAndAxleDetailsFormData.loadList" ng-click="editableDropdownSelected(load,'load', false)" class="ng-binding ng-scope">ALUMINUM FISHING BOATS</li>
```

![ie11-perf-issue](https://user-images.githubusercontent.com/15215691/32499969-0721862c-c3fa-11e7-9f4a-0e1ac4026bbb.png)

**Comment by Narretz** [comment] 2017-11-07 17:14
It looks like the problem is with ngAnimate having to look up each element in the repeat for possible animations. Can you try if the performance is better when you disable animations: https://code.angularjs.org/snapshot/docs/guide/animations#how-to-selectively-enable-disable-and-skip-animations

**Comment by haribalaji79** [comment] 2017-11-08 15:09
Awesome! It worked like charm. We have one more issue with ng-repeat when rendering a table of ~ 500 records. I have pasted the code and profiler output. I have disabled animations. If you could provide insight into this it will be great. Rendering the last column which has buttons consumes more time. I have written a directive to disable animations on element. see disable-animations attribute in div tag.

```html
<div class="panel-body panel-scroller-vh panel-no-bord scroller-primary etc* scroller-md scroller-overlay scroller-pn pn" disable-animations>
				<table id="allOrders" resizeable st-table="allordrss" st-safe-src="allordrssSort" st-element="tableElement"
					class="table table-striped table-bordered table-condensed dataTable table-blue-bord table-min-ht border-none dashbrdorddetails"
					id="dt_orderDetails"
					style="width: 100%; font-size: 13px; max-width: 100% !important; word-wrap: break-word;">
					<thead>
						<tr>
							<th st-sort="orderNbr" st-skip-natural="true" st-class-ascent="sortup-icon" st-class-descent="sortdown-icon" class="all">{{res.dgcolOrdrNo}}</th>
							<th st-sort="sequenceNumber" st-skip-natural="true" st-class-ascent="sortup-icon" st-class-descent="sortdown-icon" class="desktop">{{res.lblPermitRecordSeq}}</th>
							<th st-sort="orderStatus" st-skip-natural="true" st-class-ascent="sortup-icon" st-class-descent="sortdown-icon" class="all">{{res.dgcolStatus}}</th>
							<th st-sort="carrierName" st-skip-natural="true" st-class-ascent="sortup-icon" st-class-descent="sortdown-icon">{{res.lblCarrName}}</th>
							<th st-sort="unitNbr" st-skip-natural="true" st-class-ascent="sortup-icon" st-class-descent="sortdown-icon">{{res.dgcolUnt}}</th>
							<th st-sort="billRefNum1" st-skip-natural="true" st-class-ascent="sortup-icon" st-class-descent="sortdown-icon" class="desktop">{{res.lblBillRef1}}</th>
							<th st-sort="orderSubmitAgentName" st-skip-natural="true" st-class-ascent="sortup-icon" st-class-descent="sortdown-icon" class="all">{{res.dgAgentSubmitName}}</th>
							<th st-sort="orderSubmitDate" st-skip-natural="true" st-class-ascent="sortup-icon" st-class-descent="sortdown-icon">{{res.dgcolOrdDtTm}}</th>
							<th st-sort="permitProductId" st-skip-natural="true" st-class-ascent="sortup-icon" st-class-descent="sortdown-icon" class="all">{{res.dgcolPermitType}}</th>
							<th st-sort="stateHours" st-skip-natural="true" st-class-ascent="sortup-icon" st-class-descent="sortdown-icon">{{res.dgcolElpsdTm}}</th>
							<th st-sort="auditRegionId" st-skip-natural="true" st-class-ascent="sortup-icon" st-class-descent="sortdown-icon" class="desktop">{{res.dgAuditRegion}}</th>
							<th class="all">{{res.headerAction}}</th>
						</tr>
					</thead>
					<tbody>
						<tr ng-repeat="allorder in allordrss"> <!-- table-init directive removed -->
							<td><a title="{{allorder.permitsView.orderNbr}}" href=""
								ng-click="viewOrder(allorder.permitsView)">{{allorder.permitsView.orderNbr}}</a>
							</td>
							<td><a title="{{allorder.permitsView.sequenceNumber}}"
								href="" ng-if="allorder.permitsView.sequenceNumber!=null" ng-click="viewPermit(allorder.permitsView)">{{allorder.permitsView.sequenceNumber}}</a>
							</td>
							<td><span data-toggle="tooltip"
								title="{{allorder.permitsView.status}}"
								ng-class="{red : allorder.permitsView.status == 'Draft'}">{{allorder.permitsView.orderStatus}}</span></td>
							<td>{{allorder.permitsView.carrierName}}</td>
							<td>{{allorder.permitsView.unitNbr}}</td>
							<td>{{allorder.permitsView.billRefNum1}}</td>
							<td>{{allorder.permitsView.orderSubmitAgentName}}</td>
							<td>{{allorder.permitsView.orderSubmitDate}}</td>
							<td>{{allorder.permitsView.permitProductId}} <br>
							</td>
							<td>{{allorder.permitsView.stateHours}}</td>
							<td>{{allorder.permitsView.auditRegionId}}</td>
							<td>
								<div ng-if="allorder.actionControlsView.lblClaimBy">
									<label>{{allorder.permitsView.claimByName}}</label>
								</div>
								<div class="btn-group width100">
									<button id="lblAddWithComment" type="button"
										class="border-none bg-none pad0 pull-left mb5"
										data-toggle="tooltip" data-placement="top" title="Add Comment"
										ng-if="allorder.actionControlsView.addwithComment"
										ng-click="retrieveCommentHistory(true,allorder.permitsView)">
										<span class="viewComment-icon"></span>
									</button>
									<button id="lblAddComment" type="button"
										class="border-none bg-none pad0 pull-left mb5"
										data-toggle="tooltip" data-placement="top" title="Add Comment"
										ng-if="allorder.actionControlsView.addComment" 
										ng-click="retrieveCommentHistory(true,allorder.permitsView)">
										<span class="lnkAddComment-icon"></span>
									</button>
									<button id="lblViewEventLog" type="button"
										class="border-none bg-none pad0 pull-left mb5 "
										data-toggle="tooltip" data-placement="top"
										ng-click="viewEventLog(allorder.permitsView.orderNbr,allorder.permitsView.sequenceNumber)"
										title="View event log"
										ng-if="allorder.actionControlsView.viewEventLog">
										<span class="viewEventLog-icon"></span>
									</button>
									<button id="lnkCopyProduct" type="button"
										class="border-none bg-none pad0 pull-left mb5 "
										data-toggle="tooltip" data-placement="top"
										title="Copy this order" 
										ng-if="allorder.actionControlsView.copyOrder"
										ng-click="copyOrder(allorder.permitsView)">
										<span class="copyProduct-icon"></span>
									</button>
									<button id="lblCopyAmendOrder" type="button"
										class="border-none bg-none pad0 pull-left mb5 "
										data-toggle="tooltip" data-placement="top"
										title="Copy as Amendment" 
										ng-if="allorder.actionControlsView.showCopyAmendOrder"
										ng-click="copyAmendOrder(allorder.permitsView)">
										<span class="copyAmendOrder-icon"></span>
									</button>
									<button id="lblCopyAmendPermit" type="button"
										class="border-none bg-none pad0 pull-left mb5 "
										data-toggle="tooltip" data-placement="top"
										title="Copy as Amendment" ng-click="copyAmendPermit(allorder.permitsView)"
										ng-if="allorder.actionControlsView.showCopyAmendPermit">
										<span class="copyAmendOrder-icon"></span>
									</button>
									<a href="{{allorder.permitsView.viewPermitURL}}"
										target="_blank" data-toggle="tooltip"
										title="Show Order Summary PDF"
										ng-if="checkVisibility(allorder.permitsView)"><button
											id="lblViewPermit" type="button"
											class="border-none bg-none pad0 pull-left mb5 "
											data-toggle="tooltip" data-placement="top"
											title="Show Permit Delivery PDF"
											ng-if="checkVisibility(allorder.permitsView)">
											<span class="pdf-icon"></span>
										</button></a>
									<a href="{{allorder.permitsView.viewOrderReceiptUrl}}"
										target="_blank" data-toggle="tooltip"
										title="Show Order Receipt"
										ng-if="allorder.actionControlsView.viewOrderReciept">
										<button id="lblViewOrderReciept" type="button"
										class="border-none bg-none pad0 pull-left mb5 "
										data-toggle="tooltip" data-placement="top"
										title="Show Order Receipt"
										ng-if="allorder.actionControlsView.viewOrderReciept">
										<span class="receipt-icon"></span>
									   </button></a>
									<button id="lblResendPermit" type="button"
										class="border-none bg-none pad0 pull-left mb5 "
										data-toggle="tooltip" data-placement="top"
										title="Resend Permit" ng-click="resendPermit(allorder.permitsView)"
										ng-if="allorder.actionControlsView.viewResendPermit">
										<span class="rebillBill-icon"></span>
									</button>
									<button id="lblAssignPermitNumber" type="button"
										class="border-none bg-none pad0 pull-left mb5 "
										data-toggle="tooltip" data-placement="top"
										title="Assign Permit Number" ng-click="openAssignPrintPermitNumber(allorder.permitsView)"
										ng-if="allorder.actionControlsView.assignPermitNumber">
										<span class="permitNumber-icon"></span>
									</button>
									<button id="lblComplete" type="button"
										class="border-none bg-none pad0 pull-left mb5 "
										data-toggle="tooltip" data-placement="top"
										title="Complete Order" ng-click="completeSpecialPermit(allorder.permitsView)"
										ng-if="allorder.actionControlsView.viewComplete">
										<span class="stateResend-icon"></span>
									</button>
									<button id="lblReleasePermitForState" type="button"
										class="border-none bg-none pad0 pull-left mb5 "
										data-toggle="tooltip" data-placement="top"
										title="Release Permit For State To Open" ng-click="releasePermitForStateToOpen(allorder.permitsView)"
										ng-if="allorder.actionControlsView.releasePermitForStateToOpen">
										<span class="lnkRelease-icon"></span>
									</button>
									<button id="lblCompltStateReKey" type="button"
										class="border-none bg-none pad0 pull-left mb5 "
										data-toggle="tooltip" data-placement="top"
										title="Complete State Re-key" ng-click="openCompleteStateReKey(allorder.permitsView)"
										ng-if="allorder.actionControlsView.showCompleteStateReKey">
										<span class="permitNumber-icon"></span>
									</button>
									<button id="lblResendStAppl" type="button"
										class="border-none bg-none pad0 pull-left mb5 "
										data-toggle="tooltip" data-placement="top"
										title="Resend state application" ng-click="resendStateApplication(allorder.permitsView)"
										ng-if="allorder.actionControlsView.showResendStApplication">
										<span class="rebillBill-icon"></span>
									</button>
									<button id="lblStPrefill" type="button"
										class="border-none bg-none pad0 pull-left mb5 "
										data-toggle="tooltip" data-placement="top"
										title="State Prefill" ng-click="prefilStateWebSite(allorder.permitsView)"
										ng-if="allorder.actionControlsView.showStatePrefill">
										<span class="holdBill-icon"></span>
									</button>
									<button id="lblClaim" type="button"
										class="border-none bg-none pad0 pull-left mb5 "
										data-toggle="tooltip" data-placement="top" title="Claim"
										ng-click="claimOrder(allorder.permitsView)"
										ng-if="allorder.actionControlsView.showClaimedByBtn">
										<span class="lnkClaim-icon"></span>
									</button>
									<button id="lblRelease" type="button"
										class="border-none bg-none pad0 pull-left mb5 "
										data-toggle="tooltip" data-placement="top" title="Release"
										ng-click="releaseOrder(allorder.permitsView)"
										ng-if="allorder.actionControlsView.showReleaseBtn">
										<span class="lnkRelease-icon"></span>
									</button>
									<a href="{{allorder.permitsView.viewOrderSummaryURL}}"
										target="_blank" data-toggle="tooltip"
										title="Show Order Summary PDF"
										ng-if="allorder.actionControlsView.viewOrderSummary"><button
											id="lblViewOrdSummary" type="button"
											class="border-none bg-none pad0 pull-left mb5 lblViewOrdSummary"
											data-toggle="tooltip" data-placement="top"
											title="Show Order Summary PDF"
											ng-if="allorder.actionControlsView.viewOrderSummary">
											<span class="lnkDownload-icon"></span>
										</button></a>
									<button id="lblDeleteVisible" type="button"
										class="border-none bg-none pad0 pull-left mb5"
										data-toggle="tooltip" data-placement="top"
										title="Delete this Order" ng-click="performDeleteOrder(allorder.permitsView.orderNbr)"
										ng-if="allorder.actionControlsView.deleteVisible">
										<span class="deleteBill-icon"></span>
									</button>
								</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
```

![image](https://user-images.githubusercontent.com/15215691/32556149-a6e75ee6-c4c4-11e7-8005-4f3a238d0746.png)

**Comment by Narretz** [comment] 2017-11-09 10:47
Is this also in IE 11? 
Hard to say, nothing in the profile stands out. I assume it's the sheer amount of bindings / directives that is slowing down IE.
That said, there are some oddities in the code, e.g.
```
<a href="{{allorder.permitsView.viewOrderSummaryURL}}"
  target="_blank" data-toggle="tooltip"
  title="Show Order Summary PDF"
  ng-if="allorder.actionControlsView.viewOrderSummary"><button
    id="lblViewOrdSummary" type="button"
    class="border-none bg-none pad0 pull-left mb5 lblViewOrdSummary"
    data-toggle="tooltip" data-placement="top"
    title="Show Order Summary PDF"
    ng-if="allorder.actionControlsView.viewOrderSummary">
    <span class="lnkDownload-icon"></span>
  </button></a>
```

- the a tag should be using ng-href
- you shouldn't nest buttons inside a tags
- you have the same ngIf condition on the button as on the a tag, which is redundant.

**Comment by haribalaji79** [comment] 2017-11-14 02:03
Yes, made the above changes. Still noticing same perf issue with ng-repeat containing ng-if.
Planning to write a custom directive which iterates over <td></td> and finally compile entire HTML.

**Comment by Narretz** [comment] 2017-11-14 10:05
I think we're at a point where we have to chalk this down to a fundamental slowness of IE in conjunction with large DOM trees. AngularJS isn't immune to that unfortunately. Maybe you should look into a datatables / virtual table solution. 

(Closing because no action can be taken in core)

**Closed by Narretz** 2017-11-14 10:05 UTC
Labels: browser: IE11, component: ngAnimate, component: ngRepeat, type: perf

**Comment by nskpavani** [comment] 2018-05-26 03:43
Hi all,
I am facing the same issue....how to disable ng-animations for ng-repeat only?? can anyone post a coding sample to do that?? I could not follow in documentation instructions

**Comment by haribalaji79** [comment] 2018-05-26 06:59
write a <div> which wraps the ng-repeat code. In the <div> you can specify a directive for e.g. disable-animations

<div class="editableDropdown load-axle input-group" disable-animations>
   <ng-repeat code goes here--->
</div>.

angular.module("main").directive("disableAnimations", function($animate) {
        return {
            restrict: 'A',
            link: function( $scope, elem, attrs) {    
            	$animate.enabled(elem, false);
            }
        }
    });

**Comment by nskpavani** [comment] 2018-05-27 22:40
Thanks haribalaji79 . I did that. But the problem still exists. I have a very huge DB and I have a case where I must render 1000 records (despite having pagination) in single page. There IE11 is getting crashed and freezes at this point. I am struggling with this issue for over a week now. And the coding is done by some other developer and no KT as of now regarding the project!! Please advice on how to Batch this huge list and render in the table?? 

I am going with track by to improve performance and I think that is not enough. 

Thanks 
nskp

**Comment by haribalaji79** [comment] 2018-05-28 17:00
Narretz gave the solution already..Datatables or virtual tables solution.
Also you can do smart rendering when the user scrolls, for e.g. initially render 100 records. As the user scrolls more render next 100 records and so on...

**Comment by nskpavani** [comment] 2018-05-30 02:44
Thanks haribalaji79. I will try doing that

**Comment by gsraopersonal** [comment] 2018-10-24 22:57
Any update on this please. i do have similar issue while binding 5K records to Angular 6 with Bootstrap 4.
