### ISSUE TITLE
select ng-model sets the value to "null" in complex application when not using ng-options

### ISSUE THREAD

**Issue by pelallemant** [angular/angular.js#16359] opened 2017-12-06 10:43 UTC
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**

When I am using a `<select ng-model="item.varX"></select>` with options in raw ( `<option value="val1">val1</option>` ...) without ng-options, when the directive which holds the select is removed (ng-if condition), the model value is modified and set to null. This happens in a project with alot nested directives, on each select with raw options.
I don't have any event registered nor other directives impacting the value of the model, all the other properties are unchanged. 

**Expected / new behavior:**

The value of my model should not change when the select is destroyed.

**Minimal reproduction of the problem with instructions:**

The following plunker doesn't bug yet, but it's basically this system which bugs when wrapped in lot of directives. 
https://plnkr.co/edit/nRCJjlqIL9j5HP8PH5IK?p=preview

**AngularJS version:** 1.6.7

**Browser:** [Google Chrome 62.0.3202.94]

**Anything else:**

If i replace the raw values with a ng-options, I don't have the bug anymore. But I think that it should not produce this bug even when not using ng-options.

EDIT: http://plnkr.co/edit/RrUMcrLDTcpMsU8Fsjmb?p=preview

**Comment by gkalpak** [comment] 2017-12-06 11:18
I'm afraid there is not much we can do without an actual reproduction. Can you please try to reproduce the issue in the plnkr?

**Comment by pelallemant** [comment] 2017-12-06 11:23
I'll try to reproduce it in a minimal way, I'll edit the plnkr later (this evening).

**Comment by pelallemant** [comment] 2017-12-09 14:49
@gkalpak http://plnkr.co/edit/RrUMcrLDTcpMsU8Fsjmb?p=preview

I removed 95% of the code to isolate the problem. In the plunkr I have the bug: school_level_crit1_direction is set to null when you use the "school block" then use the "work block".
Idem for "work block". 
You can see that the input of type integer is not affected.

**Comment by pelallemant** [comment] 2017-12-09 14:58
With css fixed: http://plnkr.co/edit/RrUMcrLDTcpMsU8Fsjmb?p=preview

**Comment by pelallemant** [comment] 2017-12-10 10:31
I give you some information about understanding faster the application:

I made a "form" system which is composed of "blocks". 
The application you see allows you to view 2 blocks in edition mode, and in disabled-edition mode.

First in the controller, I initialize the mission. Each block has access to the mission, and each block is reponsible of some properties of the mission.

The "hsBlocks" directive shows the select and the desired block in the mode requested. 
The "hsMissionBloc" directive is a proxy: it allows me to select the desired directive.

**Comment by gkalpak** [comment] 2017-12-11 09:21
Sorry, it is still a lot going on (at least 3 custom directives + manual `$compile` calls + two 3rd-party libs (`ui-bootstrap`, jQuery). Could you please try to slim it down, leaving only the essential parts to reproduce the issue (and making sure it is caused by AngularJS and not by a 3rd-party lib)?

**Comment by pelallemant** [comment] 2017-12-11 09:44
I remove ui-bootstrap which were useless. There is no other Js library than angular.
This is the minimal bugging demo I can provide you, the error happens only when I have a $compile call.

If you replace the `<select ng-model="mission.school_level_crit1_direction"></select>` by a `<input type="text" ng-model="mission.school_level_crit1_direction" />` you can see the value is not reset to null.

Do you see the bug ? (click on select => block0, then change to block1, the value of the input is set to null ..).

**Comment by pelallemant** [comment] 2017-12-11 10:25
I removed jQuery too.

**Comment by gkalpak** [comment] 2017-12-11 11:21
Just for reference, this is an [actual minimal reproduction][1].
(And it is not even a good one, because it has lots of cryptic names that impose a mental overhead, but at least it is minimal and allows me to try to investigate the actual problem in a few minutes.)

Besides saving valueable time to those trying to help, the process of creating a minimal reproduction always gives a much better insight into the problem and the underlying issues and very often allows you to find the root cause yourself.

##
Anyway, the issue is that you are compiling the new HTML content of your `hsMissionBlock` element, but do not destroy the bindings created by the previous compilation. Using `$compile` is an advanced operation and you should always make sure to clean up after yourself. E.g.:

```diff
 directive('hsMissionBlock', ($compile) => ({
   scope: {
     blockName: '@',
     mission: '=',
   },
   link: function(scope, elem) {
+    let childScope;
     scope.$watch('blockName', newValue => {
+      if (childScope) childScope.$destroy();
+      childScope = scope.$new();
+
       elem.html(`<div mission-block-${newValue} mission="mission"></div>`);
-      $compile(elem.contents())(scope);
+      $compile(elem.contents())(childScope);
     });
   },
 })).
```

[Updated plnkr][2]

##
You should always try to use one of the built-in structural directives in similar situation, because they take care of this clean-up work for you. In this particular case, using `ngSwitch` sounds like a good approach for example.

##
Closing, since everything works as expected on the AngularJS side.

[1]: http://plnkr.co/edit/xrzbOc9gG7n9CLcOzl9m?p=preview
[2]: http://plnkr.co/edit/Ih0yQzzP1UPoZZ22XtX7?p=preview

**Closed by gkalpak** 2017-12-11 11:21 UTC
Labels: component: forms, needs: more info, type: bug

**Comment by pelallemant** [comment] 2017-12-11 11:55
Thanks !
