### ISSUE TITLE
[jqLight] Prepend method freezes browser

### ISSUE THREAD

**Issue by smashercosmo** [angular/angular.js#12327] opened 2015-07-11 08:56 UTC
jqLight's prepend method freezes browser completely. Here is a [plunker](http://plnkr.co/edit/CcUDVQoWOTFo1cSvKLh1). Append method works fine.

**Comment by gkalpak** [comment] 2015-07-11 16:45
Duplicate of #11217 (e.g. see https://github.com/angular/angular.js/issues/11217#issuecomment-76715981).

Because of how the Angular compiler works, you can't prepend elements to the element you are compiling during the compilation phase.

**Closed by gkalpak** 2015-07-11 16:45 UTC
