### ISSUE TITLE
AngularJS number $filter issue for numbers with 20 and 21 digits

### ISSUE THREAD

**Issue by rajeshroshan** [angular/angular.js#11183] opened 2015-02-25 21:00 UTC
I use AngularJS $filter to format a number to 2 decimal places per the code below

    $filter('number')(n, 2)
When 'n' is 20 or 21 digits long, the result of the above expression is NaN.

No issues when 'n' is less than 20 digits or more than 21 digits (for more than 21 digits, the above expression is displayed in scientific notation)

Any thoughts on how to fix the NaN issue for 20 and 21 digit numbers?

**Comment by pkozlowski-opensource** [comment] 2015-03-01 12:42
@rajeshroshan thnx for reporting. We've got an issue already for this one (https://github.com/angular/angular.js/issues/8674), unfortunately it is not trivial to fix :-/

Closing as duplicate of #8674 to centralise the discussion.

**Closed by pkozlowski-opensource** 2015-03-01 12:42 UTC
