### ISSUE TITLE
ng-model: add validateOn to allow validation on different events then updating

### ISSUE THREAD

**Issue by jbedard** [angular/angular.js#15128] opened 2016-09-12 21:37 UTC
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
`ng-model` always updates and validates at the same time based on the `updateOn`

**What is the motivation / use case for changing the behavior?**
I normally don't want my model to be updated as the user types. It might show up other places half complete, it might not be valid yet etc. But I normally do want instant validation as the user types.

I find myself always trying to achieve this various ways such as setting `ng-model` to a copy of the real model or setting it to `Object.create(realModel)` then copying the value to the real model on blur.

WDYT? Or is there an easier way to do this that I'm missing?

**Comment by Narretz** [comment] 2016-09-13 17:37
Duplicate of https://github.com/angular/angular.js/issues/7016

It didn't get much traction, so I'm still not convinced we need it.

**Closed by Narretz** 2016-09-13 17:37 UTC
