### ISSUE TITLE
$templateCache in ngInclude does not work correct with $http interception

### ISSUE THREAD

**Issue by sargiss** [angular/angular.js#11911] opened 2015-05-20 11:19 UTC
Let we have some template cached through $templateCache.
Call it template_uri.
When ngInclude tries to resolve template it use $http service with cache option set to $templateCache.
so $http looks through cache and if it does not exist value  for passed template name (template_uri in our case) then makes request to server. It works perfect until we use interception. In that case we may add some additional parameters to url and in result get something like template_url?param=someval which of course could not be found in cache.

**Comment by Narretz** [comment] 2015-05-25 18:44
Yes, the template urls are used as the cache key. It's not really expected that they change. What kind of parameters do you append? Could you use headers instead?

**Comment by pkozlowski-opensource** [comment] 2015-06-28 18:05
Closing due to the lack of the reproduce scenario / sufficient info for this issue to be actionable.

**Closed by pkozlowski-opensource** 2015-06-28 18:05 UTC
Labels: component: misc core, needs: more info
