### ISSUE TITLE
IE 9 and 11: infinite digest loop due to async href

### ISSUE THREAD

**Issue by joliveros** [angular/angular.js#13614] opened 2015-12-23 00:23 UTC
In order to reproduce the issue you may go to: 

http://crew.secureaccess.io/signup/sos

when you click next at the bottom you will be able to see the error below in the log.

I've tracked down the issue so far as to conclude that the infinite loop keeps reaching the following line before calling `self.url()` again.

https://github.com/angular/angular.js/blob/v1.4.8/src/ng/browser.js#L222

I'm aware that the following issues are related and that a pull request has already landed in master to fix this:

#9235
#11675
#11439

However, I'm still seeing this issue with angular v1.4.8.

```js
Error: Invalid pointer

   at self.url (http://192.168.0.11:3000/vendor.js:6157:10)
   at setBrowserUrlWithFallback (http://192.168.0.11:3000/vendor.js:12727:10)
   at Anonymous function (http://192.168.0.11:3000/vendor.js:12856:16)
   at Scope.prototype.$eval (http://192.168.0.11:3000/vendor.js:16561:10)
   at Scope.prototype.$digest (http://192.168.0.11:3000/vendor.js:16379:16)
   at Scope.prototype.$apply (http://192.168.0.11:3000/vendor.js:16669:14)
   at Anonymous function (http://192.168.0.11:3000/vendor.js:24127:18)
   at jQuery.event.dispatch (http://192.168.0.11:3000/vendor.js:33981:7)
   at elemData.handle (http://192.168.0.11:3000/vendor.js:33667:6)
angular.js (12328,1)
```

**Comment by Narretz** [comment] 2015-12-31 14:53
I do not get an error when using your site with IE11. It's also always better to have a minimal example that shows the error, not a complex app.

**Comment by joliveros** [comment] 2015-12-31 17:55
when you use the site currently it doesn't throw errors because I disabled updating $location
if I update location then the above error occurs
`$state.go(state, opts, {location: false, reload: reload});`

**Comment by Narretz** [comment] 2015-12-31 18:15
We really need a demo of the problem, with code, runnable and preferably
minimal in a plnkr. How else are we going to debug this?

**Comment by joliveros** [comment] 2015-12-31 18:42
Got it. Brother... Have a happy new year!!! thank you for your help! I'll get something together asap

**Comment by Narretz** [comment] 2016-04-06 15:47
I'm going to close this issue because we have no reproduction of the issue. Feel free to reopen this issue if you can provide a reproduction (ideally a runnable demo in a https://plnkr.co or similar).

**Closed by Narretz** 2016-04-06 15:47 UTC
Labels: browser: IE11, browser: IE9, component: $location, needs: more info
