### ISSUE TITLE
Can't load array of arrays

### ISSUE THREAD

**Issue by jakobmaier** [angular/angular.js#12269] opened 2015-07-04 10:11 UTC
My server returns resources that are arrays rather than objects. 
Example: `[[2015,1,1],[2015,1,8]]`

angular resources doesn't recognise this and convertes the array into an object which seems to be a bug. The configuration I use is `getDates: { method: 'GET', url: 'dates', isArray: true }`.

I managed to fix this by manually adding a check in the source:

    if (action.isArray) {
      value.length = 0;
      forEach(data, function(item) {
        if (typeof item === "object" && !(item instanceof Array)) {
          value.push(new Resource(item));
        } else {
          // Valid JSON values may be string literals, and these should not be converted
          // into objects. These items will not have access to the Resource prototype
          // methods, but unfortunately there
          value.push(item);
        }
      });
    }

The `&& !(item instanceof Array)` is from me and not in the original source. The comment below hints that arrays simple have been forgotten?

**Comment by pkozlowski-opensource** [comment] 2015-07-04 10:19
I would argue that this isn't a valid use-case for $resource since you are not dealing with domain objects here but just fetching bunch of data. Do you send other types of requests (POST, PUT, DELETE) for this resource? Why not use lower-level $http?

Could you share more code (place where you define your resource and use it)?

**Comment by jakobmaier** [comment] 2015-07-04 11:12
This use case is a kind of an edge case.
I have domain objects called "delivery" that contain the field `date`. 
I have the requirement to display all dates where a delivery takes place and in order to avoid loading all domain objects (very time intensive), I just request an array of dates.

Dates are represented as an `Array(year, month, day)`.

I think this is a valid use case. However, if you think it isn't, the issue can also be solved by implementing `transformResponse()` and manually converting the Arrays into appropriate JS date objects - so it wouldn't be a big deal.

My alternate solution:

    getDates:   { method: 'GET', url: 'dates', isArray: true,
                  transformResponse: function(data, headersGetter){
                      var result = JSON.parse(data);
                      var deliveryDates = [];
                      for (var i = 0; i < result.length; ++i) {
                          deliveryDates.push(DateUtils.arrayToDate(result[i]));
                      }
                      return deliveryDates;
                 }}

**Comment by jakobmaier** [comment] 2015-07-04 11:29
Ok, my alternate solution I posted doesn't work, since it returns an array of dates, which is - again - converted into an array of (empty) objects.
I now use the modified ngResource code with the condition `if (typeof item === "object" && !(item instanceof Array) && !(item instanceof Date)) { ... }`

**Comment by lgalfaso** [comment] 2015-07-04 16:29
I agree with @pkozlowski-opensource, this is not a valid use case as an array is not a resource.

**Comment by wesleycho** [comment] 2015-07-04 19:22
Your endpoint should probably be returning an array of:
```
{
  date: [...]
}
```
if that is how you want to represent dates. It does not sound like good API design to just return an array of arrays with no context or flexibility if the desired data structure changes.

**Comment by gkalpak** [comment] 2015-07-05 18:13
Regardless of what people think of the usecase (I try to be non-opinionated when it comes to APIs), a method defined as `{method: 'GET', ..., isArray: true}` is **not** supposed to be converted to an object by `ngResource`, but to an array (per the docs).
If it converts the array to an object, it seems indeed to be a bug (although, I have used similar custom methods several times and this problem never arose).

@jakobmaier, could you provide a runnable demo of the issue and/or verify that what you get from the server is indeed a JSONified array (and post the response data here) ?
(E.g. PHP is _notorious_ for (unexpectedly) JSON-encoding arrays as objects under certain circumstances.)

**Comment by pkozlowski-opensource** [comment] 2015-07-05 18:56
@gkalpak from what I understand it is about converting a nested array (not a top level one). Which totally make sense since each entry in an array should be an instance of a resource object and not an arbitrary array.

**Comment by gkalpak** [comment] 2015-07-05 19:17
@pkozlowski-opensource, aha :) I think you are right. I totally misread that.
In that case, items should indeed be resource instances (i.e. objects).

**Comment by lgalfaso** [comment] 2015-07-05 19:56
I think there is enough consensus that this is the expected behavior, so closing this

**Closed by lgalfaso** 2015-07-05 19:56 UTC
Labels: component: ngResource, needs: more info
