### ISSUE TITLE
'this' points to Window instead of directive object in 'link' function

### ISSUE THREAD

**Issue by zgmnkv** [angular/angular.js#12891] opened 2015-09-19 11:49 UTC
Hi guys,
I'm trying to use TypeScript with AngularJS and I faced to some issues when I tried to use class for directive definition.
Inside 'link' function of directive, 'this' does not point to the current directive definition object. Instead, 'this' points to global 'Window'. So I can't fully use TypeScript classes with inheritance for directives, which may be very useful for code reuse.
What's the reason of such behavior?
Could this issue be fixed?
This plunker demonstrates the issue: http://plnkr.co/edit/lCH5zOUSHkLi0WQ7G4GX?p=preview .
Thanks.

**Comment by Narretz** [comment] 2015-09-21 12:45
Dupe of #8549
There's a PR https://github.com/angular/angular.js/pull/9306, but there were some reservations about performance, so we'll have to see about that.

**Comment by zgmnkv** [comment] 2015-09-21 13:03
Thanks @Narretz . Haven't found this issue. I think we can close this one as a duplicate.

**Closed** 2015-09-21 13:11 UTC
