### ISSUE TITLE
SVG animateTransform bug Chrome

### ISSUE THREAD

**Issue by beginendrepeat** [angular/angular.js#16531] opened 2018-04-15 19:13 UTC
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**

https://jsfiddle.net/xyb1r0xc/
SVG text elements generated by ng-repeat are moved strangely stick together when the first text is animated until the animation of the second text begins. Reproducible in Chrome v65. In Firefox v59 animations of both texts start correctly.

**Expected / new behavior:**

Texts should start moving different times.

**Minimal reproduction of the problem with instructions:**

Reproduction in Chrome: 
https://jsfiddle.net/xyb1r0xc/

**AngularJS version:** 1.6.9

**Browser:** [Chrome 65]

**Anything else:**

**Comment by gkalpak** [comment] 2018-04-15 22:07
This seems to happen due to Chrome not being able to pick up the updated `begin` attribute, which is asynchronously set by `ng-attr-begin`. Using `begin` directly [seems to work][1] though.

Not sure if this is expected behavior or a Chrome bug (does the spec specify the correct behavior in such a case?). Anyway, everything is working as expected on the Angular side (afaict), so I am closing this as non-actionable.

[1]: https://jsfiddle.net/qan6q14z/2/

**Closed by gkalpak** 2018-04-15 22:07 UTC
