### ISSUE TITLE
Extremely long error URLs that sometimes don't lead to anything

### ISSUE THREAD

**Issue by mgol** [angular/angular.js#6077] opened 2014-01-31 19:08 UTC
Sometimes I get really long error URLs in my Karma tests, like the one pasted below.

Try clicking on it, the only thing you'll get is:

```
Failed to instantiate module {0} due to:
{1}
```

that doesn't say a lot.

http://errors.angularjs.org/1.2.10/$injector/modulerr?p0=test%2Fmocks-inlined%2Flanguage-tags.json&p1=%5B%24injector%3Anomod%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.2.10%2F%24injector%2Fnomod%3Fp0%3Dtest%252Fmocks-inlined%252Flanguage-tags.json%0Ax%2F%3C%40http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fdist%2Fbc6337f5.vendor.js%3F1391195095000%3A92%0AVc%2Fb.module%3C%2F%3C%2Fb%5Be%5D%3C%40http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fdist%2Fbc6337f5.vendor.js%3F1391195095000%3A106%0AVc%2Fb.module%3C%2F%3C%40http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fdist%2Fbc6337f5.vendor.js%3F1391195095000%3A106%0Ae%2F%3C%40http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fdist%2Fbc6337f5.vendor.js%3F1391195095000%3A115%0Aq%40http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fdist%2Fbc6337f5.vendor.js%3F1391195095000%3A93%0Ae%40http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fdist%2Fbc6337f5.vendor.js%3F1391195095000%3A115%0A%24b%40http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fdist%2Fbc6337f5.vendor.js%3F1391195095000%3A118%0AworkFn%40http%3A%2F%2Flocalhost%3A8080%2Fbase%2Ftest%2Funit%2Fvendor%2Fangular-mocks.js%3F1391195050000%3A2144%0Ajasmine.Block.prototype.execute%40http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fnode_modules%2Fkarma-jasmine%2Flib%2Fjasmine.js%3F1374365571000%3A1145%0Ajasmine.Queue.prototype.next_%40http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fnode_modules%2Fkarma-jasmine%2Flib%2Fjasmine.js%3F1374365571000%3A2177%0Ajasmine.Queue.prototype.start%40http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fnode_modules%2Fkarma-jasmine%2Flib%2Fjasmine.js%3F1374365571000%3A2130%0Ajasmine.Spec.prototype.execute%40http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fnode_modules%2Fkarma-jasmine%2Flib%2Fjasmine.js%3F1374365571000%3A2458%0Ajasmine.Queue.prototype.next_%40http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fnode_modules%2Fkarma-jasmine%2Flib%2Fjasmine.js%3F1374365571000%3A2177%0Ajasmine.Queue.prototype.start%40http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fnode_modules%2Fkarma-jasmine%2Flib%2Fjasmine.js%3F1374365571000%3A2130%0Ajasmine.Suite.prototype.execute%40http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fnode_modules%2Fkarma-jasmine%2Flib%2Fjasmine.js%3F1374365571000%3A2604%0Ajasmine.Queue.prototype.next_%40http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fnode_modules%2Fkarma-jasmine%2Flib%2Fjasmine.js%3F1374365571000%3A2177%0Ajasmine.Queue.prototype.start%40http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fnode_modules%2Fkarma-jasmine%2Flib%2Fjasmine.js%3F1374365571000%3A2130%0Ajasmine.Suite.prototype.execute%40http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fnode_modules%2Fkarma-jasmine%2Flib%2Fjasmine.js%3F1374365571000%3A2604%0Ajasmine.Queue.prototype.next_%40http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fnode_modules%2Fkarma-jasmine%2Flib%2Fjasmine.js%3F1374365571000%3A2177%0Ajasmine.Queue.prototype.next_%2FonComplete%40http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fnode_modules%2Fkarma-jasmine%2Flib%2Fjasmine.js%3F1374365571000%3A2173%0Ajasmine.Suite.prototype.finish%40http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fnode_modules%2Fkarma-jasmine%2Flib%2Fjasmine.js%3F1374365571000%3A2561%0Ajasmine.Suite.prototype.execute%2F%3C%40http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fnode_modules%2Fkarma-jasmine%2Flib%2Fjasmine.js%3F1374365571000%3A2605%0Ajasmine.Queue.prototype.next_%40http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fnode_modules%2Fkarma-jasmine%2Flib%2Fjasmine.js%3F1374365571000%3A2187%0Ajasmine.Queue.prototype.next_%2FonComplete%40http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fnode_modules%2Fkarma-jasmine%2Flib%2Fjasmine.js%3F1374365571000%3A2173%0Ajasmine.Spec.prototype.finish%40http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fnode_modules%2Fkarma-jasmine%2Flib%2Fjasmine.js%3F1374365571000%3A2432%0Ajasmine.Spec.prototype.execute%2F%3C%40http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fnode_modules%2Fkarma-jasmine%2Flib%2Fjasmine.js%3F1374365571000%3A2459%0Ajasmine.Queue.prototype.next_%40http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fnode_modules%2Fkarma-jasmine%2Flib%2Fjasmine.js%3F1374365571000%3A2187%0Ajasmine.Queue.prototype.next_%2FonComplete%2F%3C%40http%3A%2F%2Flocalhost%3A8080%2Fbase%2Fnode_modules%2Fkarma-jasmine%2Flib%2Fjasmine.js%3F1374365571000%3A2167%0A

**Comment by mzgol** [comment] 2015-03-11 22:37
I've just got a 374 thousand bytes long URL. :-) Such things are able to crash the browser.

It'd be good to pinpoint the issue but, in the meantime a hard limit on the length of the URL might help; this long URLs are not helpful anyway.

This was Angular 1.3.14, I'll check with 1.4 later.

**Comment by avdd** [comment] 2015-05-11 07:16
How do I stop the noise in my testing console?  It's extremely irritating.

**Comment by lachenmayer** [comment] 2015-08-03 13:51
I agree, is there a way to switch to normal error reporting?
In the Chrome developer tools, this results in entirely useless error messages since the console cuts off long lines:
![image](https://cloud.githubusercontent.com/assets/38614/9038810/17a8bcc8-39ef-11e5-8dcf-bb51650193b2.png)

**Comment by caitp** [comment] 2015-08-03 13:58
Is this still affecting chrome 45/46? I recall some cls landing which read like they would have addressed this issue, so i just assumed this had been resolved. Can you still reproduce this with Canary?

**Comment by lachenmayer** [comment] 2015-08-03 14:46
Version 46.0.2471.0 canary (64-bit)
![image](https://cloud.githubusercontent.com/assets/38614/9039944/b3d79022-39f6-11e5-8706-737cd398bede.png)

**Comment by leegee** [comment] 2016-01-13 15:27
Whilst this may not (or may be) still an issue in Chrome, it certainly is when running automated tests -- so much so that I imagine I am missing some flag that might produce errors that are not a hundred lines of URL-encoded URLs....

**Comment by BelfordZ** [comment] 2016-03-21 20:13
any recommended solutions for while in test?

IMO there should be an option to truncate urls in stack traces

**Comment by Narretz** [comment] 2017-02-16 11:42
Duplicate of #14744 and the the url length will be configurable (and capped by default) in the future: #15707

**Closed by Narretz** 2017-02-16 11:42 UTC
Labels: component: misc core, frequency: moderate, type: bug, type: docs
