### ISSUE TITLE
AngularJS Hash Bang Urls and Query Parameter ordering

### ISSUE THREAD

**Issue by CMCDragonkai** [angular/angular.js#6172] opened 2014-02-07 12:31 UTC
According to [AngularJS documentation](http://docs.angularjs.org/guide/dev_guide.services.$location#hashbang-and-html5-modes), it states that a hash bang URL is in this format:

```
http://foo.com/#!/bar?baz=23
```

This indicates that the hash fragment is between the path and the query parameters of the URL. It's DOMAIN - HASH FRAGMENT - QUERY PARAMETER

However on [Google AJAX Crawling Specification](https://developers.google.com/webmasters/ajax-crawling/docs/specification), when it converts a hash bang URL into the `_escaped_fragment_` format for the purposes of indexing and then converts it back for search results, it instead places the hash fragment after the query parameter. (See the Search Results section)

```
http://foo.com/?baz=23#!/bar
```

This indicates DOMAIN - QUERY PARAMETER - HASH FRAGMENT.

It seems that both are a valid URL structure (try it on a browser with any non SPA application). However if you are using this URL format on any AngularJS site, the site correctly ascertains the path, however it "forgets" the query parameters.

So if you go to [http://docs.angularjs.org?key=value#!/guide](http://docs.angularjs.org?key=value#!/guide), it turns into [http://docs.angularjs.org/guide](http://docs.angularjs.org/guide). As you can see it forgets the query parameters. If I'm using the Google AJAX specification, then this would result in search results having URLs that don't work properly as their query parameters gets dropped.

I did some testing with both urls which has illuminated the problem:

**Case 1**: Using DOMAIN - HASH - QUERY PARAMETER (AngularJS format) (http://example.com/#!/path?key=value), the query parameters never gets received by the server, but it is remembered on the client side. It's also available in `$location.search()`.

**Case 2**: Using DOMAIN - QUERY PARAMETER - HASH (Google's format) (http://example.com/?key=value#!/path), the query parameter gets received by the server (as it is not after the #), but it is forgotten on the client side. It's also not available in `$location.search()`.

Perhaps a solution can be made for case 2. So that when there is query parameter and then hash fragment, AngularJS can correctly remember the query parameter and shift it to the end of the URL (if converting to HTML5 urls) and also make it accessible with `$location.search()`. Case 1 cannot be solved due to the URL standards as everything after the # is not sent to the server.

**Comment by timomall** [comment] 2015-02-20 19:00
This is also breaking google analytics campaign tracking when linking to hashbang URLs. 

Let's take a URL like domain.com/#!/path?utm_campaign=blah. If you go to this URL and print out window.location.search, there is nothing there. 

If you use the DOMAIN QS HASH version like domain.com?utm_campaign=blah#!/path, the query string is in window.location.search. The problem is that DQS breaks the routin
This is also breaking google analytics campaign tracking when linking to hashbang URLs. 

Let's take a URL like domain.com/#!/path?utm_campaign=blah. If you go to this URL and print out window.location.search, there is nothing there. 

I'm assuming that google analytics is going to use whatever it finds in window.location.search for its campaign tracking. 

If you use the DOMAIN QS HASH version like domain.com?utm_campaign=blah#!/path, the query string is in window.location.search. The problem is that DQS breaks the routing when in html5 mode.

**Comment by nmandya** [comment] 2016-01-19 04:18
Is there any update on this? I am having the same problem as what "timomall" has reported on 9 Dec 2014.

**Comment by gkalpak** [comment] 2016-01-25 12:06
There are too different concepts here:

1. On one hand we have the _query_ part of the URL (that comes before the _hash fragment_). This is also visible to the server (i.e. it is part of a request) and is **not** used by Angular for it's client-side routing (in the default hashbang mode).

2. On the other hand, the hash fragment (which is used by Angular for it's client-side routing) may contain a "query-like" part which typically is part of the _hash fragment_ (and is ignored by the server). This is the part that Angular uses (and makes available under `$location.search()`).
As far as the browser is concerned, though, this is just part of the _hash fragment_ and totally different (and independent) from the actual _query_ part of the URL (if any).

In order to avoid confusing crawlers, one should probably encode that second "query-like" part of the _hash fragment_, when using an `_escaped_fragment_` URL.

--
In any case, the [Google AJAX Crawling Specification][1] has been [deprecated][2] since October 2015.
Closing as I don't believe there is anything we can fix on the Angular side of things.

[1]: https://developers.google.com/webmasters/ajax-crawling/docs/specification
[2]: https://googlewebmastercentral.blogspot.gr/2015/10/deprecating-our-ajax-crawling-scheme.html

**Closed by gkalpak** 2016-01-25 12:06 UTC
Labels: component: $location, frequency: moderate, needs: investigation, type: bug

**Comment by nmandya** [comment] 2016-01-26 06:18
My problem is not with the crawler at all. My code was using the non-HTML5 mode and we have URLs given to external customers which are of the form https://abcd.efgh?utm_campaign=abcd#/abcd/12. Now, if I turn on HTML5 mode and the external customer tries to use the URL already with them, the URL changes in the browser to just https://abcd.efgh/abcd/12. The query parameter of utm_campaign is completely lost.

How can I get angularjs to preserve the query parameter so that the URL becomes https://abcd.efgh/abcd/12?utm_campaign=abcd when somebody tries to use the old URL?

**Comment by gkalpak** [comment] 2016-01-26 08:59
@nmandya, I suspect it is a server cofiguration issue. But you can't really mix URL styles (hashbang and html5 mode) and have things work as expected, I'm afraid.

In https://abcd.efgh?utm_campaign=abcd#/abcd/12, Angular is only concerned with the part after `#`, namely `/abcd/12`. It sees it as:

```js
$location.path()   === '/abcd/12'
$location.search() === {}
$location.hash()   === ''
```

The equivalent of the above in html5 mode is indeed https://abcd.efgh/abcd/12.

The "problem" is that in hashbang mode, there is the _query_ part of the URL (before the `#`), which Angular is not concerned with and the _query_ part of the client-side routing (after the `#`) which Angular "sees" and interacts with. In html5 mode there is only one _query_ path.
So you can't really use the hashbang mode URLs in html5 mode (unless you do some server-side transformation maybe, converting `?utm_campaign=abcd#/abcd/12` to `#/abcd/12?utm_campaign=abcd`).

**Comment by yoxel** [comment] 2016-04-05 19:05
My problem is that IE10 auto-rewrites "https://host/#hash?search=..." to "https://host/?hash&search=..." so our Angular2 routing is all broken.

**Comment by gkalpak** [comment] 2016-04-07 21:41
If it's a Angular2 issue, you should raise it on https://github.com/angular/angular.
Although it sounds more like a IE10 issue...

**Comment by ed-at-work** [comment] 2017-03-24 06:29
Hi there, hate to comment on a closed, old issue, but the fact is that the URI RFC (RFC3986) is pretty clear that the fragment identifier comes _after_ the query string.  The way the non-html5 mode of Angular's location service works is to lose the query portion of the URL if it appears prior to the fragment.  I have a small patch to the location service that fixes this issue.  I'm in the process of submitting a pull request for it. Hopefully it will help someone.

**Comment by ramintagizade** [comment] 2017-07-19 10:07
Why AngularJS supports hashbang ? Can it be solved in future ? It just does not work with server side php ,especially post methods .

**Comment by gkalpak** [comment] 2017-07-19 12:54
For support questions, please, use one of the [appropriate support channels][1].
Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
