### ISSUE TITLE
Select element using ngoptions isn't staying in sync with ngmodel on selected option removal

### ISSUE THREAD

**Issue by dberringer** [angular/angular.js#10677] opened 2015-01-08 02:45 UTC
I'm having an issue where a the model on a select element will get out of sync with its displayed value if it has a value selected then ng-options removes the selected option from the list.  The select displays null but the model's value remains the same.  

Here is a fiddle that illustrates the issue: http://jsfiddle.net/dberringer/m2rm8Lh6/2/
It's Using angular 1.3.8
I have tested with Chrome Version 39.0.2171.95 (64-bit) OSX and Firefox on angular 1.2.0, 1.2.28 & 1.3.8

To reproduce make a note of the selected item value which is 2.  Then click the "Remove Second Item" button.  Notice that the selected option has been removed and the current selection is now the null option which is to be expected but also notice that the selected value still shows 2.  It seems that ng-model never updated the select element's model so now they are out of sync.

Huan Feng mentioned that there is no check to update the model when ng-options updates.
http://stackoverflow.com/questions/27812638/how-can-i-keep-ng-model-in-sync-with-a-select-element-after-ng-options-removes-t

Thanks.

**Comment by Narretz** [comment] 2015-01-08 09:40
@petebacondarwin We should check if the refactor already fixes this.

**Comment by lgalfaso** [comment] 2015-01-08 10:22
we should also fix this at the 1.3.x branch

**Comment by aabenoja** [comment] 2015-01-08 18:22
:+1: to fixing this on 1.3.

**Comment by LeonardoBraga** [comment] 2015-01-09 23:35
+1 for 1.3.

**Comment by Narretz** [comment] 2015-09-13 17:49
Dupe of https://github.com/angular/angular.js/issues/6379

**Closed by Narretz** 2015-09-13 17:49 UTC
Labels: branch: 1.3.x, component: forms, frequency: low, severity: confusing, type: bug
