### ISSUE TITLE
Difference in $location.path() between $locationChangeStart and $routeChangeStart

### ISSUE THREAD

**Issue by ravishivt** [angular/angular.js#12723] opened 2015-08-31 22:17 UTC
If I click on a route with path, "/test?dog=cat#boat" and have both the $locationChangeStart and $routeChangeStart handlers defined, I get different results of $location.path().  For locationChangeStart, I get the full path of "/test?dog=cat#boat" but with routeChangeStart, I only get "/test".  I could reconstitute the query params using the nextRoute argument that gets passed with $routeChangeStart but the "#boat" search history isn't available in the nextRoute.

This is on Angular 1.4.4.

**Comment by petebacondarwin** [comment] 2016-01-25 10:56
I cannot reproduce this in 1.4.4: See http://plnkr.co/edit/1WvuFIS9rDjDt9JhK7CU?p=preview

**Comment by gkalpak** [comment] 2016-06-01 17:57
Closing due to lack of reproduction.

**Closed by gkalpak** 2016-06-01 17:57 UTC
Labels: resolution: can't reproduce
