### ISSUE TITLE
$http - JSON.parse(b) is throwing exception for error string

### ISSUE THREAD

**Issue by lionkng123** [angular/angular.js#11549] opened 2015-04-12 15:36 UTC
AngularJS (v1.3.9) is encountering parsing exception while handling error condition of $http ajax call.

Server code:
```
@RequestMapping(value = "/error", method = RequestMethod.GET)
	@ResponseBody
	public Map<String, Object> getError() {
		throw new GenericException(HttpStatus.EXPECTATION_FAILED.value(), "Sample Error, should be caught by Angular");
	}
```

GenericException is customized exception and application is using `org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler`

```
@ControllerAdvice
public class GenericExceptionHandler extends ResponseEntityExceptionHandler {

	@ExceptionHandler(GenericException.class)
	protected ResponseEntity<Object> handleException(final GenericException exception, final WebRequest request) {
		return handleExceptionInternal(exception, exception.getErrorMessage(), null, HttpStatus.valueOf(exception.getErrorCode()), request);
	}
}
```

In AngularJS:
```
angular.module("dws", ['ngRoute'])
    .controller('ErrorController',
    ['$scope', '$http', function ($scope, $http) {
        $http.get("http://localhost:8080/rest/error")
            .success(function (data, status) {
                console.log(data);
            })
            .error(function (data, status) {
                console.log(data);
            }
        );
    }]
);
```

It results parsing exception:
>Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data

Closer look into angular.min.js, where parsing exception occurs:
```
function oc(b) {
     return F(b) ? JSON.parse(b) : b
}
```

For the work around, I am doing the following, which does solve this issue:
```
function oc(b) {
        try {
            return F(b) ? JSON.parse(b) : b;
        }
        catch(parseException) {
            return b;
        }
}
```

` function F(b)` is checking for String, however, all String format may not be parsed as JSON.

**Comment by pkozlowski-opensource** [comment] 2015-04-13 08:01
I presume (I can only guess since there is not enough info here...) that your server responds with some error status code (500?) and JSON response header (`application/json`) but the actual response body is not actual JSON. So your server says one thing but does different one.

I don't think we want to add `try \ catch` as suggested since the current error precisely points at the problem at hand. You need to change your setting on the server to either return valid JSON or different response headers for the error cases.

Closing as invalid.

**Closed by pkozlowski-opensource** 2015-04-13 08:01 UTC

**Comment by lionkng123** [comment] 2015-04-13 09:54
@pkozlowski-opensource, Thanks for the update and yes, you are correct.

I have updated headers at the time of propagating the error with `text/plain` which does solve it.

Changed code:
```
@ControllerAdvice
public class GenericExceptionHandler extends ResponseEntityExceptionHandler {

	@ExceptionHandler(GenericException.class)
	protected ResponseEntity<Object> handleException(final GenericException exception, final WebRequest request) {
		HttpHeaders headers = new HttpHeaders();
		headers.setContentType(MediaType.TEXT_PLAIN);
		return handleExceptionInternal(exception, exception.getErrorMessage(), headers, HttpStatus.valueOf(exception.getErrorCode()), request);
	}
}
```

Thanks again.

**Comment by bioball** [comment] 2015-06-30 15:54
I have this same problem. I'm interacting with a server that returns JSON string responses, e.g. `"foo"`, with `Content-Type:application/json`, and I see errors getting thrown by $http.

When inspecting the breakpoint, it looks like Angular is stripping out the leading and trailing quotes, and trying to parse `foo` instead of `"foo"`.

Am on Angular 1.4.1

**Comment by segevofer** [comment] 2015-08-16 15:27
+1 to @bioball.
Using Angular 1.4.3

**Comment by lgalfaso** [comment] 2015-08-16 19:54
Can someone create a plunker that shows the error?

**Comment by caitp** [comment] 2015-08-16 20:52
I'd be more interested in seeing info from the network tab in chromium (or similar tools in other browsers), to see what's actually being sent over the wire. I have some guesses as to what the problem is.

> Though I am not sure what is the problem with Content-Type:[text/plain;charset=ISO-8859-1]
>
>Angular is 
>working with: Content-Type:[text/plain]
>but not with: Content-Type:[text/plain;charset=ISO-8859-1]

As for the issue with text/plain on its own working, but with an encoding part not working, may be related to the Accept header sent by angular by default (which contains "text/plain" but not one with an encoding specified) --- I'd expect "not work" to mean receiving a 406 or some other error status code over the wire.

If you provide more information about what the client is actually receiving, it should be much easier to help with this.
