### ISSUE TITLE
Passing required directive controllers to directive's controller

### ISSUE THREAD

**Issue by timruffles** [angular/angular.js#12989] opened 2015-10-01 16:52 UTC
It's a pain to have to use `link` to pass other directives' controllers to your own. e.g I want to use a `ngModelController` instance with a directive that has a `controller` but no `link`.

At the [people](http://stackoverflow.com/questions/17116730/how-to-access-the-ngmodelcontroller-from-inside-the-controller-without-a-form-a) are having to resort to a potentially superfluous `link`, and some nasty boiler-plate:

```javascript
app.directive("myThing", function(){
  return {
    require: ["myThing", "ngModel"],
    controller: function(){
      // can't use ngModel here

      this.setNgModel = function() {
      }
    },
    link: function(scope, element, attrs, ctrls){
      var myCtrl = ctrls[0];
      myCtrl.setNgModel(ctrls[1]);
    }
  }
});
```

It'd be great to have a `$controllers` local injected variable accessible to the controller.

If this seems a good idea, I'm happy to implement it.

**Comment by gkalpak** [comment] 2015-10-01 20:59
Duplicate of #5893.
Closing since #5893 has more context/discussion.

**Closed by gkalpak** 2015-10-01 20:59 UTC
