### ISSUE TITLE
Special character filter bug.

### ISSUE THREAD

**Issue by picheli20** [angular/angular.js#10982] opened 2015-02-05 18:01 UTC
If you use the ng-repeat filter for filter a string like "@#@#@!#@#" the filter will broke.

**Comment by lgalfaso** [comment] 2015-02-05 22:10
Hi, would it be possible to get a plunker?

**Comment by pkozlowski-opensource** [comment] 2015-02-22 11:16
Closing due to the lack of reproduction scenario...

**Closed by pkozlowski-opensource** 2015-02-22 11:16 UTC
Labels: component: filters, needs: more info
