### ISSUE TITLE
Nested multiple transclude fails

### ISSUE THREAD

**Issue by harm-less** [angular/angular.js#16159] opened 2017-08-09 12:30 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I like the idea of multiple transcluding, but it seems I've run into a possible bug when transclusion happens from a parent component. The provided error is as follows:
`Required transclusion slot 'titleSlot' was not filled.`

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/BrPCuekwwbBQARcCmodo?p=preview

## Expected behavior
I expect the Plunker to work as expected because I don't understand the difference between using only the `ng-child` component with its multiple transclusion slots or "sending" the transclusion slots down to the child using another transclude. Did I miss something here?

## What is the motivation / use case for changing the behavior?
The code I'm writing would be much more DRY if this works because it allows me to combine/wrap some of my components into bigger components. 
Another solution I had is to replace the templateUrl using attributes, but that didn't work out (#11144).

## Environment

<pre><code>
Angular version: 1.6.1 (but the Plunker is using 1.6.6)

Browser:
- [x] Chrome (desktop) version Version 59.0.3071.115 (Official Build) (32-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
</code></pre>

**Comment by gkalpak** [comment] 2017-08-10 16:49
Unfortunately, this is currently not supported. See https://github.com/angular/angular.js/issues/8914#issuecomment-111457286 for some more details on what is going on under the hood.
I will close this as a duplicate of #8914, which has more context.

**Closed by gkalpak** 2017-08-10 16:49 UTC
Labels: component: $compile, frequency: low, needs: investigation, severity: broken expected use, type: bug

**Comment by harm-less** [comment] 2017-08-11 08:52
I think I understand, thanks for the clarification. The solution I'm doing right now is not a pretty and DRY, but it works nonetheless.
Does Angular 2 have this feature?

**Comment by gkalpak** [comment] 2017-08-11 12:56
Yes, this should work in Angular. Its projection (that's what transclusion is called in Angular) is quite differently implemented and more flexible.

**Comment by harm-less** [comment] 2017-08-11 13:12
Sounds good! I was indeed very surprised it wasn't working the way I expected because it sounds essential to the whole purpose of transclusion.
In a few months we're going to attempt to migrate to Angular 2 because I feel like especially large applications benefit from it. So I can't wait to be blown away by all the good things I hear about it ;)

Thanks for the information/support.
