### ISSUE TITLE
ng-animate skips animation "under pressure"

### ISSUE THREAD

**Issue by chrisguttandin** [angular/angular.js#12359] opened 2015-07-16 10:03 UTC
I created a simple fiddle to explain my problem: https://jsfiddle.net/akpr3jej/1/. It does no more than changing a dynamic class when clicked on one of the buttons. Changing this class triggers an animation. If you do that a number of times very fast, there will be no animation anymore and the colors are switched abrupt from one to the other.

I could reproduce this behavior in Chrome, Opera and Safari. But it seems to be working in Firefox.

**Comment by matsko** [comment] 2015-07-17 02:57
Alright I see what's going on here.

Once #12248 is in I will have a go at this. We should get this fixed by next week.

**Comment by chrisguttandin** [comment] 2015-07-17 09:56
Many thanks for looking into this @matsko.

**Comment by matsko** [comment] 2015-07-29 17:06
Alright so #12248 is fine, but it looks like the issue at hand is something else. I'll spend time today looking into it. My guess is that it has something do with this `$timeout` value leaking into follow-up animations: https://github.com/angular/angular.js/blob/master/src/ngAnimate/animateCss.js#L762

**Comment by matsko** [comment] 2015-08-03 18:52
Alright good sir here is a fixed build of ngAnimate. It takes care of the issue you're experiencing: http://plnkr.co/edit/P7E5CXnuMQDpH1SiJ0pj?p=preview

**Comment by matsko** [comment] 2015-08-03 18:59
Alright and we have a PR ready to be merged in: https://github.com/angular/angular.js/pull/12490

**Comment by chrisguttandin** [comment] 2015-08-04 08:52
Many many thanks for fixing this.

**Comment by matsko** [comment] 2015-08-18 04:03
The fix for this has landed in master: https://github.com/angular/angular.js/commit/d88167318d1c69f0dbd2101c05955eb450c34fd5

Once 1.4.5 is released then you can use it there or you can grab the snapshot: http://code.angularjs.org/snapshot.

**Closed by matsko** 2015-08-18 04:03 UTC
Labels: component: ngAnimate, needs: work, severity: regression, type: bug

**Comment by bmmpt** [comment] 2015-10-28 21:40
Hi matsko,

I have a similar issue to the one reported here. Before I decide to post my issue here I tried the plunker you pointed out as fixing the issue at hand: http://plnkr.co/edit/P7E5CXnuMQDpH1SiJ0pj?p=preview

It appears to me that the issue is still there when you repeatedly press the buttons randomly.

I believe my scenario is simpler and illustrates a similar problem:

http://plnkr.co/edit/YzxCThylPk4AfX0cvcfG

If you click the button to hide the label and wait for the animation to finish and then click it to show the label and wait until it finishes, all goes well. But when the animation is half way down and you click the button I would expect the label to go back up, and apparently it's happening but if you continue clicking the button, you will notice it "jumps" rather than "sliding".

Thanks in advance.
