### ISSUE TITLE
Firefox `$timeout` during `alert`

### ISSUE THREAD

**Issue by ersimont** [angular/angular.js#11452] opened 2015-03-28 17:53 UTC
In Firefox, if a `$timeout` is scheduled to occur when an `alert` or `confirm` popup is open, it will cause the `$apply already in progress` error once the user closes the popup.

It is very common to use `$timeout`, and even though it is not considered a best practice `alert` and especially `confirm` are very useful. In my case, I am using `confirm` to verify the user wants to navigate away from a page with unsaved changes (and I have found no other solution that works well when the user presses Back).

The error occurs in Firefox, but not Chrome or IE.

Use this to reproduce the issue: http://plnkr.co/edit/gPe7tQyZzC9eCCpsNcqw?p=preview

**Comment by lgalfaso** [comment] 2015-03-29 11:02
This looks like a duplicate of #10083 and a variation of an issue with Firefox https://bugzilla.mozilla.org/show_bug.cgi?id=1127236 This is a Firefox issue and there is nothing that Angular can do to prevent this :(

**Closed by lgalfaso** 2015-03-29 11:02 UTC
