### ISSUE TITLE
scope.$watch whats the point of initWatchVal?

### ISSUE THREAD

**Issue by startswithaj** [angular/angular.js#12495] opened 2015-08-04 04:58 UTC
When a scope.$watch is being wired up. The code goes 

```
$watch: function(watchExp, listener, objectEquality, prettyPrintExpression) {
     var get = $parse(watchExp);
     ...
      var scope = this,
            array = scope.$$watchers,
            watcher = {
              fn: listener,
              last: initWatchVal,
              get: get,
              exp: prettyPrintExpression || watchExp,
              eq: !!objectEquality
            };
```

Sets watcher.last too be initWatchVal which is an empty function.  

Then when the watcher gets invoked later on we have this code run

```
watch = watchers[length];
                  if (watch) {
                    if ((value = watch.get(current)) !== (last = watch.last) &&
                        !(watch.eq
                            ? equals(value, last)
                            : (typeof value === 'number' && typeof last === 'number'
                               && isNaN(value) && isNaN(last)))) {
                      dirty = true;
                      lastDirtyWatch = watch;
                      watch.last = watch.eq ? copy(value, null) : value;
                      watch.fn(value, ((last === initWatchVal) ? value : last), current);
```

So the the interesting line here is 
```
watch.fn(value, ((last === initWatchVal) ? value : last), current);
```
This is what invokes our watch function `function(newValue, oldValue, scope){}` and if watcher.last is still equal to our empty function(initWatchVal) such as on the first run of the watcher it passes the current value as the oldValue. 

This doesn't make sense to me. When the watcher is first created why isn't watcher.last set to the result of the watchExp? I.E the value of the watchExp at the time the watch is created? That is the last value of the function or property you are watching.

So instead of getting the real newValue and oldValue you just get currentValue, currentValue. In the first instance you should get newValue, (null or the true oldValue).

Why is this important?

If you have a callback like this

```
function(newValue, oldValue) {
   //do something to the dom here.
}
```
This code will execute regardless of if there has been a change or not since you wired up the watch. because ```if ((value = watch.get(current)) !== (last = watch.last)) ```... currentValue is not equal to emptyFunction.

If you do this to stop that 
```
function(newValue, oldValue) {
 if newValue != oldvalue
    //do something to the dom here
}
```
This wont fire on the first change because newValue and oldValue are the same.

**Comment by S-YOU** [comment] 2015-08-04 09:40
angular have copy of your object or array to compare deep watch or watchCollection later, so they need this imo.

**Comment by caitp** [comment] 2015-08-04 15:35
> angular have copy of your object or array to compare deep watch or watchCollection later, so they need this imo.

Only if the `objectEquality` flag is set to true, otherwise, a verson of identity equality is used, which treats `NaN` values as equal.

I recall this had actually changed at some point (to make the initial watch value always `undefined`), and was shown to be a regression which broke apps, but I may well be mistaken about that. It may have been a slightly different effect than that.

Regardless, you don't really need to perform this test in your watch function --- if the watch listener fires, you can trust that your value changed in some way. If you discover that the callback fired incorrectly, it's worth filing a bug about that. But if your listener is called, you should generally trust that the value really did change.

@lgalfaso / @gkalpak what do you think?

**Comment by startswithaj** [comment] 2015-08-05 01:55
@caitp appreciate the reply. The thing is though, if you are watching a simple value its watcher.last value is initially set to a reference to initWatchVal. So then when the first digest() is called after the watcher is wired up; it compares the currentValue -- if "Dog" !== initWatchVal then fire the watch function and provide the currentValue as the first parameter and as the second parameter (if watch.last is initWatchVal then provide currentValue "Dog") again.

**Comment by startswithaj** [comment] 2015-08-05 02:27
I've created a plunkr that demonstrates this.

http://plnkr.co/edit/9P1IxBfNytedfH1sjKbT?p=preview

Should see in the console
```
MainCtrl init
app.js:16 Wiring up watcher
app.js:18 Watcher firing
app.js:19 newValue red
app.js:20 oldValue red
```

If it's needed I'll annotate a version of 1.4.1 with logs to show whats happening in the watcher code.

**Comment by caitp** [comment] 2015-08-05 04:53
I am well aware of what the watcher code is doing.

This logic makes sure that the listener is triggered during the first digest, regardless of the value, once the value has stabilized. This is not a big, and there is no reason to test if that old value and new value are identical or not. You can always trust that the value has changed when the listener is called.

**Comment by startswithaj** [comment] 2015-08-05 05:16
But the value never changes. It's 'red' and stays red and as you correctly point out regardless of the value the first digest triggers the listener and its associated on change function. What I am illustrating is you CAN NOT always trust that the value has changed when the listener is called because the listener is called regardless of a change on the first digest. 

I'm essentially asking why is this the case? Why not parse the watchExpression when the watcher is created rather than calling the listener on the first digest? 

We don't control when the first digest happens post render so what can happen is that a change does indeed happen before the first digest and then when the first digest happens we have no previous to compare it too. Therefore in the documentation where it says ```To detect this scenario within the listener fn, you can compare the newVal and oldVal. If these two values are identical (===) then the listener was called due to initialization.```

That initialisation can happen post change and therefore by checking the equality we miss a true change.

**Comment by frfancha** [comment] 2015-08-05 10:04
This is how it works:
The watcher is always called once in the first digest after setting the watcher.
In this very first call, Angular has no way to know if the value has changed or not, as it is the first time it "computes" it, therefore there is no notion of "change" at that time, and no notion of "old" either.
Using initWatchVal internally is just an implementation detail to always force the first digest cycle to call the watcher. Using undefined instead of initWatchVal wouldn't do the job because the first observed value can be undefined and that wouldn't trigger the call.
In this first call of watcher, Angular gives you the "new" value in the "old value" parameter instead of initWatchVal because initWatchVal is just an internal implementation detail.
Fred

**Comment by gkalpak** [comment] 2015-08-05 12:19
> Regardless, you don't really need to perform this test in your watch function --- if the watch listener fires, you can trust that your value changed in some way.

@caitp, you probably mean something else, but by reading this I understanding that you claim the watch listener will never be called with `newValue === oldValue` (which is obviously incorrect).

--
@frfancha, I think @startswithaj is well aware of what is happening and why, and his question is:
_Why not intialize `watcher.last` with `watchExp(scope)` (considering it the initial value and only call the watch listener if any future evaluation of `watchExp(scope)` returns a value that is actually different than `watcher.last` ?_

@startswithaj, I don't have a good answer (since I wasn't around back when the whole watchers idea was shaping and going through all shorts of transformations, but here are a few (arbitrary) thoughts:

1. Your suggestion sounds reasonable to be (but I haven't really thought this through).

2. Making this change now would be quite of a breaking change (since a lot of apps rely on the watch listener being run at least once).

3. I wonder if the reason could be this: The implementor figured that it was a common usecase to register a watch listener and then call it once manually to perform some initial action, so instead of having people register a watch listener and call it, they decided it made more sense to call the listener upon registration as well.

<sub>
An extra subjective observation: From my experience, implementations inside the Angular code-base are the way they are for a very concrete and well-thought reason more often than not. (Notice the _more often than not_ part.)
It is a very weak argument, but if I had to take a blind guess I'd say there is a reason behind it; we just need to find it :wink: 
</sub>

**Comment by caitp** [comment] 2015-08-05 12:33
> @caitp, you probably mean something else, but by reading this I understanding that you claim the watch listener will never be called with newValue === oldValue (which is obviously incorrect).

You've misread this. I'm saying that the test `if (oldValue !== newValue) {}` is redundant, because with the exception of bugs, the watch listener is called at appropriate times.

**Comment by gkalpak** [comment] 2015-08-05 12:51
> because with the exception of bugs, the watch listener is called at appropriate times

@caitp, I don't know what you mean by _"appropriate times"_, but if you don't want the listener to be fired upon registration, then the first call (where indeed `newValue === oldValue`) will not be very appropriate :smile:
I've been in situation where the check was needed. (I even used to include it in all my listeners by default some time ago :))

---
I got curious, so `git blame` to the rescue:

Taking a look at how it wa [before `initWatchVal`][1] was introduced, it seems that _forcing $watch to fire on first run_ was a conscious choice (at that point at least).
Now let's find out why this choice was made...

--
Wow, things were pretty different [back then][2]. It seems Angular had `widgets` and forms where ruling !
The `FormController` was using the `scope`'s `$watch` to trigger all shorts of stuff, from parsing the model value to validating and setting the view value. So, it was indeed useful to have that run once upon registration.
Maybe `$watch` wasn't a general purpose watching utility meant for wide public consumption, but rather a means to two-way binding between the model and the view (in which case, running the listener at least once made sense and saved on boilerplate).

Which makes me think: Are things so diferent now ? What would happen to our forms/directives should we not run the watch listener once upon registration ?

--
Yeah, lot's of stuff would be broken (but not beyond repair).

---
OK, I think I've done as deep/back as I would like to go for now.

My final thoughts:

1. If implementing things from scratch I would definitely consider initializing `watcher.last` to the actual value.
2. Even in that case, there seem to be at least as many usecases demanding an initial call to the listeners as there are usecase needing the `newValue !== oldValue` check, so there would be trade-offs either way.
3. Considering how breaking a change it would be atm, I would rather leave things as is.

<sub>Note: I've not put my hands on any code, so there might be even more stuff breaking should we make this change.</sub>

[1]: https://github.com/angular/angular.js/commit/29f9e2665d8b771a6226870fc8fd2c4c94d7a2c0#diff-1e47cbafadbdba153d94f2abee2a8451L247
[2]: https://github.com/angular/angular.js/blob/ed36b9da3be338fe9eb36f3eeea901d6f51cd768/src/service/formFactory.js#L286-L392

**Comment by frfancha** [comment] 2015-08-05 12:51
Initializing the value by first evaluating it instead of using initWatchVal would also mean that the value would always be evaluated at registration time instead of later, "perhaps", in digest.
I say perhaps because you can remove the watcher in some cases before it has been called, in this case the first eval would be lost of time.
This has also the advantage that you can register watchers for which the observed "value" calls part of code not ready yet (functions defined later), the only necessary thing is that everything is ready when the digest begins.
In our real life applications, what you suggest as reason number 3 occurs really a lot and it is very convenient.
And "THE" scenario number one using "reason 3" is the link Angualr does between html and scope: when you display $scope.prop in html by using {{prop}}, this display action triggered at every change must be triggered to display the initial value of $scope.prop, even when $scope.prop never has never chnaged.
Fred
P.S. @gkalpak I know you know all this (much better than I ;-) ), but I write this hoping it can perhaps help people with less knowledge of internals

**Comment by caitp** [comment] 2015-08-05 13:08
> @caitp, I don't know what you mean by "appropriate times", but if you don't want the listener to be fired upon registration, then the first call (where indeed newValue === oldValue) will not be very appropriate :smile:

If you don't want it to be fired on registration, then this logic does exactly what they want it to do --- that's not what they're talking about.

**Comment by caitp** [comment] 2015-08-05 13:09
It's not rocket science folks, this is a case of fighting the framework for no reason

**Comment by startswithaj** [comment] 2015-08-06 00:32
@gkalpak your exactly on the money and I appreciate you going back through the history to try to explain it. You have understood entirely the core of my question. @caitp I'm not fighting the framework there are numerous stackoverflow questions asking why when a listener first fires the newVal and oldVal are the same. And why the listerner is firing when there is no change. Which it is. 

If you have a directive that is used per element of an ng-repeat and you wire up a scope.$watch for each of these elements. Not only during the first cycle does it create the watch but it also imo unnecessarily calls the listener which slows everything down. There are many many many github projects dedicated to providing a faster version of angular 1.x ng-repeat.

I observed this phenomenon and I wanted to understand what was causing it. Nobody is trying to fight the framework. Going forward many many people are going to be using 1.x for the foreseeable future and the more people that have these discussions and have a true understanding of these bits of legacy code the better off we are all going to be going forward. 

Things like this are very hard to explain and provide examples of. Platitudes like "it's not rocket science folks" don't really add to the discussion or further everyones understanding of the framework. "Just because it seems to work" is never a good answer.

**Comment by frfancha** [comment] 2015-08-06 07:16
Some more after the night...

In fact the digest mechanism is not designed at all to call watchers at every change (watchers are not called at every change), it is designed to call watchers at least once with the last stabilized value, even when this value has never changed, or has never been set.

Watchers not called at every change:

Suppose watcher1 set $scope.name to upper case, and watcher2 trims blanks from $scope.name.
If $scope.name is lower case with trailing blanks, one of the watcher will see the initial value, the other one will get the intermediary value (trimmed or upper), and both will see the last stabilized trimmed and upper value.
So the first change (trim or upper, depending of the order of calls in the digest) is only "seen" by one watcher.

It is even possible that a change doesn't call a watcher at all when the final stabilized value is the same as the last observed value for this watcher.
watcher1 sets $scope.name to 'Smith' (was 'Jones')
watcher2 sets $scope.name to 'Jones'
watcher3 on $scope.name won't even be called (in the cases where it is after watcher1 and watcher2 in the digest loop).
So watcher3 has never seen the change from 'Jones' to 'Smith'.

Then digest mechanism is not designed to call watchers on every change, but only at least once with the last stabilized value when this stabilized value has changed since last call or there was no last call (therefore the initWatchVal to ensure call in first digest).

Why that? Because "the" goal of this is to update html from $scope (or to update view from model if you prefer a more abstract language).
To do that, digest is exactly what we need:
-we don't care about "temporary" values, such as $scope.name already trimmed or upper but not both yet, we even prefer to not see them for performance reason (but sometimes we see them sometimes not depending of the order in digest).
-we must know the "initial" value to display it, even if no "change" has occurred.

Fred

**Comment by Narretz** [comment] 2015-08-21 09:41
@frfancha You are making a good point with this: 
> In fact the digest mechanism is not designed at all to call watchers at every change (watchers are not called at every change), it is designed to call watchers at least once with the last stabilized value, even when this value has never changed, or has never been set.

I think we can close this issue then. Or should we update the documentation to make this clearer?

**Comment by Narretz** [comment] 2015-09-22 11:32
I'm gonna close this issue. If anyone wants to update the docs, feel free to open a PR.

**Closed by Narretz** 2015-09-22 11:32 UTC
Labels: component: scopes, severity: confusing
