### ISSUE TITLE
ngModel.$setViewValue is throwing 'invalid argument' error in IE.

### ISSUE THREAD

**Issue by venkikonamma458** [angular/angular.js#16081] opened 2017-07-04 07:39 UTC
I am using angularjs version 1.3.15. I am using below code in a directive which is working fine in all the browsers except IE.

ngModel.$setViewValue("0");

above code is working fine in all the browsers. But in Internet Explorer Im getting following error.

   Error: Invalid argument.
   at interpolateFnWatchAction (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.js:8082:17)
   at interpolateFnWatcher (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.js:10243:17)
   at watchGroupAction (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.js:14084:13)
   at $digest (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.js:14412:23)
   at $apply (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.js:14675:13)
   at $$debounceViewValueCommit (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.js:23524:7)
   at $setViewValue (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.js:23496:7)
   at read (https://technovert-6c7a9fc535626e.sharepoint.com/teams/spdev/test/Timesheet/Scripts/App/app.module.js:264:33)
   at Anonymous function (https://technovert-6c7a9fc535626e.sharepoint.com/teams/spdev/test/Timesheet/Scripts/App/app.module.js:229:25)
   at dispatch (https://technovert-6c7a9fc535626e.sharepoint.com/teams/spdev/test/Timesheet/Scripts/App/jquery-1.9.1.min.js:22:28281)

**Angular version:** 1.3.15

**Browser:** [IE]

**Comment by gkalpak** [comment] 2017-07-04 07:49
Can you provide a minimal reproduction (e.g. a runnable demo using CodePen, plnkr or something similar). It is hard to investigate without a concrete reproduction.

**Comment by Narretz** [comment] 2017-07-04 09:00
Also,  1.3.x is not supported anymore. Can you please try with 1.6.4?

**Comment by Narretz** [comment] 2017-07-11 16:18
I'm going to close this issue because we haven't got any feedback. Feel free to reopen this issue if you can provide new feedback.

**Closed by Narretz** 2017-07-11 16:18 UTC
Labels: browser: IE10, browser: IE11, browser: IE9, component: forms, needs: more info, severity: broken expected use, type: bug
