### ISSUE TITLE
html5Mode(true) wrong redirect of old links.

### ISSUE THREAD

**Issue by kurtiev** [angular/angular.js#16304] opened 2017-10-29 09:22 UTC
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**
Set html5Mode to true value and make some changes to server [according to official docs](https://docs.angularjs.org/guide/$location#html5-mode), it will replace hash from url as expected and will do redirect to new urls, but if in you request was query parameters, they just will be lost.
I'm using $stateProvider to describe state:
`$stateProvider
            .state('home', {
                url: '/?param_1',
                template: '<home></home>'
            });`

ex. localhost:3000/#!/route_1?params_1=1 ==>> localhost:3000/route_1.

I can't show it on plunker, it doesn't show url of browser.

**Comment by gkalpak** [comment] 2017-10-29 13:28
I dodn't see anything in the code that would strip away the query part. And I can see it working [here][1].

I am going to close this, since everythng works as expected (afaict), but feel free to continue the discussion below (in case I missed anything). Also, happy to reopen an investigate if you can provide a minimal reproduction (e.g. in CodePen, Plnkr, etc - and yes, you can find out the browser URL in plnkrs, even if it is not shown by default :grin:).

[1]: https://codepen.io/ExpertSystem/pen/WXNmLQ?editors=1000

**Closed by gkalpak** 2017-10-29 13:28 UTC
