### ISSUE TITLE
Why a function forEachSorted use Object.keys?

### ISSUE THREAD

**Issue by rafaeldev** [angular/angular.js#14075] opened 2016-02-18 03:39 UTC
I was trying to pass an object by using the tool parameter setting _**$http**_:
`{ Method: "GET", url: "company/create" params: { name: "Rafael", age: 23} }`

It turns out that given time the object passed in the params attribute is an object created from the _**Object.create()**_ function. As we know, this function returns an object, which if you have values, will be added to the prototype of it.

I saw that every time I made the request through an object that had values ​​in the prototype, the keys/values ​​were ignored.

Studying a little more code, I saw that the object passed in params is handled by the function _**$HttpParamSerializerProvider**_, which in turn uses the _**forEachSorted**_ function.

Within the _**forEachSorted**_ function is used to _**Object.keys().sort()**_. Viewing the documentation by [MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/keys) saw that _**Object.keys**_ function does not return the keys at the prototype level, thus ignoring other attributes of the object.

Well, after all this is the question. Why use _**Object.keys**_? Why not make a for ... in ...?

Thank you!

P.S.: Google Translate

**Comment by gkalpak** [comment] 2016-02-19 18:44
@rafaeldev, it's just an implementation decision (to not consider own properties of the object).
I prsonally like it, because it's more reliable (e.g. imagine someone messing up the object prototype and breaking your `$http` requests).

And I don't think there is a point atm to even discuss about changing it, because it would be too much of a BC.

--
Is there a specific reason for using `Object.create()` ?

**Comment by lgalfaso** [comment] 2016-03-03 18:21
Hi,
  I think there is a consent that, when the user specifies `params: {name: 'foo'}`, if the request also sends `toString` and other fields, that this would be a bug. On top, Angular cannot keep up with every property that every browser adds to the object prototype (and they do add a few). With these two constraints, then there is no other simple way that to only use the properties from `params` that do not belong to the prototype.

With this in mind, I lean towards thinking that this is not a bug and the current behavior is the one expected. Will leave this open in case other people want to comment.

**Comment by lgalfaso** [comment] 2016-03-28 19:47
With the information above and no other feedback, closing this as works as expected.

**Closed by lgalfaso** 2016-03-28 19:47 UTC
Labels: component: $http, frequency: low, severity: inconvenient, type: bug

**Comment by rafaeldev** [comment] 2016-03-28 21:22
Hi everybody!
Sorry for late response. However thanks for helps.

I understood your observations.
Answering the question of @gkalpak, I see which I don't need use a `Object.create()`. I fix my "problem" removing attributes in prototype level.
