### ISSUE TITLE
ngAnimate and Bootstrap. Select input does not bind correctly when using class "form-control"

### ISSUE THREAD

**Issue by bolducpat** [angular/angular.js#14644] opened 2016-05-20 19:45 UTC
This bug can be reproduce with chrome on mobile device.
When I try to select an option value in <select> input, it does not work the first time. Also, the control is flickering on first open.

https://jsfiddle.net/vj28awk7/

In this jsfiddle, on first section, try to select a value in each select control and you will see that it is not working on first time.

But like you can see, on second section, it is always working.

The only difference between these two section is the "class='form-control'" on the <select> input.

This bug occured on AngularJs 1.5.5
Android device with Chrome v50.0.2661.89

**Comment by bolducpat** [comment] 2016-05-20 19:58
In jsfiddle, if you remove the "ngAnimate" module, this bug disappeared

**Comment by gkalpak** [comment] 2016-05-21 07:59
I can't reproduce it on Android 5.0.2/Chrome v50.0.2661.89. What android version are you trying it on ?
If it appears on specific devices/browsers only, it sounds more like non-Angular bug.

**Comment by bolducpat** [comment] 2016-05-21 11:20
I reproduce it on 2 differentes device. One on Android 6.0 and the other on Android 5.1.1

This is a screen recording that I have done to show you the behavior. in this video, I click on each drop-down, and select a value.

https://drive.google.com/file/d/0B_NwJiTIdBPtaFdFZFAyekpwb0U/view?usp=drivesdk

**Comment by gkalpak** [comment] 2016-05-24 19:36
I can see it now. Interestingly it does not happen the very first time I click on a select. From the second time onwards, it does happen.

**Comment by gkalpak** [comment] 2016-05-24 19:58
BTW, it only happens when `ngAnimate` is present and seems to be related with the fact that `form-control` has a transition property.

**Comment by bolducpat** [comment] 2016-05-24 20:29
After some investigation, I have found this post about an issue with Chrome itself. 
Maybe its a bug with chrome and not about angular. But it seem critical for me. A lot of site may have an issue with this.

https://productforums.google.com/forum/#!topic/chrome/-JLlY3eKQ-E;context-place=topicsearchin/chrome/category$3Aandroid%7Csort:relevance%7Cspell:false

**Comment by gkalpak** [comment] 2016-05-25 12:09
It seems to be a Chrome bug indeed (here is the [bug report] for future reference).
I don't think it makes sense to try to incorporate a temporary work-around into the core (until Chrome is fixed).

In the meantime, users can work around the issue, by overwriting/removing the `transition` style on `<select>` elements (e.g. the style added via Bootstrap's `form-control` class). E.g.:

```css
select.form-control {
  transition: none;
}
```

I will close this, but feel free to continue the discussion below.

[1]: https://bugs.chromium.org/p/chromium/issues/detail?id=613885

**Closed by gkalpak** 2016-05-25 12:09 UTC
Labels: browser: chrome, component: forms, component: ngAnimate, frequency: low, needs: investigation, severity: broken expected use, type: bug

**Comment by bolducpat** [comment] 2016-05-25 12:43
Thank you for your help. You are awesome !
