### ISSUE TITLE
Can't share a data-ng-model between <input type="number" /> and <input type="range" />

### ISSUE THREAD

**Issue by zippy1981** [angular/angular.js#8241] opened 2014-07-17 17:20 UTC
I demonstrate the issue in a [plunkr here](http://plnkr.co/edit/74j8DhCPUJwNZ1ckg1rg?p=preview) . [This stackoverflow answer](http://stackoverflow.com/a/24808152/95195) describes the issue in detail.

Simply put, at least in chrome ```<input type="number" />.value``` is a number. and ```<input type="range" />```.value is a string, so that's what is breaking the data-ng-model binding. That could be fixed with some casting with the ngModel directive (and possibly the ngBind directive).

On another note, the w3c spec for [number input](http://www.w3.org/TR/html-markup/input.number.html#input.number.attrs.value) and [range input](www.w3.org/TR/html-markup/input.range.html#input.range.attrs.value) both say the value should be a string representation of a number. Is this worth filing a bug with chrome over?

**Comment by Narretz** [comment] 2016-07-05 19:42
We are working on this (finally). Closing as a duplicate of #5892

**Closed by Narretz** 2016-07-05 19:42 UTC
Labels: component: forms, frequency: low, severity: inconvenient, type: feature
