### ISSUE TITLE
$cookies missing after Ajax request

### ISSUE THREAD

**Issue by rogier21** [angular/angular.js#10861] opened 2015-01-25 18:07 UTC
It's hard to make a plunkr example, but it's easy to reproduce.

As I have a SPA I do authentication serverside through $http (webAPI). I create a $http method which calls a login functions on my backend server, this will set a cookie to authenticate.

After $http is complete I check my cookies:

    public get isAuthenticated(): boolean
    {
        var cookie1: string = $cookie['.ASPXAUTH'];
        var cookie2: string = $cookie['.ASPXAUTH_USERID'];

        console.log(cookie1, cookie2);
        console.log(document.cookie);

        if (cookie1 && cookie2)
        {
            return true;
        }
        return false;
    }

Odd part is that the variables `cookie1` and `cookie2` are empty, but `document.cookie` contains the newly set cookies.

After a page refresh all is fine, it seems that $cookie doesn't recognize cookies after they have been set by an ajax call.

**Comment by shahata** [comment] 2015-01-25 19:15
Hi @rogier21, this is a duplicate of #7631 and will be resolved in Angular 1.4. In the mean time you can set a timeout of at least 100ms and check the cookies again in order to see the updated cookies after the http response.

**Closed by shahata** 2015-01-25 19:15 UTC

**Comment by rogier21** [comment] 2015-01-25 19:19
@shahata Sorry I searched but didn't see this issue! I did see the 1.4 changes but wasn't sure this was considered! Thanks for the swift response.
