### ISSUE TITLE
component $onChanges behavior change in 1.5.5

### ISSUE THREAD

**Issue by dazza999** [angular/angular.js#14475] opened 2016-04-20 14:53 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
$onChanges in a component is immediately triggered 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
http://jsbin.com/yuyabutalu/edit?html,js,output
Change to 1.5.3 to see different behavior

**What is the expected behavior?**
$onChanges should not be triggered until there is a change

**What is the motivation / use case for changing the behavior?**
Breaking change introduced

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
1.5.5, working as expected in 1.5.3

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by gkalpak** [comment] 2016-04-20 20:28
This is (sort of) a duplicate of #14433. 

The current (1.5.5) behavior is the correct one - the fact that it wasn't called before was actually a bug (see https://github.com/angular/angular.js/issues/14433#issuecomment-210194853 for a little more context). This is not a breaking change imo, because it wasn't documented to work in any particular order and in fact it was never intended to.

I'm going to close this, since it works as intended, but feel free to continue the discussion below.
(BTW, it might be a good idea to add a note in the docs about the expected behavior - PRs welcome :smile:)

**Closed by gkalpak** 2016-04-20 20:28 UTC
