### ISSUE TITLE
Digest Errors, Possible Fix?

### ISSUE THREAD

**Issue by wizeone** [angular/angular.js#15768] opened 2017-03-01 22:00 UTC
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
Feature or Bug? Not sure which to label it.

**What is the current behavior?**
Occasional Digest error "Apply already in progress"

I've been fixing a few of these using $timeout. I love patchy solutions as much as the next guy but I decided to take a deeper look and see if I could fix the problem at its core.

Taking a look into the Angular.js we can see this snippet

forEach(
  'click dblclick mousedown mouseup mouseover mouseout mousemove mouseenter mouseleave keydown keyup keypress submit focus blur copy cut paste'.split(' '),
  function(eventName) {
    var directiveName = directiveNormalize('ng-' + eventName);
    ngEventDirectives[directiveName] = ['$parse', '$rootScope', function($parse, $rootScope) {
      return {
        restrict: 'A',
        compile: function($element, attr) {
          // We expose the powerful $event object on the scope that provides access to the Window,
          // etc. that isn't protected by the fast paths in $parse.  We explicitly request better
          // checks at the cost of speed since event handler expressions are not executed as
          // frequently as regular change detection.
          var fn = $parse(attr[directiveName], /* interceptorFn */ null, /* expensiveChecks */ true);
          return function ngEventHandler(scope, element) {
            element.on(eventName, function(event) {
              var callback = function() {
                fn(scope, {$event:event});
              };
              if (forceAsyncEvents[eventName] && $rootScope.$$phase) {
                scope.$evalAsync(callback);
              } else {
                scope.$apply(callback);
              }
            });
          };
        }
      };
    }];
  }
);

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

**What is the expected behavior?**
What I expect is no digest errors to occur. My suggestion takes the logic from 'Safe' apply that is discussed here

https://coderwall.com/p/ngisma/safe-apply-in-angular-js

**What is the motivation / use case for changing the behavior?**
Reduce or remove digest errors.

**Which versions of AngularJS, and which browser / OS are affected by this issue? Did this work in previous versions of AngularJS? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
AngularJS v1.4.14

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
My suggested fix (though it might be better practice to toss the suggested code into a function like scope.SafeApply or something.

The code I linked above is what is present already in Angular. The code below contains by changes with comments next to the lines changed to make it stand out.

I'm not sure what problems this may cause and the point of this is to check with the experts on what ramifications may occur due to a change such as this.

forEach(
  'click dblclick mousedown mouseup mouseover mouseout mousemove mouseenter mouseleave keydown keyup keypress submit focus blur copy cut paste'.split(' '),
  function(eventName) {
    var directiveName = directiveNormalize('ng-' + eventName);
    ngEventDirectives[directiveName] = ['$parse', '$rootScope', function($parse, $rootScope) {
      return {
        restrict: 'A',
        compile: function($element, attr) {
          // We expose the powerful $event object on the scope that provides access to the Window,
          // etc. that isn't protected by the fast paths in $parse.  We explicitly request better
          // checks at the cost of speed since event handler expressions are not executed as
          // frequently as regular change detection.
          var fn = $parse(attr[directiveName], /* interceptorFn */ null, /* expensiveChecks */ true);
          return function ngEventHandler(scope, element) {
            element.on(eventName, function(event) {
              var callback = function() {
                fn(scope, {$event:event});
              };
              if (forceAsyncEvents[eventName] && $rootScope.$$phase) {
                scope.$evalAsync(callback);
              } else {
                 //What was here before ->  scope.$apply(callback);
                //Below is suggested change
                  var phase = scope.$root.$$phase;                                           //changed
                  if (phase == '$apply' || phase == '$digest') {                          //changed
                      if (callback && (typeof (callback) === 'function')) {           //changed
                          callback();                                                                        //changed
                      }                                                                                           //changed
                  } else {                                                                                     //changed
                      scope.$apply(callback);                                                       //changed
                  }                                                                                              //changed
              }
            });
          };
        }
      };
    }];
  }
);

**Comment by gkalpak** [comment] 2017-03-02 06:42
The current implementatiin does already check `$rootScope.$$phase` and follows the `$evalAsync()` path. Your code will not work (or rather it will make no difference), because the `$scope.$root.$$phase` will always be falsy (if we reach that code-branch).

You need to identify the real cause of the error.

##
Closing, since this is not actionable atm, but feel free to continue the discussion below. Also, happy to reopen and investigate if you can provide a reliable reproduction of the problem (e.g. using CodePen, Plnkr etc).

**Closed by gkalpak** 2017-03-02 06:42 UTC

**Comment by wizeone** [comment] 2017-03-03 18:54
By providing the check I suggested that fixed our digest error. So I'm unsure how "it makes no difference". This check is in the angular v1.4.14? Could you please point me to where is check is being made, I'm unable to find it outside of the timeout function? We've seen many digest errors and most have been patched with $timeouts which i believe is adding to our problem in the end.

Thanks

**Comment by gkalpak** [comment] 2017-03-04 08:19
In the code snippet that you have posted above, there is a check for `$rootScope.$$phase`. `$rootScope.$$phase` is identical to `$scope.$root.$$phase`, so your extra check is redundant.

I doubt your change has fixed the errors you where seeing, but I'll be gladly proven wrong (with a live reproduction :wink:).

**Comment by wizeone** [comment] 2017-03-08 17:08
After further investigation I finally see what you were saying. The $rootScope.$$phase is working as intended in this instance and returning true (or that a phase exist). What is failing is the forceAsyncEvents[eventName]. It's returning as undefined due to what is direction above this forEach call

// For events that might fire synchronously during DOM manipulation
// we need to execute their event handlers asynchronously using $evalAsync,
// so that they are not executed in an inconsistent state.
var forceAsyncEvents = {
  'blur': true,
  'focus': true
};

it seems only 'blur' and 'focus' return true for this check. The problem happening is we are in the event 'mouseleave' thus returning undefined which in turn is failing the if statement even though our scope is in an apply phase, which in the end is calling 'scope.$apply(callback);'. I'm curious to why this forceAsyncEvent check even exist? The comment above mentioning "For events that might fire synchronously during DOM manipulation" the 'might' confuses me. Does this mean other events might as well such as 'mouseleave' in our case? Would it be better just to remove this forceAsyncEvents check and simply check if a $$phase is already in progress or add "'mouseleave' : true" to forceAsyncEvents? What would be the ramifications of this?

Thanks

**Comment by wizeone** [comment] 2017-03-08 19:41
To add a small note to my previous comment. I'm currently working on other problems we're having with 'Apply already in progress' errors we are getting. All that cannot be 'solved' with a $timeout are also being caused by this 'mouseleave' event.

**Comment by gkalpak** [comment] 2017-03-12 12:11
This discussion won't lead anywhere useful without a reproduction. If you have multiple "things" in your app that may try to `$digest` at the same time, you will see the error. It could be that `ng-mouseleave` is not suitable for your usecase.
