### ISSUE TITLE
Ability to enhance how watch checks for equality for my own classes

### ISSUE THREAD

**Issue by lee-elenbaas** [angular/angular.js#5929] opened 2014-01-22 09:20 UTC
If i have a complex class MyClass that has many properties, i can usually provide better implementation for testing equality for that class then the default angular.equals.

Ffor my own watch i can optimize them by making sure i only perform watch on the specific state properties. but if my code uses some library, i can not customize the way that library perform its watch on my objects

The simplest example is an `ng-repeat` on an array of such objects

So i am looking for a way that i can enhance the equals mechanism used inside angular to fit better the specific SPA.

One possible option i presented in this pull request https://github.com/angular/angular.js/pull/5913

**Comment by gkalpak** [comment] 2016-05-31 10:40
This has been discussed in several issues. Closing as duplicate of #10069 (which has an associated PR). Let's move the discussion there.

**Closed by gkalpak** 2016-05-31 10:40 UTC
Labels: PRs plz!, type: feature
