### ISSUE TITLE
email input validation - protractor raises undefined error when controller is IFFI

### ISSUE THREAD

**Issue by tsaltd** [angular/angular.js#14620] opened 2016-05-16 20:16 UTC
**Do you want to request a *feature* or report a *bug*?**

bug ?

**What is the current behavior?**

email input - protractor raises undefined error when controller is IFFI

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

- modify plunker code to make controller IFFI and run using IE11

**What is the expected behavior?**

Chrome and Firefox execute without raising the error -- loads without error & performs validation correctly

**What is the motivation / use case for changing the behavior?**

public facing site ... can't have errors

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

"angular": "1.4.6 IE 11

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

some way to catch the error and proceed ?? ( the solution does run correctly after the page is loaded)

**Comment by gkalpak** [comment] 2016-05-17 08:09
We need more info in order to be able to investigate it. If it only happens with protractor (se you can't provide a live reproduction), please provide a minimal sample code that reproduces the error.

It should also try it out with the latest version on your branch (i.e. 1.4.10 atm) to check whether it has been fixed already.

**Comment by tsaltd** [comment] 2016-05-17 20:14
sure ... but now I'm wondering ... After I posted this I ran across a comment (Pluralsight course) that it is no longer necessary to use IFFE pattern in JS code .. That may be the fix for my issue ... 

Controllers only ?

Advise please / documentation on issue ???

thx,

/sm

**Comment by gkalpak** [comment] 2016-05-17 20:59
You probably mean IIFE (not IFFE). AFAIK, the IIFE pattern can still be useful - it's not strictly necessary, it never was - it is just a pattern (among many). Maybe the comment was in the context of newer JS versions (e.g. ES6, ES7).

In any case, IIFE is used by hundreads of JS applications (Angular and non-Angular) and it shouldn't be causing any issue. It is probably some bug/misuse in your project that is causing the error, but we can't investigate further without a reproduction.

**Comment by Narretz** [comment] 2016-06-02 13:05
I'm going to close this issue because we have no reproduction of the issue. Feel free to reopen this issue if you can provide a reproduction (ideally a runnable demo in a https://plnkr.co or similar).

**Closed by Narretz** 2016-06-02 13:05 UTC
Labels: component: forms, frequency: low, needs: more info, severity: broken expected use, type: bug
