### ISSUE TITLE
$onInit is fired a little bit too early (regarding $attrs interpolation)

### ISSUE THREAD

**Issue by NicBright** [angular/angular.js#14872] opened 2016-07-06 06:12 UTC
This is a **feature** request.

**Currently**, $onInit is fired before the attrInterpolateDirective's pre link function is able to resolve attribute interpolation. Thefore one cannot access interpolated attribute values within $onInit.

**What is the expected behavior?**
I would have expected to be able to access interpolated attributes values (via $attrs object) within $onInit.

**What is the motivation / use case for changing the behavior?**
I think that the attrInterpolateDirective using a pre-link function for resolving interpolation is outdated, considering that $onInit has effectively replaced pre-link functions for components. **Why?** This is indicated because the attrInterpolateDirective explicitly uses a priority of 100, making it clear that (prior to introducing components) one could expect attribute interpolation to be finished when your own code (within any of the two link function types (pre/post)) is executed (with a standard priority of 0).

**Suggestions**
I see two distinct possibilities to achieve the expected behavior.

1. Making attrInterpolateDirective use a controller instead of a pre-link function (doing what it needs to do during controller instantiation) ... of course one would need to additionally change the internal behaviour so that only ONE attrInterpolateDirective is added which takes care of interpolating ALL attributes of the element.
2. Merge the $onInit with the preLinkFns somehow:
![image](https://cloud.githubusercontent.com/assets/1225659/16608968/66792aa2-4350-11e6-9127-f6ea20b08f36.png)

**Comment by Narretz** [comment] 2016-07-06 07:34
If you need the interpolated values why don't you use $postLink. OnInit is intended for the bindings.

**Comment by gkalpak** [comment] 2016-07-06 07:45
This is expected behavior.

Attribute value interpolation is a DOM-related operation and as such it is not guaranteed to have finished during the controller instantiation phase. If you need the values you can either use a binding (e.g. `bindings: {foo: '@'}`) or use the `$postLink` hook (when all DOM-related operations will have finished) or register an observer for when the value changes (e.g. `$attrs.$observe('foo', ...)`).

Regarding your suggestions:

- Using controllers for `attrInterpolateDirective` would impose a big overhead (considering how commonly they are used) and having one `attrInterpolateDirective` per element would introduce unnecessary complexity.
  (Not to mention this would be a breaking change.)

- Merging `$onInit` and `pre-link` doesn't make sense, because each has a different purpose (again, not to mention the breaking change). As @Narretz said, `$onInit` is only about other controllers and bindings being initialized - nothing to do with DOM attributes.

--
I am going to close this as _"works as expected"_, because the current behavior is the intended one and there is no way to support your usecase without breaking several others.
(As mentioned above, there are other (more appropriate) ways to achieve what you want.)

**Closed by gkalpak** 2016-07-06 07:45 UTC
Labels: resolution: works as expected

**Comment by NicBright** [comment] 2016-07-07 06:06
Ok fair enough. Thanks for your answers. Your suggestions all work in some way. But there is still a specialty that is not covered:

Right now it's not possible to create a general purpose component as a wrapper (at a top level of the DOM), **accepting an arbitrary number of attributes (possibly containing interpolation)**, for exposing its controller to child directives that need to do things differently depending on how the general purpose component is configured (think of an advanced <ng-model-options>, <disable-everything-inside> or <checking-permissions-blocking-some-stuff> element wrapper). While I could resolve the arbitrary number of attributes in a $postLink function, this is too late for the child directives, whose $onInit and $postLink functions have already run. The same is true when using $attrs.$observe() (which has the other caveat that the $observer is not fired if there is no attribute, this btw contradicts the docs which states that the $observer is **always** fired).

My use-case is only possible **with a fixed amount of attributes** that are specified in the bindings-object of my general purpose component, like @gkalpak suggested. I can live with that. But I just wanted to make it clear what's possible and what's not.

**Comment by gkalpak** [comment] 2016-07-07 10:08
> But I just wanted to make it clear what's possible and what's not.

Angular is pretty flexible - you might be amazed with the things that _are_ possible (although admittedly not always obvious or trivial) :stuck_out_tongue:
Your usecase sounds like an anti-pattern to me (or maybe it is because I don't fully understand it), but it should be possible afaict. Two possible solutions would be:

1. Since this wrapper component won't have a template of it's own and no actual logic (except for exposing attribute values), you can make it non-isolated and manually interpolate attribute values in the controller. (In fact, you could even make it isolate if you are worried about accidentaly poluting the parent scope and use `$scope.$parent` for interpolation.)

2. If compilation timing wrt to parent components isn't important (it generally isn't, it shouldn't be and it can't be if you use `templateUrl` anyway), you can make the wrapper component `terminal` and manually compile its contents in the `$postLink` hook (where the attributes will have been interpolated already).

[POC][1]

[1]: https://codepen.io/ExpertSystem/pen/GqvvRj?editors=0010
