### ISSUE TITLE
ng-if on ng-view

### ISSUE THREAD

**Issue by tomismore** [angular/angular.js#14002] opened 2016-02-11 00:10 UTC
Not super concerning, as it seems to be VERY specific, but it seems that if you put an ng-if directive on an element CONTAINING your ng-view, in Angular 1.5 this now prevents ngRoute from properly routing the ng-view to your first template/controller.

My code: 
```
<section class="main-area {{pageClass}}" ng-if="session" ng-class="{scheduleShowing: scheduleShowing, headerShowing: showPatientHeader}">
            <div ng-if="session && scheduleLoaded" ng-view></div>
</section>
```

What fixed it:

```
<section class="main-area {{pageClass}}" ng-hide="!session" ng-class="{scheduleShowing: scheduleShowing, headerShowing: showPatientHeader}">
            <div ng-if="session && scheduleLoaded" ng-view></div>
</section>
```

**Comment by gkalpak** [comment] 2016-02-11 07:30
This is possibly related to the new lazy transclusion optimization.

**Comment by gkalpak** [comment] 2016-02-11 07:33
I had a similar problem once (not with lazy transclusion, but same effect) and I ended up doing a `$route.reload()` upon the initial loading of the app (which is way less than ideal :disappointed:).

**Comment by Narretz** [comment] 2016-02-11 14:55
I've tried to reproduce from the description, but it seems to work: http://plnkr.co/edit/NbRSdRaKEq6ohU6q3WgA?p=preview

**Comment by tomismore** [comment] 2016-02-11 17:15
Sure does. Wish I could pinpoint the issue--but it was an easy fix. Thanks for looking into it

**Comment by Narretz** [comment] 2016-02-11 17:24
You can still try to repro it, otherwise I'd say we close this issue.

**Closed** 2016-02-16 11:10 UTC
Labels: component: $compile, component: ngRoute, frequency: low, needs: investigation, severity: broken expected use, type: bug

**Comment by maksimr** [comment] 2016-06-14 15:12
+1 We have same problem now, when trying migrate from 1.4 to 1.5

**Comment by gkalpak** [comment] 2016-06-15 10:05
This is probably due to `$route` being instantiated too late. You could try instantiating it "manually" in a `run` block:

```js
.run([$route, angular.noop])
```

--
There was a fix for this, but it got reverted because it broke some cases (especially in tests).
We are going to re-introduce it along with a way to disable it (e.g. in tests).

**Comment by maksimr** [comment] 2016-06-15 11:28
@gkalpak  thanks, This 'hack' works

**Comment by gkalpak** [comment] 2016-06-15 12:08
BTW, there is more context in #1213 (and issues mentioned in there).
