### ISSUE TITLE
element.controller not working

### ISSUE THREAD

**Issue by samu** [angular/angular.js#11073] opened 2015-02-16 14:06 UTC
We have the following test code:

```
$scope = $rootScope.$new()
element = angular.element("<div directive-under-test=''/>")
$compile(element)($scope)
controller = element.controller("directiveUnderTest")
```

As you can see, we want to access the directive's controller through `element.controller`. This works fine with angular `v1.3.0-beta.11`. However, when using `v1.3.13`, the result of that call is an empty object. Calling the method with an invalid directive name returns `undefined`. We use jQuery `1.11.1` too.

**Comment by Narretz** [comment] 2015-02-16 15:42
You'll have to provide a runnable example, I can't reproduce this in a simple example: http://plnkr.co/edit/sNm91HuYA8HrCjGWbeW6

**Comment by Narretz** [comment] 2015-02-19 22:23
Closing until more info is provided.

**Closed by Narretz** 2015-02-19 22:23 UTC
Labels: component: $compile, needs: more info

**Comment by samu** [comment] 2015-02-20 08:59
@Narretz we are using a couple of frameworks (jasmine, sinon). I tried to reproduce the problem in a test setup, without sucess. We are also using a test runner used in rails development called teaspoon, it's possible that this is causing the problem. Thanks for your efforts anyways.

**Comment by jinkai** [comment] 2015-02-23 16:35
I've been able to reproduce this. We're also using AngularJS 1.3.13. If you update your plnkr's app.js to be:
```javascript
var app = angular.module('plunker', []);

app.controller('MainCtrl', function($scope, $compile) {
  $scope.name = 'World';

  var element = angular.element('<directive-under-test="" name="name"/>')
  $compile(element)($scope)
  var controller = element.controller("directiveUnderTest")
  
  console.log(controller);
})
.controller('ControllerTwo', function() {
  
})

.directive('directiveUnderTest', function() {
  return {
    scope: {
      name: '='
    },
    replace: true,
    controller: 'ControllerTwo',
    controllerAs: 'ctrlTwo',
    bindToController: true
  }
});
```

then you'll get `undefined` for the controller. I apologize for the paste here, I haven't used plnkr yet, and wanted to get this comment out here right away.

I have a module with 5 or so directives, all like what I've listed above, and I'm trying to unit test by compiling the directive and verify my controller has the correct bound properties / expressions.

**Comment by gkalpak** [comment] 2015-02-23 19:01
@jinkai, this is because you are using invalid markup: `'<directive-under-test="" ... />'`
If you change it to `'<directive-under-test ... />'` it works as expected.

<sub>That said, this is a support question and as such ill-suited for GitHub (which is reserved for bug-reports/feature-requests).
In the future, please, forward such questions to one of the [appropriate support channels][1].</sub>

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem

**Comment by jinkai** [comment] 2015-02-23 19:13
@gkalpak Thanks! That change does indeed fix the plnkr, but in my unit tests, I'm still getting undefined, after verifying I had the correct syntax. This must be an issue with my test setup then, and I'll continue trying to get it working there.

Sorry to raise a false alarm.

**Comment by moanrose** [comment] 2016-08-24 10:04
I also get undefined when calling element.controller()

But the issue appear only to occur when the directive template is externalized using templateUrl, id i use an inline template i get a reference to the controller instance just fine

**Comment by svkoti** [comment] 2018-06-04 13:30
Even with angular 1.6.1 version I was facing this issue whether I use template or templateUrl?
    beforeEach(inject(function($compile, $rootScope) {
        var el = angular.element('<test-directive></test-directive>');
        $compile(el)($rootScope.$new());
        $rootScope.$digest();
        controller = el.controller("testDirective");
        scope = el.isolateScope() || el.scope();
    }));

**Comment by petebacondarwin** [comment] 2018-06-04 13:56
@svkoti : `angular.element('');` why would you expect this empty element to contain your controller?

**Comment by DanielTetration** [comment] 2019-03-28 22:00
@jinkai Its not really clear if you are restricting this to a type of directive. It looks like you are using your directive as an attribute. If that is the case you should use the `restrict: 'A'` property on the directive api.
