### ISSUE TITLE
ngRepeat trackBy using a date truncates the date to the second

### ISSUE THREAD

**Issue by harbulot** [angular/angular.js#16691] opened 2018-09-12 12:50 UTC
**I'm submitting a ...**

- [X] bug report

**Current behavior:**

Using a `Date` field with `track by` in `ngRepeat` causes a `ngRepeat:dupes` error when two of this dates are the same when truncated to the second, even though they are different, with different milliseconds.

**Expected / new behavior:**

`Date` has a millisecond precision, two instances that vary only in their milliseconds should be treated as being different.

**Minimal reproduction of the problem with instructions:**

```html
<div ng-app="myApp" ng-controller="testController as $ctrl">
  <table>
      <tr ng-repeat="item in $ctrl.entries track by item.dt"><td>{{item.name}}</td><td>{{item.dt}}</td></tr>
  </table>
</div>
```

```javascript
var app = angular.module('myApp', []);

app.controller('testController', ['$scope', function($scope) {
  var $ctrl = this;
  $ctrl.entries = [
    { name: "A", dt: new Date(1536752173123) },
    { name: "B", dt: new Date(1536752173456) }
  ];
}]);
```

Only the milliseconds differ in the two dates above (`.123` for "A" and `.456` for "B"), but this generates an `ngRepeat:dupes` error.

The following values would work fine:

```javascript
  $ctrl.entries = [
    { name: "A", dt: new Date(1536752173123) },
    { name: "B", dt: new Date(1536752172456) }
  ];
```

**AngularJS version:** 1.7.2

**Browser:** [Chrome 68.0.3440.106  | Firefox 62.0]

**Anything else:**

**Comment by minijus** [comment] 2018-09-12 15:42
The issue is that [simple Object](https://github.com/angular/angular.js/blob/937fb891fa4fcf79e9fa02f8e0d517593e781077/src/Angular.js#L2026) is being used as a Map. Using Date as a key for an Object coerses it to a String, where:
```js
(new Date(1536752173123)).toString(); // Wed Sep 12 2018 13:36:13 GMT+0200 (Central European Summer Time)
(new Date(1536752172456)).toString(); // Wed Sep 12 2018 13:36:13 GMT+0200 (Central European Summer Time)
```

and then keys actually are duplicated.

Easiest solution would be to create an additional property as an identifier using `getTime`: 
```js
const entries = [
  { date: new Date(1536752173123) },
  { date: new Date(1536752173456) }
];

this.$onInit = function () {
  this.entries = entries.map(entry => {
    return {...entry, id: entry.date.getTime()}
  });
}
```

**Comment by gkalpak** [comment] 2018-09-12 19:35
We could probably do better here, e.g. using `.valueOf()` if available, but given that (a) it would be a breaking change, (b) AngularJS is in [LTS mode][1], and (c) there are workarounds available, I'm afraid this is a _won't fix_.

BTW, another way is to have a more appropriate expression in the template:

```html
ng-repeat="item in $ctrl.entries track by item.dt.getTime()"
```

[1]: https://docs.angularjs.org/misc/version-support-status

**Closed by gkalpak** 2018-09-12 19:35 UTC
