### ISSUE TITLE
ng-repeat doesn't work with generator functions

### ISSUE THREAD

**Issue by thany** [angular/angular.js#15202] opened 2016-09-30 16:05 UTC
**Do you want to request a *feature* or report a *bug*?**
A *bug*. Or possibly a *feature*. It's somewhere in between, I feel.

**What is the current behavior?**
The ng-repeat results in 0 elements repeated.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Sure! There we are: http://plnkr.co/edit/B5OFOemjOUtraeZJ6puB

You won't see it outputting 5 random numbers, but that's what I'd expect it to do. Also have a look at the console, it's outputting 5 random values, which is iterated over the same generator function, proving that the generator function itself works as expected.

**What is the expected behavior?**
Generator functions return a iterable object that iterates like any other iterable object, including arrays if I recall. So I'd expect it to behave the same, if not just similar, as `ng-repeat`-ing over an array.

**What is the motivation / use case for changing the behavior?**
It's a modern javascript construct. Part of the standard. It just makes sense to me, to support it. It allows to iterate over arbitrary data from some data model, ithout having to copy it over to an array. Perfect to supply loads of data without making a memory-hogging copy. Also great for loads of other stuff I probably can't think of right now :)

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
Angular 1.5.8, Firefox 49, Windows 10.
It's important to pick a fairly modern browser, because generator functions are a new thing in ES6. I don't think (not tested) it matter if you use Chrome or Edge, but MSIE certainly won't do. Tested on the current snapshot as well - no juice.

**Comment by gkalpak** [comment] 2016-09-30 16:48
Adding support for all kinds of iterables has been discussed before and is something we would love to add to `ngRepeat` (or actually to `$watchCollection()` in general). Unfortunately, due to how `ngRepeat`/`$watchCollection()` work internally (which involves more than a `for` loop), it is not as straight-forward as it might sound at first.

I plan to get to it at some point, but if anyone bits me to it, I won't complain :wink:

--
Closing as duplicate of #14600.

**Closed by gkalpak** 2016-09-30 16:48 UTC

**Comment by thany** [comment] 2016-10-01 00:23
It's not supporting "all kinds of iterables". It's supporting generic iterables. As far as I understand ES6, iterable objects all work exactly the same - and identical to generator functions.

I'm not all too familiar with Angular internals, but I'd expect things to become simpler, rather than harder, because of this.

**Comment by gkalpak** [comment] 2016-10-01 13:42
> As far as I understand ES6, iterable objects all work exactly the same - and identical to generator functions.

It depends. Keep in mind that we cannot assume full ES6 support in Angular, because it is not available in all supported browsers. So, for example we can't use `for...of` or `Array.from()` etc.

And since `ngRepeat` supports both arrays and objects/maps, some things are less straight-forward. E.g. we can't "blindly" use `entries()` when available, because we need to be aware of the underlying iterable (do we care about the keys or just the values).

--
> I'm not all too familiar with Angular internals, but I'd expect things to become simpler, rather than harder, because of this.

It would, if we could assume ES6 support (but we can't) 😞 

--
I am not saying it is not possible, but it is something that requires some throught and time (and probably some compromizes). It is on the roadmap, but we're not there yet.

If someone wants to step up and give it a shot, that would be amazing 👍
