### ISSUE TITLE
Error messages is confusing when accessing a property as function

### ISSUE THREAD

**Issue by ittayd** [angular/angular.js#11235] opened 2015-03-03 21:40 UTC
see http://plnkr.co/edit/60r4KhJQRTMZrXYGohc6?p=preview

When running this, the console shows an error: 
TypeError: Cannot read property '0' of null

This happens because $scope.items is an array, but ng-repeat="item in items()". It is hard to find out what ng-repeat causes this and why.

The best error would be "items is not a function in expression 'item in items()'"

**Comment by petebacondarwin** [comment] 2015-03-05 13:42
Thank you for posting this issue and I am sorry that it is difficult to track down bugs in templates like this. The problem we have right now is that by the time the expression is executed we have lost track of the original ng-repeat expression.

But what we could do, inside [`ensureSafeFunction`](https://github.com/angular/angular.js/blob/master/src/ng/parse.js#L71) is to check whether the `obj` really is a function or not and then use the `fullExpression` value, which would be `"items()"` in this case, to throw a better exception.

@lgalfaso and @IgorMinar - what do you think of that? I don't think it would have a huge impact on performance but it is certainly not going to make it any faster!

**Comment by petebacondarwin** [comment] 2015-03-05 13:57
Here is an example: http://plnkr.co/edit/p4yOWxj2fm5SDMpCYnGR?p=preview

**Comment by lgalfaso** [comment] 2015-03-08 17:00
@petebacondarwin I agree that a nicer message would be helpful, but I am not sure that start adding not security checks to `ensureSafe*` functions is best.

I think the best would be to add a property `debugInfoEnabled` to `ParseProvider` (that is `false` by default) and when this is `true` we would wrap `ensureSafeFunction` to also check that what is provided is really a function

**Comment by Narretz** [comment] 2016-09-15 11:47
This now throws "v2.items is not a function" which is better, but still not perfect. It's also a duplicate of https://github.com/angular/angular.js/issues/14072 now

**Closed by Narretz** 2016-09-15 11:47 UTC
Labels: component: $parse, severity: confusing
