### ISSUE TITLE
`$location in HTML5 mode requires a <base> tag to be present` thrown while base tag is present

### ISSUE THREAD

**Issue by adamreisnz** [angular/angular.js#15635] opened 2017-01-23 18:24 UTC
**Do you want to request a *feature* or report a *bug*?**
Possible bug

**What is the current behavior?**
Error `$location in HTML5 mode requires a <base> tag to be present` is occasionally thrown, despite there being a `<base href="/">` tag present.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
This is affecting a production website, I don't have a reproducible demo because it doesn't happen all the time (maybe around 1% of visitors).

**What is the expected behavior?**
No error to be thrown, as the base tag is present.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

Angular 1.6.1
Safari 5.1.9
OS X 10.6.8

Worked in 1.5.x, presumable because it didn't check for the base tag presence then.

**More information**
It's a basic SPA app and the index.html file contains a `<base href="/">` tag. There is no code in place that would remove this tag or modify it somehow.

Could this be caused by a browser extension removing the base tag?

**Comment by gkalpak** [comment] 2017-01-24 21:51
Closing, since this is not actionable. AFAICT, there is no change between 1.5.x and 1.6.x wrt `base` tag detection. We can't do anything without a reproduction. (Happy to reopen and investigate when/if we have one.)

**Closed by gkalpak** 2017-01-24 21:51 UTC

**Comment by sgo** [comment] 2017-02-02 14:05
Here is one http://technoscript.app.binarta.demo.thinkerit.be/
I will be looking to fix it eventually but for now you can see the issue there.
Seems to consistently happen on both firefox and chrome for me.

**Comment by gkalpak** [comment] 2017-02-02 16:59
@sgo, in your case this happen because the href does not contain a trailing slash. We are trying to ignore the origin [here][1] and fail to account for situations where there is no trailing slash.

It seems like a bug to me (unless we had a specific reason - maybe @petebacondarwin has an idea). Temporarily, you should be able to work around it by adding a trailing slash in your `<base>` href.

##
@adamreisnz, could this also explain your issue? I.e. is it possible that `base[href]` could have a trailing slash for 99% of visits and omit it for 1%? Or is it a different issue?

[1]: https://github.com/angular/angular.js/blob/3708162bc8cc23dc62df8a03483c2ffd527a6539/src/ng/browser.js#L306

**Comment by sgo** [comment] 2017-02-02 17:05
Yes, I had just figured that out as I saw a trailing slash in my other applications but not here.
I was planning to come here and tell you but you beat me to it.

If the trailing slash is necessary I think it would be better if the error message reflected that because I did not realize the problem until after playing "where's waldo" with an application that worked. I presume the same would have been true for reading the documentation. It's easy to miss.

Thanks for taking a look.

**Comment by gkalpak** [comment] 2017-02-02 17:05
This is from way back in 2012. There doesn't seem to be a specific reason: [d015945][1]
PRs welcome :smiley:

[1]: https://github.com/angular/angular.js/commit/d0159454dfa2e1cee4dd4ab7a41c2fcf9e121a64#diff-ab8fe92910b19f1815d419aead809672R235

**Comment by sgo** [comment] 2017-02-02 17:11
A pull request? I see there is a corresponding spec so that shouldn't be too hard to do. If it's not too hard to checkout angular and run the test suite.
Best to also check if the trailing slash is necessary or not then as I'd be more inclined to accept the base without it if it is not.

**Comment by gkalpak** [comment] 2017-02-02 17:26
It doesn't seem to be necessary. All we need is change the [`baseHref()` method][1] to treat URLs without the trailing slash the same as URLs with the slash:

```diff
 self.baseHref = function() {
   var href = baseElement.attr('href');
-  return href ? href.replace(/^(https?:)?\/\/[^/]*/, '') : '';
+  href = href.replace(/^(?:https?:)?\/\/[^/]*$/, '$&/');
+  return href ? href.replace(/^(?:https?:)?\/\/[^/]*/, '') : '';
 };
```

And add a couple of tests, of course.

[1]: https://github.com/angular/angular.js/blob/master/src/ng/browser.js#L304-L307

**Comment by adamreisnz** [comment] 2017-02-02 21:01
@gkalpak Our base href did have a trailing slash, as it was just a slash e.g. `href="/"`
We do serve our sites on https.

**Comment by sgo** [comment] 2017-02-03 09:14
https doesn't appear to be an issue on my end. Not to say that it can't be on yours.

**Comment by adamreisnz** [comment] 2017-02-03 20:35
@gkalpak some more information;

- Only seems to occur on Safari (5.0.6, 5.1.7, 5.1.9, and 5.1 mobile)
- Happening on iPad and OS X

All it spits out is `[$location:nobase] $location in HTML5 mode requires a <base> tag to be present!`

As this is not a one-off error (it keeps recurring quite frequently and this site is not that busy), I think it would be good to re-open this issue and investigate further.

Maybe, if nothing else, the error message could be made a bit clearer to help identify what might be causing it to be thrown. Looking in the source of the affected page it is clear that the base tag is populated and set as `<base href="/">`.

Could it be that Safari or some browser extensions might be manipulating the base tag? Removing the slash perhaps?

**Comment by gkalpak** [comment] 2017-02-03 22:58
@adamreisnz, the problem is that without a reproduction there is nothing to investigate (and we can't improve the message if we don't know what is causing the problem). I've looked at the code and I couldn't spot anything suspicious. Since it is happening on specific browsers/versions only, it sounds like the browser is doing something fishy (it could also be an extension - I don't know).

What you can do as a work around (or as a way to invstigate the issue, since you are the only one that has (indirect) access to the reproduction :smiley:) is overwrite the (private, undocumented) [`baseHref()` method][1] and return an appropriate value (or collect more info on the current state of affairs in the `<head>`).

[1]: https://github.com/angular/angular.js/blob/15581287a4ec003680d158b303af07f5f16ffbf0/src/ng/browser.js#L304-L307

**Comment by adamreisnz** [comment] 2017-02-04 00:20
That's not very practical. I am reluctant to modify the code base of Angular in a production environment, as any mistake or unforeseen problem might cause missed revenue for my client...

**Comment by gkalpak** [comment] 2017-02-04 09:56
> I am reluctant to modify the code base of Angular in a production environment, as any mistake or unforeseen problem might cause missed revenue for my client

Totally respect that. If anyone has other ideas on how to further investigate this, I'll be happy to discuss.
<sub>(BTW, I did not suggest changing the Angular code, but your app (decorating `$browser.baseHref()`. But the risks are similar.)</sub>

**Comment by chuckd** [comment] 2017-06-06 06:47
Hitting this from a legacy app we have running on Adobe AIR - it uses a WebKit equivalent to Safari 5.0.3 or so. Haven't got anywhere with debugging yet except that it seems the ```document.find("base")``` call in Angular isn't finding the base tag (it is there). Perhaps this is due to jqLite changes triggering an old WebKit bug.

**Comment by adamreisnz** [comment] 2018-11-23 23:52
I've still got this happening frequently in different apps as well
