### ISSUE TITLE
ng-click called twice with ngTouch included

### ISSUE THREAD

**Issue by tenaz3** [angular/angular.js#10660] opened 2015-01-07 01:40 UTC
I was using google chrome canary and Angular 1.3.8
I realize when I created a single ng-click and logged in console, the click was triggered twice.
.html
```
<div data-ng-click="open()"></div>
```
.js :controller
```
$scope.open = function(){
console.log('click');
}
```
output: 
click appears twice

This is a bug??? 
When I removed ngTouch module from project was worked normally

**Comment by Narretz** [comment] 2015-01-07 09:29
I cannot reproduce this in a simple plnkr.co: 
http://plnkr.co/edit/B0DvWOiybrOiBy6jfYAP?p=preview

Can you create a reproduction?

**Comment by tenaz3** [comment] 2015-01-23 21:17
Well sorry about late. I think the problem isn't in ng-touch actually. This problem just occurs in chrome canary. To reproduce the error, just create a new project with yeoman using angular template(yo angular) and I also used ui-route. Any data-ng-click will be called twice, you can see in console.

**Comment by Narretz** [comment] 2015-01-27 09:45
So it doesn't happen without ui-route? We really need a small reproducable example here.

**Comment by Narretz** [comment] 2015-02-04 14:56
I am closing this because we lack a small reproducible example of this bug. Feel free to reopen if you can provide one.

**Closed by Narretz** 2015-02-04 14:56 UTC
Labels: component: ngTouch, needs: more info

**Comment by tgasslander** [comment] 2015-02-12 05:12
I had the same problem.
`ng-click` events were triggered twice in Chrome but correctly (only once) in Firefox.
The problem was consistent across controllers.

My setup was generated from yeoman and it included `ngTouch`.

However when I removed `ngTouch` from `bower.json`, `index.html` and `app.js` the event duplication disappeared.

Hope this helps.
