### ISSUE TITLE
ngInput directive don't binding on ie11 browser When I was input CJK (I'm Korean).

### ISSUE THREAD

**Issue by powerumc** [angular/angular.js#12659] opened 2015-08-23 14:31 UTC
It don't binding on the ngInput directive. (`<input type="text"/>`)
I should guess that initCompositionEvent has difference under less than the IE11 browser.
We can presenting a bug again in input CJK mode.

You can show [Here](http://plnkr.co/edit/oEfnDObIhZLCV0Ivt7TF?p=preview) is the input bug and code example.

![image](https://cloud.githubusercontent.com/assets/1943755/9428604/f164c63c-49ee-11e5-91dc-3a461096d7cb.png)

**Comment by Narretz** [comment] 2015-08-23 15:12
I think this is a duplicate of #6656. We should evaluate all the solutions that have been offered for this, but I'm not sure if we'll find a good one. The other issue contains a good workaround, though.

**Closed by Narretz** 2015-08-23 15:12 UTC
