### ISSUE TITLE
Infinite digest loop on url replace

### ISSUE THREAD

**Issue by maksimr** [angular/angular.js#10953] opened 2015-02-03 23:48 UTC
Simple case for reproducing problem:

1. open page `https://docs.angularjs.org/tutorial#foo=foo` in Chrome(**Note:** we open page with url fragment `foo=foo`)
2. open developer tools
3. check `preserve log`
4. get injector
```js
var $injector = angular.element(document.body).injector();
```
5. change current url(location.href) to `https://docs.angularjs.org/tutorial`
```js
$injector.get('$location').url('tutorial').replace();
$injector.get('$rootScope').$digest();
```
6. See error `Uncaught Error: [$rootScope:infdig] http://errors.angularjs.org/1.4.0-beta.1/$rootScope/infdig?p0=10&p1=%5B%5D`

http://media.giphy.com/media/3rgXBFCNWWv1UvpeEM/giphy.gif

Thanks!

**Comment by maksimr** [comment] 2015-02-04 00:11
## The cause of the error

In location.js we add [**watcher**](https://github.com/angular/angular.js/blob/master/src/ng/location.js#L921) which watch url change.
If url [changed](https://github.com/angular/angular.js/blob/master/src/ng/location.js#L926) this watcher [add](https://github.com/angular/angular.js/blob/master/src/ng/location.js#L932) function to `asyncQueue` which set [url](https://github.com/angular/angular.js/blob/master/src/ng/location.js#L946).
We set url with replace then we get out [here](https://github.com/angular/angular.js/blob/master/src/ng/browser.js#L197), but location.replace is async function! And when we run [digest](https://github.com/angular/angular.js/blob/master/src/ng/rootScope.js#L721) we have a case when asyncQueue always contain one element(function which change url), because watcher(locationWatch) always(on each iteration) add this function to asyncQueue, because `while` in $digest synchronous and location.replace async.

**Comment by wemersonblend** [comment] 2015-02-06 00:13
Hi Maksimr,

I've been checking this issue, i was wondering if you could digest asynchronous this case, it makes sense?

**Comment by gkalpak** [comment] 2016-04-12 09:20
I can't reproduce the issue with the provided instructions (with Chrome 49).
Could you create a runnable demo (e.g. using CodePen, plnkr etc) ?

**Comment by gkalpak** [comment] 2016-07-10 08:52
Closing due to lack of reproduction (still can't reproduce it on Chrome 51, Windows 10).
Feel free to re-open when you can provide a "reproducible" reproduction :stuck_out_tongue:

**Closed by gkalpak** 2016-07-10 08:52 UTC
Labels: component: $location, needs: investigation, severity: broken expected use, type: bug
