### ISSUE TITLE
Sometimes the code and the result of developer guide does not match

### ISSUE THREAD

**Issue by whrool** [angular/angular.js#13917] opened 2016-02-01 07:43 UTC
Here is the mismatched result, and can not be reproduced absolutely.

![qq 20160201151840](https://cloud.githubusercontent.com/assets/7413974/12711243/4497f80e-c8f9-11e5-8cdb-961042dc9437.png)

![qq 20160201153826](https://cloud.githubusercontent.com/assets/7413974/12711311/e2f95114-c8f9-11e5-83f0-88cd5870ace0.png)

**Comment by gkalpak** [comment] 2016-02-01 12:34
Hm...this seems similar to #13906. Something fishy going on here...

**Comment by Narretz** [comment] 2016-02-01 13:42
Very weird. I also cannot reproduce this mismatch.

**Comment by gkalpak** [comment] 2016-02-01 18:20
This is really weird. The examples in the screenshot seem to be off by one but not in a consistent way:

* `example 44` is shown in place of `example43`
* `example45` is shown in place of `example46`
* `example12` is shown in place of `example11` in #13906
* `example11` is shown in place of `example10` in #13906

What's more weird, as shown in [this image][1] posted in #13906, even the direct link to `example10` shows the contents or `example11`.

[1]: http://oi64.tinypic.com/wl91td.jpg

**Comment by whrool** [comment] 2016-02-02 03:07
It occurred when my network speed becomes slow. And I use an agent called Shadowsocks to browse the Internet. Whether or not it is caused by the agent ? I also have met this situation (http://oi64.tinypic.com/wl91td.jpg) , and if I refresh the site, all will be right.

**Comment by Narretz** [comment] 2016-05-26 15:22
It looks like this isn't really a problem with the angular infrastructure. It also seems to happen very rarily. I'm gonna close this but feel free to reopen if you can provide more info

**Closed by Narretz** 2016-05-26 15:22 UTC
Labels: type: docs
