### ISSUE TITLE
$window.history.back - return to root

### ISSUE THREAD

**Issue by notour** [angular/angular.js#12673] opened 2015-08-25 13:18 UTC
Hi,

I implementing a test site to learn Angular and to create some 'tool' service for further application.
I try to implement the navigation SPA in angular I'm confront to a little problem with the back in code.

Scenario :
- Navigate to home
- Navigate to page 1
- Navigate to page 2

if the code execute the function $window.history.back or  (window.history.back or window.history.go(-1) ...) :
 - On "Edge and Chrome 44.0.24" it go to the root page "http://SITE/"
but it I use the back button from the browser interface the navigation back correctly.

joint a link to the code : <a href="https://drive.google.com/file/d/0BwqMlZk9KxnDX1FnNS1wbDZIUTg/view?usp=sharing">Code </a>

**Comment by petebacondarwin** [comment] 2016-01-25 10:50
I can't reproduce this on Chrome 48 (OS/X). @notour can you test again?

**Comment by gkalpak** [comment] 2016-06-01 18:26
Closing due to lack of reproduction.

**Closed by gkalpak** 2016-06-01 18:26 UTC
Labels: resolution: can't reproduce
