### ISSUE TITLE
I'm getting $digest max iterations reached by redirecting with $window.location.href

### ISSUE THREAD

**Issue by micahblu** [angular/angular.js#13093] opened 2015-10-14 20:08 UTC
I've also tried with `window.location.href` and `$location.path()` with same results. I've scoured stackoverflow for fixes and none have panned out. I've tried wrapping the call within $evalSync and that doesn't work either. The only thing I've found to work is wrapping it within a setTimeout, which is not reliable. 

Interesting too is that the bug is only present when the app is initially loading, the redirect works fine afterwards.

Any help would be greatly appreciated.

**Comment by Narretz** [comment] 2015-10-15 15:54
Can you please provide a demo of the code that reproduces this issue?

**Comment by micahblu** [comment] 2015-10-16 23:09
I'll do my best to put together a minimized sample over the weekend and post a link here. Thanks for the quick response.

**Comment by Narretz** [comment] 2015-11-03 21:55
Closing because we don't have a repro scenario :( Feel free to reopen when you can provide one.

**Closed by Narretz** 2015-11-03 21:55 UTC
Labels: component: $location, needs: more info
