### ISSUE TITLE
Not able to reflect server side changes in  Model on html when using Controller as cntrl syntax.

### ISSUE THREAD

**Issue by vijayjumbad** [angular/angular.js#10975] opened 2015-02-05 10:07 UTC
Hi ,
I have written EmpController  with employee attribute. The syntax used for controller is 'EmpController as empctr'.  Employee has some properties like name,salary etc. I used $http service  inside EmpController  to fetch the employee from server.  The server returns proper json result but model is not getting updated. Below is code.. The thing is that when I use $scope in COntroller instead of this and remove ;controller as ' synatx everything works fine.
I tried to search if similar issue has been raised earlier but could not found. Hence posting this .
Please Suggest.

index.html

<div ng-app="login">
		
		<div ng-controller="EmpController as empctr">
			<input type="text" ng-model="empName" /> <br>
			<button id="getEmpl" ng-click="empctr.submit(empName)">Get</button>
			Employee Details are as below:
			Name : {{empctr.employee.name}}    	     Sex : {{empctr.employee.sex}} <br>
			
			Salary :  {{empctr.employee.salary}}        nationality: {{empctr.employee.nationality}} 
			
			
		</div>
	</div>

COntroller:

	angular.module('login').controller('EmpController',
		[ 'EmpService','$http', function(EmpService,$http) {
			this.employee = new EmployeeDef('', '', '', '');

var updateResponse= function updateResponse(data){
	/** logic to update response
	
};

			this.submit = function submit(empName) {

				var req =EmpService.getEmpData(empName);
				$http(req)
				.success(
						function(data, status, headers,
								config) {
							updateResponse(data);
							
						}).error/*** next code
						***//

**Comment by vijayjumbad** [comment] 2015-02-05 10:08
I am running code on Google Chrome Version 40.0.2214.94 m.

**Comment by pkozlowski-opensource** [comment] 2015-02-05 15:13
@vijayjumbad it is not enough info in this issue description to help you - more specifically you are not sharing the code for `updateResponse`. My _wild_ guess is that your issue is due to confusion about the `this` in $http callback, but it is impossible to know for sure without seeing code.

At any rate this sounds like a support question and as such should be asked [elsewhere](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). 

I'm going to close this one as it doesn't sound like a bug in AngularJS. If you still believe that there is a bug in the framework, please provide live, minimal reproduce scenario using plunker or similar.

**Closed by pkozlowski-opensource** 2015-02-05 15:13 UTC
