### ISSUE TITLE
Different grouping in select 1.4.10 vs. 1.5.0 vs. 1.5.4 (CodePens attached)

### ISSUE THREAD

**Issue by stschaefer** [angular/angular.js#14781] opened 2016-06-15 11:50 UTC
Hi guys,

after updating angular from 1.4.9 to 1.5.6 I experience a different grouping behaviour in the select when using ng-options. 

Please take a look on my codepens:

http://codepen.io/hoody/pen/gMMPBg (Angular 1.4.10: expected behaviour)
http://codepen.io/hoody/pen/EyyPeJ (Angular 1.5.0: new optgroup container around option)
http://codepen.io/hoody/pen/ZOOQjq (Angular 1.5.6: new optgroup container around option AND empty optgroup before listing of optgroups)

Is this a known bug? Will it be fixed? Do you have a workaround for me? :)

Greetings,
Stefan

**Comment by Narretz** [comment] 2016-06-15 13:50
Thanks for the report, very thorough.
Quick Answer: Not a known bug, yes, no. :D

**Comment by Narretz** [comment] 2016-06-15 13:57
Sorry, I was a bit too quick. This is not a bug, but a known documented breaking change: https://code.angularjs.org/snapshot/docs/guide/migration#directives-ngoptions-

**Comment by stschaefer** [comment] 2016-06-15 14:04
Nevertheless, thanks for your quick reply. With the help of the link I could fix the issue. :+1: 

Greetings,
Stefan

**Comment by Narretz** [comment] 2016-06-15 14:06
@gkalpak There's still a bug here :>

**Comment by gkalpak** [comment] 2016-06-15 14:09
Sorry, I was a bit too quick. :stuck_out_tongue:

**Comment by Narretz** [comment] 2016-06-16 10:34
Fix for the duplication bug landed in https://github.com/angular/angular.js/commit/6bc81ae6ef96436b27a9aa6ee3769e394118ecc9

**Closed by Narretz** 2016-06-16 10:34 UTC
Labels: branch: 1.5.x, branch: 1.6.x, frequency: low, severity: broken expected use, severity: regression, type: bug
