### ISSUE TITLE
Having  angular for composer

### ISSUE THREAD

**Issue by lalithr95** [angular/angular.js#13137] opened 2015-10-21 07:28 UTC
Having an angularJS for composer would be great which would be helpful in php based applications. As we have Jquery, bootstrap for the composer. 
Laravel uses composer to install the dependencies in the similar way we extend for angular as well.

If that's good idea we can start with it :)

**Comment by Narretz** [comment] 2015-10-27 17:19
Duplicate of https://github.com/angular/angular.js/issues/13056

**Closed by Narretz** 2015-10-27 17:19 UTC
