### ISSUE TITLE
Including CSS with a directive

### ISSUE THREAD

**Issue by Jon889** [angular/angular.js#10294] opened 2014-12-02 14:40 UTC
It seems like it should be easier to include CSS with a directive, it would be great if the directive definition object had a cssUrl field so that you could do:

```
app.directive('myDirective', function () {
    return {
        templateUrl:'templates/myTemplate.html',
        cssUrl: 'css/myCSS.css',    
        link: function (scope, elm, attrs, ctrl) {

        }
    };
});
```

Then an link element would be inserted in the head with the href to the cssUrl URL.

**Comment by Narretz** [comment] 2017-02-17 14:47
Duplicate of #15014

**Closed by Narretz** 2017-02-17 14:47 UTC
Labels: component: $compile, needs: public api, type: feature
