### ISSUE TITLE
why the cause in ExceptionHandlerProvider is always undefined?

### ISSUE THREAD

**Issue by bargitta** [angular/angular.js#11069] opened 2015-02-16 03:30 UTC
I try to add context to the exception handler, e.g., when there is an exception, I want to know which controller throws it, instead of just pure stack trace. I find that the one provided by angular has two parameters: exception and cause, and "cause" is supposed to be a string with context information. However it is not used in the implementation and always be undefined.
How can I add such information in cause?

```js
function $ExceptionHandlerProvider() {
  this.$get = ['$log', function($log) {
    return function(exception, cause) {
      $log.error.apply($log, arguments);
    };
  }];
}
```

**Comment by pkozlowski-opensource** [comment] 2015-02-16 18:56
@bargitta the `$exceptionHandler` defines a generic API that people are free to implement differently, taking `cause` into account. But given that the default implementation doesn't take this param into account nor it is called with the cause anywhere, maybe we should document this / remove? 

I agree that the current situation is slightly confusing....

**Comment by pkozlowski-opensource** [comment] 2015-02-16 19:01
Wait, actually the cause argument _is_ taken into account. So you can pass whatever you want as the additional argument(s).

I'm not sure we want to add context info in the framwork itself, I'm not sure it would add anything on top of the stack trace (where you've got all the classes involved).

Why are you saying this:
> when there is an exception, I want to know which controller throws it, instead of just pure stack trace

What is the info, from the framework, that you don't have in the stack trace? What is the exact error that is hard to track in your particular case?

**Comment by bargitta** [comment] 2015-02-17 02:20
Thanks for your reply.
For example, sometimes I get errors of the 3rd party like the following. I want to know in which controller this 3rd party function is called so that I could dig into it. But the default $exceptionHandler does not set the cause parameter, and since it is unhandled exception (not something thrown explicitly by my code), I have no idea how can I set the cause parameter. It will be very helpful if the framework could pass some information there.

TypeError: undefined is not a function
    at Object.fn (http://localhost:6677/vendor/angular-bootstrap/ui-bootstrap-tpls.min.js:9:1667)
    at Scope.$get.Scope.$digest (http://localhost:6677/vendor/angular/angular.js:12434:29)
    at http://localhost:6677/vendor/angular/angular.js:9776:45
    at http://localhost:6677/vendor/angular/angular.js:4490:7
    at Array.forEach (native)
    at forEach (http://localhost:6677/vendor/angular/angular.js:325:11)
    at fireUrlChange (http://localhost:6677/vendor/angular/angular.js:4489:5)
    at n.event.dispatch (http://localhost:6677/vendor/jquery/dist/jquery.min.js:3:6404)
    at n.event.add.r.handle (http://localhost:6677/vendor/jquery/dist/jquery.min.js:3:3179) undefinedangular.js:9959 (anonymous function)angular.js:7298 $getapp.js:72 (anonymous function)angular.js:12453 $get.Scope.$digestangular.js:9776 (anonymous function)angular.js:4490 (anonymous function)angular.js:325 forEachangular.js:4489 fireUrlChangejquery.js:4409 n.event.dispatchjquery.js:4095 n.event.add.r.handle

**Comment by gkalpak** [comment] 2016-06-01 08:53
Such errors are caught in the digest's `try/catch` block. It is a very generic `try/catch` and we don't really have any more context (other than the scope whose watcher caused the error or the watcher itself - both of which would be of very little value to the debugger).
The stacktrace is your best friend here.

Closing, but feel free to reopen (or open a new issue) if you have any suggestions on how we could provide a useful `cause`. (Note that a `scope` is not necessarily bound to a specific controller or element.)

**Closed by gkalpak** 2016-06-01 08:53 UTC
Labels: component: misc core, needs: more info
