### ISSUE TITLE
Removing an element in a nested directive

### ISSUE THREAD

**Issue by mbenadda** [angular/angular.js#11494] opened 2015-04-02 16:39 UTC
I have a problem with nested directives that remove elements. I don't know if this is a bug or a feature request. It seems to me that it should be possible to remove an element from inside a nested directive.

When attempting to remove a nested element in the compile function of its directive, I get the following error :

```html
<outer-directive>
  <div my-directive></div>
</outer-directive>
```

```javascript
app.directive('myDirective', function () {
  return {
    compile: function(tElem, tAttrs) {
      tElem.html('');
      tElem.remove();
    }
  };
});
```

```
TypeError: Cannot read property 'childNodes' of undefined
    at compileNodes (angular.js:7049)
    at angular.js:7970
    at processQueue (angular.js:13249)
    at angular.js:13265
    at Scope.$get.Scope.$eval (angular.js:14467)
    at Scope.$get.Scope.$digest (angular.js:14283)
    at Scope.$get.Scope.$apply (angular.js:14572)
    at done (angular.js:9699)
    at completeRequest (angular.js:9889)
    at XMLHttpRequest.requestLoaded (angular.js:9830)
```

In addition, the outer directive entirely stops compiling after raising that exception, so there are no bindings, etc.

I can partly remedy this by moving the element removal to the link function of the directive. The directive compiles and everything works properly, but there is still a raised exception.

```html
<outer-directive>
  <div my-directive></div>
</outer-directive>
```

```javascript
app.directive('myDirective', function () {
  return {
    compile: function(tElem, tAttrs) {
      return function(scope, elem, attrs) {
        tElem.html('');
        tElem.remove();
      };
    }
  };
});
```

```
TypeError: Cannot read property 'insertBefore' of null
    at forEach.after (http://localhost:8001/vendor/angular/angular.js:3187:13)
    at Object.JQLite.(anonymous function) [as after] (http://localhost:8001/vendor/angular/angular.js:3271:17)
    at Object.$AnimateProvider.$get.enter (http://localhost:8001/vendor/angular/angular.js:4690:23)
    at http://localhost:8001/vendor/angular/angular.js:22089:26
    at publicLinkFn (http://localhost:8001/vendor/angular/angular.js:6996:29)
    at $get.boundTranscludeFn (http://localhost:8001/vendor/angular/angular.js:7136:16)
    at controllersBoundTransclude (http://localhost:8001/vendor/angular/angular.js:7796:18)
    at Object.ngIfWatchAction (http://localhost:8001/vendor/angular/angular.js:22080:15)
    at Object.oneTimeListener [as fn] (http://localhost:8001/vendor/angular/angular.js:12853:20)
    at Scope.$get.Scope.$digest (http://localhost:8001/vendor/angular/angular.js:14309:29)
```

I was hoping to mitigate this issue by delaying the element removal through the use of `scope.$applyAsync` (which as I understand should be able to do that as we're in a directive) or `setTimeout` but neither of these got rid of the exception.

Anyway, I encountered this problem while using [mobile-angular-ui](http://mobileangularui.com/)'s `uiContentFor` directive but I don't think this problem is specific to that library -- removing nested elements from a directive is a behavior I currently need and would have to implement on my own anyway. Of course, if there is a relevant way to do this that I overlooked, I'll be glad to use it and also submit a pull request to mobile-angular-ui.

Otherwise I suppose it should be possible to add type checks in the directive compiling loops to make sure a node still exists before attempting to access its properties. I could submit a PR if you think this is the path to follow.

My use case was to project buttons / modals into divs that are actually located outside of the directive. An example would be to put an OK button in the top navbar in a mobile app.

I think given the current focus on using directives as components in preparation to Angular2 and web components, directives should be able to support element removal at compile or link phase.

**Comment by Narretz** [comment] 2015-04-02 21:50
It doesn't make sense that you are removing the `tElem`- which is the root element of your directive. Why would you remove it?

**Comment by mbenadda** [comment] 2015-04-02 22:26
Well this is a simplified example. In real life the directive copies its body into another part of the document.

Or maybe you did mean that myDirective should just be a container and be left in-place as an empty remain with its content moved elsewhere ?

**Comment by lgalfaso** [comment] 2015-04-03 13:56
This looks like a duplicate of #9198. BTW, removing the element is not a supported action.

**Closed by lgalfaso** 2015-04-03 13:56 UTC
Labels: component: $compile

**Comment by mbenadda** [comment] 2015-04-03 14:01
Ok @lgalfaso thanks for this clarification. I'll see to submit a pull request in the lib.

**Comment by dlsso** [comment] 2018-01-17 20:10
> removing the element is not a supported action.

Important to know, thanks! Didn't see this in the documentation and my directive was broken because of it.
