### ISSUE TITLE
cannot use ng-if on select default option any more

### ISSUE THREAD

**Issue by Tim-Erwin** [angular/angular.js#12951] opened 2015-09-25 20:26 UTC
I cannot conditionally have a default option for a select using ng-if. See here: http://plnkr.co/edit/lGaZeIFHBUTVciqNMp2B?p=preview

I was able to do that with Angular 1.3.x. With Angular 1.4.x instead of an adding a default option, the default option is displayed as selected in the closed select box, but in fact the first real option is selected. That's independent of wether ng-if is true or false.

When I resort to ng-show it works correctly in the "true" case. However, in the "false" case, it will show the default option as selected although when opening the select (or inspecting the element), it's not there.

As a workaround one can use ng-show and set an option as selected explicitly.

**Comment by Narretz** [comment] 2015-09-25 21:56
This is a dupe of #12190. Here's a PR: #12952

**Closed by Narretz** 2015-09-25 21:56 UTC
