### ISSUE TITLE
Strange behaviour of cyrillic symbol using ngPattern

### ISSUE THREAD

**Issue by sschegolev** [angular/angular.js#14181] opened 2016-03-04 16:49 UTC
Hi all. In my directive I use ngPattern and regExp
`/^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}$/` for some input.
When I try to tap cyrillic symbol in that input for the first time that change current email with some strange behaviour. It seems like angular tries to encode my symbol. For example:
Was: for@mat.com
Became: for@mat.xn--com-hdd 
xn--...-hdd - was added to the email.

If I try to continue tapping there is no problem and cyrillic symbols appear in the input.

**Comment by gkalpak** [comment] 2016-03-05 07:51
@sschegolev, could you post a live demo (e.g. using CodePen, Plnkr etc) ?

**Comment by m-amr** [comment] 2016-03-06 20:56
I have created a Plinkr and can't see the Issue 
https://plnkr.co/edit/vQjAaGV3dNMyqQDcwMY5?p=preview
everything work normally

**Comment by gkalpak** [comment] 2016-03-08 00:57
Unfortunately, there is not much we can do if we can't reproduce the problem.
I can't think of anything that might cause what you described. `ngPattern` does not change the input value; it merely validates it and reports if it's valid or not.

Closing for now, but feel free to reopen when you have a minimal reproduction.

**Closed by gkalpak** 2016-03-08 00:57 UTC
Labels: component: forms, needs: more info, type: bug
