### ISSUE TITLE
ngShow not working on stable versions

### ISSUE THREAD

**Issue by atishaybaid** [angular/angular.js#11430] opened 2015-03-25 19:22 UTC
ng-show/ng-hide not working on stable versions, i tried with 1.3.13 and 1.3.15,however it works fine with CDN

**Comment by pkozlowski-opensource** [comment] 2015-03-25 19:33
@atishaybaid not sure I understand. Could you please share a reproduce scenario using http://plnkr.co/edit/?p=preview ?

**Comment by pkozlowski-opensource** [comment] 2015-04-13 10:02
Closing due to the lack of reproduce scenario.

**Closed by pkozlowski-opensource** 2015-04-13 10:02 UTC
