### ISSUE TITLE
Can no longer cancel $resource request with a promise

### ISSUE THREAD

**Issue by simonjm** [angular/angular.js#9332] opened 2014-09-29 21:56 UTC
I've tested this on Chrome 37.0.2062.124 m, Firefox 32.0.3, and IE11 on Windows 8.1

Here is some code to reproduce the issue.

```html
<body ng-app="testApp">
    <div ng-controller="TestCtrl">
        <button type="button" ng-click="clear()">Clear</button>
        <ul>
            <li ng-repeat="val in dataset">
                {{val | json}}
            </li>
        </ul>
        <button type="button" ng-click="start()">Start</button>
        <button type="button" ng-click="stop()">Stop</button>
    </div>
    <script type="text/javascript" src="https://code.angularjs.org/1.3.0-rc.3/angular.js"></script>
    <script type="text/javascript" src="https://code.angularjs.org/1.3.0-rc.3/angular-resource.js"></script>
    <script type="text/javascript">
        angular.module('testApp', ['ngResource']).controller('TestCtrl', function ($scope, $resource, $q) {                                   
            var promises = [];
            function getResource() {
                var defered = $q.defer();
                promises.push(defered);
                return $resource('/data', {}, {
                    query: {
                        method: 'GET',
                        isArray: true,
                        timeout: defered.promise
                    }
                });
            }

            $scope.start = function () {
                getResource().query(function (res) {
                    $scope.dataset = res;
                });
            };

            $scope.stop = function () {
                promises.forEach(function (p) { p.resolve(); });
                promises = [];
            };

            $scope.clear = function() {
                $scope.dataset = [];
            }
        });
    </script>
</body>
```
https://github.com/angular/angular.js/commit/23bc92b17df882a907fb326320f0622717fefe7b appears to be the culprit. Before this the above code works as expected.

**Comment by tsonev** [comment] 2015-01-06 14:48
This is a very valuable article, around which I have created my own duplicate request aborter service. 

https://developer.rackspace.com/blog/cancelling-ajax-requests-in-angularjs-applications/

Does it mean that from 1.3 on this will not be possible anymore?

**Comment by Orcrist78** [comment] 2015-02-27 15:36
try to change this line of ngResource source code:

httpConfig[key] = copy(value);

in

httpConfig[key] = key !== 'timeout' ? copy(value) : value;

the problem is the copied promise

**Comment by valente** [comment] 2015-04-23 20:52
I tracked down this issue to [resource.js, 563](https://github.com/angular/angular.js/blob/master/src/ngResource/resource.js#L563-567):

<pre lang="javascript"><code>
            forEach(action, function(value, key) {
              if (key != 'params' && key != 'isArray' && key != 'interceptor') {
                httpConfig[key] = copy(value);
              }
            });
</code></pre>

The function clones all config values except some with special treatment. The timeout promise is currently getting cloned. So, when [httpBackend.js, 115](https://github.com/angular/angular.js/blob/master/src/ng/httpBackend.js#L115-119) receives the timeout,

<pre lang="javascript"><code>
    } else if (isPromiseLike(timeout)) {
      timeout.then(timeoutRequest);
    }
</code></pre>

It actually registers that callback on a clone, which never gets resolved.

I made a quick & dirty fix which doesn't clone but just assigns a 'timeout' property in the iteration above, and issue gets resolved.

**Comment by qpitlove** [comment] 2015-06-08 12:03
:+1: @valente

**Comment by psergus** [comment] 2015-08-28 23:43
any workaround for this?

**Comment by kayhadrin** [comment] 2015-08-29 03:12
I've crafted a promise that can be cancelled so that I can ignore the ajax
request result if need be.

**Comment by psergus** [comment] 2015-08-29 03:32
yeah, I was playing with the promise as well and following this example https://developer.rackspace.com/blog/cancelling-ajax-requests-in-angularjs-applications/ I can do just abort() on resource and ignore the ajax response. However, it does not solve the issue. If a browser is clogged if slow responses,  which cannot be cancelled, it decreases the performance level. 
I am contemplating to write my own lightweight version of ngResource with cancelable actions.

**Comment by kayhadrin** [comment] 2015-08-29 04:57
Correct me if I'm wrong, but I thought that applying a patch for this was
relatively easy in Angular's source code?

**Comment by darabos** [comment] 2015-10-08 15:54
I see the reason behind copying the config from the Resource to the `$http` request (isolating requests from each other). But cancellation really needs to be solved. How can you live without it?

I see the arguments for the Resource actions are already Byzantine, but could we add one more optional argument that is a per-request `config` object for `$http`? This could be merged with the Resource-level config without copying.

This could be useful in other cases as well. (E.g. decide caching on a per-request basis.) I'd be happy to work on this issue with a little guidance. Thanks!

**Closed** 2015-10-28 22:26 UTC
Labels: component: $q, component: ngResource, severity: broken expected use, severity: regression
