### ISSUE TITLE
Hard coded <option> causes error "TypeError: Cannot read property 'getOptionFromViewValue' of undefined"

### ISSUE THREAD

**Issue by godza** [angular/angular.js#11685] opened 2015-04-23 01:14 UTC
Hi, in documentation is stated that 'empty option' can be used when using ng-options. Here is direct quote

> Optionally a single hard-coded **option** element, with the value set to an empty string, can be nested into the **select** element. This element will then represent the null or "not selected" option

I used that in 1.3 very heavily  and it worked flawlessly, but in 1.4 i'm getting error
```
TypeError: Cannot read property 'getOptionFromViewValue' of undefined
```

Just to be clear, here is the template i'm using

```html
<select ng-options="option.id as option.name for option in selectable_options">
  <option value="">Choose an option</option>
</select>
```

Is this planed regression or a bug? If this is planed regression, is there a workaround for the thing i'm trying to accomplish?

**Comment by gkalpak** [comment] 2015-04-23 10:07
I can't reproduce the error. Which version are you using. Ideally you should provide and live reproduction using CodePen, JSFiddle, Plnkr or a similar.

<sub>You should also use `ngModel` on the select.</sub>

**Comment by godza** [comment] 2015-04-23 11:11
Hi, i was using 1.4 rc and i built latest angular from git master, but it's the same error. Here is the plunkr but error thrown there is not the one you get when you're running from files on your computer

As you can see, the select is not populated with options.

```
http://plnkr.co/edit/l0SV6rcOeVufxJ2f6oNm?p=preview
```

**Comment by gkalpak** [comment] 2015-04-23 11:44
I don't get any error. (Neither on my computer nor in the plnkr.)
`ngOptions` requires `ngModel`, so it won't populate your `<select>`, unless you have `ngModel` on it.

[Updated plnkr][1]

[1]: http://plnkr.co/edit/jGQO46vvikq1J2z7PKV9?p=preview

**Comment by lammel** [comment] 2015-04-23 12:49
We are seeing the same issue in our application. But only in a particular situation (we pass the a model to a directive which in turn displays the select with the hardcoded empty option). Other usage of select with ng-options works fine (also with the hardcoded empty option).

We try to isolate the issue in a plunker for further analysis.

**Comment by bbasic** [comment] 2015-04-23 13:10
I have modified the plnkr in order to exemplify the problem.

http://plnkr.co/edit/tOpUPO1fZge3tuxzUHpY?p=preview

I've isolated the problem to the instruction for directive to replace the element in DOM, ```replace: true```

**Comment by godza** [comment] 2015-04-23 13:37
@gkalpak i finally managed to reporoduce the problem, even on plunker.

The catch is that template of customSelect directive in my example needs to be loaded via templateUrl. In that case i see errors and list is not printed.

- If you edit **select_template.html** file and remove **empty option** it works
- if you copy/paste select_template.html content and paste it in **template** property of directive definition, it will work even with **empty_option**

```
http://plnkr.co/edit/l0SV6rcOeVufxJ2f6oNm?p=preview
```

**Comment by bbasic** [comment] 2015-04-23 14:03
Just to be thorough. 
It will work in a situation where **replace: true** is not used.

[plunker] (http://plnkr.co/edit/JEoUUxhyLYxRF7Qs2LqV?p=preview) 
Uncomment the line 27 in **app.js** to see the error.

**Comment by gkalpak** [comment] 2015-04-23 14:33
Indeed it seems that the combination of `templateUrl` (instead of `template`) and `replace: true` results in no options being created.
I am not sure if this should be fixed though, considering that `replace: true` has been deprecated.

@petebacondarwin, wdyt ?

**Comment by godza** [comment] 2015-04-23 14:37
@gkalpak even though it's deprecated it should be working properly until removed.

**Comment by marcelgwerder** [comment] 2015-06-11 09:41
I think I have the same issue. I have a simple select with an additional custom directive that uses ` 

```js
$compile(element.contents())(scope); 
```
It only works if I either remove the empty option:

```html
<select ng-options="country.code as country.title for country in countries" ng-model="selectedCountry" random-directive>
</select>
```

Or the custom directive:
```html
<select ng-options="country.code as country.title for country in countries" ng-model="selectedCountry">
    <option value="">Please select...</option>
</select>
```

But both together throw a `TypeError: Cannot read property 'getOptionFromViewValue' of undefined`.

http://plnkr.co/edit/kIZqA67L1adub2f179Yj?p=preview

This worked with 1.3:

http://plnkr.co/edit/VA5NeFeTYExSb7jCtOYs?p=preview

**Comment by egervari** [comment] 2015-09-16 13:19
Thank you thank you for the replace: true post. This solved my problem as well.

**Comment by Narretz** [comment] 2015-09-28 10:34
Here's why it happens:
In a regular select, the <option> elements add themselves as options to the selectCtrl. It also adds an element $destroy listener that  removes the option and forces a render.
In a ngOptions select, the first <option> element is extracted from the element, and compiled separately. Since it's not part of the document, it doesn't have a selectCtrl parent, and it doesn't get added. 
If another directive compiles the select contents before ngOptions is linked, the option gets added. But when ngOptions runs it also gets removed from the DOM, and its destroy listener is called, which calls render, which delegates to ngOptions, which at this point doesn't have options set.
So the easy fix is simply to check if options are defined here: https://github.com/angular/angular.js/blob/1.4.6/src/ng/directive/ngOptions.js#L459
But the problem also raises some questions about the interop between ngOptions and select ...

**Comment by petebacondarwin** [comment] 2015-09-28 12:30
https://github.com/angular/angular.js/blob/v1.4.6/src/ng/directive/ngOptions.js#L459

**Comment by petebacondarwin** [comment] 2015-09-28 12:45
A workaround is to ensure that your random directive has a higher priority than the `select` and `ngOptions` directives: http://plnkr.co/edit/kIZqA67L1adub2f179Yj?p=preview

**Closed** 2015-10-06 12:54 UTC
Labels: component: $compile, component: forms, type: bug
