### ISSUE TITLE
Wire up a Backend example broken on angularjs.org

### ISSUE THREAD

**Issue by Mateopato** [angular/angular.js#12754] opened 2015-09-04 05:30 UTC
The save button on the create a new project view in the Wire up a Backend example section demo of the front page of angularjs.org appears to be broken. 

Steps to reproduce:
1. Navigate to angularjs.org.
2. Scroll down to Wire up a Backend section.
3. In demo on the right side of the page, click the plus sign to add a new project.
4. Type in valid data.
5. Hit save button--nothing happens.

Chrome's console gives a "TypeError: Projects.$add is not a function" error. I assume the code in detail.js should be Projects.projects.$add instead of Projects.$add, but that's a guess. The edit project save button works correctly, but the new project save button does nothing.

![image](https://cloud.githubusercontent.com/assets/3789235/9677161/72ace1ee-52a4-11e5-9abb-7073ff194ae2.png)

**Comment by gkalpak** [comment] 2015-09-04 07:10
Duplicate of https://github.com/angular/angularjs.org/issues/171.

**Comment by gkalpak** [comment] 2015-09-04 07:11
BTW, this repo is for AngularJS. Issues regarding https://angularjs.org should be filed at https://github.com/angular/angularjs.org.

**Closed by gkalpak** 2015-09-04 07:10 UTC
