### ISSUE TITLE
jQlite `.one` order incorrect

### ISSUE THREAD

**Issue by SimeonC** [angular/angular.js#6916] opened 2014-03-31 03:10 UTC
I noticed in some of my tests that jqlite is currently removing the event passed through to `.one` before firing it. I've shown the code (@ [jqLite.js#L764](https://github.com/angular/angular.js/blob/master/src/jqLite.js#L764)) and my fix for it being correctly executed. This was tested with 1.2.15, the code is same in the current master repo as at the link above.

Current Code:

``` js
one: function(element, type, fn) {
    element = jqLite(element);

    //add the listener twice so that when it is called
    //you can remove the original function and still be
    //able to call element.off(ev, fn) normally
    element.on(type, function onFn() {
      element.off(type, fn);
      element.off(type, onFn);
    });
    element.on(type, fn);
  },
```

Should Be:

``` js
one: function(element, type, fn) {
    element = jqLite(element);

    //add the listener twice so that when it is called
    //you can remove the original function and still be
    //able to call element.off(ev, fn) normally
    element.on(type, fn);
    element.on(type, function onFn() {
      element.off(type, fn);
      element.off(type, onFn);
    });
  },
```

**Comment by mgol** [comment] 2018-03-28 20:09
I'm going through old jqLite issues but I can't reproduce a problem with the handler passed to `one` not firing, both for native events & when used with `triggerHandler`. The `handle` function responsible for handling events is shallow-cloning the handlers array before invoking them so both should be invoked anyway.

That said, all the tests seem to pass if the order of the handlers is reversed. Thus, I'm closing the issue now but if someone has a test case (or a code snippet at least) showing when the problem arises I'll happily land a patch that reverses the ordering.

**Closed by mgol** 2018-03-28 20:09 UTC
Labels: component: jqLite, type: bug
