### ISSUE TITLE
Karma is not recognized as the internal or external command

### ISSUE THREAD

**Issue by shafaiatul** [angular/angular.js#12023] opened 2015-06-04 01:08 UTC
In order to run karma as part as an angular-seed project, use this command:

npm install -g karma-cli

**Comment by Narretz** [comment] 2015-06-08 12:13
Is this a request to update the docs about this?

**Comment by Narretz** [comment] 2015-06-15 19:56
Closing because the issue is not clear.

**Closed by Narretz** 2015-06-15 19:56 UTC
Labels: needs: more info
