### ISSUE TITLE
$browser exhibits weird behavior in keeping track of history when $location.search is used to set param

### ISSUE THREAD

**Issue by wesleycho** [angular/angular.js#4367] opened 2013-10-10 19:12 UTC
I used $location.search('attemptID', 123456) in an app (say while `window.location.href` is `path/to/url`, and after the user is completed with a view, the app then calls $location.path('path/to/another/url') - when I hit back on the browser, my app sends me to `path/to/another/url?attemptID=123456`, instead of the expected behavior of `path/to/url?attemptID=123456`.

Is this expected behavior, and why?

**Comment by gkalpak** [comment] 2017-01-03 17:35
I am going to close this, since it is about a pretty old version (and hopefully not an issue any more) and the reproduction repositories have been removed. If this is still an issue in latest releases, please open a new bug report.

**Closed by gkalpak** 2017-01-03 17:35 UTC
Labels: needs: more info, type: bug
