### ISSUE TITLE
ngSrc duplicate request for iframe in IE

### ISSUE THREAD

**Issue by Ilya-Hubich** [angular/angular.js#9843] opened 2014-10-30 14:42 UTC
Hi.

I have the issue with iframe and ngSrc directive in IE 10 in Standard mode. 
When I set the ngSrc value it duplicate request for iframe resources.
One of them is with status 'aborted' and another is '200 OK'.

But sometimes on the server side we get 2 requests instead of 1.
It's critical for us because one of params(guid) should be unique, but when two same requests are sent the guids are the same too.

The jsfiddle exampe is here : http://jsfiddle.net/6au10sk4/4/

In angular  source code i find :

Line:15704

          attr.$set(name, value);
          // on IE, if "ng:src" directive declaration is used and "src" attribute doesn't exist
          // then calling element.setAttribute('src', 'foo') doesn't do anything, so we need
          // to set the property as well to achieve the desired effect.
          // we use attr[attrName] value since $set can sanitize the url.
          if (msie && propName) element.prop(propName, attr[name]);
        });

I think here is the problem :

          if (msie && propName) element.prop(propName, attr[name]);

**Comment by vriestimo** [comment] 2015-02-05 14:09
I can confirm this issue exists for IE8 as well. Is someone working on this yet?

**Comment by wescopeland** [comment] 2015-07-27 17:54
+1

**Comment by tsonev** [comment] 2015-07-29 11:17
+1
to work around the problem a temporary solution could be a custom directive that would set the element attribute src in the link function.

Something like:
http://jsfiddle.net/eebfcb77/

**Comment by ramirezd42** [comment] 2015-07-30 00:19
The solution that @Ilya-Hubich posted previously worked well for me. 

It's not the prettiest but I'd be happy to submit a pr for something along those lines if no one can think of a better approach.

**Comment by lingalamadhukar** [comment] 2015-07-30 08:36
+1 
The solution is working fine in IE

**Comment by fasfsfgs** [comment] 2015-08-24 01:40
+1
Thank you! This solution worked great!

Did anyone manage to make a directive that solves this issue as well? I'm afraid to leave this solution in the angular src code...

**Comment by fasfsfgs** [comment] 2015-09-18 22:00
Do we have any news on this issue? We already have a PR with the solution discussed here but it isn't moving.
Since the current solution involves messing around with angular source code, it's not safe for people that have this issue to update it.

**Comment by ramirezd42** [comment] 2015-09-18 22:55
I'm honestly on the fence about whether it should be pulled in or not. 

On one hand it's not the most elegant solution to the problem and would leave a bit of a workaround scar. 

On the other hand, having to add an external dependency just to have a directive that doesn't break for iframes in IE also seems a bit silly, and would be frustrating for people that encounter the issue and haven't seen this thread. Also, it doesn't seem much worse to me than the `if (msie && propName) element.prop(propName, attr[name]);` that was there already.

Just my 2 cents.

**Comment by fasfsfgs** [comment] 2015-09-19 00:26
I actually don't think it's a workaround at all.
That is what's Angular about, isn't it? It provides stable directives that's browser agnostic.
Angular source code is full of specific code for some browsers so it doesn't break on them.

**Comment by Ilya-Hubich** [comment] 2015-09-21 20:32
I suppose the best solution is to create your own directive, as I've done.
Here is my solution:
```javascript
angular.module('app')
    .directive('iframeSrc', function () {
        return {
            restrict: 'A',
            link: function (scope, element, attrs) {
                attrs.$observe('iframeSrc', function (value) {
                    if (value) {
                        attrs.$set('src', value);
                    }
                });
            }
        };
    });
```
And then use it like this:
```
    <iframe iframe-src="{{src}}"></iframe>
```

**Comment by fasfsfgs** [comment] 2015-09-21 21:15
Thanks for sharing this @Ilya-Hubich.
This is way better than messing with Angular's source code.

I still hope we can rely on Angular with this feature in the future (hey that rhymes... =D).

**Comment by ThiagoPorto** [comment] 2016-02-24 14:43
I replaced ng-src by src and it worked

**Comment by bartoszbobin** [comment] 2016-09-14 11:03
For me it works - angular 1.3.17
`<iframe
    class="form-group"
    ng-if="reviewCtrl.previewAttachmentUrl"
    src="{{ reviewCtrl.previewAttachmentUrl }}"></iframe>`

**Comment by gkalpak** [comment] 2016-09-16 11:55
Thx for the feedback @bartoszbobin. I can't indeed reproduce it on newer versions.
Closing...

**Closed by gkalpak** 2016-09-16 11:55 UTC
Labels: browser: IE10, browser: IE11, component: misc core, frequency: low, severity: broken expected use, type: bug

**Comment by faizhal-ahamed** [comment] 2018-10-03 21:55
It is happening again in IE 1.1.17134.0 - Windows10
