### ISSUE TITLE
Can see the "under the hood movements" for animations on mobile

### ISSUE THREAD

**Issue by sonoman** [angular/angular.js#7438] opened 2014-05-13 03:31 UTC
This does not happen on my notebook, but my cell phone (once it is shipped with Phonegap. I think it has something to do probably with speed.
I have a sliding transition for ng-views, where leaving view moves out to left (from 0 to -100%), and entering view starts from left = 100% to left = 0. 
When I click on some button changing route, on my phone I can see for a very short moment how the "entering" view moves to the right, as if it is taking its initial position to start moving to the left. it appears that when angular is asigning that view the class for starting at 100%, that class is also animated.
It's only a moment, given that right away, it starts moving to the left as the desired animation.
Of course, the leaving view doesn't do anything weird because it already starts at 0% so everything is fine.

Below the style I'm using:

```
.slide.ng-enter,
.slide.ng-leave,
.slide_inverse.ng-enter,
.slide_inverse.ng-leave,
.grow.ng-enter, .grow.ng-leave {
    transition-duration: 0.15s;
    -webkit-transition-duration: 0.15s;
    -ms-transition-duration: 0.15s;
    transition-timing-function: ease-in;
    -webkit-transition-timing-function: ease-in;
    -ms-transition-timing-function: ease-in;
    backface-visibility:hidden;
    -webkit-backface-visibility:hidden;
    -moz-backface-visibility:hidden;
    -ms-backface-visibility:hidden;
}
.slide.ng-enter {
    -webkit-transform: translate3d(100%, 0, 0);
    transform: translate3d(100%, 0, 0);
}
.slide.ng-enter.ng-enter-active {
    -webkit-transform: translate3d(0, 0, 0);
    transform: translate3d(0, 0, 0);
}
.slide.ng-leave {
    -webkit-transform: translate3d(0, 0, 0);
    transform: translate3d(0, 0, 0);
}
.slide.ng-leave.ng-leave-active {
    -webkit-transform: translate3d(-100%, 0, 0);
    transform: translate3d(-100%, 0, 0);
}
```

This is more evident for the routes whre I have a resolve that retrieves data from backend.

**Comment by Narretz** [comment] 2017-02-16 14:16
I'm going to close this issue because we have no reproduction of the issue. Feel free to reopen this issue if you can provide a reproduction (ideally a runnable demo in a [Plunker](https://plnkr.co) or similar. You can use this [Plunker Template](http://plnkr.co/edit/tpl:yBpEi4)).

**Closed by Narretz** 2017-02-16 14:16 UTC
Labels: browser: Phonegap, component: ngAnimate, frequency: low, severity: broken expected use, type: bug
