### ISSUE TITLE
$resource   problem with 17 digit number

### ISSUE THREAD

**Issue by mnuthan1** [angular/angular.js#15708] opened 2017-02-14 07:22 UTC
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
 we are using $resource to query a 17 digit number,  http response in browser showing correct response where as result from query is giving wrong number.  For example from server i am getting  [{"id":"41538455546609777"}] as response where as from $resource.query I am seeing  [{"id":"41538455546609780"}]

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Which versions of AngularJS, and which browser / OS are affected by this issue? Did this work in previous versions of AngularJS? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

1.5.6

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by gkalpak** [comment] 2017-02-14 10:36
The circumstances under which it happens (or what exactly happens) are not clear.
Please, provide more info, including exact steps to reproduce or a runnable demo (ideally using CodePen, Plnkr etc).

**Comment by Narretz** [comment] 2017-02-20 10:54
I'm going to close this issue because we haven't got any feedback. Feel free to reopen this issue if you can provide new feedback.

**Closed by Narretz** 2017-02-20 10:54 UTC
Labels: component: ngResource, needs: more info
