### ISSUE TITLE
[1.6.1] NgModel set value undefined in input number with decimal 

### ISSUE THREAD

**Issue by GuillaumeSmaha** [angular/angular.js#15636] opened 2017-01-24 00:06 UTC
Have undefined value for 0.07.

Related to bug #15257 and 081d06ffd15c2c6c539ce97b5eb63fa8e2403818

It seems fixed for 1.5.9/1.5.11 but not for 1.6.1
See on plunk :
- 1.5.9 : https://plnkr.co/edit/BFK1qzq9jYenB57yut2E?p=preview
- 1.5.11 : https://plnkr.co/edit/sPWns1rB0QfxRFUxToUZ?p=preview
- 1.6.1 : https://plnkr.co/edit/TUET0tyQqUQDh9dhyKgv?p=preview

**Comment by sabby62** [comment] 2017-01-24 18:31
Adding convert-to-number to select tag should get it working meanwhile.

**Comment by gkalpak** [comment] 2017-01-24 21:24
This is a duplicate of #15504.
- For 1.5.x, it was fixed with 1.5.11 (which was released after 1.6.1).
- For 1.6.x, the fix has been merged (c95a673) and it will be released soon, with 1.6.2.

**Closed** 2017-01-24 21:24 UTC

**Comment by GuillaumeSmaha** [comment] 2017-01-24 23:09
@gkalpak Thanks !
