### ISSUE TITLE
Returning null in transformResponse returns request data

### ISSUE THREAD

**Issue by andreaslarssen** [angular/angular.js#16190] opened 2017-08-22 08:44 UTC
**I'm submitting a ...**
- [X] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

This is the method in my service, returning a resource:

```
sendSMSOTP: {
        method: 'POST',
        url: APIBase.fetch('v1/auth/sendSMSOTP'),
        transformResponse: function (jsonData) {
          var data = null;

          try {
            data = angular.fromJson(jsonData);
          } catch (e) {
            return null;  // <-- Returning null
          }

          return data;
        }
      }
```
Calling the method: 

```
AuthenticationService.sendSMSOTP({
      ssn: ctrl.credentials.ssn,
      phone: ctrl.credentials.phone,
      entryToken: ctrl.credentials.entryToken
    }, function (success) {
      console.log('success', success);
    }, function (error) {
      console.log('error', error);
    });
```

... returns the request data to the success (and error) callback when server returns an unexpected response not possible to parse to json, making the transformResponse method return null:

```
success Resource {ssn: "SSN", phone: "PHONENO", entryToken: "TOKEN", $promise: Promise, $resolved: true}$promise: Promise {$$state: {…}}$resolved: trueentryToken: "TOKEN"phone: "PHONENO"ssn: "SSN"__proto__: Object
```

Returning an empty object instead of null: 

```
sendSMSOTP: {
        method: 'POST',
        url: APIBase.fetch('v1/auth/sendSMSOTP'),
        transformResponse: function (jsonData) {
          var data = null;

          try {
            data = angular.fromJson(jsonData);
          } catch (e) {
            return {};  // <-- Returning empty object
          }

          return data;
        }
      }
```

... returns an empty resource: 

```
success Resource {$promise: Promise, $resolved: true}
```

**Expected behavior:**
You would expect the service method callbacks to receive an empty resource when returning null from the transformResponse, wouldn't you? Or am I not understanding something? Can't seem to find the behavior documented. 

**Minimal reproduction of the problem with instructions:**
If this is indeed a transformResponse bug, you should be able to reproduce by just returning null from a service method: 

```
sendSMSOTP: {
        method: 'POST',
        url: APIBase.fetch('v1/auth/sendSMSOTP'),
        transformResponse: function (jsonData) {
          return null;
        }
      }
```

**AngularJS version:** 1.6.4. Upgraded to 1.6.6, still there.

**Browser:**
Tested in:
- Chrome 60.0.3112.101 (64-bit)
- Firefox 54.0.1 (32-bit) 
- Firefox 55.0.2 (32-bit)
- IE 11.540.15063.0
- Edge 40.15063.0.0

**Comment by gkalpak** [comment] 2017-08-22 15:31
I tried to reproduce this and couldn't. Please provide a live reproduction (e.g. using CodePen, Plnkr or similar).

**Comment by andreaslarssen** [comment] 2017-08-23 10:08
That's more than strange to me. I'll come back with a plnkr as soon as I find the time. But with what you've said, I'm thinking it must be a local problem, so I'll try and spin up a brand new angularjs project to see what happens. Thanks for checking it out.

**Comment by Narretz** [comment] 2017-09-06 14:33
I'm going to close this issue because we have no reproduction of the issue. Feel free to reopen (or ask to reopen) this issue if you can provide a reproduction (ideally a runnable demo in a [Plunker](https://plnkr.co) or similar. You can use this [Plunker Template](http://plnkr.co/edit/tpl:yBpEi4)).

**Closed by Narretz** 2017-09-06 14:33 UTC
Labels: component: ngResource, needs: more info
