### ISSUE TITLE
Function created by angular.mock.inject() doesn't return the return value of the wrapped function

### ISSUE THREAD

**Issue by Sleepyowl** [angular/angular.js#13621] opened 2015-12-23 13:22 UTC
Consider the following test (mocha + chai):
```javascript
it("async test", function(){
    // preparation etc
    return expect(somePromise).to.eventually.eq("some value");
});
```

Using `inject()` to wrap the whole test function will break it:
```javascript
it("async test that doesn't know it's async", inject(function($q){
    // preparation etc
    return expect(somePromise).to.eventually.eq("some value");
}));
```
Function wrapper created by inject doesn't propagate return value to mocha. That is especially problematic if you need to use composition of test function wrappers:
```javascript
var t = function(f){ return sinon.test(inject(f)); };
it("even worse", t(function($q){ /* ... */}));
```

Could you please consider returning test function return value from function wrapper created by `angular.mock.inject()` or confirm that you're not going to do that. Thanks.

**Comment by Narretz** [comment] 2015-12-23 13:42
Dupe of https://github.com/angular/angular.js/issues/13584

**Closed by Narretz** 2015-12-23 13:42 UTC
