### ISSUE TITLE
Namespaces Support

### ISSUE THREAD

**Issue by VitalyTomilov** [angular/angular.js#11139] opened 2015-02-22 18:31 UTC
We'got used to the fact that all Angular directives start with 'ng-' and all third-party libraries follow it by using their own prefix. The problem is that such approach is neither enforced nor it is stipulated in any way, except for the fact it may break things, if not followed.

If there was a way for a library to register it's prefix as predefined, this would solve many issues if incompatibility and erroneous overrides.

Example:
````
var myLib = app.library('ml');

myLib.directive('DirName', [function () {
    return {
    }
}]);
````
Such <b>library</b> would simply redirect registration to module <b>app</b>, while automatically extending directive name as if it were 'mlDirName'. Such approach would guarantee that directives from different libraries do not get into naming conflicts. Only library name/prefix would have to be unique in this case.

**Comment by pkozlowski-opensource** [comment] 2015-02-22 18:38
@VitalyTomilov this is duplicate of existing issues, ex.:
* https://github.com/angular/angular.js/issues/2767
* https://github.com/angular/angular.js/issues/2447

and those issues got some discussion going already. Please, let's centralize this discussion - could you add your comments in there?

Closing as a duplicate.

**Closed by pkozlowski-opensource** 2015-02-22 18:38 UTC

**Comment by VitalyTomilov** [comment] 2015-02-22 18:42
Oh, man, almost a 2-year long discussion without a resolution still...

Yeah, I was late to the party :)
