### ISSUE TITLE
Ng-model doesn't initialize properly when a select option's value is set using curly braces

### ISSUE THREAD

**Issue by distinctdan** [angular/angular.js#12668] opened 2015-08-24 19:22 UTC
Hi,

I'm trying to use ng-model with an html select. However, I'm using curly braces to set each option's value to a scope variable (An enum, specifically). Unfortunately, my select's default option never gets selected when the page loads. I suspect that ng-model runs before the values get interpolated.

Here's my plunker: http://plnkr.co/edit/Q3yM8t53PdpN1pG64T52?p=preview

I would use ng-options, but in our real app, each option has an ng-if to hide it, depending on the user's permissions. Also, unfortunately I can't build an options array in the controller, because it needs to be in the html template for our translation process to work.

Thanks!

**Comment by frfancha** [comment] 2015-08-24 20:07
@distinctdan As a workaround you can assign your default value as such:
$timeout(function() {self.fruit = 'banana';}, 50);
(self comes from the classical var self = this;)
This way the html is "ready" when ng-model receives 'banana'

**Comment by Narretz** [comment] 2015-08-26 21:54
This is a dupe of https://github.com/angular/angular.js/issues/12005. I have a PR here: https://github.com/angular/angular.js/pull/12582 I just need someone to review it.

**Closed by Narretz** 2015-08-26 21:54 UTC
