### ISSUE TITLE
ngRoute not firing 'window.onhashchange' event

### ISSUE THREAD

**Issue by betonetotbo** [angular/angular.js#14875] opened 2016-07-06 18:58 UTC
When I use routes on ngRoute, they aren't firing `hashchange` event of the `window`, but at the address bar of the browser the url is updated.

To reproduce, just create a simple ngRoute app, and put on a `script` tag this

`window.onhashchange = function() { alert(window.location.hash); }`

The `alert` never appears.

**Comment by gkalpak** [comment] 2016-07-06 20:20
We are not doing anything to prevent the `hahchange` event and I can't reproduce it ([example][1]).
Please, provide a runnable demo (e.g. using CodePen, Plnkr etc) that shows the problem.

[1]: https://codepen.io/ExpertSystem/pen/GqvqLq?editors=0011

**Comment by Narretz** [comment] 2016-07-21 09:48
I'm going to close this issue because we haven't got any feedback. Feel free to reopen this issue if you can provide new feedback.

**Closed by Narretz** 2016-07-21 09:48 UTC
Labels: component: ngRoute, frequency: low, needs: more info, severity: broken expected use, type: bug
