### ISSUE TITLE
Controller definition inside ng-view

### ISSUE THREAD

**Issue by michaldudak** [angular/angular.js#11384] opened 2015-03-20 07:41 UTC
If a ngRoute view contains an inline script with controller definition, that controller fails to register. A workaround is to enable `$controllerProvider.allowGlobals();` and define a controller as a global function, but the recommended approach does not work.

 Here's the plunker showing the problem: http://plnkr.co/edit/JU350xL7X9ryF3S72o6s

Click on the link there to change the route and take a look at the browser's console.

**Comment by wesleycho** [comment] 2015-03-21 17:47
I'm not sure this is behavior that was intended to be supported.

**Comment by pkozlowski-opensource** [comment] 2015-03-21 18:40
Nope, currently there is no mechanism to load controllers on demand. We are working on it and @btford owns the topic, you can read more about it here: https://github.com/angular/angular.js/issues/11015

Global controllers were dropped in 1.3 so this is not a path to take either. 

Closing as duplicate of #11015

**Closed by pkozlowski-opensource** 2015-03-21 18:40 UTC

**Comment by michaldudak** [comment] 2015-03-21 18:50
Thanks, good to know you're taking it into consideration.
