### ISSUE TITLE
bug($compile): custom annotations don't work on named controllers

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular.js#14279] opened 2016-03-19 15:14 UTC
BUG in angular.js : v1.5.0...v1.5.2; master
In $compile we attach custom annotations to the controller constructor. But this doesn't work if the component controller is specified by name (i.e. a controller that was defined by the `module.controller(...)` helper.

This was noted at  https://github.com/angular/angular.js/pull/14114#issuecomment-198185528

http://plnkr.co/edit/glqJw8ezAHVJAbtGY4au?p=preview

We should handle this scenario.  The question is: should get hold of the referenced controller and attach the custom annotation directly to the constructor function, or whether we create a new derived controller from the named controller and assign the custom annotation to the derived controller constructor?

I thinking more likely the latter...

**Comment by petebacondarwin** [comment] 2016-03-19 15:47
Agh! This is a real pain to fix, since we don't have access to the controller's constructor function if it was defined by `mod.controller(...)`.

The workaround is to put the custom annotation directly onto the controller's constructor in the first place. See http://plnkr.co/edit/QS34r5wO6TpOO3rmfGiF.

Supporting this is also problematic, as noted in this bug report, where we would have to either modify the controller's constructor, which may be shared among components or somehow create yet another controller function derived from the provided controller for each component. In fact this is problematic even without named controllers, where the controller is shared among different components.

I am tempted to say that using custom annotations with a component that is using a named/shared controller is not supported.

**Comment by alexgoldstone** [comment] 2016-03-21 00:25
@petebacondarwin I raised #14284 which @gkalpak closed as a duplicate of this one.

Are you able to show how your workaround should be applied for `$routeConfig` because when I follow your Plunker in the context of #14284 I get the error:

```
Component "Root" has no route config.
```

**Comment by gkalpak** [comment] 2016-03-21 13:24
@alexgoldstone, with currently released versions, the only work-around it to not register component/directive controllers by name, but reference the actual function/Class itself (as mentioned in https://github.com/angular/angular.js/issues/14284#issuecomment-199061481).

E.g. instead of `controller: 'AppController'` do `controller: AppController`.
See an example [here][1].

We understand this is inconvenient and are working on a fix, so you will be able to use either form (string or function/Class) to register component controllers soon :smiley:

[1]: https://codepen.io/ExpertSystem/pen/bpqvap?editors=0010

**Comment by alexgoldstone** [comment] 2016-03-22 02:59
@gkalpak Thank you for the clarification. It was helpful as I now know I misunderstood previous comments. This workaround means the component and controller declarations need to live in the same file so I haven't tried yet but will do so asap. Thanks again.

**Comment by gkalpak** [comment] 2016-03-22 06:14
> This workaround means the component and controller declarations need to live in the same

Yes unless you are using some module system that allows you to import/require the controller from a different file.

BTW, you can still instantiate the controller separately for tests, by means of the `$componentController` service provided by `ngMock`.

**Closed** 2016-04-04 19:06 UTC
Labels: branch: 1.5.x, branch: 1.6.x, component: $compile, needs: feedback, needs: investigation, needs: work, severity: inconvenient, type: bug
