### ISSUE TITLE
Model inside dynamically compiled ngIf not updating properly

### ISSUE THREAD

**Issue by michaldudak** [angular/angular.js#14506] opened 2016-04-25 06:53 UTC
I've got a specific case where my directive adds an ngIf attribute to an element and recompiles it. Prior to 1.5.0-beta1 it worked as desired, but after I recently updated angular to latest version, the {{ }} interpolation inside my directive stopped working. I think the lazy compilation of ngTransclude function introduced in beta1 may cause it.

See http://jsbin.com/cademegoze/1/edit?html,js,output for a repro - click the button and notice the value inside the second directive is not updating.

I can get around this by using ng-bind instead of {{ }} (as shown on the demo) but as I'm building a library I wouldn't like to restrict users from doing what usually works across angular applications.

**Comment by Narretz** [comment] 2016-04-25 10:32
Hi,
yeah this is 99% caused by lazy transclusion. However, in your example you are doing something that's considered bad practice: re-compiling the same element twice. This can be problematic if you don't know what other directives are on the element and what kind of behavior they add.
I've looked at some workarounds, but so far I've got nothing.

I wonder what's the use case for your wrapper?

**Comment by michaldudak** [comment] 2016-04-25 11:19
Well, you're right, this can cause some problems. I'll think about rewriting it. I stumbled upon this problem when working on a read/edit-mode switcher in my grid: https://github.com/michaldudak/light-grid/blob/page-size-split/src/lightGrid/view.js#L63

**Comment by Narretz** [comment] 2016-04-25 11:23
The problem is that with lazy compilation, the second compilation receives the already compiled text node (1) instead of {{value}}, so no interpolation is detected and no watcher is added.

Here are two other options that achieve the same thing:

1. Extract the contents (html) of the node at compile time, and replace the compiled contents before recompilation. Note that this adds twice the interpolation watchers though. One for the first compilation and one for the second. (same as your original working example)

2. Make the directive terminal and the wrapper directive an attribute. This way, you can stop the interpolation from happening and when you recompile, the wrapper directive isn't included again.

I'm still not sure about the use case though. Especially with structural directives like ngIf, you should let the user make that choice where and when they add them.

**Comment by Narretz** [comment] 2016-05-19 12:41
I'm going to close this issue because we haven't got any feedback, and I because re-compilation is not a supported mechanism.

**Closed by Narretz** 2016-05-19 12:41 UTC
Labels: branch: 1.5.x, component: $compile
