### ISSUE TITLE
URL generation for defined routes / Use routing service to both map and generate URLs

### ISSUE THREAD

**Issue by slavafomin** [angular/angular.js#7091] opened 2014-04-11 18:05 UTC
Hello, right now `$routeProvider` from `ngRoute` is used to setup routes for application.

It looks like this:

``` javascript
$routeProvider
    .when('/', {
        redirectTo: '/foo'
    })
    .when('/foo', {
        controller: 'FooCtrl',
        templateUrl: '/partials/foo',
    })
    .when('/foo/bar', {
        controller: 'FooBarCtrl',
        templateUrl: '/partials/foo-bar',
    })
;
```

And in the HTML we have to use code like this:

``` html
<a href="/foo">Foo</a>
<a href="/foo/bar">Foo's Bar</a>
```

The problem is, that this approach is breaking [DRY](http://en.wikipedia.org/wiki/Don't_repeat_yourself) principle. We have to specify URL's in two places: first in route definition `when('/foo', ...)` second in `href` attribute of HTML page. It gets complicated pretty fast when you have lots of routes and complex URLs and you trying to refactor it somehow.

The better approach is to use single service to both map and generate URLs. This service can be configured like this:

``` javascript
$routeProvider
    .when('root', '/', {
        redirectTo: '/foo'
    })
    .when('foo', '/foo', {
        controller: 'FooCtrl',
        templateUrl: '/partials/foo',
    })
    .when('foo-bar', '/foo/bar', {
        controller: 'FooBarCtrl',
        templateUrl: '/partials/foo-bar',
    })
;
```

And HTML could look like this:

``` html
<a ng-href="foo | route">Foo</a>
<a ng-href="foo-bar | route">Foo's Bar</a>
```

And both `foo | route` and `foo-bar | route` will be replaced by proper URLs generated with the help of routing service.

This is exactly how [routing implemented in Symfony 2 framework](http://symfony.com/doc/current/book/routing.html#generating-urls) for example.

Of course, this routing service can be implemented by the end-developers, but I think the whole community will benefit greatly if it will be included in the `ngRoute`. In the end, this is a good practice to keep things DRY.

Thank you! I hope I'm not duplicating issues.

**Comment by Narretz** [comment] 2017-04-26 14:39
Essentially duplicate of #1791. Note that there are no plans to implement this at this point, since uiRouter already has all these features.

**Closed by Narretz** 2017-04-26 14:39 UTC
Labels: component: ngRoute, frequency: moderate, severity: inconvenient, type: feature
