### ISSUE TITLE
Chinese is handled incorrectly while using `input [type="email"]`

### ISSUE THREAD

**Issue by leftstick** [angular/angular.js#14679] opened 2016-05-26 08:28 UTC
**What is the current behavior?**

While having an input as `<input type="email" ng-model="email"/>`, once i typed in few Chinese words, the `email` model i got became messy. As following snapshot: 

![screen shot 2016-05-26 at 4 27 46 pm](https://cloud.githubusercontent.com/assets/1059956/15568495/d09f6eda-235e-11e6-94ed-8505bc4b3deb.png)

Here is the [plunker](http://plnkr.co/edit/ekEUdRTWlMZpn7C8L8Nj?p=preview)

**Comment by gkalpak** [comment] 2016-05-26 09:47
It seems to work fine on my machine. I guess there is something else (non-Angular related) going on.
What is the value of the input element (e.g. `document.querySelector('input').value`) ?

**Comment by leftstick** [comment] 2016-05-26 10:53
hi @gkalpak , have you tried modify something in the `input`? I mean, the initial state is correct, but once you modify something(even just remove a character `t` from the whole email), the output part get messed up

**Comment by leftstick** [comment] 2016-05-26 13:26
I've recored a `gif` to express the issue. While modifying `input`, the right output part went into messy, even get value via `document.querySelector('input').value`. But once the characters `test` were totally removed, the value retrieved by `document.querySelector('input').value` went to normal. And the output part disappeared because of the invalid email format

![test](https://cloud.githubusercontent.com/assets/1059956/15575948/fb542bd8-2387-11e6-946c-6f1f11e6356f.gif)

**Comment by gkalpak** [comment] 2016-05-26 18:26
As your gif shows, it is not an Angular-specific issue. `ngModel` just reads the input's `value` property.
The same problem can be reproduced without Angular.

I'm not at all familiar with chinese and how it's handled in browsers, but if there is a bug it is on the browser side, not Angular.

Closing...

**Closed** 2016-05-26 18:26 UTC
Labels: component: forms, frequency: low, needs: investigation, needs: more info, severity: broken expected use, type: bug

**Comment by lgalfaso** [comment] 2016-05-26 22:49
Without a way to test this, it is hard to know for sure, but it looks like
the browser is punycode escaping the domain name (to what it is in fact the
real domain name)
