### ISSUE TITLE
Copied promise stays unresolved

### ISSUE THREAD

**Issue by Cinamonas** [angular/angular.js#8726] opened 2014-08-22 07:39 UTC
I believe this issue is related to [23bc92b1 commit](https://github.com/angular/angular.js/commit/23bc92b17df882a907fb326320f0622717fefe7b) in `v1.3.0-beta.18`.

Up until this change, when you copied a promise with `angular.copy` and resolved deferred *afterwards*, the copy would be resolved along with it. But now it stays unresolved. I'm not sure if this behaviour makes sense as both promises originate from the same deferred, which you then resolve.

See these fiddles with identical code, but different AngularJS versions, illustrating the issue:

- [`v1.3.0-beta.17`](http://jsfiddle.net/jshmzph7/1/) – both promises are resolved
- [`v1.3.0-beta.18`](http://jsfiddle.net/o7jc04e4/) – only original promise is resolved

Which behaviour should be considered correct?

I have encountered this issue when [dotJEM/angular-routing](https://github.com/dotJEM/angular-routing) stopped working with `v1.3.0-beta.18`. So if not a regression, it's a breaking change then.

**Comment by lgalfaso** [comment] 2015-01-03 14:15
This issue is not isolated to angular promises, as all Promise A+ implementations have the same issue. The root of the problem is that promises are not meant to be copied around. With this in mind, I am closing this issue as invalid.

**Closed by lgalfaso** 2015-01-03 14:15 UTC
Labels: component: $q, needs: more info, resolution: won't fix

**Comment by jeme** [comment] 2015-01-03 15:47
@lgalfaso while that is correct, aren't you also stating that the angular.copy method does in fact misbehave in that it actually copies promises??...

Since the angular.copy method already has special handing for allot of things, would it be that bad to add a special case for when encountering promises?...

**Comment by lgalfaso** [comment] 2015-01-03 16:13
@jeme I think it would be a bad idea for `angular.copy` to try to handle every single thing that is out there and handle it using a specific API for each case. There are just too many different things that need to be handled in different ways. Now, once ES6 promises is out and there is a reasonable browser support, then I think it would be ok to add some special logic (same goes for other ES6 constructs)

**Comment by jeme** [comment] 2015-01-03 17:44
@lgalfaso yet angular already looks at "IsPromiseLike" when providing something to the $q.when service... so the difference is?

It would be fair if it only worked with angular promises in my mind though.

**Comment by lgalfaso** [comment] 2015-01-03 18:57
`$q.when` deals needs to know what is a promise and what is not a promise. That is what `$q.when` does, so it needs to know what it is a promise and what is not. The fact that *thenable* objects are handled as promises is a consequence of the fact that Promise/A+ mandates this.

`angular.copy` is meant to handle simple objects. Given a promise `p1`, what is the expected behavior of a copy `p2`? Should `p2` get resolved when `p1` is resolved? If `p1` is locked/resolved, should `p2` also be locked/resolved? If `p1`, when resolved, would resolve other promises (each with its own functions that should get called), should `p2` also have other promises that should get called and also trigger the same functions?
Many of these are not easy questions to answer, the reason being that it is not defined what a copy of a promise is, nor how it should behave.


If I go back to the original issue opened, it reads
```
...
v1.3.0-beta.17 – both promises are resolved
v1.3.0-beta.18 – only original promise is resolved

Which behaviour should be considered correct?
...
```

The answer would be: When passing a promise to `angular.copy`, the resulting object has its behavior unspecified

**Comment by jeme** [comment] 2015-01-03 20:28
@lgalfaso I think your making a promise out to be a much more complex construct that it is.
If you review it just as a future result I think the answer is quite simple.

Why should copying an object change it's behavior? By the second argument, the promise should be able to be resolved with a different state?... But now it's not really a true copy is it?... 

 - A) `both promises are resolved`: Framework friendly, as you can grap an object from a framework, copy it and pass it on. Things won't break... The framework can be treated as a black-box.
 - B) `only original promise is resolved`: Not Framework friendly, copying objects may break behavior and you will have a hard time figuring out why. To compensate you need to know the insides of the framework, the framework must suddenly be treated as a white-box...

Anyways, I stand by my opinion here...
But I can see ill have to stop using angular.copy...

**Comment by Gauravshah** [comment] 2019-08-12 13:25
thanks @jeme, wasted a day and then came to this article. Not sure how many more hours I would have spent if I had not read this. I agree with the thought. I don't see any reason to copy a promise at the same time I do not see any reason not to , especially when promises are part of big object.
