### ISSUE TITLE
$watch breaking change from 1.2 to 1.3

### ISSUE THREAD

**Issue by areel** [angular/angular.js#12301] opened 2015-07-08 15:11 UTC
I have recently migrated our code base from 1.2 to 1.3.16.

We have noticed the following change in behaviour.

We have a directive that is responsible for detecting and reacting to a change in the height of our application's root dom element.

Our strategy involved the following function

```
function watchElementHeightChange() {
                scope.$watch
                    (
                        function() { return element.height(); },
                        function (newValue, oldValue) {
                            if (newValue !== oldValue) {
                                requestResize("height Change");
                            }
                        }
                    );
            }
```
This has worked robustly within our Angular 1.2 codebase, when a digest occurred the value returned by our watchExpression's function  ``` element.height()``` was the new height of our element.

Moving to 1.3, this was no longer true, the value returned by the watchExpression function ```element.height()``` was the height of the element before the digest occurred. Also at no time during the digest's multiple invocations of the watchExpression did that value change.

I have not seen any mention of this change in behaviour mentioned in the migration document (https://docs.angularjs.org/guide/migration). 

Nor have I seen any internet chatter either apart from this question on SO (http://stackoverflow.com/questions/27810450/angularjs-getting-stale-results-for-element-dimensions-in-a-directive-1-2-vs-1?rq=1)

As a workaround we have adopted the following :
```
function watchElementHeightChange() {
                scope.$watch
                    (
                        function() {
                            setTimeout(function () {
                                newHeight = element.height();
                                if (oldHeight !== newHeight) {
                                    oldHeight = newHeight;
                                    requestResize("height change");
                                }
                            },100);
                        }
                    );
            }
```

The use of ```setTimeout``` to avoid raising more digest cycles.

I would appreciate, if someone could either confirm what I have written or explain where I have errored.

Regards

Aidan

**Comment by gkalpak** [comment] 2015-07-08 21:21
1. It is not considered a good practice to access DOM properties (especially if that results in layout thrashing).

2. You can use `$timeout` and still avoid invoking a digest (by using `$timeout`'s third argument).

3. It is really hard to tell what the problem might be without a live reproduction.

4. If I had to guess, I would say that the change in height is a result of class manipulation, which happens (either explicitly or implicitly) using Angular's `$animate` (either the built-in or `ngAnimate`'s one).

**Comment by areel** [comment] 2015-07-11 17:57
1. I do not consider this comment appropriate to the question asked, see(4) below. This is a directive not a controller, so accessing/monitoring dom elements should be acceptable. No one mentioned layout thrashing, and layout thrashing (if I guess correctly what that means) is not occurring.
2. Thanks, had not spotted that, this will allow me to remove Jasmine's Clock dependency from our test suite.
3. If on rereading this comment, a sample is still required, I will provide one.
4. This suggests that you misread the post. The change in height is expected and is not in question. In 1.2 the new height is provided as the new value in the $watch, in 1.3 the old, original height is provided as the new value.

**Comment by gkalpak** [comment] 2015-07-11 18:38
1. I just realized that I omitted a very crucial part from my previous comment. What I meant to say is that _"it is not considered a good practice to access DOM properties (especially if that results in layout thrashing) **in a watch function**"_. (I fixed the original comment to avoid future confusion.)

In case it is not obvious, a watch function can be triggered multiple times during a digest (at least 2), so accessing the DOM (which is known to be slow) inside a watch function is not recommened. (Performance is not the only reason, but it's a major one).

Additionally, using jQuery's `height`, which uses `getBoundingClientRect()` under the hood, will cause a _forced synchronous layout_ (aka _layout thrashing_) each time, which is a really bad practice perfomance-wise.
([Layout thrashing cheatsheet][1] - thx @ThomasBurleson for sharing :wink:) 

--
3. As already mentioned, it is really hard to tell what the problem might be without a live reproduction (and the comment didn't actually provide any more info regarding the problem).

--
4. Sorry, I did **not** misread the post. What I said in (4) is actually what I believe is going on, but it's really impossible to be sure without more info (see (3) :smiley:).
In fact, I believe (but again I can only guess here) that this is a duplicate of #10522. Take a look at https://github.com/angular/angular.js/issues/10522#issuecomment-67627356 for a more detailed explanation of what I meant in (4).

[1]: http://ricostacruz.com/cheatsheets/layout-thrashing.html

**Comment by areel** [comment] 2015-07-13 22:49
The clarifications and url links you provided show that you had not misread the question and they have allowed me to understand the points that you were making.

1. I am aware of $watch being triggered multiple times during a digest, I did not see the correct height value in any of the calls made in a given digest. I was not aware of the underlying cost of JQuery's height function, I will read the link provided and look for an alternative method for getting the current height.
3. The digest is caused by a binding change, e.g. a given select control has values that when selected cause some visible controls to be hidden while making some hidden controls visible, or by a check box being ticked/unticked, again some additional controls being made visible on selection and invisible on deselection using ng-show/ng-hide. It would help the poster, if, when more information is required, some indication of what kind of information is needed, some direct questions would help.
4. #10522 looks to be the same issue, I believe the change in behaviour I am seeing is due to deferring class changes to postDigest, since the hiding / showing of components is via ng-show which translates to the class ".ng-hide".

Any advice on a strategy for detecting height change within an Angular applications that avoids $watch would be appreciated. 

The requirement to be able to react to a change in the DOM height stems from having to support running the application within 3rd party integrator's embedded IE components, some are locked down in various ways, one of which is the prevention of client side code executing window resizing, so there is a need to detect height changes passing them to the appropriate external handler.

**Comment by gkalpak** [comment] 2015-07-14 09:53
> I will read the link provided and look for an alternative method for getting the current height

I don't really think there is a "cheap" way to actually get the height, but note that in most cases this is not necessary (as you can watch for stuff that triggered the change in height - usually height's don't just change randomly). That said, things are more complicated when something happens outside of the Angular context, but it should be possible nonetheless.

--
> It would help the poster, if, when more information is required, some indication of what kind of information is needed, some direct questions would help.

Quoting myself from above:
> It is really hard to tell what the problem might be without a live reproduction.

I thought _"live reproduction"_ was direct enough (but still I haven't seen any :P). 

--
> I believe the change in behaviour I am seeing is due to deferring class changes to postDigest, since the hiding / showing of components is via ng-show

Indeed, [`ngShow`][1] uses `$animate.add/removeClass()` to add/remove `.ng-hide`, so the change is deferred until the post-digest phase (and thus not detectable in your watch).

--
> Any advice on a strategy for detecting height change within an Angular applications that avoids $watch would be appreciated.

As I mentioned above, usually there is some event/action/condition that results in the change of height.
Watching that instead of meassuring the actual height is the way to go. Furthermore, it sounds like you are in fact trying to detect if the element is visible or not (and not really care about the height).

From what you said (and again...no demo...just saying), the element is shown/hidden as a result of an Angular expression bound to `ngShow`. If that is indeed the case, you should watch that same expression itself.

--
So, I am going to close this issue, as we seem to have pinpointed the cause of the observed behaviour and the Angular part works as expected (and documented).

Feel free to follow-up should you need any more clarifications.
You can also direct support/usage question to one of the [support channels][2].

[1]: https://github.com/angular/angular.js/blob/v1.4.2/src/ng/directive/ngShowHide.js#L172
[2]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem

**Closed by gkalpak** 2015-07-14 09:53 UTC
Labels: needs: more info
