### ISSUE TITLE
Error: 'name' getter called on an object that does not implement interface File.

### ISSUE THREAD

**Issue by shine60vn** [angular/angular.js#11484] opened 2015-04-02 02:51 UTC
Hi guys,
An error has occurred when I watch **deeply** an object that is implementation of [File interface](https://developer.mozilla.org/en/docs/Web/API/File). 

This is the error I have received
```
Error: 'name' getter called on an object that does not implement interface File.
equals@http://localhost:3000/assets/angular/angular-3c7181b1fa8efd68c9fcb7292e0d9281.js?body=1:932:15
equals@http://localhost:3000/assets/angular/angular-3c7181b1fa8efd68c9fcb7292e0d9281.js?body=1:932:16
equals@http://localhost:3000/assets/angular/angular-3c7181b1fa8efd68c9fcb7292e0d9281.js?body=1:917:18
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:3000/assets/angular/angular-3c7181b1fa8efd68c9fcb7292e0d9281.js?body=1:14303:31
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:3000/assets/angular/angular-3c7181b1fa8efd68c9fcb7292e0d9281.js?body=1:14572:13
timeout/timeoutId<@http://localhost:3000/assets/angular/angular-3c7181b1fa8efd68c9fcb7292e0d9281.js?body=1:16309:25
completeOutstandingRequest@http://localhost:3000/assets/angular/angular-3c7181b1fa8efd68c9fcb7292e0d9281.js?body=1:4925:7
Browser/self.defer/timeoutId<@http://localhost:3000/assets/angular/angular-3c7181b1fa8efd68c9fcb7292e0d9281.js?body=1:5313:7
```
Any idea for this issue?
Thanks

**Comment by pkozlowski-opensource** [comment] 2015-04-02 11:44
Sounds like a duplicate of https://github.com/angular/angular.js/issues/10524 - see the discussion in there. If you believe that this is not a duplicate, please provide a minimal reproduce scenario using plunker + provide other essential info to reproduce (ex. a browser and its version used). See: 
https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#submitting-an-issue

**Closed by pkozlowski-opensource** 2015-04-02 11:44 UTC
