### ISSUE TITLE
[1.4.9] $compile:nonassign error in directive

### ISSUE THREAD

**Issue by s-KaiNet** [angular/angular.js#13832] opened 2016-01-23 12:31 UTC
I created directive, isolated scope has a bi-directional binding `isOpen: '='`. In html I didn't set `is-open` attribute, but do it in a click handler. In that case $compile:nonassign error is thrown.   
Here the a simple plunk demonstrating the issue - [plunk](http://plnkr.co/edit/rMIG0zJpq5QTNpUSqPl2?p=preview)  (error is in console)

For version 1.4.8 all works good - here the same [plunk](http://plnkr.co/edit/OIf4qvoSBgF6noPZm2Ra?p=preview) but for 1.4.8 version.   
This can be fixed but making binding optional `isOpen: '=?'`, but is this a bug in 1.4.9 or not?

**Comment by gkalpak** [comment] 2016-01-23 14:05
This seems like an intentional change made in 7bb2414 (with a relevant test added in 45c5688) to fix #13367 (which is about a regression that was introduced in 1.4.0-beta.3 as part of 6a38dbf).

**Comment by wesleycho** [comment] 2016-01-23 14:25
I encountered this too when upgrading from 1.4.7 to 1.4.9 - that was actually the main reason I opened #13827.

While this is a regression, I think the proper fix is to indeed mark it with `?` because this involves setting two watchers internally if there is a two way binding, and it doesn't make sense to do so if the attribute isn't set.

**Comment by lgalfaso** [comment] 2016-01-25 10:02
A fix landed with 4ff9c02

**Closed by lgalfaso** 2016-01-25 10:02 UTC
Labels: branch: 1.4.x, component: $compile, component: $parse, needs: investigation, severity: regression, type: bug

**Comment by AckerApple** [comment] 2016-03-07 19:58
This issue breaks my 1.4.6 angular code. I can't go look at every single controller. I will just be putting a question mark after EVERY scope attribute just so I can move on without error.
