### ISSUE TITLE
Email Max Length Validation is Incorrect

### ISSUE THREAD

**Issue by kcjmowright** [angular/angular.js#15606] opened 2017-01-13 03:09 UTC
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

Report a *bug*.

**What is the current behavior?**

The default angular validation marks an email field invalid for anything longer than 128 characters.
0123456789012345678901234567890123456789012345678901234567890123@012345678901234567890123456789012345678901234567890123456789012 is the longest “valid” email address angular validation will allow on an input type email.  64 characters before the @ symbol and 63 characters after the @ symbol for a total of 128 characters.  

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

See http://plnkr.co/edit/Lb4vJq?p=preview

**What is the expected behavior?**

RFC 3696 specifies a maximum of 320 characters (octets) including separators.  RFC 3696 is supplanted by RFC 5321 which specifies 64 characters (octets) before the @ symbol or 255 characters after the @ symbol up to 256 characters total including separators ( See https://tools.ietf.org/html/rfc5321#section-4.5.3  ).  

**What is the motivation / use case for changing the behavior?**

The motivation for this behavior is to be able to support, at a minimum, a RFC 5321 compliant e-mail address.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

Angular 1.5.10 and the latest snapshot are affected by this issue.

It looks like the behavior changed starting with angular 1.5.7.  Prior versions supported longer email addresses.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by gkalpak** [comment] 2017-01-13 10:14
You _can_ have a valid e-mail that is longer than 128 chars:

```
<---------------------------------------------------------------------------------------------------------------------------- 254 --------------------------------------------------------------------------------------------------------------------------->
<----------------------------- 64 -----------------------------> <----------------------------- 63 ----------------------------> <----------------------------- 63 ----------------------------> <---------------------------- 61 --------------------------->
0123456789012345678901234567890123456789012345678901234567890123@012345678901234567890123456789012345678901234567890123456789012.012345678901234567890123456789012345678901234567890123456789012.0123456789012345678901234567890123456789012345678901234567890
```

The reason your address shows up as invalid is that in addition to the limitation in RFC 5321, there is an extra limitation wrt domain name "labels" (the parts of a domain name between the `.`) coming from [RFC 1035][1] (which is mentioned by RFC 5321).

The current EMAIL_REGEX implementation (which among other things imposes the length limits) is a result of f3f5cf7 (and the corresponding PR: #14719). There is plenty of discussion there about the reasoning of the changes as well as pointers to resources.

##
I am aware that the current REGEX may not be the ultimate email validation regex, but then again there is no such thing either :smiley:
We have tried to keep it reasonably close the RFC and I am happy with what we have. Keep in mind that it is just a (hopefully sane) default validation and users are [free to overwrite it][2], according to their needs.

##
I am going to close this now, since everything seems to work as expected (or at least as intended), but feel free to continue the discussion below.

[1]: https://tools.ietf.org/html/rfc1035
[2]: https://code.angularjs.org/1.6.1/docs/guide/forms#modifying-built-in-validators

**Closed by gkalpak** 2017-01-13 10:14 UTC
Labels: resolution: works as expected

**Comment by kamleshwebtech** [comment] 2019-09-19 13:51
How to validate an email address which character size is 320 (64 characters before '@', one character of '@' and 255 characters for domain name)? Kindly share your suggestion. Thanks a lot.

**Comment by tsasioglu** [comment] 2021-01-22 01:57
@kamleshwebtech There's some confusion around this, but an email address of 320 characters isn't valid according to the IETF. 254 is the maximum length.
https://stackoverflow.com/questions/386294/what-is-the-maximum-length-of-a-valid-email-address
