### ISSUE TITLE
bug(ngComponentRouter): Working code with Angular 1.5.0 breaks with 1.5.2

### ISSUE THREAD

**Issue by alexgoldstone** [angular/angular.js#14284] opened 2016-03-20 23:30 UTC
I declare $routerRootComponent like this:

```
(function() {
    'use strict';

    angular.module('app', ['app.config', 'ngComponentRouter', 'ngIdle', 'smart-table']);

    angular.module('app').config(function($locationProvider) {
        $locationProvider.html5Mode(true);
    });

    angular.module('app').value('$routerRootComponent', 'app');
})();
```

I then declare the first $routeConfig like this:

```
(function() {
    'use strict';

    angular.module('app').component('app', {
        controller: 'AppController',
        templateUrl: 'app.html',
        $routeConfig: [
            {path: '/user/login', name: 'Login', component: 'login', useAsDefault: true},
            {path: '/admin/...', name: 'Admin', component: 'admin'}
        ]
    });
})();
```

The above worked fine in Angular 1.5.0 but with Angular 1.5.2 I get this error:

```
Failed to instantiate module app due to:
TypeError: Cannot create property '$routeConfig' on string 'AppController'
    at http://localhost:3000/app.js:1:24483
    at p (http://localhost:3000/app.js:1:1052)
    at Bc.component (http://localhost:3000/app.js:1:24434)
    at d (http://localhost:3000/app.js:1:17190)
    at http://localhost:3000/app.js:1:17296
    at p (http://localhost:3000/app.js:1:863)
    at g (http://localhost:3000/app.js:1:17091)
    at db (http://localhost:3000/app.js:1:19121)
    at c (http://localhost:3000/app.js:1:7768)
    at xc (http://localhost:3000/app.js:1:8071
```

**Comment by gkalpak** [comment] 2016-03-20 23:50
Duplicate of #14279. This is indeed a bug/limitation - we're working on it.
<sub>(A temporary workaround is to not register component/directive controllers by name, but reference the actual function/Class itself.)</sub>

**Closed by gkalpak** 2016-03-20 23:50 UTC
