### ISSUE TITLE
input type=date .ng-valid-date stays after reset

### ISSUE THREAD

**Issue by ghost** [angular/angular.js#13587] opened 2015-12-18 21:20 UTC
Hello,

When I use Google Chrome with the input type date, there a cross that allow to reset the date.

I don't know if this is a bug or not since I'm very new to Angular but:

When I load the page, with the date set by the model to null
![date1](https://cloud.githubusercontent.com/assets/15908008/11907558/1ef28282-a5d5-11e5-9c9a-b731912c4f49.png)

When I set the day, month and year it has the .ng-valid-date class
![date2](https://cloud.githubusercontent.com/assets/15908008/11907561/28d72c08-a5d5-11e5-9812-b88409a80680.png)

When I click on this cross, it has still the .ng-valid-date class but it's null again
![date3](https://cloud.githubusercontent.com/assets/15908008/11907563/2d81c6be-a5d5-11e5-9342-5504f5118480.png)

**Comment by Narretz** [comment] 2015-12-19 22:56
Yes, that looks like a bug. Thanks for reporting.

**Comment by gkalpak** [comment] 2015-12-21 14:57
It seems that when the field is empty the field-type-specific class is not affected.

E.g. the same happens when clearing the date by deleting/unsetting each part (day, month, year).
In that case, the field is empty and valid, but the `ng-invalid-date` is still on the element.

**Comment by Narretz** [comment] 2016-01-02 16:02
This is actually an issue for all validators (even though date input does the validation inside $parsers with parseError). Validators can only return `true` or `false`, and if the input is empty, they return `true`. Basically, there's no extra flag for the emptiness of an input. So any validator that is applied to an empty input will return `true`.
This probably not an issue for most people, because I assume most developers use styles for invalid classes, not for valid classes. Otherwise I can't explain why this issue hasn't been raised before. In 1.5, you can use the `ng-not-empty` class in conjunction with the valid classes, so that your styles etc. only appear when there's input in your inputs.
@gkalpak do you think we should fix this behavior?
We could fix this with having validators return a third type for when the validation is undefined / doesn't apply.

**Comment by gkalpak** [comment] 2016-01-22 16:28
Revisiting this, I think the behavior described in OP's post is as expected for when clearing the field. Currently, there is the problem of not running the validation when partially editing the date fields, but it will be fixed with #12902.

The only thing that is a little weird (and probably needs further investigation) is the fact that (unlike other validators) the date validator does not initially add the `ng-valid-date` class when the field is empty. This is inconsistent, because other validators that I tried do set their valid classes immediatelly, but since the overall `ng-valid` class is set correctly, I am not too concerned about this.
I don't think the specific validator classes are that useful or that many people rely on them for something.

**Comment by gkalpak** [comment] 2016-12-23 11:41
Closing as a duplicate of #14740 (since that one has more discussion).

##
Note to self, wrt:

> The only thing that is a little weird (and probably needs further investigation) is the fact that (unlike other validators) the date validator does not initially add the ng-valid-date class when the field is empty.

The difference with other fields (e.g. `email`, `url` etc) is that `date` does not have a `date` validator; it relies on the default `$$parserName` validator (also named `date`). Other fields have `$validators` that match `$$parserName`.

**Closed by gkalpak** 2016-12-23 11:41 UTC
Labels: branch: 1.4.x, branch: 1.5.x, component: forms, severity: broken expected use, type: bug
