### ISSUE TITLE
ngChange fires before the model changes if the model and change function are passed in via a directive

### ISSUE THREAD

**Issue by nseegmiller** [angular/angular.js#11349] opened 2015-03-17 16:56 UTC
If you create a directive that wraps an input field and pass the change function and model to the directive and pass it along to the input field, the change function will fire before the model is updated. This behavior seems to have existed all the way back to 1.2 or even before. When ngModelOptions and updateOn: blur, it still calls the change function before the model is updated. I've created a pretty simple Plunker to demonstrate the issue.

http://plnkr.co/edit/2RLr1GxShY87FVvey4CT?p=preview

**Comment by Narretz** [comment] 2015-03-18 16:02
I think this is a duplicate of https://github.com/angular/angular.js/issues/4558

**Closed** 2015-03-18 16:07 UTC
Labels: component: forms, severity: broken expected use, type: bug
