### ISSUE TITLE
when use component inside 'p' tag- it places the html should be transcluded outside the 'p'

### ISSUE THREAD

**Issue by shootermv** [angular/angular.js#15838] opened 2017-03-21 14:49 UTC
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
My component uses two more inner components which should transclude some custom html
The first one acting properly , but the second - places the html should be transcluded outside the 'p' tag

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
http://plnkr.co/edit/ph7WPPgj1vZsX0dBh8jW?p=preview

**What is the expected behavior?**
should transclude some custom html and leave it inside the component

Tried this in chrome & ff browsers on windows and mac.

**Comment by gkalpak** [comment] 2017-03-21 14:57
Duplicate of #1459 (and several others). See [here][1] and [there][2] for explanations why this happens.
(Hint: It is the browser, not AngularJS.)

[1]: https://github.com/angular/angular.js/issues/1459#issuecomment-150607446
[2]: http://stackoverflow.com/questions/9852312/list-of-html5-elements-that-can-be-nested-inside-p-element#answer-9852381

**Closed by gkalpak** 2017-03-21 14:57 UTC
