### ISSUE TITLE
Model not updating when dynamic select element is manipulated via arrow keys

### ISSUE THREAD

**Issue by RodolpheGohard** [angular/angular.js#7042] opened 2014-04-08 11:36 UTC
**Steps**
1. have a select which all options are generated from ng-options
2. focus the select (but do not select any option yet)
3. type "T"
4. type "T" again

**What should happen?**
at step 3, the model should be "TN"
at step 4, the model should change to "TX"

*What happens and should not?*
at step 4, the model stays to "TX"

**Environment**
Chrome 33 , angular 1.2 or beta 1.3

**demonstration** (taken from https://github.com/angular/angular.js/issues/2230):
http://jsfiddle.net/ADukg/5116/
or http://plnkr.co/edit/2R9YM6KF01bye4kPeoZL?p=preview

**work around**
1. hard code the empty item `<option value="" />` inside the select
2. trigger a change event on keystrokes: `$(document).on( 'keyup', 'select', function(){$(this).trigger('change')} );`

**related**
* https://github.com/angular/angular.js/issues/4216
* https://github.com/angular/angular.js/issues/2230

**Comment by NateRedding** [comment] 2015-03-20 15:48
I am experiencing the same problem as well in Chrome X and Safari Y. I had just created a Plunker and was about to submit a ticket when I saw this one. Here's my Plunker. http://plnkr.co/edit/Zsb3iiGeoc2Ep0OyaWek

**Comment by vipin030** [comment] 2015-06-01 14:31
Now I'm facing the same problem, I don't think it is a problem related to browser. Is there any way to tackle this problem?

**Comment by gkalpak** [comment] 2015-06-01 21:03
@vipin030, could you elaborate why you don't think it is a browser-related problem ?

As explained elsewhere (and confirmed by @NateRedding), adding a explicit empty option solved the issue:

```html
<select ng-model="..." ng-options="...">
  <option value="">--- Select (or any text you like) ---</option>
</select>
```

**Comment by vipin030** [comment] 2015-06-02 14:02
@gkalpak , I have added the explicit option tag into my selection tag, but the problem is still exist, I have tested in firefox and chrome, it is not working in both.

I have developed the same by using javascript for testing purpose, it is working fine on both the browser.

**Comment by gkalpak** [comment] 2015-06-02 14:31
@vipin030, can you provide  the Angular code that is not working for you (or better yet provide a runnable demo, using CodePen, Plnkr, JSFiddle etc) ?

**Comment by vipin030** [comment] 2015-06-03 13:47
@gkalpak , please check the below plnkr example, it is not working for me, The browser which I have tested is Firefox 37.0.1. Please let me know your thoughts.
http://plnkr.co/edit/2xSGeVPc9sKUz2SCcbZz?p=preview

**Comment by gkalpak** [comment] 2015-06-03 16:44
@vipin030, I tried your demo on latest Chrome and Firefox and it works as expected.

--
Note that there is one difference between Chrome and Firefox in respect to when the select's value is changed:

1. Chrome updates the element's value as soon as a new option is selected.
2. Firefox updates the element's value only after the element is blurred.

The spec is somewhat unclear regarding that, stating that the value should be updated as soon as the user in done interacting with it, but it is a matter of interpretation.

This might be a source of confusion sometimes.

**Comment by vipin030** [comment] 2015-06-04 06:22
@gkalpak , Please check my demo code again 
http://plnkr.co/edit/2xSGeVPc9sKUz2SCcbZz?p=preview

You can see two selection box  there, second one using our pure javascript to show the value, it is working on every browser regardless of the version

Note:
Firefox also  updates the element's value as soon as a new option is selected.( Please check my demo and let me know why angular is not performing the same thing like pure javascript )

**Comment by gkalpak** [comment] 2015-06-04 08:41
@vipin030, both versions work as expected (each :smiley:).
The difference is that in your pure-JS implementation you use `onkeyup` (which is fired more consistently across browsers), whereas Angular is using `onchange` (which fires differently on FF vs Chrome).

If you want to update `onkeyup` instead of `onchange`, it is easy enough to write a custom directive that listens for the `keyup` event and triggers a `change` event:

```js
directive('changeOnKeyup', function changeOnKeyupDirective() {
  return function changeOnKeyupPostLink(scope, elem) {
    elem.on('keyup', elem.triggerHandler.bind(elem, 'change'));
  };
});
```

[Updated plnkr][1]

[1]: http://plnkr.co/edit/PcD55HqECuJrSC9usUFv?p=preview

**Comment by Narretz** [comment] 2015-08-13 18:52
Closing as dupe of https://github.com/angular/angular.js/issues/9134

**Closed by Narretz** 2015-08-13 18:52 UTC
Labels: component: forms, frequency: low, needs: investigation, severity: broken expected use, type: bug
