### ISSUE TITLE
1.5.0 rc1 issues with ng-if

### ISSUE THREAD

**Issue by diegope** [angular/angular.js#13817] opened 2016-01-22 07:43 UTC
When upgrading to Angular 1.5.0, we're noticing some issues with element directives that use ng-if at the root of their markup throwing exceptions (cannot find property childnodes of undefined). Moving the ng-if lower down into the template seems to fix this.

From my brief debugging of the issue, it seems that the compile function is pointing at a textNode when this occurs.

Is this a regression?

**Comment by gkalpak** [comment] 2016-01-22 09:12
@diegope, would you be able to put together a minimal demo (e.g. using CodePen, Plnkr etc) ?
It's hard to tell what the problem might be, without a reproduction.

**Comment by Narretz** [comment] 2016-01-22 10:18
@diegope Also, from which version did you update?

**Comment by diegope** [comment] 2016-01-22 16:01
We upgraded from 1.4.7 - I'm working on getting you guys an isolated repro of this. A couple additional things to things to note about our app in the meantime we have jQuery 2.2.0 loaded, and are also using the UI router.

**Comment by diegope** [comment] 2016-01-22 16:12
Here's a plunker illustrating the pattern I'm referring to:

https://plnkr.co/edit/TwrXsvf26645nZdb11xN?p=preview

**Comment by diegope** [comment] 2016-01-22 16:21
And a sample stack trace (these vary on the specific template that triggers the issue, but the "element" that triggers this is always a textNode):

UnhandledAngularException: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'. (caused by "                    ")
TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at TypeError (native)
    at getStyles (/dependencies.bundle.js:5649:15)
    at curCSS (/dependencies.bundle.js:5793:25)
    at Function.jQuery.extend.css (/dependencies.bundle.js:6192:10)
    at Object.jQuery.cssHooks.(anonymous function).get (/dependencies.bundle.js:6216:38)
    at Function.jQuery.extend.css (/dependencies.bundle.js:6187:16)
    at /dependencies.bundle.js:9743:13
    at access (/dependencies.bundle.js:3638:10)
    at jQuery.fn.(anonymous function) [as height] (/dependencies.bundle.js:9716:11)

I'm thinking this could be because we have indenting spaces in some of these templates that are somehow throwing off the compiler in the new version.

**Comment by Narretz** [comment] 2016-01-22 17:04
Am I correct that the plnkr doesn't show the problem yet?
It could be a problem with the priority of directives. Are you using ngMessages in your app?

**Comment by diegope** [comment] 2016-01-22 17:15
Correct, the plnkr just illustrates the pattern, still trying to get a repro outside of the application. And no, we are not currently using ngMessages.

**Comment by petebacondarwin** [comment] 2016-01-27 18:02
Without a reproduction we can't act on this issue, moving to 1.5.x

**Comment by Narretz** [comment] 2016-02-08 12:31
Closing due to lack of feedback / reproduction. Please reopen if you can provide more info.

**Closed by Narretz** 2016-02-08 12:31 UTC
Labels: branch: 1.5.x, component: misc core, needs: more info, severity: regression, type: bug
