### ISSUE TITLE
link orders are disturbed by `templateUrl` when compiled manually using `$compile`

### ISSUE THREAD

**Issue by gera2ld** [angular/angular.js#13616] opened 2015-12-23 03:16 UTC
There are three angular directives: `trans`, `foo`, `bar`.

* `trans` has an attribute of `{transclude: true}`.
* `foo` has a template of `<bar></bar>`.
* `bar` has a template of `<p>foobar!</p>`.

Think about creating a DOM like this dynamically using `$compile`:

    <trans>
      <foo></foo>
    </trans>

The expected link order is: `bar` -> `foo` -> `trans`.

* When I create the directives with `template` attributes, it works well.
* If the `$compile`'d template above is written in the DOM directly, it works well too.

**Problem:**

But when I use `templateUrl` and `$compile` manually, the link order becomes: `foo` -> `trans` -> `bar`.

It seems that `templateUrl` causes an asynchronous compilation for `bar`.

[Here](https://jsfiddle.net/gera2ld/n5y1aua3/3/) is the JsFiddle. (See console for the link orders.)

**Comment by gkalpak** [comment] 2015-12-23 11:56
This behavior is by design. `templareUrl` causes the compilation/linking to happen asynchronously, because we should freeze the rest of the view's compilation/linking while templates are being requested.
Thus, when using `templateUrl` there are no guarantees about the compilation/linking order.

I understand this can be inconvenient, but the pros outweight the cons.

Closing as it works as expected.

**Closed by gkalpak** 2015-12-23 11:56 UTC
Labels: component: $compile, resolution: works as expected
