### ISSUE TITLE
filter : textinput as results

### ISSUE THREAD

**Issue by FlamesoFF** [angular/angular.js#11085] opened 2015-02-17 09:07 UTC
```html
ng-repeat="person in persons | filter : text as filteredCollection | orderBy : 'name' | limitTo : 2"
```
Why this filter is not working? Here is no reserved names or something else which could conflict. Just not working. Without filter all is working properly.

persons = array;
text = input[type=text];

**Comment by pkozlowski-opensource** [comment] 2015-02-17 09:19
@FlamesoFF impossible to say without a clear, minimal, runnable reproduce scenario using plunker, jsbin, jsfiddle or similar. Please provide one - without it this issue is not actionable really...

**Comment by FlamesoFF** [comment] 2015-02-17 09:55
Here: http://jsfiddle.net/q0yfm6ap/

**Comment by pkozlowski-opensource** [comment] 2015-02-17 10:30
@FlamesoFF the reason is that `as [variable name]` is not an operator but rather a part of ngRepeat micro-syntax so it can be used only at the end (and not as operator, inside an expression), see:
http://jsfiddle.net/c2s7dLuj/

Closing, as it works as expected. If you want to capture intermediate results you can do so by moving filtering to a controller's function and do custom processing on the JS side.

**Closed by pkozlowski-opensource** 2015-02-17 10:30 UTC
Labels: component: filters, needs: more info

**Comment by FlamesoFF** [comment] 2015-02-17 10:33
Thanks, where I can find this in documentation?

**Comment by pkozlowski-opensource** [comment] 2015-02-17 10:38
https://docs.angularjs.org/api/ng/directive/ngRepeat

**Comment by gkalpak** [comment] 2015-02-17 10:58
Jut mentioning another alternative for capturing intermediate results in the view is:

    ng-repeat="p in (results = ps | filter : text) | orderBy : 'name' | limitTo : 2"
