### ISSUE TITLE
$http GET request not sending data (request body) when params is not sent 

### ISSUE THREAD

**Issue by Sinapsis-Innovation** [angular/angular.js#13022] opened 2015-10-06 17:12 UTC
we are consuming a service that retrieve data from a GET request, filtering the data by the request body sent by data parameter on the $http method, it works great when is sent along with the params parameter, but it does not work when params is not set or is sent as an empty parameter , any idea of how resolve this?

**Comment by pkozlowski-opensource** [comment] 2015-10-06 17:23
Get requests can't have body

**Comment by RyanDawkins** [comment] 2015-10-06 17:39
Could you post an example of code that you are doing?

**Comment by Sinapsis-Innovation** [comment] 2015-10-06 18:56
sure.

1. when I  sent the parameters, the call works fine.

var config = {
                   method: 'GET',
                   url: 'urlservice',
                   params: {paged:"true",pageSize:"1000",pageNumber:"1",orderBy:"ProjectNum"},                 
                   data: {projectStatus:["ON"]},
                   headers: {
                    'Authorization': 'Basic am1lamlhQGlhZGIub3JnOmExNjkwYmQ5ZWE0ZTRlMzlhODU1NWI5YzdmODFlZjIw',
                    'Content-Type': 'application/json; charset=utf-8'
                   }
        }

        $http(config).then(projectComplete, onError);


2. but, when call whitout parameters, the data is not sent

var config = {
                   method: 'GET',
                   url: 'urlservice',                                   
                   data: {projectStatus:["ON"]},
                   headers: {
                    'Authorization': 'Basic am1lamlhQGlhZGIub3JnOmExNjkwYmQ5ZWE0ZTRlMzlhODU1NWI5YzdmODFlZjIw',
                    'Content-Type': 'application/json; charset=utf-8'
                   }
        }

        $http(config).then(projectComplete, onError);

**Comment by gkalpak** [comment] 2015-10-06 20:30
I wonder if it is a browser things (rather than an Angular-thing).
@Sinapsis-Innovation , could you try with "raw" `XMLHttpRequest` and see if the same thing happens ?

**Comment by Sinapsis-Innovation** [comment] 2015-10-06 22:48
@gkalpak 
this code works great 

 var xhr = new XMLHttpRequest();
       xhr.onreadystatechange = callback;

       function callback() {
        if(xhr.readyState < 4){
          return;
        }
        if(xhr.status !== 200){
          console.log('problems');
          return;
        }
        console.log(xhr.responseText);
       }

       xhr.open('GET', 'http://mifservicest.iadb.org/Projects', true);
       xhr.setRequestHeader('Authorization', 'Basic am1lamlhQGlhZGIub3JnOmExNjkwYmQ5ZWE0ZTRlMzlhODU1NWI5YzdmODFlZjIw');
       xhr.send('{projectStatus:["ON"]}');

**Comment by gkalpak** [comment] 2015-10-07 07:07
I can't reproduce the issue with `v1.4.7` (see [demo pen][1]).

What version of Angular are you using, @Sinapsis-Innovation ?
Could you create a live reproduction of the problem (e.g. using CodePen, Plnkr etc) ?

[1]: http://codepen.io/ExpertSystem/pen/avWRRE?editors=001

**Comment by frfancha** [comment] 2015-10-07 09:25
@pkozlowski-opensource "Get requests can't have body"
In fact in the standard they can (at least nothing says they can't). But lot of servers and firewall implementation suppose they can't and drop them so using body in get request is a very bad idea.
@Sinapsis-Innovation Really, you shouldn't use body in your get request, you will have a lot of problems, not only with angular

**Comment by pkozlowski-opensource** [comment] 2015-10-07 09:32
> In fact in the standard they can (at least nothing says they can't). But lot of servers and firewall implementation suppose they can't and drop them so using body in get request is a very bad idea.

Well, this is a gray area at best... Same as with DELETE. 

But this is getting a bit academical as in practice sending body with GET request is a sure way of getting into funny pbs. I don't think angular should encourage this (and it would be kind of doing it if such option was added to the API)

**Comment by Sinapsis-Innovation** [comment] 2015-10-07 13:25
I appreciate so much all your time you guys put on this, and your fast answers, it seems like the best solution it´s change the service itself, so we will provide all this information to the person in charge of the web service to see how can he help us in this problem, but i´m totally agree with you, that is not a good idea sending body in GET request

**Comment by gkalpak** [comment] 2015-10-07 13:39
FWIW, Angular doesn't seem to be preventing you from sending GET requests with body (but you shouldn't do it regardless).

**Comment by gkalpak** [comment] 2015-10-07 13:40
I am closing this, since there is nothing actionable here.

**Closed by gkalpak** 2015-10-07 13:40 UTC
Labels: component: $http, frequency: low, needs: feedback

**Comment by UncleGena** [comment] 2016-11-18 13:51
[MDN](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/send)

> The XMLHttpRequest.send() method sends the request. If the request is asynchronous (which is the default), this method returns as soon as the request is sent. If the request is synchronous, this method doesn't return until the response has arrived. send() accepts an optional argument for the request body. **If the request method is GET or HEAD, the argument is ignored and request body is set to null.**
