### ISSUE TITLE
Angular 1.5.X dialog boxes not firing and return false

### ISSUE THREAD

**Issue by benbrownlol** [angular/angular.js#15024] opened 2016-08-14 21:24 UTC
**Do you want to request a *feature* or report a *bug*?**
A possible bug that occurs only on iPad Safari, seems to work as intended on all other browsers including iPhone Safari.

**What is the current behavior?**
When calling a dialog box such as `alert();` or `confirm();` after pressing the browser 'back' button the dialog does not fire and returns false.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
1. Go to fonts.google.com on an iPad using Safari with Remote Debugging enabled.
2. Open up the Safari Remote Dev Tools on your computer.
3. Type `confirm('TEST');` in the console and a Confirm Dialog Box will appear on the iPad.
4. Navigate to a different state using the navigation (e.g. Featured).
5. Type `confirm('TEST');` in the console and a Confirm Dialog Box will appear on the iPad.
6. Press the native safari back button to go back to the index page.
7. Type `confirm('TEST');` in the console and a Confirm Dialog Box will **not** appear on the iPad and false will be returned inside the console.

**What is the expected behavior?**
Dialog box should appear and true **or** false should be returned depending on user input.

**What is the motivation / use case for changing the behavior?**
Stop angular.js interfering with native JavaScript behaviour

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
Only tested on Angular 1.5.0 & Angular 1.5.8

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
n/a

**Comment by gkalpak** [comment] 2016-08-14 22:01
What makes you think it is an Angular issue?

**Comment by benbrownlol** [comment] 2016-08-14 22:11
I've tried it on 4 separate angular apps after spending almost 8 hours today taking my app apart a day before we go live thinking it was an issue I had created. ( 1 created by me, 3 random apps off the web including fonts.google.com )

But you're right it could be an issue caused by a shared dependency of all 4 apps like ui-router or something commonly used. I'll look into this tomorrow.

**Comment by Narretz** [comment] 2016-09-05 19:48
I'm going to close this issue because we have no reproduction of the issue. Feel free to reopen this issue if you can provide a reproduction (ideally a runnable demo in a https://plnkr.co or similar. You can use this [Plunker Template](http://plnkr.co/edit/tpl:yBpEi4)).

**Closed by Narretz** 2016-09-05 19:48 UTC
Labels: browser: Safari, needs: more info
