### ISSUE TITLE
ngRoute incorrectly matching route when URL contains unencoded slash

### ISSUE THREAD

**Issue by roryf** [angular/angular.js#11858] opened 2015-05-12 10:20 UTC
Given a route config
```js
$routeProvider
  .when('/foo', { /* etc. */ })
  .when('/bar', { /* etc. */ });
```

A URL with a query parameter containing an unencoded forward slash will incorrectly match the second route: `http://example.com/foo?q=/bar`.

Unsure if this is a bug or by design, but it seems contradictory to the [URI spec](https://tools.ietf.org/html/rfc3986#section-3.4):

> The characters slash ("/") and question mark ("?") may represent data
   within the query component. ... it is sometimes better for usability to avoid percent-
   encoding those characters.

**Comment by petebacondarwin** [comment] 2016-01-20 12:33
I can't reproduce this in a unit test:

```js
  iit('should correctly match a route that contains forward slashes in the query', function() {
    module(function($routeProvider) {
      $routeProvider.when('/foo', {templateUrl: 'foo.html'});
      $routeProvider.when('/bar', {templateUrl: 'bar.html'});
    });

    inject(function($route, $location, $rootScope) {
      $location.url('/foo?q=/bar');
      $rootScope.$digest();
      expect($route.current).toBeDefined();
      expect($route.current.templateUrl).toEqual('foo.html');
    });
  });
```

This test passes.

@roryf can you provide a running example of this failing?

**Comment by roryf** [comment] 2016-01-20 15:51
Thanks @petebacondarwin, some debugging suggests the issue is with `$location` however I'm struggling to create an isolated test case. I'll update this when I get further.

**Comment by gkalpak** [comment] 2016-06-01 13:15
Closing. Feel free to re-open if you manage to get a reproduction.

**Closed by gkalpak** 2016-06-01 13:15 UTC
Labels: component: ngRoute, needs: investigation, severity: broken expected use, type: bug
