### ISSUE TITLE
$http does not resolve the same local file twice (Chrome 52,54)

### ISSUE THREAD

**Issue by Chexpir** [angular/angular.js#14865] opened 2016-07-04 12:50 UTC
`angular.module('plunkerTemplate', [])
  .run(['$http',  '$q', function ($http) {
        console.log('Init');
        $http.get('sample.json').then(function () {
		      console.log('In progress...');
          $http.get('sample.json').then(function (jsonData) {
            console.log('Done!');
          }); 
    });
}]);
`

**What is the current behavior?**
Current behaviour on Chrome >= 52 is that the second promise does not get resolved, only the first one.
http://http://plnkr.co/edit/DF7AcC

Be aware that:
- it does not fail in all the executions. There might be executions where it starts working after 
some modifications.
- It happens when the file is served locally and in HTTP, not HTTPS.
- it happens when resolving the same file twice, but I couldn't get it working with the index.html file, only with js/json files, so might be some security-related code involved?

**What is the expected behavior?**
I will expect to behave as in Chrome 51, resolving the file twice.

**What is the motivation / use case for changing the behavior?**
We have this code implemented, with the second retrieval further in time than in the example (so file can potentially change between requests).

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
It affects Angular 1.3, 1.4, 1.5 in Chrome 52, 53, 54. I use windows 7.

**Comment by Chexpir** [comment] 2016-07-04 13:15
I am closing the issue not to lose your time, as I can't reproduce it on plunkr https://plnkr.co/edit/kcHR1S?p=preview

**Comment by Narretz** [comment] 2016-07-04 14:00
This definitely sounds a like serious issue. However, I cannot reproduce it in the latest canary build. It sounds like a Chrome bug, though. So maybe they fixed it? Current version is 51 ... and we don't support beta / dev / canary channels officially.

**Comment by Chexpir** [comment] 2016-07-04 14:05
Yes, in my app we don't officially support them, but we'll all have to support Chrome52 in a couple of days, so let's call it preventive support :+1: I'll ask somebody with a non-windows OS to test it, as I continue reproducing it when opening an incognito window.

**Comment by Narretz** [comment] 2016-07-04 14:18
Does it only reproduce in an incognito window?
And does the iframe in the plnkr make a difference? Does it only reproduce in an iframe?

**Comment by Narretz** [comment] 2016-07-04 14:31
So I've also tested with Version 52.0.2743.60 (incognito off / on) and I still cannot reproduce it in the plnkr

**Comment by Chexpir** [comment] 2016-07-04 15:03
I had simplified the plunker further and it does not require iframes, so the description we have should apply and should be reproducible but:
- I have tested now on the latest beta Version 52.0.2743.60 beta-m (64-bit) and it is not reproducible
- It is reproducible in Version 54.0.2787.0 canary (64-bit)

So you can close it, and we'll reopen if it's still reproducible once 54 reachs beta.

**Comment by Chexpir** [comment] 2016-07-04 15:09
![bug_angularjs2](https://cloud.githubusercontent.com/assets/4041868/16564829/99e23b2c-4201-11e6-9b4a-e0ed16ac3e4e.gif)
Attaching a videogif to show it's happening, and that in a second run it does work, is in the first run when it fails.

**Comment by gkalpak** [comment] 2016-07-04 15:38
In any case, this doesn't sound like an Angular-specific issue at all. Have you tried reproducing this with raw `XMLHttpRequest`?

**Comment by Chexpir** [comment] 2016-07-08 11:16
gkalpak. I agree with you. It does not sound like Angular specific. I have opened a defect on Chromium though. https://bugs.chromium.org/p/chromium/issues/detail?id=625656#

**Comment by gkalpak** [comment] 2016-07-08 11:26
I would try to reproduce it with raw `XMLHttpRequest` first. It is much easier for Chromium people to investigate a reported issue if it has less moving parts and doesn't rely on external things like frameworks.

**Comment by gkalpak** [comment] 2016-07-08 11:34
So, I am going to close this anyway, since there is no evidence that this is related to Angular.
Feel free to re-open if you can prove me wrong :stuck_out_tongue: 

Thx for the Chromiu issue link btw :+1:

**Closed by gkalpak** 2016-07-08 11:34 UTC
Labels: browser: chrome, component: $http, needs: more info

**Comment by Chexpir** [comment] 2016-07-11 14:08
Hi, I can't reproduce it using plain XHR and I don't know what's the underlying mechanism and/or its reusability in angular.js to replicate it. http://plnkr.co/edit/RJlyNW?p=preview
So I feel the defect in Chromium is not going to be accepted. I feel the error is in Angular.js.
pofficial release date is 26th July and I feel we should work on the issue. 
tbh, I have solved the issues in my product adding a query parameter to the 2nd call, but I'd like to help you diagnosing and solving it. Can you point me to your XHR wrapper?

**Comment by Narretz** [comment] 2016-07-11 14:15
The wrapper is here: https://github.com/angular/angular.js/blob/master/src/ng/http.js

**Comment by tielur** [comment] 2016-08-15 20:10
I'm experiencing this same behavior using $resource in my angular app as well.

**Comment by gkalpak** [comment] 2016-08-17 13:08
`$resource` is a wrapper around `$http`, which is a wrapper around the native `XMLHttpRequest`. This is not related to Angular afaict. It seems to be related to [this bug][1].

[1]: https://bugs.chromium.org/p/chromium/issues/detail?id=633696

**Comment by alexw23** [comment] 2016-08-18 00:44
Any temporary fixes to this bug? It is a chrome issue - firefox works fine, and our customers only started finding an issue a few weeks ago (when v52 was launched)

**Comment by gkalpak** [comment] 2016-08-18 12:37
This is indeed not Angular-related. Follow Chromium bugs [633696][1] and/or [636699][2] for more info.

Afaict, disabling ETag support or avoid making a request from within another requests success callback (e.g. wrapping it in a `$timeout`) might help as a temporary work-around (I am not sure though).

[1]: https://bugs.chromium.org/p/chromium/issues/detail?id=633696
[2]: https://bugs.chromium.org/p/chromium/issues/detail?id=636699

**Comment by Chexpir** [comment] 2016-09-09 08:40
Defect fixed in Chromium.
https://bugs.chromium.org/p/chromium/issues/detail?id=633696#c36

The fix is included in:
53.0.2785.101 or later
54.0.2840.0 or later
55.0.*
Not included in:
53.0.2785.89
