### ISSUE TITLE
$parse error when model property contains 00

### ISSUE THREAD

**Issue by igorcosta** [angular/angular.js#10670] opened 2015-01-07 12:59 UTC
There's a very strange behavior while updating to angular 1.3.8 from 1.2.28

I have a model delcared as follow ng-model="userModel.00NDtWO00" in my ng-model attribute.

If you declare something like that in 1.2.28 no errors appear, but after I updated to angular 1.3.8.

I was trying to debug but turns out I'm out of options, couldn't fine a better answer to that.

Is something releated to this? Due to bdfc9c02 

Any help to understand this I must appreciate.

**Comment by Narretz** [comment] 2015-01-07 14:23
This sounds odd. What is the error message? You could try to isolate the first version where this change happens - going back version by version (including betas).

**Comment by igorcosta** [comment] 2015-01-07 15:35
Very odd.

I've tried to run over 1.3.5 ..6 ..7 

Error: [$parse:syntax] Syntax Error: Token '.00' is an unexpected token at column 14 of the expression [CadastroModel.00Ni000000DToGw] starting at [.00Ni000000DToGw].
http://errors.angularjs.org/1.3.8/$parse/syntax?p0=.00&p1=is%20an%20unexpected%20token&p2=14&p3=CadastroModel.00Ni000000DToGw&p4=.00Ni000000DToGw
    at http://localhost:9000/bower_components/angular/angular.js:63:12
    at Parser.throwError (http://localhost:9000/bower_components/angular/angular.js:11998:11)
    at Parser.parse (http://localhost:9000/bower_components/angular/angular.js:11951:12)
    at $parse (http://localhost:9000/bower_components/angular/angular.js:12659:39)
    at new NgModelController (http://localhost:9000/bower_components/angular/angular.js:20390:23)
    at Object.invoke (http://localhost:9000/bower_components/angular/angular.js:4182:17)
    at extend.instance (http://localhost:9000/bower_components/angular/angular.js:8441:21)
    at http://localhost:9000/bower_components/angular/angular.js:7693:13
    at forEach (http://localhost:9000/bower_components/angular/angular.js:331:20)
    at nodeLinkFn (http://localhost:9000/bower_components/angular/angular.js:7692:11) <div ng-view="" class="ng-scope">

**Comment by lgalfaso** [comment] 2015-01-07 16:36
Replace any reference you have with userModel['00NDtWO00']

**Comment by igorcosta** [comment] 2015-01-07 16:39
Really can't figure out how, but after evaluate as a function, it worked.

ex: var simple_var = 'ModelName.00Undit3030';
var model = $parse(simple_var);
model.assign($scope,300);
console.log($scope.ModelName.00Undit3030);
//300

**Comment by igorcosta** [comment] 2015-01-07 16:40
@lgalfaso problem Lucas those variables are related to Sales force, can't ignore. I created a workarround that. Worked, but it's buggy, and I can't find where.

**Comment by lgalfaso** [comment] 2015-01-07 16:44
You only need to replace them on templates and when using $parse

**Comment by igorcosta** [comment] 2015-01-07 16:46
Yep, just did that. Funny part you just figure out those problems when you apply Falsy variables on model update. And odd it's working directly with $parse, not the other way around. 

Anyhow I really appreciate the efforts.

**Comment by Narretz** [comment] 2015-01-07 17:00
@lgalfaso Do you know what change causes this to fail?

**Comment by pkozlowski-opensource** [comment] 2015-01-07 17:35
@Narretz @lgalfaso regardless of what is the root cause of this thing in a parser right know the question is - do we want to make this possible given that doing `window.00NDtWO00 = 'foo';` in pure JS will fail with:
> Uncaught SyntaxError: Unexpected token ILLEGAL

at least in Chrome?

I'm not sure it makes sense / it is worth to try to support this use-case as we would deviate from what JS does and we could better invest this time elsewhere....

**Comment by igorcosta** [comment] 2015-01-07 17:51
@pkozlowski-opensource Yep, same on JS and happens as well in firefox and opera.

Turns out Sales force could evaluate their way to support variable nomenclature.

IMHO is not worth a dime to support such a thing.

**Comment by pkozlowski-opensource** [comment] 2015-01-07 17:54
@igorcosta glad that you are with me on this one. Yeh, while there is still a work-around (`window['00NDtWO00' = 'foo';`) this could be a pain in a neck if one needs to access those variables frequently.

Going to close this one as "won't fix" for now.

**Closed** 2015-01-07 17:55 UTC
Labels: component: $parse, resolution: won't fix
