### ISSUE TITLE
Invalid target element for this operation in IE9

### ISSUE THREAD

**Issue by wikimo** [angular/angular.js#13299] opened 2015-11-13 06:47 UTC
How about "Invalid target element for this operation" in IE9， angular 1.4.1， 
the error happend in code like this

```
<tr ng-repeat="item in data.items  | filter:query " ng-include="item.is_query ? 'views/user/query.show.html':'views/user/query.item.html'"></tr>
```

search with google get some info 
- innerHTML is read only in tbody so the error happend
- http://stackoverflow.com/questions/4729644/cant-set-innerhtml-on-tbody-in-ie
- http://stackoverflow.com/questions/28316096/invalid-target-element-for-this-operation-ngtable
- https://github.com/esvit/ng-table/issues/667

say there is no resolution.

what should i do, thanks for your help.

**Comment by Narretz** [comment] 2015-11-13 14:03
There's not much that can be said without a demo of the problem. The only thing I can say is that manipulating `<table>`  elements and their contents is difficult, because the browser HTML parser is very strict with regards to them.

**Comment by wikimo** [comment] 2015-11-15 05:48
demo: http://dev.cmcm.us/,

error Invalid target element for this operation   "<tr class="ng-scope" ng-include="'views/home/tr.html'" ng-repeat="item in items"> 
" in ie 9

**Comment by Narretz** [comment] 2015-11-29 17:52
I have read the stackoverflow and the github issue for ngTable. If the problem is with jqlite, you could open a PR that changes the implementation to match that of jquery.

**Comment by mgol** [comment] 2018-03-29 08:06
Without a small isolated test case it's hard to work on an issue. Taking that into account as well as age of this ticket, the closeness of the maintenance mode of jqLite and the fact it only affects IE 9 I'm going to close this.

**Closed by mgol** 2018-03-29 08:06 UTC
Labels: browser: IE9, component: $compile, component: jqLite, needs: investigation
