### ISSUE TITLE
mocks.$httpBackend uses mocks.$timeout to control asyncronous requests, which causes $timeout.verifyNoPendingTasks to fail unless an extra $timeout.flush(0) is called

### ISSUE THREAD

**Issue by deignacio** [angular/angular.js#7492] opened 2014-05-16 22:12 UTC
Hey-

I'm trying to add in retry logic to an angular module that makes $http requests.  My approach uses $timeout to allow for a delay between attempts.  When writing unit tests for this module, I find that an extra $timeout.flush(0) is required to make $timeout.verifyNoPendingTasks() succeed.  

Digging into ngMock, it looks like this is due to $httpbackend using $timeout to wrap responses and make then asyncronous.
https://github.com/angular/angular.js/blob/master/src/ngMock/angular-mocks.js#L1117

I have a gist that shows the failure and success once you include $timeout.flush(0)

https://gist.github.com/deignacio/c50787980fbee4c3d1db

Is there any way to decouple the two services to not require this extra flush?

**Comment by mbarakaja** [comment] 2016-03-28 16:55
I am facing this same issue.

In my case, I'm using **`$timeout`** to call a function that makes use of the  $http service. Before I flush everything and call **`$timeout.verifyNoPendingTasks();`** and error like next appears:
```javascript
Error: Deferred tasks to flush (1): {id: 2, time: 109999}
```

I need an extra call to **`$timeout.flush`** to empty the Deferred task remaining.

**Comment by gkalpak** [comment] 2016-03-29 08:57
It's been a long time since the original post, so not sure what where the roots of the problem back then (but I know what causes it now :smiley:). BTW, if anyone is curious, I put the code into a runnable demo [here][1].

I'm closing this issue in favor of #14336, where I have described the actual problem (and some background).

--
@mbarakaja, I am not sure your problem is the same (I am kind of buffled by `time: 109999`).
If you are confident it is the same issue, then let's track this in #14336. If not, please sublit a new issue providing sufficient details to reproduce the problem (a live demo works best :stuck_out_tongue:).

[1]: https://codepen.io/ExpertSystem/pen/ZWJYdj?editors=001

**Closed by gkalpak** 2016-03-29 08:57 UTC
Labels: component: $http, component: ngMock, frequency: moderate, needs: investigation, severity: confusing, type: bug
