### ISSUE TITLE
Programmatically triggering a 'click' events does not work inside ng-repeate, when using external jQuery library

### ISSUE THREAD

**Issue by smlz** [angular/angular.js#3470] opened 2013-08-05 14:43 UTC
When
- using the full jQuery library inside Angular.js (as opposed to the built-in jQLite lib)
- and triggering a 'click' event on a radio button inside a ng-repeate programmatically with jQuery

the model does not get updated, even though the effects of selecting the radio button are visible on the screen,.

However, 
- manually clicking on the radio button
- or programmatically triggering the 'click'-event twice (`$('input[name=test]').trigger('click').trigger('click')`)

does give the expected results.

For full demo of the problem see the following jsfiddle: http://jsfiddle.net/MpyFW/8/

Being able to programmatically trigger events would be quite usefull for automated testing.

**Comment by jthibeaux** [comment] 2015-02-16 18:27
I have noticed this problem in 1.2.28 (not ready to upgrade to 1.3) when running specs under Chrome 40 (have not tried elsewhere yet).  Resolving by simply clicking twice:
```
element.find('input[type=radio][value=1]').click().click()
```
This seems to be a problem unique to radio, as a similar checkbox control works fine with one click().

**Comment by eknuth** [comment] 2015-03-05 19:18
We are seeing this issue with checkboxes in 1.3.14.  We weren't seeing it in 1.2.18.  These are checkboxes with an ng-change.

**Comment by cadilhac** [comment] 2015-04-30 14:25
FYI, I also get this issue but just under IE11, not under latest versions of chrome and firefox. It concerns only radio buttons since I checked that it works well with checkboxes. I'm using angular 1.3.14. I think this was working with angular 1.2.x but not sure.
Calling click() twice fixes the issue (this is called from a jqeru 'on' handler).

**Comment by Narretz** [comment] 2015-08-15 15:19
The problem is that after `trigger` is executed, the checked property is not yet set inside the click callback of the radio.

**Comment by mastepan** [comment] 2016-03-07 09:59
Similar issue is there with checkbox. 
- If I `element.trigger('click')` once, checkbox state is visually changed but model doesn't change accordingly. 
- If I "click" twice, model uptates after 2nd click but the checkbox is in it's initial state unlike radiobutton. 
- If I "click" 3 times, model is updated and the checkbox has proper state

But If I want to click (as it was clicked by user (not speaking of 3times triggering click in code)) the checkbox once, then check something and then click it 2nd time, this serie of 3 click triggerings behaves probably as if The click has been triggered 6 times and that doesn't give desired result.

**Comment by Narretz** [comment] 2017-10-14 12:45
I cannot reproduce the original issue in 1.3.0 and above, see http://plnkr.co/edit/1wE6wrCAZ9wwPryIElep?p=preview
I also saw no issues with checkbox

Any other issues mentioned in this thread must be different from the original issue. If there are still issues, please open a new issue with a repro.

**Closed by Narretz** 2017-10-14 12:45 UTC
Labels: component: forms, severity: inconvenient
