### ISSUE TITLE
Angular tutorial step 06: using src attribute for img tag behaves correctly

### ISSUE THREAD

**Issue by Zion-ICS** [angular/angular.js#11540] opened 2015-04-09 21:29 UTC
`Replace the ng-src directive with a plain old src attribute. Using tools such as Firebug, or Chrome's Web Inspector, or inspecting the webserver access logs, confirm that the app is indeed making an extraneous request to /app/%7B%7Bphone.imageUrl%7D%7D (or /app/{{phone.imageUrl}}).`

I found the opposite to be true. Both src and ng-src showed the correct image in Windows Firefox and IE. Using Firefox's inspector, I found images such as `<img src="img/phones/dell-streak-7.0.jpg">`.
See https://code.angularjs.org/1.3.15/docs/tutorial/step_06

**Comment by pkozlowski-opensource** [comment] 2015-04-11 08:37
@Zion-ICS you might be wrongly interpreting what you are seeing - the images will, _eventually_, display correctly and the `src` attribute will be updated to a correct value. The problem is that a browser will also pick up an _invalid_ value (with interpolation brackets) and will issue an invalid HTTP request. This is the crux of the pb and this is what the tutorial is trying to point out.

I'm going to close this one as I believe that the tutorial is correct. But please fell free to re-open if you believe that some browsers (and here we would need exact details) don't issue invalid HTTP requests.

**Closed by pkozlowski-opensource** 2015-04-11 08:37 UTC

**Comment by Zion-ICS** [comment] 2015-04-13 13:14
Thank you very much for your very informative and very prompt response!
