### ISSUE TITLE
"Value" of progress element does not bind in IE11

### ISSUE THREAD

**Issue by omarmeky** [angular/angular.js#12322] opened 2015-07-10 15:21 UTC
If I do something like:

`<progress max="100" value="{{progress}}"></progress>`

It displays correctly on browsers besides IE11 (haven't tested older versions of IE). On IE11, it always evaluates to "0"

I am using my own directive to bypass this issue:

`<progress max="100" progress-bar-value="progress"></progress>`

```
.directive('progressBarValue', ['$parse', function($parse) {
            return {
                restrict: 'A',
                link: function(scope, elem, attrs) {
                    scope.$watch(attrs.progressBarValue, function() {
                        elem.attr('value', $parse(attrs.progressBarValue)(scope));
                    });
                }
             };
         }]);
```

**Comment by langdonx** [comment] 2015-07-10 17:20
Funny, I was just dealing with something similar myself.  It seems like standard attributes with interpolation have issues in IE11.

Your issue in a Fiddle: http://jsfiddle.net/langdonx/6qcs6yee/

Related issue I filed a moment ago: https://github.com/angular/angular.js/issues/12324

**Comment by Narretz** [comment] 2015-07-10 17:49
There's also `ngValue`, which should work for this use-case, too.

**Comment by Narretz** [comment] 2015-07-10 17:49
Closing as dupe of #7218

**Closed by Narretz** 2015-07-10 17:49 UTC
