### ISSUE TITLE
Email address validation fails on single character local-part email addresses

### ISSUE THREAD

**Issue by cmcardle75** [angular/angular.js#13399] opened 2015-11-27 15:51 UTC
The email validation regular expression requires the local part of an email address (before @) to be at least 2 characters. This is not compliant with RFC822, which clearly permits a single "atom" to form a "local-part".

Motivation:
It meant I couldn't log into Ryanair's website today as they've recently rolled out angular email validation to their login page and my email address is the shortest RFC822 compliant address I could afford as I'm very lazy. This is the first website I've encountered that has refused my email address, so limiting at least 2 characters is not common.

Version:
Unknown. I couldn't find it in the page source for Ryanair's website.

Browsers:
All tried (recent Firefox/Chrome/IE)

Reproduce:
Go to ryanair website (or any Angular site using email address validation). Attempt to login using an email address with only a single atom before the @ symbol. There's no need for the account to exist (or even possibility if you hadn't created one already). Input field will show red with client side validation failure.

Suggest a fix:
Modify the regular expression used to validate email addresses to be compliant with RFC822, which is very permissive of the local-part of an email address, allowing all but a small selection of symbols.

**Comment by gkalpak** [comment] 2015-11-27 17:34
This has nothing to do with Angular. (They are using Angular `v1.4.6` btw, but this is irrelevant.)

If you examine the field, you will see that they are applying a `validEmail` directive.
This directive is defined in `etc/designs/ryanair/frontent.<some_hash>.js` and (among other things) uses the following regexp to vaidate the entered e-mail address:

```js
/^[\sA-Z0-9._%+-]+[A-Z0-9]+@[A-Z0-9]+[A-Z0-9.-]+\.[A-Z]{2,4}[\s\t]*$/i
  \______________/\_______/\...
         |            |
   At least one       |
   of these chars     |
                      |
               And at least one
               of these chars
```

Hence the error.

--
Closing as the issue is not related to Angular.

**Closed by gkalpak** 2015-11-27 17:34 UTC
