### ISSUE TITLE
Inconsistent in en_US localization

### ISSUE THREAD

**Issue by tdrozdz** [angular/angular.js#12134] opened 2015-06-16 12:39 UTC
Hi, during development on localizations I've noticed that in core angular code localization for ```en_US``` looks different than in a file with localizations exposed as bower dep.

value in angular core
https://github.com/angular/angular.js/blob/291d7c467fba51a9cb89cbeee62202d51fe64b09/src/ng/locale.js#L36

value in bower dep
https://github.com/angular/bower-angular-i18n/blob/master/angular-locale_en-us.js#L118

I'm not sure which one is correct so don't want to create PR but would be great if we could have the same value in both cases.

**Comment by lgalfaso** [comment] 2015-06-16 14:30
This looks like a valid bug. Thanks for reporting this.

If someone wants to put together a PR, it would be ideal. If not I will look into this before the next release

**Comment by petebacondarwin** [comment] 2015-07-16 11:36
It seems weird that we have a "sort-of" duplicate of the en-us locale inside the `ng` module.
If we just copied the `ngLocale` module for `en-us` into the angular.js file, we would lose 400 bytes (pre-zip) but we would gain consistency and also get rid of that annoying caught error during bootstrap, where it says that `ngLocale` is missing.

**Comment by petebacondarwin** [comment] 2015-07-16 13:57
I have a fix for this #12362

**Closed** 2015-07-16 18:20 UTC
Labels: component: $location
