### ISSUE TITLE
Cannot load component from browser even after setting url rewrite 

### ISSUE THREAD

**Issue by csfanse** [angular/angular.js#14831] opened 2016-06-27 08:52 UTC
I am using angular 1.5 component and component routing with Typescript. I am not able to reload component after refresh. Before configuring URL rewrite, I was getting 404 error but after configuring URL rewrite, neither I am getting any error nor the component is loaded. I just get "blank" white screen after pressing F5. The application is configured in IIS and URL rewrite module for IIS is also installed. I investigated from inspect element and found that ng-outlet is not loaded.
Below is the configuration for URL rewrite in web.config.

     <rewrite>
      <rules>
        <rule name="angularjs routes" stopProcessing="true">
          <match url=".*" />
          <conditions logicalGrouping="MatchAll">
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
            <add input="{REQUEST_URI}" pattern="^/(Mdrx.CAL.API)" negate="true" />
          </conditions>
          <action type="Rewrite" url="/" />
        </rule>
      </rules>
     </rewrite>

If I set type="Redirect", it redirects to start page which is fine but does not work in case of "Rewrite"

What is the issues..?

**Comment by gkalpak** [comment] 2016-06-27 09:10
It is impossible to say what might be wrong without more info. This is possibly an IIS configuration issue and we can't help you with that.

If you were able to provide a reproduction of the issue (e.g. using CodePen, Plnkr etc) or at least point to a live app that demonstrates the problem, we could investigate further.

**Comment by joshinisarg** [comment] 2016-07-06 09:16
Issue occurs when we manage routes dynamically.

Let me try to explain issue.

1) Root component : **app**
2) **app** has two routes : Login and Home
3) Login is terminal route while Home has children routes.
4) Login is default route for **app**
5) From login, we navigate to Home 

`login()
        {

            
            this.CalRoutes = this.RouteService.getRoutes();
            this.$router.registry._rules.set('home', null);
            this.CalRoutes.forEach((route) => {
                if (!this.$router.registry.hasRoute(route.name, 'home'))
                    this.$router.registry.config('home', route);
            });

            this.$router.navigate(['Home']);
        }`

This works fine in normal scenarios. But when we are at http://localhost:49750/home/child2 and do F5 (browser url re-load), components are not getting loaded properly. There is no error reported either.

**Comment by gkalpak** [comment] 2016-07-06 10:13
I still do not understand your code 100% (it would help if you created a runnable demo), but you seem to be using undocumented and private stuff (e.g. `_rules`), so I am not sure the usecase is supported (not to mention that this version of the router has been deprecated and it is unlikely to see further development atm).

Also, the fact that this works if your change your server config to redirect instead of rewrite makes me think it is still related to some configuration issues (although without a reproduction I am not sure if it is on the server or on the client).

**Comment by Narretz** [comment] 2016-07-14 13:24
I'm going to close this issue because we haven't got any feedback. Feel free to reopen this issue if you can provide new feedback.

**Closed by Narretz** 2016-07-14 13:24 UTC
Labels: component: component router, needs: more info, severity: broken expected use, type: bug
