### ISSUE TITLE
When we click Ctrl+"Edit in Plunker" button, the Plunker is not opening in new tab.

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [angular/angular.js#10641] opened 2015-01-05 05:34 UTC
When we click Ctrl+"Edit in Plunker" button, the plunker is not opening in new tab, instead it is  opening the plunker in the same tab. But when we click Ctrl+edit in plunker button, it should open in the new tab, which is not happening as of now. And because of it we are unable to stay in the same page to refer the docs.

**Comment by arpit2438735** [comment] 2015-01-05 06:14
It's very specific to Browser.It's not a issue with Angular website,can you retest the same scenario with different site probably [Stackoverflow](http://stackoverflow.com)

**Comment by rajeshwarpatlolla** [comment] 2015-01-05 11:02
When i click Ctrl+"Edit in Plunker" in  "angular-ui.github.io/bootstrap/", the plunker is opening in a new tab. But this is not happenning in "angularjs.org". In "angularjs.org", when i do the same the plunker is opening in the same tab.

**Comment by arpit2438735** [comment] 2015-01-05 11:15
Ok that fine but this forum is not for website bug it is specific to angular.js code.You can post the bug to https://github.com/angular/angularjs.org

**Comment by pkozlowski-opensource** [comment] 2015-01-05 16:57
Closing as duplicate of https://github.com/angular/angularjs.org/issues/149

**Comment by jeffbcross** [comment] 2015-01-08 21:39
Reopening, as the code for this is actually in angular.js, not angularjs.org: https://github.com/angular/angular.js/blob/master/docs/config/templates/runnableExample.template.html

**Comment by ghoti143** [comment] 2015-01-16 18:57
Looks like the plunkr form used to open in a new window, but due to popup blockers getting in the way the behavior was changed to it's current state.  https://github.com/angular/angular.js/commit/925b2080a0341d9348feeb4f492957a2e2c80082

**Closed** 2015-01-23 21:48 UTC
Labels: PRs plz!, type: docs
