### ISSUE TITLE
$cacheFactory expire value

### ISSUE THREAD

**Issue by corporatepiyush** [angular/angular.js#11134] opened 2015-02-22 15:46 UTC
it would be nice to have timeout(or expire) value set while creating $cacheFactory instance

$cacheFactory('expirableCache', { expire: 10})

where 10 is 10 seconds

**Comment by Narretz** [comment] 2015-02-23 08:56
Hi, this is a duplicate of #https://github.com/angular/angular.js/issues/5482

We want to keep the angular core slim, so this is not planned right now. Have you looked at https://github.com/jmdobry/angular-cache? It's quite powerful.

**Closed by Narretz** 2015-02-23 08:56 UTC
