### ISSUE TITLE
ngMockE2E not mock $httpBackend when accessing "/#/" with enabling html5Mode

### ISSUE THREAD

**Issue by hiroaki-yamamoto** [angular/angular.js#13120] opened 2015-10-19 07:11 UTC
Hi,

I found a bug about ngMockE2E. Creating `$httpBackend` mock for E2E test and accessing `/#/` with `html5Mode = true`, the mock doesn't work.

To show this bug, I created [the repo](https://github.com/hiroaki-yamamoto/prtr-mock-bypass), so please review them.

Thanks.

**Comment by Narretz** [comment] 2016-01-23 15:11
Sorry for taking so long to respond to this.
I don't understand the problem. The $httpBackend should be used to mock API requests, and htmlMode is for the app only. So the two should not have any problems interacting.

**Comment by hiroaki-yamamoto** [comment] 2016-01-24 11:22
Hi,
> The $httpBackend should be used to mock API requests, and htmlMode is for the app only. So the two should not have any problems interacting.

Yeah, exactly. That's what I expected, but somehow creating a route to `/` with `location.htmlMode = true`, and then mocking the backend on E2E testing, the mock doesn't work [like this]

The repo doesn't have so long code, so please review it.

[like this]: https://github.com/hiroaki-yamamoto/prtr-mock-bypass

**Comment by hiroaki-yamamoto** [comment] 2016-02-12 14:09
Hi :smiley: 

I have a question. Does `$httpBackend.when` on `ngMockE2E` work if the route (which means route that defined on the app) is changed on E2E testing? I supposed the following case:

(mock requests) -> (call `brower.get('/#/'`) -> (Redirects to `/` by html5Mode) -> (Does mock set at 1st step work?)

**Comment by gkalpak** [comment] 2016-06-02 12:16
@hiroaki-yamamoto, I tried reproducing the problem, but the repo seems to be broken (I ran into several issues trying to `npm install` on Windows, until I gave up). Even reading at the code or the readme or this issues, it's not clear what the problem is (i.e. what is the actual vs expected behavior).

I'm going to close this. If you are still having problems with the latest versions, please open a new issue with a clear reproduction.

**Closed by gkalpak** 2016-06-02 12:16 UTC
Labels: component: ngMock, needs: more info, resolution: can't reproduce
