### ISSUE TITLE
Radio option selection issue on IOS - 10.2

### ISSUE THREAD

**Issue by varun-bansal** [angular/angular.js#15709] opened 2017-02-14 14:44 UTC
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
After selecting an option from the available radio buttons, the binding variable in the form is not updated in the template. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
http://plnkr.co/edit/lteYqVlbVaBqAoDo6vd0?p=preview
This won't reproduce the bug. But you get the idea of how we have implemented the code. After watching the video and screenshot you'll get to know the issue we are facing.

**What is the expected behavior?**
Selecting a radio option should update the binding variable in form.

**What is the motivation / use case for changing the behavior?**
Due to this issue user won't be able to submit the form successfully and will have to change the selection and reselect the correct option again.

**Which versions of AngularJS, and which browser / OS are affected by this issue? Did this work in previous versions of AngularJS? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
Angular version - 1.3.13
OS - IOS 10.2 on Iphone 5/6s
Haven't tested on any previous versions

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
Screenshot of the issue: https://drive.google.com/open?id=0BywABUsLPa4AMkRoYlpzNTFuZ0E
Video depicting the issue: https://drive.google.com/open?id=0B8zXVeTfYECYY3JjbHdEVHBZTnc

**Comment by frederikprijck** [comment] 2017-02-14 15:05
@varun-bansal Maybe it's a great idea to drop by the official support channels to get support regarding your problem instead of reporting a bug which is not reproducable (or atleast, you didn't get to reproduce it).

Please ask support questions on gitter (https://gitter.im/angular/angular.js) or reach out to anyone @ IRC.

**Comment by Narretz** [comment] 2017-02-14 15:09
Three things:
- Why does the plnkr not reproduce the bug? Are you maybe using 3rd party code that is actually responsible for the problem? Without a repro, we cannot do anything about this,
- 1.3.13 is not supported anymore, please check if the issue persists with 1.6.1 and the latest master snapshot
- Your video and screenshot are not public

**Comment by varun-bansal** [comment] 2017-02-16 11:54
1. Plnkr will not reproduce the bug as it is specific to ios 10.2. We are using ionic and cordova, but even it run the app in safari on ios 10.2 the bug is still reproducable, so there is no problem with the third party application.
2. Currently, we cannot update our system to 1.6 as that will include a lot changes to be done in our and we have planned that for some time in future.
3. Video and Screenshot link update

Upon further investigation, we found that the listener attached to the radio input was not fired sometimes when the radio input is selected, causing the model to not reflect the changes.

For now, we have implemented a workaround by surrounding the input tag in a label tag and adding ng-click handler in the parent label tag. When clicking on the parent tag that is same as clicking on the radio option we set the model value manually. Here's how

*Template*
`
                                    <label class="quiz-radio-wrap" data-ng-repeat="option in question.answer.options" data-ng-click="sampleInput(option, question)">
                                        <input class="radio-input" type="radio" name="{{  question.$key }}"
                                               data-ng-value="option.id"
                                               data-ng-model="quizFormData[question.$key]" data-ng-required="question.required"/>
                                        <span class="quiz-radio-circle">
                                            <span></span>
                                        </span>
                                        <span class="label-text" data-ng-bind="option.display_text"></span>
                                    </label>

`

Controller
`
$scope.sampleInput = function(option, question) {
         $scope.quizFormData[question.$key] = option.id;
};
`

Also, event if we would update our angular version to 1.6, can you assure that the bug would have been fixed?

You help is much appreciated! Thanks.

**Comment by Narretz** [comment] 2017-02-16 12:11
No, I can't guarantee that the problem goes away with 1.6.1. But if  you can re-create the bug with the plunkr in ios 10.2, then you should also be able to test it with 1.6.1 instead of your app's version. Can you do that and report back?
It does sound like an ios problem, though.

**Comment by varun-bansal** [comment] 2017-02-16 12:25
Sure, will try with 1.6.1 on plunkr and get back.

**Comment by Narretz** [comment] 2017-03-06 17:10
I'm going to close this issue because we haven't got any feedback. Feel free to reopen this issue if you can provide new feedback.

**Closed by Narretz** 2017-03-06 17:10 UTC
Labels: component: forms, needs: more info
