### ISSUE TITLE
Data binding not working in Canary 

### ISSUE THREAD

**Issue by rgb4268** [angular/angular.js#16912] opened 2019-11-06 21:30 UTC
I have an Angular 1.3 app running. It works fine on Chrome. However, it does not render correctly in Canary v80. The following are snippets from my code -

`
<paper-dropdown-menu >
    <paper-listbox class="dropdown-content" selected = "1">
        <paper-menu class="menu" data-ng-model="abc" attr-for-selected="name">
            <paper-item name="{{a}}" data-ng-repeat="a in abc">{{a}}</paper-item>
        </paper-menu>
    </paper-listbox>
</paper-dropdown-menu>
`
(This works fine if the data is something static)

In the controller file, I invoke a REST call to get the data 'abc'. I have verified by the debugger that the data is loaded correctly.

In the drop-down, nothing shows. So data-ng-model is not loading data in time for the render. I get the stack trace below
TypeError: el.getPropertyInfo is not a function
at http://127.0.0.1:9000/bower_components/ng-polymer-elements/ng-polymer-elements.js:196:39
at Array.forEach ()
at link (http://127.0.0.1:9000/bower_components/ng-polymer-elements/ng-polymer-elements.js:163:18)
...
at compositeLinkFn (http://127.0.0.1:9000/bower_components/angular/angular.js:7143:13)

This might be a polymer error I guess. Or polyfills. Just don't know how to fix this.

**Comment by gkalpak** [comment] 2019-11-06 22:47
I guess this is the same issue as [this StackOverflow question][1]. It is hard to tell whether this is an AngularJS issue (although it sounds more likely that it is a Polymer/WebComponents issue). Impossible to tell without a reproduction.

Also, note that v1.3 is not maintained any more. See [here][2] for more info on the current version support status.

I am going to close this issue, since it is not actionable atm.
If you can provide a (minimal) reproduction (using a recent AngularJS version), please open a new issue.

[1]: https://stackoverflow.com/questions/58698130/latest-canary-angular-webcomponents-polymer-polyfill-is-broken
[2]: https://docs.angularjs.org/misc/version-support-status

**Closed by gkalpak** 2019-11-06 22:47 UTC

**Comment by rgb4268** [comment] 2019-11-06 22:51
I would have to create a whole application if we want something reproducible.
