### ISSUE TITLE
angular.merge breaks sce trusted values

### ISSUE THREAD

**Issue by jchitel** [angular/angular.js#12743] opened 2015-09-02 23:23 UTC
When you call angular.extend with a src that contains sce trusted values, the corresponding values in the dst object are recognized as objects and not unwrapped. 

If my understanding is correct, angular.merge should not deep copy these values.

**Comment by petebacondarwin** [comment] 2015-12-07 18:09
@jchitel can you clarify with a code example exactly what you mean?
Are you saying that a property on the `src`, say `src.myVal` that has been converted to a trusted value, is being modified when copied over to the `dest` so that `dest.myVal` is no longer trusted?

**Comment by Narretz** [comment] 2017-06-06 08:32
I'm going to close this issue because we have no reproduction of the issue. Feel free to reopen this issue if you can provide a reproduction (ideally a runnable demo in a [Plunker](https://plnkr.co) or similar. You can use this [Plunker Template](http://plnkr.co/edit/tpl:yBpEi4)).

**Closed by Narretz** 2017-06-06 08:32 UTC
