### ISSUE TITLE
AngularJS problems with $http

### ISSUE THREAD

**Issue by furyscript** [angular/angular.js#13567] opened 2015-12-17 10:41 UTC
I noticed that when I was "away from keyboard" over 5-10min and I make a call to backend (`GET, POST or something`) the first call `OPTIONS` remains pending and if I make a second call works fine, so the applications seems to unlocking me.

The request is never resolve.
If I press again the button pressed before it works (also if a make different call from application it work)

Obviously the request not arrive to backend so it isn't resolved, this is the header of request, maybe can be helpfull..
```
Request URL:http://api.work.com/checkAuthToken
Request Headers
Provisional headers are shown
Access-Control-Request-Headers:accept, authorization
Access-Control-Request-Method:GET
Origin:http://work.com
Referer:http://work.com/admin/measure-units/
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36
X-DevTools-Emulate-Network-Conditions-Client-Id:FDF19108-AB76-422C-96DF-40E2ED3F7A3E
```

Why?
the problem is from browser? 
Do it happened the same thing to someone else?

**Comment by pkozlowski-opensource** [comment] 2015-12-17 10:42
I would be _very_ surprised if this would be AngularJS specific. Try to use pure XHR and see if you can reproduce the same issue.

**Comment by furyscript** [comment] 2015-12-17 10:58
This is the function in service that I use globally for make request:
```javascript
    var get = function(url, callbackOnSuccess, callbackOnError) {
        $log.debug('data.httpService.get fnUrl:' + url);
        var req = {
            method: 'GET',
            url: APP_CONFIG.api.base_url + url
        };

        if (appState.getValue('auth_token')) {
            req.headers = {
                'Authorization': appState.getValue('auth_token')
            };
        }

        if (!callbackOnError) {
            callbackOnError = callbackOnErrorDefault;
        }

        $http(req).success(callbackOnSuccess).error(callbackOnError);
    };
```
And this is an example how I use it:
```javascript
httpService.get('/users', function(result, status) {
     // Do something
});
```

I don't think that it is the problem...

**Comment by furyscript** [comment] 2015-12-17 14:04
Uhm... I think the problem is from chrome... Now I get this problem while page refreshing (I make http call  when state is start)... I'm 90% sure that the problem is chrome...

**Comment by furyscript** [comment] 2015-12-18 14:57
I paid more attention to call executed and see that after 5-10min I think the browser have cached the "authorization" from backend so it doesn't send again the OPTIONS request but send directly the GET, POST or something request in question

See that when request goes in `pending` after 5-10mins
`Access-Control-Request-Method:GET`
There isn't the OPTIONS request before...
If I press again the button, first browser make OPTIONS, and second GET...
How can I fix this?

**Comment by gkalpak** [comment] 2015-12-21 12:01
@furyscript, the `OPTIONS` request is made by the browser (i.e. Angular neither causes it, nor can it prevent it).
It is related to CORS requests. You can find more info on the relevant [MDN article][1].

[1]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Overview

**Comment by furyscript** [comment] 2015-12-21 13:12
I'm thinking the problem is firewall...

**Comment by Narretz** [comment] 2016-01-04 19:13
Closing since it's not an issue with Angular

**Closed by Narretz** 2016-01-04 19:13 UTC
Labels: component: $http
