### ISSUE TITLE
XHR Timeout issue Internet Explorer

### ISSUE THREAD

**Issue by endamaco** [angular/angular.js#15259] opened 2016-10-13 09:06 UTC
Hi,

I'm using angular 1.3.15 and I'm experiencing a wrong behavior with Explorer 10 and 11 when XHR calls are timing out.

Based on angular's documentation I can set a client timeout using the timeout parameter on $http call. Looking at angular source code when the timeout triggers the xhr.abort() method is triggered.

Doing so on IE causes a lot of 400 (bad request) server-side. With my tests I found that using the xhr.timeout parameter would solve the issue. Is there any reasonable answer on why xhr.timeout is not used while xhr.abort() is implemented?

Could this be fixed?

**Comment by gkalpak** [comment] 2016-10-13 11:34
I am not sure why it was implemented like this. One reason could be [compatibility][1] (especially considering it is a feature added long ago). But one other important reason is that `$http`'s `timeout` does not only accept numeric values (as its native counterpart), but also promises, allowing much better control over cancelling a request.

Also, 1.3.x is a pretty old release and is no longer maintained. You should try upgrading to a newer version and see if the problem persists. Also, make sure there is not something else going on - I couldn't reproduce the problem on IE11.

<sub>(TBH, I am a little surprized no one else has complained about this before.)</sub>

--
I am going to close this since this is not actionable at the moment. I would be happy to reopen and investigate alternatives if we have a reproduction of the problem using the current version (1.5.8).

[1]: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#Browser_Compatibility

**Closed by gkalpak** 2016-10-13 11:34 UTC

**Comment by endamaco** [comment] 2016-10-13 12:34
Being that $httpBackend implements the timeout in the same way I would say the problem still persist also on the current version.

I must say this wasn't an easy issue to be replicated: to be sure to trigger this I had to cycle over 100 requests and fire them all together having a reasonably short timeout to be sure it was fired.

I have been googling around this for a while and the most similar issues are the following twos:

http://stackoverflow.com/questions/6941898/jquery-ajax-post-parameters-sometimes-not-sent-on-ie 
http://stackoverflow.com/questions/4796305/why-does-internet-explorer-not-send-http-post-body-on-ajax-call-after-failure

Aborting the xhr client-side might cause the same network errors that are there mentioned

**Comment by gkalpak** [comment] 2016-10-13 17:22
So, if this happens randomly and under heavy load, it sounds more like a browser issue/bug, rather than Angular's. If we can't reproduce `xhr.abort()` causing problems or unwanted side effects, we can't move forward.
