### ISSUE TITLE
Generic track by annotation for any component bindings

### ISSUE THREAD

**Issue by Aaron-Pool** [angular/angular.js#15647] opened 2017-01-28 05:09 UTC
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

In component bindings, $onChanges is only triggered if an object reference changes. You can also use $doCheck, but it is, in my opinion, more complex than necessary for the average non-object-reference dirty-check for a component binding. It would also be nice to be able to specify in the parent template what you consider to make a binding "dirty" as opposed to only once in the component definition.

**What is the expected behavior?**

```
<my-component
    // normal binding, watches object reference for dirty check
    binding1="model1"
    // But here I have a value field on the model object, and instead of comparing the object reference of my model here, I want you to check this expression value when checking for dirtiness
    binding2="model2 track by model2.value"
></my-component>
```

**What is the motivation / use case for changing the behavior?**

Again, I think that `$doCheck` is overkill for a lot of the times I want to have an identifier field on a binding, but I'm also pretty tired of doing a shallow clone to change an object reference, because, while efficient, it isn't intuitive to people reading code. People are familiar with the `track by` method, do to `ng-repeat`, so it seems like this would be an intuitive change. It would also add a GREAT deal of readability to code, in my opinion. This could also, obviously, be accomplished with `$scope.$watch`, but that encourages the poor habit of regularly injecting and using `$scope`

**Comment by Narretz** [comment] 2017-01-28 14:30
Hi,
I while I see how this would improve the workflow, it's unlikely to be implemented, as Angular2 does not have this feature, and in general we don't want to introduce features that have no equivalent in Angular2. I'd say having the change tracking by reference is also a feature that should be embraced and not worked around.

**Comment by Aaron-Pool** [comment] 2017-01-28 20:24
@Narretz , so, would you see any point in making a similar feature request to the ng2 team? Also, I agree that change tracking by reference is a feature, due to it's performance advantage, but similar performance advantages can be achieved by using a primitive or a subproperty object reference as the track by identifier, right?

**Comment by Narretz** [comment] 2017-01-31 09:15
@Aaron-Pool I'm not super familar with the Angular architecture, but I assume the focus on immutability of data is even bigger in Angular, so I don't see huge chances. You can always open an issue and get some feedback.

**Comment by Aaron-Pool** [comment] 2017-01-31 20:19
Sorry, I'm a bit confused on what this has to do with immutability? I'm simply talking about making the change checking mechanism more precise. If a change is detected, the whole model would _still_ update it's entire state, which I think is in keeping with the immutability paradigm?

**Comment by Narretz** [comment] 2017-02-01 12:16
Immutability is probably not the right word. I meant that by design the whole change tracking mechanism is based on the identity of the object, i.e. you have to create a new object to kick of the $onChange listener. This is an intentional decision to discourage the mutation of objects. If you now introduce something that's based on the property change of an object, it runs contrary to this idea, I would say.

**Comment by Narretz** [comment] 2017-03-16 22:34
I'm going to close this issue because we haven't got any feedback. Feel free to reopen this issue if you can provide new feedback.

**Closed by Narretz** 2017-03-16 22:34 UTC
Labels: component: $compile, type: feature
