### ISSUE TITLE
Do not clear functions from resource objects after getting a response from the server

### ISSUE THREAD

**Issue by gingermusketeer** [angular/angular.js#7526] opened 2014-05-20 22:16 UTC
I have run into an issue with $resource when requesting data from the server. After constructing an instance and before making a request to the server i attached a function which returns a related object which is used to display data before and after the response has been received.

If my understanding is correct $resource removes all properties from the resource after receiving data from the server. See https://github.com/angular/angular.js/blob/d5a92d22502dac617351dd2bc1726025973c439a/src/ngResource/resource.js#L579

The solution i have come up with is to reattach the function using $promise.finally

It would be great if shallowClearAndCopy did not delete properties if they were functions. Maybe this could be configured through an option?

**Comment by Narretz** [comment] 2017-04-26 15:23
Duplicate of https://github.com/angular/angular.js/issues/1453

**Closed by Narretz** 2017-04-26 15:23 UTC
Labels: component: ngResource, frequency: low, severity: inconvenient
