### ISSUE TITLE
[ngAria] aria-invalid attribute is incorrectly set to true initially

### ISSUE THREAD

**Issue by TimVevida** [angular/angular.js#15899] opened 2017-04-07 09:09 UTC
**I'm submitting a ...**

- bug report

**Current behavior:**

When an input field is marked with the required attribute, the ng-aria module initially sets the aria-invalid attribute to true. Assistive technology (screen readers) will read something like "Input, required, invalid" when the user navigates to the input.

**Expected / new behavior:**

The aria-invalid attruibute should only be set after the field is touched or the form is submitted. As per the [W3C spec](https://www.w3.org/TR/wai-aria/states_and_properties#aria-invalid):

> ... if the user has not attempted to submit the form, authors SHOULD NOT set the aria-invalid attribute on required widgets simply because the user has not yet entered data.

In addition, when the value of the input is set in the binded property, the input should be validated initially.

**Minimal reproduction of the problem with instructions:**

See [this plunker](https://plnkr.co/edit/BmaWzUDWoD3KJmV7C04k?p=preview).

**Angular version:** 1.6.3

**Browser:** all

**Anything else:**

The presence of this bug with other validation methods:
- Using ng-required yields the same (incorrect) result as adding the required attribute.
- When using ng-min and ng-max, aria-invalid is correctly set to false initially
- When using ng-pattern, aria-invalid is correctly set to false initially
- When using a custom validator, aria-invalid is correctly set to false initially
- When using any of the input types date, datetime-local, email, month, number, time, url and week, aria-invalid is correctly set to false initially

**Comment by Narretz** [comment] 2017-04-07 12:51
Thansk for the report. This looks like a dupe of https://github.com/angular/angular.js/issues/11883 and I think the solution is actually not to apply aria attributes to native input elements, since the required attribute should be enough to handle it.

**Closed by Narretz** 2017-04-07 12:51 UTC

**Comment by TimVevida** [comment] 2017-04-07 13:13
Sorry for the duplication, my bad. I will continue this discussion in #11883.
