### ISSUE TITLE
#chrome links with transition color issue

### ISSUE THREAD

**Issue by Ciul** [angular/angular.js#3164] opened 2013-07-08 21:38 UTC
I'm passing an application to Angularjs, it is using Twitter Bootstrap.
And something strange is happening on Chrome.

I override links with next rule to make transition color and background:

``` css
a, a:visited, a:focus, a:hover, a:visited {
    -webkit-transition: all 0.5s linear;
    -moz-transition: all 0.5s linear;
    -ms-transition: all 0.5s linear;
    -o-transition: all 0.5s linear;
    transition: all 0.5s linear;
    text-decoration: none;
}
```

Now, there are some links that not taking initial color (white) that they should have, instead they're getting transparent.

This is fixed if:
1- I open or close the console (really strange)
2- After first hover over the links.
3- I modify the styles of anything else using the console

Also, this happens only in Google Chrome, not happening in FireFox, neither on IE.
And this happens only on the Angularjs version of the app.

If I remove the transitions styles they work as expected (having color white on initial state and not transparent).

http://screencast.com/t/ThnqK1kAdX
(left window is Chrome, right window is FireFox)

Any idea?

**Comment by mattnish** [comment] 2015-03-20 21:30
+1

Getting same chrome (41.0.2272.101) rendering bug with v1.3.15.

![screenshot 2015-03-19 13 18 40](https://cloud.githubusercontent.com/assets/892867/6761172/854b1fa2-cf0d-11e4-81c8-4a8688782ab4.png)

**Comment by GSchutz** [comment] 2015-04-01 03:53
+1

I have the same problem with anchor tag,
Angular v1.3.9, Angular-ui-router v0.2.13, Chrome v39.0.2171.99

But I found a solution (at least for me it worked), the `ui-router` use the attribute `ui-sref`, I just add the `href` attribute back, when I remove the `href` the problem comes back again.

![angular-anchor](https://cloud.githubusercontent.com/assets/1896145/6934240/a60b24c8-d807-11e4-9d8c-b69aa472a308.png)

**Comment by mattnish** [comment] 2015-04-07 21:17
Hmm that's funky.  It seems that when I use `ng-href` on anchor tags, there are the color rendering issues in Chrome.

![screenshot 2015-04-07 14 13 23](https://cloud.githubusercontent.com/assets/892867/7033671/a6132e38-dd30-11e4-89a6-b560490b55c4.png)

But when I use the normal `href` it's all good.

![screenshot 2015-04-07 14 14 27](https://cloud.githubusercontent.com/assets/892867/7033681/bba23c9e-dd30-11e4-818e-3320121705e6.png)

**Comment by petebacondarwin** [comment] 2015-04-12 18:36
@mattnish - I wonder if you have different CSS styles for `<a>` tags that have no `href`? The CSS might then be rendered based on the lack of `href` when the HTML is initially rendered and Chrome is not then re-rendering when the `ng-href` directive adds in the `href` attribute later.

**Comment by mattnish** [comment] 2015-04-13 18:10
@petebacondarwin I'm simply using bootstrap and an override class.  So, there are no classes that are different for anchors with/without `href`, just the out-of-the-box bootstrap anchor style, then my override that looks like this:

```
a  {
  color: $grey-8;
  &:focus, &:visited {
    color: $grey-8;
  }
}
```

**Comment by sricks** [comment] 2015-04-16 19:27
I have this same issue, there are definitely no styles that reference an a tag with/without an href. Adding `href="#"` fixed it for me.

**Comment by waltercolindres** [comment] 2015-10-06 22:59
same issue popped up for me on angular#1.3.15

**Comment by Narretz** [comment] 2016-11-05 13:56
Is this still a problem for anyone here with newer Angular / Chrome versions? If so, can someone provide a runnable demo?

**Comment by Narretz** [comment] 2017-02-13 11:40
I'm going to close this issue because we have no reproduction of the issue. Feel free to reopen this issue if you can provide a reproduction (ideally a runnable demo in a [Plunker](https://plnkr.co) or similar. You can use this [Plunker Template](http://plnkr.co/edit/tpl:yBpEi4)).

**Closed by Narretz** 2017-02-13 11:40 UTC
Labels: browser: chrome, needs: investigation, type: bug

**Comment by leandroluk** [comment] 2017-11-01 14:09
I fixing this crazy bug on stop to use <a href> tag for link's and start using a <button> or another tag for this...
