### ISSUE TITLE
Using $compile, a directive can unintentionally call scope functions in the parent controller

### ISSUE THREAD

**Issue by stevebrowndotco** [angular/angular.js#15775] opened 2017-03-05 02:05 UTC
**Do you want to request a *feature* or report a *bug*?**

I believe this is a bug.

**What is the current behavior?**

If I $compile the nested contents of a directive and link the scope, (e.g `$compile(element.contents())(scope);`)I am able to call scope functions in the parent controller. I believe this should not be the case. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

Here I show how you can reproduce this: https://jsfiddle.net/stevewbrown/ntvc3a5q/14/ .

Open the console and click the "click me" button on each three directives  

1. **Directive that uses Compile** - runs the "onClickButtonInDirective()" functions in both the isolated scope and the parent controller scope. **This is the bug**
2. **Directive that uses transclusion** - only runs the "onClickButtonInDirective()" in the isolated scope. **Intended Behaviour**
3. **Directive that uses template** - only runs the "onClickButtonInDirective()" in the isolated scope. **Intended Behaviour**

**What is the expected behavior?**

Please see 2 and 3 above

**What is the motivation / use case for changing the behavior?**

I believe its a fundamental issue when creating reusable directives with serverside generated code.

**Which versions of AngularJS, and which browser / OS are affected by this issue? Did this work in previous versions of AngularJS? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

Appears to be a bug in all versions to date

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by stevebrowndotco** [comment] 2017-03-05 02:09
(Sorry about the mass title changes, trying to make it concise and clear)

**Comment by gkalpak** [comment] 2017-03-05 13:22
This is expected behavior. (OK, maybe not expected, but intended :smiley:)

This is discussed in more detail in #13845. The gist of it is that a directive's isolate scope is only "visible" in the directive's template (as documented [here][1]):

> Note that an isolate scope directive without a `template` or `templateUrl` will not apply the isolate scope to its children elements.

##
In your case, you do not have a template and the isolate scope would not be visible anywhere, except you re-compile the element's contents with it. So essentially, the element's contents are compiled twice:

1. From angular using the parent scope (since the isolate scope should not be visible to the contents as they are not in the directive's template).
2. Manually from within the directive's post-linking function using the isolate scope.

Note that compiling an HTML subtree twice is not supported and may lead to unexpected failures and memory leaks (as documented [here][2]). This is most likely not what you want anyway.

You can achieve what you want, by making your directive `terminal` (and possibly giving it a very low priority). [Updated fiddle][3].

##
Closing since everything works as intended.

[1]: https://docs.angularjs.org/api/ng/service/$compile#-scope-
[2]: https://docs.angularjs.org/guide/compiler#double-compilation-and-how-to-avoid-it
[3]: https://jsfiddle.net/8p6oz4tk/

**Closed by gkalpak** 2017-03-05 13:22 UTC

**Comment by stevebrowndotco** [comment] 2017-03-05 16:36
Thanks @gkalpak for taking the time, if it's intended then I guess that's the way it is..

"In your case, you do not have a template and the isolate scope would not be visible anywhere, except you re-compile the element's contents with it. So essentially, the element's contents are compiled twice:"

But isn't this what is happening with the transcusion example as well (in my jsfiddle)? My understanding is that the transcusion recompiles as well. Is it just because transcusion will always create the isolated scope whereas $compile does not? (Trying to understand why it's different behaviour when conceptually they seem to be doing the same thing... At least in my mind)

**Comment by gkalpak** [comment] 2017-03-05 16:54
> But isn't this what is happening with the transcusion example as well (in my jsfiddle)?

No. Transclusion does not compile the content twice. The content is removed from the DOM (until transcluded) and is only compiled once.
