### ISSUE TITLE
in $digest, "TypeError: JSON.stringify cannot serialize cyclic structures."

### ISSUE THREAD

**Issue by nbrustein** [angular/angular.js#8470] opened 2014-08-04 15:25 UTC
At least sometimes, adding a property to a scope that includes a cyclical structure will blow up on the error: "TypeError: JSON.stringify cannot serialize cyclic structures.".  The error traces back to the following place in $digest.

The really frustrating this is that it doesn't seem like that json is really going to be used for anything anyway (I guess unless you hit the 10 iteration limit?).

Seems like there should be a try/catch there.  It should be okay to put a property on a scope event if it has a cyclical structure in it, right?
                    
                     if (ttl < 5) {
                        logIdx = 4 - ttl;
                        if (!watchLog[logIdx]) watchLog[logIdx] = [];
                        logMsg = (isFunction(watch.exp))
                            ? 'fn: ' + (watch.exp.name || watch.exp.toString())
                            : watch.exp;
                        logMsg += '; newVal: ' + toJson(value) + '; oldVal: ' + toJson(last);
                        watchLog[logIdx].push(logMsg);
                      }

**Comment by booleanbetrayal** [comment] 2015-06-18 02:30
@caitp + @jeffbcross - FWIW, this appears to happening on our models during serialization when encountering a property `$$embeddedIn` which we named as such to piggyback on the transient nature of `$$` prefixed properties during JSON serialization. Called directly into `angular.toJson` by the model, passing its as the value to be serialized. Looking at the source, the `toJsonReplacer` function appears sound and should be doing its job in that call flow.

The odd thing is that this is only happening on Windows 8.1 on Firefox 38. So, it seems like some odd environmental abnormality of some sort, if anything happens to jump out ... I have not been able to reproduce in a VM test environment yet.

**Comment by caitp** [comment] 2015-06-18 03:16
A quick bug search doesn't turn up much for that @booleanbetrayal https://bugzilla.mozilla.org/buglist.cgi?list_id=12335697&short_desc=JSON%20replacer&resolution=---&resolution=FIXED&resolution=INVALID&resolution=WONTFIX&resolution=DUPLICATE&resolution=WORKSFORME&resolution=INCOMPLETE&resolution=SUPPORT&resolution=EXPIRED&query_format=advanced&bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&bug_status=RESOLVED&bug_status=VERIFIED&bug_status=CLOSED&short_desc_type=allwords&component=General&component=JavaScript&component=JavaScript%20Engine&component=JavaScript%20Engine%3A%20JIT&component=JavaScript%3A%20GC&component=JavaScript%3A%20Internationalization%20API&component=JavaScript%3A%20Standard%20Library&component=Libraries&component=Library --- You might want to put together a quick reproduction and filing it

**Comment by Narretz** [comment] 2016-01-22 17:33
Closing because there's no reproduction / activity.

**Closed by Narretz** 2016-01-22 17:33 UTC
Labels: component: scopes, needs: more info, type: bug
