### ISSUE TITLE
angular-1.3.8 - Infinite digest in Safari 5.1 related with difference between $browser.url() and $location.absUrl()

### ISSUE THREAD

**Issue by SerjoPepper** [angular/angular.js#11486] opened 2015-04-02 10:29 UTC
I explored that this code worked unexpectedly in Safari 5.1 (row 11397 in angular.js)
var oldUrl = trimEmptyHash($browser.url()); // returns "http://swift-musk-ox-6940.vagrantshare.com/catalog/c596/для_женщин/"
var newUrl = trimEmptyHash($location.absUrl()); // returns http://swift-musk-ox-6940.vagrantshare.com/catalog/c596/%D0%B4%D0%BB%D1%8F_%D0%B6%D0%B5%D0%BD%D1%89%D0%B8%D0%BD/

Maybe it related with Safari's "location.href" returns undecoded url

**Comment by petebacondarwin** [comment] 2015-07-20 13:52
@SerjoPepper - thanks for reporting this issue. I am afraid that Safari 5.1 is no longer supported by Apple on any platform. I could not reproduce this issue in Angular on my only version of Safari which is Version 8.0.7 (10600.7.12).

I am afraid that we will not be providing resources to fix this issue. If you are able to provide a PR with tests that fixes this without breaking the latest versions of our supported browsers, then I would be happy to consider it.

**Comment by SerjoPepper** [comment] 2015-07-20 14:32
@petebacondarwin this bug reproduces not only in Safari in 5.1. I explored this bug when used prerender.io. Prerender.io uses Phantom.js 1.9 version, which uses same webkit engine as in Safari 5.1

**Comment by petebacondarwin** [comment] 2015-07-20 14:43
OK, so can you reproduce this in a unit test that fails with phantomjs 1.9?

**Comment by SerjoPepper** [comment] 2015-07-20 14:54
yes, I can, with any cyrillic url. I am able to provide PR

**Comment by petebacondarwin** [comment] 2015-07-20 15:14
Awesome.

**Comment by petebacondarwin** [comment] 2015-07-30 16:46
Closing this - please provide a PR with a unit test that fails on phantomjs 1.9. Thanks

**Closed by petebacondarwin** 2015-07-30 16:46 UTC
Labels: component: $location, resolution: can't reproduce, resolution: won't fix, type: bug
