### ISSUE TITLE
Cannot read property 'ng339' of undefined error inside ng-switch-when and directive on 1.2.25

### ISSUE THREAD

**Issue by p3rsist** [angular/angular.js#9485] opened 2014-10-08 03:37 UTC
I have a directive inside an ng-switch-when directive. When I do some changes to the scope models inside that directive (saving data to the server and updating the models) and I switch view (going to another ng-switch view) and go back again to that same ng-switch-when I get this ng339 error.

**Comment by seaside98** [comment] 2015-06-22 20:12
I am getting this same error in 1.4.1.

**Comment by lgalfaso** [comment] 2015-06-22 20:42
@seaside98 would it be possible for you to create a plunker with the error?

**Comment by seaside98** [comment] 2015-06-22 21:40
@lgalfaso It seems to be a bit too complex for me to replicate outside of my app, and I can't just paste the app because it is a private project. I will keep working on the plunker to see if I can replicate it. 

If it helps at all, here is the full error log:
```
[Error] Error: undefined is not an object (evaluating 'element.ng339')
jqLiteRemoveData@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular.js:2807:26
jqLiteDealoc@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular.js:2764:41
jqLiteRemove@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular.js:2960:30
https://ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular.js:3503:19
https://ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular.js:5218:25
push@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular.js:4832:44
leave@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular.js:5217:35
ngSwitchWatchAction@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular.js:27696:68
$digest@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular.js:15667:31
$apply@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular.js:15935:31
https://ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular.js:17691:42
completeOutstandingRequest@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular.js:5387:15
https://ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular.js:5659:33
	(anonymous function) (angular.js, line 12314)
	(anonymous function) (angular.js, line 9101)
	$digest (angular.js, line 15685)
	$apply (angular.js, line 15935)
	(anonymous function) (angular.js, line 17691)
	completeOutstandingRequest (angular.js, line 5387)
	(anonymous function) (angular.js, line 5659)
```

**Comment by lgalfaso** [comment] 2015-06-22 22:43
@seaside98 without a way to reproduce this issue or access to some environment that shows this error, then it is not possible to move forward.
Just looking at the stacktrace, the only thing that comes to my mind is that at some point there is some DOM manipulation performed not using using the right mechanisms at some DOM elements that are at the same level than an `ngSwitch`


BTW, any application that removes/modifies DOM elements directly using jQuery/jqLite has the potential to create a memory leak

**Comment by seaside98** [comment] 2015-06-25 16:15
@lgalfaso After doing a bunch of testing, I have determined that it isn't confined to ```ngSwitch```. ```ngRepeat``` also throws this same error, and for whatever reason it seems to pop up very often in my app, but I can't make it happen elsewhere. Anyway, I've found the code that doesn't logically work...
<br>

The origin of the problem is [animate.js#L480](https://github.com/angular/angular.js/blob/291d7c467fba51a9cb89cbeee62202d51fe64b09/src/ng/animate.js#L480), which calls ```element.remove();``` with no arguments. ```element.remove``` is a wrapper for ```jqLiteRemove``` [jqLite.js#L470-L474](https://github.com/angular/angular.js/blob/9efb0d5ee961b57c8fc144a3138a15955e4010e2/src/jqLite.js#L470-L474). 

```jqLiteRemove``` expects an ```element``` to be passed to it, and does not check to make sure one actually is. It is passes the ```element``` (which is ```null```) to ```jqLiteDealoc```, and then to ```jqLiteRemoveData```, who assumes ```element``` is defined and tries to access the property ```ng339``` (and breaks my entire app).

The cleanest and most stable fix I've found for this (it had no side effects I could find, and threw no errors) is to just check that ```element``` is defined in ```jqLiteRemoveData```.
```javascript
function jqLiteRemoveData(element, name) {
  if(element == undefined) {
      return;
  }
  var expandoId = element.ng339;
  //...
}
```
While this doesn't fix the root of the problem, it does stop these annoying answers. If anyone can come up with a better solution, that would be great.

**Comment by lgalfaso** [comment] 2015-06-25 19:51
@seaside98 when calling `element.remove()` the function should not get called directly but thru the wrapper at https://github.com/angular/angular.js/blob/9efb0d5ee961b57c8fc144a3138a15955e4010e2/src/jqLite.js#L1014
that adds the element as the first parameter... there is something else going on

Ping @matsko

**Comment by seaside98** [comment] 2015-06-25 20:26
Ok, I tracked up the stack a bit more and found that [```leave```](https://github.com/angular/angular.js/blob/291d7c467fba51a9cb89cbeee62202d51fe64b09/src/ng/animate.js#L478) is getting called without an element by ```ngSwitchWatchAction```. (This is logging ```element``` and ```options```) ![screen shot 2015-06-25 at 3 20 13 pm](https://cloud.githubusercontent.com/assets/6372893/8364789/65a21614-1b4e-11e5-8470-8ba1fff5ec9f.png)

**Comment by Narretz** [comment] 2016-01-06 16:31
Fixing this in jqlite is probably the wrong way. But we need a demo of the problem to find the underlying issue.

**Comment by seaside98** [comment] 2016-01-10 22:48
This issue has only been reproduced in complex apps running in Safari 8 (OSX Yosemite Safari). Since that is out of date software now, and because it is impossible to reliably reproduce this bug, it really isn't worth the effort. The underlying issue was something with Safari likely not functioning as it should.

**Comment by gkalpak** [comment] 2016-01-11 08:18
Thx @seaside98 for the follow-up. Closing.
(Feel free to reopen, if the problem appears in latest versions.)

**Closed by gkalpak** 2016-01-11 08:18 UTC
Labels: component: ngAnimate, type: bug
