### ISSUE TITLE
Angular App: IE11 memory increase with continuous polling

### ISSUE THREAD

**Issue by anantkulkarni83** [angular/angular.js#15546] opened 2016-12-26 09:06 UTC
**Do you want to request a *feature* or report a *bug*?**
   Seems to be bug. Not sure whether in code or in angular.

**What is the current behavior?**
When application is continuously polling data from server, IE11 memory keeps increasing. With actual application the change in IE11 memory is huge if we keep application open for 2-3 hrs. Though in this case application remains responsive.

The thing is we are not observing increase in memory for Chrome browser.

The minimal demo is created at:
http://plnkr.co/edit/6UfekbeQyxtbUS1OUvNb?p=catalogue

Expected is; it should not increase memory continuously.

**Which versions of Angular, and which browser / OS are affected by this issue?**
Angular 1.4.8, IE11

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
To simulate please download the code and run locally on IE11.

Attached are the memory snapshots for app running..... 
**At startup** 
![image](https://cloud.githubusercontent.com/assets/22074170/21479159/0d3f3bd8-cb78-11e6-91fc-2d62140e244d.png)

**After ~1hr**
![image](https://cloud.githubusercontent.com/assets/22074170/21479164/14b42748-cb78-11e6-84ed-c7f55f957521.png)

**Comment by gkalpak** [comment] 2016-12-29 17:31
I did some profiling and here is what I found:

1. Although the total memory increases slightly (as mentioned by the OP), the heap snapshots (which show the un GC'ed objects) show absolutely no increase in retained memory.

2. A similar increase was observed even without Angular, with a simple script containing:
    ```js
    setInterval(function () {
      Math.random();
      Math.random();
      Math.random();
      Math.random();
    }, 500);
    ```

3. Afaict, IE11 does not show info related to the total memory outside of the heap.

Based on the above, it seems to me that any memory leak is caused by a browser issue, not Angular, and IE11 does not provide the necessary info to further investigate the situation 😞

**Comment by anantkulkarni83** [comment] 2017-01-02 12:02
Thanks @gkalpak for the information.

For our application as well actual heap memory is not getting increased. So does this confirms that there is no leak with angular app but with IE11 browser?

**Comment by gkalpak** [comment] 2017-01-03 10:29
@anantkulkarni83, that is correct (according to my understanding at least). Unfortunately, IE11 doesn't seem to offer much insight into what the non-heap memory increase is about, so I can't tell with 100% certainty, but from what I understand if you had a memory leak in your app, the heap size would keep increasing. Also, based on the fact that a siilar memory increase happens even without Angular, I would say there is definitely something wrong on the browser level.

**Comment by gkalpak** [comment] 2017-01-03 10:32
Since you confirmed that there is no increase in the heap size and there is currently no indication that this is an Angular issue, I am going to close this as _non-actionable_. Feel free to continue the discussion below, though.

**Closed by gkalpak** 2017-01-03 10:32 UTC
Labels: browser: IE11, component: misc core, needs: investigation, resolution: not core, severity: memory leak

**Comment by anantkulkarni83** [comment] 2017-02-16 05:08
Hi, 
I was able to fix this issue.. 

Following link explains exact scenario we were having.. i have added comment in it as well. I have shared this here; may be this would help someone!

https://medium.com/@garthw/how-to-work-around-ie-memory-leaks-in-spas-b2f6bc7c9ae9#.98cnrjxu2
