### ISSUE TITLE
$overrideModelOptions does not apply timezone

### ISSUE THREAD

**Issue by booblin** [angular/angular.js#16181] opened 2017-08-18 08:11 UTC
I'm thinking is bug 

**Current behavior:**
Changing timezone programmatically (use $overrideModelOptions) dont work 

**Expected / new behavior:**
If we set new timezone, it apply to model

**Minimal reproduction of the problem with instructions:**
```
function ChangeModelOptionsDirective () {
  return {
    restrict: 'A',
    require: 'ngModel',
    link: function ($scope, element, attrs, ngModel) {
      ngModel.$overrideModelOptions({
	timezone: '+0400', // dont work
	debounce: {
	  'default': 5000 // it work
        }
     })	     
    }
  };
}
```
Plunker: [http://plnkr.co/edit/7zHR1EKigTMaFjDU1yDc?p=preview](http://plnkr.co/edit/7zHR1EKigTMaFjDU1yDc?p=preview)

**Angular version** - 1.6.5

**Comment by gkalpak** [comment] 2017-08-18 11:47
You are right, it is a bug (or at least, I believe it unintended behavior). The reason this happens is that in "date-family" directives, we [cache the timezone][1] in the directive's pre-linking phase, which comes before your `$overrideModelOptions()` call.

I think we shouldn't cache that value (or at least not until later). 

In the meantime, you can ensure your call happens before caching the timezone, by moving it in the pre-linking phase and giving your directive a higher-than-default priority:

```js
return {
  priority: 10,
  ...
  link: {
    pre: function ($scope, element, attrs, ngModel) {
      ngModel.$overrideModelOptions({...});
    }
  }
};
```

[1]: https://github.com/angular/angular.js/blob/7c876285cbfebf69a2ea64a216f903cf8d3803ee/src/ng/directive/input.js#L1434

**Comment by booblin** [comment] 2017-08-18 12:38
Yes, thank.
link pre override options when directive start, but for our business case we need change timezone (offset) in "online".

Now i use this solution
```
pre: (scope, element, attrs, ngModelCtrl) => {
  ngModelCtrl.$overrideModelOptions({
    timezone: 'utc'
  })
  ngModelCtrl.$parsers.push((value) => {
    let utc = moment.utc(value);
    let serverTimeZone = 'Europe/London'; // for example
    let tzOffsetMinutes = moment.tz(utc, serverTimeZone).utcOffset();
    let serverLocalDate = utc.subtract(tzOffsetMinutes, 'minutes');
    return serverLocalDate.toDate();
  })
}
```

**Closed** 2018-04-06 14:40 UTC
Labels: PRs plz!, component: forms, frequency: low, severity: inconvenient, type: bug
