### ISSUE TITLE
Angular messes up events on a select tag

### ISSUE THREAD

**Issue by blittle** [angular/angular.js#11901] opened 2015-05-18 23:48 UTC
Steps to reproduce:
  1. Look at http://jsbin.com/xazadekuti/3/edit?html,js,console,output
  2. Click on the empty text input
  3. Tab to the select input
  4. Press "i" key twice
  5. Notice that the second event does not fire (whether logged by angular, jquery, or native).

If I comment out all of the angular code, the event fires correctly. The problem exists in 1.3.x and 1.4.x. I can work around the problem apparently by putting a blank `<option></option>` tag at the start of the list.

**Comment by blittle** [comment] 2015-05-18 23:50
Tested in Chrome, FF, and Safari. Broken in Chrome and Safari.

**Comment by miraage** [comment] 2015-05-19 12:02
Reproduced jsbin example on Chrome 42, Kubuntu 14.04 - imo.

**Comment by Narretz** [comment] 2015-05-25 18:51
Hmm. One thing's weird. If you preselect an option via, say `ngModel = 'AL'`, it also works with angular.

**Comment by Narretz** [comment] 2015-05-25 19:06
This is a duplicate of https://github.com/angular/angular.js/issues/9134. When angular removes the "unknown" option from the DOM, Chrome somehow gets confused and doesn't fire a change event.

**Closed by Narretz** 2015-05-25 19:06 UTC
Labels: browser: chrome, component: forms, severity: broken expected use, type: bug
