### ISSUE TITLE
Infinite digest loop occurring on first run of app when running grunt server

### ISSUE THREAD

**Issue by jaredwilli** [angular/angular.js#10423] opened 2014-12-11 18:25 UTC
I tried to update my app to use 1.3.6 but when I do for some reason an infinite digest loop happens when I run grunt server and the app opens in the browser. It appears to redirect in the url bar over and over before it shows anything until finally it shows the page. Looking at the console I can see there are several errors for this.

```
Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
http://errors.angularjs.org/1.3.6/$rootScope/infdig?p0=10&p1=%5B%5D
    at http://localhost:9003/bower_components/angular/angular.js:63:12
    at Scope.$digest (http://localhost:9003/bower_components/angular/angular.js:14233:19)
    at Scope.$apply (http://localhost:9003/bower_components/angular/angular.js:14457:24)
    at bootstrapApply (http://localhost:9003/bower_components/angular/angular.js:1441:15)
    at Object.invoke (http://localhost:9003/bower_components/angular/angular.js:4169:17)
    at doBootstrap (http://localhost:9003/bower_components/angular/angular.js:1439:14)
    at bootstrap (http://localhost:9003/bower_components/angular/angular.js:1459:12)
    at angularInit (http://localhost:9003/bower_components/angular/angular.js:1353:5)
    at HTMLDocument.<anonymous> (http://localhost:9003/bower_components/angular/angular.js:25995:5)
    at fire (http://localhost:9003/bower_components/jquery/dist/jquery.js:3073:30)
```

When I refresh the page though, it doesn't happen. Only on the first run of the app.

The last version of angular that it doesn't do this in is 1.3.3.

**Comment by mvpspl619** [comment] 2015-01-21 06:49
@jaredwilli Can you share the code somehow ? If you can't do Plnkr, how about bundling your code and shipping it to me ?

**Comment by Narretz** [comment] 2015-04-20 18:38
I have put this into the Icebox since there is no reproduction and there is no one lese experiencing this problem.

**Comment by gkalpak** [comment] 2015-05-29 19:13
I think I was able to reproduce it (it's a much broader usecase - nothing to do with grunt server).

Basically, (I think) it happens when you have an empty `$location#path` and try to set a `$location#hash` during the initial bootstrap apply (e.g. in a `run` block, or during the instantiation of a controller).

[Live reproduction][1]

--
This is happening since v1.3.6 and the problem is (afaict) in [ng/browser.js][2] on this line:

```js
location.hash = getHash(url);
```

This is what happens:

1. **Initial state:**
    - `location.href === 'http://example.com/index.html'`
    - `$location.path() === ''`
    - `$location.hash() === ''`

2. **Action:**
    - `$location.hash('foo')`

3. **Results into:**
    - `$location.url() === '##foo'`   <--- inserts empty path
    - `$location.absUrl() === 'http://example.com/index.html##test'`

4. **In turn results into:**
    - `location.hash = getHash('http://example.com/index.html##test')` (see [ng/browser.js][2])

Here is where the issue starts:

`getHash()` looks for the first `#` (if any) and returns the substring of the URL starting right after the first `#` (in this case, it will return `#test`). So, by calling `location.hash = '#test'` we really want to have `.../index.html##test` (notice the double `#`).
Unfortuntely, (at least on Chrome and FF that I tried) `location.hash` tries to be smart and handle values both _with_ and _without_ the leading `#`. I.e. `location.hash = 'foo'` is equivalent to `location.hash = '#foo'` and both will result into `.../index.html#foo`. (Essentially, in the former case it adds the `#` automatically since it was missing, but in the latter case it doesn't add a `#`, because it thinks it's already there.) 

(Assuming it works the same way in the rest of the supported browsers), the fix should be simple:

Just keep the leading `#` when setting `location.hash`. I.e. change `getHash()`'s [implementation][3] like this:

```js
function getHash(url) {
  var index = url.indexOf('#');
  //return index === -1 ? '' : url.substr(index + 1);
  return index === -1 ? '' : url.substr(index);
}
```

---
/cc @petebacondarwin (since you are currently working on `$location` issues) 

[1]: http://codepen.io/ExpertSystem/pen/oXBZGb?editors=101
[2]: https://github.com/angular/angular.js/blob/master/src/ng/browser.js#L158
[3]: https://github.com/angular/angular.js/blob/master/src/ng/browser.js#L64-L67

**Comment by petebacondarwin** [comment] 2015-06-15 09:16
@jaredwilli and @gkalpak - can you see if https://github.com/angular/angular.js/commit/91b602263b96b6fce1331208462e18eb647f4d60 fixed this?

**Comment by petebacondarwin** [comment] 2015-06-15 09:20
I see that it doesn't on the live reproduction.

**Comment by jaredwilli** [comment] 2015-06-15 13:49
I no longer have access to the code base that I was seeing this issue with. I have a different job now so can't test if this works.

**Comment by petebacondarwin** [comment] 2015-06-17 10:35
I have a fix for this, using @gkalpak's suggestion. Please can you review?

**Comment by gkalpak** [comment] 2015-06-17 12:31
#12145 seems to fix my live reproduction scenario.

**Closed** 2015-06-17 13:02 UTC
Labels: component: $location, severity: broken expected use, severity: regression, type: bug
