### ISSUE TITLE
$http.post can't manage errors

### ISSUE THREAD

**Issue by guimard** [angular/angular.js#14133] opened 2016-02-26 07:05 UTC
Hi all,
I've a REST server that returns a 400 error when something is wrong in request. This simple code fails:

    $http.post('notifications/actives', $scope.formPost).success(function(data) {
      console.log('ok');
    }).error(function(j,e)) {
      console.log('nok');
    });
error function is never launched. Angular responds this:

    Failed to load resource: the server responded with a status of 400 (Bad Request)
    angular.js:12722 TypeError: Cannot read property 'data' of undefined
        at angular.js:10498
        at processQueue (angular.js:14991)
        at angular.js:15007
        at Scope.$eval (angular.js:16251)
        at Scope.$digest (angular.js:16069)
        at Scope.$apply (angular.js:16359)
        at done (angular.js:10791)
        at completeRequest (angular.js:10989)
        at XMLHttpRequest.requestLoaded (angular.js:10930)

I'm using AngularJS 1.4.9 on a Debian/Testing.

**Comment by gkalpak** [comment] 2016-02-26 08:14
It's not possible to say what might be going on without more context. (Could be a misbehaving responseError interceptor ?)
Please, provide a live reproduction of the issue (e.g. using CodePen, Plnkr etc).

**Comment by KegDemon** [comment] 2016-02-29 19:16
Per the docs:

> The $http legacy promise methods success and error have been deprecated. Use the standard then method instead. If $httpProvider.useLegacyPromiseExtensions is set to false then these methods will throw $http/legacy error.

**Comment by guimard** [comment] 2016-02-29 21:45
On 29/02/2016 20:19, Max Kunowski wrote:
> Per the docs:
> 
>     The $http legacy promise methods success and error have been
>     deprecated. Use the standard then method instead. If
>     $httpProvider.useLegacyPromiseExtensions is set to false then these
>     methods will throw $http/legacy error.

OK, thank you !

**Comment by Narretz** [comment] 2016-03-15 12:45
Closing due to lack of reproduction.

**Closed by Narretz** 2016-03-15 12:45 UTC
Labels: component: $http, needs: more info
