### ISSUE TITLE
Smooth scrolling issues on web

### ISSUE THREAD

**Issue by Acidfabric** [angular/angular.js#13055] opened 2015-10-08 20:57 UTC
Can anyone explain me, why my webpage have scrolling issues on mac safari when I click the link? Same is on ipad: chrome & safari apps crashes on scrolling. Otherwise chrome at mac have not this problem: it looks like everything working perfect here. http://tailorshop.tk/dist/

This is scrolling directive:

```
.directive('scrollOnClick', function () {
  return {
    restrict: 'A',
    link: function(scope, element, attrs) {
      var mainbody = $("html, body");
      var idToScroll = attrs.href;
      element.on('click', function() {
        var $target;
        if (idToScroll) {
          $target = $(idToScroll);
        } else {
          $target = element;
        }
        mainbody.animate({scrollTop: $target.offset().top}, "slow");
      });
    }
  };
});
```

**Comment by Narretz** [comment] 2015-10-12 17:44
Sorry, there's not enough info to assess this issue. It could be many different things. Are you using jquery for animation? You can  try by generating a minimal demo (that preferably doesn't use jquery) and putting it on a plnkr.co or similar so the issue can be reproduced. But from first glance I'd say it doesn't look like an angular problem

**Comment by Acidfabric** [comment] 2015-10-12 17:55
Tried to comment owlcarousel2 and now everything are working perfect. Could it be problem in carousel?
I made controller with perference like this:
```
angular.module('tailorApp')
  .controller('OwlCtrl', function ($scope) {
    $scope.owl1 = {
	  lazyLoad: true,
 		items: 1,
 		loop: true,
 		autoplay: true,
 		autoplayTimeout: 3000,
 		autoplayHoverPause: true,
 		margin: 1
	};
	$scope.owl2 = {
		lazyLoad: true,
 		loop: true,
 		autoplay: true,
 		autoplayTimeout: 3000,
 		autoplayHoverPause: true,
 		margin: 5,
        responsive : {
            // breakpoint from 0 up
            0 : {
                items : 2
            },
            // breakpoint from 480 up
            480 : {
                items : 3
            },
            // breakpoint from 768 up
            768 : {
                items : 4
            },
            960 : {
                items : 6
            }
        }
    };
  });
```

and then just used this directive:

```
angular.module('tailorApp')
  .directive('owlCarousel', function () {
	return {
	  restrict: 'A',
	  scope: {
		owlOptions: '='
	  },
	  link: function (scope, element) {
		element.owlCarousel(scope.owlOptions);
	  }
	};
  });
```

**Comment by Narretz** [comment] 2015-10-12 19:19
Then you should check if the problem also occurs if you have only have owl-carousel without any angular.

**Comment by Narretz** [comment] 2015-10-15 11:47
Closing because it's likely not a problem with angular.

**Closed by Narretz** 2015-10-15 11:47 UTC
Labels: needs: more info
