### ISSUE TITLE
Lexer.isIdent refuse valid identifiers

### ISSUE THREAD

**Issue by antonellopasella** [angular/angular.js#14195] opened 2016-03-07 22:51 UTC
BUG: valid JavaScript variable identifiers are not allowed in templates

For example
```
<input ng-model="ui.Φui" />
```
throws an error
```
angular.js:13236 Error: [$parse:lexerr] Lexer Error: Unexpected next character  at columns 3-3 [Φ] in expression [ui.Φui]
```

ES5 says (http://es5.github.io/x7.html#x7.6) that a valid identifier starts with
```
IdentifierStart ::
UnicodeLetter
$
_ 
\ UnicodeEscapeSequence
```

But Lexer (https://github.com/angular/angular.js/blob/4883e957971f1c551a0f560427bba0224f291449/src/ng/parse.js#L197) only checks:
```
isIdent: function(ch) {
    return ('a' <= ch && ch <= 'z' ||
            'A' <= ch && ch <= 'Z' ||
            '_' === ch || ch === '$');
  },
```

In chrome console this is valid code
```
var ui = {};
ui.Φui = 2;
```

**Comment by gkalpak** [comment] 2016-03-08 00:50
Angular's parser is not supposed (and not trying) to be a full-blown JavaScript parser. Thus, Angular expressions are a subset of JavaScript expressions (there are many more things other than non-latin characters that are not supported in Angular expressions).

The god news is that adding support for extending the identifiers recognized by the parser might be added soon. This is tracked in #12896.

**Comment by gkalpak** [comment] 2016-03-08 00:51
Closing as this is so by design.

**Closed by gkalpak** 2016-03-08 00:50 UTC
