### ISSUE TITLE
$q.when(value)'s promise does not get resolved when manually trigger a digest cycle from tests

### ISSUE THREAD

**Issue by yklee1013** [angular/angular.js#14028] opened 2016-02-13 00:15 UTC
I'm using Jasmine/Karma to test an angular app, the function I'm testing looks something like this:

```
function foo() : ng.IPromise<SomeInterface>{
  var promise : ng.IPromise<SomeInterface> = returnedFromSomeAPI();
   return promise.then((data : SomeInterface) => {
           return this.$q.when(data.someAttribute);
    })
}
```

My test triggers $rootscope.$apply() right after calling foo(), but for some reason the promise inside of "this.$q.when(data.someAttribute);" does not get resolved with value. I tried triggering two digest cycles right after(one for promise.then and another for resolving promise inside of when()), but it still didn't work. 

I'm using Angular.js 1.3. Is this a bug?

**Comment by gkalpak** [comment] 2016-02-13 14:37
I couldn't reproduce it on `v1.3.0`. Could it be that `returnedFromSomeAPI()` does not return a `$q` promise or that it is rejected (not resolved) ?

If not, please post a live reproduction (e.g. using CodePen, Plnkr etc).

**Comment by Narretz** [comment] 2016-04-06 15:48
I'm going to close this issue because we have no reproduction of the issue. Feel free to reopen this issue if you can provide a reproduction (ideally a runnable demo in a https://plnkr.co or similar).

**Closed by Narretz** 2016-04-06 15:48 UTC
Labels: component: $q, needs: more info, severity: broken expected use, type: bug
