### ISSUE TITLE
Binding ignores object keys that begin with '$'

### ISSUE THREAD

**Issue by uriva** [angular/angular.js#14057] opened 2016-02-16 10:21 UTC
Codepen:
http://codepen.io/uriva/pen/mVoQZg

**Comment by Narretz** [comment] 2016-02-16 10:28
1. leading $ and $$ are public / private API indicators and you should not use them in your objects for that reason
2. The codepen doesn't show the problem
3. The pen is using a very old version of angular - it shouldn't matter in this case, but please always test with the latest stable.

**Comment by uriva** [comment] 2016-02-16 10:57
Fixed codepen.

**Comment by uriva** [comment] 2016-02-16 11:12
Related to #1463

**Comment by Narretz** [comment] 2016-02-16 11:22
Duplicate of https://github.com/angular/angular.js/issues/6266 Atm, we don't have plans to fix this and I've recently updated the repeat docs to reflect this.

**Closed by Narretz** 2016-02-16 11:22 UTC
