### ISSUE TITLE
response.data is always converted to string under Chrome

### ISSUE THREAD

**Issue by msummers-intrax** [angular/angular.js#13374] opened 2015-11-25 03:25 UTC
Downloading Word & PDF docs via a REST API response.data is always converted to string and the extended characters are 'decoded'. This only happens on Chrome, Firefox & IE (current) work as expected. 

Angular 1.3.14 & 1.4.8
Chrome Version 46.0.2490.86 m (64-bit)
Windows 8.1

As this maybe an XMLHttpRequest problem I've also reported it to Chrome.

```
            var _config = {
              responseType: 'arraybuffer'
            };

           var success = function (data, status, header, config) {
             $log.debug('Download resume success ');
             var _contentType = (header('Content-Type'));
             _contentType = _contentType.substring(0,_contentType.indexOf(";"));
             var blob = new Blob([data], {type: _contentType});
             var url = (window.URL || window.webkitURL).createObjectURL(blob);
             var anchor = angular.element('<a/>');
              anchor.attr({
              href: url,
              target: '_blank',
              download: _fileName
              })[0].click();
            }

            var error = function (e) {
               if(e != null) {
                 bootbox.alert('Error encountered when downloading resume ');
                 $log.debug('Downloading error ' + JSON.stringify(e));
               }
            };

           $http.get(_url, _config).success(success).error(error);
```

**Comment by petebacondarwin** [comment] 2015-11-25 10:25
I cannot reproduce this issue. Here is a more complete example.
To test it you need a local HTTP server and a test PDF file that is called `test.pdf` in the same folder as the index.html.

```html
<!DOCTYPE html>
<html>
<head>
  <script src="https://code.angularjs.org/1.4.8/angular.js"></script>
  <script type="text/javascript">
    angular.module('app', [])

    .run(function($http, $log) {
      var _url = 'test.pdf';

      var _config = {
        responseType: 'arraybuffer'
      };

      var success = function (data, status, header, config) {
        $log.debug('Download resume success ', data);

        var _contentType = header('Content-Type');
        _contentType = _contentType.substring(0,_contentType.indexOf(";"));

        var blob = new Blob([data], {type: _contentType});
        var url = (window.URL || window.webkitURL).createObjectURL(blob);

        var anchor = angular.element('<a></a>');
        anchor.attr({ href: url, target: '_blank', download: 'test.pdf' });
        anchor[0].click();
      };

      var error = function (e) {
        if(e != null) {
           bootbox.alert('Error encountered when downloading resume ');
           $log.debug('Downloading error ' + JSON.stringify(e));
        }
      };

       $http.get(_url, _config).success(success).error(error);
     });
  </script>
</head>
<body ng-app="app">
</body>
</html>
```

**Comment by msummers-intrax** [comment] 2015-11-26 21:13
@petebacondarwin What 'more info' do you need? What version of Chrome & OS are you running on?

Thanks-- Mike

**Comment by petebacondarwin** [comment] 2015-12-07 21:08
@msummers-intrax I am running Chrome 47.0.2526.73 (64-bit) on OS/X 10.11.1
Are you saying it only happens on Chrome 46?

You should be able to test if it is a Chrome specific issue (and not Angular) but using HttpRequest directly.

Can you provide a link to the issue on the Chrome issue tracker?

**Comment by Narretz** [comment] 2016-06-03 19:40
I'm going to close this issue because we haven't got any feedback. Feel free to reopen this issue if you can provide new feedback.

**Closed by Narretz** 2016-06-03 19:40 UTC
Labels: browser: chrome, component: $http, frequency: low, needs: more info, type: bug
