### ISSUE TITLE
Shouldn't prevent default on forms.

### ISSUE THREAD

**Issue by fabiocarneiro** [angular/angular.js#11495] opened 2015-04-02 17:02 UTC
Since ```action=""``` is invalid HTML5 markup, and Angular.js prevents the default submit when action attribute is not set, there is no way of using the document address with valid html5 markup when using angular.

Please create a property that must be set on the forms to enable this preventDefault behavior.

**Comment by Narretz** [comment] 2015-04-02 22:12
I'm not sure what you are trying to do actually. Can you elaborate?

**Comment by fabiocarneiro** [comment] 2015-04-02 22:26
I'm trying to submit the form to the document address. Angular adds a preventDefault and the form is not submited, which makes it impossible to use the valid markup.

# valid markup
```html
<form>
</form>
```

# invalid markup
```html
<form action="">
</form>
```

**Comment by Narretz** [comment] 2015-04-02 22:35
Ah okay I see. Well, that's inconvenient. Does it work, for purpose of validation and submission, if you put in a `#` into the action property?

**Comment by gkalpak** [comment] 2015-04-02 22:52
There is an easy work-around if anyone is interested:

Since the condition for preventing the default form action is `$attrs` not having an `action` property, you can manually put an `action` property on the Attributes object without adding an `action` attribute on the element.

E.g. to have this work-around automatically applied on all forms with a `method` attribute:

```js
.directive('method', function () {
  return {
    priority: 1,   // To run before the default `form` directive
    restrict: 'A',
    compile: function (_, tAttrs) { tAttrs.action = undefined; }
  };
})
```

[Demo][1]

[1]: http://codepen.io/ExpertSystem/pen/Pwgypz?editors=101

**Comment by gkalpak** [comment] 2015-04-02 22:57
Of course, @Narretz's suggestion of having `action="#"` (or even `action="?"`) does work, but messes with your URL, so might not be appropriate for some usecases.

**Comment by fabiocarneiro** [comment] 2015-04-03 21:38
> if you put in a # into the action property?

Actually the HTML5 specification says that:

> The action and formaction content attributes, if specified, must have a value that is a valid non-empty URL potentially surrounded by spaces.

```action="#"``` and ```action="?"``` and  ```action=""``` are all invalid markup

You must either set a valid url, or do not use the attribute at all.

**Comment by Narretz** [comment] 2015-04-04 11:53
So basically the problem is that a HTML validator will say that the document is invalid, yes?
I rather not make "no prevent default" the default behavior, because most people don't use html form submission with angular, but ajax requests. Suggestion: allow default form submission behavior even if no action attribute is set.

**Comment by gkalpak** [comment] 2015-04-04 18:12
Default form submission should definitely not be the default. 

How about not preventing the default only if there is a `method` attribute.
The truth is though, that I would prefer having an explicit flag attribute foralliwing the default behaviour.

**Comment by fabiocarneiro** [comment] 2015-04-04 20:20
I don't think angular should mess with how forms are submitted by default at all. The best approach is to create a new attribute like "data-ng-form" and people that want the forms to be handled by angular set it.

The problem isn't the validation itself, but that may be other frameworks being used (which is exactly what is happening to me) that are HTML5 compliant, and then you're creating an incompatibility between those frameworks by not following the standard.

Good code, usually do nothing that changes the default behavior unless explicit configured to do so.

**Comment by pkozlowski-opensource** [comment] 2015-04-04 20:23
> Good code, usually do nothing that changes the default behavior unless explicit configured to do so.

But AngularJS was designed for SPAs where not submitting forms is a default behaviour.... So I guess it really comes down to what one means by "default" and what are the expectations.

While I understand that people might want to have this "default" to be configurable, I don't think we should change the current behaviour "default" behaviour.

**Comment by fabiocarneiro** [comment] 2015-04-04 21:01
Being designed for SPA doesn't necessarily mean it needs to force behaviors. These behaviors might still be optional and being optional is always an advantage. By adding a form attribute ppl will still be able to achieve the same behavior, but with the advantage of not affecting ppl that doesn't want that behavior.

**Comment by gkalpak** [comment] 2015-04-05 08:59
> Being designed for SPA doesn't necessarily mean it needs to force behaviors.

I think we all agree on that; that's why we are trying to figure out the best way to allow the developer to choose their preferred behaviour.

> These behaviors might still be optional and being optional is always an advantage. By adding a form attribute ppl will still be able to achieve the same behavior, but with the advantage of not affecting ppl that doesn't want that behavior.

This also applies to the _other_ (non-spa default) behaviours.

--
The question is what should be an Angular default and what should be an opt-in alternative.

Considering that:

1. The great majority of people building SPAs, does not want the default submit

2. Angular is not a general purpose JS lib, it is a SPA framework, so just including it in the page you are making an explicit choice. It should support the most common behaviour out of the box and be configurable for edgecases (not the other way around)

3. It would be a major breaking change, affecting almost every app and possibly third-party dependencies

I believe that the default form behaviour remains unchanged and we add a way to opt-out (e.g. either by explicitly adding a special attribute or by automatically detecting a `method` attribute (indicating the users intention to use the default submit behaviour)).

**Comment by pkozlowski-opensource** [comment] 2015-04-05 09:17
+1 @gkalpak

**Comment by lgalfaso** [comment] 2015-04-05 10:44
Hi, I see this conversation being fruitless, just stating that this is not valid html markup is really not a good reason. All browsers fail to follow the standard in one way or another and this does not prevent people from using and libraries like Angular to have to workaround their limitations.

If you want the `form` directive not to prevent the default behavior and keep the markup valid, then just do `<form x-action=""></form>` there is no need to argue that X is more or less /pure/.

I think the current behavior is the right one and that this issue should be closed as wont fix.


BTW
> action="#" and action="?" and action="" are all invalid markup

action="?" is a valid markup

http://www.w3.org/TR/html5/forms.html#attributes-for-form-submission reads
The action and formaction content attributes, if specified, must have a value that is a valid non-empty URL potentially surrounded by spaces.

A string is a valid non-empty URL potentially surrounded by spaces if, after stripping leading and trailing whitespace from it, it is a valid non-empty URL.

A string is a valid non-empty URL if it is a valid URL but it is not the empty string.

A URL is a valid URL if it conforms to the authoring conformance requirements in the URL standard. [URL]

The W3C URL specification defines the term URL, various algorithms for dealing with URLs, and an API for constructing, parsing, and resolving URLs. Developers of Web browsers are advised to keep abreast of the latest URL developments by tracking the progress of https://url.spec.whatwg.org/

Then https://url.spec.whatwg.org/ reads
4.1. URL writing
[...]
A relative URL must be either a scheme-relative URL, an absolute-path-relative URL, or a path-relative URL that does not start with a scheme and ":", optionally followed by a "?" and a query.

A path-relative URL must be zero or more path segments separated from each other by a "/".

This is, the string "?" is not the empty string, it has zero path segments and is followed by a "?"

**Comment by fabiocarneiro** [comment] 2015-04-06 05:15
Despite the ? and # being valid URLs, the point here is that angular is using ```action=""```  as opt-out, which is invalid markup and this is clear. 

Also it makes much more sense to enable some behavior than disable it. If you can have angular features working in non-SPA, why not avoid creating behaviors that change the default html one?

__Couldn't you guys consider this change for the next major and create a new opt-out attribute in this release?__

Imagine i have a full application with thousands of forms and they're all using document address as form action (with no action attribute). Then i want to migrate some parts of my application to angular and this part has for example 1 form. Then now i have to add a unnecessary attribute or action to every single form in my application just to avoid some default behavior of angular. These other forms have nothing to do with angular.

Now i'll have to add this action or attribute to every single form i have, just to make sure their default behavior will not be prevented by angular.

**Comment by gkalpak** [comment] 2015-04-06 05:43
> Imagine i have a full application with thousands of forms and they're all using document address as form action (with no action attribute). Then i want to migrate some parts of my application to angular and this part has for example 1 form.

There are ways for limiting Angular to specific parts of your page. Angular will not parse the whole page, just the parts you specify as part of the Angular app.

> Then now i have to add a unnecessary attribute or action to every single form in my application just to avoid some default behavior of angular.

Speaking for myself, of course, but I would rather have **you** add an "unnecessary" attribute to every single form, than have **you** (once fully migrated) and **every other** regular Angular user add an "unnecessary" attribute to every single form to get the reasonable (for SPAs) behaviour.

--
Anyway, as @lgalfaso pointed out, this discussion isn't going anywhere.
And with the `x-action`/`data-action` alternatives in place, I too vote for closing as _won't fix_.

**Comment by fabiocarneiro** [comment] 2015-04-06 06:39
> And with the x-action/data-action alternatives in place,

data-action is valid, but i wasn't able to validate x-action. Also, this is used to create attributes that are not part of the HTML5 standard. In this case, we're discussing the erroneous change of some attribute behavior that is part of HTML5.

> but I would rather have you add an "unnecessary" attribute to every single form, than have you (once fully migrated) and every other regular Angular user add an "unnecessary"

In this case since i'm using the default HTML5 behavior, i shouldn't need to add anything. But since you're modifying the form behavior, then you have to enable a feature. Comparing my app to the SPA world is like comparing the SPA world to non-SPA world. Its almost the same to say that the default HTML5 document address behavior when no action attribute is set should be removed because there are some SPA applications that do not use it.

__Couldn't you guys consider this change for the next major and create a new opt-out attribute in this release (2.0)?__

You're viewing this change as a bc break, but forgetting that it would be a nice improvement, allowing non SPA applications to use angular (without dividing parts of the application or resetting default behaviors).

**Comment by lgalfaso** [comment] 2015-04-06 08:04
Hi, I am sorry that the current behavior will make you work on migrating your application to Angular, but the current behavior is considered the right one. Closing this issue

**Closed by lgalfaso** 2015-04-06 08:04 UTC
Labels: component: forms, needs: more info, severity: inconvenient, type: bug
