### ISSUE TITLE
Tolerances for ng-swipe-left & ng-swipe-right

### ISSUE THREAD

**Issue by patrickmarabeas** [angular/angular.js#5721] opened 2014-01-10 06:56 UTC
These needs to be dramatically increased. Currently, the user needs to swipe at less than ~10deg. This is just bad user experience. The user should not need to perfect a swipe to get the expected result.

`var MAX_VERTICAL_RATIO = 0.3;` is the variable in question. Even increased to `2`, vertical scrolling was in no way effected and expectation of my swipe performing as expected went from 40% to 90%.

`var MAX_VERTICAL_DISTANCE = 75;` Is very shallow. The longer the user's swipe, the greater the vertical discrepancy that needs to be allowed for.

**Comment by Narretz** [comment] 2016-01-26 14:11
Dupe of #4550

**Closed by Narretz** 2016-01-26 14:11 UTC
Labels: component: ngTouch, frequency: moderate, type: bug
