### ISSUE TITLE
`shortTime` date filter is not working properly under Chrome 67

### ISSUE THREAD

**Issue by clauzf** [angular/angular.js#16612] opened 2018-06-25 10:17 UTC
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**

`shortTime` filter returns different results under Chrome 67 comparing to other browsers.
```
Chrome 67: 8:35 AM
Firefox 60: 8:30 AM
IE11: 8:30 AM
```

Sample codes:
```
<!doctype html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <script src="//code.angularjs.org/snapshot/angular.min.js"></script>
</head>

<body ng-app>
  <span>{{'1900-01-01T08:30:00+08:00' | date:"shortTime"}}</span>
</body>

</html>
```

**Expected / new behavior:**

It should return the same result under Chrome 67.

**Minimal reproduction of the problem with instructions:**

https://plnkr.co/edit/4AI4K3ShFsrJjBDh0JUd?p=preview

**AngularJS version:** 1.x.y

Latest.

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 67.

**Anything else:**

One dev in our team hasn't updated his Chrome (v 66). He gets the correct result.

**Comment by Narretz** [comment] 2018-06-25 10:39
Hm, I get `1:30` in both FF and Chrome. So the minute part is correct. I've tested on Windows 10, `Version 67.0.3396.87 (Offizieller Build) (64-Bit)`

**Comment by clauzf** [comment] 2018-06-25 11:08
Hi @Narretz, I just tried with a different system timezone. UTC, +0100 doesn't have this issue. Try change system timezone to +0200 +0600 +0800, etc. 

```
+0200 2:53 AM
+0600 5:37 AM
+0800 8:35 AM
```

`Version 67.0.3396.87 (Official Build) (64-bit)`

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36`

**Comment by Narretz** [comment] 2018-06-25 12:08
Ok, I can see it. The date changes to the "correct" minutes in 1931 with offset +0200. This StackOverflow question (first answer) indicates that this is intended behavior, as historic timezones are very complex and Chrome has implemented a change to the ECMA Script spec: https://stackoverflow.com/questions/50609860/browsers-time-zones-chrome-67-error

I'll propose closing this as it works as expected.

**Comment by clauzf** [comment] 2018-06-25 14:49
Thanks. Wow. This really should be marked as a breaking change. 
Also, it might be an incorrect implementation from Chromium team. 

My understanding is when calling `new Date('...')`, if timezone info is missing, it should be filled based on the info from the IANA database. Like Dublin has a -0:25 timezone offset until Aug 2, 1880, but it's 0:00 ever since Oct 1, 1916.

My example has a vital difference from the StackOverflow example, it has timezone info embedded.
`Date()` shouldn't override the timezone based on IANA database.

```javascript
var x = new Date('1900-01-01T08:30:00+08:00')
x.getTimezoneOffset() // Firefox: -480; Chrome 67: -485;
```

I agree it's safe to close this ticket.

**Comment by Narretz** [comment] 2018-06-25 14:57
Ok, I will close it. 
If you open a ticket with the Chrome bug tracker, you can link it from here for reference.

**Closed by Narretz** 2018-06-25 14:57 UTC
Labels: browser: chrome

**Comment by clauzf** [comment] 2018-06-25 15:44
Ref: https://bugs.chromium.org/p/chromium/issues/detail?id=849404
