### ISSUE TITLE
memory leak in using $compile

### ISSUE THREAD

**Issue by SudhakarSundar** [angular/angular.js#13842] opened 2016-01-25 22:34 UTC
My application uses a tab management which will have forms being customized for each tabs for the selected item. so far each tab a new DOM will constructed using the $compile attached the code for the same

```js
var cachedFomObj = $templateCache.get(name+"_"+FA);
		if(angular.isUndefined(cachedFomObj)){
			var serviceObj = this;
			serviceObj.get(templateURL).success(
				function(data, status, headers, config) {
					var templateHTML = data;
					serviceObj.get(configUrl).success(
					function(data, status, headers, config) {
						if(childScope != null){
							childScope.$destroy();
						}
						//Create  a new scope that inherits from our current scope
					    childScope = scope.$new();					    
						var configObj = data.fields;
						cachedFomObj = serviceObj.getFormObj(configObj, templateHTML, name);
						$templateCache.put(name+"_"+FA, cachedFomObj);
						$templateCache.put(name+"_"+FA+"_configobject", configObj);
						node.empty().append(cachedFomObj);
						cachedFomObj.on('$destroy', function() {
							  console.debug("destroying child scope");
						      if (childScope != null) {
						           childScope.$destroy();
						           childScope = null;
						       }
						   });
						
						$compile(cachedFomObj)(childScope);
						
					}).error(function(data, status, headers, config) {
						console.debug("Error occurred while fetching template");
					});
				}).error(function(data, status, headers, config) {
				console.debug("Error occurred while fetching template");
			});
```

the main problem is the $compile which internally occupies memory(around 20 to 30 MB) on each call and not getting released, I wanted to know how to handle this memory leak, referring some forums I implemented childscope but still I see the same problem, so if I continuously use the system switching around the tabs within my application it occupies 1GB of memory in the browser, looking for a solution inregard to this. Thanks in advance

**Comment by gkalpak** [comment] 2016-01-26 09:24
@SudhakarSundar, would you be able to provide a minimal live demo of the issue (e.g. using CodePen, Plnkr etc). It's difficult to find the problem, if we can't reproduce it (and the code you provided is _not_ sufficient for a reproduction).

Some more info that would also help:

* What versions of Angular have you tried/are affected by this ?
* What browsers/OSes have you tried/are affected by this ?

**Comment by petebacondarwin** [comment] 2016-01-26 09:38
Also this code snippet is incomplete. What do you do if the `cachedFomObj` is found in the cache? Also, what does `serviceObj.getFormObj` do?
I suspect that this is not a memory inside Angular core but a result of your application holding onto a DOM node or other object unnecessarily.

**Comment by SudhakarSundar** [comment] 2016-01-26 20:58
Hello Pete,

When the cachedFomObj is found in the cache I am still doing a compile to
have the various field binding happening properly.

The entire code snippet is given below



angular.module('Dynamic.Form').service('DynamicFormService',
DynamicFormService);
function DynamicFormService($http, $templateCache, $compile) {
var service = {};
var childScope = null;
service.get = function(url) {
return $http.get(url);
};
service.getCachedConfigObj = function(name){
return $templateCache.get(name);
};
var count = 0;

service.appendFormObj = function(configUrl, templateURL, name, FA,node,
scope){
var cachedFomObj = $templateCache.get(name+"_"+FA);
if(angular.isUndefined(cachedFomObj)){
var serviceObj = this;
serviceObj.get(templateURL).success(
function(data, status, headers, config) {
var templateHTML = data;
serviceObj.get(configUrl).success(
function(data, status, headers, config) {
if(childScope != null){
childScope.$destroy();
}
//Create  a new scope that inherits from our current scope
   childScope = scope.$new();
var configObj = data.fields;
cachedFomObj = serviceObj.getFormObj(configObj, templateHTML, name);
$templateCache.put(name+"_"+FA, cachedFomObj);
$templateCache.put(name+"_"+FA+"_configobject", configObj);
node.empty().append(cachedFomObj);
cachedFomObj.on('$destroy', function() {
 console.debug("destroying child scope");
 if (childScope != null) {
          childScope.$destroy();
          childScope = null;
      }
  });
$compile(cachedFomObj)(childScope);
}).error(function(data, status, headers, config) {
console.debug("Error occurred while fetching template");
});
}).error(function(data, status, headers, config) {
console.debug("Error occurred while fetching template");
});
}
else{
if(childScope != null){
childScope.$destroy();
}
//Create  a new scope that inherits from our current scope
childScope = scope.$new();
scope.$on('$destroy', function() {
 console.debug("destroying scope");
 if (childScope != null) {
          childScope.$destroy();
          childScope = null;
      }
  });
node.empty().append(cachedFomObj);
$compile(cachedFomObj)(childScope);
cachedFomObj.on('$destroy', function() {
 console.debug("destroying child scope");
 if (childScope != null) {
          childScope.$destroy();
      }
  });
}
};

// configObj is an array which contains the fields required for the form to
be displayed based on the API response
service.getFormObj = function(configObj, templateHTML, name){ var fields =
configObj; var html = templateHTML; var form = $("<form
class=\"form-vertical\" style=\"margin-top:10px;\" name="+name+"></form>");
form.append($("<fieldset><div id='sid'></div></fieldset>")); for (key in
fields) { // get the form field by Id var formFieldId = "#" +
fields[key].field; var formField = $(html).find(formFieldId); // apply
style class for column length var newClasses = "col-md-" +
fields[key].columnSize*2 + " col-lg-" + fields[key].columnSize;
$(formField).addClass(newClasses); if(fields[key].mandatory ||
fields[key].systemMandatory || fields[key].userMandatory){ var str =
$(formField).find("label").text();
$(formField).find("label").text(str+"*"); }
form.find("#sid").append(formField); } return form; }; return service; }

The service.appendFormObj will be called from my controller for every new
request that comes in, so the problem Iam seeing here is every time this
function is called there is around 20 MB of increase in my browser memory
which is not getting released even if I navigate to different section of
the application. Looking forward for a solution. Thanks

On Tue, Jan 26, 2016 at 3:40 AM, Pete Bacon Darwin <notifications@github.com

**Comment by SudhakarSundar** [comment] 2016-01-26 21:01
FYI, Iam using angular 1.3.16 and browser is FireFox 38.5.0 and OS is
windows 7

On Tue, Jan 26, 2016 at 3:40 AM, Pete Bacon Darwin <notifications@github.com

**Comment by petebacondarwin** [comment] 2016-01-27 08:34
Can you try upgrading to 1.4.9 or even better try moving to 1.5.0-rc.2; we are close to releasing 1.5.0 and see if the memory leak still occurs?

**Comment by SudhakarSundar** [comment] 2016-01-27 14:11
Hello Pete,

Thanks for your response, I tried upgrading to 1.5.0-rc.2 and I still see
the same issue, the scope and the html element which we are trying to
compile is pretty large so for each compile it occupies around 20 to 40 mb
of memory, but my concern is why after the $compile(cachedFomObj)(childScope);
it is not able release the memory even if Iam out of this page and when I
call the same function for same data it again increases rather than
releasing the previously occupied memory which is a major concern, I also
tried emptying the htmlelement object( node.empty().append(cachedFomObj);)
but still it didnt helped, Please let me know what am I missing here.
Thanks.

Regards,

Sudhakar S



On Wed, Jan 27, 2016 at 2:37 AM, Pete Bacon Darwin <notifications@github.com

**Comment by petebacondarwin** [comment] 2016-01-27 14:33
I think you problem is that you are reusing the same DOM node, on each compile. So effectively you are compiling and linking the same DOM over and over again. When DOM is compiled and linked it has data attached to the nodes, which I expect it not being released when you recompile.
How about you try caching only the HTML string that you built, or alternatively cloning (deeply) the cached DOM before compiling.

**Comment by SudhakarSundar** [comment] 2016-02-03 03:47
Hello Pete,

As mentioned I put the source in the plnkr(
https://plnkr.co/edit/QEGfSjchDJ3xuepB3QpS?p=preview) , the scope object
that will be passed to the dynamic form is pretty large in the actual
system and that the DOM that will be having is also pretty large and which
will have its custom directives, and the same function will be called again
and again for many forms to generate it dynamically, is anything can be
done to clear the memory which was occupied during thr previous compile, I
tried putting scope.destroy in all the custom directives but still I see
there is a memory accumulation over a period of time. Can you please let me
know is there any better way to fine tune this so as to release the memory
that is occupied in the previous compile. Thanks.

Regards,

Sudhakar S

**Comment by petebacondarwin** [comment] 2016-02-03 10:26
I believe that you need to release the DOM nodes that you have compiled rather than just compiling them again.

> How about you try caching only the HTML string that you built, or alternatively cloning (deeply) the cached DOM before compiling.

**Comment by SudhakarSundar** [comment] 2016-02-03 14:28
I remove the DOM every time before I call the compile, if you see the main
controller which has the code for the same

if($scope.activeFormId != ''){
            $('#'+$scope.activeFormId).children().remove();
        }

**Comment by petebacondarwin** [comment] 2016-02-03 16:24
There is a difference between detaching the DOM from the document and actually releasing it so that it can be garbage collected. I believe that you are taking the exact same set of objects (DOM nodes) and repeatedly calling `$compile` on them.

**Comment by SudhakarSundar** [comment] 2016-02-03 16:41
Can you please let me know how to release it. Thanks.

On Wed, Feb 3, 2016 at 10:27 AM, Pete Bacon Darwin <notifications@github.com

**Comment by petebacondarwin** [comment] 2016-02-04 06:22
This is appears not to be an issue with Angular and has turned into a support request. I'm afraid that this is not what the issue tracker is for. Please try posting your problem on the mailing list or StackOverflow.

**Closed by petebacondarwin** 2016-02-04 06:22 UTC
Labels: component: $compile, frequency: low, needs: more info, severity: memory leak
