### ISSUE TITLE
Non-assignable error thrown for literals

### ISSUE THREAD

**Issue by MoonStorm** [angular/angular.js#5951] opened 2014-01-23 10:09 UTC
Hi there,

The issue is simple and most likely only affects widget creators and consumers. 

Basically if I wanted to expose an optional parameter that is then used internally by my widget in a bidirectional databinding, I would use '=?' in the definition of the isolated scope. But this creates a very nasty restriction on the way the widget can be used. 

Going through the scenarios:
1. The attribute is not set. Inside the widget I can set it to a default value and use it. In this case changing the value from within won't cause problems.
2. The attribute is set to a variable. If the consumer changes the value then I can automatically see the change. Same goes vice-versa. Great.
3. The attribute is assigned to a literal. That means the consumer is not interested in listening for changes, but provides an initial value. Problem is, the widget is stuck with that value. Any attempt to change it fails with a non-assignable error. Angular should not throw exceptions in this case because it's inconsistent with the first scenario and more importantly this forces the consumer to set up a variable just for the purpose of using the widget and initializing one of its parameters, or the widget must somehow deal with the situation manually through a set of one or two listeners, depending whether the attribute is bound to a literal or not, which is not great.

**Comment by Narretz** [comment] 2015-11-03 21:32
Interesting. 1 1/2 years later, the issue manifests in a different way. When the scope binding is a literal, it will overwrite the value in the isolate scope whenever you try to set it in the isolate scope. I assume the update mechanism picks up the object literal as "new" because it cannot assign to it. Not sure if this behavior is intended.

**Comment by Narretz** [comment] 2017-02-22 19:00
I assume this has been working as intended for a while now.

**Closed by Narretz** 2017-02-22 19:00 UTC
Labels: component: $compile, frequency: low, severity: inconvenient
