### ISSUE TITLE
The quickstart page still referencing AtScript

### ISSUE THREAD

**Issue by fals** [angular/angular.js#11533] opened 2015-04-08 21:00 UTC
I was surfing arround the angular.io web site and I notice that It still referencing AtScript, at the page https://angular.io/docs/js/latest/quickstart.html.

Given this oficial document https://docs.google.com/document/d/11YUzC-1d0V1-Q3V0fQ7KSit97HnZoKVygDxpWzEYW0U/edit#heading=h.9kzwyri4iqho, Angular 2 will be based on TypeScript language.

This should be updated.

**Comment by pkozlowski-opensource** [comment] 2015-04-08 21:28
@fals the repository for the angular.io website is at https://github.com/angular/angular.io so this issue should probably be opened in there. 

Having said this, the currently Angular 2 is still in the process of being converted from AtScript -> TypeScript so referencing TS would be a bit misleading. This was already discussed: https://github.com/angular/angular.io/issues/14

Closing as duplicate of https://github.com/angular/angular.io/issues/14

**Closed by pkozlowski-opensource** 2015-04-08 21:28 UTC
