### ISSUE TITLE
Directive's element.$destroy callback not called on iOS

### ISSUE THREAD

**Issue by graywithanA** [angular/angular.js#12053] opened 2015-06-09 01:18 UTC
I've got an app running 1.3.15 and using UI-Router to manage states.  I've created a directive which uses a $destroy event listener on the directive's element.  I'm declaring the event listener in the directive's link function.  When navigating to a new state the this is working fine on all devices except those running iOS.  Switching the event listener to listen for the directive scope's $destroy event works everywhere including iOS.

Here's the code that doesn't work on iOS:

```javascript
element.on('$destroy', function() {
    player.off('loadedmetadata', emitLoaded);
    player.dispose();
    console.log('PLAYER DISPOSED');
});
```

And the code that does:
```javascript
scope.$on('$destroy', function() {
    player.off('loadedmetadata', emitLoaded);
    player.dispose();
    console.log('PLAYER DISPOSED');
});
```

**Comment by gkalpak** [comment] 2015-06-09 04:55
Could it be that iOS is **not** destroying the element for whatever reason (perf, leak, ...) ?
I don't know much about iOS, but this might not be an Angular issue.

**Comment by jmaynier** [comment] 2015-06-09 07:08
I have memory leak also only on iOS 8. I also use ui router ans the memory seems to be never released until the app crash (ionic + ui-router).

**Comment by gkalpak** [comment] 2016-06-02 09:13
Closing as there has been a while since anyone complained about it and there are indications that this was not an Angular issue. Feel free to re-open if this problem still exists and you are able to provide a reproduction (e.g. a live demo or a complete code sample + reproduction steps).

**Closed by gkalpak** 2016-06-02 09:13 UTC
Labels: browser: iOS, component: scopes, needs: investigation, severity: broken expected use
