### ISSUE TITLE
Different DOM when using template vs templateUrl with replace true

### ISSUE THREAD

**Issue by kopatsy** [angular/angular.js#10612] opened 2014-12-31 20:55 UTC
When repeating a directive with replace=true and a templateUrl, all the elements of the repeated directives end up in the last repetition.

The only difference between the two plnkr's below is that the first one is using templateUrl while the second one is using an inlined template. The rendering is however different.

With templateUrl (broken): http://plnkr.co/edit/c7jZSldkkQxzjNRZHcPZ
With template (working): http://plnkr.co/edit/aMm6eReAZ4C5WgrsMddD

**Comment by kopatsy** [comment] 2015-01-01 06:35
Unit test reproducing the issue: https://gist.github.com/kopatsy/a9083762cc8cf479b2d6

**Comment by nabaraz** [comment] 2015-01-02 21:41
I have faced similar issues on past. Wrapping ````ng-repeat```` element with ```div``` fixes it. Though I cant explain why.

**Comment by lgalfaso** [comment] 2015-01-03 16:30
there are a few previously reported issues on different variations of this. The main issue is that when `replace=true` and there is a directive at the top level of the directive that specifies `replace=true` or `transclude=element`, then the compilation runs into this issue. It is not a simple problem to solve, but it falls into the small variations that are present between the use of `template` and `templateUrl` that in many cases, just like this, are very hard to solve

**Comment by Narretz** [comment] 2015-01-06 21:30
So, the question is if we intent to fix these or simply document these edge cases

**Comment by Narretz** [comment] 2018-04-06 16:04
Duplicate of #14326

**Closed by Narretz** 2018-04-06 16:04 UTC
Labels: component: $compile, severity: broken expected use, type: bug
