### ISSUE TITLE
ng-repeat track by is broken

### ISSUE THREAD

**Issue by coli** [angular/angular.js#12506] opened 2015-08-05 19:47 UTC
See http://stackoverflow.com/questions/27780049/angular-js-ng-repeat-track-by-dynamic-collection

**Comment by lgalfaso** [comment] 2015-08-05 20:02
There are two aspects on `ngRepeat`:
* A `$watchCollection` on the expression
* The use of `track by` to define the ordering within the collection

The example fails on the first point, this is, the elements in the collection are new (previously never seen) elements. This works as expected. Closing.

**Closed by lgalfaso** 2015-08-05 20:02 UTC

**Comment by coli** [comment] 2015-08-06 22:56
@lgalfaso I thought tracking by id should have worked? Or at least I thought it worked before?

Eg:
```
item in f(a) track by item.id
```

Or is my memory failing me?

**Comment by lgalfaso** [comment] 2015-08-07 08:00
The ngRepeat watching algorithm changed from Angular 1.0 to 1.2, and this
is the same mechanism that is present in 1.4. I am not sure if you would
still have this issue with 1.0, but I think that you would run into the
same problem

**Comment by plestik** [comment] 2015-08-20 10:03
@lgalfaso Can we make this into a feature request? Have $watchCollection support `ng-repeat`'s `track by` instead of only supporting object equality checks? (Correct me if I'm wrong or if I should open another issue).

I have a lot of collections which are transformations from data from the backend. I don't want to add listeners/watches to cache the data, I just want the transformations to always run. However, currently, this causes an infinite digest.

**Comment by coli** [comment] 2015-08-20 15:15
I thought the whole point of track by was to handle the case where the function returns a new collection/object in the first place, plus I thought it was working when it was first introduced...

**Comment by lgalfaso** [comment] 2015-08-30 16:52
@plestik created  a POC that adds a third parameter to `$watchCollection` that adds a *valueExtractor* function to be able to get the value identity and then changed `ngRepeat` to add this value. The issue is that doing so breaks existing use cases. Specifically doing `ngRepeat` over primitives with `track by $index`. With this in mind, whatever patches are needed to add support for your case would be a lot more code that what I would be comfortable with.

If someone is willing to create a PR that solves this issue, I can take a look.

**Comment by plestik** [comment] 2015-08-31 06:28
@lgalfaso I'd love to have a look, a bit daunting but I can give it a s hot. Do you have anything I can build on? (Should this issue be re-opened?)

**Comment by lgalfaso** [comment] 2015-08-31 09:09
@plestik I do not think this issue should be reopened, at least not in the current state as `ngRepeat` is working as expected. I would be ok in opening a new issue that asks for a change in the current behavior of `ngRepeat` to handle the case at hand
