### ISSUE TITLE
directive.compile method reverses the controllers array in 1.4.8

### ISSUE THREAD

**Issue by peeter-tomberg** [angular/angular.js#13918] opened 2016-02-01 09:35 UTC
Seems like the controllers array is reversed in 1.4.8. The bug occoured in https://github.com/spongessuck/gm.datepickerMultiSelect/issues/37

Using angular 1.4.7 the controller I'm looking for is the first one. Upgrading to 1.4.8 and the controller I'm looking for is the last one. Couldn't find anything in the patch notes to explain this.

**Comment by Narretz** [comment] 2016-02-01 13:35
Thanks for reporting. I see that your directive is decorating another directive - which one is that? It also helps a lot if you can provide a minimal demo of the problem. I don't think this is a general problem, otherwise we would have tons of reports.

**Comment by Narretz** [comment] 2016-02-01 14:22
I've tried the plnkr that is linked in the multi datepicker select readme, but I can't reproduce the issue: http://plnkr.co/edit/iVSdXt?p=preview

**Comment by peeter-tomberg** [comment] 2016-02-02 09:13
An example of the error occouring at http://plnkr.co/edit/nNENrasVJV9LBF4pRUWm?p=preview 

It seems to be an issue when using directives to nest the date picker

**Comment by Narretz** [comment] 2016-02-02 10:29
The error in the plnkr happens in all 1.4.x versions, not only in 1.4.8. I assume it's a problem with the new controller in the datepicker.

**Comment by gkalpak** [comment] 2016-02-02 10:45
It happens until at least as back as `v1.2.29`.
Basically, as the warning in the console says, the `datepicker` has been deprecated and you should use `uibDatepicker` instead. [Updated demo][1]

But it's also an implementation fault in the `gm.datepickerMultiSelect` module's `datepicker` directive, that they don't account for the absence of an optional controller and try to access properties on it, even if not present. It's probably because `gm.datepickerMultiSelect` is an outdated version that is not compatible with the version of `ui.bootstrap` you are using.

--
In any case, closing as it's not related to core Angular.

[1]: http://plnkr.co/edit/ARUXhpxRH5EFGtlXmQsn?p=preview

**Closed by gkalpak** 2016-02-02 10:45 UTC
Labels: branch: 1.4.x, component: $compile, needs: more info, type: bug
