### ISSUE TITLE
Character replacement empties textfield for specific chars

### ISSUE THREAD

**Issue by eueumasl** [angular/angular.js#13620] opened 2015-12-23 12:30 UTC
Hello,

I've written a character replacer that replaces unwanted characters in a textfield with others. I'd created a directive and put it on the textfield.
```javascript
.directive('charreplacer', ['$parse', function($parse) {
    return {
      restrict: 'A',
      require: 'ngModel',
      link: function($scope, element, attr, ctrl) {
        ctrl.$parsers.push(function(value){
            value = value.replace(/[äÄáâàåæöÖóøüÜçÇéêèùûîíñßšµ¹²³€£¤¦,¨´¸¼½¾\s]/g, function(m) {
              return {
              'ä': 'ae',
              'Ä': 'Ae',
              'á': 'a',
              'â': 'a',
              'à': 'a',
              'å': 'a',
              'æ': 'ae',
              'ö': 'oe',
              'Ö': 'Oe',
              'ó': 'o',
              'ø': 'o',
              'ü': 'ue',
              'Ü': 'Ue',
              'ç': 'c',
              'Ç': 'C',
              'é': 'e',
              'ê': 'e',
              'è': 'e',
              'ù': 'u',
              'û': 'u',
              'î': 'i',
              'í': 'i',
              'ñ': 'n',
              'ß': 'ss',
              'š': 's',
              ' ': '-',
              'a': 'q',
              'µ': 'm',
              '¹': '1',
              '²': '2',
              '³': '3',
              '€': 'E',
              '£': 'L',
              '¤': '',
              '¦': '',
              ',': '',
              '¨': '',
              '´': '',
              '¸': '',
              '¼': '',
              '½': '',
              '¾': ''
            }[m];
        });
            ctrl.$setViewValue(value);
            ctrl.$render();
            return value;
        });
      }
    };
  }])
```

If I test it in Chrome everything is fine. In my Firefox 38.3.0 characters like `éèêáàâóîí` causing that the textbox will be empty. 
I've seen that the with these characters the replacement happens twice. One time normal, the second time, a empty String comes in.
The characters have to been written in the textfield. To copy and paste it into the textfield doesn't cause this bug.

**Comment by Narretz** [comment] 2015-12-23 13:23
When you are using $setViewValue inside a parser, it runs the whole parser / model update pipeline again before returning the new value. Please don't do this, as it can lead to unexpected behavior.
This should work: 
```
            ctrl.$viewValue = value;
            ctrl.$render();
```

And another thing: we only test against the latest version of "evergreen" browsers. So you should really update your Firefox to at least 38.7.0, which is the current  Extended Support Release. There was a bug in previous versions of Firefox that you seem to be hitting.

**Comment by eueumasl** [comment] 2015-12-23 14:28
I've updated my firefox to 43.0.2, but the error still occurs

**Comment by Narretz** [comment] 2015-12-23 14:34
I should have added that I couldn't reproduce the error. Can you please
create a demo with exact steps to reproduce? And have you tried my changes
to your directive?
Am 23.12.2015 15:30 schrieb "eueumasl" <notifications@github.com>:

**Comment by eueumasl** [comment] 2015-12-28 09:38
I was able to reproduce the error in an isolated project:
https://jsfiddle.net/gc0xae7z/

**Comment by eueumasl** [comment] 2016-01-12 08:25
@Narretz could you reproduce it with your Firefox?

**Comment by eueumasl** [comment] 2016-02-01 10:53
@Narretz Could you please have a look on this bug?

**Comment by Narretz** [comment] 2016-02-01 12:24
@eueumasl Sorry, I didn't see your update. Will look at it today.

**Comment by Narretz** [comment] 2016-02-01 13:57
So I'm using FF 44, and I cannot reproduce this issue. How do you enter these characters? On my German keyboard, I have to press ` first, then e, and the input is as expected output as e. I have also copy and pasted è and it's also converted to e.

**Comment by eueumasl** [comment] 2016-02-01 14:07
I'm using FF 43 and a German keyboard too. Copy and paste works fine and the é is converted to e. But pressing ´ and then e causes the textfield to be emptied.
I'm currently updating to FF 44 and will test it again.

**Comment by eueumasl** [comment] 2016-02-01 14:10
In FF 44 it sill occurs. Could it be that the operating system makes a difference? I'm using Ubuntu 14.04

**Comment by Narretz** [comment] 2016-02-01 14:15
Am 01.02.2016 um 15:12 schrieb eueumasl:
>
> In FF 44 it sill occurs. Could it be that the operating system makes a 
> difference? I'm using Ubuntu 14.04
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/angular/angular.js/issues/13620#issuecomment-177988330>.
>
Possibly, yes. I'm on Windows 7.

**Comment by gkalpak** [comment] 2016-06-03 20:19
Closing as there is no indication this is an Angular issue. Possibly a browser/OS combination bug.

**Closed by gkalpak** 2016-06-03 20:19 UTC
Labels: component: forms, needs: more info
