### ISSUE TITLE
ngList doesn't update viewValue if the modelValue is altered 

### ISSUE THREAD

**Issue by bogdanalexe90** [angular/angular.js#10679] opened 2015-01-08 12:39 UTC
The ngList doesn't update viewValue if the modelValue is altered.

If you change (not replace) the modelValue array returned by ngList, the directive doesn't update the viewValue.

Plunkr Example:
http://plnkr.co/edit/k2K0d1ITP7tsopdcj9KU?p=preview

**Comment by Narretz** [comment] 2015-01-08 15:46
Thanks for your report. This is a dupe of https://github.com/angular/angular.js/issues/1751. There's currently no timeline when this will be implemented, but we are aware of this.

**Closed by Narretz** 2015-01-08 15:46 UTC
