### ISSUE TITLE
Angularjs updates $scope.list but not $scope.list[index]

### ISSUE THREAD

**Issue by nielzzz1993** [angular/angular.js#15641] opened 2017-01-26 09:58 UTC
You can view the detailed question on stackoverflow
http://stackoverflow.com/questions/41851985/angular-scope-listindex-does-not-update

**Comment by gkalpak** [comment] 2017-01-26 10:28
Closing, because GitHub issues are reserved for bug reports and feature requests.
StackOverflow is better suited for these types of question.

**Closed by gkalpak** 2017-01-26 10:28 UTC

**Comment by nielzzz1993** [comment] 2017-01-26 10:33
but i think this might be some kind of bug. Because it isn't behaving like it supposed to be.

**Comment by gkalpak** [comment] 2017-01-26 10:37
Currently this doesn't look like a bug (at least not in Angular). If have verified that this is a bug in Angular, please post a minimal reproduction (with exact steps to reproduce the issue).

<sub>(But I am pretty sure this is not a bug in Angular :wink:)</sub>
