### ISSUE TITLE
Default multiple select not working

### ISSUE THREAD

**Issue by miffo** [angular/angular.js#12538] opened 2015-08-10 10:59 UTC
Using a default value on multiple select is not working in 1.4.3 
http://jsfiddle.net/miffo/7v740bLb/2/
It throws a error and does not reset the model.

It has been working in previous version (v1.2.10) not sure when it breaks.
http://plnkr.co/edit/jDijgjJ0EZLFUGIkTKDs?p=preview

I tested it on FF(39.0.3) Chrome(44.0.2403.130) and IE(11)

**Comment by Narretz** [comment] 2015-08-10 12:36
This is a duplicate of #12511

**Closed by Narretz** 2015-08-10 12:36 UTC

**Comment by Narretz** [comment] 2015-08-10 20:22
Hm, I just wondered. In 1.2.x, the empty / default value doesn't even exist if the select is multiple. So do you expect from the select  to display the `--choose one--` option? And if it is selected, the model should be set to an array?
