### ISSUE TITLE
Error using ngOptions with objects containing circular references

### ISSUE THREAD

**Issue by dubejf** [angular/angular.js#11372] opened 2015-03-19 14:27 UTC
The new `ngOptions` in Angular `1.4-beta` doesn't handle objects containing circular references well.

Steps to reproduce:
1. Define a `ng-options` with `ng-model`. At least one of the items in the source array must be a recursive object (such as a Breeze entity).
2. Select the recursive object.
3. *Uncaught RangeError: Maximum call stack size exceeded* is printed on the console.

http://jsfiddle.net/dubejf/tn102eh8/    (using `1.4.0-beta6`)

The watcher of `ngModel`, set by the `ngOptionsDirective`, compares the selected item with the last value by deep equality (using `angular.equals`). When a recursive object is selected, this causes the stack to blow up (as described in #7724).
 
Using `track by` doesn't alleviate the problem. 

This error is not reproducible in Angular 1.3.

**Comment by mgbee8** [comment] 2015-03-25 11:28
I can confirm and reproduce this error with Breeze entities, it was working correctly in beta5 but beta6 displays this behavior

**Comment by dubejf** [comment] 2015-03-25 15:11
You're right, it was broken by this commit: 6a03ca274314352052c3082163367a146bb11c2d

**Comment by booleanbetrayal** [comment] 2015-03-28 13:51
#11448 offers a way to work around this issue, provided you aren't trying to use `track by`

**Comment by petebacondarwin** [comment] 2015-03-31 07:23
Having landed #11448 I can see that this bug appears to be fixed: http://jsfiddle.net/L9vqc9ew/

**Comment by dubejf** [comment] 2015-04-11 15:24
Yes, this bug is fixed in `1.4.0-rc.0`, as long as you are not using `track by`. `track by` with cyclic objects still gives an error, but that regression seems less important.

In any case, with the recent performance optimizations to `ngOptions` (identity comparison, no copies), is it fair to say to `track by` should be *avoided* when using objects with `ngOptions`? As opposed to `ngRepeat`, where the guideline appears to be to use `track by` whenever possible.

**Comment by pranaydutta89** [comment] 2015-04-15 04:36
:+1:

**Comment by petebacondarwin** [comment] 2015-04-28 09:56
I think this is a better fix #11743

**Closed** 2015-04-29 13:31 UTC
Labels: component: forms, severity: regression, type: bug

**Comment by booleanbetrayal** [comment] 2015-04-29 13:51
@petebacondarwin - I think the select documentation also needs to be updated as well - https://github.com/angular/angular.js/blob/abf59c285c3ff6af20dbf4236eba5204ae735abb/src/ng/directive/select.js#L131-L133

**Comment by petebacondarwin** [comment] 2015-04-29 14:01
Yes that block is not valid in that directive anyway, since it references `ngOptions`

**Comment by petebacondarwin** [comment] 2015-04-29 14:02
@booleanbetrayal - Would you like to put together a PR with it removed/changed?

**Comment by booleanbetrayal** [comment] 2015-04-29 14:23
Sure thing

**Comment by booleanbetrayal** [comment] 2015-04-29 14:42
@petebacondarwin - https://github.com/angular/angular.js/pull/11758
