### ISSUE TITLE
Angular and http get json

### ISSUE THREAD

**Issue by onigetoc** [angular/angular.js#15835] opened 2017-03-21 02:43 UTC
I always have problem with http request to json files.

jQuery .ajax or .getJson work everytime. but with Angular you have to try multiples ways until you may finally find the right one to get that json file.
Alway the same thing.

With Angular you have to get used to see message like:
- XMLHttpRequest cannot load
- has been blocked by CORS policy
- No 'Access-Control-Allow-Origin' header is present on the requested resource
- Possibly unhandled rejection

I just did a php fille with json header and callback and it's alway work the first time with jQuery, but Angular, you have to try multiples bizarre things to get it work, 2 hours on it and it doesn't work, but 5 minutes with jQuery and it's done.

**Comment by gkalpak** [comment] 2017-03-21 08:28
Closing since this is not actionable. Happy to reopen and investigate if you can provide a way to reproduce the problem.

If this is a usage problem (and not an AngularJS issue/bug), you can use one of the [general support channels][1].

<sub>(FWIW, I've never heard of people having difficulties fetching JSON data with AngularJS. In fact there have been complains about it not being straight-forward to send/receive non-JSON data. That said, we are always interested in improving developer ergonomics if you can point out specific, reproducible problems/difficulties.)</sub>

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Closed by gkalpak** 2017-03-21 08:28 UTC
