### ISSUE TITLE
Warning and error while installing npm and run protractor

### ISSUE THREAD

**Issue by abhijit1978** [angular/angular.js#13117] opened 2015-10-18 06:12 UTC
![nodeinstallwarning](https://cloud.githubusercontent.com/assets/11061051/10562822/387eb6da-758d-11e5-82aa-d74d5c99674b.PNG)
![protractorerror](https://cloud.githubusercontent.com/assets/11061051/10562823/3bcd380c-758d-11e5-8cba-2006196c35db.PNG)
![protractorerror2](https://cloud.githubusercontent.com/assets/11061051/10562824/3dbb244e-758d-11e5-9286-c5d5e0acd1b7.PNG)

**Comment by abhijit1978** [comment] 2015-10-18 06:14
My node version v4.2.1
My npm version 2.14.7
Please help

**Comment by gkalpak** [comment] 2015-10-26 14:11
This doesn't seem directly related to Angular. It could be either [angular-phonecat][1]-related or [protractor][2]-related or (most probably) user setup/environment-related.

--
Please, use one of the [appropriate support channels][3] for support questions such as this.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

If it turns out to be a problem with Angular itself (or one of the aforementioned projects), open an issue (on the appropriate repo) with a description of how to reproduce it.

--
BTW, I tried `npm run protractor` on a fresh clone of `angular-phonecat` and didn't get any errors.
(Env: Windows 10 | node v4.2.1 | npm v2.14.7)

Closing, as it is not actionable atm. Feel free to re-open (as described above).

[1]: https://github.com/angular/angular-phonecat
[2]: https://github.com/angular/protractor
[3]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Closed by gkalpak** 2015-10-26 14:11 UTC
