### ISSUE TITLE
Invalid argument in IE when using $compile

### ISSUE THREAD

**Issue by Matsemann** [angular/angular.js#8659] opened 2014-08-18 19:54 UTC
A fiddle with a trivial example: http://jsfiddle.net/1t4crp6e/

````
<div ng-app="myApp">
    <div ng-controller="myctrl">
        <div test>the value is: {{testmodel}}</div>
        
        <br>
        <input type="text" ng-model="testmodel">
    </div>
</div>
....
link: function(scope, elm, attrs) {
            var standardText = elm.text();
            
            elm.html('something');
            
            $timeout(function() {
                console.log(standardText);
                elm.html('').append($compile('<span>' + standardText + '</span>')(scope.$parent));
            }, 2000);
        }
```


Wait 2 secs, see the content of directive change to a binding. In Firefox, everything works. In IE it *works*, but it throws a lot of errors in the console.
(Don't worry about what I'm doing here, I just made a small example showing the issue)

> Error: Invalid argument.
  at Anonymous function (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.22/angular.min.js:62:80)
   at k.prototype.$digest (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.22/angular.min.js:109:350)
   at k.prototype.$apply (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.22/angular.min.js:112:343)
   at Anonymous function (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.22/angular.min.js:18:158)
   at d (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.22/angular.min.js:34:474)
   at c (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.22/angular.min.js:18:66)
   at fc (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.22/angular.min.js:18:270)
   at Xc (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.22/angular.min.js:17:362)
   at Anonymous function (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.22/angular.min.js:214:78)
   at o (https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js:2:14725)

**However, most of my tries of actually writing this worked in all browsers *except* IE. For instance, if I remove the span in the compile, and instead of elm.text() use elm.contents().**
http://jsfiddle.net/1t4crp6e/1/ Only changed line 13 and 19 in the js, breaks horribly in IE. It's almost impossible to compile stuff in IE.

Am I doing something wrong? And any workarounds?

**Comment by just-boris** [comment] 2015-02-12 09:47
related issue https://github.com/angular-ui/ui-select/issues/276
solved same way that @kentcdodds

**Comment by Javarome** [comment] 2015-05-07 17:09
Had the same issue on the dynamic text of a button ; solved by kentcdodds' ng-bind workaround.

**Comment by kyro38** [comment] 2015-05-28 11:52
While there is a workaround. A fix would be welcome :)

**Comment by daniel-nalbach** [comment] 2015-07-02 21:09
I ran into a variant of this issue as well with Angular 1.2.15 with IE 11. It was caused by this dynamic button text:

`<button class="someclasses" ng-click="toggleSomething()">{{ showText ? 'Hide' : 'View' }} Some Text</button>`

The error was caused by the addTextInterpolateDirective function last compile line of:

`node[0].nodeValue = value`

When console logging the node, it had no text node and would error out in IE.
Moving the expression to an ng-bind resolved the issue.

**Comment by cassilup** [comment] 2015-07-07 07:44
I am also eagerly waiting for a fix to this issue.

Meanwhile, changing this:
````
    <button class="someclasses" ng-click="toggleSomething()">
        {{ showText ? 'Hide' : 'View' }} Some Text
    </button>
````
to this (notice the `ng-if`):
````
    <button class="someclasses" ng-click="toggleSomething()" ng-if="showText">
        {{ showText ? 'Hide' : 'View' }} Some Text
    </button>
````
fixes it for now.

Logic: `ng-if` adds/removes element from DOM based on the truthfulness of the expression. If the element doesn't exist in the DOM, IE won't complain if no text node is present on it. 

Downside: template code pollution.

**Comment by wawyed** [comment] 2015-09-03 12:42
Any updates on this issue?

**Comment by siemiatj** [comment] 2015-09-09 11:09
How about we just use this 3 line fix that I've posted and be done with it ?

**Comment by TombolaShepless** [comment] 2015-09-17 12:15
Also experiencing this issue, any word on a timescale for the fix proposed to be implemented?

**Comment by astreate** [comment] 2015-09-30 20:46
I'm seeing the same issue.  Is this going to be fixed soon?

**Comment by wombleton** [comment] 2015-10-06 22:29
If you're using webpack, I added this loader to solve this problem: https://www.npmjs.com/package/falafel-loader

**Comment by bogdanmatra** [comment] 2015-10-15 13:48
This approach fixed it for me. ---> empty().append() instead of html()
https://github.com/knalli/angular-translate/commit/c4b16d3524459f3cb0093f8aaea6790944d8455e

element.empty().append('<p>my html</p>');
$compile(element.contents())(scope);

instead of:

element.html('<p>my html</p>');
$compile(element.contents())(scope);

**Comment by willchen90** [comment] 2015-10-21 00:35
Would love to see an official fix for this as well. We are using this for a large-scale Angular app and the interim solutions will be a pain to use.

**Comment by wombleton** [comment] 2015-10-21 00:56
The actual solution for me was writing a test to fail if I wrote `placeholder="{{'foo'|translate}}"` in a template instead of `ng-attr-placeholder="{{'foo'|translate}}"`. <3 IE.

**Comment by silentHoo** [comment] 2015-11-02 10:02
+1 on that issue here, we also have a very large AngularJS app to maintain.

**Comment by kentcdodds** [comment] 2015-11-02 13:46
For people experiencing this issue, I would recommend you simply use the work-around of `ng-bind`. There are actually [a few reasons](https://twitter.com/chandeepkhosa/status/651746731747581953) it's better than `{{ }}` anyway.

**Comment by bogdanmatra** [comment] 2015-11-03 15:24
Hey `kentcdodds`, `ng-bind` can be a valid solution but when you have to use `$compile` on a lot of code changing all `{{ }}` to 'ng-bind' can be frustrating. The above solution fixed the issue for me. The difference in the jQuery implementation between `.html()` and `.empty().append()` seems to do the trick on IE for me.

**Comment by Narretz** [comment] 2015-11-03 23:11
I've tested the fix that @siemiatj provided, but it makes a ton of other tests fail, so we cannot use it. Given that there are plenty of workarounds for this issue, this issue doesn't have high priority. I'll invite you to build on the PR and find a solution, though: https://github.com/angular/angular.js/pull/13243

**Comment by rent-a-developer** [comment] 2015-11-12 23:15
Please correct me if I am wrong...

To me the observed behavior (the 'Invalid argument' error) does not seem like a bug in IE or in angular at all.

Lets examine the code in the opening post:

1. There is a div where a directive is applied to:
<div test>the value is: {{testmodel}}</div>

2. The div contains an angular expression:
{{testmodel}}

3. The directive then removes all child nodes of the div:
elm.html('something');

(You could also do elm.html("") or elm.empty())

So what happens here?

1. Angular must watch the scope variable "testmodell" for changes and must update the DOM node that contains the {{testmodel}} expression whenever the scope variable has changed.
So angular creates a watch for the {{testmodel}} expression, which means it must also keep a reference to the DOM node that contains the {{testmodel}} expression, to be able to update it when the scope variable has changed.

2. When the directive removes the DOM node (elm.html('something')) that contains the {{testmodel}} expression, angular does not know about the fact that this DOM node does not need to be updated anymore and that the watch for the expression should be removed.
It still holds a reference to the DOM node that contains the {{testmodel}} expression and the watch on the scope variable is still active.
But this DOM node (the text node containing {{testmodel}}) is no longer part of the DOM tree of the webpage.

3. When the scope variable has been changed angular tires to update the DOM node that is now not a part of the DOM tree of the web page, because the watch on the testmodel scope variable is still active.
Of course updating a detached (abandoned) DOM node is not a good idea.
However, this seems to work in browsers like Chrome or FF, but fails in IE.
It fails in IE for a good reason: The DOM node is not part of the DOM tree anymore (in some sense like a memory leak).

So to me it seems to not be a bug in IE or in angular, but rather in the code presented in the opening post.
One should not modify DOM nodes where angular watches exist on.
Instead angular should modify the DOM (via ng-if, ng-repeat, etc...), so it knows when removed DOM nodes do not need to be updated anymore.

However it's not always possible to let angular manage the DOM.
But when we modify the DOM directly, we must in some way notify angular about it.
The simplest way is to destroy the scope of removed DOM nodes.

So the solution would be to create a child scope for the DOM element that contains the {{testmodel}} expression.
When we remove that DOM node, we can call $destroy() on the child scope and angular knows it must not update the DOM node any longer.
Problem solved.

**Comment by Narretz** [comment] 2015-11-13 15:21
@rent-a-developer Thanks for investigating, I think you are right that this is actually expected behavior, it's just that many browsers tolerate it, while IE does not.
Thinking about it again, the example in the OP includes a bad practice: namely re-compiling already compiled and linked DOM nodes. The interpolated text node is already compiled and linked before it is removed from the DOM, and then it is recompiled, which not only makes IE complain, but also adds another watcher on the scope, which is bad for perf reasons.
If you want to extract text nodes / content from the DOM and re-compile it, you should either do it in the compile fn or make sure no other directive is executed before you do your stuff in the link fn:
http://jsfiddle.net/1t4crp6e/8/

@lgalfaso Do you agree that this is actually expected behavior?

**Comment by petebacondarwin** [comment] 2015-11-18 17:53
I agree with @Narretz - that if you are going to modify the contents of the node and potentially recompile then you should be doing this in the `compile` function and probably terminating the compilation too.
On top of that, whenever you intend to be recompiling elements during the application run then you need to create new scopes to ensure that they can be destroyed correctly to prevent leaks.

**Comment by Narretz** [comment] 2015-11-26 16:33
Based on the explanations of @rent-a-developer and @petebacondarwin and my recommendations, I will close this issue as "wontfix"

**Closed by Narretz** 2015-11-26 16:33 UTC
Labels: browser: IE11, component: $compile, frequency: moderate, severity: confusing, type: bug

**Comment by Cerbrus** [comment] 2015-12-01 10:50
I recently came across the same issue rendering a kendo treeview with an angular template.

The template used to be:

    <span k-template>
        <span id="{{dataItem.id + '_' + dataItem.entityType}}"
              ng-attr-title="{{dataItem.title}}">
            {{dataItem.text}}
        </span>
    </span>

Adding an `ng-if` in there fixed the issue:

    <span k-template>
        <span ng-if="dataItem"
              id="{{dataItem.id + '_' + dataItem.entityType}}"
              ng-attr-title="{{dataItem.title}}">
            {{dataItem.text}}
        </span>
    </span>

**Comment by askucher** [comment] 2016-02-03 22:57
+1

**Comment by Narretz** [comment] 2016-02-04 08:44
I'm going to lock this issue. Please see the explanations in https://github.com/angular/angular.js/issues/8659#issuecomment-156267569 and the recommended course of action in https://github.com/angular/angular.js/issues/8659#issuecomment-157800230.
If you see any 3rd party module doing this (re-compiling a node), then this is a problem that should be pointed out to them.
