### ISSUE TITLE
$templateCache is executed after my http interceptors

### ISSUE THREAD

**Issue by fromi** [angular/angular.js#12693] opened 2015-08-27 13:04 UTC
Hi,

I have an http interceptor that change all my requests URLs (adding a context root that depends on the environment).
I also use Angular Bootstrap, which put "manually" many templates in the $templateCache.
My interceptor is executed before the templateCache, therefore Bootstrap template cannot be found.

I think templateCache should take place before the interceptors, or at least it should be configurable.

Romain

**Comment by pkozlowski-opensource** [comment] 2015-08-27 13:25
Duplicate of https://github.com/angular/angular.js/issues/10257

**Closed by pkozlowski-opensource** 2015-08-27 13:25 UTC
