### ISSUE TITLE
ngModelOptions for date input using min attribute

### ISSUE THREAD

**Issue by LRFalk01** [angular/angular.js#11221] opened 2015-03-02 15:15 UTC
I am running into an issue, and I am not sure if it is expected behavior or not. I would expect the min attribute on a date input to adjust to UTC when ngModelOptions is set for that, but it is not doing it. Below of a Plunker that outlines what I am talking about.

http://embed.plnkr.co/IjCPztKVsbERDJaNO160/preview

**Comment by LRFalk01** [comment] 2015-03-03 18:29
I think this is probably an issue with the min and max validators not using the convertTimezoneToLocal function on value if timezone is set. (If the min and max attributes are supposed to adjust to the timezone in ngModelOptions.)

https://github.com/angular/angular.js/blob/ddc612056e4203eb7466f84e4fb0cce610eadb15/src/ng/directive/input.js#L1144

**Comment by Narretz** [comment] 2015-03-22 11:10
@shahata can you take a look at this? Thanks!

**Comment by shahata** [comment] 2015-03-23 10:18
Yeah, I'll take a look probably tomorrow

**Comment by SSARCandy** [comment] 2015-07-31 17:58
is it still an issue?
I try the demo code but can't find out where is wrong?

**Comment by LRFalk01** [comment] 2015-07-31 18:06
Top input is invalid because min attribute sees the date as before the acceptable min date. The min/max attributes are not respecting ngModelOptions' timezone setting.

**Comment by SSARCandy** [comment] 2015-07-31 18:13
I see.
I cannot find out wrong just because i'm at UTC +8
thanks !

**Comment by LRFalk01** [comment] 2015-07-31 18:17
Ohh. Yeah. I should have demo'd a max issue as well to cover both sides of UTC. Sorry.

**Comment by Narretz** [comment] 2017-11-23 17:29
Dupe of #16342

**Closed by Narretz** 2017-11-23 17:29 UTC
Labels: component: forms
