### ISSUE TITLE
No error provided when template doesn't load

### ISSUE THREAD

**Issue by BenMorganIO** [angular/angular.js#10661] opened 2015-01-07 02:34 UTC
I've been using AngularJS for the past few months and it feels like there's a lack in error reporting. I though I would stop by and help out, but I'm not much of a front end developer.

When using `$routeProvider` (or `ngRoute`), when I create a write, say:

```coffee
AuthModule.config [
  "$routeProvider"
  ($routeProvider) ->
    $routeProvider
    .when("/login",
      templateUrl: "login-template"
      controller: "LoginController"
    ).when("/password-recovery",
      templateUrl: "password-recovery-template"
      controller: "PasswordRecoveryController"
    ).otherwise(
      templateUrl: "signup-template"
      controller: "SignupController"
    )
]
```

And make _none_ of the templates, I do not receive any errors.  If I do _not_ make any of the controllers, I also do not receive any errors.

**Comment by BenMorganIO** [comment] 2015-01-07 02:35
Angular version: 1.2.28

**Comment by caitp** [comment] 2015-01-07 02:39
http://plnkr.co/edit/7IrKV94QDyla4uP0L9Bq?p=preview << error in master branch

http://plnkr.co/edit/7mWnACBpngbZPGI2LNhI?p=preview << also error in 1.2.28

**Comment by BenMorganIO** [comment] 2015-01-07 06:46
@caitp the silent failing has been creating a lot of issues for me, specifically with the templates. The controllers I haven't been worried about within my application.

I seem to have a bug in my app and the templates are not loading. I don't know why, but I'm thinking that if silent failing was removed, it would really help with the development. Perhaps a more experienced developer wouldn't be so bothered.

Also, it looks like when you forget to set up a controller such as the `SignupController`, this is what is raised:

```
Error: [ng:areq] Argument 'SignupController' is not a function, got undefined
http://errors.angularjs.org/1.3.9-build.3750+sha.1334b8c/ng/areq?p0=SignupController&p1=not%20aNaNunction%2C%20got%20undefined
```

It looks portion `not a function` was mangled into `not aNaNunction`. The log output or the online documentation don't seem to explicitly state that a `SignupController` does not exist. Is it possible to change the error text to:

```
Error: [ng:areq] 'SignupController' does not exist, please define one.
```

I think that would help developers a lot more.

Getting back to templates and silent failing, I understand that silent failing is for when you're planning to create a template, but what if you've already created one and you're scratching your head wondering why its not rendering? I think silent failing could be causing more pain than eloquentness.

**Comment by caitp** [comment] 2015-01-07 06:54
> Also, it looks like when you forget to set up a controller such as the SignupController, this is what is raised:

This is literally exactly what I told you. You don't get a silent fail here, you get a specific failure. You can debug this.

**Comment by BenMorganIO** [comment] 2015-01-07 06:56
Yes, you can, but what if the template doesn't load?

**Comment by caitp** [comment] 2015-01-07 07:01
> Yes, you can, but what if the template doesn't load?

Then you can look in your network console and see the 404 status code and say "oops, I guess I didn't create that template", you know?

**Comment by BenMorganIO** [comment] 2015-01-07 07:05
In my instance, I'm actually left with using script templates instead on page load instead of HTTP requests.

**Comment by caitp** [comment] 2015-01-07 07:09
then the templates are in the templateCache and the request doesn't fail, so what do you want? You've written your templates, they're just empty. Maybe add a "TODO: WRITE THIS MARKUP" in there? :)

**Comment by BenMorganIO** [comment] 2015-01-07 07:12
Actually, my templates are full of markup. I can see them in the DOM but they're not being displayed on the page. It just appears that they're not rendering.

**Comment by caitp** [comment] 2015-01-07 07:14
then I think you should post a reproduction because your bug report keeps changing from what you've described. http://plnkr.co or http://jsbin.com and we can take a look

**Comment by BenMorganIO** [comment] 2015-01-07 07:20
@caitp just figured out what my issue was :)

It appears that I had forgotten to add `ng-view` to the application. Are we able to get an error or a warning when there's no view to render a template?

**Comment by caitp** [comment] 2015-01-07 07:33
probably not, because it's ngView which decides it needs to render the template. $route has no idea about that. can't just track the number of ng-view directives in the DOM because we really have no idea when an element is added or removed

**Comment by pkozlowski-opensource** [comment] 2015-01-07 18:22
Yeh, I'm not sure how we should detect "lacking" ngView as in the current design this is this very directive that drives route changing...

@caitp do you see anything actionable here?

**Comment by caitp** [comment] 2015-01-07 18:32
Not personally

**Comment by pkozlowski-opensource** [comment] 2015-01-07 18:35
Yeh, me neither :-/ I can see how this could lead to a confusing situation but I don't think we can do anything about it with the current design...

Going to close this for the current router, maybe @btford wants to skim through this issue for his router rewrite.

**Closed by pkozlowski-opensource** 2015-01-07 18:35 UTC
Labels: component: ngRoute, needs: more info

**Comment by BenMorganIO** [comment] 2015-01-08 01:15
I would :heart: it if the new design can help.

Maybe a a development gem or a package that could watch for them independently?

**Comment by Narretz** [comment] 2015-01-08 09:53
Maybe it's also a feature for https://github.com/angular/angular-hint
