### ISSUE TITLE
Angular JS $location issue

### ISSUE THREAD

**Issue by bhagyashreethorat** [angular/angular.js#14595] opened 2016-05-12 08:36 UTC
Hi,
I want to report an issue. It might not be an issue but an unexpected behavior.
When I am inside any controller, and i say $location.path('xxx'). The sequence of statements below get executed. Should we explicitly return from there. Is it required?
Ideally I would think i am jumping to other controller file so the statements below should not get executed.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

I am using angular.min.js. Version details are as follows:
/*
 AngularJS v1.4.9
 (c) 2010-2015 Google, Inc. http://angularjs.org
 License: MIT
*/

I also tested on latest snapshot
/*
 AngularJS v1.5.6-build.4794+sha.f1f892d
 (c) 2010-2016 Google, Inc. http://angularjs.org
 License: MIT
*/

I would suggest on call of $location.path('xxx') the below statements should not get executed. An implicit return statement can be added.

**Comment by Narretz** [comment] 2016-05-12 11:35
What statements do you mean? I don't see anything.

**Comment by gkalpak** [comment] 2016-05-13 18:14
If I understand correctly you mean that given the following code:

```js
.controller('SomeController', function SomeController($location) {
  $location.path('...');
  // Do this
  // Do that
})
```

The lines below `$location.path(...)` should never execute. Ignoring the fact that we can't actually do that in JavaScript, it is not the intended behavior. `$location.path()` does not necessarily mean that the current controller or service will be detroyed. There are many usecases where this is indeed not the case.
If you want to exit the currently executing function, you should explicitly call `return`.

Closing, as this is working as expected.

**Closed by gkalpak** 2016-05-13 18:14 UTC
Labels: component: $location, needs: more info
