### ISSUE TITLE
linky filter fails on already present <a> tags

### ISSUE THREAD

**Issue by habovh** [angular/angular.js#13144] opened 2015-10-21 13:39 UTC
## Issue
Hi, I found an issue in the linky filter.

If the content on which the filter is applied already has a `<a>` tag, the output is not right.

It seems that the closing `"` of the original `<a>` tag's `href` attribute is ignored when linky tries to parse content for URLs, resulting in wrong URLs generated by the filter.

### Input
```
<a href="http://www.example.com/">example link</a>
```
> <a href="http://www.example.com/">example link</a>

### Expected output
```html
&lt;a href="<a href="http://www.example.com/">http://www.example.com/</a>"&gt;example link&lt;/a&gt;
```
> &lt;a href="<a href="http://www.example.com/">http://www.example.com/</a>"&gt;example link&lt;/a&gt;

### Actual output
```html
&lt;a href="<a href="http://www.example.com/&quot;&gt;example">http://www.example.com/"&gt;example</a> link&lt;/a&gt;
```
> &lt;a href="<a href="http://www.example.com/&quot;&gt;example">http://www.example.com/"&gt;example</a> link&lt;/a&gt;

**Comment by Narretz** [comment] 2015-10-27 17:14
The docs say that linky operates on text input, not on html input. So I'd say it works as expected. I don't know how much detecting HTML in the input would complicate the parsing. Maybe you could set up a PR for this?

**Comment by Narretz** [comment] 2015-10-27 17:16
This is a duplicate of https://github.com/angular/angular.js/issues/9586

**Closed by Narretz** 2015-10-27 17:16 UTC
Labels: component: misc core, severity: confusing

**Comment by habovh** [comment] 2015-10-27 17:41
Hi, I don't expect *linky* to detect HTML, but only for it to generate an `<a>` tag around the actual URL that is inside the originally inputted `href` attribute, hence the output would look like the expected output in OP.
