### ISSUE TITLE
 Uncaught ReferenceError: Node is not defined

### ISSUE THREAD

**Issue by mato75** [angular/angular.js#13442] opened 2015-12-03 15:08 UTC
angular.js:2789 Uncaught ReferenceError: Node is not defined

Updated from 1.4.7 to 1.4.8

**Comment by Narretz** [comment] 2015-12-03 16:13
Please provide more context information; stacktrace, minimal demo etc.

**Comment by mato75** [comment] 2015-12-03 16:16
This happens on specific d3 charts. Will try to create an example.

**Comment by jlmitch5** [comment] 2015-12-03 23:04
```
No coverage information was collected, exit without writing coverage information
/Users/jmitchell/tower_fork/node_modules/angular/angular.js:2789
var jqLiteContains = Node.prototype.contains || function(arg) {
                     ^

ReferenceError: Node is not defined
    at /Users/jmitchell/tower_fork/node_modules/angular/angular.js:2789:22
    at Object.<anonymous> (/Users/jmitchell/tower_fork/node_modules/angular/angular.js:29016:3)
```

It's happening after `require("angular/angular");` in the traceback

**Comment by Narretz** [comment] 2015-12-04 09:24
Ah, I see it's a change that has been made to jqlite which relies on Node. I'm not sure how that's fixable for server use of angular.

**Comment by Narretz** [comment] 2015-12-04 09:30
Actually, how exactly do you use Angular with require? In the browser or on the server?

**Comment by jlmitch5** [comment] 2015-12-07 14:24
@Narretz I inherited this flow, and I haven't dove too deep/know if its best practice, but we `require` angular when building the app for testing.

We take several client JS libraries through `require`, and then set up these to be found on `window`.

**Comment by neha-nsharma** [comment] 2015-12-09 22:52
I am getting the same exception with the mocha tests after upgrading to angular 1.4.8 

var jqLiteContains = Node.prototype.contains || function(arg) {
                     ^
ReferenceError: Node is not defined
    at .../angular/angular.js:2789:22

**Comment by Narretz** [comment] 2015-12-10 14:40
@gkalpak ping because you committed the change that causes this. Do you think this is something we should account for?

**Comment by gkalpak** [comment] 2015-12-10 15:53
Did I ? Let me take a closer look :)

**Comment by gkalpak** [comment] 2015-12-10 16:16
I don't think I was involved with 941c1c3, which introduced this, but I think it is worth solving anyway...
The fix sho be pretty simple too.

**Comment by Narretz** [comment] 2015-12-10 16:45
@gkalpak Ah, sorry. But thanks for fixing it ;)

**Comment by Narretz** [comment] 2015-12-16 09:23
@neha-nsharma: can you explain / show your setup? For example, Are you using a module loader or jsdom?

**Comment by neha-nsharma** [comment] 2015-12-16 16:59
I am using jsdom (0.11.1 version); I have the issue running my mocha tests. I was able to make it work by setting Node = window.Node; in the mocha config.


Thank you,
Neha

**Comment by Narretz** [comment] 2015-12-16 23:27
If you are using jsdom, it's your responsibility to provide the correct context. So I'd say this is not fixable in angular.

**Comment by gkalpak** [comment] 2015-12-17 15:41
@neha-nesharma, does it mean that changing `Node.prototype.contains` to `window.Node.prototype.contains` in Angular solves the issue ?
That might be a reasonable change.

**Comment by neha-nsharma** [comment] 2015-12-17 17:47
That is correct. This change will work.

Thank you

**Comment by petebacondarwin** [comment] 2016-01-04 21:25
@mgol is going to look into whether doing this comprehensively is feasible without too much work.

**Comment by simkessy** [comment] 2016-03-24 04:48
When I change to `window.Node.prototype.contains` I now get the error `Unable to get property 'prototype' of undefined or null reference`

I'm using IE8 and trying to get angular running there.

**Comment by petebacondarwin** [comment] 2016-03-24 09:51
@simkessy - Versions of Angular after 1.2 do not support IE8

**Comment by simkessy** [comment] 2016-03-24 14:02
@petebacondarwin - thanks for the response. I've begun reverting back to 1.2 (unfortunately)

**Comment by mato75** [comment] 2016-03-29 08:37
I am getting this issue in angular 1.5.3 version. 

How to fix this?

**Comment by gkalpak** [comment] 2016-03-29 09:13
@mato75, you need to make sure [`Node`][1] is available on the global context.

[1]: https://developer.mozilla.org/en-US/docs/Web/API/Node

**Comment by mato75** [comment] 2016-03-29 09:26
Ok, thank you, but why is not the fix included with new versions of Angular library?

**Comment by gkalpak** [comment] 2016-03-29 09:36
@mato75, this doesn't break any of the "officially" supported browsers (and so far there hasn't been any report of an issue that couldn't be solved on the developer's side).

But we are investigating if/how we can fix this and other similar issues, so it is easier for people running their code/tests in other environments (e.g. jsdom). This is not a high priority though, so don't expect a quick turnaround.

**Comment by petebacondarwin** [comment] 2016-03-29 15:02
@mato75 see https://github.com/angular/angular.js/issues/13442#issuecomment-165285474

**Comment by mgol** [comment] 2016-03-30 12:35
PR: #14345

**Closed** 2016-04-06 18:36 UTC
Labels: component: jqLite, type: bug

**Comment by mato75** [comment] 2016-07-19 07:57
@gkalpak changing Node.prototype to window.Node.prototype doesnt solve this issue.

**Comment by mgol** [comment] 2016-07-19 08:06
@mato75 If window.Node.prototype doesn't exist for you in Chrome then something must be really weird with your setup. We'd have to see a reproducible example, we can't do anything here if we don't see the code.

**Comment by mato75** [comment] 2016-07-19 09:11
Ah I see. It is a problem when using angularjs library in web worker.

**Comment by mgol** [comment] 2016-07-19 09:36
That explains the problem. Angular 1 is not supported in Web Workers. What are you trying to do with Angular there? Since Web Workers don't have access to the DOM, most of the Angular functionality (directives/components, events, data binding etc.) disappears.
