### ISSUE TITLE
ng-required not working on binding ng-model and ng-blur from directive

### ISSUE THREAD

**Issue by parthiban23** [angular/angular.js#16072] opened 2017-06-28 12:41 UTC
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

**Expected / new behavior:**

**Minimal reproduction of the problem with instructions:**

**Angular version:** 1.x.y

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by Narretz** [comment] 2017-06-28 13:55
I'm going to close this issue because we have no reproduction of the issue. Feel free to reopen this issue if you can provide a reproduction (ideally a runnable demo in a [Plunker](https://plnkr.co) or similar. You can use this [Plunker Template](http://plnkr.co/edit/tpl:yBpEi4)).

**Closed by Narretz** 2017-06-28 13:55 UTC
