### ISSUE TITLE
ng-messages: provide the input-element attributes to be used inside of the ng-message template

### ISSUE THREAD

**Issue by johannesjo** [angular/angular.js#10319] opened 2014-12-04 00:55 UTC
Would nice to be able to to something like this:
```html
<div ng-message="minlength">Your input should be at least {{attrs.minlength}} characters long</div>
```
Or even more sophisticated:
```html
<div ng-message="max"
        ng-if="attrs.type='date'">'The date provided should be no later than the {{attrs.max  |date}}</div>
```
If interested, I could try to provide a pull-request.

**Comment by Narretz** [comment] 2016-03-23 23:24
Dupe of https://github.com/angular/angular.js/issues/9849 (although there are currently not tangible plans for that)

**Closed by Narretz** 2016-03-23 23:24 UTC
Labels: component: forms, component: ngMessages, frequency: low, severity: inconvenient, type: feature
