### ISSUE TITLE
Font-family when bind value

### ISSUE THREAD

**Issue by tylerd92vn** [angular/angular.js#16259] opened 2017-10-06 04:35 UTC
**I'm submitting a ...**

- [ ] bug report

**Current behavior:**

After I bind value into HTML, the font-family I defined is cleared out, and the browser's font is used instead.

**Expected / new behavior:**

https://prnt.sc/gtvj8i
I defined `font-family:HelveticaNeue`, but after binding value, the `font-family` is rendered as Meiryo, which is no where in my code.

**Minimal reproduction of the problem with instructions:**

**AngularJS version:** 1.6.6

**Browser:** [all | Chrome 61.0.3163.100 (Official Build) (64-bit) | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by petebacondarwin** [comment] 2017-10-06 06:14
Can you include the code that contains the binding?

**Comment by Narretz** [comment] 2017-10-09 10:24
I'm going to close this issue because we have no reproduction of the issue. Feel free to ping us if you can provide a reproduction (ideally a runnable demo in a [Plunker](https://plnkr.co) or similar. You can use this [Plunker Template](http://plnkr.co/edit/tpl:yBpEi4)).

**Closed by Narretz** 2017-10-09 10:24 UTC
