### ISSUE TITLE
Angular-mock 1.6.2 $httpBackend injection error

### ISSUE THREAD

**Issue by fantarama** [angular/angular.js#15773] opened 2017-03-03 09:19 UTC
I've update to the new 1.6.2 version and all unit-test that inject $httpBackend mock service now fail with this exception:

```
TypeError: Cannot read property 'callbacks' of undefined
	at $jsonpCallbacksProvider.$get (../src/test/webapp/lib/angular.js:13103:36)
	at Object.invoke (../src/test/webapp/lib/angular.js:4862:19)
	at ../src/test/webapp/lib/angular.js:4656:37
	at getService (../src/test/webapp/lib/angular.js:4803:32)
	at injectionArgs (../src/test/webapp/lib/angular.js:4828:58)
	at Object.invoke (../src/test/webapp/lib/angular.js:4854:18)
	at $HttpBackendProvider.origProvider.$get (../src/test/webapp/lib/angular.js:4729:43)
	at Object.invoke (../src/test/webapp/lib/angular.js:4862:19)
	at ../src/test/webapp/lib/angular.js:4656:37
	at getService (../src/test/webapp/lib/angular.js:4803:32)
Error: Declaration Location
	at window.inject.angular.mock.inject (../src/test/webapp/lib/angular-mocks.js:3133:25)
	at Suite.<anonymous> (../src/test/webapp/app/checkout/checkoutOrderCtrlTest.js:12:16)
	at ../src/test/webapp/app/checkout/checkoutOrderCtrlTest.js:1:1
Chrome 56.0.2924 (Windows 7 0.0.0) checkoutOrder controller should redirect to ** FAILED
TypeError: Cannot read property 'callbacks' of undefined
	at $jsonpCallbacksProvider.$get (../src/test/webapp/lib/angular.js:13103:36)
	at Object.invoke (../src/test/webapp/lib/angular.js:4862:19)
	at ../src/test/webapp/lib/angular.js:4656:37
	at getService (../src/test/webapp/lib/angular.js:4803:32)
	at injectionArgs (../src/test/webapp/lib/angular.js:4828:58)
	at Object.invoke (../src/test/webapp/lib/angular.js:4854:18)
	at $HttpBackendProvider.origProvider.$get (../src/test/webapp/lib/angular.js:4729:43)
	at Object.invoke (../src/test/webapp/lib/angular.js:4862:19)
	at ../src/test/webapp/lib/angular.js:4656:37
	at getService (../src/test/webapp/lib/angular.js:4803:32)
Error: Declaration Location
	at window.inject.angular.mock.inject (../src/test/webapp/lib/angular-mocks.js:3133:25)
	at Suite.<anonymous> (../src/test/webapp/app/checkout/checkoutOrderCtrlTest.js:12:16)
	at ../src/test/webapp/app/checkout/checkoutOrderCtrlTest.js:1:1
Chrome 56.0.2924 (Windows 7 0.0.0): Executed 1 of 1 (1 FAILED) ERROR (0.379 secs / 0.031 secs)
03 03 2017 09:58:49.347:INFO [watcher]: Removed file "../src/test/webapp/app/checkout/checkoutOrderCtrlTest.js".
```
I've removed the $httpBackend injection (and commented related test lines code) and test pass.

By now I've rollback to angular-mock 1.6.1

**Comment by gkalpak** [comment] 2017-03-03 10:24
This is a duplicate of #15685 and has been fixed with #15686.
The fix will be included in the upcoming 1.6.3 release.

**Closed** 2017-03-03 11:43 UTC
