### ISSUE TITLE
ng-change, ng-blur or maybe ng-model fail after cancel scan creditcard

### ISSUE THREAD

**Issue by akirayjin** [angular/angular.js#11690] opened 2015-04-23 05:43 UTC
Happen only in iOS 8 and iPhone 6 using safari. When field has contain scan credit card and click in soft keyboard scan credit card. Then click cancel in top left of the screen. After canceling all directive components in ng (ng-change, ng-blur) has stop working.

**Comment by Narretz** [comment] 2015-04-23 08:28
1.) What do you mean by "scan credit card"? Is this a custom input element? Something built-in by iOs?

**Comment by akirayjin** [comment] 2015-04-23 08:37
It's function by iOS 8 in safari. By adding id="credit-card" or using class="credit-card" in input tag. When tap in input and keyboard is up, there a scan credit card in top of keyboard. More info: http://9to5mac.com/2014/06/05/safari-in-ios-8-uses-camera-to-scan-and-enter-credit-card-info/

**Comment by Narretz** [comment] 2015-04-23 10:11
Thanks. I'm not equipped to test this, unfortunately. It looks like Safari is messing with the events on the input, or maybe they are replacing the element. You could test this by adding event handlers for `input` to the input, and check if they still fire after the steps you described.

**Comment by rivan-n** [comment] 2015-05-20 09:45
ng-click is not fired as well sometimes after back from scan credit card view.

Have tried to bind click event using jQuery.click and it is working fine.

**Comment by Narretz** [comment] 2017-02-13 15:24
I'm going to close this issue because we have no reproduction of the issue (and also because it's quite old and hasn't been reported by anyone else). Feel free to reopen this issue if you can provide a reproduction (ideally a runnable demo in a [Plunker](https://plnkr.co) or similar. You can use this [Plunker Template](http://plnkr.co/edit/tpl:yBpEi4)).

**Closed by Narretz** 2017-02-13 15:24 UTC
Labels: browser: iOS, component: forms, needs: investigation
