### ISSUE TITLE
ng-options group by duplication (1.4.8)

### ISSUE THREAD

**Issue by m3fawner** [angular/angular.js#13550] opened 2015-12-15 17:52 UTC
```html
 <select ng-model="ctrl.model" ng-options="reason.description group by reason.type for reason in ctrl.possibleReasons"></select>
```
With a collection of:

```javascript
this.possibleReasons = [{ type : 1, description: 'Test1'}, { type: 2, description: 'Test2'}];
```

produces a dom element that has 4 opt-groups output instead of the expected two. This creates a duplication of the groups within the select element.

**Comment by gkalpak** [comment] 2015-12-15 18:43
Duplicate of #13487.

It has already been fixed in master. The fix will land with `v1.4.9` and `v1.5.0-rc.1`.

**Closed by gkalpak** 2015-12-15 18:43 UTC
