### ISSUE TITLE
ngClick with ngTouch prevent nested link on mobile

### ISSUE THREAD

**Issue by ipoly** [angular/angular.js#13668] opened 2016-01-04 11:02 UTC
With ngTouch module, If an element has ngClick directive, then its child link can't work.

Demo: http://embed.plnkr.co/pz7AEhTqFwBZVtmo3pJQ/

The links in the nav have parent \<li> with ngClick, and its click event be busted.
Use chrome simulator to reproduce this issue.

**Comment by Narretz** [comment] 2016-01-04 15:01
This is a duplicate of a lot of other issues. At this point, we advise you to not use ngTouch, but use hammer.js / fastclick,js instead

**Closed by Narretz** 2016-01-04 15:01 UTC

**Comment by ipoly** [comment] 2016-01-05 02:30
Ok, thanks.
