### ISSUE TITLE
ng-select does not consistently select when using keyboard

### ISSUE THREAD

**Issue by krotscheck** [angular/angular.js#13067] opened 2015-10-10 17:21 UTC
Bug observed in Google Chrome 45.0.2454.101. Bug NOT observed in Firefox 41.

JSFiddle using Angular 1.4.7 available here: https://jsfiddle.net/oeo9h2vh/5/

In the case where a select box is populated with multiple items with the same first letter, attempting to select the _second_ item, by typing the first letter via the keyboard, does not update the ID. After selecting the third, the selection updates as expected.

Basic steps: 
* Tab into a select box with N>2 items with the same first letter (using 's' as an example).
* Hit 's' to select the first. ng-model is updated.
* Hit 's' to select the second. ng-model is NOT updated.
* Hit 's' to select the third. ng-model is updated.
* All subsequent updates function as expected.

**Comment by Narretz** [comment] 2015-10-12 08:21
It looks like this is a dupe of https://github.com/angular/angular.js/issues/9134

**Closed by Narretz** 2015-10-12 08:21 UTC
