### ISSUE TITLE
Suggestion: default values for directive scope bindings

### ISSUE THREAD

**Issue by Earl-Brown** [angular/angular.js#13562] opened 2015-12-17 00:22 UTC
I have found myself writing code in the link function to double-check values on my scope properties, to ensure a valid default value.

I think it would be nice to be able to specify a default value when specifying the property. I was thinking something like "=enabled|true", but that wouldn't allow for functions or more complex options.  

I've reviewed all of the current issues, and haven't seen a suggestion like this; and I haven't seen anything in the docs to indicate something like this is possible.

So, I'm submitting the idea to the community.  

I'm looking forward to hearing what everybody has to say - I expect I'll learn a bit more about Angular from it!

**Comment by Narretz** [comment] 2016-01-21 20:14
Dupe of https://github.com/angular/angular.js/issues/9278

**Closed by Narretz** 2016-01-21 20:14 UTC
Labels: component: $compile, frequency: moderate, severity: inconvenient, type: feature
