### ISSUE TITLE
injecting $location rewrites and breaks anchor links

### ISSUE THREAD

**Issue by skivvies** [angular/angular.js#4608] opened 2013-10-23 17:49 UTC
Simply injecting $location anywhere in your app breaks anchor links (which up till now have been working for [20 years](http://www.w3.org/MarkUp/draft-ietf-iiir-html-01.txt)!). Here is example code demonstrating the issue: https://gist.github.com/skivvies/7125406

Here is a rawgithub link so you can actually run this code: https://rawgithub.com/skivvies/7125406/raw/b42a135b7a40db7dc00a7726fa8efd080e14b7b7/index.html

Please keep an eye on the browser's address bar when you click "link to anchor". Compare this to almost the exact same code, with the only difference being that $location is not injected: https://gist.github.com/skivvies/7125477

Again, here is a rawgithub link to this version so you can run it: https://rawgithub.com/skivvies/7125477/raw/1b4a4d2692616c42b92b813b4c7d1e26ffe38c9b/index.html

Reproduction steps:
1. Open a new browser window directly to an anchor on a page with an Angular app that injects $location, e.g. https://rawgithub.com/skivvies/7125406/raw/b42a135b7a40db7dc00a7726fa8efd080e14b7b7/index.html#anchor
2. Angular hijacks the url's hash and rewrites it to add a leading slash, e.g. https://rawgithub.com/skivvies/7125406/raw/b42a135b7a40db7dc00a7726fa8efd080e14b7b7/index.html#/anchor
3. The browser does not scroll the page down to the linked-to anchor
4. Clicking any links on the page to the anchor (e.g. the "link to anchor" link in the example code) also fails to scroll the page to the anchor

(I hit this because I'm using angular-bootstrap's [dropdown toggle directive](http://angular-ui.github.io/bootstrap/#/dropdownToggle) which injects $location, I don't ever actually inject it into my app, but simply depending on angular-bootstrap is enough to break my anchor links. Thanks to [this post](http://stackoverflow.com/questions/18379715/disable-angularjs-routing-routeprovider-already-gone) for tipping me off. /cc @pkozlowski-opensource)

http://www.benlesh.com/2013/02/angular-js-scrolling-to-element-by-id.html looked like a promising workaround but ultimately didn't work. **Update:** See comments below.

**Comment by jainarpit014** [comment] 2015-01-03 19:57
set target="_self" in every anchor tag.This workaround is working fine for me.

**Comment by jeromebrule** [comment] 2015-01-21 15:20
set target="_self" fix my problem. thx :)

**Comment by wobine** [comment] 2015-01-22 16:48
setting target="_self" only fixes the problem internally to the site itself. If you want to link from outside to an anchor link, there is still that horrible slash (angular's hijacking) sitting right inside your hyperlink. Its terrible!

**Comment by wobine** [comment] 2015-01-22 17:00
I'm using version 1.3.9 and it doesn't work yet. Why are folks saying it was fixed in 1.2??

**Comment by Rutix** [comment] 2015-01-22 17:31
@wobine We didn't say it was fixed in 1.2 . There has been a fix and it will probably be merged into 1.2.x but that hasn't happened yet.

**Comment by Rutix** [comment] 2015-01-22 17:31
@wobine We didn't say it was fixed in 1.2 . It has been fixed and it will probably be merged into 1.2.x but that hasn't happened yet.

**Comment by iobaixas** [comment] 2015-06-11 14:53
I managed to get anchors working correctly using the following setup (it only considers id anchors and probably messes up angular routing for more complex use cases)

```js
module.config([ '$anchorScrollProvider', function($anchorScrollProvider) {
	$anchorScrollProvider.disableAutoScrolling();
}])
.run(['$rootScope', '$location', function($rootscope, $location) {
	// mimic the anchor behaviour, avoid using the $anchorScroll service
	$rootscope.$on('$locationChangeSuccess', function() {
		var element = $('#' + $location.url().replace('/', ''));
		if(element.length > 0) element[0].scrollIntoView();
	});
}]);
```

**Comment by manutalcual** [comment] 2015-06-12 07:58
Hi,

I've found a solution to this nightmare, but I'm new to AngularJS and don't know if it is a correct solution.
I've enabled html5mode like this:

```javascript
saApp.config (function($locationProvider) {
    $locationProvider.html5Mode({
	enabled : true,
	requireBase: false,
	rewriteLinks : false
    });
});
```

Now all links work as expected and there are no errors on js.

**Comment by lydiastepanek** [comment] 2015-08-10 22:46
I got around this by using a ng-click event with a window.open(url) command:

<a class="viewLink" ng-href="" ng-click="linkViewed()">

$scope.mediaViewed = function linkViewed() {
  window.open($scope.link)
}

**Comment by cwi-ezoutas** [comment] 2015-10-20 06:59
I can confirm that manutalcual answer works as expected with AngularJS v1.3.13.

The only problem is that when I directly load e.g. http://site.com/#test and I click again on #test the final URL is http://site.com/#test#test.

**Comment by brunoamancio** [comment] 2015-10-26 23:10
@manutalcual, your solution solved it.

**Comment by cesardariogarcia** [comment] 2016-03-28 22:45
#14315

**Comment by cesardariogarcia** [comment] 2016-03-28 22:47
#14315

**Comment by cesardariogarcia** [comment] 2016-03-28 22:48
#14315

**Comment by VincentLoy** [comment] 2016-11-02 15:21
This is my workaround:
Stop event propagation directive with high priority
```javascript
var app = angular.module('my.module', []);

app.directive('externalAnchorLink', [function () {
    return {
        restrict: 'A',
        priority: 0,
        link: function (scope, el) {
            /*jslint unparam: true*/
            el.on('click', function (event) {
                event.stopPropagation();
            });
        }
    };
}]);
```

Then in HTML

```html
<a href="/test/example/#my-anchor" external-anchor-link>link text</a>
```

**Comment by gkalpak** [comment] 2016-11-03 09:45
Regarding the original problem (`$location` affecting the default behavior of anchor links):

Indeed Angular uses `#` (potentially with a hash-prefix after `#`) to identify a "client-side" route (in non-HTML5 mode). It is `$location`'s job to interact with hash part of the URL. So, since it is not possible to distinguish a `#some-client-side-route-path` for `#i-want-to-scroll-to-an-element`, it has to always assume it is a client-side route path.

There are several solutions available (most of them discussed above) - especially if you don't use `$location`/client-side routing in your app (but might have dependencies that instantiate it):

1. Use an empty path and a client-side route hash: `href="##i-want-to-scroll-to-an-element"`.
2. Configure `$locationProvider` to [use HTML5 mode][1]
3. [Change the hash-prefix][2] (which is empty by default), so that `#foo` is not recognized as a client-side route path. E.g. with `$locationProvider.hashPrefix('!')`, a client-side route needs to start with `#!` (e.g. `#!foo`). Thus `#foo` is not recognized as a path and the normal browser behavior applies.

**Note:** Starting with v1.6 the default hash-prefix will be `!`, so OP's usecase will work out-of-the-box (without the need to manually call `$locationProvider.hashPrefix('!')`). In older versions, you need to configure it yourself.

--
I understand there may be several roblems discussed in this issue, but this does not help with assessing, investigating and hopefully fixing them, so (since the original problem falls under the _fixed_/_works as expected_ category), I am going to close this issue. If you are still running into different problems (that are not already reported), please open separate issues.

[1]: https://docs.angularjs.org/api/ng/provider/$locationProvider#html5Mode
[2]: https://docs.angularjs.org/api/ng/provider/$locationProvider#hashPrefix

**Closed by gkalpak** 2016-11-03 09:45 UTC
Labels: component: $location, frequency: moderate, Lots of comments, severity: broken expected use, type: bug
