### ISSUE TITLE
Tabs demo from Angular material website doesn't work with ngAnimate 1.4.2

### ISSUE THREAD

**Issue by Bebop182** [angular/angular.js#12348] opened 2015-07-14 22:18 UTC
The Tabs Demos displayed on https://material.angularjs.org/latest/#/demo/material.components.tabs are made using v1.3.15 of all angular package. Using 1.4.2 will introduce strange animation during tab switch. The tab content height will transition to 0 during tab-switching and then take back its expected height.

This is the original codepen exemple, but with dependencies upgraded to 1.4.2:
http://codepen.io/anon/pen/waXmMO

**Comment by Narretz** [comment] 2015-07-15 08:51
hm, still happens with latest snapshot.

/cc @matsko @ThomasBurleson

**Comment by ThomasBurleson** [comment] 2015-07-16 20:31
This appears to be fixed with latest changes in master: https://github.com/angular/material/commit/cc8130cf377e5a353e967d2bacc5bd56d3aef975

**Comment by Bebop182** [comment] 2015-07-17 18:42
Do you happen to know what was the cause of this bug?

**Comment by ThomasBurleson** [comment] 2015-07-17 20:47
Still broken (with lastest master Angular Material and Angular 1.4.3:

* Open http://localhost:8080/#/demo/material.components.tabs
* Then navigate to Dialogs (clicking on the Dialog demos in SideNav) http://localhost:8080/#/demo/material.components.dialog

![screen shot 2015-07-17 at 3 45 09 pm](https://cloud.githubusercontent.com/assets/210413/8756862/09eb845a-2c9b-11e5-8b03-6b2cd9fb0bb8.png)

**Comment by ThomasBurleson** [comment] 2015-07-18 05:30
This SHA https://github.com/angular/material/commit/31bb1210a6fbb08dafc015a00db4105d7bb60980 appears to resolve this issue. This is a workaround, I believe, to perhaps a subtle issue with ngAnimation.

ngAnimate appears to be transitioning/animating elements regardless of scope.$destroy(). Have not confirmed more yet. Ask @robertmesserle for more details.

**Comment by matsko** [comment] 2015-08-25 18:05
@Bebop182 @ThomasBurleson is this issue still relevant? I tried testing against the original but it looks like it works just fine.

**Comment by Bebop182** [comment] 2015-08-28 23:46
Nope, just tested the whole thing, the issue was solved on both side. Tab animation is now properly working with:
- Angular-Material 0.10.0 and Angular.js 1.4.4.
- Angular-Material 0.10.1 and Angular.js 1.4.2.

**Closed** 2015-08-28 23:47 UTC
Labels: component: ngAnimate, hotlist: material, type: bug

**Comment by matsko** [comment] 2015-08-28 23:59
P.S. 1.4.5 is out: https://code.angularjs.org/1.4.5/

**Comment by matsko** [comment] 2015-08-28 23:59
Use that one instead since it fixes the issues with requestAnimationFrame.
