### ISSUE TITLE
$filter("currency") with negative is giving "-" sign instead of "()" parenthesis in Angular 1.5

### ISSUE THREAD

**Issue by aarongan** [angular/angular.js#14163] opened 2016-03-02 19:10 UTC
hi, 

I am facing the changes $filter("curency") with negative value which is returning "-" prefix instead of "()" parenthesis. 
It this a bug or is a fix from previous version seems 1.3 is showing "-" as well. 

thanks,
Aaron

**Comment by Narretz** [comment] 2016-03-03 11:11
Duplicate of https://github.com/angular/angular.js/issues/12870 Specifically look at https://github.com/angular/angular.js/issues/12870#issuecomment-180785981 for ways of dealing with this,

**Closed by Narretz** 2016-03-03 11:11 UTC

**Comment by aarongan** [comment] 2016-03-03 14:25
Thanks, but there is bug if $filter('currency') is returning negative-sign , it is not supported in ngModel.$setViewValue function. 

ngModel.$setViewValue("-$50") results below
=> ngModel.$viewValue = ""
=> ngModel.$modelValue = ""

But it works when using parenthesis "()" instead of negative-sign "-".
