### ISSUE TITLE
Bug in checkbox

### ISSUE THREAD

**Issue by gaoyuan121** [angular/angular.js#10662] opened 2015-01-07 02:49 UTC
I use checkbox like this:
```
[label][input type="checkbox" ng-checked="go" ng-true-value="true" ng-false-value="false" ng-model="go"][/input]Send out email notification[/label]
```

the default value of parameter "go" is "true", when I un-checked the checkbox,the value of go is still "true" when I use console.log(go) to trace it. And when I check and then un-check it angain, its value changed.

**Comment by caitp** [comment] 2015-01-07 02:51
Hey, thanks for the bug report =) could you please post a minimal reproduction of your issue to http://plnkr.co or http://jsbin.com? thanks~

**Comment by gaoyuan121** [comment] 2015-01-07 03:00
Hi @caitp , here I create an example for that
http://plnkr.co/edit/sXFd6hZ8bXRLN1SG3217

**Comment by LeonardoBraga** [comment] 2015-01-07 03:05
Initialize `go` correctly and it will work: http://plnkr.co/edit/49at2ol4W4la4LVrRqcT?p=preview

**Comment by LeonardoBraga** [comment] 2015-01-07 03:11
... and you can also remove the `ng-false-value` and `ng-true-value` in this case, since they're `false` and `true`, respectively, by default. I hope it helps!

**Comment by gaoyuan121** [comment] 2015-01-07 03:13
@LeonardoBraga Got it. So its value should be boolean, not string. Hope it would be more convenient because all of my data are get as string.
My problem is solved. Thanks.

**Comment by caitp** [comment] 2015-01-07 03:13
he wants the `true` and `false` to be string values --- ng-true-value and ng-false-value need to be initialized with constant values. If they are wrapped in quotes like `ng-true-value="'true'"` it works just fine

**Comment by caitp** [comment] 2015-01-07 03:15
http://plnkr.co/edit/sXFd6hZ8bXRLN1SG3217?p=preview like this

**Comment by LeonardoBraga** [comment] 2015-01-07 03:20
Sure thing, @caitp. He didn't mention the values had to be strings in the beginning, this is why I considered it being the wrong usage, and suggested using `true` instead of `'true'` and removing ngFalseValue and ngTrueValue directives, which also made the code simpler.

**Comment by gaoyuan121** [comment] 2015-01-07 03:21
@caitp Do you mean initialize it like this? But it didn't run properly.
http://plnkr.co/edit/sXFd6hZ8bXRLN1SG3217?p=preview

1. [input ng-model="go" type="checkbox" 
    ng-true-value="'true'" ng-false-value="'false'" 
    ng-checked="go">!</p>

 2.  $scope.go = 'true';

**Comment by gaoyuan121** [comment] 2015-01-07 03:29
@LeonardoBraga Yes, I must use Boolean(go) to convert it to boolean formats. Well, it works fine for me now. Great thanks for your kind help.

**Comment by caitp** [comment] 2015-01-07 03:37
@gaoyuan121 hmmm, you're right. That's weird. lets keep this open so that we can fix that bug.

**Comment by LeonardoBraga** [comment] 2015-01-07 03:58
@gaoyuan121 The glitch with string values is being caused because the input has both `ng-model` and `ng-checked` in it. Remove `ng-checked` and it will work with the strings as well.

**Comment by caitp** [comment] 2015-01-07 04:05
when on earth did we add that? but yeah I don't think that's an excuse --- we probably shouldn't allow `ngChecked` to operate if it's used on its own input, to prevent weirdness

**Comment by LeonardoBraga** [comment] 2015-01-07 04:09
@caitp I can provide a PR for that, if you think it's appropriate.

**Comment by caitp** [comment] 2015-01-07 04:11
no let me do it i haven't solved any problems in this repo for at least a month now =) nah i'm kidding, go for it

**Comment by LeonardoBraga** [comment] 2015-01-07 04:15
@caitp lol :-)

**Comment by gaoyuan121** [comment] 2015-01-07 05:08
@LeonardoBraga Sounds good:)

**Comment by petebacondarwin** [comment] 2015-01-08 12:02
I don't understand why we need this fix. What is the need for using `ngModel` and `ngChecked` on the same element. They are for different purposes. If you remove the `ngChecked` everything works fine.

http://plnkr.co/edit/PU8QKeMgITqUbDAm9XlK?p=preview

**Comment by petebacondarwin** [comment] 2015-01-08 12:03
@caitp  and @gaoyuan121 - can you provide the real world use case ?

**Comment by Narretz** [comment] 2015-01-21 10:12
It actually doesn't make sense to use ng-checked and ng-model together. I'd be fine with reverting this and updating the docs for ng-checked instead.

**Comment by petebacondarwin** [comment] 2015-01-21 13:58
@caitp - can you give a view on reverting this?

**Comment by caitp** [comment] 2015-01-21 16:57
I'm anti-reverting, but I'm pro-shrinking if you can find a way to express it in fewer characters.

The API should not be surprising people

**Comment by lgalfaso** [comment] 2015-03-11 16:31
With #10664 landed, it should be safe to close this. If anybody wants to talk about the interactions of ng-model and ng-checked, then please open another issue just for this

**Closed by lgalfaso** 2015-03-11 16:31 UTC
Labels: component: forms, needs: more info
