### ISSUE TITLE
ngResource   Array with Array

### ISSUE THREAD

**Issue by luanxuechao** [angular/angular.js#16165] opened 2017-08-11 03:58 UTC
我的数据类型是[[{}]] 但是 通过ngResource 的转变之后变成了[{{}}] 第二层变成了map ,我在源码看到了
![tim 20170811115611](https://user-images.githubusercontent.com/13465762/29200953-4f9956d6-7e8c-11e7-8cde-ebab6e032300.png)
![tim 20170811115637](https://user-images.githubusercontent.com/13465762/29200954-4f9a9834-7e8c-11e7-83a2-f8b820a116da.png)
为什么要这样做啊？ 有人遇到吗

**Comment by frederikprijck** [comment] 2017-08-11 06:14
Hi @luanxuechao ,

Sadly I'm not familiar with Chinese (I did translate it, but not sure if I totally get it). Could you please rephrase it in English and provide a reproduction sample so someone can take a look at it?

Please try to create issues in English next time, makes it easier for us to understand it! ❤️

**Comment by luanxuechao** [comment] 2017-08-11 08:00
@frederikprijck  Sorry  and thank you for your answer,I have a problem about ngResource ,when my httpResponse structure is [ [ {},{}] ], after $q   service  resolve(response), httpResponse  structure  is changed,
it is [ {{} ,{}} ],I find source code, the picture show you ,the structure changed. how can I solve it .

**Comment by frederikprijck** [comment] 2017-08-11 12:11
I'm not sure I understand what you're talking about. Maybe others can help you, but other than that I think it will be beneficial if you'd create a reproduction of the problem.

**Comment by gkalpak** [comment] 2017-08-11 12:50
As @frederikprijck said, there is not enouhg info to understand the problem you are facing. Please share a minimal reproduction.

That said, this sounds more like a general support question (than a bug in AngularJS). If that is the case, it is recommended to use one of the [appropriate support channels][1].
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by Narretz** [comment] 2017-08-17 09:42
I'm going to close this issue because we haven't got any feedback. Feel free to reopen this issue if you can provide new feedback.

**Closed by Narretz** 2017-08-17 09:42 UTC
Labels: component: ngResource, needs: more info
