### ISSUE TITLE
select element doesn't select the correct value. 1.3.8

### ISSUE THREAD

**Issue by lebster** [angular/angular.js#10693] opened 2015-01-08 22:53 UTC
In 1.3.8 it selects the wrong value after the list is loaded.

http://plnkr.co/edit/boi3q34i9Nr8vVO6msHO?p=preview

**Comment by Narretz** [comment] 2015-01-08 22:58
Hi, this is a duplicate of a few other issues and we are currently working on a fix.

**Closed by Narretz** 2015-01-08 22:58 UTC
