### ISSUE TITLE
ng-transclude should not create new sibling scope.

### ISSUE THREAD

**Issue by mbykovskyy** [angular/angular.js#5489] opened 2013-12-20 00:41 UTC
This is more of a change request and I would like to see what other people think.

In my humble opinion ng-transclude should not create it's own scope or at least have a way to prevent it from doing so. The reason behind this is that a directive which requests transclusion already has means to specify whether or not it wants to have a scope or an isolated scope or no scope at all. It uses ng-transclude directive to mark where it wants to insert the content. When ng-transclude creates it's own sibling scope it kind of breaks the expectations of the directive which defines what kind of scope it wants and there comes the manifestation of the popular 'value' vs 'object.value' confusion.

Here's an example of where new scope doesn't make sense in my opinion:
```
ui.directive('box', function() {
	return {
		restrict: 'E',
		transclude: true,
		template: '<div ng-transclude/>',
		replace: true,
		scope: {}
	};
});
```
All this directive wants is replace the `<box>content</box>` with a `<div>content</div>` and the content to have the isolated scope.

Creating nested structure of directives like this leads to a scope tree pollution. Here's a plunker example (http://plnkr.co/edit/DwukVGGprFFjQuVY8yTz) of three nested directives which create a scope tree structure like this:
```
< Scope (002) : ng-app
	< Scope (003) : ng-controller
		< Scope (004) : box
		< Scope (005) : ng-transclude
			< Scope (006) : box
			< Scope (007) : ng-transclude
				< Scope (008) : box
				< Scope (009) : ng-transclude
```
This behaviour doesn't seem to add any value to its purpose but creates a lot of confusion among beginners.

At the moment I use the following workaround which achieves exactly what the previous example does:
```
ui.directive('box', function() {
	return {
		restrict: 'E',
		transclude: true,
		template: '<div/>',
		replace: true,
		scope: {},
		link: function(scope, element, attrs, transclude) {
			transclude(scope.$parent, function(content) {
				element.append(content);
			});
		}
	};
});
```
Here's a plunker example (http://plnkr.co/edit/46v6IBLkhS71L1WbUDFl) which illustrates this concept. It leaves the scope tree nice and tidy:
```
< Scope (002) : ng-app
	< Scope (003) : ng-controller
		< Scope (004) : box
		< Scope (005) : box
		< Scope (006) : box
```
And the 2-way binding works the way many expect when they bind 'value' rather than 'object.value'. (I believe that the fact that passing just 'value' works in some cases but not the other and blaming the nature of prototypal inheritance in javascript is not a good excuse. The fact that many people find this behaviour unexpected indicates that there's an architectural flaw.)

I would love to hear what other people think and use cases where they think that creating a new sibling scope for ng-transclude makes sense.

**Comment by Opiskull** [comment] 2015-01-21 08:43
+1

**Comment by arturgspb** [comment] 2015-01-21 21:16
+1

**Comment by sergiofilhowz** [comment] 2015-02-04 19:56
+1

**Comment by sgarbesi** [comment] 2015-02-08 10:50
+1

**Comment by amitgupta1202** [comment] 2015-02-17 17:11
+1 seems transcluded directive creates scope even when asked not to do so. example http://plnkr.co/edit/Wn81IBkE87vtigXvjmIa?p=preview

**Comment by ljwagerfield** [comment] 2015-02-17 20:59
+1

**Comment by valorbreak** [comment] 2015-03-13 21:25
+1

**Comment by c0ntinuum** [comment] 2015-03-17 07:27
+1

**Comment by balmychan** [comment] 2015-03-18 09:51
+1

**Comment by Polooo2** [comment] 2015-05-05 09:07
+1

**Comment by princejwesley** [comment] 2015-05-09 07:30
+1

**Comment by nadar** [comment] 2015-05-18 08:01
+1

**Comment by KasraKhosravi** [comment] 2015-06-03 05:46
+1

**Comment by nikkwong** [comment] 2015-06-07 09:19
+1—are there any valid workarounds for this?

**Comment by SanderElias** [comment] 2015-06-12 05:18
@nikkwong, there are a couple workarounds posted in this thread. I know I did put link in a plunk that showed a workaround.

**Comment by petebacondarwin** [comment] 2015-09-08 14:03
OK, so even if this arrives it will not be until 1.5.x

But before that I have a concern. The primary reason for creating a new scope (call it a sibling of the isolate scope, or more accurately a child of the original scope from where the transcluded content comes) is to prevent memory leaks.  Compare this plunker:
http://plnkr.co/edit/3NVxdYGy1AFDvD0M2BYI?p=preview
and a version that reuses the scope from where the original transclusion comes:
http://plnkr.co/edit/MXFz2awcqwQQ7R882Xwz?p=preview

In the second version, as you toggle the transcluded content on and off the number of watchers keeps going up - a memory leak.

**Comment by troch** [comment] 2015-09-08 14:31
@petebacondarwin it should definitely be a new scope so it can be destroyed with its watchers. I think most of the grief about transclusion is because ng-transclude would create a sibling scope of the containing scope, making it not possible to access its variables through prototypal inheritence. Or am I wrong?

**Comment by amitgupta1202** [comment] 2015-09-08 15:32
We reailzed that the issue is the way angular 2 way binding works, definietly ng-transclude creates a child scope, but there will be numerious occasions where you will find your self in same situation, for example ng-repeat creates child scope. After looking at the angular code, we realized that issue with 2 way binding issue doesnt work property with the object attribute, but works fine with objects itself

Problem : http://plnkr.co/edit/Wn81IBkE87vtigXvjmIa?p=preview

Solution: http://plnkr.co/edit/KShClgQVwIjscXPzVRwR?p=preview

Its not perfect but knowing this solved lot of our issues, never do two way binding on an attribute

Note that this solution is already suggested by mbykovskyy, when he raised issue, I am just giving an example as it took me a while to figure it out.

**Comment by SanderElias** [comment] 2015-09-08 15:38
@petebacondarwin It will only be an temporary leak, until the holding scope will get destroyed. Here is (a plunk)[http://plnkr.co/edit/Q587WQnX0u0u7JjhtCxa?p=preview] that shows that if you switch out the transclude-holding-scope, everything will gets released just fine.
Still it's a point that needs attention. Perhaps a large Waring in the docs about this possible leak might be enough to fix it?

**Comment by petebacondarwin** [comment] 2015-09-08 16:44
Well any JS leak is only temporary until you refresh the browser ;-)

**Comment by frfancha** [comment] 2015-09-08 18:21
@SanderElias Users of our Angular application are busy from begin to end of the day.
We already see that the memory usage is increasing during the day and we must be very careful in what we put on the page, introducing more possible leaks is risky.

**Comment by petebacondarwin** [comment] 2015-09-09 11:24
@troch - transclusion actually creates a childscope of the scope where the transcluded content is originally found. This was broken a few versions back (definitely in 1.2) where instead it just created a child of the parent of the current directives scope. This meant that deeply nested transclusions actually got the wrong transclusion scope.

**Comment by lgalfaso** [comment] 2015-09-10 14:51
I have to agree with @petebacondarwin, and even when the current behavior is not 100% intuitive, then the current behavior works best to prevent any leak. I am inclined to close this issue as Wont Fix

**Closed** 2015-09-10 22:07 UTC
Labels: component: $compile, frequency: high, Lots of comments, type: bug

**Comment by mbykovskyy** [comment] 2016-02-17 22:18
Good thing I switched to Ember years ago. :)
