### ISSUE TITLE
SCRIPT7002: XMLHttpRequest: Network Error 0x2ef3, Could not complete the operation due to error 00002ef3

### ISSUE THREAD

**Issue by vinothbabu** [angular/angular.js#15432] opened 2016-11-24 11:49 UTC
We are getting the below error, while using `angular 1.2.X` 
`
SCRIPT7002: XMLHttpRequest: Network Error 0x2ef3, Could not complete the operation due to error 00002ef3`

Error details: 

- Post request calls are getting aborted by the browser randomly throws the above said error in browser's console. 
- It happens only in IE 9-11 browser intermittently. 

![v1 2 32](https://cloud.githubusercontent.com/assets/1165332/20597134/11e70fe0-b268-11e6-9148-05b904343ed8.png)
![v1 2 32_1](https://cloud.githubusercontent.com/assets/1165332/20597135/11ff3516-b268-11e6-98ce-29fb6d4dabc2.png)

We have been investigating this issue for a long time, we could not arrive at a conclusion to close this item. Any help would be appreciated.

**Comment by gkalpak** [comment] 2016-11-24 14:01
This error is very generic and we cannot identify the cause. There seem to be several possible reasons (e.g. see [here][1], [here][2], [here][3]), ranging from incorrect server configuration to bad mime-types, but we can't investigate further without more info. In any case, there is no indication that this is Angular-related.

Closing since this is not actionable in its current state.

[1]: http://stackoverflow.com/questions/14527387/script7002-xmlhttprequest-network-error-0x2ef3-could-not-complete-the-operati
[2]: http://stackoverflow.com/questions/23145688/ie10-11-ajax-xhr-error-script7002-xmlhttprequest-network-error-0x2ef3
[3]: https://connect.microsoft.com/IE/feedback/details/817359/xmlhttprequest-issue

**Closed by gkalpak** 2016-11-24 14:01 UTC
