### ISSUE TITLE
Origin not being added to request headers in some circumstances

### ISSUE THREAD

**Issue by techjanitor** [angular/angular.js#12255] opened 2015-07-01 18:35 UTC
Sometimes when I load my website angular will fail to add an origin to the request header. This causes a failure in xmlhttprequest because the backend server is expecting a particular address for allow-origin. If it gets null, the server won't add the header. That seems reasonable for CORS?

Anyway I can't directly reproduce it, it just happens randomly in Chrome. Closing the tab and reloading my website fixes the error. It seems like some weird caching thing, but all my pages are set to no-cache. No idea how to handle this, because allow-origin would never work in this situation unless I'm just essentially echoing the request host.  

CORS error:
![Imgur](http://i.imgur.com/av8EmPa.png)

request header from angular:
![Imgur](http://i.imgur.com/FVwMl9F.png)

This is with Angular 1.4.1

**Comment by pkozlowski-opensource** [comment] 2015-07-01 19:14
@techjanitor what is the HTTP verb we are talking about here? OPTIONS or sth else? Could you provide more details? I'm asking since it is not AngularJS that adds this header but rather a browser, so IMO something else is going on here.

**Comment by techjanitor** [comment] 2015-07-01 19:26
Sorry, it's on GET. Only happens when I initially load the page, sometimes. 

The app executes correctly, all the routes are there etc. It just fails to add an origin in the request header. 

This happens on ALL routes and controllers, even if I load another page that calls a $resource method.

It persists if I clear the cache in dev mode and reload the page. It only is resolved if I close the tab and reload the page in Chrome. Very strange.

I haven't seen it happen on OPTIONS or POST. 

Some more details:
The app itself is using ngResource, and is packaged with angular 1.4.1 with browserify.

**Comment by techjanitor** [comment] 2015-07-17 19:05
Might it have something to do with the new javascript bytecode caching feature in Chrome 42?

http://blog.chromium.org/2015/03/new-javascript-techniques-for-rapid.html

**Comment by Narretz** [comment] 2015-09-19 10:57
@techjanitor  Did you ever find a solution for this? It does look like a browser issue and I am inclined to close this issue because of this.

**Comment by techjanitor** [comment] 2015-09-19 17:54
You're inclined to close the issue because angular, which runs in browsers, is potentially having a strange interaction with a feature in the most used browser in the world. Ok.

**Comment by pkozlowski-opensource** [comment] 2015-09-19 18:10
@techjanitor it is more like:
* we don't have reproduce scenario
* it is not AngularJS that sends CORS pre-flight headers but a browser

If you really want to see it fixed, please help us to narrow if down. You are the only one reporting this, we can't reproduce so you are in the best position to help here.

We want to do "the right thing here" but we lack the context that you've got.

**Closed** 2015-09-19 18:18 UTC
Labels: component: $http, needs: more info
