### ISSUE TITLE
ngAnimate makes IE11 grind to a halt

### ISSUE THREAD

**Issue by circlingthesun** [angular/angular.js#11791] opened 2015-05-02 16:48 UTC
This jsfiddle (http://jsfiddle.net/oga2z7bb/3/) uses ng-repeat to render 10000 numbers. This jsfiddle (http://jsfiddle.net/oga2z7bb/4/) does the same thing but includes ngAnimate.

Both examples work fine in Chrome & Firefox. The first example also works in IE11, however if you open http://jsfiddle.net/oga2z7bb/4/ in IE11 your browser should stop responding. I've profiled (with 1 000 numbers instead of 10 000) this and it seems that 99% of the time is spent in ```window.requestAnimationFrame()```.

I use ng-repeat to render a calendar in my app. With IE11 it is effectively unusable unless I do some browser sniffing and not load ngAnimate when IE is detected.

**Comment by circlingthesun** [comment] 2015-05-02 17:01
Here it is again with 1000 elements
on 1.3.15:
   https://jsfiddle.net/oga2z7bb/7/
on 1.4.0-rc.1:
   https://jsfiddle.net/oga2z7bb/8/

The example on 1.4.0-rc.1 takes a lot longer to show when compared to 1.3.15.

**Comment by Narretz** [comment] 2015-05-03 11:53
Can confirm that there's a significant delay.

**Comment by Narretz** [comment] 2015-05-03 18:49
It also happens in the latest snapshot. Interestingly, it doesn't regress if you combine an angular version from before the refactoring (say 1.4.0-beta.6) with an animate version from after the refactoring.

**Comment by alexlamsl** [comment] 2015-05-03 19:35
@Narretz at least `$$AnimateRunner` is not defined in the earlier versions of `angular.js`, which seems to be required by the latest `angular-animate.js`

So probably not regressing due to the module not being loaded successfully?

**Comment by matsko** [comment] 2015-05-04 18:19
OK there is now a fix for this:

Existing (broken) version:
http://104.131.123.85/ngAnimate/regressions/11791/broken.html

Fixed version:
http://104.131.123.85/ngAnimate/regressions/11791/fixed.html

**Closed** 2015-05-05 21:20 UTC
Labels: component: ngAnimate, severity: regression, type: perf

**Comment by mzgol** [comment] 2015-07-01 14:39
Was this submitted to MS? I couldn't find it so I created my own report:
https://connect.microsoft.com/IE/feedback/details/1494442

We should be good Web citizens, though, and report such issues to browser vendors. If they don't know about it, they can't fix it!
