### ISSUE TITLE
Scope doesnt update on selects when using arrow keys

### ISSUE THREAD

**Issue by esiege** [angular/angular.js#10887] opened 2015-01-27 22:35 UTC
(Simple dropdown jsfiddle)
http://jsfiddle.net/derkoe/KN9xx/presentation/

Click on first dropdown twice to activate.  Press down arrow.  Ng-model updates.  Press down again.  Ng-model does not update.

(Testing in chrome)

**Comment by VitalyTomilov** [comment] 2015-01-28 00:07
I have simplified the example and updated AngularJS from 1.1.4 to 1.3.11, the issue is still very easy to see: http://jsfiddle.net/KN9xx/301/

It's got something to do with the initial arrowDown key, while arrowUp key works perfectly.

The issue appears to be browser-specific:

- Doesn't happen in IE11;
- Happens in Chrome as described above;
- In FireFox it is much worse - arrow keys result in no model update at all!

**Comment by petebacondarwin** [comment] 2015-01-28 13:42
This is a duplicate of #7600

**Comment by petebacondarwin** [comment] 2015-01-28 13:43
and #9134

**Comment by petebacondarwin** [comment] 2015-01-28 13:44
and #10382

**Closed by petebacondarwin** 2015-01-28 13:43 UTC
