### ISSUE TITLE
date filter i18n does not  change according to the language that i have setted

### ISSUE THREAD

**Issue by zhaoxiong** [angular/angular.js#13810] opened 2016-01-21 10:44 UTC
if i developed a mobile application  that would use five language ,i have to import different angular-locale_localeId.js in the head tag which means i have to release five different versions(that's a little annoying) .I even couldn't switch the language once i have install the app .is it possible that i can dynamic switch my language without  consider too much the i18n of the date filter? by the way ,i have use angular-dynamic-locale to resolve the problem ,but it has a little defect,it works well on the pc(i use anywhere to run my app),it does not work on my android mobile(i use ionic to develop a hybrid mobile app).I'm sure it's not my problem,It's the same code just run on different platforms

**Comment by petebacondarwin** [comment] 2016-01-21 20:48
I do not know much about developing multilingual PhoneGap applications but the only support that AngularJS has for changing $locale is by refreshing the browser and loading a new page with a different locale file. Is this possible in PhoneGap apps?

**Comment by zhaoxiong** [comment] 2016-01-22 07:10
by the way,i know angular-translate use $translateProvider.determinePreferredLanguage() to determining preferred language automatically.why does date filter i18n not implement the same way?

**Comment by petebacondarwin** [comment] 2016-01-22 09:31
The way that `ngLocale` works means that you cannot select the module after the angular app has bootstrapped. If you want to dynamically choose the locale module to load, you must do this outside of Angular before the application bootstraps.

**Comment by Krabi** [comment] 2016-02-01 19:04
Why it is done so? Loading page again is total... Loading page again breaks that single page fancy thing - load once and request only data as needed! From my point of view very badly designed part that should be fixed.

**Comment by lgalfaso** [comment] 2016-02-01 19:45
There are several third-party modules that are able to do this. Shameless advertising https://github.com/lgalfaso/angular-dynamic-locale

**Comment by Krabi** [comment] 2016-02-01 20:02
To fix angular problems, those that should be implemented in angular? I don't think so, that external and third party tools should do things that should be logically part of angular.

**Comment by lgalfaso** [comment] 2016-02-01 20:17
Sorry @Krabi but I do not share your point of view. Angular core does a lot of things, but this is not reason for Angular core to do everything. The ability to dynamically change the locale is something that a small percentage of applications need, and adding this functionality to the core would imply that everybody that builds an Angular app would have to pay for the extra bytes that this adds.


This is why there are many third-party modules that solve in some specific way a given necessity. In most cases that there are multiple modules that solve the same problem, this is because there are other requirements that are specific to one or other environment. This make the Angular ecosystem healthier.

**Comment by Krabi** [comment] 2016-02-01 20:28
We newer getting consensus :)

**Comment by gkalpak** [comment] 2016-06-03 20:24
I'm going to close this, since this is workign as intended.

**Closed by gkalpak** 2016-06-03 20:24 UTC
Labels: component: ngLocale
