### ISSUE TITLE
Changing variable doesn't update CSS class in Chrome Dev

### ISSUE THREAD

**Issue by rsmith31415** [angular/angular.js#13264] opened 2015-11-06 06:31 UTC
There is small issue after changing a variable in order to set a CSS class. This is better explained using an example:

[Demo](http://plnkr.co/edit/0dtRMNxqb0hQmOPLLSsH?p=preview)

The idea is that after clicking one of the words, the property that controls a CSS class will be updated to reflect the selected word.

```
<div ng-click="changeStatus(button)" ng-repeat="button in buttons" ng-class="{value: button.status}">
        {{ button.name }}
</div>
```

So there are a couple of objects in an array called `buttons` and we want to show a different color for the element with class `value` which is set if the property `button.status` is `true`.

The problem is that if you alternate between clicking on "button1" and "button2" several times, eventually you will find that the recently clicked element doesn't change color as it should. However, modifying something in the browser or moving the mouse over other elements in the page triggers the appropriate change. As far as I can tell, this only happens in Chrome dev. I tested in Firefox and Chrome stable (on Ubuntu 15.10) and I believe this problem doesn't occur (although maybe I'm not repeating the process enough times). 

I initially thought this was due to the digest cycle not being triggered immediately, but I'm not sure why this only occurs occasionally and other browsers seem to be producing the correct behavior. Any ideas?

**Comment by Narretz** [comment] 2015-11-06 12:46
So what I should be seeing is that the currently red button loses its color, but the clicked button doesn't become red? I have tested this in Chrome 48.0.2556.0 canary (64-bit), but I do not see this behavior.

**Comment by rsmith31415** [comment] 2015-11-06 15:57
Correct. This is what I see in Chrome dev:

![out](https://cloud.githubusercontent.com/assets/599274/11001272/03d45078-846c-11e5-9fca-d24cd40cc40a.gif)

When I'm moving the cursor over a word, I'm actually clicking but as you can see, nothing happens. Usually, it takes a few trials before getting this behavior although in the gif this is occurring very frequently.

**Comment by Narretz** [comment] 2015-11-06 21:44
Hm, I can reproduce it. Im on Windows btw, maybe that's another factor.
At the moment it looks like a bug in Chrome that's hopefully temporary and won't make it into a full release.

**Comment by rsmith31415** [comment] 2015-11-07 00:20
I hope so. It works in Chrome beta, by the way. I will keep testing the following releases.

**Comment by Narretz** [comment] 2015-11-13 14:24
Thanks @rsmith31415 . If it shows up in a beta, we need to worry.

**Comment by rsmith31415** [comment] 2015-12-14 20:40
@Narretz Bad news. This is now occurring in 48.0.2564.41 beta.

**Comment by Narretz** [comment] 2015-12-14 21:47
I reckon this is related to https://github.com/angular/angular.js/issues/13494, and we are working on a fix for that.

**Comment by Narretz** [comment] 2015-12-14 21:59
Arg, the demo doesn't even include ngAnimate, so it can't be that. Do you have any plugins running etc.?

**Comment by rsmith31415** [comment] 2015-12-14 23:22
No, I'm running a clean installation of Chrome beta. It only includes the default extensions (Google Docs, Google Sheets, Google Slides)

**Comment by rsmith31415** [comment] 2016-01-14 03:27
@Narretz A little update.

In the most recent version of Chrome dev (49.0.2618.8), the bug is not occurring anymore. However, it  reappears when I tested in incognito mode. That's very unusual.

Can you reproduce this behavior? 

The bug is still showing up in Chrome beta but still absent in Chrome stable.

**Comment by Narretz** [comment] 2016-01-19 14:00
@rsmith31415 I can't reproduce it. Maybe ypu should open an issue with the Google Chrome tracker.

**Comment by rsmith31415** [comment] 2016-01-20 15:22
@Narretz I just tested in the latest Chrome dev (49.0.2623.0 dev) and now this bug is also occurring with and without incognito mode. Should I still report this as a bug to the Chrome tracker?

**Comment by rsmith31415** [comment] 2016-01-22 08:19
@Narretz Bad news. Now this bug can be seen in Chrome stable (48.0.2564.82)

**Comment by Narretz** [comment] 2016-01-22 16:53
I cannot reproduce this.
But you should report it yes.

**Comment by rsmith31415** [comment] 2016-01-22 18:20
I reported the bug [here](https://code.google.com/p/chromium/issues/detail?id=580606&thanks=580606&ts=1453486699).

**Comment by petebacondarwin** [comment] 2016-01-22 18:44
I could repro on Chrome 47 or 48.0.2564 (OS/X) (or in Incognito mode)

**Comment by Narretz** [comment] 2016-01-22 19:07
@petebacondarwin Hm, that's bad! Did you also try with 1.4.9? I wonder if this is related to the animation timekeeping - should be fixed in 1.4.9

**Comment by petebacondarwin** [comment] 2016-01-22 20:06
Sorry I have edited my comment :-)

**Comment by Narretz** [comment] 2016-01-22 20:20
You scared me there for a moment!

**Comment by gkalpak** [comment] 2016-06-02 12:00
Based on the [reported bug][1] it seems to affect specific distributions only (Ubuntu GNOME) and if anything shouldn't be related to Angular.

Closing due to lack of reproduction. 

[1]: https://bugs.chromium.org/p/chromium/issues/detail?id=580606&thanks=580606&ts=1453486699

**Closed by gkalpak** 2016-06-02 12:00 UTC
Labels: browser: chrome, needs: browser fix, resolution: can't reproduce
