### ISSUE TITLE
Feature Request: ng-message referencing input's min/max

### ISSUE THREAD

**Issue by adrianandreias** [angular/angular.js#10037] opened 2014-11-13 07:39 UTC
Implement the ability to write a generic ng-message in the ng-messages-include html that would reference min/max attributes of the referred input.
Something like:

<span ng-message="min">The value must be in range {{ field.min }} to {{ field.max }}.</span>

**Comment by Narretz** [comment] 2016-03-23 23:23
Dupe of https://github.com/angular/angular.js/issues/9849

**Closed by Narretz** 2016-03-23 23:23 UTC
Labels: component: forms, component: ngMessages, frequency: low, severity: broken expected use, type: feature
