### ISSUE TITLE
Binding doesn't work on value attribute of <progress> element in IE11

### ISSUE THREAD

**Issue by tkrugg** [angular/angular.js#12482] opened 2015-08-02 07:53 UTC
Here is a [sample](http://plnkr.co/edit/NVrbDEy53lHfFGlHMu7P?p=preview) that illustrates it. As you can see the progress element stays at value=0.

seen on IE11 with angular 1.4

**Comment by Narretz** [comment] 2015-08-03 22:57
That's a dupe of #7218 (see workaround in the issue)

**Closed by Narretz** 2015-08-03 22:57 UTC
