### ISSUE TITLE
Bug: Multiple select gets jumpy when used in the ui-bootstrap modal body

### ISSUE THREAD

**Issue by tharumax** [angular/angular.js#6608] opened 2014-03-07 23:02 UTC
When a user tries to click the options inside the select with `multiple`, which is located inside the `modal-body` of  `ui-bootstrap` modal, sometimes it gets jumpy and reverts back to previously selected options:

demo : http://plnkr.co/edit/Bg3hYkcClhYq5JSnHX8d?p=preview

Currently I was able to workaround this problem by adding this to

```
        selectElement.on('click', function(evt) {
          evt.stopPropagation();
        });
````

after line 343 in `src/ng/directive/select.js`. I do not know whether this is a proper solution or really did not have time to test this for side effects.

PS: Tested on Chrome 33.0.1750.146.

**Comment by Narretz** [comment] 2015-06-16 10:37
Interesting. The last plnkr shows this pretty well. Basically, when the multi select is scrolled somewhere in the middle and the height of the modal changes (in the plnkr, this happens when items are sent from one to the other list), the select scrolls a little bit, which is unexpected. It doesn't affect the selection, though. Happens in FF and Chrome.

**Comment by gkalpak** [comment] 2015-06-16 11:57
@Narretz, what you describe (which is probably different from what OP faces), only happens when you remove items that are higher than the currently scrolled to item. Basically, the select doesn't scroll, but it's height and items change.
I.e. when you have scrolled the select to `scrollTop === 130` at which point item `foo` is visible and then remove 10 items above `foo`, the select remains at `scrollTop === 130` but now item `bar` is visible at that point (because item `foo` moved 10 positions up).

I don't know if browsers should be smarter and keep the selected element or currently visible element in the viewport (I lean towards _they shouldn't_), but this doesn't sound like an Angular issue.
That said, I can't reprodice the original issue on Chrome 43/Win8.1.

**Comment by Narretz** [comment] 2015-10-09 16:36
@gkalpak Yes, you are right, this seems to be a different problem. Annoying, but also with very little impact.
Since I also can't reproduce the original problem, I'm gonna close this issue.

**Closed by Narretz** 2015-10-09 16:36 UTC
Labels: component: forms, frequency: low, severity: inconvenient, type: bug
