### ISSUE TITLE
$compile doesn't work properly with directive transclusion

### ISSUE THREAD

**Issue by eloytoro** [angular/angular.js#11624] opened 2015-04-16 22:10 UTC
I came across this particular issue because I noticed that sometimes when I compile an element it wouldnt create a two-way-data-binding properly for some of the `ng-model` directives

```javascript
.directive('transcludeTest', function () {
  return {
    restrict: 'A',
    transclude: true,
    template: '<div ng-transclude></div>'
  };
})

.controller('ViewCtrl', function ($document, $scope, $compile) {
  $compile('<div transclude-test><input ng-model="name"></div>')($scope, function (clone) {
    $document.append(clone);
    $scope.$watch('name', function (name) {
      console.log($scope.$name); // <- always logs undefined
      console.log(name) // <- shows the correct value
    });
  });
});
```

Is this the desired behaviour? It doesn't make much sense that `$compile` would compile directives but not the ones that transclude content. If so why would `$watch` trigger whenever the given property is modified but at the same time the property is **not defined** in the scope?

**Comment by lgalfaso** [comment] 2015-04-17 05:01
There is a typo in your example.

console.log($scope.$name);

Should be

console.log($scope.name);


If the issue is something else, please create a plunker

**Comment by eloytoro** [comment] 2015-04-17 15:50
Yes indeed, I'm still getting the issue, but not with the code displayed above.
I'll try to come up with a more concise example (and no typos)

**Comment by lgalfaso** [comment] 2015-04-17 16:43
I am going to close this, but once you have an example that shows the issue, feel free to reopen it

**Closed by lgalfaso** 2015-04-17 16:43 UTC

**Comment by eloytoro** [comment] 2015-09-12 17:10
Request to reopen this issue since I found how to repro this with a simple example
```html
<div>
  {{ text }} <!-- does not bind to the transcluded scope -->
  <my-transclude-directive>
    {{ text }} <!-- binds to the scope model -->
    <input type="text" ng-model="text">
  </my-transclude-directive>
</div>
```
Turns out that the ng-model only updates the value of the transcluded binding, whereas the binding outside the transcluded scope stays the same

Is this intended? How do I overcome this?

**Comment by lgalfaso** [comment] 2015-09-12 17:17
If you found a way to reproduce the issue and created a plunker, feel free
to reopen this issue

**Comment by eloytoro** [comment] 2015-09-12 17:36
Play with the input fields and you'll see what i mean.
http://plnkr.co/edit/wUUf2mmOocFY6wL41osI

**Comment by lgalfaso** [comment] 2015-09-13 11:45
@eloytoro this is working as intended. Please check https://github.com/angular/angular.js/wiki/Understanding-Scopes to understand how scopes work. The link is slightly outdated, but this case is covered in full
