### ISSUE TITLE
Email Id validation fails in AngularJS V1.8.0

### ISSUE THREAD

**Issue by Vishal-Bhavsar** [angular/angular.js#17089] opened 2020-10-13 07:22 UTC
Hi,

It looks like email id validation fails for AngularJS V1.8.0.
As per document https://docs.angularjs.org/api/ng/input/input%5Bemail%5D the email id me@example is a valid email id but it shouldn't be.

Could you please look in to it and provide resolution for same.

**Comment by gkalpak** [comment] 2020-10-13 13:43
This is a duplicate of #16177 (among others :grin:).

**tl;dr**
Such e-mails are valid (see also #14719 for some discussion and links to more info regarding valid e-mail addresses in general).

##
As mentioned in [the docs][1], if you need different validation rules, you can either use `ng-pattern` or modify the built-in `email` validator.

[1]: https://docs.angularjs.org/api/ng/input/input%5Bemail%5D

**Closed by gkalpak** 2020-10-13 13:43 UTC
