### ISSUE TITLE
Angular does not throw exception for un-assigned bi-directional scope property

### ISSUE THREAD

**Issue by dukehoops** [angular/angular.js#6060] opened 2014-01-30 16:57 UTC
please [see demo](http://plnkr.co/edit/1uexf11wnVOyly3Yjna2?p=preview) - notice that  `foo` is not assigned yet  there is no exception in console. Per [`$compile` docs](http://docs.angularjs.org/api/ng.$compile) exception should be raised, since `foo` is non-optional:

> If the parent scope property doesn't exist, it will throw a NON_ASSIGNABLE_MODEL_EXPRESSION exception. You can avoid this behavior using =? or =?attr in order to flag the property as optional.

nice to have: IMO attributes should be treated in the same way: required unless `?` is used

**Comment by Narretz** [comment] 2017-07-25 14:07
Further discussion here https://github.com/angular/angular.js/issues/6060

Closing as duplicate of #6080

**Closed by Narretz** 2017-07-25 14:07 UTC
Labels: component: $compile, frequency: high, needs: breaking change, type: bug
