### ISSUE TITLE
Infinite digest loop when query param contains special char

### ISSUE THREAD

**Issue by smoebody** [angular/angular.js#16643] opened 2018-07-24 12:57 UTC
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**
When a query parameter contains a special character such as `'` angular goes into an infinite digest loop.

**Expected / new behavior:**
angular behaves normally

**Minimal reproduction of the problem with instructions:**
just open the public website:
https://angularjs.org/?foo=bar%27

the URL contains a key-value pair `{ foo: "bar'" }` as query-parameter.
Open the developer console and you can see javascript spamming messages

**AngularJS version:** 1.7.2 
this is what i experienced the problem with. I don't know which version angularjs.org is running at.

**Browser:** [Chrome 67.0.3396.99 | Firefox 61.0.1 ]

Operating System is Fedora Core 28

**Anything else:**

**Comment by Narretz** [comment] 2018-07-24 13:08
Dupe of https://github.com/angular/angular.js/issues/16592

We hope to have a release out later this week

**Closed by Narretz** 2018-07-24 13:08 UTC

**Comment by useltmann** [comment] 2018-07-24 15:20
All right. Thanks for not yelling at me. I thought I searched thoroughly all existing issues but appearently i didn't.
