### ISSUE TITLE
$cookieStore Creating Duplicate Cookies

### ISSUE THREAD

**Issue by nmellempudi** [angular/angular.js#10995] opened 2015-02-06 17:38 UTC
We are adding a cookie using $cookieStore as shown below. But this step will also create additional new cookies with sub domain name xyz.abc.com. These new copies are just copy of existing cookies added by prior server call with domain name .abc.com  

To provide step by step details

1. Loading the page xyz.abc.com/index.html  sets two cookies with domain .abc.com
2. Set a cookie on client side $cookieStore.put('cookieAng', 'Test'). Now you will see total 5 cookies.
       Two original cookies with domain name .abc.com
        one new cookie that we set through cookiestore with domain xyz.abc.com
        two additional cookies (copy of original two cookies) with domain name xyz.abc.com

Any thoughts? Below is bower.json

		"angular": "1.2.22",
		"restangular": "1.4.0",
		"angular-animate": "1.2.22",
		"angular-mocks": "1.2.22",
		"angular-route": "1.2.22",
		"angular-cookies": "1.2.22",

**Comment by Narretz** [comment] 2015-02-09 21:14
Hi,
in which browsers do you see this? Any or a specific browser? And to clarify, the problem is that angular diuplicates cookies that have been set from the server side?

@shahata Do you have any idea why this might happen? I'm actually not very knowledgable about cookie setting behavior.

**Comment by nmellempudi** [comment] 2015-02-10 16:12
It can be re produced in any browser. Yes. Some cookies were set on server with domain .abc.com even though host name is xyz.abc.com. As soon as I create a cooki with cookiStore it duplicates existing other cookies with different domain value(xyz.abc.com) and path.

**Comment by shahata** [comment] 2015-02-20 23:09
@nmellempudi This shouldn't happen unless you changed the value of those cookies. Can you post an example on plunker or something similar that reproduces your issue?

**Comment by Narretz** [comment] 2015-06-16 22:12
I'm going to close this because we don't have a reproduction. It's possible that this was fixed as part of https://github.com/angular/angular.js/commit/706a93ab6960e3474698ccf9a8048b3c32e567c6

**Closed by Narretz** 2015-06-16 22:12 UTC
Labels: component: ngCookies, needs: more info
