### ISSUE TITLE
ng-repeat with ng-form not working properly if we remove first element of array

### ISSUE THREAD

**Issue by AtahAhmed** [angular/angular.js#14813] opened 2016-06-22 08:18 UTC
I have ng-repeat with ng-form and I am using ng-messages to show validation messages. When I delete first element of ng-repeat using splice, ng-repeat is updating properly, but ng-form for 1st element is not getting created and the next element's validation message is not shown

**Comment by Narretz** [comment] 2016-06-22 10:33
Hi, thanks for the report. Can you please put a demo of the problem in a https://plnkr.co or similar? Otherwise we can't assess if this is really a bug.

**Comment by Narretz** [comment] 2016-06-24 09:34
I'm going to close this issue because we have no reproduction of the issue. Feel free to reopen this issue if you can provide a reproduction (ideally a runnable demo in a https://plnkr.co or similar).

**Closed by Narretz** 2016-06-24 09:34 UTC
Labels: component: forms, needs: more info
