### ISSUE TITLE
Angular 1.5 RC 0: ng-show bug

### ISSUE THREAD

**Issue by azurelogic** [angular/angular.js#13740] opened 2016-01-11 18:20 UTC
We attempted to upgrade from 1.4.8 to 1.5 RC to start using .component. However, when we did this, the following line of markup stopped working in Chrome and IE 11 (but it works in Firefox):

    <div ng-repeat="ticketType in vm.ticketTypes" ng-show="vm.ticketTypeCount(ticketType) > 0">

Under 1.5, all of the items generated by the ng-repeat get hidden. This is very puzzling. Are we doing something wrong here, or is this a bug?

**Comment by gkalpak** [comment] 2016-01-11 18:33
@azurelogic, could you create a live demo (e.g. using CodePen, Plnkr etc), so it is easier to reproduce and investigate the issue ?

**Comment by gkalpak** [comment] 2016-01-11 18:45
I tried to reproduce it [here][1], but everything works as expected.

[1]: https://codepen.io/ExpertSystem/pen/RrggPG?editors=100

**Comment by azurelogic** [comment] 2016-01-11 19:13
@gkalpak, that's interesting. Your sample works fine. I'll have to try to work up a plunker when I have a moment.

It's a really weird bug. I thought it was something in our ticketTypeCount function, but it worked in Firefox, and there are no console errors. Funny thing is that it works in Chrome if I put in `ng-show="1 > 0"` too. I thought maybe it had to do with the actual expression evaluation. It's just so strange.

**Comment by gkalpak** [comment] 2016-01-11 19:42
That's indeed strange. Could it be something with the data (based on which `ticketTypeCount()` calculates its return value) ? Try logging the return value of `vm.ticketTypeCount(ticketType)` and see what you get in each browser.

**Comment by Narretz** [comment] 2016-01-11 20:56
@azurelogic Have you tried with the current snapshot:
http://code.angularjs.org/snapshot/angular.js
http://code.angularjs.org/snapshot/angular-animate.js

**Comment by Narretz** [comment] 2016-01-15 14:53
Closing due to no feedback. Feel free to reopen if you have more information

**Closed by Narretz** 2016-01-15 14:53 UTC
Labels: branch: 1.5.x, component: misc core, frequency: high, needs: more info, severity: regression, type: bug
