### ISSUE TITLE
Error: undefined is not an object (evaluating 'element.nodeType')

### ISSUE THREAD

**Issue by seaside98** [angular/angular.js#12771] opened 2015-09-06 14:58 UTC
I often get this error when changing routes (I am using ngRoute). 

The route's templateUrl loads fine, but all directives contained in the template don't load.

Browser: Safari 8.0.8 on OSX
Stack trace:
```
[Error] Error: undefined is not an object (evaluating 'element.nodeType')
append@http://localhost/netflix/app/bower/angular/angular.js:3407:27
http://localhost/netflix/app/bower/angular/angular.js:3532:19
startingTag@http://localhost/netflix/app/bower/angular/angular.js:1285:40
invokeLinkFn@http://localhost/netflix/app/bower/angular/angular.js:8748:41
nodeLinkFn@http://localhost/netflix/app/bower/angular/angular.js:8246:23
compositeLinkFn@http://localhost/netflix/app/bower/angular/angular.js:7637:23
publicLinkFn@http://localhost/netflix/app/bower/angular/angular.js:7512:45
boundTranscludeFn@http://localhost/netflix/app/bower/angular/angular.js:7656:28
controllersBoundTransclude@http://localhost/netflix/app/bower/angular/angular.js:8273:35
update@http://localhost/netflix/app/bower/angular-route/angular-route.js:935:36
$broadcast@http://localhost/netflix/app/bower/angular/angular.js:16200:33
http://localhost/netflix/app/bower/angular-route/angular-route.js:619:36
processQueue@http://localhost/netflix/app/bower/angular/angular.js:14634:30
http://localhost/netflix/app/bower/angular/angular.js:14650:39
$eval@http://localhost/netflix/app/bower/angular/angular.js:15878:28
$digest@http://localhost/netflix/app/bower/angular/angular.js:15689:36
$apply@http://localhost/netflix/app/bower/angular/angular.js:15986:31
http://localhost/netflix/app/bower/angular/angular.js:12165:30
eventHandler@http://localhost/netflix/app/bower/angular/angular.js:3293:25
```

**Comment by Narretz** [comment] 2015-09-19 10:51
Can you please provide a minimal demo on plnkr.co or similar?

**Comment by Narretz** [comment] 2015-11-03 21:59
Closing because we don't have a reproduce scenario.

**Closed by Narretz** 2015-11-03 21:59 UTC
Labels: browser: iOS, needs: more info

**Comment by btpka3** [comment] 2017-07-31 10:04
angular 1.5.11 + webpack, iOS simulator  with  Hardware/device/ios 8.1/iphone 5s.
found :

<img width="1242" alt="ng1-undefined" src="https://user-images.githubusercontent.com/1555406/28772957-4b5a168e-761a-11e7-887b-4816a385f3a9.png">


been wondering why 'this[i]=== undefined' ?  Should jquery be introduced? Need to try~

**Comment by gkalpak** [comment] 2017-07-31 11:28
It is not expected for `this[0]` to be undefined. It can only happen if `this.length` is not properly updated (and this shouldn't happen normally).
We still need a reproduction 😕

**Comment by seaside98** [comment] 2017-07-31 12:50
Wow this is old. This bug was specific to Safari 8, I've never seen it in any later version of Safari. Upgrading my browser a few years ago fixed the issue.
