### ISSUE TITLE
$http cache broke when working with angular cache

### ISSUE THREAD

**Issue by Delagen** [angular/angular.js#13980] opened 2016-02-09 12:55 UTC
angular 1.5 final
this code confusing with angular-cache
```
 if (isPromiseLike(cachedResp)) {
            // cached request has already been sent, but there is no response yet
            cachedResp.then(resolvePromiseWithResult, resolvePromiseWithResult);
          } else {
            // serving from cache
            if (isArray(cachedResp)) {
              resolvePromise(cachedResp[1], cachedResp[0], shallowCopy(cachedResp[2]), cachedResp[3]);
            } else {
              resolvePromise(cachedResp, 200, {}, 'OK');
            }
          }
....
function resolvePromiseWithResult(result) {
	        resolvePromise(result.data, result.status, shallowCopy(result.headers()), result.statusText);
	      }
```
produces error such as headers is not a function

if promise result is interpreted in one way if not promise in another
changed to
```
function resolvePromiseWithResult(result) {
	      if (isArray(result)) {
	              resolvePromise(result[1], result[0], shallowCopy(result[2]), result[3]);
	            }
			else{
	        resolvePromise(result.data, result.status, shallowCopy(result.headers()), result.config);
	        }
	      }
```
and this solved my day

**Comment by Narretz** [comment] 2016-02-09 14:14
Hm, if this is a problem with angular-cache, then angular-cache needs to solve it. In any case, I'm not really sure where exactly the problem is. Could you try to put a demo in a plnkr.co or similar? Or at least show your code setup? Also, is this something that worked before?

**Comment by Delagen** [comment] 2016-02-09 14:19
I working with it with storeOnReject so it caches and negative responses. I think problem in this

Why in code if it is not promise and response array [response, status, headers, statusText] it parses as
```
resolvePromise(cachedResp[1], cachedResp[0], shallowCopy(cachedResp[2]), cachedResp[3]);
```
but if promise is opened it parses as object
```
resolvePromise(result.data, result.status, shallowCopy(result.headers()), result.config);
```
???

**Comment by Narretz** [comment] 2016-02-09 14:26
So, just to make sure you are using https://github.com/jmdobry/angular-cache? Then I would advise that you ask for support / clarification there first. At the moment it's not clear that this is a bug with angular core.

**Comment by Delagen** [comment] 2016-02-09 19:25
Reworked my code and it works, because no promises in cache

But core code still inconsistent because different ways of processing data passed with promise and without
```
if (isPromiseLike(cachedResp)) {
	            // cached request has already been sent, but there is no response yet
	            cachedResp.then(resolvePromiseWithResult, resolvePromiseWithResult);
// WTF processed different as it does on condition without promise
	          } else {
	            // serving from cache
	            if (isArray(cachedResp)) {
	              resolvePromise(cachedResp[1], cachedResp[0], shallowCopy(cachedResp[2]), cachedResp[3]);
	            } else {
	              resolvePromise(cachedResp, 200, {}, 'OK');
	            }
	          }
```

**Comment by gkalpak** [comment] 2016-02-09 19:43
@Delagen, a promise indicates (as the comment says) that a request to the same URL has been sent, but the response hasn't arrived yet. In that case, we don't need to send a second request, we will use the returned response as soon as it arrives (so in that case we will be consuming a `response` object).

The difference is that a `response` object has a `headers` function property (which we have to call to get the headers). Once the response has arrived and cached, the cached response object (`cachedResp`) contains a headers map as its 3rd argument.

--
Closing as everything works as expected.

**Closed by gkalpak** 2016-02-09 19:43 UTC
Labels: component: $http, needs: more info

**Comment by Delagen** [comment] 2016-02-10 06:29
If cacheFactory implementation will be async and return promise. That method will cause error.
I see now that you prevent with this multiple get requests to the same url

**Comment by gkalpak** [comment] 2016-02-10 09:10
As mentioned in [the docs][1], the cache should be a _cache object (built with `$cacheFactory`)_ and it's used from `$http` to cache responses. If you decide to use your own implementation of a cache object, you must ensure that it's API doesn't defer from those created with `$cacheFactory` (which also includes not returning promises, but the stored data directly).

Although not explicitly supported, if you want to initialize your cache with some data fetch asynchronously, you should make sure that the result returned from your promise matches the `response` object that `$http` expects.

[1]: https://docs.angularjs.org/api/ng/service/$http#caching
