### ISSUE TITLE
Animation issue on Android 4.1.2.

### ISSUE THREAD

**Issue by mdudek** [angular/angular.js#12187] opened 2015-06-22 14:09 UTC
Hi, 

I'm facing issue regarding angular animations in my Cordova app running on Android 4.1.2. It happen time to time, its hard to reproduce and I don't know what it could be caused by. I have tried both versions of Angular (1.3.16 and 1.4)

Here is stacktrace:

```
Details:Cannot set property 'WebkitTransitionProperty' of undefined: TypeError: Cannot set property 'WebkitTransitionProperty' of undefined
    at blockTransitions (file:///android_asset/www/js/lib/angular-animate.js:1982:70)
    at animateSetup (file:///android_asset/www/js/lib/angular-animate.js:1813:11)
    at animateBefore (file:///android_asset/www/js/lib/angular-animate.js:1990:13)
    at Object.beforeAddClass [as fn] (file:///android_asset/www/js/lib/angular-animate.js:2086:36)
    at file:///android_asset/www/js/lib/angular-animate.js:741:46
    at forEach (file:///android_asset/www/js/lib/angular.js:326:20)
    at run (file:///android_asset/www/js/lib/angular-animate.js:729:11)
    at Object.before (file:///android_asset/www/js/lib/angular-animate.js:770:13)
    at performAnimation (file:///android_asset/www/js/lib/angular-animate.js:1413:16)
    at file:///android_asset/www/js/lib/angular-animate.js:1219:17
```

Dont you have and idea what could be wrong with it? Thanks for help.

**Comment by matsko** [comment] 2015-06-22 14:48
Maybe it's attempting to animate a comment node or a non-element node somehow? Is there anyway you could do a `console.log(node)` for the node in that function (`blockTransitions`)?

**Comment by mdudek** [comment] 2015-06-22 19:42
This issue is reported by our external tester, I will modify angular-animate.js with this logging and  create special app version for him. We will hopefully get better info about related node.

**Comment by matsko** [comment] 2015-07-15 20:15
Would you mind testing this out on the latest version of Angular?

**Comment by matsko** [comment] 2015-07-17 18:38
Could you test this out on 1.4.3 or snapshot?
https://code.angularjs.org/1.4.3/angular-animate.js
https://code.angularjs.org/snapshot/angular-animate.js

We fixed a few issues with the node being deleted during an animation. Perhaps this also fixed this issue.

**Comment by mdudek** [comment] 2015-07-20 08:02
ok, we will try v1.4.3, if its fixed...

**Comment by matsko** [comment] 2015-07-28 20:37
Any luck?

**Comment by mdudek** [comment] 2015-07-29 05:06
It looks good, no issues reported after two days of testing. But it needs more time to finally confirm that its fixed, because this issue happen time to time.

**Comment by matsko** [comment] 2015-07-29 05:07
Sure thing.

**Comment by mdudek** [comment] 2015-08-12 12:48
I got similar exception from tester today:

```
Details:Cannot set property 'WebkitTransitionDelay' of undefined

Stack:TypeError: Cannot set property 'WebkitTransitionDelay' of undefined
    at applyInlineStyle (file:///android_asset/www/js/lib/angular-animate.js:689:20)
    at blockTransitions (file:///android_asset/www/js/lib/angular-animate.js:675:3)
    at applyBlocking (file:///android_asset/www/js/lib/angular-animate.js:1094:11)
    at init (file:///android_asset/www/js/lib/angular-animate.js:1018:7)
    at prepareRegularAnimation (file:///android_asset/www/js/lib/angular-animate.js:1537:22)
    at initDriverFn (file:///android_asset/www/js/lib/angular-animate.js:1321:13)
    at invokeFirstDriver (file:///android_asset/www/js/lib/angular-animate.js:2911:24)
    at triggerAnimationStart (file:///android_asset/www/js/lib/angular-animate.js:2763:31)
    at runNextTask (file:///android_asset/www/js/lib/angular-animate.js:313:5)
    at nextTick (file:///android_asset/www/js/lib/angular-animate.js:297:7)
```

**Comment by matsko** [comment] 2015-08-14 21:26
@mdudek we just released 1.4.4 with some nice fixes for ngAnimate. Would you mind testing against that one?

**Comment by mdudek** [comment] 2015-08-21 08:43
@matsko we just downloaded 1.4.4, but I found that css animations are completely broken ! I have checked that animations worked in previous 1.4.3. Its really big issue.

**Comment by matsko** [comment] 2015-08-25 17:57
@mdudek I'm sorry to hear that. Can you test against these files:
http://www.angular-dev.com/raf-fix/angular.js
http://www.angular-dev.com/raf-fix/angular-animate.js

There's a fix in here that will be applied to 1.4.5.

**Comment by mdudek** [comment] 2015-08-25 18:25
@matsko Thanks for fix, animations works perfectly with this build. We will test 'WebkitTransitionDelay' related issue against this build. When we could expect stable release of 1.4.5?

**Comment by matsko** [comment] 2015-08-25 18:27
Awesome. Later this week.

**Comment by matsko** [comment] 2015-08-25 18:27
1.4.5 will come out then.

**Comment by mdudek** [comment] 2015-08-25 18:28
Great news thanks for info.

**Comment by mdudek** [comment] 2015-08-26 11:35
I have just found another exception right now in v1.4.5-local+sha.0e00108:

Details:Cannot read property 'length' of undefined

Stack:TypeError: Cannot read property 'length' of undefined
    at onAnimationExpired (file:///android_asset/www/js/lib/angular-animate.js:1326:67)
    at file:///android_asset/www/js/lib/angular.js:18215:49
    at completeOutstandingRequest (file:///android_asset/www/js/lib/angular.js:5615:20)
    at file:///android_asset/www/js/lib/angular.js:5888:17

**Comment by matsko** [comment] 2015-08-27 06:05
@mdudek there's a fix for this pending: https://github.com/angular/angular.js/pull/12651

**Comment by mdudek** [comment] 2015-08-27 10:51
Following exception still happen time to time in v1.4.5-local+sha.0e00108:

Cannot set property 'WebkitTransitionDelay' of undefined
    at applyInlineStyle (file:///android_asset/www/js/lib/angular-animate.js:364:26)
    at blockTransitions (file:///android_asset/www/js/lib/angular-animate.js:350:9)
    at Array.close [as 1] (file:///android_asset/www/js/lib/angular-animate.js:1121:29)
    at onAnimationExpired (file:///android_asset/www/js/lib/angular-animate.js:1328:58)
    at file:///android_asset/www/js/lib/angular.js:18215:49
    at completeOutstandingRequest (file:///android_asset/www/js/lib/angular.js:5615:20)
    at file:///android_asset/www/js/lib/angular.js:5888:17

**Comment by matsko** [comment] 2015-08-27 21:30
@mdudek this is now in master: https://github.com/angular/angular.js/commit/2f6b6fb7a1dee0ff97c5d2959b927347eeda6e8b

Please test this out in about 30 min:
https://code.angularjs.org/snapshot/angular-animate.js

Is this current issue still a problem now that that's fixed?

**Comment by mdudek** [comment] 2015-08-28 09:12
@matsko It's not fixed yet!  Following exception is thrown very often (on Android 4.1.2) in v1.4.5-build.4192+sha.ea8016c:

Cannot set property 'WebkitTransitionDelay' of undefined
Stack:TypeError: Cannot set property 'WebkitTransitionDelay' of undefined
    at applyInlineStyle (file:///android_asset/www/js/lib/angular-animate.js:367:20)
    at blockTransitions (file:///android_asset/www/js/lib/angular-animate.js:353:3)
    at init (file:///android_asset/www/js/lib/angular-animate.js:1001:9)
    at prepareRegularAnimation (file:///android_asset/www/js/lib/angular-animate.js:1624:22)
    at initDriverFn (file:///android_asset/www/js/lib/angular-animate.js:1404:13)
    at invokeFirstDriver (file:///android_asset/www/js/lib/angular-animate.js:3049:24)
    at Array.triggerAnimationStart [as 0] (file:///android_asset/www/js/lib/angular-animate.js:2895:33)
    at nextTick (file:///android_asset/www/js/lib/angular-animate.js:420:15)
    at scheduler (file:///android_asset/www/js/lib/angular-animate.js:390:5)
    at file:///android_asset/www/js/lib/angular-animate.js:2917:9
    at Scope.$digest (file:///android_asset/www/js/lib/angular.js:16207:56)

**Comment by matsko** [comment] 2015-08-28 15:46
OK I'll debug and get to this before 1.4.5 is out.

**Comment by matsko** [comment] 2015-08-28 18:24
So I'm able to run android tests, but I can't run the code that you have. Is there anyway you can upload something into a code example?

**Comment by matsko** [comment] 2015-08-28 19:01
@mdudek unfortunately we need to delay this to 1.4.6. Let's pair on this next week.

**Comment by mdudek** [comment] 2015-08-31 14:22
Can't give you code, the app is too complex, but I partially dumped node variable when node.style is null in applyInlineStyle:

```
{"isContentEditable":false,"previousElementSibling":null,"$$hashKey":"object:18","offsetTop":0,"dataset":{"ngAnimate":"2"},"itemRef":{"length":0,"value":""},"o
ffsetHeight":533,"align":"","style":{"length":0,"parentRule":null,"cssText":""},"offsetLeft":0,"id":"","contentEditable":"inherit","lastElementChild":{"isContentEditable":false,"$$hashKey":"object:17"
,"previousElementSibling":null,"offsetTop":0,"$$ngAnimateParentKey":2,"dataset":{},"itemRef":{"length":0,"value":""},"offsetHeight":533,"align":"","style":{"length":0,"parentRule":null,"cssText":""},"
offsetLeft":0,"id":"","contentEditable":"inherit","lastElementChild":{"$$hashKey":"object:30","isContentEditable":false,"previousElementSibling":{"isContentEditable":false,"previousElementSibling":{"$
$hashKey":"object:19","isContentEditable":false,"previousElementSibling":{"isContentEditable":false,"previousElementSibling":null,"offsetTop":0,"dataset":{},"itemRef":{"length":0,"value":""},"offsetHe
ight":0,"align":"","style":{"length":0,"parentRule":null,"cssText":""},"offsetLeft":0,"id":"","contentEditable":"inherit","lastElementChild":{"dataset":{},"previousElementSibling":null,"itemRef":{"len
gth":0,"value":""},"style":{"length":0,"parentRule":null,"cssText":""},"offsetHeight":0,"offsetLeft":0,"id":"","itemProp":{"length":0,"value":""},"contentEditable":"inherit","className":"backButtonBar
 fixed","firstElementChild":{"isContentEditable":false,"previousElementSibling":null,"offsetTop":0,"dataset":{"i18n":"_Back_"},"itemRef":{"length":0,"value":""},"offsetHeight":0,"style":{"length":0,"p
arentRule":null,"cssText":""},"offsetLeft":0,"id":"","contentEditable":"inherit","lastElementChild":null,"itemProp":{"length":0,"value":""},"form":null,"autofocus":false,"validity":{"valueMissing":fal
se,"valid":true,"rangeOverflow":false,"tooLong":false,"rangeUnderflow":false,"customError":false,"typeMismatch":false,"stepMismatch":false,"patternMismatch":false},"className":"animate backButton","fi
rstElementChild":null,"properties":{"names":{"length":0},"length":0},"baseURI":"file:///messageDetail","itemValue":null,"formNoValidate":false,"disabled":false,"draggable":false,"nextSibling":null,"na
mespaceURI":"http://www.w3.org/1999/xhtml","nodeName":"BUTTON","outerHTML":"<button class=\"animate backButton\" data-i18n=\"_Back_\" ng-click=\"xinAppNavigator.navigateBack()\">Back</button>","hidden
":false,"firstChild":{"nextSibling":null,"namespaceURI":null,"length":4,"nodeName":"#text","nodeValue":"Back","attributes":null,"previousSibling":null,"nodeType":3,"lastChild":null,"data":"Back","owne
rDocument":{"alinkColor":"","webkitVisibilityState":"visible","$$hashKey":"object:12","all":{"0":{"isContentEditable":false,"previousElementSibling":null,"$$hashKey":"object:5","offsetTop":0,"dataset"
:{},"itemRef":{"length":0,"value":""},"offsetHeight":533,"style":{"length":0,"parentRule":null,"cssText":""},"offsetLeft":0,"id":"","contentEditable":"inherit","lastElementChild":{"isContentEditable":
false,"$$hashKey":"object:4","previousElementSibling":{"dataset":{},"previousElementSibling":null,"itemRef":{"length":0,"value":""},"style":{"length":0,"parentRule":null,"cssText":""},"profile":"","of
fsetLeft":0,"id":"","itemProp":{"length":0,"value":""},"contentEditable":"inherit","className":"","firstElementChild":{"offsetTop":0,"previousElementSibling":null,"dataset":{},"style":{"length":0,"par
entRule":null,"cssText":""},"itemRef":{"length":0,"value":""},"offsetLeft":0,"id":"","itemProp":{"length":0,"value":""},"contentEditable":"inherit","className":"","firstElementChild":null,"properties"
:{"names":{"length":0},"length":0},"baseURI":"file:///messageDetail","itemValue":null,"disabled":false,"draggable":false,"nextSibling":{"nextSibling":{"dataset":{},"itemRef":{"length":0,"value":""},"o
ffsetLeft":0,"offsetHeight":0,"id":"","contentEditable":"inherit","className":"","lastElementChild":null,"firstElementChild":null,"properties":{"names":{"length":0},"length":0},"baseURI":"file:///mess
ageDetail","itemValue":null,"scheme":"","draggable":false}
```
as I wrote, the bug happen time to time in Android 4.1.2 webview.

Let me know if I could help you more with it...

**Comment by Narretz** [comment] 2017-04-26 13:17
I'm going to close this issue because we have no reproduction of the issue. Feel free to reopen this issue if you can provide a reproduction (ideally a runnable demo in a [Plunker](https://plnkr.co) or similar. You can use this [Plunker Template](http://plnkr.co/edit/tpl:yBpEi4)).

**Closed by Narretz** 2017-04-26 13:17 UTC
Labels: branch: 1.4.x, branch: 1.5.x, branch: 1.6.x, component: ngAnimate
