### ISSUE TITLE
model isnt't updated upon ESC in IE

### ISSUE THREAD

**Issue by kamilkp** [angular/angular.js#7297] opened 2014-04-29 06:33 UTC
This happens in Internet Explorer 11. Hitting ESC in an `input` element clears it but the model isn't updated.

Fiddle: http://jsfiddle.net/e8TDg/
type something in the `input` and then hit ESC button on keyboard. The `input` clears, but the model value remains.

**Comment by Splaktar** [comment] 2018-08-29 23:37
I'm not sure if this was fixed by Microsoft as they are no longer updating IE11. They also shut down Microsoft Connect, so the bug link above no longer works.

It also looks like JSFiddle no longer supports IE11 (it's just a bouncing cloud forever).

But I created a [CodePen](https://s.codepen.io/Splaktar/debug/EeNVNj) for this and testing in IE11 seems to demonstrate that the model is now updated when the `ESCAPE` key clears the input. Verified this with AngularJS 1.7.2.

CC @gkalpak

**Comment by petebacondarwin** [comment] 2018-08-30 08:37
Thanks @Splaktar - I can't confirm locally but @Narretz  or @gkalpak  probably could and then we can close this issue.

**Comment by Narretz** [comment] 2018-09-01 14:15
Confirmed that this works in AngularJS 1.7.2. Thanks @Splaktar !

**Closed by Narretz** 2018-09-01 14:15 UTC
Labels: browser: IE11, component: forms, frequency: moderate, severity: inconvenient, type: bug
