### ISSUE TITLE
ng-if as base element of replaced directive destroys isolate scope.

### ISSUE THREAD

**Issue by nosideeffects** [angular/angular.js#12936] opened 2015-09-24 16:03 UTC
Example: https://jsfiddle.net/01mfdjwm/1/

**Comment by mzdunek93** [comment] 2015-09-29 19:24
You could use `{{$parent.dir.hello}}`, but this clearly seems to be a bug, since the same issue doesn't exist when using `templateUrl`. Turns out that the directives at the root of a replaced directive get moved "next to" the containing directive, so the scope for the transclusion is set to be outside the directive. I submitted a fix to change the scope's prototype in such case:  #12975

**Comment by nosideeffects** [comment] 2015-09-29 20:07
Super strange that it works with `templateUrl`. Thanks for submitting a fix!

**Comment by mzdunek93** [comment] 2015-09-29 20:13
My pleasure. Just to be clear, it's not in yet, we'll have to wait for somebody from the core team to approve it.

**Comment by petebacondarwin** [comment] 2015-10-05 13:41
Duplicate of #9837 ?

**Closed** 2015-11-10 20:48 UTC
Labels: component: $compile, type: bug
