### ISSUE TITLE
Missing required controller error when using template instead of templateUrl

### ISSUE THREAD

**Issue by kycook** [angular/angular.js#10771] opened 2015-01-16 03:12 UTC
See http://jsfiddle.net/m6v6tf7s/4/.

The snippet currently throws an error: "Controller 'ngModel', required by directive 'myInnerDirective', can't be found!" If you make either one of these changes, it no longer throws an error:
1) Remove the template property and uncomment the templateUrl property.
2) Remove the link property.

I would expect the error to never occur. Ideally, it would always behave like this snippet: http://jsfiddle.net/m6v6tf7s/5/

**Comment by joelross** [comment] 2015-01-16 09:56
I think this is an expected behavior. When you do `var directive = $compile(html)(scope);`, your inner directive is not yet part of the DOM tree, and thus can not find the ngModelController of its parents (because it does not have a parent yet).
If you inverse the insertion in the DOM and the compilation, [it works as expected](http://jsfiddle.net/qz8ykf1y/).

**Comment by kycook** [comment] 2015-01-16 14:17
Thanks, Joël. That makes sense. So I guess the real issue here is it's not failing consistently as it should.

**Comment by pkozlowski-opensource** [comment] 2015-01-17 10:42
@kycook it is not "failing consistently" as there is a timing difference here - that is - access to a template expressed in the `template` attribute is synchronous while to the one expressed as `templateUrl` is asynchronous.

@joelross response proves this point by saying (btw, great analysis @joelross !):
 > If you inverse the insertion in the DOM and the compilation, it works as expected.

I'm not sure we can do much about this issue as the current behaviour is consistent with what is actually happening - I'm afraid that one needs to be aware of the directives lifecycle to correctly navigate those quirks....

I'm going to close this issue for now but if anyone has an idea of improvements (either code and / or docs) PRs are more then welcomed!

**Closed by pkozlowski-opensource** 2015-01-17 10:42 UTC
