### ISSUE TITLE
charset=utf-8 to uppercase

### ISSUE THREAD

**Issue by vnn456** [angular/angular.js#11558] opened 2015-04-13 14:41 UTC
Chrome automatically sends(PUT/POST) the charset in uppercase UTF-8. Firefox and IE don't. 

Thanks

**Comment by pkozlowski-opensource** [comment] 2015-04-13 15:36
This sounds like a statement not a bug report... Are you suggesting that AngularJS has something to do with it? If so, please provide a minimal reproduce scenario as requested here: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#submitting-an-issue

**Comment by vnn456** [comment] 2015-04-13 19:07
**AngularJS Version: 1.3.15**

Please see the line below from source:
```var CONTENT_TYPE_APPLICATION_JSON = {'Content-Type': APPLICATION_JSON + ';charset=utf-8'};```

I have read in many forums that uppercase 'UTF-8' is the de facto standard. 

For now, I modified ```ng``` code to uppercase in my application. Thought it would be nice if you make changes on your end as well.

Because of lower case, my Struts2-REST plugin based application that was using  was not populating the model. So, PUT/POST methods didn't seem to work. I will be submitting a patch to Apache Struts to ignore case.

Thanks.

**Comment by pkozlowski-opensource** [comment] 2015-04-15 19:50
Well, looking through various discussions it seems like charset casing shouldn't matter: http://stackoverflow.com/questions/19391221/http-are-character-set-names-case-sensitive

Do you have a pointer to other docs / spec that would state otherwise? What do you mean by:
> I have read in many forums that uppercase 'UTF-8' is the de facto standard.

Could you provide the source (ideally a spec?)

I'm going to close this one since from my quick reading it seems that charset should not be case-sensitive and default headers are configurable, which means that you can change `$http` configuration to suit your particular backend needs.

Happy to re-open / re-consider if you can point me to specs that state otherwise, though.

**Closed by pkozlowski-opensource** 2015-04-15 19:50 UTC
Labels: needs: more info
