### ISSUE TITLE
linky filter does not handle certain punctuation well

### ISSUE THREAD

**Issue by ppham27** [angular/angular.js#15907] opened 2017-04-12 04:54 UTC
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

Links like `(www.example.com):` include `):` as part of the link when it is punctuation.

**Expected / new behavior:**

`):` should not be part of the link.

**Minimal reproduction of the problem with instructions:**

Type `(www.example.com):`  in the example https://docs.angularjs.org/api/ngSanitize/filter/linky

**Angular version:** 1.6.4

**Browser:** [all]

**Anything else:**

**Comment by gkalpak** [comment] 2017-04-12 09:58
Closing as duplicate of #7213.

**Closed by gkalpak** 2017-04-12 09:58 UTC

**Comment by gkalpak** [comment] 2017-04-12 10:52
I just realized this something different than #7213. Yet, the main problem is discussed in #7213, which is that `linky` filter currently disallows certain characters that is should allow (per the spec), but aligning it with the spec would break people's expectations wrt to links in plain text.

There is also #13699, which discusses a more general problem, which is that the RegExp used in `linky` is pretty broken anyway :grin:

I'll keep this closed. Let's move the discussion on #7213 and/or #13699.
