### ISSUE TITLE
feature($http): parameter to avoid triggering $apply

### ISSUE THREAD

**Issue by dragosrususv** [angular/angular.js#14191] opened 2016-03-07 12:59 UTC
**PROBLEM**: Complex pooling fed screens become unresponsive when they have 4-5 poolers at 2-3 seconds each.

**SOLUTION**: allow the developer to trigger $apply via $timeout(f(), 0) and allow him to opt out of the $digest cycle on each $http request

**PROPOSAL**:
$http({...., apply: false})   // by default the $apply will be triggered; if false, it will not be triggered

I can make a PR - just wanted to get in sync with the community, if they reached this problem.
Please mind that I'm forced to consider ReactJS like frameworks due to this limitation.

**Comment by lgalfaso** [comment] 2016-03-07 13:13
There are a few hurdles as `$http` uses `$q` extensively, but if the issues can be solved and the implementation is good, I see no problems.

BTW, do you know that there is `$httpProvider#useApplyAsync` that can partially solve this?

**Comment by Narretz** [comment] 2016-03-07 15:53
Duplicate of https://github.com/angular/angular.js/issues/2049

I'd be happy to include this in a future release.

Here's a PR that attempted to do this: 
https://github.com/angular/angular.js/pull/12557

There's also this, which should be considered when implementing this: https://github.com/angular/angular.js/issues/13108

**Closed by Narretz** 2016-03-07 15:53 UTC

**Comment by dragosrususv** [comment] 2016-03-07 19:17
@Narretz thank you kindly - tried to search before but haven't found the other ticket. I'm glad that this is not new to our community and people are interested in scaling large angularjs apps.
