### ISSUE TITLE
ngMockE2E $httpBackend "passThrough()" doesn't work

### ISSUE THREAD

**Issue by ghost** [angular/angular.js#1434] opened 2012-10-02 21:19 UTC
Hi, I'm trying to set up some test that actually do hit the backend, but I can't get this to work:

$httpBackend.whenPOST(/.\*/).passThrough()
$httpBackend.whenGET(/.\*/).passThrough()

But I get the error: "POST /some/url No more request expected"

I am still able to use .whenGET().respond(), and it's variants, to mock the requests. Am I doing something wrong with passThrough()?

**Comment by Deminetix** [comment] 2015-04-17 05:44
Any update on this? I've been using the workaround @IxDay mentioned for months, but its not ideal.

**Comment by builtbylane** [comment] 2015-05-07 15:58
+1

**Comment by vietnogi** [comment] 2015-05-11 16:44
+1 I have my own mocking solution using sinon.js and want all requests to pass through

**Comment by zuzusik** [comment] 2015-05-22 20:11
Also ran into this issue. We have special module that gives us the ability to configure fake backend. It depends on `ngMockE2E`. I need to unit test this module.

**Comment by zivc** [comment] 2015-05-27 15:41
BUMP!

**Comment by mgerring** [comment] 2015-06-08 20:45
Yeah, this is absurd, I'd like to be able to write e2e tests without having to rely on a real API

**Comment by bbraithwaite** [comment] 2015-06-16 00:00
If it's of help to anyone, here is a solution that I use to make real HTTP calls when I'm using ngMock for unit tests. I mainly use it for debugging, working through the test, getting JSON examples etc.

I wrote up the solution over at my blog: http://www.bradoncode.com/blog/2015/06/16/unit-test-http-ngmock-passthrough/

**Comment by ivankolev** [comment] 2015-06-24 05:43
Same problem here. I would love to have the flexibility to switch between fake and real http calls.

**Comment by Galaf** [comment] 2015-08-26 09:09
Same!
Actually wrote a message on Karma's bugtracker (https://github.com/karma-runner/karma/issues/1567) but doing it here seems more appropriate.

Can we have an update on this?

**Comment by jmuharsky** [comment] 2015-08-28 17:06
+1

**Comment by urecio** [comment] 2015-09-03 09:21
+1

**Comment by dsge** [comment] 2015-09-28 10:53
+1

**Comment by ArdentKid** [comment] 2015-10-08 18:00
+1

**Comment by mathilde-pellerin** [comment] 2015-10-09 13:51
subscribing

**Comment by ethanmick** [comment] 2015-10-13 01:05
+1

**Comment by flirtomania** [comment] 2015-10-18 23:58
+1

**Comment by Kira2** [comment] 2015-10-28 15:14
+1
Used @bbraithwaite's solution (thank you) with the fix for Angular v1.4.3.

**Comment by hypery2k** [comment] 2015-10-29 20:44
+1

**Comment by mmmichl** [comment] 2015-11-04 12:08
+1

**Comment by fabiooshiro** [comment] 2015-11-06 23:47
+1

**Comment by panmanphil** [comment] 2015-11-14 14:01
Adding to the chorus, +1. Here is the scenario. We have an isolated unit suite using Karma, jasmine and bard. Everything is mocked, that's fine. We'd also like an integration suite that does full or partial end to end tests, still using karma and jasmine, but not bard. It will make some http calls, say to our own api, but mock other calls, say to amazon s3 put urls or to api's that require too much setup to execute. Finally I'll have a non destructive smoke test using protractor. 

This should be possible, and thanks to all who have worked some magic for workarounds.

**Comment by damiendube** [comment] 2015-11-26 21:55
+1

**Comment by EdoB** [comment] 2015-12-07 18:55
+1

**Comment by melbourne2991** [comment] 2015-12-21 02:15
@kharnt0x I tried this implementation and it does hit the server and call the success callback, but then the response is undefined. Is this a side effect of the hack or something else?

Cheers

**Comment by Lunanne** [comment] 2015-12-23 13:07
+1 Trying to unit test a directive with templateUrl and running into this issue.

**Comment by mali-eg** [comment] 2016-01-01 20:15
+1

**Comment by TraianAlex** [comment] 2016-01-14 02:57
Error: [$injector:modulerr] Failed to instantiate module demoApp due to:
[$injector:modulerr] Failed to instantiate module ngMockE2E due to:
[$injector:nomod] Module 'ngMockE2E' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.8/$injector/nomod?p0=ngMockE2E
minErr/<@https://code.angularjs.org/1.4.8/angular.js:68:12
etc

**Comment by bartvanderwal** [comment] 2016-01-16 20:54
On a positive one comment in case this helps others.

I was trying to mock the backend while testing the frontend logic in the browser (no unit test). I had some issues and reading this issue it seemed to confirm to me Angular's ngMockE2E did not support this scenario yet. However, upon double checking for me using a wildcard `/.*/` regexp at the end of the mockrun this IS working (I'm using Angular 1.3):
    `$httpBackend.whenGET("api/test").respond(function(method, url, data) {
     ...
     });
    `$httpBackend.whenGET(/.*/).passThrough();`

So for the `api/test` url my mock is used and the rest is passed to the server.

**Comment by igordeoliveirasa** [comment] 2016-01-18 00:45
+1

**Comment by atefth** [comment] 2016-02-11 09:26
Any solutions to this?

**Comment by schmod** [comment] 2016-02-11 21:26
I've had a PR open for several months now.  No clue what I need to do to get it reviewed or merged, but... it's there.

**Comment by gkalpak** [comment] 2016-02-11 22:14
I guess there is no strong argument for the necessity to have both `ngMock` and `ngMockE2E` loaded together, yet. It doesn't seem like a good practice to mix unit and e2e test functionalities together.

I still think that unit tests should not interact with the server at all, but if enough people find this useful, I think the best way would be to leave `ngMockE2E` out of this and enable passing requests through in `ngMock`. It needs to be well thought through, though, and might not be trivial to get right.

<sub>Just my 2 cents...</sub>

**Comment by schmod** [comment] 2016-02-11 22:41
The problem is that angular-mocks loads `ngMock` for you, regardless of whether you want it or not.  I suspect that very few people are *deliberately* loading both, but any usage of `angular.mock.inject` automatically adds `ngMock` to the injected module, even if you've already loaded `ngMockE2E`.  

It's not hard to understand why somebody might want to write an integration test with Jasmine. 

In my case, I want to test some functionality that loads and processes some very large files (which are sometimes binaries).  I'd rather not have to mock these files by inlining them into my tests -- it's far cleaner to simply make a "real" HTTP request to fetch them when they're needed.

**Comment by mmmichl** [comment] 2016-02-12 13:25
I love to make service tests to assure the back-end services still behave as I expect. Too often the back-end guys changes something without telling me, which resulted in a tester standing next to me :)

@gkalpak: Including the pass through functionality directly in `ngMock` out of the box sounds like the finest solution. But I would already be happy not to need a crazy hack to make this work.

**Comment by gkalpak** [comment] 2016-02-13 21:42
@schmod, if you have already loaded `ngMockE2E` you should not be runnign unit test. In which case, you should not call `angular.mock.inject()`. What do I miss ?

**Comment by alvarocantador** [comment] 2016-04-21 21:45
+ 1

**Comment by teyc** [comment] 2016-04-29 21:13
Here's a working example of using ngMockE2E with $httpBackEnd

```
require('./test-helper.js');

// our system under test
// which is a wrapper around 
// Yahoo's weather service
//
function sunriseService($http, $log) {
  this.query = function(location) {

    var yql = 
      'select * from weather.forecast    \n\
       where woeid in (                  \n\
         select woeid from geo.places(1) \n\
         where text="' +                 
         location.replace("'", "''") + '")';

     var url = 'https://query.yahooapis.com/v1/public/yql' +
        '?q=' + yql.replace('    ', '') + 
        '&format=json' + 
        '&env=store://datatables.org/alltableswithkeys';

    $log.debug(url);

    return $http.get(url)
        .then(function(result) {
            return result.data.query.results.channel.item.condition;
        });
  }
}

angular.module('app', [])
  .service('sunriseService', function($http, $log) {
      return new sunriseService($http, $log);
   });

//
// test suite
//

// define a new module that takes a dependency on
// our module and the ngMockE2E module
//
//
// !! do not include 'ngMock' in the list
//    as it'll load ngMock and override 
//    $httpBackend
//
angular.module('appDev', ['app', 'ngMockE2E']);

describe('ngMockE2E', function() {

  beforeEach(function () {
    //
    // !! do not use ngMock's module function
    //    as it'll load ngMock and override 
    //    $httpBackend
    //
    angular.module('appDev')
        .run(function ($httpBackend) {
            $httpBackend.whenGET(/.*/).passThrough();
        });
    });

  it('uses $httpBackend passthrough', function (done) {

    //
    // !! do not use ngMock's inject function
    //    as it'll load ngMock and override 
    //    $httpBackend
    //
    $injector = angular.injector(['appDev']);
    $injector.invoke(function(sunriseService, $rootScope) {

      sunriseService.query('brisbane, australia')
        .then(function (forecast) {
            console.log(forecast);
            expect(Object.keys(forecast)).toContain('text');
            done();
        })
        .catch(function (error) {
            done.fail(JSON.stringify(error));
        });
        $rootScope.$digest();
    });
  });
});

```

**Closed** 2016-06-06 10:15 UTC
Labels: component: scenario runner, frequency: high, Lots of comments, severity: confusing, type: bug
