### ISSUE TITLE
Could $resource delete send a data in body be possible?

### ISSUE THREAD

**Issue by ChrisFuck** [angular/angular.js#15174] opened 2016-09-22 05:36 UTC
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
$resource delete doesn't support to send a body

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

**What is the expected behavior?**
Is it possible to config the $httpProvider.defaults.headers.delete to make it possible to send a request with a body?

If it is possible,and how?

thanks

**What is the motivation / use case for changing the behavior?**
Because many backend guys don't follow the RESTfull standard,and they want to change their API design.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by gkalpak** [comment] 2016-09-22 08:19
It is currently not possible. Closing as duplicate of #8567.

**Closed by gkalpak** 2016-09-22 08:19 UTC

**Comment by gkalpak** [comment] 2016-09-22 08:26
This has also been discussed in #3207. There are more details on what is/isn't possible there (e.g. starting at https://github.com/angular/angular.js/issues/3207#issuecomment-148684507).

**Comment by ChrisFuck** [comment] 2016-09-23 07:50
@gkalpak thanks
another question 
this is a service
![test](https://cloud.githubusercontent.com/assets/10722776/18778039/f6375cc6-81a4-11e6-99ed-535c5169d07b.jpeg)
this is a middleware
![test-1](https://cloud.githubusercontent.com/assets/10722776/18778066/14a1ddd0-81a5-11e6-8625-8e900a82b3c8.jpeg)

if I call the tagHandler.saveDeviceMapByTag function ,the request url will be like be this
https://localhost:8080/api/v1/tag/device/map?tag_id=4,
and the request body is {tag_id: 4, group_id: 1}
I dont want the params add to url, I want to send a request url like https://localhost:8080/api/v1/tag/device/map

How could I do?

**Comment by gkalpak** [comment] 2016-09-25 17:03
@ChrisFuck, you specify the default params as `{tad_id: '@tag_id'}`. This means that there will be a param named `tag_id` whose value will be the value of the instance's `tag_id` property (here `4`). Since there is no param named `tag_id` in the URL, as happens with the extra params, it will be appended as a query param.

I am not sure what you are trying to achieve with `{tag_id: '@tag_id'}`, so I can't suggest a solution.
