### ISSUE TITLE
$location.url() Is decoding the url. 

### ISSUE THREAD

**Issue by gladsonqb** [angular/angular.js#14269] opened 2016-03-18 11:38 UTC
I have a encoded url such as  var slug =  'test-test/7%2F8-test';
am using $location.url(slug) to redirect but unfortunately it gets decoded while it comes to the browser. 

My need is the same encoded url should seen in the browser. 

Current behavior in the browser is : www.test.com/test-test/7/8-test
Expected behavior or my requirement is : www.test.com/test-test/7%2F8-test

But when I use path its get encoded again.

Any help please. 

I guess $location.ur() is decoding it by default. so any help on how to extend the $location of angularjs https://github.com/angular/angular.js/blob/master/src/ng/location.js#L388

**Comment by gkalpak** [comment] 2016-03-21 09:21
@gladsonqb , could you create a live reproduction (e.g. using CodePen, plnkr etc) ?
How are you trying to use it ?

BTW, if `$location.url()` expects an encoded URL, have you tried encoding it before passing it to `$location.url()` ?

**Comment by Narretz** [comment] 2016-04-06 15:48
I'm going to close this issue because we have no reproduction of the issue. Feel free to reopen this issue if you can provide a reproduction (ideally a runnable demo in a https://plnkr.co or similar).

**Closed by Narretz** 2016-04-06 15:48 UTC
Labels: component: $location, frequency: low, needs: investigation, needs: more info
