### ISSUE TITLE
How to edit/delete all text on an "required" field with ng-model-options="{ getterSetter: true }"  in AngularJS

### ISSUE THREAD

**Issue by smsahu** [angular/angular.js#11633] opened 2015-04-17 12:03 UTC
Hi,
I am observing inconsistent behavior while editing field with ng-model-option and required validation.

1. If field is not maked as required, on deleting last character, my model is getting called with "" (empty string).
2. If field is marked as required, on deleting last character, my model is getting called with undefined.

As per my below code the deleted/undefined value is not being set to my scope.
 $scope.name= function(name){
         console.log(name);
        if (angular.isDefined(name)) {
          name1 = name;
        }
        return name1;
      }

Please let me know how to proceed.

StackOverflow: http://stackoverflow.com/questions/29682922/how-to-edit-delete-all-text-on-an-required-field-in-angularjs/29693570#29693570
Plunkr: http://plnkr.co/edit/8QcUsX?p=preview

**Comment by gkalpak** [comment] 2015-04-17 12:59
Actually, this is the expected behaviour (considering how `ngModel`, `required` and `getterSetter` work).
The issue arises because of the implementation of the getter/setter function.

This is explained in more detail in #11361 (and especially https://github.com/angular/angular.js/issues/11361#issuecomment-84022489) along with a proposed solution.

--
I assume this is a result of copying/pasting the example in the docs, where the input is not validated (and therefore there is no need to account for passing `undefined` as a value).
A docs update that addresses this possible misconception has been already submitted (#11604).

**Comment by pkozlowski-opensource** [comment] 2015-04-21 12:23
@gkalpak this is marked as "works as expected". Shell we close it then?

**Comment by gkalpak** [comment] 2015-04-21 15:21
I left it open in case OP had a comment or something. I was planning to close it after a week or so.
Since there is no response (neither here nor on SO), I think we can safely close it.

**Comment by pkozlowski-opensource** [comment] 2015-04-21 15:22
@gkalpak cool. Usually I'm moving such issues to the Purgatory milestone and re-visiting it every week or so.

**Closed by gkalpak** 2015-04-21 15:21 UTC
Labels: component: misc core, resolution: works as expected

**Comment by gkalpak** [comment] 2015-04-21 15:32
@pkozlowski-opensource: Noted :wink: Thx
