### ISSUE TITLE
$touched returns true for disabled fields

### ISSUE THREAD

**Issue by rayon1990** [angular/angular.js#12454] opened 2015-07-28 14:11 UTC
**$touched** method of ng-messages for form field returns true even if form field is disabled..

**Comment by matthewjh** [comment] 2015-07-28 18:37
Isn't this desirable behaviour? Many valid forms would not validate if a disabled field is pristine by default and there's no way to touch it, e.g. if you're disabling a 'save' button when the form is pristine.

**Comment by rayon1990** [comment] 2015-07-29 06:05
What if input field is diabled and user clicks on it, validation message will be shown as validation condition sayd this field is required..

**Comment by Narretz** [comment] 2015-08-03 16:49
Can you please show an example of this? You mean, if a user blurs a disabled field, $touched is set to true?

**Comment by rayon1990** [comment] 2015-08-04 01:40
Actually I am playing with angular material chips and this field is
dependent upon selection of some other field, so I have diabled this chips
field untill the related value is selected. In this case if the chips field
is in diabled state and user clicks on this disabled field, ng-messaged
"required" message is being shown.

I hope you got my point..

*Rayon Dabre.*
Email: *rayzel.dabre@gmail.com <rayzel.dabre@gmail.com>*
Cell: +919823608959

**Comment by Narretz** [comment] 2015-08-05 13:55
@rayon1990 I don't really understand how this can happen. `$touched` is set on the control after it has been blurred, not when it is in focus. Can you please provide a small demo of this problem?

**Comment by Narretz** [comment] 2015-08-13 18:24
@rayon1990 I'm gonna close this issue, since we don't have a reproduce scenario. Please reopen when you can provide a demo of the problem.

**Closed by Narretz** 2015-08-13 18:24 UTC
Labels: component: forms, needs: more info
