### ISSUE TITLE
Error with multiple ng-repeat-start in v1.5.0 and Chrome browser

### ISSUE THREAD

**Issue by 4kochi** [angular/angular.js#14267] opened 2016-03-18 09:29 UTC
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I have two `ng-repeat-start` and one `ng-repeat`. They should render a table. Sometimes it works but in some cases i get an angular error

```
VM2058 angular.js:13236 Error: [$compile:uterdir] Unterminated attribute, found 'ng-repeat-start' but no matching 'ng-repeat-end' found.
http://errors.angularjs.org/1.5.0/$compile/uterdir?p0=ng-repeat-start&p1=ng-repeat-end
    at VM2058 angular.js:68
    at groupScan (VM2058 angular.js:8387)
    at applyDirectivesToNode (VM2058 angular.js:8507)
    at compileNodes (VM2058 angular.js:8149)
    at compile (VM2058 angular.js:8048)
    at VM2058 angular.js:8440
    at boundTranscludeFn (VM2058 angular.js:8244)
    at controllersBoundTransclude (VM2058 angular.js:9020)
    at ngRepeatAction (VM2058 angular.js:28571)
    at $watchCollectionAction (VM2058 angular.js:16529)(anonymous function) @ VM2058 angular.js:13236(anonymous function) @ VM2058 angular.js:9965Scope.$digest @ VM2058 angular.js:16682Scope.$apply @ VM2058 angular.js:16928(anonymous function) @ VM2058 angular.js:18753completeOutstandingRequest @ VM2058 angular.js:5804(anonymous function) @ VM2058 angular.js:6081
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

Here is the plunker: http://plnkr.co/edit/2iX4RvGF5526NbVy72PJ?p=preview

As the problem occurs randomly the best way to reproduce it is to change the variable `i` in the `app.js` in plunker.

**What is the expected behavior?**
The table should be rendered without problems.

**What is the motivation / use case for changing the behavior?**

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

The issue only occurs in Angular >= 1.5.0 and Google Chrome (Version 49.0.2623.87 (64-bit)). Angular < 1.5.0 works fine in all browsers. And other browser have also no problem with Angular 1.5.0. Also Chrome Canary (Version 51.0.2682.0 canary (64-bit)) works fine.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by Narretz** [comment] 2016-03-18 10:23
Looks like a dupe of https://github.com/angular/angular.js/issues/14041

**Closed by Narretz** 2016-03-18 10:23 UTC
