### ISSUE TITLE
Angular $log console bug

### ISSUE THREAD

**Issue by ramtob** [angular/angular.js#14224] opened 2016-03-12 19:58 UTC
* **Do you want to request a *feature* or report a *bug*?**

Report a bug

* **What is the current behavior?**

When you print to the console using $log (unlike console.log), the console does not show the correct line from which the print was issued. Instead, it shows a line inside the angular.js file.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Just use $log and watch the console. Use console.log(), and see the difference.

See http://embed.plnkr.co/Gfw1rywiT8aWn71C9ouS/

* **What is the expected behavior?**

See the console in the case of console.log(), in the demo.

* **What is the motivation / use case for changing the behavior?**

The ability to go, from a console printout, to the source line from which the print was issued.

* **Which version of Angular, and which browser and OS does this issue affect?** Did this work in previous
versions of Angular?

I checked it in versions 1.4.9 and 1.5.0.
I don't know whether it worked correctly in any previous version.

**Comment by mgol** [comment] 2016-03-13 17:45
I don't think it's possible to fix this issue on the Angular side. Chrome just always shows the line in which the `console.log` happens so if you use any wrapper you'll experience the same issue.

**Comment by nhducit** [comment] 2016-03-19 07:07
@ramtob I suffer this pain too. in development mode, I use $log.error instead of $log.info/$log.warn.
The second way is you can change the current behavior of $log.info/$log.warn by using $provide
http://stackoverflow.com/questions/20738707/angularjs-log-show-line-number

**Comment by ramtob** [comment] 2016-03-20 18:53
@nhducit, thanks for the info! As your link indicates, there is also the option of blackboxing angular, at least in Chrome.

**Comment by wesleycho** [comment] 2016-06-01 15:49
This is a duplicate of #11660

**Comment by mgol** [comment] 2016-06-01 16:05
@wesleycho True that! Closing then.

**Closed by mgol** 2016-06-01 16:05 UTC
Labels: component: misc core, frequency: moderate, severity: confusing
