### ISSUE TITLE
Reference to .info() is breaking change in patch version of angular-aria, etc.

### ISSUE THREAD

**Issue by DrShaffopolis** [angular/angular.js#15814] opened 2017-03-14 19:40 UTC
In reference to this change: https://github.com/angular/angular.js/commit/60e294cbd8f0c34ed03046778a0be3befc6b6982

The .info function doesn't seem to exist before angular version 1.6.3, so upgrading any of these modules without a full angular upgrade will break them.

Sorry for not having a real PR; I wasn't sure the best approach for solving ... Suggestions:
- Make this a minor version, not a patch version
- Add angular 1.6.3 as a dependency
- The ever-hacky ` if (module.info) { }`

**Comment by dudewheresmycode** [comment] 2017-03-14 20:33
+1 👍

**Comment by gkalpak** [comment] 2017-03-14 21:40
Duplicate of #15788, #15789, #15791.

**tl;dr**
This works as expected. Using non-matching versions of angular and angular modules is not supported.

**Closed by gkalpak** 2017-03-14 21:40 UTC
